### ISSUE TITLE
templateUrl issue with Angular 2 templateUrl

### ISSUE THREAD

**Issue by lelehehe** [wallabyjs/public#1009]
### Issue description or question
test cases works fine with karma-jasmine. But they are not executed the same way in wallaby. 
Wallaby Error: 
Location: file: app.component.spec.ts, line 20
Message: This test module uses the component Appcomponent which is using a "templateUrl" ...

Question: 
Is there a simple way wallaby config could import the setting from karma.conf.js and no more such kind of error? 

### Wallaby.js configuration file
https://github.com/lelehehe/quickstart

### Code editor or IDE name and version

Visual Studio Code v1.x
Sublime Text v3

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
I have sent you [the pull request](https://github.com/lelehehe/quickstart/pull/2/files). Because your wallaby config is using system.js format, it needs `__moduleName` instead of `module.id` as [described in this issue](https://github.com/angular/angular/issues/6053). So I have added a preprocessor to handle it.

Karma is working because it uses your default TS compilation option to commonJs, as opposed to system.js like wallaby.js is doing. You may make wallaby to do the same, I have send you [another pull request to demonstrate](https://github.com/lelehehe/quickstart/pull/3) how to do it. Note that in this case you'll also need to do: `npm install electron --save-dev`, because I switched wallaby to [use Chrome/Electron](https://wallabyjs.com/docs/integration/electron.html), otherwise PhantomJs doesn't recognise error stacks from CommonJs based system.js and inline messages will not work.

Hope it makes sense. Both options should work for you.
