### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by martinop** [wallabyjs/public#1011]
### Issue description or question
I get this error when start wallaby.. 
![screenshot_21](https://cloud.githubusercontent.com/assets/10482079/22857697/68b2ba58-f080-11e6-9267-9d01e3871232.png)
Im Using angular CLI

wallaby.js is in the root and wallabyTest inside src. Please help me

### Wallaby.js configuration file

```var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'src/wallabyTest.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
      {test: /\.json$/, loader: 'json-loader'},
      {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
      {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
      {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
      {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
    ]
  }
});

var compilerOptions = require('./src/tsconfig.json').compilerOptions;

module.exports = function (wallaby) {

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code Latest

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the report, I have just updated the [sample repo](https://github.com/wallabyjs/ngCliWebpackSample). Looks like the latest angular-cli beta has commented out [a few polyfills by default](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/polyfills.ts#L22), and PhantomJs (used by default by wallaby) needs them.

I have [updated the wallabyTest.ts file](https://github.com/wallabyjs/ngCliWebpackSample/blob/master/src/wallabyTest.ts) to include the polyfills. If you get the latest version of the file, it should work for you.

Alternatively, you may switch to use the [Chrome/Electron runner in wallaby](https://wallabyjs.com/docs/integration/electron.html), so that wallaby will not need the most of the polyfills (and will work closer to how karma in the generated repo is configured - it uses Chrome).
