### ISSUE TITLE
Using NightmareJS with Wallaby

### ISSUE THREAD

**Issue by bfulop** [wallabyjs/public#1015]
Hello,

I'm testing out [NightmareJS](https://github.com/segmentio/nightmare) with Wallaby, but so far without success.

NightmareJS opens an Electron instance and runs commands on it. I just tried the [examples](https://github.com/segmentio/nightmare#examples) provided in the readme but it doesn't seem to run in Wallaby (`timeout of 2000ms exceeded`).

I've set `env.type: 'node'` 

If I just run the example from Node in the command line, it works fine... Any ideas why Electron doesn't not start up?

**Comment by ArtemGovorov** [comment]
Electron does start up, it's just the NightmareJs example is not very good, because the test is written in a way that doesn't catch/report any errors, also the test is doing a web request, so the default 2000ms timeout of mocha is hit.

First of all, the default timeout needs to be increased. You may either do it in [the `setup` function](https://wallabyjs.com/docs/config/bootstrap.html), 
```javascript
    setup: function (wallaby) {
      wallaby.testFramework.timeout(15000);
    }
```
or for an individual test:
```javascript
describe('test duckduckgo search results', function () {
  it('should find the nightmare github link first', function (done) {
    this.timeout(15000);
    ...

```

Second, you need to improve the test to report errors. One way to re-write the example would be to use mocha's way of handling promises and return the promise from the test (I also added the `catch` because nightmare throws string as opposed to an Error):

```javascript
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test duckduckgo search results', function() {
  it('should find the nightmare github link first', function() {
    var nightmare = Nightmare()
    return nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#zero_click_wrapper .c-info__title a')
      .evaluate(function () {
        return document.querySelector('#zero_click_wrapper .c-info__title a').href
      })
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
      })
      .catch(function (e) {
        throw e instanceof Error ? e : new Error(e);
      })
  });
});
```

Alternatively you may use the async test with `done` callback, but then still need to handle the nightmare promise errors, otherwise they are just lost.

Once you catch the error, you'll see that it's the familiar: 
```
$_$wf is not defined
```
that happens because the function passed to `evaluate` is instrumented by wallaby, but executed in a context of the page loaded by nightmare.

The easiest way to fix it, is to define the function as a string (nightmare is doing `toString` internally fir the function anyway to pass its content across to the Electron). So this should work for you (with a better timeout set in the `setup` function or the test):

```javascript
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test duckduckgo search results', function() {
  it('should find the nightmare github link first', function() {
    var nightmare = Nightmare()
    return nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#zero_click_wrapper .c-info__title a')
      .evaluate(new Function(`
        return document.querySelector('#zero_click_wrapper .c-info__title a').href
      `))
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
      })
      .catch(function (e) {
        throw e instanceof Error ? e : new Error(e);
      })
  });
});
```

**Comment by bfulop** [comment]
Thank you so much for the quick help! (I was suspecting it had to do with the timeout, but got lost somewhere between the settings)

You saved my day!

**Comment by bfulop** [comment]
I followed your instructions and still cannot get it running... 

I'm basing off the simple [NodeJS example](https://github.com/wallabyjs/wallaby-node-iojs-sample/) of the Wallaby repo.

The error I get in the console:

```
​​[Error] Pinging test runner sandbox...​​
​​[Error] The sandbox ping failed: not opened​​
```
 
I've also tried running the NightmareJS example within the `setup` function in the configs to hopefully sidestep the timeout and instrumentation issues. It still hangs, without errors.

I'm using the latest versions of Wallaby (extension and core) with VSCode (normal and insiders). Node v.7.5.0

**Comment by bfulop** [comment]
Here's my wallaby.js file:

```javascript
module.exports = function () {
  return {
    files: [
      'lib/**/*.js'
    ],

    tests: [
      'test/**/*Spec.js'
    ],

    testFramework: 'mocha',

    setup: function (wallaby) {
      global.expect = require('chai').expect
      wallaby.testFramework.timeout(15000)
      wallaby.delayStart()
      var Nightmare = require('nightmare')
      var nightmare = Nightmare()

      nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#zero_click_wrapper .c-info__title a')
      .evaluate(function () {
        return document.querySelector('#zero_click_wrapper .c-info__title a').href
      })
      .end()
      .then(function (result) {
        console.log(result)
        wallaby.start()
      })
      .catch(function (e) {
        wallaby.start()
        throw e instanceof Error ? e : new Error(e)
      })
    },
    // debug: true,
    env: {
      type: 'node'
    }
  }
}
```

**Comment by ArtemGovorov** [comment]
I have it working, but not with the test inside the `setup` function.

I have this config:
```javascript
module.exports = function () {
  return {
    files: [
      'lib/**/*.js'
    ],

    tests: [
      'test/**/*Spec.js'
    ],

    testFramework: 'mocha',

    setup: function (wallaby) {
      wallaby.testFramework.timeout(15000);
    },

    env: {
      type: 'node'
    }
  }
}
```
and this spec file:
```javascript
var Nightmare = require('nightmare');
var expect = require('chai').expect; // jshint ignore:line

describe('test duckduckgo search results', function() {
  it('should find the nightmare github link first', function() {
    var nightmare = Nightmare()
    return nightmare
      .goto('https://duckduckgo.com')
      .type('#search_form_input_homepage', 'github nightmare')
      .click('#search_button_homepage')
      .wait('#zero_click_wrapper .c-info__title a')
      .evaluate(new Function(`
        return document.querySelector('#zero_click_wrapper .c-info__title a').href
      `))
      .end()
      .then(function(link) {
        expect(link).to.equal('https://github.com/segmentio/nightmare');
      })
      .catch(function (e) {
        throw e instanceof Error ? e : new Error(e);
      })
  });
});
```

**Comment by bfulop** [comment]
I've tried your setup on two different Macs and nothing happens. :( 

`$ node example.js` works as expected (Electron window opening, running the tests), but not inside Wallaby.

**Comment by ArtemGovorov** [comment]
I have created the working sample for you here: https://github.com/ArtemGovorov/wallaby-1015. It was working for me in IntelliJ platform IDEs, but apparently you may be using VS Code and when I tried I could reproduce the error. VS Code is passing its own ENV variable `ELECTRON_RUN_AS_NODE` that is breaking Nightmare (because wallaby is juts passing it through). Once I [delete the variable](https://github.com/ArtemGovorov/wallaby-1015/blob/master/wallaby.js#L1), it starts working for me in VS Code as well.

**Comment by bfulop** [comment]
Yes, that was exactly the problem! (running the tests in VS Code)
