### ISSUE TITLE
Run Wallaby when no internet connection

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#102]
When I run Wallaby it tries to check for updates. When I don't have internet connection, or my proxy is misconfigured, it gives me the message
> Cannot download from Wallaby.json

Beside the fact that this message gives me no clue about the actual problem, I cannot continue running Wallaby. There should be at least an 'ignore' button.

**Comment by ArtemGovorov** [comment]
From what I can observe, wallaby.js in most of cases starts up even if it can't check for updates for any reason, including no internet connection. There're only 2 by design cases when it doesn't start if it can't update. 

The first case is when there's no locally installed core. It may happen you install wallaby plugin for the first time in some environment, then run it. At this stage wallaby has to download the latest version of its core, if it can't - it can't start.

The second case is when locally installed core is not compatible with the plugin version. It should not have happened to you (unless you have been playing with some old versions of wallaby and it tried to upgrade them).

Did you hit the first case or there's some other case I'm missing? If latter, could you please describe the steps to reproduce it?

**Comment by fvanwijk** [comment]
I cannot easily reproduce, but it looks like you have to keep update all the time (which requires internet) to stay on the edge and prevent errors like this.
Core version was v1.0.7, but the error was not reproducable on v1.0.12 as expected.

**Comment by larsthorup** [comment]
I am able to reproduce this with the latest version.

I have WebStorm v10.0.4 for Windows and Wallaby plugin v1.0.20.

With internet connection starting Wallaby, it says in the Wallaby console:

    wallaby.js started
    core v1.0.67
    Finished executing 14 affected test(s)

Then disconnecting internet and restarting Wallaby, it says

    wallaby.js started
    core v1.0.67

And in the right corner a wheel is spinning saying "Running tests" forever and nothing happens.

**Comment by ArtemGovorov** [comment]
@larsthorup Does wallaby.js restart (still without internet connection) help?

**Comment by larsthorup** [comment]
@ArtemGovorov No, after restarting, it just hangs again.

**Comment by ArtemGovorov** [comment]
Could you please attach your WebStorm log (can be found by using menu Help - Show Log in Explorer)?

**Comment by larsthorup** [comment]
https://gist.github.com/larsthorup/7c790a1b312a82bc79f1

**Comment by ArtemGovorov** [comment]
@larsthorup Can't reproduce it on 3 different Windows instances I have access to, the issue may be machine configuration specific. What's your Windows version? Do you have any default system proxy settings changed or proxy configured?

**Comment by ArtemGovorov** [comment]
@larsthorup Could you please also set [`debug: true`](http://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) in your wallaby config and paste the output, it should have a bit more information about when exactly it stops/fails to start.

**Comment by larsthorup** [comment]
@ArtemGovorov I have Windows 8.1 and no proxy. The debug output from Wallaby says "Sandbox receiver error": https://gist.github.com/larsthorup/e581739eb50bf29399de

**Comment by ArtemGovorov** [comment]
@larsthorup Thanks, I have tried something to fix it. Could you please try the latest version (core v1.0.69) to see if it works now?

**Comment by larsthorup** [comment]
@ArtemGovorov Sweet! With v1.0.69 it works. Thank you for your fast response :)

**Comment by ArtemGovorov** [comment]
@larsthorup Awesome, thanks for your help!
