### ISSUE TITLE
Recognise app-module-path

### ISSUE THREAD

**Issue by antonydenyer** [wallabyjs/public#1020]
### Issue description or question

We use [app-module-path](https://github.com/patrick-steele-idem/app-module-path-node) in our nodejs application to pull in references for our tests so that we do not have to fully qualify our requires in our unit tests. 

This means that wallabyjs does not pick up changes in files and tests do not run again as they should. 

We specify specHelper.js in our wallabyjs config but I'm guessing it doesn't detect the additional module search paths that have been added. 

### Code editor or IDE name and version
Sublime Text v3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
As you haven't provided your wallaby config, I just took a basic wallaby setup for node, added a specHelper with `app-module-path` call and everything seems to work ok for me. Here's the sample: https://github.com/ArtemGovorov/wallaby-1020. Could you please have a look and share a sample that doesn't work for you?

**Comment by antonydenyer** [comment]
Thanks for taking a look. I wanted to make sure you expected it to work with app-module-path. I've managed to reproduce it with the repo you sent over. 

I've resolved my issue by just requiring in the spec helper in a normal way and everything works as expected.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

The way required the specHelper was imported (from you local folder), the [local folder was passed](https://github.com/ArtemGovorov/wallaby-1020/blob/master/test/specHelper.js#L2) to the `app-module-path`, so instead of using its own cache with instrumented files, wallaby was trying to load you raw local files. 

I have [updated the sample](https://github.com/ArtemGovorov/wallaby-1020/blob/master/wallaby.js#L18) just in case in someone else hits the same issue.
