### ISSUE TITLE
Not rerunning tests when file is deleted

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#103]
It's in the title: when I remove a file (which has errors or failing tests) the tests are not rerunning. I expect Wallaby also to watch files begin added/removed.

**Comment by ArtemGovorov** [comment]
Wallaby is monitoring files being added/removed and when it can it runs the affected tests. 

I was able to reproduce the bug that you have described: when I delete some source file covered by some other test file, the test file tests didn't run and indicators in the test file were not updated. The issue is fixed.

If it was something else and it's still reproducible, please let me know.
