### ISSUE TITLE
Tagging tests and configuring WallabyJS to include/exclude them

### ISSUE THREAD

**Issue by PaddyMann** [wallabyjs/public#1036]
We have some (relatively) slow running integration tests that test that our routes are give or deny access to different users with different permissions.

It's really useful to have WallabyJS test them when we're actively working on them. But when we're not, it's preferable for WallabyJS to skip them to speed things up.

We'd rather not move them to a separate file, so I'm wondering if we can somehow tag our describe() or it() calls and then configure whether we want WallabyJS to include or ignore these.

Is this possible?

**Comment by ArtemGovorov** [comment]
Could you please share your wallaby.js config file?

**Comment by ArtemGovorov** [comment]
It may be possible to suggest something, but I need to understand your environment, hence the question about the config.

**Comment by PaddyMann** [comment]
Understood - sorry for skipping that!

    module.exports = (wallaby) => {
      process.env.NODE_ENV = 'development';
      process.env.MYSQL_ROOT_PASSWORD = '0La$@$l91kK';

      return {
        files: [
          'shared/**/*.js',
          'test/components/**/*.js',
          'test/config/**/*.js',
          'api/v2/test/**/*.js',
          'api/v2/source/**/*.js',
          'api/v2/source/**/*.json',
          '!api/v2/source/**/*.spec.*.js',
        ],
        tests: [
          'api/v2/source/**/*.spec.*.js',
        ],
        compilers: {
          '**/*.js': wallaby.compilers.babel(),
        },
        env: {
          type: 'node',
        },
        bootstrap: (w) => {
          // Tell Wallaby about our app
          const path = require('path'); // eslint-disable-line
          if (global.app) return;
          global.app = require(path.join(process.cwd(), 'api/v2/source/server/server.js')); //eslint-disable-line

          // Fix support for rootrequire
          // This is required as rootrequire creates absolute paths that are broken
          // when Wallaby caches the JS scripts.
          require('rootrequire'); // eslint-disable-line
          require.cache[require.resolve('rootrequire')].exports = w.projectCacheDir + path.sep;
        },
        testFramework: 'mocha',
        slowTestThreshold: 10,
        lowCoverageThreshold: 99, // 70%
        debug: true,

        workers: {
          recycle: true,
        },
      };
    };

**Comment by ArtemGovorov** [comment]
Thanks!
In this case you may use [mocha's tagging feature](https://github.com/mochajs/mocha/wiki/Tagging).

```javascript
    ...
    bootstrap: function (w) {
      var mocha = w.testFramework; 
      mocha.grep('slow'); // or any other name, like supressInWallaby
      ...
    }
```

You may then use the tag in the test names, and the tests with the tag will not run at all:
```javascript
describe('app', function(){
  describe('GET /login', function(){
    it('should respond with the login form', function(){

    })
  })

  describe('GET /download/:file', function(){
    it('should respond with the file @slow', function(){

    })
  })
})
```

(the second test will not run in wallaby)

Let me know if this works for you.

**Comment by PaddyMann** [comment]
Hmm, I think I need to invert the grep(), but still can't get it to work:

Updated config file:

    module.exports = (wallaby) => {
      process.env.NODE_ENV = 'development';

      return {
        files: [
          'shared/**/*.js',
          'test/components/**/*.js',
          'test/config/**/*.js',
          'api/v2/test/**/*.js',
          'api/v2/source/**/*.js',
          'api/v2/source/**/*.json',
          '!api/v2/source/**/*.spec.*.js',
        ],
        tests: [
          'api/v2/source/**/*.spec.*.js',
        ],
        compilers: {
          '**/*.js': wallaby.compilers.babel(),
        },
        env: {
          type: 'node',
        },
        bootstrap: (w) => {
          // Tell Wallaby about our app
          const path = require('path'); // eslint-disable-line
          if (global.app) return;
          global.app = require(path.join(process.cwd(), 'api/v2/source/server/server.js')); //eslint-disable-line

          // Don't run slow tests in Wallaby
          const mocha = w.testFramework;
          mocha.grep('@slow').invert();

          // Fix support for rootrequire
          // This is required as rootrequire creates absolute paths that are broken
          // when Wallaby caches the JS scripts.
          require('rootrequire'); // eslint-disable-line
          require.cache[require.resolve('rootrequire')].exports = w.projectCacheDir + path.sep;
        },
        testFramework: 'mocha',
        slowTestThreshold: 10,
        lowCoverageThreshold: 99, // 70%
        debug: true,

        workers: {
          recycle: true,
        },
      };
    };

Test still running:

    OrganizationProject acls GET /api/organizations/<organizationId>/projects/count @slow denies access to orgAccounts

**Comment by PaddyMann** [comment]
I've tested on the command line and:

   mocha --grep slow --invert

has the desired effect.

So just need to get it working programmatically with Wallaby :)

**Comment by ArtemGovorov** [comment]
Wallaby runs the `bootstrap` function [before each test run](https://wallabyjs.com/docs/config/bootstrap.html), and by default [test runner node process is re-used](https://wallabyjs.com/docs/integration/node.html#node-process-reuse), while mocha instance is re-created for each run, so you need to move 

```javascript
const mocha = w.testFramework;
mocha.grep('@slow').invert();
```
to happen before you do
```javascript
if (global.app) return;
```
otherwise the code initialising mocha grep is only called during the first run, but not for any subsequent runs.

**Comment by PaddyMann** [comment]
Ah OK - that's fixed it. Thanks v much @ArtemGovorov !

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by grantbowering** [comment]
Is there a way to do this with jasmine?
I'd like to be able to have two wallaby configurations, one that runs all of the tests in the spec and one that excludes some of them.  But I want them to be in the same spec files.
The use case is testing components in an angular 5 cli project; I have some tests that bring them up in the angular test bed, and other tests that just create them and run the code directly without angular at all.  The purpose of doing most of them as the latter is for execution speed and clean clarity, while the purpose of having the former as well is making sure the components actually work as expected inside angular.  They're in the same spec.ts files both because they test the same component and because they share some boilerplate.
The problem with executing all of them is not the extra execution time (though that might become annoying as the project grows), but the false-positive test coverage.  If I haven't actually written a test verifying the behavior of an init function, I don't want it to show up as covered in the wallaby app just because it got executed by the angular framework when I instantiated the component...
Any thoughts?
(Sorry to bump an old issue @ArtemGovorov, but it didn't seem worthy of its own entire separate thread :) )

**Comment by ArtemGovorov** [comment]
@grantbowering Yes, we have just published the way to do it in Jasmine as well by using Jasmine's `specFilter`. Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version and you may do the following in your wallaby config:

```diff
    setup: function () {
+     jasmine.getEnv().specFilter = function (spec) {
+       // will only execute tests with "abc" in its name
+       return spec.description && ~spec.description.indexOf('abc');
+     };
      window.__moduleBundler.loadTests();
    },
```
