### ISSUE TITLE
instument:false doens't seem to work on all files

### ISSUE THREAD

**Issue by nibblesnbits** [wallabyjs/public#1043]
### Issue description or question
I'm trying to get Wallaby to ignore a few files in test coverage, but still load them for use in tests.  I have `{instrument: false}` in the definition of the file, but it seems to ignore this.

See [this repo](https://github.com/nibblesnbits/webpack-wallaby) for an example.
### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      { pattern: 'src/**/*.js' },
      { pattern: 'src/**/*.spec.js', ignore: true },
      { pattern: 'src/store/*.js', ignore: true },
      { pattern: 'src/index*.js', ignore: true },
      { pattern: 'src/routes*.js', ignore: true },
      { pattern: 'src/webpack*.js', ignore: true },
      { pattern: 'src/*.prod.js', ignore: true },
      { pattern: 'src/constants/*.js', instrument: false },// <-- this should not be included in coverage
      { pattern: 'src/sagas/rootSaga.js', ignore: true },
      { pattern: 'src/config*', instrument: false }, // <-- this should not be included in coverage
    ],

    tests: [
      { pattern: 'src/**/*.spec.js' },
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        "presets": [
          "latest",
          "react",
          "stage-2",
        ],
      }),
    },

    debug: true,

    setup: function () {
      process.env.NODE_ENV = 'test';
      require('jsdom-global/register');
      require('babel-polyfill');

      ['.css', '.scss', '.png', '.jpg'].forEach(ext => {
        require.extensions[ext] = () => null;
      });
    },
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.9.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

Unless it's an `ignore` flag, wallaby applies setting for patterns from the top of the list and the first match wins. So `{ pattern: 'src/**/*.js' },` entry settings are applied, because everything under `src/constants/*.js` and `src/config*` also matches teh first encountered `src/**/*.js`.

If you move the two patterns to be above the broader pattern, you'll get the expected behavior. However, it may not work for you, because if file is not instrumented by wallaby, then it is not compiled by wallaby either, so you may need to set up a [separate babel preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) for those patterns.

If your goal is just to exclude the files from the code coverage calculation, your better option is to [use another setting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-a-file), designed specifically for these cases.

Let me know if it addresses your question.
