### ISSUE TITLE
Sails.js

### ISSUE THREAD

**Issue by chrisns** [wallabyjs/public#105]
Amazing, don't think I've ever bought software faster - this will make me so much faster (after I've sorted this out)

Hey, anyone had luck getting [Sails](http://sailsjs.org) to work with wallaby? I'm struggling with:

 -  wallaby does some funky stuff with putting the instrumented js somewhere but without the node_modules, but sails deliberately does stuff with the path and require: [here](https://github.com/balderdashy/sails/blob/master/lib/hooks/orm/backwards-compatibility/upgrade-datastore.js#L77) and so cannot find any of the node_module modules
   - maybe a symlink could work? I'm really just looking for the path of least resistance.
 - I also need to give it a different port for every thread - any thoughts on how I can get a random number in a range that doesn't clash with other active threads?
 - how can I do teardown sails between runs?
 - I'm trying to make @bredikhin's [github.com/bredikhin/sailsjs-mocha-testing-barrels-fixtures-example](https://github.com/bredikhin/sailsjs-mocha-testing-barrels-fixtures-example) work which appears to be the best example I could get, I intend to make a pull request once I've figured it all out, so would be nice if I could avoid being too distructive over the code.
- my work in progress is at [github.com/chrisns/sailsjs-mocha-testing-barrels-fixtures-example](https://github.com/chrisns/sailsjs-mocha-testing-barrels-fixtures-example) - though I wouldn't vouch for any of it :)

**Comment by ArtemGovorov** [comment]
Thanks for your support!

I have added a property to `bootstrap` wallaby argument called `localProjectDir` and published the new version.

I have created the [pull request](https://github.com/chrisns/sailsjs-mocha-testing-barrels-fixtures-example/pull/1) to make it work. 
1) Major changes are a couple of tricks to make sails look to the local project folder for node modules and grunt tasks. 
2) For the port number issue I have used [freeport](https://github.com/daaku/nodejs-freeport), added it to dev dependencies in package.json. There may be some other way, but just passing 0 to sails didn't work like it works for a [standard http server](http://stackoverflow.com/questions/30178023/avoiding-eaddrinuse-when-using-wallaby-js-with-an-express-project).
3) Added `if (global.sails) return;` to the `bootstrap` so that once created sails instance is not re-created.

With these changes the tests seem to work. If you encounter any other issues related to the test environment cleanup or issues similar to port numbers, here is a small trick. Wallaby allows you to [configure workers](https://github.com/wallabyjs/public#workers-setting) and if it's not possible to reuse workers or run things in parallel for whatever reason, you may use the following configuration: 
``` JavaScript
    workers: {
      initial: 1, 
      regular: 1,
      recycle: true
    }
```
First 2 settings will make wallaby to use only 1 node process (so there'll be no port issues), and `recycle: true` will make it re-create the node process. With the configuration like this, wallaby will completely dispose your testing environment. It'll not be as fast as with process reusing, but it'll still be much faster than any other ways to run tests, as it'll still only run few tests affected by your code changes.

Let me know if it answers your questions and works for you.

**Comment by chrisns** [comment]
You're incredible, thank you so much - that's way more support than I anticipated! :)
Will test that out later

**Comment by chrisns** [comment]
works a dream, thanks so much!
