### ISSUE TITLE
Support Mocha's 'require' interface

### ISSUE THREAD

**Issue by HowlingEverett** [wallabyjs/public#1059]
Hi,

Our existing test suite is written in Mocha using it's new-ish require interface (http://mochajs.org/#require). This means you import the functions you want rather than relying on globals, e.g.

```javascript
import {describe, it} from 'mocha'

describe('my feature', () => {
  it('should do a thing', () => {})
})

```
### Wallaby.js configuration file

When I try to load the require ui via the setup function, Wallaby tells me it's an unsupported interface. Is there a way to work around this?

```javascript
module.exports = wallaby => ({
  files: [
    'source/**/*.js',
    '!source/**/__tests__/*-test.js'
  ],

  tests: [
    'source/**/__tests__/*-test.js'
  ],

  compilers: {
    '**/*.js': wallaby.compilers.babel()
  },

  env: {
    type: 'node',
    runner: 'node'
  },

  setup: (wallaby) => {
    wallaby.testFramework.ui('require')
  }
})
```

**Comment by ArtemGovorov** [comment]
It's actually an error from mocha, because the `require` interface is not really an interface that can be configured via the `.ui` call. Here's the [list of supported interfaces](https://github.com/mochajs/mocha/blob/master/lib/interfaces/index.js), so when you call `.ui('require')`, [this is hit](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L195). It's a couple of lines later [mocha exports the functions](https://github.com/mochajs/mocha/blob/master/lib/mocha.js#L200).

The reason why it doesn't work for you is that by default wallaby is using its own embedded mocha version. You may just switch to using the one form your node modules, and it should work for you:

```javascript
module.exports = wallaby => ({
  ...
  testFramework: {
      type: 'mocha',
      path: 'mocha'
  }
})
```

Let me know if this works.

**Comment by HowlingEverett** [comment]
That did the trick, thanks :)
