### ISSUE TITLE
JetBrain's no longer showing a diff

### ISSUE THREAD

**Issue by vespertilian** [wallabyjs/public#1081]
### Issue description or question

Yesterday I would get a visual diff for object differences in the JetBrains IDE. After updating the wallaby package this morning I no longer get this. 

![example](https://cloud.githubusercontent.com/assets/441418/24256205/6e3c2ef4-0fdf-11e7-97e6-64a05836cc0e.png)

### Wallaby.js configuration file

Verbose Angular CLI config from your repository

### Code editor or IDE name and version

PhpStorm v2016.3

### OS name and version

Windows 7

**Comment by vespertilian** [comment]
Actually it seem to work with .toEqual just not .toBe after I updated to PhpStorm v2017.1.

Maybe that is the expected behavior, anyway it's one of my favorite features of Wallabyjs, and I thought it worked with both. Please close if .toBe should not show a diff. Thank you.

**Comment by ArtemGovorov** [comment]
It is the expected behavior, we've never displayed the diff for the `.toBe` matcher. The reason is simple: the matcher just compares the values with `===`, so for objects it's just comparing their references. It means even the `expect({}).toBe({})` assertion fails (even though the diff would obviously show that the objects are the same).
