### ISSUE TITLE
__dirname and __filename in NodeJS

### ISSUE THREAD

**Issue by Dviejopomata** [wallabyjs/public#1084]
When developing in Nodejs, **__dirname** and **__filename** variables are pointing to the directory where the extension is instead of the actual file, the path is something like this:
WallabyJs.wallaby-vscode-1.0.46\projects\ba620d153de95c1d\instrumented\test

I would like to be able to determine where the actual script.

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
    return {
        files: [
            'src/**/*.js'
        ],
        tests: [
            'test/**/*.test.js'
        ],
        env: {
            type: 'node'
        }
    };
};
```

## /test/index.test.js
```javascript
describe("bug dirname",()=>{
    it("Should return dirname",()=>{
        console.log(__dirname);
    })
})
```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
It is by design. Wallaby.js copies you files to its own folder, instruments the files, and runs your tests from there, so the actual code being executed does live in the folder you see being reported.

> I would like to be able to determine where the actual script.

If you would like to get the name of your local project folder, there're ways to do it. But could you please tell why do you need to do it, what is your scenario?

**Comment by ArtemGovorov** [comment]
If you need to access any files of your project from your tests, like load some `.json` files or other files, you may just [include them to you `files` list](https://wallabyjs.com/docs/config/files.html). This way these files will be copied over to the wallaby file cache, and you'll be able to access them.
