### ISSUE TITLE
Uncaught TypeError: __webpack_require__.n is not a function

### ISSUE THREAD

**Issue by thuey** [wallabyjs/public#1087]
### Issue description or question
I've been looking into this issue for a while, and I'm at a loss. When I run wallaby, I get the error:
```
Uncaught TypeError: __webpack_require__.n is not a function
```

### Wallaby.js configuration file

`babelConfig` and `webpackConfig` are dynamically generated, so it's a bit difficult to include those. If necessary, though, I can try to piece it together.

```javascript
{
    "files": [
        {
            "pattern": "src/**/*.html",
            "load": false
        },
        {
            "pattern": "src/**/*.js",
            "load": false
        },
        {
            "pattern": "src/**/*.json",
            "load": false
        },
        {
            "pattern": "test/**/*.js",
            "load": false,
            "instrument": false
        },
        {
            "pattern": "src/**/*.test.js",
            "ignore": true
        }
    ],
    "tests": [
        {
            "pattern": "src/**/*.test.js",
            "load": false
        }
    ],
    env: {
      type: 'browser',
      kind: 'electron',
      runner: electron,
    },
    "compilers": {
      '**/*.js': wallaby.compilers.babel(babelConfig),
    },
    setup: function() {
      window.__moduleBundler.loadTests();
    },
    postprocessor: wallabyWebpack(webpackConfig),
    "testFramework": "mocha"
}
```

### Code editor or IDE name and version

Atom v1.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Webpack integration is provided by the `wallaby-webpack` package, and we have added the [support for `__webpack_require__.n`](https://github.com/jeffling/wallaby-webpack/blob/master/index.js#L390) a while ago. 

If you are not using the latest version of the package (1.0.38), please update it. If you are using the latest version, and the issue is still showing up, please create a sample repo where we could reproduce it (hopefully shouldn't be too hard, simple webpack config and your project specific bit of code may be enough to reproduce it).

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. If the issue still valid, please share the info requested above.
