### ISSUE TITLE
Wallaby alters thrown exception when spread operator is used in the arguments?

### ISSUE THREAD

**Issue by mhelvens** [wallabyjs/public#109]
I'm not *exactly* sure what is happening here, but at least it's completely reproducible. Have a look at [graph.es6.js, line 1134](https://github.com/mhelvens/graph.js/blob/wallaby-bug/src/graph.es6.js#L1134) in a special demonstration branch I made on GitHub.

There are two lines of code there (one of them commented out) that should be equivalent. But for the one that uses the spread operator, Wallaby misbehaves. It seems that the thrown exception is altered in some way. This is detected by the test-suite, which analyzes the thrown exception, causing 6 failed tests.

To compare, the Karma test runner works properly for both lines (use `npm test`).

Unfortunately, I failed in my attempt to create a minimal example to reproduce this.

**Comment by ArtemGovorov** [comment]
Thanks for the branch with the error.

After some investigation it turned out to be an issue with polyfill for `Function.prototype.bind` from `node_modules/babel-core/browser-polyfill.js`. It works in Karma because in `karma.common.js` you're also including a separate `node_modules/phantomjs-polyfill/bind-polyfill.js` polyfill for `Function.prototype.bind`. It gets loaded before the babel-core one and it works fine.

if you include the same polyfill in wallaby config it also works. If you comment out the working polyfill from karma config - it stops working and throws some obscure error.

I have also noticed that you are using webpack loader for babel in wallaby. While it should work, I'd recommend using [wallaby preprocessors or compilers instead](https://github.com/jeffling/wallaby-webpack#loaders-vs-preprocessorscompilers), as it's more performant than and out-of-box provides you correct error stacks. This way you'll be able to see error links in the Failing Tests console and Line Tests window) and clearly see any error source right in the editor. 

So instead of:
![screen shot 2015-05-18 at 12 57 03 pm](https://cloud.githubusercontent.com/assets/979966/7673792/9b3535b8-fd5d-11e4-843a-3fb1dcab4bc1.png)

You'll be able to see:
![screen shot 2015-05-18 at 12 58 04 pm](https://cloud.githubusercontent.com/assets/979966/7673796/a757b87a-fd5d-11e4-914a-04c84f8dc384.png)

One last change I'd recommend is avoid instrumenting library files as I'm assuming you don't really need coverage for them.

Below is the configuration for your project with all the above mentioned changes. Please let me know if it works for you.

``` JavaScript
var babel = require('babel');
var wallabyWebpack = require('wallaby-webpack');
var webpack = require('webpack');

var wallabyPostprocessor = wallabyWebpack({
    plugins: [
      new webpack.optimize.OccurenceOrderPlugin()
    ]
  }
);

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false },
      {pattern: 'node_modules/babel-core/browser-polyfill.js', instrument: false },
      {pattern: 'src/**/*.es6.js', load: false},
      {pattern: 'test/helpers.es6.js', load: false}
    ],
    tests: [
      {pattern: 'test/**/*-spec.es6.js', load: false}
    ],
    compilers: {
      '**/*.es6.js': wallaby.compilers.babel({
        babel: babel
      })
    },
    postprocessor: wallabyPostprocessor,
    bootstrap: function () {
      window.__moduleBundler.loadTests()
    }
  };
};
```

BTW, very nice library, good job! I was looking for something like this a while ago for my 2D rogue-like game I was doing in my spare time.

**Comment by mhelvens** [comment]
Heh, stupid mistake. I should have realized that one. Thanks!

Also, thanks for your other suggestions. Good stuff!
