### ISSUE TITLE
How to reduce wallaby config

### ISSUE THREAD

**Issue by alexei-led** [wallabyjs/public#1099]
### Issue description or question

The project I'm working on has multiple folders, with test and code is located together. Is there a way to define one pattern to scan all subfolders in the current directory? something like `./**/*.js`?

p.s.: this type of question is better to ask on channel (Slack or Gitter) than opening a GitHub issue

### Wallaby.js configuration file

```javascript
// paste your config here
'use strict';

module.exports = function () {
    return {
        files: [
            'auth/**/*.js',
            'build-manager/**/*.js',
            'dal/**/*.js',
            'errors/**/*.js',
            'event-bus/**/*.js',
            'events/**/*.js',
            'notifications/**/*.js',
            'queue/**/*.js',
            'safe/**/*.js',
            'server/**/*.js',
            'utils/**/*.js',
            'workflow/**/*.js',
            '!./**/*.e2e.spec.js',
            '!./**/*.unit.spec.js'
        ],

        tests: [
            'auth/**/*.e2e.spec.js',
            'auth/**/*.unit.spec.js',
            'build-manager/**/*.e2e.spec.js',
            'build-manager/**/*.unit.spec.js',
            'server/**/*.e2e.spec.js',
            'server/**/*.unit.spec.js'
        ],

        testFramework: 'mocha',

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: '--harmony',
                env: 'NODE_ENV=test'
            }
        }
    };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.10.2

### OS name and version

OSX

**Comment by ProLoser** [comment]
I would imagine he can't respond to every question immediately, ergo the github issues. Plus it gives public documentation to issue resolution.

You should look into regex and pattern matching, you may be able to do `**/*.(e2e|unit).spec.js` but I don't know patterns too well off the top of my head.

You could have also made your life a little easier by throwing all your stuff into a `src` tree so you would have been able to just do `src/**/*.js` and `**/*.(e2e|unit).spec.js`

This isn't really a problem specific to wallaby however. More about project structure and general tooling configuration.

**Comment by ArtemGovorov** [comment]
> this type of question is better to ask on channel (Slack or Gitter) than opening a GitHub issue

As @ProLoser had mentioned, we are trying to have public documentation to issue resolution, so everyone can easily search and use it. It's a **good question that may help others as well**.

>  Is there a way to define one pattern to scan all subfolders in the current directory?

Wallaby fully supports glob patterns, so you may include all and then exclude few things, like `node_modules`:
```javascript
return {
   files: [
     '**/!(*.spec).js', // all but specs
     '!node_modules/**'
   ],
   tests: [
      '**/*.(e2e|unit).spec.js', // specs only
      '!node_modules/**'
   ]
...
```

However, I wouldn't recommend doing it for the [reasons described here](https://github.com/wallabyjs/public/issues/1097#issuecomment-291067527) plus possibly a bit worse startup time (for the same reasons). Also, because wallaby copies the listed files to its local cache, specifying such greedy patterns (and forgetting to exclude things) may lead to copying stuff that you don't really need.

So I would rather follow the suggestion from @ProLoser and put everything into an `src`-like folder, and then would do:

```javascript
    return {
        files: [
            'src/**/*.js',
            '!src/**/*.(e2e|unit).spec.js'
        ],

        tests: [
            'src/**/*.(e2e|unit).spec.js'
        ],
```

Also, given that wallaby config is just a node program, there's also the third solution to make it more compact:

```javascript
module.exports = function () {
    // folders can be listed or you may even read them from fs
    var folders = ['auth', 'build-manager', ...];
    return {
        files: folders.map(f => f + '/**/!(*.spec).js'), // all but specs
        tests: folders.map(f => f + '/**/*.(e2e|unit).spec.js'), // specs only
...

```
