### ISSUE TITLE
Node.js support

### ISSUE THREAD

**Issue by Pencroff** [wallabyjs/public#11]
Hi, I have tried to use this plugin for NodeJs project on webstorm.
But faced issue with `require` in my tests.
Message "ReferenceError: Can't find variable: require".
I use require for connecting `chai` and dependencies for test entity in my spec files.
```
var expect = require('chai').expect,
      path = require('path');
```
Also I need `require` for my internal behavior in test entity, something like
```
var path = require('path');
 // Using path in my logic
```
I saw in example configuration files, you suggest to list all dependencies in file section. This approach required change all exist tests and not compatible with any file that use require for loading dependencies.

Could you suggest solution for this issue?

**Comment by ArtemGovorov** [comment]
Hi, node.js and io.js support is not yet implemented, only browser based Mocha tests supported at the moment. Node support is in progress and will be available relatively soon.

For node you will not have to list files in order, just will need to specify a pattern/folder where your source files are, because as you've correctly said - we don't need ordered files lists in case of CommonJs with require.

**Comment by tomByrer** [comment]
Hopefully an [Atom editor](https://atom.io/) plugin will follow io.js support ;)

**Comment by wojciak** [comment]
+1 for the node support, do you have an ETA on it? :)

P.s. awesome plugin! :)

**Comment by ArtemGovorov** [comment]
Yes, node.js/io.js support is going to be released on Monday next week.

**Comment by wojciak** [comment]
Awesome!

**Comment by ArtemGovorov** [comment]
http://dm.gl/2015/02/23/wallaby-version-one/
