### ISSUE TITLE
importing mongoose causes "long running code". Repro repo inside.

### ISSUE THREAD

**Issue by lgandecki** [wallabyjs/public#1114]
### Issue description or question
clone this:

https://github.com/lgandecki/wallabyMongooseFreeze

npm install -> try running wallabyjs -> "Some long running code has been detected: one of your files is 
taking more than 5000ms to execute." 

error. Tests don't run.

requiring/importing mongoose is enough to cause this. Tests run just fine with jest. (and the test that imports .js file that imports mongoose runs 6 ms)

Please help :) It would be fantastic to have this working.

### Wallaby.js configuration file
```javascript
module.exports = function () {

    return {
        files: ['index.js'],

        tests: ['index.test.js'],

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest'
    };
};
```
### Code editor or IDE name and version

WebStorm 2016.3

### OS name and version

OSX

**Comment by lgandecki** [comment]
Setting the testFramework to mocha helps. But I do use jest in my original app..

**Comment by ArtemGovorov** [comment]
Thanks for the repo. After some investigation I have found out that [one of the modules](https://github.com/christkv/require_optional/blob/master/index.js#L12) used by other modules used by mongoose, falls into an infinite loop, because it can't find `package.json` file.

It works with mocha because unlike jest, mocha doesn't fake the main/root module.
It works with jest cli, because the working directory is your project dir in this case and there's a `package.json` file in the folder. Even though the file is irrelevant in this case, it prevents the infinite loop.
In case of running jest with wallaby, wallaby runs tests from its own local file cache (and the `package.json file` is not there). Fortunately, as [specified in docs](https://wallabyjs.com/docs/config/files.html), you may just add the required file to your `files` list and everything will work:

```javascript
module.exports = function () {

    return {
        files: ['index.js', 'package.json'], // <--

        tests: ['index.test.js'],

        env: {
            type: 'node',
            runner: 'node'
        },

        testFramework: 'jest'
    };
};
```

We'll also implement adding the file to the `files` list automatically for jest in the next wallaby version. But for now adding it to your files list should do the trick.

Let me know if this helped.

**Comment by lgandecki** [comment]
Works, thanks a lot! This premium support is the reason why it's worth paying for the plugin :) 
Keep up great work!
