### ISSUE TITLE
Set NODE_PATH env variable for Jest

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#1118]
### Issue description or question

I'm trying to set up Wallaby to use it in [Next.js](https://github.com/zeit/next.js) but I'm having trouble getting the right config file to match the project.

As you can see in the project's `package.json` file **Jest** is being run with [`NODE_PATH=test/bin`](https://github.com/zeit/next.js/blob/master/package.json#L26) but I haven't be able to make it work with the current config or using `projectCacheDir`.

PD: I also had to change some files to make the test run against the source code instead of the compile code like in the case of [`shallow-equals.test.js`](https://github.com/zeit/next.js/blob/master/test/unit/shallow-equal.test.js#L3) but I think that is solve and is now working.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'server/**/*.js',
      'test/isolated/**/*.js',
      'test/isolated/**/*.json',
      '!test/isolated/**/*.test.js',
      'test/integration/**/*.js',
      'test/integration/**/*.json',
      '!test/integration/**/*.test.js',
      'client/**/*.js',
      'lib/**/*.js',
    ],

    tests: [
      'test/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_PATH=test/lib'
      }
    },

    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

WebStorm 2017.1

### OS name and version

OSX 10.12.3

**Comment by ArtemGovorov** [comment]
The issue is simple - `test/lib`, as well as `dist/**` are not in your `files` list, and it is exactly what the error is saying. You may inspect wallaby cache (to see what files are copied to it) like [described here](https://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page).

After adding the folders (and cleaning up file paths), this config works for me:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'server/**/*.js',
      'client/**/*.js',
      'lib/**/*.js',
      'dist/**/*.js',
      'test/**/*.*',
      '!test/**/*.test.js',
    ],

    tests: [
      'test/**/*.test.js',
      '!test/integration/**/*.test.js'
    ],

    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'NODE_PATH=test/lib'
      }
    },

    testFramework: 'jest'
  }
}
```

Note that I have excluded integration tests. The tests, as you can by running jest CLI, open up a browser window via Chrome driver and take >1minute to execute. As you know, wallaby is great for fast unit tests, but if you'll be running those integration tests on each key stroke like wallaby does - I don't think it makes much sense.

If you still want to include them, then you'll need to do the [similar pre-test thing `npm run test` does](https://github.com/zeit/next.js/blob/master/package.json#L25) and spin up and close `chromedriver ` [like `fly` pre/post test are doing](https://github.com/zeit/next.js/blob/master/flyfile.js#L64) in [wallaby's `setup`/`teardown` respectively](https://wallabyjs.com/docs/config/bootstrap.html). But as I said, I don't think these very long running integration tests are a good fit for the wallaby driven workflow.

**Comment by davegomez** [comment]
Thank you as always Artem
