### ISSUE TITLE
Webpack, Typescript and Jest

### ISSUE THREAD

**Issue by dweber019** [wallabyjs/public#1121]
### Issue description (Support)
I'm building a new boilerplate for webpack, typescript and jest but I have a hard time with wallaby.
Here my setup: https://github.com/w3tecch/aurelia-typescript-boilerplate/tree/feature/new-skeleton-backport

I also tried to enable with webpack plugin but no success.

Currently I have no errors but no tests are run:
```
0 failing tests, 0 passing​​​​​
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    // set `load: false` to all source files and tests processed by webpack
    // (except external files),
    // as they should not be loaded in browser,
    // their wrapped versions will be loaded instead
    files: [
      { pattern: 'src/app/**/*.ts', load: false }
    ],

    tests: [
      { pattern: 'test/jest-unit/**/*.test.ts', load: false }
    ],

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        typescript: require('typescript')
      })
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest',

    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.11

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
The issue is that you have the `load: false` attribute set for your `tests`, so wallaby doesn't load them. The attribute is required when you are [using wallaby with webpack](https://wallabyjs.com/docs/integration/webpack.html) (because tests are loaded later in the `setup` function).

Your config however doesn't use webpack at all, and it shouldn't anyway, because you are using jest and jest runs in node environment, and webpack is simply not required to run your tests. Moreover, wallaby doesn't even support webpack with node tests.

I have sent you [the pull request](https://github.com/w3tecch/aurelia-typescript-boilerplate/pull/3) to make it work.

**Comment by dweber019** [comment]
You are awesome! Thx
