### ISSUE TITLE
Assertion error when starting wallaby

### ISSUE THREAD

**Issue by kristojorg** [wallabyjs/public#1124]
### Issue description or question

When I start wallaby I am sometimes given an error:

```
​​[Error] Runtime error: Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1591.​​
```

This appears to happen when there is also some syntax or other error in my code.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.test.js',
      { pattern: '.env', instrument: false },
    ],

    tests: ['__tests__/**/*.test.js', 'src/**/*.test.js'],

    env: {
      type: 'node',
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    workers: {
      recycle: true,
    },
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.11.2

### OS name and version

OSX 10.12.3

**Comment by ArtemGovorov** [comment]
The issue doesn't seem to be wallaby specific. It actually may not even be specific to your tests, but may also come up in your app at some point.

[According to this](https://github.com/nodejs/node/issues/8258), it happens when there's memory corruption in node because of some native modules that you may be using (wallaby itself doesn't use any native modules).

I'd suggest trying to exclude some native modules in question, and see it it helps. If it does, then I'd perhaps report the issue to that module repo.

**Comment by kristojorg** [comment]
Thank you, sorry for the misplaced issue

**Comment by ArtemGovorov** [comment]
No worries at all, please let me know if you find the module that is causing the issue, I'm interested to know what it was.

**Comment by kristojorg** [comment]
It ended up being related to a deasync library being called in `massive` js module for postgres database querying. :sad: I just want an easy node database
