### ISSUE TITLE
Jest | Wallaby Performance

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#1133]
This is a question about what would be the best way of writing test case for Jest and Wallaby in terms of performance and readability.

Many time you can find yourself writing repetitive test in order to test several cases but these tests can sometime be expressed in a more succinct way. I wonder how the way we write those test can affect the performance of Jest and specially Wallaby?

Unit tests for `add()`:
```javascript
test('Add numbers', () => {
  expect(add(1, 2).toBe(3))
  expect(add(2, 3).toBe(5))
  expect(add(3, 4).toBe(7))
})
```

Unit tests for `add()` using an array of values:
```javascript
const cases = [
  [1, 2, 3],
  [2, 3, 5],
  [3, 4, 7]
]

test('Add numbers', () => {
  cases.map(case => expect(add(case[0], case[1]).toBe(case[2])))
})
```

**Comment by ArtemGovorov** [comment]
In your particular example the performance will not be visibly affected, even if the number of test cases was a magnitude higher.

Many tests may look like they may be expressed in a more succinct way, and it may be quite tempting to refactor them. And it may seem like a good approach, as long as the tests **pass**. 

My personal approach is to always check whether a test parametrization/generalization doesn't obscure the test results when it **fails**. Because spending more time to understand what went wrong, often outweights many benefits of having more compact tests.

So it really depends on a particular approach. Say in your case you refactor the `add` function and one of test cases, say `add(2, 3)`, starts failing, because the test case need to be changed. With your first way (explicit expect statements), you immediately see the line that is failing. With your second approach, you may spend a bit more time finding the actual test case and fixing it.

Overall, this particular example of yours should probably be fine with both approaches. However in other cases I'd still recommend checking if refactoring a test doesn't obscure the output much when it's failing.
