### ISSUE TITLE
Status indicator keeps spinning forever

### ISSUE THREAD

**Issue by FlippieCoetser** [wallabyjs/public#1135]
### Issue description or question
When starting wallaby the status indicator keeps spinning forever.
Running `gulp test` works just fine.
Code base was not touched and wallaby was working just fine.

### Error log
![image](https://cloud.githubusercontent.com/assets/3672126/25553868/76b216e6-2cbf-11e7-90a0-c7fb4814ebdb.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'source/entities/*.ts'
    ],
    tests: [
      'test/*.test.ts'
    ],
    testFramework: 'mocha',
    env: {
        type: 'node'
    },
    debug: true
  };
};
```

### Code editor or IDE name and version
Visual Studio Code v1.11.2

### OS name and version
Windows 10 Enterprise v10.0.14393 Build 14393

**Comment by ArtemGovorov** [comment]
What is your node.js version? Did you update it recently?

**Comment by ArtemGovorov** [comment]
Never mind, we were able to track the issue from the provided stack trace. The fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). The issue is related to one of the npm package that you must have installed/updated recently (it conflicts with one of the packages used by wallaby.js).

**Comment by FlippieCoetser** [comment]
@ArtemGovorov thanks, I can confirm problem resolved after updating.
