### ISSUE TITLE
feature request: display results from a single test (or few selected tests)

### ISSUE THREAD

**Issue by faceyspacey** [wallabyjs/public#1156]
## Use Case
Say you're examining the logs of functions run by many tests (in your editor). You won't know which logs correspond to the test your focused on ***if the called function is run many times***. So then you change a test file to run only one test (e.g. `it.only`), but then a bunch of other files are still being run. That doesn't solve it. In general, even rewriting `it.only` *temporarily* is not ideal. 

## Proposal
Like in music or video editing software, the webpanel has a checkbox to "solo" a given test or group of tests.

The *common user experience* for most apps (unrelated to tests) is a checkbox to toggle on/off each individual item, but I think the utility in this case is perhaps more about "soloing." Having to do all the *development work* to provide features to complete this thought now includes *uncheck/checkall*, which is unnecessary. And in terms of developer experience, it's more work without a real purpose.

That said, in a second iteration, the complete manifestation of this feature includes `check all / uncheck all` buttons, which simplifies the *"common user experience"* I just mentioned. And this would be on the basis that there was additional "purpose," such as doing this actually updates your code so that CI also would benefit from these actions and these actions aren't limited to Wallaby. Updating tests from Wallaby is a stretch, it's just an example of a some purpose/utility the *common user experience* could provide. To start the feature is simply: **"soloing"**.

**Comment by breathe** [comment]
I'd be even happier with a text field in the web-page that lets you filter the tests to run/view ala the file/test name regex's filters in jest (--testPathPattern and --testNamePattern)

**Comment by ArtemGovorov** [comment]
Hey everyone, thanks for your feedback on the feature!

Focusing on a single test (or few tests) is something that we have been thinking to add for a while. 

The feature could be useful not just from the wallaby app, but from the editor as well (see https://github.com/wallabyjs/public/issues/465).

How does the following user experience sound to you:

- Wallaby App Tests tab will have a text field at the top that one would use to filter the tree by entering a (part of the) test name. The resulting filtered tree will only display tests (within their tree parents) that name satisfies the entered text.
- The tests tree leaf nodes (tests) and root nodes (test files), regardless of whether the tree is filtered or not, will have a checkbox next to them that will allow to focus on selected/checked test(s)/test file(s). The tree will have an option to check/uncheck all currently displayed nodes.
- Editor integrations will have a new `Focus` (on a test/test file) command, that will be possible to run while having a cursor inside a particular test/test file. Running the command will have the exact same effect as selecting/checking a test/test file in the wallaby app.
- When a test (or few tests/test file) is selected to focus on, either from wallaby app or an editor, wallaby.js will immediately display only the focused test(s) results in wallaby app and editor. The results include: errors, logs, code coverage. So if a test is focused, wallaby app and editor results will look like only this test exists and ran, no results from other tests will be displayed.
- After focusing on a test(s), a user may keep editing any code or any tests, including the focused one(s). Wallaby will be running all tests affected by the change, but only displaying the results for focused test(s) in the app and editor.
- To remove focus from a test(s), a user may just clear the selection (uncheck all) in the tests tree in the wallaby app. A command to remove focus from all currently focused tests will be added to editors as well.

Let me know what you think.

**Comment by mattapperson** [comment]
if we could add a UI aspect to editors that support it it would be great! Something along the lines of adding a breakpoint in the gutter to the first line of the test

**Comment by breathe** [comment]
This sounds really really awesome!!  I can't wait!

**Comment by faceyspacey** [comment]
Looks like you've thought of everything!

My only concern is this one:
> After focusing on a test(s), a user may keep editing any code or any tests, including the focused one(s). Wallaby will be running **all tests** affected by the change, but only displaying the results for focused test(s) in the app and editor.

Part of the benefit of these features is supposed to be faster test running. So if you're editing code that touches many different tests, then it will be slower. Of course if you're just changing the test code itself, it won't make a difference. 

Wallaby can get slow sometimes. I've yet to come up with any hypothesis why, other than it's simply a lot of work when you have a lot of tests. Async tests seem to be a cause too, even if they're supposed to be mocked 1 tick async tests.

Anyway, perhaps an option in the config is all that's needed to toggle on whether non-focused tests are re-run as well. Though UI settings in the web app is always preferably. It might be nice to start to see a Settings page there.

**Comment by bruderstein** [comment]
Sounds really good. I'd add that showing only the coverage for the focused test is the key feature here. I've hacked around not having this using `it.only` etc and seeing the paths a particular test follows in the code has helped me find issues on many occasions.

Running more than one test within a test file is only possible via the web app, correct?

Really looking forward to this feature!

**Comment by ArtemGovorov** [comment]
Thanks for your feedback!

@mattapperson 

> if we could add a UI aspect to editors that support it it would be great!

It may be tricky, but we'll see what we can do.

@faceyspacey 

> Anyway, perhaps an option in the config is all that's needed to toggle on whether non-focused tests are re-run as well. Though UI settings in the web app is always preferable. It might be nice to start to see a Settings page there.

The issue with not running other tests (if required by the code changes) and only running focused ones, is that when the focus is removed and you need to see all test results, wallaby will need to run ALL tests, because there's no guarantee that the changes didn't break some of them (and there's no way to reduce the set of tests to re-run because wallaby was "blind" in terms of tracking the dependencies by not running the affected tests).

> Wallaby can get slow sometimes. I've yet to come up with any hypothesis why, other than it's simply a lot of work when you have a lot of tests. Async tests seem to be a cause too, even if they're supposed to be mocked 1 tick async tests.

If you find some case like this please share a reproducible repo, I'm happy to have a look and investigate.

@bruderstein

> Running more than one test within a test file is only possible via the web app, correct?

We may allow focusing multiple tests from an editor by invoking the `Focus` command multiple times on different tests.

**Comment by faceyspacey** [comment]
makes sense. just wanted to point out the the "run all" tests thing.

**Comment by bruderstein** [comment]
> The issue with not running other tests (if required by the code changes) and only running focused ones, is that when the focus is removed and you need to see all test results, wallaby will need to run ALL tests, because there's no guarantee that the changes didn't break some of them (and there's no way to reduce the set of tests to re-run because wallaby was "blind" in terms of tracking the dependencies by not running the affected tests).

I'd accept that performance hit any day to not have the other tests run when it's focused. For any of the projects I work on, that would be a no-brainer trade off. (Just to give some real world usage info 😀)

**Comment by breathe** [comment]
I had similar thoughts regarding the "run all tests even non-focused behavior".  I can see both sides.

What worries me is feedback speed/console debugging focus when  tracking down flaky tests or test timeouts -- say you make a code change that causes a large number of async tests to timeout.  In that case you end up wanting to watch incremental output from the debug console during a specific test execution.  Is it easy to see the relevant info in the debug console output?  Is the developer sure they aren't waiting on other tests to timeout before they can see the feedback they are looking for ..?

**Comment by chrisblossom** [comment]
I'm very happy this feature is moving forward.

@ArtemGovorov Is there a reason this could not be controlled via test frameworks already supported ``.only`` test flag? As a vim user, I would greatly prefer not having to use my mouse to focus a test, or alt tab to an external UI.

**Comment by ArtemGovorov** [comment]
@chrisblossom Editors will have a command to focus a test, so it'll be possible to focus a test with one keyboard shortcut.

**Comment by chrisblossom** [comment]
@ArtemGovorov I understand yet another shortcut could be learned / set. I am trying to understand why wallaby would reinvent the wheel here and not use the exact format all test engines currently use. Less things to learn for new/existing users and things would work as one would expect they do along with current test frameworks- it would just work as expected.

Unless I am missing something here?

**Comment by ArtemGovorov** [comment]
@chrisblossom 

`.only` makes a test engine to run the marked test only (no matter what code or tests you are editing). The issue with this approach is described here https://github.com/wallabyjs/public/issues/1156#issuecomment-321176114:

> The issue with not running other tests (if required by the code changes) and only running focused ones, is that when the focus is removed and you need to see all test results, wallaby will need to run ALL tests, because there's no guarantee that the changes didn't break some of them (and there's no way to reduce the set of tests to re-run because wallaby was "blind" in terms of tracking the dependencies by not running the affected tests).

So if you mark a test with `.only`, edit some code, remove the `.only`, wallaby will have to run ALL of your tests (because your code changes may have affected other tests).

With the approach when you mark tests with wallaby command, we will be able to display the results in a way like only the marked test is running, but to also incrementally run other affected tests behind the scenes, so that when you unmark the test, we can display the full results instantly, without having to run ALL tests.

As discussed above, some users seem to be ok with the penalty of running ALL tests after removing the focus from a single test, so we're considering to implement both ways - with running affected tests and without running affected tests while one test is focussed (but with running all tests when it is unfocussed). 

So we may enable using `.only` as an additional way to focus a test (as a part of the second approach implementation). But even then, there are enough reasons to re-invent the wheel and provide the originally suggested way to focus tests:
- `.only` requires your tests code modification, so wallaby app users will not be able to use it.
- I think it is subjective what's easier: type `.only` or press: [`Alt+Enter`, `f`, `Enter` in WebStorm for example] (or any other custom shortcut).

**Comment by chrisblossom** [comment]
Thank you for the detailed explanation! I can definitely see how the perceived quickness would increase.

I don't necessarily think typing ``.only`` is easier than pressing a shortcut, but I do think it is easier not having to set a custom shortcut for multiple editors- and remembering each one. Also not having to dig through Wallaby docs to find this feature is a plus.

**Comment by breathe** [comment]
>> The issue with not running other tests (if required by the code changes) and only running focused ones, is that when the focus is removed and you need to see all test results, wallaby will need to run ALL tests, because there's no guarantee that the changes didn't break some of them (and there's no way to reduce the set of tests to re-run because wallaby was "blind" in terms of tracking the dependencies by not running the affected tests).

>I'd accept that performance hit any day to not have the other tests run when it's focused. For any of the projects I work on, that would be a no-brainer trade off. (Just to give some real world usage info 😀)

I've thought more about this and I would _really_ like the option to control whether wallaby executes non-selected tests -- or if controlling this behavior is too complex - I would choose for test subsetting to run only the tests in the subset and no tests not in the subset (rather than making it this behavior affect the view only) 

Wallaby really shines with quick-running unit-style tests -- however its also pretty nice with longish running tests.  The issue with long running tests comes when you have too many long-running tests -- it starts to take too long to get feedback.  However if you only run a few of the longer-running tests - the 'less instant but still near instant' feedback workflow that wallaby gives you is still really nice even if its not providing feedback derived from the entire test-suite.

My test suite consists of lots of quick tests and some (growing number) of longer-running tests.  My ideal workflow would let me quickly:

(1) exclude all the slower running tests when I want a fast feedback cycle from the unit tests -- (means I would need a way to define groups of tests for later reuse?  I would be completely fine with defining/maintaining such groups in the wallaby config file if it were possible ... )
(2) run all the tests (which may take too long to be the default mode) but still allows me to use wallaby to manage updating of snapshots for the whole suite
(3) execute specific ad-hoc test subsets to help maintain focus and reduce the mental energy required to navigate and process the test results.  Would also support a nice workflow when working on/debugging slower running tests

**Comment by lgandecki** [comment]
@ArtemGovorov Any update? This would be a great to have. Currently I change my wallabyjs config when I want to track a single file/test but it requires me to reload the whole wallabyjs, and to figure out paths etc.

**Comment by ArtemGovorov** [comment]
@lgandecki No updates to share yet, but we will get there.

**Comment by ArtemGovorov** [comment]
Happy to announce that the [feature is now implemented](https://wallabyjs.com/docs/intro/selected-tests.html). After listening to your feedback, we have decided to avoid adding any new UI elements to use it, and instead utilize existing features of testing frameworks that allow to focus specific test(s). Now, using `.only` works as you'd expect and simply mutes other test files (even in testing frameworks with parallel spec runs, such as Jest).

**Comment by chrisblossom** [comment]
@ArtemGovorov thank you and your team! This will help so much!

**Comment by DJTB** [comment]
No more constantly editing wallaby config `tests` array !
:champagne:

**Comment by faceyspacey** [comment]
Thanks @ArtemGovorov !

**Comment by lgandecki** [comment]
@ArtemGovorov would it be too much work to, similarly to what you did with 
// file.only
and 
//file.skip

do // test.only and //test.skip ? 

For the first use case - I want to focus development with one (or a handful tests), but I want jest to run in the background and constantly check ALL tests.
For the second usecase - I want to be able to add integration tests (such as - calling real external API), that i DO NOT want to run on a keystroke, but on file save - relatively fine :) 
The second one is less important for me - as I can move them to separate files now and do //file.skip.

But the first usecase would give a huge boost to my workflow :)

**Comment by ArtemGovorov** [comment]
> // test.only and //test.skip

You may already do it by using `it.only`/`describe.only` and `it.skip`/`describe.skip`, or am I missing something?

**Comment by lgandecki** [comment]
File.only and file.skip are wallabyjs specific and jest ignores them.
I would like the same functionality for test level granularity as well. 
Does my explanation for usecases not make sense? Currently if I skip with wallaby I skip with jest as well. But I want jest to work in the background the way it would normally (and test everything, catching problems I wouldn’t think of) but focus wallaby on one test at a time - which is what wallabyjs is best at.

**Comment by ArtemGovorov** [comment]
@lgandecki Got it. We'll look into it, but it's a more complex beast than the `file.*`. `file.only`/`file.skip` are easy to detect can be anywhere in the file, while for something like `test.only`/`test.skip` we'll need to figure out selected test name (that can be generated dynamically or use a variable as a name) via static analysis prior to running any tests (while `it.only`/`it.skip` are executed run time).

**Comment by NikGovorov** [comment]
Hi All,

We improved the scenario of focusing a single test by adding new [Test Filtering](https://bit.ly/2CyP32d) feature. 

We would love to hear your feedback!

**Comment by lgandecki** [comment]
Looks great!
