### ISSUE TITLE
Wallabyjs configuration with Featherjs

### ISSUE THREAD

**Issue by phamduongnhatnam** [wallabyjs/public#1162]
### Issue description or question
Hi, I need a working config for the FeatherJS project, I tried but there is some error.

### Wallaby.js configuration file
Please make a fork from here: https://github.com/phamduongnhatnam/featherjs-wallabyjs

```javascript
module.exports = function () {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*test.js'
    ],

    setup: function () {
        var chai = require('chai');
        var chaiAsPromise = require('chai-as-promised');
        chai.use(chaiAsPromise);
        global.expect = chai.expect;
        global.assert = chai.assert;
    },

    env: {
      type: 'node',
      runner: 'node'
    }
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.12.1

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
If you open the error line and `console.log(app.get('public'))`, you'll see that it returns `undefined`.  It's expected because you haven't include the `public` folder to your `files` list as [wallaby.js requires](https://wallabyjs.com/docs/config/files.html). The next error after you fix this one will point you to the missing configuration, and it happens because the `config/` folder files are also not included. 

I have sent you the [PR to make the config work](https://github.com/phamduongnhatnam/featherjs-wallabyjs/pull/1).

**Comment by phamduongnhatnam** [comment]
Thanks @ArtemGovorov, got it works. I just forgot this rule of the config file.
