### ISSUE TITLE
Can't get Wallaby JS working in Aurelia/TypeScript/Webpack skeleton

### ISSUE THREAD

**Issue by massimocode** [wallabyjs/public#1167]
It would be awesome if someone could do a PR to get WallabyJS working on this example Aurelia skeleton project. https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript-webpack

I'm an experienced Wallaby user (used in on all sorts of projects) and have spent hours and hours trying to get this working but no luck so far.

**Comment by ArtemGovorov** [comment]
I'm not sure what exact issues you've had encountered, but because the skeleton project is [using Jest](https://github.com/aurelia/skeleton-navigation/blob/master/skeleton-typescript-webpack/package.json#L19) as a testing framework and [wallaby fully supports Jest](https://wallabyjs.com/docs/integration/jest.html), I have just copied the config from the docs as is and after adjusting files paths and add TS compiler setting for modules, everything is working with a simple config like this:

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.ts',
      'src/**/*.html',
      'test/unit/**/__snapshots__/*.snap',
      'tsconfig.json'
    ],

    tests: [
      'test/unit/**/*.spec.ts'
    ],

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' })
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```
