### ISSUE TITLE
Wallaby not working with jest and async test

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#1175]
### Issue description or question

I've setup wallaby to execute my Jest tests in this repo:
https://github.com/KnisterPeter/tscodeshift

But for some reason (there is no good error message) the wallaby start fails with a timeout.
```
[Error] Some long running code has been detected: test "undefined" is taking more than 5000ms to execute.​​
​​[Error] Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error] and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error] Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.​​
​​[Error] Pinging test runner sandbox...​​
​​[Error] The sandbox ping failed: not opened​​
```

The error only happens when I have an await statement in my test code.
On the CLI the jest tests run successful.

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.ts',
      '!src/**/*.test.ts',
      'tsconfig.json'
    ],
    tests: [
      'src/**/*.test.ts'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest',
    setup: function(wallaby) {
      const jest = require('./package.json').jest;
      delete jest.transform;
      wallaby.testFramework.configure(jest);
    },
    debug: false
  };
}
```

### Code editor or IDE name and version

Visual Studio Code v1.12.2

### OS name and version

Linux

**Comment by ArtemGovorov** [comment]
The issue is not in async code, the issue is that [you are killing test runner process](https://github.com/KnisterPeter/tscodeshift/blob/17856c545d7900b6ca5f5b117567fb9ecc4407db/src/index.ts#L56) before it is able to report any results.

I have [sent you the PR](https://github.com/KnisterPeter/tscodeshift/pull/7) to make it work.

**Comment by KnisterPeter** [comment]
Thanks. Awesome

**Comment by mmcgee-aya** [comment]
Can we paste the fix in here, the PR was archived

**Comment by smcenlly** [comment]
The PR is still working for me (weird). Please see the diff below:

```diff
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.ts',
      '!src/**/*.test.ts',
      'tsconfig.json'
    ],
    tests: [
      'src/**/*.test.ts'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest',
    setup: function(wallaby) {
+     process.exit = function () {  };
      const jest = require('./package.json').jest;
      delete jest.transform;
      wallaby.testFramework.configure(jest);
    },
    debug: false
  };
}
```

---

Please note that this issue is 5 years old and we have made significant changes to our `jest` integreation during that time.  If you're having problems with Jest and Asynchronous tests, I expect it to be different to this issue and the fix suggested almost certainly doesn't apply.

Please make sure that you are using Wallaby's [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) to run your `jest` tests. If you're having problems after doing that, please [create a new issue](https://github.com/wallabyjs/public/issues/new/choose) and provide your Wallaby Diagnostics report (instructions for generating the report are in the issue template).
