### ISSUE TITLE
Private repo / Typescript/ ​​Error: Cannot find module

### ISSUE THREAD

**Issue by Artur-A** [wallabyjs/public#1178]
### Issue description or question
`​​Error: Cannot find module 'my.core/Name'​​`

There is a problem with symlinked private repos and typescript.
Having a project structure:
```
|--projectA
|--projectB
|----node_modules
|------projectA (npm link)
```
Running tests inside projectA works without a problem. Tests in projectB referencing projectA fail to run.
<img width="968" alt="wallaby_promblem" src="https://cloud.githubusercontent.com/assets/6156012/26640609/e7b46512-4630-11e7-9049-e5443c4b4b99.png">

Similar project with manual mocha testing also works (via `ts-node`).

##### NPM
I am using NPM 5 (@latest) that provides automatic linking for local projects. Just run `npm install` without manual npm link.

### Wallaby.js configuration file
The simplified project is available at https://github.com/Artur-A/wallaby-problem-symlink-ts
```
npm install
cd lib/my.core && npm install
cd ../my.domain && npm install
```
then start Wallaby

### Environment
Visual Studio Code v1.12.2
Typescript v. 2.3.3
NodeJS 7.9.0 (backend testing) + Mocha
Wallaby: latest
OSX Sierra 10.12.5

### What is tried
- `process.env.NODE_PATH += path.delimiter + path.join(wallaby.localProjectDir, 'lib','my.domain', 'node_modules');`
   and other combinations
- adding  paths alias to `tsconfig.json`
- reduced and recycled `workers`
- cleaning wallaby cache

**Comment by ArtemGovorov** [comment]
I have sent you [the PR to make it work](https://github.com/Artur-A/wallaby-problem-symlink-ts/pull/1).

Here's the important bit:

```javascript
process.env.NODE_PATH += path.delimiter + path.join(wallaby.projectCacheDir, 'lib');
```

By doing this you are telling node.js to look up node modules in your `lib` folder (in wallaby's cache so that it's all instrumented and the coverage is displayed for the `my.core`).

I have also made a couple of smaller changes:
- excluded `node_modules` from the `files`/`tests` list because all specified `files` are copied (and instrumented by default) to the wallaby cache and you don't need it for `node_modules` as [described here](https://wallabyjs.com/docs/config/files.html).
- removed the `compiler` section, because wallaby will detect and use the `tsconfig.json` by default. Doing this by the way will also [resolve this issue](https://github.com/wallabyjs/public/issues/1035#issuecomment-305170233) for you, because wallaby will use the correct default if you don't pass the config explicitly (if you do like you were - wallaby is respecting all passed `compilerOptions` values).

Hope it makes sense.

**Comment by Artur-A** [comment]
"Aha moment", the problem was in _path.join(__wallaby.localProjectDir__) that I wrongly took from https://wallabyjs.com/docs/integration/node.html, while the needed path is __wallaby.projectCacheDir__.

Awesome support, thank you!

---

Just one question aside (have not found it in the discussions): having two wallaby testing configs `wallaby.client.js` and `wallaby.server.js` is it possible to run them simultaneously or there is only way to switch between them via 'Wallaby configuration selection' in VSCode?

**Comment by ArtemGovorov** [comment]
Yes, `wallaby.localProjectDir` can be used to point to your project's folder (to node_modules that don't have to be compiled/instrumented for example), in your case it's a bit different.

> having two wallaby testing configs wallaby.client.js and wallaby.server.js is it possible to run them simultaneously or there is only way to switch between them via 'Wallaby configuration selection' in VSCode?

At the moment only one wallaby config at a time is supported, please feel to subscribe to the related [feature request](https://github.com/wallabyjs/public/issues/89).

**Comment by Artur-A** [comment]
Excellent, thank you! :thumbsup:
