### ISSUE TITLE
Issue with jest.mock in setupFiles when using Typescript

### ISSUE THREAD

**Issue by mikemorton** [wallabyjs/public#1184]
### Issue description or question
Jest mocks do not work correctly in file defined in setupFiles.  I'm using Typescript for my project, but that may be a red herring.

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
          'tsconfig.json',
          'Scripts/**/*.ts',
          'Scripts/**/*.tsx',
          'Scripts/*.js',
          'Scripts/thrift/*.*',
          'Scripts/Tests/beforeAll.js'
        ],

        tests: [
          'Scripts/Tests/**/*.test.ts',
          'Scripts/Tests/**/*.test.tsx'
        ],
        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest'
    };
};
```

Jest portion of package.json
```
{
  "jest": {
    "transform": {
      ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
    "testRegex": "(\\.(test|spec))\\.(ts|tsx)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "json"
    ],
    "setupFiles": [
      "./Scripts/Tests/beforeAll.js"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/*.js"
    ],
    "mapCoverage": true,
    "testResultsProcessor": "./node_modules/jest-junit"
  },
  "jest-junit": {
    "usePathForSuiteName": "true"
  }
}
```

the problem I have is that before.js has some mocks in it that look like this...
```javascript
jest.mock('../reactor/app/helpers/ActionFactory', () => {
    return {
        // ...
    }
});

jest.mock('../reactor/app/helpers/StoreFactory', () => {
    return {
        // ...
    }
});
```

I find if I run my tests from jest in the command line, the objects are mocked correctly, but if I run with wallaby the mocks are not present.

### Code editor or IDE name and version
Visual Studio v2015 update 3

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
There are a couple of changes required in your wallaby config to make it work.

First, wallaby is using its own file cache and your `beforeAll.js` file is executed from your local project (you may see it yourself because it has grey coverage indicators meaning that even though the file is considered by wallaby, it's other version is executed).

This happens because when the path is defined like `"./Scripts/Tests/beforeAll.js"` (or with the `rootDir` prefix), Jest will take the file from the local project. Normally it's not an issue with wallaby, but you are using some relative paths in the file (to mock things), and those are resolved incorrectly in this case.

[Overriding the `setupFiles` setting](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) to load the file from the wallaby cache, so that it could correctly resolve the paths, should suffice:

 ```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'package.json',
      ...
    ],

    ...
    setup: wallaby => {
      const path = require('path');
      const jestConfig = require('./package.json').jest;
      jestConfig.setupFiles = [path.join(wallaby.projectCacheDir, 'Scripts/Tests/beforeAll.js')];
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

Second, because you're using TypeScript, then quite possibly you are using it with the `allowSyntheticDefaultImports` compiler option. In this case [`ts-jest` does some magic](https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360) that affects module loading and may affect mocking as well. If you are using the setting, you may need to configure wallaby to work the same way `ts-jest` does (as described [in this comment](https://github.com/wallabyjs/public/issues/1181#issuecomment-305678360)).

The resulting config that should work for you will like this:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'tsconfig.json',
      'package.json',
      'Scripts/**/*.ts',
      'Scripts/**/*.tsx',
      'Scripts/*.js',
      'Scripts/thrift/*.*',
      'Scripts/Tests/beforeAll.js',
      '!Scripts/Tests/**/*.test.ts?(x)'
    ],

    tests: [
      'Scripts/Tests/**/*.test.ts',
      'Scripts/Tests/**/*.test.tsx'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',

    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'es2015'
      })
    },
    preprocessors: {
      '**/*.js': file => require('babel-core').transform(
        file.content,
        {sourceMap: true, plugins: ['transform-es2015-modules-commonjs']})
    },

    setup: wallaby => {
      const path = require('path');
      const jestConfig = require('./package.json').jest;
      jestConfig.setupFiles = [path.join(wallaby.projectCacheDir, 'Scripts/Tests/beforeAll.js')];
      wallaby.testFramework.configure(jestConfig);
    }
  };
};
```

Hope it makes sense.

**Comment by mikemorton** [comment]
Thanks for the reply, I'll give that a try.
