### ISSUE TITLE
Debug file is not loaded

### ISSUE THREAD

**Issue by splintor** [wallabyjs/public#1186]
We have a debug file (debugFile.ts) which sets a global property:
```
window.__current__version__ = Infinity;
```
The file is only included in debug build and in tests.
It is also included in wallaby.config.js under `files`.
Some of our tests depend on this property.
Until recently, this worked well, but since once of the last wallaby updates, these tests fail when Wallaby is started. If I add a `console.log` to this file, I don't see it in the failed test log.

When I re-run the test, `window.__current__version__` is properly set and the test pass.

Can you explain what is going on here?
Shouldn't `files` be loaded and evaluated prior to `tests`?

(this used to work OK previously)

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        debug: true,
        files: [
            {pattern: 'src/languages/en-US/*.json', instrument: false},
            {pattern: 'src/test-fixtures/**/*', instrument: false},
            {pattern: "test/polyfills/*.js", instrument: false},
            {pattern: "build/all-protos.d.ts", instrument: false}, // wallaby hack: Make sure protos are loaded so enums are defined properly
            {pattern: "vendor/jquery.min.js", instrument: false}, // make sure jQuery is loaded before angular
            {pattern: "vendor/long.min.js", instrument: false}, // wallaby hack: Make sure long is loaded before bytebuffer.js
            {pattern: "vendor/bytebuffer.min.js", instrument: false}, // wallaby hack: Make sure byte array are loaded before protobuf.js
            {pattern: "vendor/angular.min.js", instrument: false}, // Make sure angular is loaded before angular-translate
            {pattern: "vendor/angular-translate.min.js", instrument: false}, // Make sure angular-translate is loaded before angular-translate-loader-partial
            {pattern: "vendor/*.min.js", instrument: false},
            {pattern: "vendor/ui-bootstrap-tpls.js", instrument: false},
            {pattern: "vendor/angular-ui-tab-scroll.js", instrument: false},
            {pattern: 'vendor/angular-busy.js', instrument: false},
            {pattern: 'vendor/bmc-dpl/src/components/busy-preloader/busy-preloader.js', instrument: false},
            {pattern: 'vendor/bmc-dpl/src/components/timepicker/timepicker.js', instrument: false},
            {pattern: 'vendor/bmc-dpl/src/components/datepicker-new/datepicker.js', instrument: false},
            {pattern: 'vendor/bmc-dpl/src/components/datetimepicker/datetimepicker.js', instrument: false},
            {pattern: 'vendor/bmc-dpl/src/components/counter/counter.js', instrument: false},
            {pattern: 'vendor/jsbn.js', instrument: false},
            {pattern: 'vendor/rsa.js', instrument: false},
            {pattern: 'vendor/jquery-ui-1.11.0.js', instrument: false},
            {pattern: 'vendor/date.js', instrument: false},
            {pattern: 'vendor/x2js.js', instrument: false},
            {pattern: "build/all-protos.js", instrument: false},
            {pattern: "vendor/go.js", instrument: false},
            {pattern: 'vendor/ag-grid.js', instrument: false},
            {pattern: 'vendor/ag-grid-new.noStyle.js', instrument: false},
            {pattern: 'vendor/ag-grid-new.css', instrument: false},
            {pattern: 'vendor/Chart.js', instrument: false},
            {pattern: 'vendor/ngDraggable.js', instrument: false},
            {pattern: 'vendor/angular-chart.js', instrument: false},
            {pattern: 'vendor/angular-vs-repeat.js', instrument: false},
            {pattern: 'vendor/diff_match_patch.js', instrument: false},
            {pattern: 'vendor/FileSaver.js', instrument: false},
            {pattern: 'vendor/jasmine-data_driven_tests/all.js', instrument: false},
            {pattern: "node_modules/angular-mocks/angular-mocks.js", instrument: false},
            {pattern: 'node_modules/jasmine-jquery/lib/jasmine-jquery.js', instrument: false},
            {pattern: 'vendor/ag-grid7.noStyle.js', instrument: false},
            {pattern: 'src/styles/**/*.css'},
            'src/debugMode.ts',
            'src/common/applicationServices/*.ts',
            'src/common/applicationServices/**/*.ts',
            "src/*/*.ts",
            "src/*/*/*.ts",
            "src/*/*/*/*.ts",
            "src/*/*/*/*/*.ts",
            "src/*/*/*/*/*/*.ts",
            "src/*/*/*/*/*/*/*.ts",
            "src/*/*/*/*/*/*/*/*.ts",
            "src/**/*.ts",
            "!src/**/*.tests/**/*.ts",
            "!src/**/*.tests2/**/*.ts",
            "!src/**/*.tests3/**/*.ts",
            "!src/**/*.tests4/**/*.ts",
            "!src/**/*.tests5/**/*.ts",
            "!src/**/*.tests6/**/*.ts",
            "!src/**/*.tests7/**/*.ts",
            "!src/common/bootstrapApp.ts",
            "src/**/*.html",
            "src/images/*"
        ],

        tests: [
            "src/**/*.tests/**/*.ts",
            "src/**/*.tests2/**/*.ts",
            "src/**/*.tests3/**/*.ts",
            "src/**/*.tests4/**/*.ts",
            "src/**/*.tests5/**/*.ts",
            "src/**/*.tests6/**/*.ts",
            "src/**/*.tests7/**/*.ts"
        ],

        preprocessors: {
            "src/**/*.html": function (file) {
                return require('wallaby-ng-html2js-preprocessor').transform(file, {
                    stripPrefix: 'src/',
                    moduleName: 'st-templates'
                })
            }
        },

        env: {
            kind: 'electron'
        }
    }
};

```

### Code editor or IDE name and version

WebStorm v2017.2 EAP

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
> Shouldn't `files` be loaded and evaluated prior to tests?

Correct, they should and they are loaded and executed prior to tests. Here [I have created the repo](https://github.com/ArtemGovorov/wallaby-1186) with your config file and [the `src/debugMode.ts`](https://github.com/ArtemGovorov/wallaby-1186/blob/master/src/debugMode.ts) file, and a [couple of test files using the variable](https://github.com/ArtemGovorov/wallaby-1186/blob/master/src/a.tests/someTest.ts#L2), and everything is working as expected. Please try the repo to see if it is working for you.

> Until recently, this worked well, but since once of the last wallaby updates, these tests fail when Wallaby is started.

We didn't make any changes recently that could have affected the behaviour. To completely rule out the effect of our recent changes, try setting the `reportUnhandledPromises` to `false` in your config:

```javascript
module.exports = function () {
    return {
        reportUnhandledPromises: false,
        ...
```
This should turn off the only change that theoretically could have affected your scenario, but I highly doubt it, because there would be some other error message reported (about unhanded promises).

However, as I said, it's unlikely that any wallaby changes affect your scenario (plus my sample is working no problem), so the issue is likely specific to your project.

If the sample project I have provided is working for you, then 
- try reviewing some recent changes in your project (recently updated/installed modules, code changes, etc.) to see if there is anything that could affect the `window.__current__version__` property. 
- my guess is that some of your code/tests could be deleting the property so that other tests are failing. As you said, tests run fine if you re-run them, and this happens because when you re-run a a test file, wallaby runs it alone in isolation, so nothing else touches the `window.__current__version__` property and the test passes. But when you run all of your tests, something may be removing/clearing the property. The reason it might had worked before is because you possible had less/more tests (and recently added/deleted some). Wallaby runs tests is separate isolated batches, and adding/removing test files could have caused affecting the tests that were previously passing (because the code/test that removes the property had been shifted to the same batch).
- try changing the `tests` list and only include one test path there (the one that depends on the `window.__current__version__` property). Run wallaby to see if the test is passing, if it is - something else somewhere in your code is definitely affecting (removing/unsetting) the property.
- if nothing else from listed above helps and the [provided sample](https://github.com/ArtemGovorov/wallaby-1186) is working, then try adding your project specific details (files/tests) into the project until it breaks. Once it breaks, please share the reproducible sample (you can do it privately via our email if you like, or I can create a private Github repo for you).

**Comment by ArtemGovorov** [comment]
One other thing that you may try (which won't help in case if some of your code is deleting the `window.__current__version__` property) is to set it in [the wallaby setup function](https://wallabyjs.com/docs/config/bootstrap.html) which always runs before your tests:

```javascript
 module.exports = function () {
   return {
     ...

     setup: function (wallaby) {
       window.__current__version__ = Infinity;
     }
   };
 };
```
But as I said, the file should work for you the same way.

**Comment by splintor** [comment]
Thanks @ArtemGovorov for your detailed response.
Your guess is absolutely correct - `__current__version__` is indeed deleted by other tests, and this is what caused the test to fail. I fixed the other tests to restore the value of `__current__version__` and now the Wallaby is running with a failure.

Thanks and sorry for the trouble. This is an old code and I didn't think I need to look for other test that might affect it.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
