### ISSUE TITLE
Test is not triggered when src changes may be not instrumented

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#119]
I have some concerns about the way Wallaby instruments the code. It looks like tests are linked to files, not to statements, lines or code chunks/branches.
So if I change something in a file (this could be just a new line at the end), all tests associated to that file are triggered.

This is a simple case where it doesn't trigger automatically when you change something in file 1.

File 1:
```javascript
var a = 1;
```

File 2:
```javascript
function doSomething() {
  return a;
}
```

Spec 1:
```javascript
it('does something', function () {
  expect(doSomething()).toBe(1);
});
```

When I run the test manually and the test changes from fail to pass or vice versa and change something in file 1 again, it does run the test automatically.
I expect that all specs will be triggered when the statement in file 1 changes.

This is kind of a stupid example, but I had a lot of issues with Angular dependencies (constants) changing without retriggering the tests. In general I can't trust on Wallaby running all the relevant tests automatically when I change the source.

**Background questions:**
How does Wallaby instrument its code? Why is file 1 instrumented after I run the spec manually but not before?

I noticed that coverage is only given for (function) expressions, not for function declarations:
![function_declaration](https://cloud.githubusercontent.com/assets/963136/7723668/a9e4b3a2-feea-11e4-903b-2e56261e90f1.png)

How is a function declaration instrumented?
Why do you instrument on a file basis instead of a more fine grained level?

**Comment by ArtemGovorov** [comment]
Can't reproduce the issue that you have described:

![dep](https://cloud.githubusercontent.com/assets/979966/7725887/d2f36c46-ff41-11e4-96af-9ad59ad9c024.gif)

Please let me know how I can I reproduce it.

Regarding your question about how tests are linked to code, it depends on whether you're concerned about the code coverage or about the automatic tests triggering.

From the code coverage prospective, wallaby instruments all code on expression level to provide the code coverage. Once a test run is finished, you can inspect any branch and find out what tests are covering it.

Running tests based on ongoing code changes on the other hand is a separate concern. Wallaby triggers tests using quite a few strict runtime dependency analysis rules as well as several heuristic rules. 

There are few cases when wallaby can't figure out dependencies between files and can't run dependent tests until full or manual re-run. For example, If you add a new source file during running wallaby session, it may not know what tests to run for it, until you run some manually or restart wallaby. It does use some heuristics to mitigate, such as running the last edited spec. If you find some specific scenarios when it doesn't work, please let me know and I'll try to add some heuristics to cover them.

Function declaration is not highlighted because it's hoisted:

``` JavaScript
// Outputs: "Yes!"
isItHoisted();

// no matter where I put it
function isItHoisted() {
    console.log("Yes!");
}
```

**Comment by fvanwijk** [comment]
Sorry, I see that you have to switch file 1 and 2 (or make sure that file 2 is loaded first).
It looks like it has something to do with hoisting.
Also make sure that the code is created first and then start Wallaby. Or restart Wallaby.

**Comment by ArtemGovorov** [comment]
I have created file1, file2, spec. Tried listing file2 then file1 and the other way around, restarting. Still everything works:
![dep](https://cloud.githubusercontent.com/assets/979966/7727714/fd0d4860-ff4d-11e4-848f-4a6e67a6f90e.gif)

The only scenario I can think of when it won't work (and I have mentioned it above) is to create a spec first, stop wallaby, start wallaby, add files (or even one file). Tests will not trigger, the reason is simple - how may wallaby know what tests to run? Running everything on a file adding may be an overkill, as the project may have thousands of them. It doesn't know yet that file(s) are covered by the spec. Simple restart (or manual run) will put everything back on track. I'm happy to add some heuristics for this case, but can't think of any good one. Maybe just taking the risk of a possible long run and running all specs is the answer. 

As I have mentioned, there's some heuristics to mitigate it, but it's for a case when you add a spec and then add some code without restarting wallaby. In this case it'll be running the last edited spec, so file dependencies will be picked up without a restart or a manual run.

**Comment by fvanwijk** [comment]
I understand that you don't want to automatically rerun all specs when a new file is added. However, since heuristics are not waterproof, you cannot trust on the 'auto re-run' feature and always have to run all specs again before making a commit to be sure that you are not committing broken stuff.

In the mentioned case Wallaby is running (no files touched after starting Wallaby) and the `var a = 10` is changed to something else, and the test does not rerun on my machine. (It does on yours...)

The console says 'Finished executing 0 affected test(s)'.

I'll try to make a fancy movie like you do to demonstrate it. Perhaps there are still some differences between my setup and yours...

**Comment by ArtemGovorov** [comment]
It's true that heuristics are not waterproof. I guess all we can do is to add new rules to cover more and more cases to reduce the need to run anything manually. Before committing I personally restart wallaby.js to do the full run.

Anyway, wallaby.js wasn't designed to be the last resort or silver bullet to make sure that nothing is broken, it can't guarantee that. Even if we manage to cover 100% of cases with some smart rules and even if all tests pass in wallaby, it doesn't mean that they are not broken in some browser or on some device. Wallaby goal is to make your more productive when writing your code, but ideally there still should be a safety net of CI build test runs that should be performed on as many platforms and devices that you support as possible.

With the scenario with `var a = 10`, could you please share a small repo with your wallaby config and the exact sequence of steps that you're performing? It looks like I'm failing to reproduce it because I'm doing something differently.

**Comment by ArtemGovorov** [comment]
After giving more thought to your concerns, I have had an idea. Maybe we could add a button that would allow to quickly run all tests in wallaby, without any instrumentation, but still with parallelisation to make it as fast as possible. This way one may run all the tests before committing code or basically anytime the full fast run is required. What do you think?

**Comment by ArtemGovorov** [comment]
> 3 files case

I think after a few attempts I managed to reproduce it, but can't do it again, will try more.

**Comment by yongoh** [comment]
Hi Artem, 

+1 for quick rerun button.   I'm currently hit by same issue... 

Thanks.   Enjoy your weekend!

**Comment by fvanwijk** [comment]
Fair enough. I agree with your point about the waterproofness. A "quick run all" button would increase development efficiency and will contribute to your goals. Furthermore this will bring you closer to implementing #72.

**Comment by ArtemGovorov** [comment]
@fvanwijk @yongoh Ok I think I have reproduced the issue, the simplest case is just 2 files, where test is using a global variable from any file:
![screen shot 2015-05-21 at 6 00 42 pm](https://cloud.githubusercontent.com/assets/979966/7744039/5df768c8-ffe3-11e4-84d7-1ed2be79e54a.png)

The issue here is that when wallaby runs the test, the `var a = 1;` is not executed, so wallaby can not establish the link between the line of code and the test.

`var a = 1;` gets executed when the file where it's declared is loaded into the test page (sandbox).

So even though everything is instrumented correctly, the test has no idea where `a` comes from.

A working alternative for such scenarios that would make wallaby work is to define constants like this in a form of a function:
![screen shot 2015-05-21 at 6 10 32 pm](https://cloud.githubusercontent.com/assets/979966/7744222/cdcc9ad2-ffe4-11e4-97bd-42cc2c2038f0.png)

This way the test is able to establish the link because it executes the `a` function to get the value. 

A perhaps better way would be something like this:
![screen shot 2015-05-21 at 6 20 39 pm](https://cloud.githubusercontent.com/assets/979966/7744384/1df645f2-ffe6-11e4-9709-b8f02e81c5de.png)

This way production code will initialise constants while executing the source file and tests will be able to initialise them as required in `beforeEach` and have a chance to establish the link between tests and lines with constant values.

I understand it may not be desirable to declare constants like this just for the sake of getting wallaby working, but that's the best I can think of right now. I'll keep thinking how to improve it.

**Comment by ArtemGovorov** [comment]
@fvanwijk @taeyangoh I have added the "Run project tests" action to the wallaby quick actions.
![screen shot 2015-06-22 at 6 26 25 pm](https://cloud.githubusercontent.com/assets/979966/8278106/4bd0870a-190c-11e5-822f-b1bb067ef458.png)
It allows to run all tests without restarting wallaby.

I have also added a warning to the Wallaby Console that is displayed when wallaby.js can't figure out what tests to run as a result of some code changes. The warning may be used as an indicator when to use "Run project tests" action.

![screen shot 2015-06-22 at 6 29 41 pm](https://cloud.githubusercontent.com/assets/979966/8278179/b39826a4-190c-11e5-943c-bdb2a697e8bc.png)
