### ISSUE TITLE
How can I load external library ?

### ISSUE THREAD

**Issue by olegdovger** [wallabyjs/public#120]
How can I load external library from config file ('//maps.google.com/maps/api/js?sensor=true')

**Comment by olegdovger** [comment]
The main issue in JSONP. I can not load google maps script because of JSONP. 
```
ReferenceError: Can't find variable: google
	at bower_components/leaflet-plugins/layer/tile/Google.js:29
	at bower_components/leaflet/dist/leaflet.js:6
```

**Comment by ArtemGovorov** [comment]
At the moment it's not possible to specify a URL for the file. I can add a support for it, so you'll be able to just use a URL instead of a relative path. 

The only workaround for now that I can think of is creating a script that synchronously loads the external library ([something like this](http://stackoverflow.com/a/2880147/146850)), and including this script to the list of your files where you need it.

**Comment by ArtemGovorov** [comment]
@olegdovger I have created this sample repo for you - https://github.com/wallabyjs/wallaby-external-script. Please note that you have to pass [this PhantomJs setting](https://github.com/wallabyjs/wallaby-external-script/blob/master/wallaby.js#L15) to allow sync XHR requests.

**Comment by olegdovger** [comment]
Yes. It works. I used google stub script but right now it no need any more I think. Thank you.
