### ISSUE TITLE
Async errors are inconsistent with standard Jest runner

### ISSUE THREAD

**Issue by BrendanAnnable** [wallabyjs/public#1204]
### Issue description or question
The following contrived minimal example test passes using the standard jest test runner (using the `jest` command), but fails when run by wallaby configured to use `jest` as a test runner.

```javascript
it('async error test', () => {
  new Promise(async() => {
    await Promise.resolve()
    throw new Error()
  })
  expect(true).toBeTruthy()
})
```

Now you can certainly argue that this test _should_ fail and that jest should not let it pass, but that puts me in a pickle, because I use wallaby personally within my team, but everyone else uses Jest standard. Which means while everyone else thinks their tests are passing... they might fail for me 😞  Any suggestions?

Did not include wallaby config since there is nothing specific to this problem in there other than `testFramework: 'jest'`.

### Code editor or IDE name and version

IntelliJ IDEA 2017.1

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
By default wallaby reports unhandled promise rejections as errors, because in future they'll just crush node process if stay unhandled.

If you run your tests using the `jest` command, you should be able to see the warning from node:

![screen shot 2017-06-22 at 3 07 44 pm](https://user-images.githubusercontent.com/979966/27418175-b0d4f722-575c-11e7-98bf-adc7d29753f6.png)

I'd recommend looking into the root of the issue (why the test is not handling the promise) at some point, because in future versions of node the `jest` command may just start crashing, as described in the warning.

Having said that, if you'd like to ignore the warning and make wallaby work like plain Jest, you may use the `reportUnhandledPromises: false` setting:

```javascript
module.exports = function() {
  return {
    ...
    reportUnhandledPromises: false
  };
};

```

**Comment by BrendanAnnable** [comment]
Thanks @ArtemGovorov, I completely agree on all accounts, it was just about keeping consistency between the runners. Thanks for that!
