### ISSUE TITLE
Show difference dialog missing and coverage information gray on fail

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1205]
### Issue description or question
I am not sure what I am doing wrong here / misunderstanding, but I am not seeing the ``Show Difference`` dialog when commenting out [chrisblossom/clean-self-webpack-plugin/clean_self_webpack_plugin.test.js#L179](https://github.com/chrisblossom/clean-self-webpack-plugin/blob/e1a2c4441ed9b8b1653ce0e6ad277d3727e02c05/src/clean_self_webpack_plugin.test.js#L179)

It also seems like the coverage information is missing when a test is failing. All status icons are gray, instead of red and stopping at last code path. I think this was the previous behavior. Please disregard if I am mistaken.

<img width="428" alt="screen shot 2017-06-22 at 9 02 02 am" src="https://user-images.githubusercontent.com/1595871/27444217-82931812-572a-11e7-94d6-956f27c1ad24.png">

### Wallaby.js configuration file

```javascript
/* eslint-disable global-require,strict */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js',
            'jest.config.js',
            // '__sandbox__/**/*', // I don't think this is necessary because it is created by the tests
            '!src/**/*.test.js',
        ],

        tests: ['src/**/*.test.js'],

        env: {
            type: 'node',
            runner: 'node',
        },

        compilers: {
            '**/*.js': wallaby.compilers.babel(),
        },

        testFramework: 'jest',

        // https://github.com/wallabyjs/public/issues/465
        workers: { initial: 1, regular: 1 },

        setup: w => {
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2017.2 EAP
Build #WS-172.3095.13, built on June 21, 2017
WebStorm EAP User
Expiration date: July 21, 2017
JRE: 1.8.0_152-release-915-b3 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```

### OS name and version

``OSX 10.12.5``

**Comment by ArtemGovorov** [comment]
This is a limitation of Jest, [currently unhandled async errors crash it](https://github.com/facebook/jest/issues/2059). Because of the crash, wallaby is only able to report as much as plain Jest is reporting. You may see what happens when you run `npm test` for your example [chrisblossom/clean-self-webpack-plugin/clean_self_webpack_plugin.test.js#L179](https://github.com/chrisblossom/clean-self-webpack-plugin/blob/e1a2c4441ed9b8b1653ce0e6ad277d3727e02c05/src/clean_self_webpack_plugin.test.js#L179):

![screen shot 2017-06-23 at 1 19 57 pm](https://user-images.githubusercontent.com/979966/27465424-b276087c-5816-11e7-8617-9fd4bb72b550.png)

As you can see, no proper test result are reported. You may compare the result with a sync expectation fail, for example if you make [the assertion on the line 175 to fail](https://github.com/chrisblossom/clean-self-webpack-plugin/blob/e1a2c4441ed9b8b1653ce0e6ad277d3727e02c05/src/clean_self_webpack_plugin.test.js#L175)) (in both Jest and wallaby you'll get a nice expected result).

As recommend in [the mentioned Jest issue](https://github.com/facebook/jest/issues/2059#issuecomment-263611085), you may use `try {} catch(e) { done.fail(e) }` approach in async tests:

```javascript
        compiler.run(() => {
            try {
              expect(cleanSelfWebpackPlugin.currentAssets).toEqual([
                '0.bundle.js',
                // 'bundle.js',
              ]);
            }
            catch(e) {
              done.fail(e);
            }
        });
```

It's not ideal (considering that other testing frameworks like jasmine just work), but does the trick and makes Jest (and wallaby) to work as expected.
