### ISSUE TITLE
Object spread operator won't work in combination with typescript

### ISSUE THREAD

**Issue by brechtbilliet** [wallabyjs/public#1212]
### Issue description or question
Object spread operator won't work in combination with typescript.
Runtime error:   33 |         dispatch(action) {
  34 |             $_$wf(6);
> 35 |             $_$w(6, 48), this.store.dispatch({ ...action });

### Wallaby.js configuration file

```javascript
var compilerOptions = require('./tsconfig.jest.json');
compilerOptions.module = 'commonjs';
compilerOptions.jsx = 'React';

module.exports = function (wallaby) {
    var path = require('path');
    var ts = require(path.join(wallaby.localProjectDir, 'node_modules/typescript'));
    return {
        files: [
            "src/**/*.ts?(x)",
            "!src/**/*.spec.ts?(x)",
            "package.json"
        ],
        tests: [
            "src/**/*.spec.ts?(x)"
        ],
        env: {
            type: "node",
            runner: "node"
        },
         compilers: {
            'src/**/*.ts?(x)': wallaby.compilers.typeScript(Object.assign(compilerOptions, {typescript: ts}))
        },
        testFramework: "jest",
        debug: true,
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure({
                "globals": {
                    "__TS_CONFIG__": "tsconfig.jest.json"
                },
                "setupTestFrameworkScriptFile": "./test-bundle.js",
                "transformIgnorePatterns": [
                    "<rootDir>/node_modules/(?!react-rx-connect)"
                ],
                "moduleNameMapper": {
                    "^.+\\.(s?css|less)$": "<rootDir>/config/empty-module.js"
                }
            });
        }
    };
};
```

### tsconfig file

```
{
  "compilerOptions": {
    "module": "CommonJs",
    "target": "es5",
    "moduleResolution": "node",
    "baseUrl": "src",
    "allowSyntheticDefaultImports": true,
    "noImplicitAny": false,
    "sourceMap": true,
    "outDir": "ts-build",
    "jsx": "react",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "ES2015",
      "DOM"
    ]
  },

  "exclude": [
    "node_modules",
    "**/*.spec.ts*"
  ]
}

```

### babel.rc file

```
{
  "presets": ["react", "es2015", "stage-0"],
  "plugins": ["react-hot-loader/babel", "transform-object-rest-spread"]
}
```

### Code editor or IDE name and version

WebStorm v? 2017.1.4

### OS name and version
osx el capitan 10.11.3

**Comment by ArtemGovorov** [comment]
I can't reproduce the issue using your config files. Here the repo I have put together (with your config files): https://github.com/ArtemGovorov/wallaby-1212, everything is working for me - [including the object rest operator](https://github.com/ArtemGovorov/wallaby-1212/blob/master/src/a.spec.ts#L3). Please clone the repo to see if it's working for you.

There's only one guess I have, you're getting the error not from .ts file, but from .js file. This may be because you actually don't have any babel compilation configured for your .js files in your wallaby config. You may try adding the babel preprocessor like [described in the docs](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel):

```javascript
module.exports = function (w) {

  return {
    ...
    preprocessors: {
      '**/*.js?(x)': file => require('babel-core').transform(
        file.content, {
          sourceMap: true,
          "presets": ["react", "es2015", "stage-0"],
          "plugins": ["react-hot-loader/babel", "transform-object-rest-spread"]
        })
    }
  };
};
```

If the above suggested doesn't help, please create a repo to reproduce the issue. You may [fork the sample](https://github.com/ArtemGovorov/wallaby-1212) I have created and add the missing details to it.

**Comment by brechtbilliet** [comment]
Thank you so much! Fixed
