### ISSUE TITLE
Importing a CSS file causes tests to stop executing

### ISSUE THREAD

**Issue by mindjuice** [wallabyjs/public#1213]
### Issue description or question
If a JavaScript (or TypeScript) file contains a line like:

```import 'codemirror/addon/dialog/dialog.css'```

then it seems to cause an exception, and no code after that point is executed (grey boxes in the code).

I tried changing to `require()`, but get a different error.

I just found the Wallaby.js Console in the OUTPUT section, which shows:
```
[Info]​​​​​ ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.CodeMirror-dialog {
​​​​​[Info]​​​​​                                                                                          ^
​​​​​[Info]​​​​​ SyntaxError: Unexpected token .
​​[Error] Runtime error: /Volumes/hrt/dev/algo/earth/client/node_modules/codemirror/addon/dialog/dialog.css:1​​
​​[Error] ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){.CodeMirror-dialog {​​
```

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    testFramework: 'jest',
    env: {
      type: 'node',
      runner: 'node'
    },

    files: [
      'src/components/**/index.tsx',
      'src/components/**/styles.ts',
      'src/middleware/*.ts',
      'src/modules/**/index.ts',
      'src/panels/**/index.tsx',
      'src/utils/*.ts',
      'src/index.ts',
    ],
    tests: [
      'src/**/__tests__/*_tests.ts',
      'src/**/__tests__/*_tests.tsx',
    ],
    debug: true,
    hints: {
      ignoreCoverage: /ignore coverage/
    },
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.13.1

### OS name and version
OSX 10.12.3 Sierra

**Comment by mindjuice** [comment]
Should also have mentioned that the unit tests run just fine with Jest even with the `import` lines, so it seems that there is something in the parsing that Wallaby's doing that doesn't like the CSS.

**Comment by ArtemGovorov** [comment]
Jest needs some configuration in order to correctly load/mock CSS files. Normally it looks something like this in your Jest configuration:

```javascript
    ...
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/__mocks__/styleMock.js"
    }
```

Now given Jest CLI is working for you, it means that wallaby doesn't load your Jest configuration. Wallaby automatically loads Jest configuration if it's located in your `package.json` file.

If your Jest configuration is located somewhere else, like in `jest.config.js`, then you'll [need to pass it to wallaby like described here in the docs](https://wallabyjs.com/docs/integration/jest.html#jest-configuration), for example:

```javascript
module.exports = () => {
    return {
        files: [
            'jest.config.js',
            ...
        ],

        ...

        setup: w => {
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

Let me know know if this helps. If not, please let me know how/where Jest in configured in your project.

**Comment by mindjuice** [comment]
Hmmm...I don't have a separate Jest config file, and I don't have any Jest config in my `package.json`.  I'm just using `create-react-app` with `react-scripts-ts`.

Is it possible that wallaby is not looking for the Jest config from `create-react-app` config because I'm using `react-scripts-ts` instead of `react-scripts`?

**Comment by ArtemGovorov** [comment]
> I'm just using `create-react-app` with `react-scripts-ts`.

Ah, this changes things. I thought you're using Jest directly when you said that "tests run just fine with Jest", but you must be running them with `react-scripts test`.

In order to configure wallaby for `create-react-app`, you may [read this docs section](https://wallabyjs.com/docs/integration/react-jsx.html#create-react-app), that explains the process in detail.

You'll just need to adjust the sample to use `react-scripts-ts` instead of `react-scripts`:

```javascript
var path = require('path');
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts-ts/node_modules');
  require('module').Module._initPaths();

module.exports = () => {
  return {

    ... // the rest of your config

    setup: (wallaby) => {
      wallaby.testFramework.configure({
        // as in node_modules/react-scripts-ts/utils/createJestConfig.js
        testURL: 'http://localhost',
        setupFiles: [require('path').join(wallaby.localProjectDir, 'node_modules/react-scripts-ts/config/polyfills.js')],
        moduleNameMapper: {
          '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve('react-scripts-ts/config/jest/fileTransform.js'),
          '^.+\\.css$': require.resolve('react-scripts-ts/config/jest/cssTransform.js'),
          '^react-native$': 'react-native-web'
        }
      });
    },
  }
}
```

**Comment by mindjuice** [comment]
Working now.  Thanks!
