### ISSUE TITLE
On Windows 10 - No test coverage

### ISSUE THREAD

**Issue by licaon** [wallabyjs/public#1219]
### Issue description or question
Recently wallaby is not showing coverage for files, even on the http://wallabyjs.com/app/#/files, i get 0%
I've created a basic repo with the issue: https://gitlab.com/raul.macarie/posts_and_comments

Also a screenshot of the IDE: https://www.screencast.com/t/IHQ1GbtI2L5

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
    ],

    tests: ['test/**/*spec.js'],
    compilers: {
      '**/*.js*': wallaby.compilers.babel(),
    },
    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v2017.1.5
Visual Studio Code v1.12.2

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the repo. Looks like you have started using `modulePaths` in your Jest config, and when you declare it like:
```javascript
  modulePaths: [
    './',
    ...
```
jest will just load the file imported like `import App from 'src/components/app'` from your local project folder (and not from wallaby cache where the file is instrumented and ready for the coverage displaying).

All you need to do is just let wallaby know to look to its file cache instead of the the local project:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      'jest.config.js',
    ],

    tests: ['test/**/*spec.js'],
    compilers: {
      '**/*.js*': wallaby.compilers.babel(),
    },
    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    setup: w => {
      const jestConfig = require('./jest.config');
      jestConfig.modulePaths[0] = w.projectCacheDir; // <--
      w.testFramework.configure(jestConfig);
    },
  };
};

```
