### ISSUE TITLE
Wallaby doesn't recognise object-spread operator (among other things)

### ISSUE THREAD

**Issue by adilhz** [wallabyjs/public#1220]
### Issue description or question
I can't seem to run wallaby on my code. I'm using a standard vue-webpack setup (ES6, vue & webpack). I'm also getting issues related to webpack(?) - e.g. module '72' not found.
### Wallaby.js configuration file

```javascript
/* eslint-disable */
const wallabyWebpack = require('wallaby-webpack');
const webpackConfig = require('./build/webpack.test.conf');
const webpackPostProcessor = wallabyWebpack(webpackConfig);
module.exports = function (wallaby) {
	return {
		files: [
			{
				pattern: 'node_modules/babel-polyfill/dist/polyfill.js',
				instrument: false
			},
			{
				pattern: 'src/**/*.js',
				load: false
			},
			{
				pattern: 'src/**/*.vue',
				load: false
			}
		],

		tests: [
			{
				pattern: 'test/unit/specs/*.spec.js',
				load: false
			}
		],

		compilers: {
			'**/*.js': wallaby.compilers.babel()
		},

		postprocessor: webpackPostProcessor,

		setup: function() {
			window.__moduleBundler.loadTests();
		},

		debug: true,
		testFramework: 'mocha'
	}
};

// .babelrc
{
  "presets": [
    ["env", {
      "modules": false,
      "targets": {
        "browsers": ["> 1%", "last 2 versions", "not ie <= 8"]
      }
    }],
    "es2015",
    "stage-2"
  ],
  "plugins": ["transform-runtime", "transform-object-rest-spread"],
  "env": {
    "test": {
      "presets": ["env", "es2015", "stage-2"],
      "plugins": ["istanbul"]
    }
  }
}

```

### Code editor or IDE name and version

Visual Studio Code 1.13.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Could you please create a sample repo demonstrating the issue? I'm happy to have look and help with the config.

**Comment by adilhz** [comment]
Just uploaded one here: https://github.com/adilhz/wallaby-test
However wallaby.js seems to fine using that repo, which is strange because that repository forms the base for my project. 

Here are the logs from running wallaby: https://ghostbin.com/paste/oqc8h

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

You're using aliases and as [described in the docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder) you need to pint webpack to wallaby cache folder. You also need to include `.babelrc` into the `files` list because `vue-loader` will start looking for the file in the wallaby cache once `resolve.alias` path is changed.

I have sent you [the PR with the mentioned changes](https://github.com/adilhz/wallaby-test/pull/1).
If applying a similar fix in your project's config doesn't help, please reproduce the issue in your sample repo.

**Comment by adilhz** [comment]
Oh wow, it works! Thanks for the help!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
