### ISSUE TITLE
Test does not fail when it should

### ISSUE THREAD

**Issue by FlemmingBehrend** [wallabyjs/public#1225]
### Issue description or question
Iam running a node application and a test that should fail is passing.

![image](https://user-images.githubusercontent.com/1967934/28124646-981fe700-6724-11e7-848a-24a6a95c4700.png)

Any idea what's wrong?

### Wallaby.js configuration file

```javascript
module.exports = function (w) {
    return {
        files: [
            'src/**/*.js',
            {pattern: 'src/**/*.spec.js', ignore: true}
        ],
        tests: [
            'src/**/*.spec.js'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'jasmine'
    };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v2017.1.3

### OS name and version
Microsoft Windows 7 Enterprise
6.1.7601 Service Pack 1 Build 7601

**Comment by ArtemGovorov** [comment]
I think your test is failing after Jasmine finish executing it (and treats it as passed), so your test can't properly fail. Looks like your test is defined as a sync test, but you are using an async code in it (the promise). 

It's similar to this:

```javascript
it('should fail but will pass', () => {
  setTimeout(() => {
     throw new Error('should fail');
  }, 1000)
});
```
this test will always pass, because it's sync and the failure is async. But, if you change it to an async test:

```javascript
it('should fail but will pass', done => {
  setTimeout(() => {
     throw new Error('should fail');
     done();
  }, 1000)
});
```
then it'll start failing as expected. You need to the same in your async test (accept Jasmine test callback as an argument in the test, and invoke the callback when the test is finished doing assertions):

```javascript
it('should fail but will pass', done => { // <--
  ...
  your_promise.then(() => {
    ...
    expect(...)
    done(); // <--
  });
});
```

**Comment by FlemmingBehrend** [comment]
Thanks for helping out even though it had nothing to do with you awesome product :+1:
