### ISSUE TITLE
Question: karma-server-side equivalent?

### ISSUE THREAD

**Issue by suchipi** [wallabyjs/public#1235]
### Issue description or question
I am converting a project from karma to wallaby. In my karma configuration, I was using a package called [karma-server-side](https://github.com/featurist/karma-server-side) to run code on the server via the client, using a websocket connection. It's pretty much a fancy way to write code on the client that the server evals.

I'd like to reimplement karma-server-side so that it can be used in wallaby. To do so, I'll need to run a websocket server on the server (in node) that the client can talk to; could you point me in the right direction for where to put the server-side code? Also, I assume I can put the clientside websocket connection code in `setup` in my wallaby config; is that correct? Or is there a more appropriate place?

### Wallaby.js configuration file
(Not really relevant, but posting anyway because your template asks for it. It's a pretty simple webpack setup.)
```javascript
const wallabyWebpack = require("wallaby-webpack");
const webpackConfig = require("./webpack.config")({ wallaby: true });
const wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
  return {
    testFramework: "mocha",

    files: [
      { pattern: "src/**/*.test.js", load: false, ignore: true },
      { pattern: "src/**/*", load: false },
    ],

    postprocessor: wallabyPostprocessor,

    tests: [
      { pattern: "src/**/*.test.js", load: false },
    ],

    compilers: {
      "**/*.js": wallaby.compilers.babel(),
    },

    env: {
      kind: "electron"
    },

    setup: function() {
      window.__moduleBundler.loadTests();
    },
  };
};
```

### Code editor or IDE name and version

Atom v1.18.0

### OS name and version

macOS Sierra 10.12.5

**Comment by ArtemGovorov** [comment]
> could you point me in the right direction for where to put the server-side code? 

You may put the server side code right into your wallaby config, or in a separate file/module required from wallaby config. Note that you'll need to check `process.argv[2] !== 'worker'` condition, because wallaby runs the config file across multiple processes (for parallel compilation, etc.), but you only need to start the server in the main process.

> Also, I assume I can put the client side websocket connection code in `setup` in my wallaby config; is that correct?

If you'd like to do something before tests are executed, like connect to the websocket server, then yes. 

However, the [`karma-server-side` module docs suggest](https://github.com/featurist/karma-server-side#usage) that you require the module from your tests, and call the `run` function which return a promise. If you'd like to preserve the contract, then you may create a `wallaby-server-side` module or `wallaby-server-side.js` file, `require` it from your tests as well. The run function will try to connect to the remote server (instantiated in your config) and communicate with the server.

Here's a simple example ([using `ws` socket server](https://github.com/websockets/ws#server-example)), that creates the websocket server and connects to it from the client before running tests. If you run it, it'll print the received message `Opened ws conection, starting tests` to the [Wallaby console in Atom Dev Tools](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting).

```javascript
// you may put the server code into a separate file or module
// and require it from your wallaby config
if (process.argv[2] !== 'worker') { // only start the server in the main wallaby process
  const WebSocket = require('ws');
  const wss = new WebSocket.Server({port: 8282});

  wss.on('connection', function connection(ws) {
    ws.on('message', function incoming(message) {
      console.log('received: %s', message);
    });
  });
}

module.exports = function (wallaby) {

  ...

  return {
    ...

    setup: function (wallaby) {
      wallaby.delayStart();

      // you may put the client code into a separate file or module
      // and require it from your tests
      var ws = new WebSocket('ws://127.0.0.1:8282');

      ws.onopen = function () {

        ws.send('Opened ws conection, starting tests');

        window.__moduleBundler.loadTests();
        wallaby.start();
      }
    }
  };
};
```

Note that I'm connecting before running tests just as an example. If you create a separate file/module imported from your tests like `karma-server-side`, then you may connect on the first `.run` call as the `karma-server-side` module, and hide the logic behind the promise.

Hope it makes sense.

**Comment by suchipi** [comment]
Thank you for the detailed response! Makes perfect sense. I will give this a try. Thank you!
