### ISSUE TITLE
Angular + Jest setup -  ​​Error: Cannot resolve all parameters for 'TestService'(?)

### ISSUE THREAD

**Issue by urish** [wallabyjs/public#1236]
### Issue description or question

Seems like dependency injection in Angular 4 app tests doesn't work inside Wallaby. Running the same test suite command line (jest) works correctly.

### Wallaby.js configuration file

See [here](https://github.com/urish/wallaby-jest-angular-issue/blob/master/wallaby.js)

### Code editor or IDE name and version

Visual Studio Code v1.14.2

### OS name and version

Windows

I created a small repo that reproduces the issue for me:

https://github.com/urish/wallaby-jest-angular-issue

Also, Wallaby is awesome. Keep up to good work! 🥇

**Comment by ArtemGovorov** [comment]
Thanks for creating the repo! I have sent you [the pull request](https://github.com/urish/wallaby-jest-angular-issue/pull/1) to make it work.

The reason why it didn't work for you was because wallaby.js only [looks for the project's root `tsconfig.json` file](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings). In your case the file is in the `app` subfolder, so you need to specify the [TS compiler settings  explicitly](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings).

**Comment by urish** [comment]
It did the trick :-)

Thanks!
