### ISSUE TITLE
Joi + Jest snapshots issue

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1237]
### Issue description or question
When using Joi combined with Jest snapshots, Wallaby does not output the same string as Jest. Tests are passing when running ``jest`` but failing with Wallaby.

EDIT: Minimal example: [chrisblossom/wallaby-issue-1237](https://github.com/chrisblossom/wallaby-issue-1237)

<img width="1072" alt="screen shot 2017-07-23 at 3 51 40 pm" src="https://user-images.githubusercontent.com/1595871/28503570-dcf5665a-6fbe-11e7-8cec-70ce386f6ba3.png">

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js',
            'jest.config.js',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: w => {
            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2017.2
Build #WS-172.3317.70, built on July 13, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
```

### OS name and version

``Mac OS X 10.12.5``

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

The issue here is that wallaby instruments all functions, so a snapshot of Joi string taken when the code is run without code coverage is always different from the snapshot taken from a string with coverage.

It's not a wallaby specific issue though, and will happen if you run any other code coverage solution (that modifies the original code before running it). For example, if you [run Jest with its built-in coverage](https://facebook.github.io/jest/docs/configuration.html#collectcoverage-boolean), by changing your Jest config to:

```javascript
'use strict';

module.exports = {
    rootDir: 'src',
    moduleDirectories: ['node_modules', 'src'],
    testEnvironment: 'node',
    collectCoverage: true
};
```

you'll get a similar error:

![screen shot 2017-07-24 at 2 06 28 pm](https://user-images.githubusercontent.com/979966/28507854-54b9592a-7079-11e7-8730-9d27c11a9dda.png)

In order get the test passing, you may make wallaby to [ignore code coverage instrumentation just for that function](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file). I have sent you the [PR with the change](https://github.com/chrisblossom/wallaby-issue-1237/pull/1). This way wallaby will not instrument the function and your code should look the same with or without instrumentation (note that there still may be some edge case scenarios when the code may still be different, in which case you may need to turn of the instrumentation for the whole file where functions used in Joi are defined).

Please note that you'll also need to [upgrade your wallaby.js core to v 1.0.456](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), as there's been some recent changes to the way code coverage hints work.

**Comment by chrisblossom** [comment]
Thank you! My issue is my ``__sandbox__`` directories are getting code coverage. Looking at the docs you linked, I tried adding ``{ pattern: 'src/**/__sandbox__/**/*', instrument: false }`` without success.

This worked for Jest:
```js
    collectCoverage: true,
    coveragePathIgnorePatterns: ['/__sandbox__/']
```

Ideas?

https://github.com/chrisblossom/wallaby-issue-1237/commit/076e9f8c0bd26760823d69b5e41fb87eba105839

**Comment by ArtemGovorov** [comment]
Thanks for the update. 

Wallaby.js applies rules in the `files` list for each source code file from the top of the list, so because you have the `'src/**/*.js'` pattern first in the list (and by default the `instrument` flag is `true` in the pattern), all files in `src/**/__sandbox__/**/*` are processed as with the `'src/**/*.js'` rules (`instrument: true`). All you need to do is move the less broad pattern up in the list (to be before the broad pattern). I have sent you [the pull request with the change](https://github.com/chrisblossom/wallaby-issue-1237/pull/2).

**Comment by chrisblossom** [comment]
Thank you again @ArtemGovorov ! The next issue I found is when ``instrument`` is false, the files are not being compiled with ``babel``.

https://github.com/chrisblossom/wallaby-issue-1237/commit/0d7176ad068111d10b79d56f8aac5397fd206482

```
➜  wallaby-issue-1237 git:(master) ✗ cat /Users/chris/Library/Caches/WebStorm2017.2/wallaby/projects/cbe47ba4ad6759db/instrumented/src/__sandbox__/test_file.js

const fn = () => 'fn';

export default fn;
```

**Comment by ArtemGovorov** [comment]
Yep, when wallaby is not instrumenting files, it's not compiling them either. In this case you may just let Jest default transformer (`babel-jest` to do the trick). Have sent you [the PR](https://github.com/chrisblossom/wallaby-issue-1237/pull/3) with the required config change (re-adding [jest transform](https://facebook.github.io/jest/docs/configuration.html#transform-object-string-string), that is not normally used because wallaby is using its own babel compiler, plus the `.babelrc` file so that `babel-jest` can transform stuff in the wallaby cache folder).

**Comment by chrisblossom** [comment]
Thank you! I looks like that was the last of my issues. Got pretty complicated there towards the end.
