### ISSUE TITLE
"Test without test file id" error when importing tests from different file

### ISSUE THREAD

**Issue by mhelvens** [wallabyjs/public#124]
In the [v2.0.0 branch of graph.js](https://github.com/mhelvens/graph.js/tree/v2.0.0), I'm introducing a subclass of `Graph`, tentatively called `GraphOO`. Being a behavioral subtype, all `Graph` tests should also pass for `GraphOO`.

To avoid duplicating those tests, I put them in a [separate file](https://github.com/mhelvens/graph.js/blob/v2.0.0/test/spec-template.es6.js), parametrized by graph class.

OK, here's the problem: Wallaby doesn't seem to like this arrangement, or perhaps I'm doing something wrong. All tests are executed, but none of them 'count'. The Failing Tests tab says:

```
No failing tests, 0 passing
```

The Wallaby Console tab looks like this:

```
...
...
Finished executing 918 affected test(s)
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'is present',
  id: 100001,
  log: undefined,
  filesInvolved: 
   [ 'test/helpers.es6.js',
     'test/spec-template.es6.js',
     'src/graph.es6.js' ] }
...
...
```

I get one of those errors for each test.

**Comment by ArtemGovorov** [comment]
You're not doing anything incorrectly, it's current wallaby.js limitation. In order to run tests in parallel and incrementally, it has a requirement that test files (where `describe` and `it` reside) has to be entry points.

As a workaround for now I may suggest to place your `specs(GraphClass)` function right in the entry test file, construct both Graph and GraphOO there and invoke the function twice from there.

**Comment by ArtemGovorov** [comment]
I have a few ideas how to remove the limitation, but it may require some additional investigation.

**Comment by mhelvens** [comment]
OK, thanks!

Out of curiosity, what causes this limitation?

**Comment by ArtemGovorov** [comment]
It's a combination of things. In order to run a minimal set of tests on code changes, wallaby performs runtime analysis based on the code instrumentation to understand connections between tests and source code. When certain test `it` function runs, apart from other things wallaby records all files that participated in the function execution. Later on, it uses the list of files to find out which test file the test belongs to. In your case the list of files will contain invoked source files and `spec-template.es6.js`, which wallaby doesn't treat as a test file, because it is in the files list and not the tests list. So it gets confused and hence the message `Test without test file id`.

Moving `spec-template.es6.js` to the tests list on the other hand is not an option, because tests in the list are entry points and `spec-template.es6.js` is not.

I'll have to somehow separate these two concerns that up until now have been unified: test file and execution entry point.

**Comment by boneskull** [comment]
Is there anything we can do in Mocha itself to help on this issue?

**Comment by ArtemGovorov** [comment]
Not really, it's just the way wallaby runtime analysis currently works.

**Comment by vjpr** [comment]
> Moving spec-template.es6.js to the tests list on the other hand is not an option, because tests in the list are entry points and spec-template.es6.js is not.

I was getting the same error.

```
import makeTest from './makeTest'

describe('test', function() {
  
  it('foo', makeTest('an option'))

})
```

I fixed it by adding `./makeTest` to the tests files.

Just wanted to check if there is anything wrong with this, as it seemed in your comment that there was a potential issue. Will it affect incremental test running?

**Comment by ArtemGovorov** [comment]
@vjpr It may definitely break incremental test running, especially if webpack is used.

**Comment by vjpr** [comment]
So what is the best practice for test helpers?

**Comment by ArtemGovorov** [comment]
@vjpr If possible, test helpers need to be included in the `files` list.

**Comment by ArtemGovorov** [comment]
@vjpr And test bodies (functions) need to be in the test files (those in `tests` list).

**Comment by vjpr** [comment]
You mean like this:

```
import makeTest from './makeTest'

describe('test', function() {

  it('foo', async function() {
    makeTest.call(this, 'an option')
  })

})
```

**Comment by ArtemGovorov** [comment]
@vjpr Yes, this may actually work.

**Comment by vjpr** [comment]
But I still get `Test without test file id, most likely the test did not run`.

```
Test without test file id, most likely the test did not run { testFileIdCanNotBeDetermined: 'ReactComponent 2',
  id: 200001,
  log: 
   [ { message: 'expected [ Array(1) ] to have the same members as [ \'/tmp/src/client/component/Foo.js\' ]',
       stack: [Object] } ],
  filesInvolved: 
   [ 'src/__tests__/makeGeneratorUnitTest.js',
     'src/app/TestHelper.js',
     'src/generators/ReactComponent.js',
     'src/index.js',
     'src/app/LiveGenerator.js',
     'src/app/mixinHelpers.js',
     'src/util/template.js',
     'src/app/Environment.js',
     'src/app/FileManager.js',
     'src/__tests__/helpers.js' ] }
```

**Comment by vjpr** [comment]
Actually it seems to work...

**Comment by ArtemGovorov** [comment]
The idea is to have at least on code region of the actual test that belongs to the file marked as a test (its file is in the `tests` list).

**Comment by vjpr** [comment]
OK great! This looks like a solution.

Its also necessary to have this otherwise the red gutter notifications don't show up in the test file for failed tests.

**Comment by mhelvens** [comment]
FYI: I'd still like to see a real solution to this. It's been a while. Is it still planned?

**Comment by ArtemGovorov** [comment]
@mhelvens It is still planned (like lots of other things marked as enhancements in this repo), and I'd like to improve things in this area, but can't promise any ETA.

**Comment by jbrey** [comment]
Any news ? is it still planned ?

**Comment by ArtemGovorov** [comment]
@jbrey No news yet, will post some here when this changes.

**Comment by damonmaria** [comment]
I too am striking this same issue. One of the main problems with it is that the failures are hidden because the "Failing tests" tab says `No failing tests`, but if you click on "Wallaby console" then you can see the error messages. The only other hint is if you happen to be looking at the right file and see the grey dots against the test code. 

Would it be possible, if there's `Test without test file id` errors, that this is reported in the "Failing tests" tab. Otherwise it's easy to have broken tests and not realise.

**Comment by ArtemGovorov** [comment]
> Otherwise it's easy to have broken tests and not realise.

Good point. From the core v1.0.313, if any of the `Test without test file id` is failing, it is reported to the `Failing Tests` tab as well.

**Comment by mhelvens** [comment]
I'd like to request that you give this issue a higher priority. It's 18 months old now. It would be fantastic if a fix could be introduced by the end of the month, as I'll be focusing on some of my older projects again that are still compromised by this problem.

**Comment by ArtemGovorov** [comment]
We have added *some* support for the scenario (published in core v 1.0.316), it is experimental at this stage, let us know how it goes for you.

**Comment by mhelvens** [comment]
Seems to be working well, at least on the scenario described in my initial bug report. Thanks!

May I ask what you mean by "_some_ support"? Are there limits?

**Comment by ArtemGovorov** [comment]
@mhelvens Awesome, thanks for checking. By "some support" I mean that only `jasmine` and `mocha` now support shared tests in a different file with wallaby. Still have to investigate how/if it's possible to make it work for other testing frameworks that we support.

**Comment by mhelvens** [comment]
Fair enough. I am satisfied with this support, but I'll leave it up to you to close the issue when you see fit.

Thanks again!
