### ISSUE TITLE
Support Storybook Storyshots (typescript)

### ISSUE THREAD

**Issue by goldenbearkin** [wallabyjs/public#1249]
### Issue description or question
similar to #1150, we would like to use storybook storyshots but with typescript. We use create-react-app-typescript to build the structure. We are able to run test under yarn test/ npm test. When use wallabys, we got error as below:

![screen shot 2017-08-01 at 5 45 02 am](https://user-images.githubusercontent.com/11225712/28799813-9de0ccf6-767c-11e7-99b6-837943a9e844.png)

Repo for reproduction can be found here:
https://github.com/goldenbearkin/react-jest

### Wallaby.js configuration file

```javascript
const path = require('path');

module.exports = function (wallaby) {
  process.env.NODE_PATH +=
    path.delimiter +
    path.join(__dirname, 'node_modules') +
    path.delimiter +
    path.join(__dirname, 'node_modules/react-scripts-ts/node_modules');
  require('module').Module._initPaths();

  // Babel needs this
  // create-react-app-typescript does not use this
  // process.env.NODE_ENV = 'development';

  return {
    files: [
      'src/**/*.ts*',
      '!src/**/*.test.ts*',
      '.storybook/config.js'
    ],

    tests: [
      'src/**/*.test.ts*',
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    setup: (wallaby) => {
      wallaby.testFramework.configure({
        moduleNameMapper: {
          '^.+\\.(jpg|jpeg|png|gif|svg)$': require.resolve('react-scripts-ts/config/jest/fileTransform.js'),
          '^.+\\.css$': require.resolve('react-scripts-ts/config/jest/cssTransform.js')
        }
      });
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version
Version 1.14.2 (1.14.2)

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. I have sent you [the PR with the config change](https://github.com/goldenbearkin/react-jest/pull/1) to make it work.

The major change (fixing the reason why it didn't work) is to add [a preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) that changes your `.storybook/config.js` on the fly and makes it load `.js` files, instead of `.tsx`. Alternatively, you could just put some conditional logic into the file, checking `if (global.wallaby)...` but I thought the solution without changing the file is cleaner.

The change is required because wallaby TS compiler saves pre-compiled `.ts`/`.tsx` files as `.js`.

Other changes are including `.snap` files to your `files` list, fixing test(s) patterns (to not include the `.snap` files), [configuring TS compiler](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) to use your tsconfig files (by default wallaby is using only `tsconfig.json`, so I included the `tsconfig.test.json` as well).

Hope it helps.
