### ISSUE TITLE
Completely disable TypeScript postprocessor?

### ISSUE THREAD

**Issue by TheOtherSamP** [wallabyjs/public#1261]
I'm being rather silly and writing my own typescript postprocessor with some custom behaviour. For the most part it's working, though I'm running up against some hard-to-debug issues with line-numbers that I'm struggling to isolate at the moment.

Without knowing the intricacies of the inbuilt typescript processing, I'm unsure if the default behaviour is interfering with mine. Currently I'm "disabling" it like so:

```ts
compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
        noEmit: true
     })
},
```
Does this completely disable everything Wallaby is doing by default? Is there a better way to disable it?

**Comment by ArtemGovorov** [comment]
Could you please tell a bit more about your environment:
- Is it browser or node? Are you using the [webpack postprocessor](https://wallabyjs.com/docs/integration/webpack.html) as well?
- Is all your custom logic located in a postprocessor? How does your wallaby config look like?
- Out of curiosity, what custom behaviour are you trying to add?

**Comment by TheOtherSamP** [comment]
This is node, VSCode, no webpack in sight. I'm pretty much just messing around with an idea in a temporary prototyping project here, so there's not much fancy about the environment or config other than the postprocessor.

```js
module.exports = function(wallaby) {
    return {
        files: [
            "tsconfig.json",
            "src/test.ts"
        ],

        tests: [
            "tests/**/*.test.ts"
        ],

        env: {
            type: "node",
            runner: "node"
        },

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
                noEmit: true
            })
        },

        postprocessor: (wallaby) => {
            const builder = require("./build/wallaby-builder");
            return builder.processor.update(wallaby);
        }
    }
};
```

I've been messing around with putting together a library of types for typescript, where the whole library is declaration files and "operator" types. See [typical](https://github.com/tycho01/typical) for a similar project.

Writing tests for that is hard, as really you're testing that each unit _compiles_, rather than runs. I wrote a typescript transformer than takes test files in the standard `describe`/`it` format and replaces the bodies of the tests with throw statements for any semantic errors within the original body.

So 
```ts
it("is a demo test", () => {
    type A = B;
}
```
becomes
```ts
it("is a demo test", () => {
    throw new Error("Cannot find name 'B'.");
}
```

This allows me to run this as a normal set of tests, which is really nice. But I've been playing with Wallaby recently and wanted to get it working here. So far I've got the custom postprocessor working to the point where it uses the transformer and tests run correctly. Now I'm working on the _hard_ problem of making line-numbers and things match up, wrangling source maps. Most of the tests Wallaby _knows_ are failing (they mark as failures in the count) have green boxes at the moment.

**Comment by TheOtherSamP** [comment]
There's a chance this may work better as a preprocessor, but I couldn't find an easy nice way to do that without instance persistence. I believe I'd have to load the whole project from disk and type-check it all in every preprocess step. This way I can have a single shared language-service instance.

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

There's a way to replace the built-in compiler/postprocessor with yours, however I suspect the issue with your postprocessor (that is causing the line numbers issue) is that it doesn't act as wallaby compiler (doesn't produce a set of ranges + source map).

Let me explain how the built-in TypeScript compilation works.

Wallaby TypeScript compiler (specified in the compilers section) contains a special flag (`replaceWithPostprocessor` and `postprocessor`), that tells wallaby to promote the compiler to a postprocessor. We only set the flag for TypeScript compiler, because it can't operate on a file basis and needs an access to all files (so needs to be a [postprocessor](https://wallabyjs.com/docs/config/postprocessor.html)).

So Wallaby TypeScript compiler is internally promoted to a postprocessor. Now, in order to display code coverage (in the right places), wallaby needs to instrument your code. To let wallaby know what regions of the original source code are coverable, wallaby compilers need to [return `ranges`  and source map](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler).

And in our TypeScript postprocessor implementation, apart from just compiling TypeScript to JavaScript, we also traverse TypeScript AST to find and return `ranges`.

Do the new compiled file promise that is returned from our postprocessor looks like:

```javascript
          createFilePromises.push(wallaby.createFile({
            path: ...,
            original: affectedFile,
            content: result.code,
            sourceMap: JSON.parse(result.sourceMap),
            ranges: ranges,
            order: affectedFile.order
          }));
```

Note that we pass `ranges`. We create the ranges array by traversing the TypeScript `languageService.getProgram().getSourceFile(affectedFile.fullPath)` AST visitor.

So `ranges` + the source map (from the TypeScript -> JavaScript compilation) is enough for wallaby to correctly display the code coverage.

Now, here's how you could implement your custom TS compiler/postprocessor and replace the built-in one:
- update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update),
- remove your `postprocessor` setting (extract the value to a variable), we'll use compiler that will be automatically promoted to a postprocessor.
- add a compiler that returns `replaceWithPostprocessor: true` and the `postprocessor` for the `**/*.ts?(x)` file pattern (important to use this pattern to completely replace wallaby's default TS compiler):

```javascript
var postprocessor = (wallaby) => {
            const builder = require("./build/wallaby-builder");
            return builder.processor.update(wallaby);
};
...
compilers: {
            '**/*.ts?(x)': () => ({
              replaceWithPostprocessor: true, 
              postprocessor: postprocessor 
            })
},
```
- in your postprocessor, for all file you compile (and call `wallaby.createFile({...})` for), you need to get and pass the `ranges` array (to `createFile({...})`). You may read about the [format of `ranges` here](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler), and how you get them depends on how you compile your TypeScript. We do this:
- [create TS language service](https://github.com/Microsoft/TypeScript/wiki/Using-the-Language-Service-API) (`ts.createLanguageService`), store/share it between compilations. 
- For each compiled file we call `languageService.getProgram().getSourceFile(affectedFile.fullPath)` to get TypeScript file AST, 
- [Visit the AST](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#traversing-the-ast-with-a-little-linter) and collect `ranges` for things that should be displayed as covered (or not covered). It contains various types of expressions, including binary and conditional, but you may start with just getting ranges for `ts.SyntaxKind.ExpressionStatement` (that should cover the majority of simple cases), and later add the rest gradually if you need to.

Hope it makes sense.

**Comment by TheOtherSamP** [comment]
Wow, that's a _great_ answer, thanks!

I've actually already got the ranges stuff (mostly) working, though I do suspect it may be part of where my issue lies. If I take the transformer out, my typescript building _seems_ to function as well as the inbuilt, though I'm probably missing a few things somewhere.

The main issue though (I think) is making the source map match up after the transformer's done its thing and chopped stuff up.

I might be being dumb here (I really should have taken a sleep break a while ago) but I can't actually get that `replaceWithPostprocessor` solution to work. I'm using the _exact_ snippets you provided there, but for some reason I'm getting:

```
​​Failed to run compilers on tests/test.test.ts, Error: Processor must be an async function with two params, where last param is done callback, or sync function with one param and returning the result.​​
```

Which, as far as I can see, it is. Any idea what's going on there?

**Comment by ArtemGovorov** [comment]
> `​​Failed to run compilers on tests/test.test.ts, Error: Processor must be an async function with two params, where last param is done callback, or sync function with one param and returning the result.​​`

Oops, sorry, I have added a function where there shouldn't be one. Here's the correct example (also fixed in above):

```javascript
    compilers: {
      '**/*.ts?(x)': {
        replaceWithPostprocessor: true,
        postprocessor: postprocessor
      }
    },
```

**Comment by TheOtherSamP** [comment]
Oh hah, oops. Always the little things, thanks.

**Comment by TheOtherSamP** [comment]
Sorry to bother you further, you've been exceedingly helpful here. I just realised that the ranges may actually be completely unnecessary. Every one of my tests (post transform) is going to consist solely of zero or more `throw new Error("some message literal");` statements, so coverage isn't really an issue.

A picture's worth a thousand words and all that. This test is failing, the transformer replaces the `type` line with a `throw` statement, and Wallaby says it failed in the console and the count, but the box is green. Are the ranges still needed for making the boxes/icons line up in the tests themselves? Or is that purely a matter of source maps?

![image](https://user-images.githubusercontent.com/19550501/29201993-9a57c684-7e5b-11e7-9d81-9c4899660641.png)

**Comment by ArtemGovorov** [comment]
Correct, if you'd like the line 4 to be displayed as a source of the error, there need to be a coverable range for it. Otherwise wallaby has no idea where to display the error.

**Comment by TheOtherSamP** [comment]
That makes sense, thanks!

**Comment by TheOtherSamP** [comment]
(Almost) completely got it working now, thanks for all the help! Having discovered some extra source-mapping features in the TS compiler (oops) it would now be possible to implement this solely with a typescript transformer, were Wallaby able to support those. My custom postprocessor is now just a (slightly buggy) re-implementation of yours with one extra property on the `ts.LanguageServiceHost`.

Is there any way to supply transformers to Wallaby currently? Is that something you'd be interested in adding if not? I can make a new issue for that if it's preferable. The one caveat (and problem with a lot of the current tools' implementation of `getCusomTransformers`, though think there're plans to fix those) is that a reference to the `ts.Program` would be needed to be supplied to the transformer.

**Comment by ArtemGovorov** [comment]
> Is there any way to supply transformers to Wallaby currently?

There no such way at the moment, however we're happy to add the extension point. As we are not using any transformers at the moment, only a simple visitor, could you please specify exactly where you need to plug in?

Here is approx how the relevant code on our side looks like:

```javascript
        var output = languageService.getEmitOutput(affectedFile.fullPath);
        ...

        // Collecting ranges
        var ranges = visitor.visit(languageService.getProgram().getSourceFile(affectedFile.fullPath));

        var result = {};
        output.outputFiles.forEach(outputFile => {
          var ext = path.extname(outputFile.name);
          if (ext === '.map') {
            result.sourceMap = outputFile.text
          }
          else if (ext === '.js' || ext === '.jsx') {
            result.code = outputFile.text;
          }
          else {
            logger.debug('Unexpected output file: %s', outputFile.name);
          }
        });

        if (result.sourceMap) {
          createFilePromises.push(wallaby.createFile({
            // When some modules system is used, preserving the original file name, just changing the file extension
            path: ...,
            original: affectedFile,
            content: result.code,
            sourceMap: JSON.parse(result.sourceMap),
            ranges: ranges,
            order: affectedFile.order
            ...
          }));
        }
...
// visitor

  visit = function (node) {
      var v = visitor[node.kind];
      v && v(node);
      self._parent = node;
      ts.forEachChild(node, visit);
    };

    // a few functions of to collect ranges from various types of statements/expressions, like:
    visitor[ts.SyntaxKind.ExpressionStatement]
      = visitor[ts.SyntaxKind.ReturnStatement]
      =
      function (node) {
        collectRange(node);
      };

    visitor[ts.SyntaxKind.ConditionalExpression]
      =
      function (node) {
        collectRange(node.whenTrue);
        collectRange(node.whenFalse);
      };
     ....
```

**Comment by TheOtherSamP** [comment]
That's great, thanks.

The extension point actually wouldn't be there, it would be in the `LanguageServiceHost` supplied to `createLanguageService`.

There's an optional property `getCustomTransformers` that takes a function returning `CustomTransformers`, which looks like this:

```ts
interface CustomTransformers {
    /** Custom transformers to evaluate before built-in transformations. */
    before?: TransformerFactory<SourceFile>[];
    /** Custom transformers to evaluate after built-in transformations. */
    after?: TransformerFactory<SourceFile>[];
}
```

Mine just looks like this right now:

```ts
getCustomTransformers: () => ({before: [diagnosticTransformer(this.getService().getProgram())]})
```

Tools like ts-loader expose this directly by letting you just provide this function, as seen [here](https://github.com/TypeStrong/ts-loader#getcustomtransformers-----before-transformerfactory-after-transformerfactory---).

However, for it to be useful for my case (and many others) it would need to provide a reference to `ts.Program`, so I'd suggest adding a `(program: ts.Program)` parameter to that function and otherwise copying the convention. I believe many other tools will likely make that change soon as it's essential to using much of the power of transformers.

I hope that's a clear enough explanation...

**Comment by ArtemGovorov** [comment]
So, before I implement it, I thought I'd run it past you to make sure it'd work for you.

In your wallaby config, you'll be able to pass an array of custom transformers to the standard wallaby TypeScript compiler/postprocessor like this:

```javascript
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
                getCustomTransformers: (program) => {
                  return [
                    {before: [diagnosticTransformer(program)]}
                  ]
                }
            })
        },
```

The `getCustomTransformers` will be attached to the language service that we create for TypeScript (curried with the language service `getProgram()` program), so that you may use it to instantiate/setup your transformer.

Would this work for you?

**Comment by TheOtherSamP** [comment]
That's perfect, thanks!

**Comment by ArtemGovorov** [comment]
Done. 
Please upgrade to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, and you may now do:

```javascript
        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
                getCustomTransformers: (program) => {
                  return [
                    {before: [diagnosticTransformer(program)]}
                  ]
                }
            })
        },
```

**Comment by ArtemGovorov** [comment]
Let me also thank you for clearly explaining what you wanted us to implement in such a detail. It's a pleasure to implement features like this.

**Comment by TheOtherSamP** [comment]
*deletes a tonne of hacky code*

Perfect, thanks! That's got to be the best turn around time on a feature request I've experienced, that was great. Now to hunt down the bug that I had _hoped_ was being caused by my dodgy ranges implementation, but that's still there so must be my source maps. Also sleep, I should do that. 

No big deal now of course, but you've got an extra array in that example by the way.

Seriously, 10/10 githubbing experience here.

**Comment by ArtemGovorov** [comment]
> No big deal now of course, but you've got an extra array in that example by the way.

Thanks! Fixed the example.
