### ISSUE TITLE
Can't import enum in Wallaby

### ISSUE THREAD

**Issue by ksnyde** [wallabyjs/public#1262]
I thought I was hitting a Typescript problem so I posted the following to Stackoverflow:

https://stackoverflow.com/questions/45642413/weird-ts-import-problems/45645862#45645862

But it appears that at this point everything DOES work from the terminal but wallaby continues to have this error. Here is the issue again:

I have a npm module that I have used for a number of my Typescript projects called `common-types` (repo: https://github.com/lifegadget/common-types). Recently added an enum for my work with Firebase projects called `FirebaseEvent` which is defined as:

    export enum FirebaseEvent {
      value = 'value',
      child_added = 'child_added',
      child_moved = 'child_moved',
      child_removed = 'child_removed',
      child_changed = 'child_changed'
    };

The problem I'm having is that when I try and import that enum with the following expression:

    import { FirebaseEvent } from 'common-types';

I get the following error: 

[![enter image description here][1]][1]

For reference sake, line 5 of the common-types file is:

     export interface IDictionary<T = any> {
       [key: string]: T;
     }

And I strongly suspect that error message is a red-herring as if I import any of the following it works without error:

    import { IDictionary } from 'common-types';
    import { IDictionary, datetime } from 'common-types';

And yet any import that includes `FirebaseEvent` -- such as below -- fails with the same error message as above:

    import { IDictionary, FirebaseEvent } from 'common-types';

  [1]: https://i.stack.imgur.com/u9Hv0.png

-----

You'll notice in the Stackoverflow discussion that a very odd "solution/workaround" has been suggested but one that seems to work. I have added this workaround into the current `common-types` module which is involved in this issue but the problem persists in Wallaby.

**Comment by ArtemGovorov** [comment]
The issue here is that your `common-types` exports not only type definitions, but also some **executable** code implemented in TypeScript. Most of the tools (including wallaby and `ts-node`) expect node modules to export executable **JavaScript** code, so the code in the `node_modules` folder is not compiled by TS compiler (in wallaby and `ts-node`) because the folder is ignored.

There's a difference between exporting type definitions - that is not an executable code and is only used during the compile time, and exporting classes (even empty) or enums. You may have a look at how only [type definitions from your module are compiled to an empty module](https://www.typescriptlang.org/play/#src=%0A%2F**%20%0A%20*%20A%20Javascript%20hash%20which%20allows%20for%20any%20set%20of%20keys%0A%20*%2F%0Aexport%20interface%20IDictionary%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20string%5D%3A%20T%3B%0A%7D%0A%0A%2F**%0A%20*%20A%20numeric%20Javascript%20array%0A%20*%2F%0Aexport%20interface%20INumericArray%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20number%5D%3A%20T%3B%0A%7D%0A%0A%2F**%20A%20function%20for%20sorting%20JS%20arrays%20*%2F%0Aexport%20type%20SortingFunction%20%3D%20(a%3A%20any%2C%20b%3A%20any)%20%3D%3E%20number%3B%0A%0A%2F**%20a%20string%20of%20the%20format%3A%20%22YYYY-MM-DD%22%20*%2F%0Aexport%20type%20datestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22HH%3Amm%3Ass%22%20*%2F%0Aexport%20type%20timestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22UTC%22%20*%2F%0Aexport%20type%20timezone%20%3D%20string%3B%0A%2F**%20string%20representation%20of%20datetime%20in%20format%20of%20%222016-07-17T13%3A29%3A11.652Z%22%20*%2F%0Aexport%20type%20datetime%20%3D%20string%3B%0A%2F**%20unix%20epoch%20datetime%20format%20(aka%2C%20seconds%20since%201970)%20*%2F%0Aexport%20type%20epoch%20%3D%20number%3B%0A%0A), however if you add an enum, or a class export, then [some executable JavaScript is generated as a result](https://www.typescriptlang.org/play/#src=%0A%2F**%20%0A%20*%20A%20Javascript%20hash%20which%20allows%20for%20any%20set%20of%20keys%0A%20*%2F%0Aexport%20interface%20IDictionary%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20string%5D%3A%20T%3B%0A%7D%0A%0A%2F**%0A%20*%20A%20numeric%20Javascript%20array%0A%20*%2F%0Aexport%20interface%20INumericArray%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20number%5D%3A%20T%3B%0A%7D%0A%0A%2F**%20A%20function%20for%20sorting%20JS%20arrays%20*%2F%0Aexport%20type%20SortingFunction%20%3D%20(a%3A%20any%2C%20b%3A%20any)%20%3D%3E%20number%3B%0A%0A%2F**%20a%20string%20of%20the%20format%3A%20%22YYYY-MM-DD%22%20*%2F%0Aexport%20type%20datestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22HH%3Amm%3Ass%22%20*%2F%0Aexport%20type%20timestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22UTC%22%20*%2F%0Aexport%20type%20timezone%20%3D%20string%3B%0A%2F**%20string%20representation%20of%20datetime%20in%20format%20of%20%222016-07-17T13%3A29%3A11.652Z%22%20*%2F%0Aexport%20type%20datetime%20%3D%20string%3B%0A%2F**%20unix%20epoch%20datetime%20format%20(aka%2C%20seconds%20since%201970)%20*%2F%0Aexport%20type%20epoch%20%3D%20number%3B%0A%0A#src=%0A%2F**%20%0A%20*%20A%20Javascript%20hash%20which%20allows%20for%20any%20set%20of%20keys%0A%20*%2F%0Aexport%20interface%20IDictionary%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20string%5D%3A%20T%3B%0A%7D%0A%0A%2F**%0A%20*%20A%20numeric%20Javascript%20array%0A%20*%2F%0Aexport%20interface%20INumericArray%3CT%20%3D%20any%3E%20%7B%0A%20%20%5Bkey%3A%20number%5D%3A%20T%3B%0A%7D%0A%0A%2F**%20A%20function%20for%20sorting%20JS%20arrays%20*%2F%0Aexport%20type%20SortingFunction%20%3D%20(a%3A%20any%2C%20b%3A%20any)%20%3D%3E%20number%3B%0A%0A%2F**%20a%20string%20of%20the%20format%3A%20%22YYYY-MM-DD%22%20*%2F%0Aexport%20type%20datestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22HH%3Amm%3Ass%22%20*%2F%0Aexport%20type%20timestring%20%3D%20string%3B%0A%2F**%20a%20string%20of%20the%20format%3A%20%22UTC%22%20*%2F%0Aexport%20type%20timezone%20%3D%20string%3B%0A%2F**%20string%20representation%20of%20datetime%20in%20format%20of%20%222016-07-17T13%3A29%3A11.652Z%22%20*%2F%0Aexport%20type%20datetime%20%3D%20string%3B%0A%2F**%20unix%20epoch%20datetime%20format%20(aka%2C%20seconds%20since%201970)%20*%2F%0Aexport%20type%20epoch%20%3D%20number%3B%0A%0Aexport%20enum%20FirebaseEvent%20%7B%0A%20%20value%20%3D%20'value'%2C%0A%20%20child_added%20%3D%20'child_added'%2C%0A%20%20child_moved%20%3D%20'child_moved'%2C%0A%20%20child_removed%20%3D%20'child_removed'%2C%0A%20%20child_changed%20%3D%20'child_changed'%0A%7D%3B).

This is why when you import:
```javascript
import { IDictionary } from 'common-types';
import { IDictionary, datetime } from 'common-types';
```
it works. Because having or not having the import in your code change **absolutely nothing** in the generated JavaScript. These are pure type definitions that are only used for type checking and do not affect the resulting JavaScript at all.

Now when you import an enum:
```javascript
import { FirebaseEvent } from 'common-types';
```
there's some executable JavaScript code that need to be generated. Because the values of the enum has to be accessible not just during the compile time, but in runtime as well.

To make it work, you may just let tools know that your module needs to be compiled (not just used for pure type definitions). As I said, [`ts-node` by default ignores `node_modules`](https://github.com/TypeStrong/ts-node/blob/1385d4791222e0619d97ac1150d83ea26244cc8f/src/index.ts#L193), so [using `ts-node` register and passing `false` to as the value of the `ignore` setting](https://github.com/ArtemGovorov/wallaby-1262/blob/master/wallaby.js#L18) should do the trick. 

I have [created the example repo with the working solution](https://github.com/ArtemGovorov/wallaby-1262).

Hope it makes sense.

P.S. I'm not sure if the hack with the empty class export is really required (wallaby doesn't need it and works with or without it).

**Comment by ksnyde** [comment]
Since `enum` was a typescript-only construct I wasn't considering that it would need a run-time component but now that you say it it does make sense. I think the best solution is just to have my `common-types` repo transpiled to JS with the typing file next to it. This should allow me just to remove the empty class altogether.

**Comment by ksnyde** [comment]
That's based off of the `common-types` version 1.2.0: https://github.com/lifegadget/common-types/commit/13dadf947e101886e57a316a43117b4272f24c78

**Comment by ksnyde** [comment]
Ok nevermind. I had reversed the reference to `main` and `types` in package.json. Fixed. Thanks a ton.
