### ISSUE TITLE
Jest vs Wallaby.js Returning Different Results

### ISSUE THREAD

**Issue by MattMorgis** [wallabyjs/public#1263]
### Issue description or question
Running two tests with Jest returns 2 passes. Running the same two tests with Wallaby.js (w/`testFramework: 'jest`) in Visual Studio Code returns two failures. 

The tests are written in TypeScript. I setup an [example project here.](https://github.com/MattMorgis/WallabyTypeScriptExample)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.ts',
      '!src/**/*.test.ts'
    ],
    tests: [
      'src/**/*.test.ts'
    ],
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code: **v.1.15.0**

### OS name and version

OSX: **v10.12.6**

**Comment by MattMorgis** [comment]
[That](https://github.com/MattMorgis/WallabyTypeScriptExample/pull/1) did it! Thank you!

**Comment by ArtemGovorov** [comment]
Thanks for providing the example repo.

Quick inspection of the response.text helped me to see what the issue is:

![1263](https://user-images.githubusercontent.com/979966/29255309-5c6d6cfe-80e3-11e7-96fc-23028df59496.gif)


As the docs specify, you need to [include all file used by your code/tests in the `files` list](https://wallabyjs.com/docs/config/files.html).
I [have sent you the pull request](https://github.com/MattMorgis/WallabyTypeScriptExample/pull/1) to make the config work.

**Comment by MattMorgis** [comment]
That did it! Thank you!
