### ISSUE TITLE
Possible race condition with process.chdir

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1268]
### Issue description or question
When running Wallaby and using ``process.chdir`` to a directory outside of the current root directory, ``Error: Cannot find module './jest.config'`` is thrown when modifying the test quickly.

I am not sure this is an issue with Wallaby or an issue with Jest + how fast Wallaby updates. Does not happen with ``jest --watch``. Likely only happens with Jetbrain's products because of the auto-save. Also a likely fix is to add a delay for wallaby in the config file.

[chrisblossom/wallaby-issue-1268/src/issue.test.js#L27](https://github.com/chrisblossom/wallaby-issue-1268/blob/677f333773e5469875a304697428093079241a58/src/issue.test.js#L27
)
### Code editor or IDE name and version

```
WebStorm 2017.2.2
Build #WS-172.3757.55, built on August 15, 2017
JRE: 1.8.0_152-release-915-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```

### OS name and version

``Mac OS X 10.12.6``

**Comment by ArtemGovorov** [comment]
As usually, thanks a lot for providing the repo! Makes it so much easier to address issues/answer questions.

I have send you [the pull request](https://github.com/chrisblossom/wallaby-issue-1268/pull/1) to make the setup work. 

Here's what happens: when you change your code, wallaby stops an existing test run as fats as possible. 

So for example it will may not wait until some async after/afterEach hook gets executed (who knows how much time an async operation may take, but you already have the next run scheduled, so probably don't want to wait). Or for example, if you introduce an infinite loop in your code, and keep changing it, wallaby.js will just stop the execution (and it won't be able to execute any hooks anyway).

As an alternative to the PR, you may actually make wallaby to work close to how Jest works by using [the `workers.recycle: true` setting](https://wallabyjs.com/docs/integration/node.html#node-process-reuse). This way you won't have to worry if the cleanup code ran or not, because the whole process is recycled. It will however make wallaby run only as fact as plain Jest runs (which is a bit slower than how Wallaby with process re-use is working).

Hope it makes sense.

**Comment by chrisblossom** [comment]
Yes it does, thank you! It isn't something I currently need fixed as it is only affecting one of my test files. I just wanted to make you guys aware of a potential issue.
