### ISSUE TITLE
How do I include external libraries in my tests?

### ISSUE THREAD

**Issue by alesch** [wallabyjs/public#128]
For example underscore.js?

I can see in the sample projects that for Chai I can use: `var assert = chai.assert;` and include chai.js as a source file.

But for underscore?
I would usually use: `_ = require('underscore')`

Thanks!

PS: I guess I would prefer to use the same syntax when running my tests with Wallaby than when I run them directly with Mocha. So I don't need to change my code depending on the runner.

**Comment by ArtemGovorov** [comment]
You can include libraries the same way you would do it in Mocha. 
Is your question about browser tests (with webpack or browserify) or node.js tests? Where are you normally assigning `_ = require('underscore')`? 
If you do it in every test file, you can still do it. Otherwise you may use wallaby [`bootstrap` function](https://github.com/wallabyjs/public#bootstrap-setting) to assign global `_` and use it from every test.

**Comment by ArtemGovorov** [comment]
Please let me know more about your environment and I can create a sample for you.

**Comment by alesch** [comment]
Sorry for the late reply. Thanks for your answer.
