### ISSUE TITLE
Wallaby and constructors

### ISSUE THREAD

**Issue by Lloyc** [wallabyjs/public#1298]
### Issue description or question

I've noticed a weird behavior with only constructors. A class with just a constructor like the following image
![image](https://user-images.githubusercontent.com/11031281/30289793-45f0ba48-96fb-11e7-9e16-8fc38da842c4.png)
is not counted by Wallaby in the total coverage, even if this constructor is called somewhere. If we add a statement like an if(true), wallaby will count it.

![image](https://user-images.githubusercontent.com/11031281/30289961-d9143b06-96fb-11e7-8fe8-59bbca06450d.png)

### Wallaby.js configuration file

```
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js'],
  resolve: {
    alias: {
      'kendo-ui/js': '@progress/kendo-ui/js',
      'kendo-ui': '@progress/kendo-ui/js/kendo.core.js'
    }
  }
});

module.exports = function () {
  return {
    files: [{
        pattern: 'src/**/*.ts',
        load: false
      },
      {
        pattern: 'test/unit/fake-mvc-service.ts',
        load: false
      },
      {
        pattern: 'test/unit/setup.ts',
        load: false
      }
    ],

    //filesWithNoCoverageCalculated: ['src/**/*dal.ts'],

    tests: [{
      pattern: 'test/unit/**/*.spec.ts',
      load: false
    }],

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```
### Typescript configuration file
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "sourceMap": true,
    "target": "es5",
    "module": "amd",
    "declaration": false,
    "noImplicitAny": false,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "lib": ["es2015", "dom"],
    "allowJs": true
  },
  "exclude": [
    "node_modules",
    "scripts"
  ],
  "filesGlob": [
    "./src/**/*.ts",
    "./test/**/*.ts",
    "./custom_typings/**/*.d.ts"
  ],
  "atom": {
    "rewriteTsconfig": false
  }
}
```

### Code editor or IDE name and version
Visual Studio Code v 1.15.1

### OS name and version
Windows 8.1

**Comment by ArtemGovorov** [comment]
This is by design and it's not specific to constructors, but to all functions. So for example if you have an empty function

```javascript
function f() {
}
```
the coverage will be same same regardless of whether or not you call it.

This is because wallaby calculates Statement/Branch coverage. So for the coverage purposes it considers statements/expressions that can be either executed or not executed. And because there are no executable statements in the function/constructor, the code coverage doesn't changes regardless of whether it is called or not.

Consider another example with 3 lines of code (in program scope, or within some function):

```
var a = 0;

var b = 0;
```

Lines 1 and 3 will be considered for code coverage calculation. The empty line 2 will not be considered for code coverage calculation for the same reason as an empty constructor or function, because there's no executable statement on it.

Hope it makes sense and answers your question.

**Comment by Lloyc** [comment]
Thank you @ArtemGovorov. It makes sense now.
