### ISSUE TITLE
Show variable values on hover

### ISSUE THREAD

**Issue by pelotom** [wallabyjs/public#1301]
I really love the `/*?*/` feature for seeing the runtime value of an expression... it would be super convenient to be able to just hover over an identifier and get that information! I know this is something VSCode supports as it's used to show TypeScript type information, and this would be a natural runtime counterpart to that.

**Comment by smcenlly** [comment]
Closing this issue as it has been addressed. We added the `Show Value` command to Wallaby in September 2018 that effectively addresses this issue. In VS Code, this displays the result in a hover. Unfortunately we cannot always display the value on hover due to system resource constraints (it's simply not viable to store/process all the information to have that available). Our [time travel debugger](https://wallabyjs.com/docs/intro/time-travel-debugger.html) does allows you to select an object, object property, parameter, expression or variable that you want to view and will display the information for you immediately upon selection.
