### ISSUE TITLE
Mocha tests pass, wallaby tests fail with async code

### ISSUE THREAD

**Issue by whydoidoit** [wallabyjs/public#1310]
Issue description or question

Wallaby tests fail and Mocha pass. 

Updated repo:
https://github.com/whydoidoit/3r

Wallaby.js configuration file
```
module.exports = function (wallaby) {
    return {
        files: [
            'src/**/*.js',
            {pattern: 'src/node_modules/**/*.js', ignore: false, load: true, instrument: true},
            {"pattern": "src/test/**/*.js", ignore: true}
        ],
        tests: [
            'src/test/**/*.js'
        ],
        env: {
            type: 'node'
        },
        testFramework: 'mocha'
    }
}
```
Code editor or IDE name and version

IntelliJ IDEA v2017.2

OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for updating the repo.

Looks like you have some promises that are rejected without catching the rejection. This is deprecated in Node and will terminate node process in future, so wallaby by default reports it as an error. Actually Mocha also reports the error:

![screen shot 2017-09-18 at 12 35 40 pm](https://user-images.githubusercontent.com/979966/30527606-fe3d2916-9c6d-11e7-95f3-8147b8ee41d0.png)

just doesn't mark the test run as failed. Wallaby is a bit stricter in this regard and reports the error as a test run error.

I'd recommend investigating why some promises rejection is unhandled (because it may cause troubles in future node versions). However, if you'd just like wallaby not to report the error and let the tests pass, you may [use the `reportUnhandledPromises : false` setting](https://wallabyjs.com/docs/config/overview.html#unhandled-promise-rejections):

```javascript
 module.exports = function () {

    return {
      ...
      reportUnhandledPromises: false
    };
  };
```

**Comment by bashmish** [comment]
I spent a couple of hours debugging my test and trying to understand why it works it Wallaby.js and not in Karma. Apparently it is because I was trying to catch uncaught error via `window.addEventListener('error', cb)` which didn't work in Karma while in Wallaby.js `reportUnhandledPromises` is set to `true` by default and it makes it work for unhandled promise rejections too.

I don't think this default is really useful, because of 2 reasons:
1. This is not how testing frameworks behave nowadays (and there is no config option like `reportUnhandledPromises` to align this behavior with Wallaby.js, or is there?).
2. This is a very unexpected default.

I would expect `reportUnhandledPromises` to be `false` by default.

Am I missing smth?

**Comment by ArtemGovorov** [comment]
We report unhandled promise rejection because they are already deprecated in node:

`Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

So to avoid being caught by surprise in future you either need to handle them or set the setting to `false`.

**Comment by bashmish** [comment]
@ArtemGovorov then it makes even more sense to have it `false` by default, doesn't it.

Btw, I ran into this while testing in browsers and there was no deprecation message at all.

**Comment by ArtemGovorov** [comment]
@bashmish The idea is that unhandled promise rejections are not good at all. And they may either need to be fixed (that is recommended, and that's why we report them by default), or suppressed with the setting at your own risk.

**Comment by bashmish** [comment]
@ArtemGovorov yeah, I agree that they need to be fixed. But while reporting you don't provide any hint about that. You just delegate it to the normal global uncaught error handler and as a test writer you see it in your callback here `window.addEventListener('error', cb)`.

I was testing extension to a 3rd party ES class. In my class I throw an exception and I wanted to make sure it is properly thrown. I didn't even know that my extension code was executed in the promise context in the 3rd party code. And test in Wallaby.js worked, but not in Karma. That was extremely misleading.

**Comment by ArtemGovorov** [comment]
@bashmish Could you please describe your scenario in a bit more detail, so that we could try to see if there's something that can be done without changing the default? 

All we do in Wallaby with the setting is basically this:

```js
    if (reportUnhanledPromises) {
      window.addEventListener('unhandledrejection', function (e) {
        ...
        throw e;
      });
    }
```

**Comment by bashmish** [comment]
@ArtemGovorov I has already refactored my code to throw outside of the Promise context. And I has already learned about his behavior of Wallaby.js, hopefully will not run into hours of debugging again.

The problem is not that code or tests can't be fixed. And of course you can also change the config to deactivate `reportUnhanledPromises `.

The problem is that this is not a useful default in the way how it is currently implemented, and even creates confusion while debugging issues in tests. Just my opinion maybe. Let's see if there will be moe people who also find it misleading. For now I have no other questions or suggestion regarding it.

**Comment by ArtemGovorov** [comment]
@bashmish We do actually change the error message to prefix it with the `Unhandled promise rejection:`:

```js
e.message = 'Unhandled promise rejection: '
```
Wasn't the message visible/helpful?

Anyway, I see you point, and I think it actually makes sense to change the default for browser environment the way you've suggested. We'll discuss the matter internally with the team and make the change in one of the future versions.

**Comment by ArtemGovorov** [comment]
@bashmish We have had changed the setting's default to `false` by default for browser environments and published the new version. After your [Wallaby core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) gets updated to v1.0.633, you may remove the setting from your Wallaby config.
