### ISSUE TITLE
[$compile:tpload] Failed to load template

### ISSUE THREAD

**Issue by ptomaszi** [wallabyjs/public#1311]
The component I am testing is using the "templateUrl" to provide a template:

```
import { Component, Inject, Input, Output, EventEmitter, OnChanges } from 'ng-metadata/core';

@Component({
    selector: 'diContactList',
    templateUrl: 'src/app/portal/parties/contacts/list/contact-list.component.html'
})
export class ContactListComponent implements OnChanges {
```

Then I have a corresponding unit test:

```
import { bundle, getInjectableName, NgModule, Component } from 'ng-metadata/core';

describe('ContactListComponent', () => {
    @Component({
        selector: 'test-component',
        template: `
            <di-contact-list>
            </di-contact-list>`
    })
    class TestComponent {
        constructor() {}
    }
    @NgModule({
        declarations: [TestComponent, ContactListComponent]     
    })
    class TestNgModule { } 
    
    let $compile: ng.ICompileService;
    let $rootScope: ng.IRootScopeService;
    let $scope: ng.IScope;
    let render: IRender<TestComponent>;
    let sut: ContactListComponent;
    
    beforeEach(() => {
        const TestModule: string = bundle(TestNgModule).name;
        ng.mock.module(TestModule);
    });

    beforeEach(ng.mock.inject(function($injector: ng.auto.IInjectorService) {
        $compile = $injector.get<ng.ICompileService>('$compile');
        $rootScope = $injector.get<ng.IRootScopeService>('$rootScope');
        $scope = $rootScope.$new();
        
        render = renderFactory($compile, $scope);
        sut = render(ContactListComponent).ctrl;
    }));
```

When run I am getting the following error:

> Error: [$compile:tpload] Failed to load template: src/app/portal/parties/contacts/list/contact-list.component.html (HTTP status: undefined undefined)
	http://errors.angularjs.org/1.6.5/$compile/tpload?p0=src%2Fapp%2Fportal%2Fparties%2Fcontacts%2Flist%2Fcontact-list.component.html&p1=undefined&p2=undefined

When I remove templateUrl or replace with template in the component, unit tests run correctly.

**Comment by ArtemGovorov** [comment]
I don't have much experience with AngularJs 1.x, and no experience at all with `ng-metadata`, so not even sure how is it supposed to work (outside of wallaby.js context).

I know that wallaby/karma users for Angular 2/4 project are using the `angular2-template-loader` webpack loader to process `templateUrl`s, you may see the example here: https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L21 (plus html loader https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L19). Try this approach and if it doesn't work, please share a sample Github project with a working karma config and the error from wallaby - I'll just take the way you have it working in karma and will help creating a similar wallaby config.

**Comment by ptomaszi** [comment]
Hi,

I have created a sample project which has "my.component.ts" and "my.component.spec.ts" files. The "ng-metadata" allows you to write Angular 1 components using the Angular 2 syntax. When you run tests you will get results 1 pass and 1 fail. But if you change the templateUrl to be just template then all tests will run.

https://github.com/ptomaszi/wallaby_webpack

**Comment by ArtemGovorov** [comment]
Thanks for setting up the repo.

I have created [this pull request](https://github.com/ptomaszi/wallaby_webpack/pull/3) to make wallaby config work. Here are some notes about the changes:

- [Commented out this rule of yours](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-22afadecb208f8af673f61960f51fbc9R22) because it is not a valid rule for the current version of webpack you are using in the sample repo.
- added [`.html` files](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR15) to the files list, because [wallaby needs all used files](https://wallabyjs.com/docs/config/files.html) to be listed.
- Set the [`instrument: false` flag for libraries](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR16). The [`instrument` boolean property](https://wallabyjs.com/docs/config/files.html#file-object) (true by default) determines whether the file is instrumented. Setting the property to false disables the file code coverage reporting and may prevents the file changes from triggering automatic test execution. The setting should normally be set to false for libraries, utils and other rarely changing files. Using the setting makes wallaby.js run your code faster, as it doesn’t have to perform unnecessary work.
- [Added `angular2-template-loader` and `html-loader`](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR7) as I was suggesting above (also to the `package.json`, should be in `devDependencies` though).
- [Changed the `templateUrl` to a relative path](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-757a0612010dca1cc87c816fc09347caR5). According `ng-metadata` docs, it is the way to do it:
https://github.com/ngParty/ng-metadata/blob/master/README.md#the-gist
https://github.com/ngParty/ng-metadata/blob/master/docs/recipes/component.md
- Added [missing `rxjs` dependency](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R13) required by `ng-metadata`.

If you have a different setup, and some of my changes can not be applied to it, then please update the sample repo with something close to your setup (including working versions of all dependencies) and add your **working karma config**, so I could just take the way you load/process things there to apply the same in your wallaby config.

**Comment by ptomaszi** [comment]
Hi,

I tried the solution on my project, but it did not work. I created another repository which mimics my DEV project and could you please have a look that why wallaby fails to load a template?

https://github.com/ptomaszi/portal

**Comment by ArtemGovorov** [comment]
I have sent you the pull request https://github.com/ptomaszi/portal/pull/1.

Wallaby renames `.ts` files to `.js` when it compiles them (before webpack compilation), so as [specified in the docs](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns), when specifying your file paths in context of webpack `entryPatterns` and `module.rules`, you need to use the `.js` extension, just like [I did in the previous sample](https://github.com/ptomaszi/wallaby_webpack/pull/3/files#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR7).

I have also commented out a couple of `templateUrl` to some `.html` files that are missing in the project.

Using `angular2-template-loader` is just one way to make it work, and I was asking for your working karma config in order to see if wallaby config can be closer to your karma config in this regard, but unfortunately your karma config in the provided project doesn't work.

**Comment by ptomaszi** [comment]
By changing the templateUrl to be a relative path to HTML file, makes wallaby happy, but when compiled to bundle by webpack and try to run the site, it cannot find the HTML by relative path. Maybe there is an option on the webpack to specify how to resolve templateUrls?

**Comment by ArtemGovorov** [comment]
`angular2-template-loader` [transforms `templateUrl` paths to relative paths](https://github.com/TheLarkInn/angular2-template-loader/blob/master/index.js#L12), so webpack options (like additional module paths) will not help here (because the path is relative). As specified in the `ng-metadata` docs:
https://github.com/ngParty/ng-metadata/blob/master/README.md#the-gist
https://github.com/ngParty/ng-metadata/blob/master/docs/recipes/component.md
the paths has to be specified as relative paths (try following the links and searching for `templateUrl`s - they're all relative).

I'm not sure how your bundle works with absolute paths. I can't test it, because your sample project build doesn't work (and can't test how it works in karma because it also doesn't work). Your webpack config doesn't have anything to bundle templates and the [committed bundle file](https://github.com/ptomaszi/portal/blob/master/dist/app.bundle.js) in your project has absolute paths with `templateUrl` pointing to your `src` folder. 

- How is your bundle supposed to work in production if it is referencing HTML templates like this `templateUrl: 'src/app/portal/parties/contacts/list/contact-list.component.html'`?
- Do you have a working karma config? It it's working there, I can just configure wallaby to do the same.

**Comment by ArtemGovorov** [comment]
Just a thought - perhaps you need to add `angular2-template-loader` or similar to your production bundle build so that HTML templates are resolved and inlined (which is exactly what wallaby is using `angular2-template-loader` for)?

**Comment by ptomaszi** [comment]
Yep that works now! Thanks for your support. @ArtemGovorov is there any support for debugging using the wallabyjs?

**Comment by ArtemGovorov** [comment]
@ptomaszi Awesome, thanks for the update!

> is there any support for debugging using the wallabyjs?

Wallaby supports [very powerful realtime logging](https://wallabyjs.com/docs/intro/advanced-logging.html) that can be used for debugging. I'd specifically recommend checking out the [special live comments feature](https://wallabyjs.com/docs/intro/advanced-logging.html#live-comments). With the feature you may see any values of any expressions anywhere in your code, even without setting any breakpoints and also in places where you simply can't set a classical breakpoint.

There's also this [feature request for the classic debugger](https://github.com/wallabyjs/public/issues/74) that you're already subscribed too.

**Comment by bcaleroCS** [comment]
disclaimer: im not fluent in English
After many  posts of this issue and searching on many pages, i found that the problem on my case was caused by $httpProvider.interceptors.push .... because i had a mistake setting a header on request, i deleted it and , done ... my problem was solved ... i hope that maybe this would help you
