### ISSUE TITLE
Failed to parse module

### ISSUE THREAD

**Issue by lamartire** [wallabyjs/public#1318]
### Issue description or question

Hello! Thank you for awesome tool! :smile_cat: 
I have a strange error and can't resolve it:

```bash
[Error] ​​Failed to parse node_modules/nwmatcher/src/modules/nwmatcher-cache.js, SyntaxError: Unexpected token (152:5)​​
[Error] ​​  at emitTwo (events.js:125:13)​​
[Error] ​​  at process.emit (events.js:213:7)​​
[Error] ​​  at emit (internal/child_process.js:774:12)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:141:11)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
[Error] ​​  at _combinedTickCallback (internal/process/next_tick.js:131:7)​​
[Error] ​​  at process._tickCallback (internal/process/next_tick.js:180:9)​​
```

Project works like a charm.

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      '**/*.js',
      '!**/*.spec.js'
    ],
    tests: [
      '**/*.spec.js'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.16.1

### OS name and version

Linux: Mint 18.1, Ubuntu 17.04

**Comment by ArtemGovorov** [comment]
Hello,

your file patterns are too greedy and include `node_modules`. 

If you have a root folder for your source file, like `src`, please use it - it'll be the most efficient way:

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      'src/**/*.js',
      '!src/**/*.spec.js'
    ],
    tests: [
      'src/**/*.spec.js'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest'
  }
}
```

Another (less recommended way) is to just exclude your `node_modules` folder:

```javascript
module.exports = (wallaby) => {
  return {
    files: [
      '!node_modules/**',
      '**/*.js',
      '!**/*.spec.js'
    ],
    tests: [
      '!node_modules/**',
      '**/*.spec.js'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'jest'
  }
}
```

This approach less recommended because wallaby copies everything that is included to its file cache. So even though you have excluded your `node_modules`, you may need to exclude more files in your root/subfolders that are not required to run your tests, like some configs, maybe your dist/bin/build folders, etc. It's just easier to only include what's required, like in the first approach that I have suggested.

**Comment by lamartire** [comment]
Thank you! :tada:
