### ISSUE TITLE
Frequent random crashes on VS Code/Windows

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/public#1321]
### Issue description or question

On a smallish project with 300-something tests, and a few thousand lines of code, I get frequent (at least once a day) crashes on a Core i7 machine with 12GB RAM when files change on disk. The usual cases:

- Pull from a git repo
- Perform a rebase
- Extract translations using gettext (these files are not used anywhere in the tests)

It doesn't happen 100% of the time, and the time between starting Wallaby and occurrence of a crash is random. I am pretty certain that Wallaby plays a role in this because VS Code never crashes when Wallaby is not turned on, and the crash usually happens immediately (usually under 1s) after Wallaby status tells me it's working.

### Wallaby.js configuration file

```javascript
const babelConf = {
  sourceMap: true,
  plugins: ["transform-es2015-modules-commonjs", "jest-hoist"],
  presets: ["babel-preset-jest"],
};

module.exports = (wallaby) => ({
  files: [
    "tsconfig.json",
    "package.json",
    "src/**/*.*",
    "!src/**/*.test.ts",
    "!src/**/*.test.tsx",
  ],
  tests: [
    "src/**/*.test.ts",
    "src/**/*.test.tsx",
  ],
  env: {
    type: "node",
  },
  testFramework: "jest",
  debug: true,
  compilers: {
    "**/*.ts?(x)": wallaby.compilers.typeScript({
      module: "es2015",
    }),
  },
  preprocessors: {
    "**/*.js?(x)": file => require("babel-core").transform(file.content, babelConf),
  },
  setup(wallaby) {
    var jestConfig = require("./package.json").jest;
    jestConfig.modulePaths[0] = jestConfig.modulePaths[0].replace("<rootDir>", wallaby.projectCacheDir);
    wallaby.testFramework.configure(jestConfig);
  },
});
```

### Code editor or IDE name and version

Visual Studio Code v1.16.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
What exactly happens during the crash? Does wallaby just silently stop? Does it show any error messages on the wallaby console?

**Comment by ArtemGovorov** [comment]
> VS Code never crashes 

Oh, so the whole VS Code crashes and exists? Like the editor simply exits/closes?

**Comment by foxbunny** [comment]
VS Code tells me it's crashed and asks to reopen the editor, yes.

**Comment by ArtemGovorov** [comment]
In this case I don't think wallaby.js is causing it. 

First of all, VS Code extensions work in a separate process, and even if the process is crashed by some extension, VS Code doesn't prompt to reopen the editor.

Second, most of the wallaby.js related work that reacts on file changes happens in another third process, and even if it ever crashes - it just shows the error in the wallaby console output channel.

>  the crash usually happens immediately (usually under 1s) after Wallaby status tells me it's working

This sounds like a coincidence. You said the crash is happening after files change on disk. Wallaby is trying to re-run tests on changes, so you see the indicator that it is working. But anything else that is processing files change on disk can crash VS Code. From the symptoms you have described, it is not an extension - because crashed extension process doesn't cause VS Code to ask to reopen the editor.

I would suggest trying to reproduce the issue with opened VS Code Dev Tools (`Toggle Developer Tools` command), or try to open VS Code Dev Tools after the crash if it's still possible. There should be some indication/error messages in the Dev Tools console that you may then submit as an issue to VS Code repo.

**Comment by foxbunny** [comment]
Thanks for the info. I'll keep the dev tools open and see if I can catch something.

**Comment by ArtemGovorov** [comment]
Thanks, even if it's not wallaby related, please post an update here if you get something in the Dev Tools console, would be interesting to see.

**Comment by foxbunny** [comment]
My next suspect is the built-in console in which I have webpack dev server running. It would normally write out the webpack messages when files update. At any rate, I'll post any findings here.

**Comment by ArtemGovorov** [comment]
> the built-in console

The build-in stuff sounds like a likely candidate to me if VS Code crashes with the prompt to reopen the editor. 

Any chance you remember how does the crash notification look like? What buttons does the notification has? Does it say re-open/restart editor (and restarts the whole editor), or it says something like restart extension host?

**Comment by foxbunny** [comment]
I think it asks for the editor to be reopened. I'll take a screenshot next time it happens.

**Comment by foxbunny** [comment]
![image](https://user-images.githubusercontent.com/65413/30745726-95682606-9fa7-11e7-9485-4431a924f912.png)

This is the dialog that pops up. This time, no files were changed, I just opened a project file and it crashed immediately. Tomorrow I'll back up and remove all extensions except wallaby and see if that makes any difference, though this crash happens roughly every couple of hours of work, so not sure if I'll come to a definitive conclusion.
