### ISSUE TITLE
Times out when testing Bluebird promise

### ISSUE THREAD

**Issue by jagreehal** [wallabyjs/public#133]
Running via mocha cli runs the test OK but wallaby times out (works fine with Q). 

<pre><code>
describe('wallaby mocha bluebird promise test', ()=>{
  const assert = require('assert');
  const Promise = require('bluebird');

  const square = function(num){
    return Promise.resolve(num * num);
  };

  it('Should be ok', (done) =>{
    square(2).then((result) =>{
      assert.equal(result, 4);
      done();
    })
  })
});
</code></pre>

**Comment by ArtemGovorov** [comment]
I'm getting consistent behaviour in both wallaby and mocha CLI for this test - it passes.

If I change it to fail, for example `assert.equal(result, 5);`, both mocha CLI and wallaby are timing out (mocha CLI just show the error earlier). The reason is that `assert.equal(result, 5);` throws an exception, so the next `done();` line is never executed.

Anyway, the best way to make it work like you're expecting is to use [mocha built-in support for testing promises](http://stackoverflow.com/questions/26571328/how-to-i-properly-test-promises-with-mocha-and-chai):
``` JavaScript
describe('wallaby mocha bluebird promise test', ()=>{
  const assert = require('assert');
  const Promise = require('bluebird');

  const square = function(num){
    return Promise.resolve(num * num);
  };

  it('Should be ok', () =>{
    return square(2).then((result) =>{
      assert.equal(result, 4);
    })
  })
});
```
If you return the promise from your test function, you don't need to have `done` param and use it.

Please let me know if it helps.

**Comment by jagreehal** [comment]
Tested on another machine and it works fine. Thanks for the testing tip!
