### ISSUE TITLE
lates wallaby release does strange things to kiest snapshots

### ISSUE THREAD

**Issue by rogergl** [wallabyjs/public#1333]
### Issue description or question

Wallaby create a lot of snapshots on start and one snap shot is changed like this:

from  -    ```<Entry>```
to +   ``` <Component>```

But Entry is the right one. Running jest standalone works as expected.

It all worked on Sunday...

### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
    return {
        files: [
            './app/**/*.js',
            '!/app/**/__tests__/*.js'
        ],

        env: {
            type: 'node',
            runner: 'node'
        },

        tests: [
            './app/**/__tests__/*.js'
        ],
        "transform": {
            "^.+\\.js$": "babel-jest"
        },
        "snapshotSerializers": [
            "enzyme-to-json/serializer"
        ],
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({babelrc: true, presets: [ "es2015",
                "react",
                "stage-0"]})
        },
        setup(wallaby) {
            wallaby.testFramework.configure(require('./package.json').jest)
        },
        debug: true

    };
};
```

### Code editor or IDE name and version

IntelliJ IDEA latest release

### OS name and version

OSX and Jest 19.0.2

**Comment by ArtemGovorov** [comment]
There were no recent changes in wallaby that could have affected snapshots, so recent wallaby releases couldn't have affected it. Could you please create a sample repo demonstrating the issue? I'm happy to have a look.

**Comment by ArtemGovorov** [comment]
> It all worked on Sunday...

I can't see any changes since Sunday that could have affected snapshot testing. Our sample repo with snapshots https://github.com/wallabyjs/wallaby-jest-snapshots is also working for me (with Jest 19.0.2).

Could you please check if the repo is working for you, and if yes, then could you please create a sample repo demonstrating the issue? 

I have also noticed a couple of issues in your config:

1. These are not wallaby settings, they look like Jest settings, and have no effect in wallaby config:
```
        "transform": {
            "^.+\\.js$": "babel-jest"
        },
        "snapshotSerializers": [
            "enzyme-to-json/serializer"
        ],
```

2. Your `files` patterns are [missing snapshot pattern](https://github.com/wallabyjs/public/issues/1264#issuecomment-322152562). Try adding it:
```diff
files: [
            './app/**/*.js',
+           './app/**/*.snap',
             ...
```

**Comment by ArtemGovorov** [comment]
Could you please also share how the `<Entry>` component is declared and exported?

**Comment by rogergl** [comment]
Hi adding './app/**/*.snap', seems to solve at least a part of the problem. At least no new snapshots are generated. Have to try if the failing test still produces the wrong snapshot.

**Comment by ArtemGovorov** [comment]
Great, thanks for the update.

> Have to try if the failing test still produces the wrong snapshot.

If it is, please create a sample repo demonstrating the issue, but before spending time on the repo, please share how the `<Entry>` component is declared and exported (I may be able to see what the issue is just from that). I.e. does it look like:

```javascript
import React from 'react';

const Entry = () => {
    return ...
};

export default Entry;
```

or like 

```javascript
import React from 'react';

export default class Entry {
  ...
};
```
or somehow else?

**Comment by roger-gl** [comment]
One declaration looks like this:
```
export const Entry = ({id, title, line1, line2, dateLine, withTis}) => {
    const renderLine = (text) => {
        if (!_.isEmpty(text)) {
            return (
                <span>
                    <Line text={text}/>
                </span>
            )
        }
    };
```

**Comment by roger-gl** [comment]
BTW:  Wallaby changes it from ```<Component> to <Entry/>```   . Wich seems ok...

**Comment by ArtemGovorov** [comment]
> One declaration looks like this:
```
export const Entry = ({id, title, line1, line2, dateLine, withTis}) => {
    const renderLine = (text) => {
        if (!_.isEmpty(text)) {
            return (
                <span>
                    <Line text={text}/>
                </span>
            )
        }
    };
```
> Wallaby changes it from `<Component>` to `<Entry/>` . Wich seems ok...

So it is working for you as expected? From what I see it should be `<Entry/>`, not `<Component>`.

**Comment by ArtemGovorov** [comment]
I have put together this repo https://github.com/ArtemGovorov/wallaby-1333, with a setup similar to yours. Both wallaby and Jest CLI are consistently running the test and writing `<Entry/>` to the snapshot. Note that I have placed babel config to the `.babelrc` file (and not specifying any babel settings in the wallaby config) to avoid any discrepancies between what Babel settings Jest is using and what Babel settings wallaby is using (because the discrepancies may cause the issue).

Please try the repo and if it is working for you, then please fork the repo (or create a new one) to demonstrate the issue, I'm happy to have a look.

**Comment by roger-gl** [comment]
i found a workaround: If I export a function instead of a fat arrow function it works. Seems like an enzyme related problem.
