### ISSUE TITLE
Uncaught Error: Cannot find module '371' and Uncaught Error: Module build failed: [object Object]

### ISSUE THREAD

**Issue by spinachandkale** [wallabyjs/public#1338]
### Issue description or question
I am getting below error

<img width="708" alt="screen shot 2017-10-07 at 11 33 18 pm" src="https://user-images.githubusercontent.com/25850583/31313960-8daec222-abb8-11e7-9745-efc38929eff5.png">

There is no module in my project with the name '371'
For the second error 'module build failed [object, object]' I dont understand the issue here. 
Please help.

### Wallaby.js configuration file

Same as the one in angular cli example with two changes, env changed to chrome and tsconfig changed to right path.

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./src/tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      loaders: [
        {test: /\.css$/, loader: ['raw-loader', 'css-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.less', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.styl', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.json', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

### Code editor or IDE name and version

WebStorm 2017.2.4

### OS name and version

macOS Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
Are there any other error being reported in Wallaby Console or to the Failing Tests console?

Both errors are coming from webpack, not from wallaby directly. It looks like webpack is having issues compiling one the modules used in your app, but it's hard to tell which one. Looks like one of the module loaders throws an error that is not an Error object, so webpack is just appending it to the error message as a string: https://github.com/webpack/webpack/blob/master/lib/ModuleBuildError.js#L15

Here's what I'd try first:
- open the `node_modules/webpack/lib/ModuleBuildError.js` file,
- and change:
```javascript
...
			} else {
				this.message += err;
			}
```
to
```javascript
...
			} else {
				this.message += JSON.stringify(err);
			}
```
- then restart wallaby and see what object is thrown by the webpack loader.

If it doesn't help, please restart wallaby, open the URL from the error in Chrome (the one with `wallaby-bundle.js` file), wait till the file loads (may take some time, as it may be quite large), cop the file content and attach the file to this issue.

The fastest way for us to help would be if you can create a sample repo demonstrating the issue. None of your real app files is required, one dummy test is enough as long as the issue is reproducible.

**Comment by spinachandkale** [comment]
>> Are there any other error being reported in Wallaby Console or to the Failing Tests console?

Yes, there are other errors, shown in below images.
Changed node_modules/webpack/lib/ModuleBuildError.js.  It is throwing below errors now.

In Failing-tests:

<img width="1360" alt="screen shot 2017-10-08 at 4 51 27 pm" src="https://user-images.githubusercontent.com/25850583/31321355-88a53170-ac4a-11e7-906a-0e1b24c4172b.png">

<img width="1372" alt="screen shot 2017-10-08 at 5 02 21 pm" src="https://user-images.githubusercontent.com/25850583/31321363-b34a0b12-ac4a-11e7-8bf0-6905467796bb.png">

In Wallaby-console:

<img width="1349" alt="screen shot 2017-10-08 at 5 07 03 pm" src="https://user-images.githubusercontent.com/25850583/31321387-27c72a56-ac4b-11e7-88c9-a1a8ce8d807c.png">

>> open the URL from the error in Chrome (the one with wallaby-bundle.js file)

Attached the file, it is not a big file as expected (waited for sometime to load it completely), changed paths to ** and filenames to numbers.

[webpack_details.txt](https://github.com/wallabyjs/public/files/1367245/webpack_details.txt)

>> create a sample repo

This is relatively big project, I don't have any idea on how to isolate the problem and giving only the part with issue, without keeping entire code in repo. Please give me some pointers, I will try.

**Comment by ArtemGovorov** [comment]
> Attached the file, it is not a big file as expected (waited for sometime to load it completely), changed paths to ** and filenames to numbers.

Thanks for providing the file, I was actually asking for the one with `wallaby-bundle.js` file, not `wallaby-webpack.js` file. 

However, from the provided file and the issues displayed after modifying webpack `node_modules/webpack/lib/ModuleBuildError.js`, it is now clear to me what the issue is. Your tests list pattern includes `e2e-spec` files and wallaby doesn't support protractor tests, so you need to exclude them:

```diff
    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
+     {pattern: 'src/**/*e2e-spec.ts', ignore: true},
    ],
```

**Comment by spinachandkale** [comment]
Thanks. Issue is resolved.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
