### ISSUE TITLE
ESNext modules using dynamic import syntax fail to parse

### ISSUE THREAD

**Issue by tomrj** [wallabyjs/public#1346]
### Issue description or question

Any code ESNext dynamic imports, e.g. this

```javascript
 const {DocHeaderDesktop} = await import(/* webpackChunkName: "DocHeader" */ './DocHeaderDesktop');
```

fail to parse.

The project compiles and runs ok. Typescript tsconfig has this

```javascript
    "module": "esnext",
    "moduleResolution": "node",
```

```javascript
Postprocessor run failure: Failed to parse src/javascript/app/components/DocHeader/DocHeader.js, SyntaxError: Unexpected token (55:45)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
```
### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {

  const ts = require('typescript');

  const wallabyWebpack = require('wallaby-webpack');
  // const CircularDependencyPlugin = require('circular-dependency-plugin');
  const webpack = require('webpack');
  const React = require('react');
  const path = require('path');

  var constants = require('./w/constants.json');

  const webpackPostprocessor = wallabyWebpack({
    // webpack options
    resolve: {
      modules: [
        path.join(wallaby.projectCacheDir, 'src/javascript')
      ],
      extensions: ['.js', '.jsx', '.ts', '.tsx']
    },
    externals: {
      cheerio: 'window',
      'react/lib/ExecutionEnvironment': true,
      'react/lib/ReactContext': true,
      'react/addons': true
     // "react": "React"
    },
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/\.(gif|png|scss|css|svg)$/, 'node-noop'),
      // new CircularDependencyPlugin({exclude: /node_modules/, failOnError: true}),
      new webpack.DefinePlugin({
        __IS_TEST__: 'true',
        CONSTANTS: JSON.stringify(constants)
      })
    ]
  });

  return {
    files: [
      'src/javascript/test/components/setup.ts',
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'node_modules/phantomjs-polyfill/bind-polyfill.js', instrument: false},
      {pattern: 'node_modules/react/dist/react-with-addons.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon.js', instrument: false},
      {pattern: 'node_modules/jquery/dist/jquery.js', instrument: false},

      {pattern: 'node_modules/whatwg-fetch/fetch.js', instrument: false},
      {pattern: 'src/javascript/app/**/*.ts*', load: false},
      {pattern: 'src/javascript/dev/**/*.ts*', load: false},
      {pattern: 'src/javascript/test/utils.ts', instrument: false}
    ],

    tests: [
      {pattern: 'src/javascript/test/**/*Spec.ts*', load: false}
    ],

    compilers: {
      '**/*.ts*': wallaby.compilers.typeScript({
        typescript: ts
      })
    },

    postprocessor: webpackPostprocessor,
    testFramework: 'mocha',
    bootstrap: function() {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2017.2, 2017.3

### OS name and version

OSX Sierra 10.12.6

**Comment by ArtemGovorov** [comment]
It is interesting, wallaby (parser) fully supports dynamic imports. 
Is this code

```javascript
 const {DocHeaderDesktop} = await import(/* webpackChunkName: "DocHeader" */ './DocHeaderDesktop');
```

located in a program scope, or within some function?

If it's located in a program scope, then it is not valid TypeScript or ESNext, because the `await` keyword can only be used inside an async function. In this case the error makes sense, the error is displayed by [TypeScript compiler](http://www.typescriptlang.org/play/index.html#src=const%20%7BDocHeaderDesktop%7D%20%3D%20await%20import('.%2FDocHeaderDesktop')%3B), [ESNext compiler](https://babeljs.io/repl/#?babili=false&browsers=&build=&builtIns=false&code_lz=AQYw9gdgzgLsDeARMIASBTAhgE3QJ0XSgGsYwAHAX2AF5hMB3TASzmYFtyw8YAKAegBUwBugBG5TCGIBhABYBXCMQBymdugBcwAETI0WXHh3BB_YAHIAdP30Yc-QiTLkLASgDcQA&debug=false&circleciRepo=&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&targets=Node-8&version=6.26.0), Chrome 63 (that supports dynamic `import`):
<img width="485" alt="screen shot 2017-10-13 at 10 42 57 am copy" src="https://user-images.githubusercontent.com/979966/31525437-aa2a26fe-b003-11e7-8257-1dafe3d602e8.png">


If the code is located in an async function, then I can't reproduce the issue. I have created this sample repo with your config https://github.com/ArtemGovorov/wallaby-1346, and everything is working for me:

![screen shot 2017-10-13 at 10 35 14 am](https://user-images.githubusercontent.com/979966/31525312-bcbdd820-b002-11e7-88af-2a0434dc11a2.png)

Try cloning the repo to see if it's working for you, and if it is, please fork it to add a sample to reproduce the issue.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please try the steps listed above, and create a sample repo demonstrating the issue - we are happy to have a look into it.
