### ISSUE TITLE
Unable to run unit tests with kendo controls

### ISSUE THREAD

**Issue by JeanFrancoeur** [wallabyjs/public#1350]
### Issue description or question

Hi!  We try to find the right way to configure wallaby with kendo controls.
Our sample works with karma and we cannot figure out how to load the missing packages.
Can you help us to complete this configuration?

Here's the actual result:

​​*Uncaught Error: Unhandled promise rejection: Unable to find module with ID: aurelia-pal-browser​​
​​at http://localhost:25621/__wallaby__/tracer.js:14​​
  
  ​​​​the app says hello too​​​​ ​​​[5003 ms]​​​​
    ​​​​
    ​​Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.​​*

Here's the [repo](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo)

Thank you,
Jean Francoeur

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js'],
  resolve: {
    alias: {
      'kendo-ui/js': '@progress/kendo-ui/js',
      'kendo-ui': '@progress/kendo-ui/js/kendo.core.js'
    }
  }
});

module.exports = function () {
  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'test/unit/setup.ts', load: false}
    ],

    tests: [{
      pattern: 'test/unit/**/*.spec.ts', load: false
    }],

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Wallaby: 1.0.64
Node: 6.11.2
Npm: 5.4.2

Visual Studio Code:
Version 1.17.1
Architecture x64

### OS name and version

Windows 10 x64

**Comment by ArtemGovorov** [comment]
Hi,

Thanks for sharing the repo.

I have sent you the [pull request to make wallaby configuration work](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/1).

Here's the short description of my changes:

- Added `aurelia-webpack-plugin` dependency as aurelia webpack integration needs it.
- As discussed in this issue https://github.com/wallabyjs/public/issues/1252, I have added `PLATFORM.moduleName(...)` instead of the plain string for module names that are implicitly imported (by using `.plugin`, `.resources`, etc). Aurelia webpack plugin needs it, and adding those doesn't affect karma. Here's the discussion in Aurelia repo about it: https://github.com/aurelia/webpack-plugin/issues/99#issuecomment-290034760.
- As discussed in this aurelia issue https://github.com/aurelia/webpack-plugin/issues/95#issuecomment-286850917, I had to add `new AureliaPlugin({aureliaApp: undefined })`, otherwise I was getting the `Webpack - TypeError: Cannot read property 'used' of null` error.

Here's the working config for your repo:

```javascript
var wallabyWebpack = require('wallaby-webpack');
var AureliaPlugin = require('aurelia-webpack-plugin').AureliaPlugin;
var DefinePlugin = require('webpack').DefinePlugin;

var wallabyPostprocessor = wallabyWebpack({
  entryPatterns: ['test/unit/setup.js', 'test/unit/**/*.spec.js'],
  resolve: {
    alias: {
      'kendo-ui/js': '@progress/kendo-ui/js',
      'kendo-ui': '@progress/kendo-ui/js/kendo.core.js'
    }
  },
  plugins: [
    new DefinePlugin({AURELIA_WEBPACK_2_0: undefined}),
    new AureliaPlugin({
      aureliaApp: undefined
    })
  ]
});

module.exports = function () {
  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'test/unit/setup.ts', load: false}
    ],

    tests: [{
      pattern: 'test/unit/**/*.spec.ts', load: false
    }],

    env: {
      kind: 'chrome'
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

```

Hope it helps.

**Comment by JeanFrancoeur** [comment]
Hi Artem,  Thank you so much for your help, it's very appreciated.
We will integrate these changes inside our project.
Have a nice day,
Jean Francoeur

**Comment by Lloyc** [comment]
Hi @ArtemGovorov. We updated our [sample](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo) with the solution suggested in the the previous issue.
We still have some errors. Please Can you help us to complete this configuration? Do I need to open another issue?

Thank you

**Comment by ArtemGovorov** [comment]
@Lloyc Sure, we can use this this issue.

I had a look into the changes, and looks like a couple of your changes had broken the sample:
- this https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/blob/b36c69950005208abf1ea5ec467ae106a7b8d0e4/test/unit/app.spec.ts#L28, `aurelia-webpack-plugin` is a plugin for webpack to do compile time things (at the stage when webpack is compiling your code, not in runtime), not sure why you'd need it as a plugin in your code.
- the module alias here was incorrect https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/blob/b36c69950005208abf1ea5ec467ae106a7b8d0e4/wallaby.conf.js#L9 (removed the leading slash).

I have sent the [pull request to fix these](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/3).

After fixing these issues, tests start running but the `shows notifications` test is failing, it looks like [jasmine's `toHaveBeenCalled`](https://jasmine.github.io/2.0/introduction.html#section-Spies) is not correctly used:

```javascript
expect(viewModel.showNotification("info")).toHaveBeenCalled();
``` 

I think it's supposed to be:

```javascript
viewModel.showNotification("info");
expect(viewModel.showNotification).toHaveBeenCalledWith('info');
```

**Comment by Lloyc** [comment]
Thank you @ArtemGovorov. Sorry for the broken sample. I updated the repo with your changes. I added some changes find in [this issue](https://github.com/wallabyjs/public/issues/1252). We still can't load the ressources. We need it to be able to test kendo UI controls. I tried some hints in this issue but I not able to make it work.
![image](https://user-images.githubusercontent.com/11031281/32128165-a78e03a6-bb49-11e7-8495-1d5f12970e50.png)
Some relevant print screens:
![image](https://user-images.githubusercontent.com/11031281/32128131-6b08aa26-bb49-11e7-943d-3485f706ab28.png)
![image](https://user-images.githubusercontent.com/11031281/32128193-e9e7cc28-bb49-11e7-8b47-ca720bde5dab.png)

**Comment by ArtemGovorov** [comment]
@Lloyc Thanks for updating the sample. I have sent the [pull request with the changes to make it work](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/4).

- Webpack needs `modules` location to be configured to load modules by absolute paths from tests (like `app` as opposed to `../../app`), you had them commented out in your config but they [need to be in wallaby webpack configuration](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/4/files#diff-048752d1796dc58b3bf94046816a7cfdR15). I also uncommented [module loaders for CSS/HTML](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/4/files#diff-048752d1796dc58b3bf94046816a7cfdR23) as in the [referenced issue](https://github.com/wallabyjs/public/issues/1252).
- Also, just like for [app HTML files](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/blob/b1de44494da17dcfa677cde512b578a2d3b2e0bb/test/unit/app.spec.ts#L22), looks like webpack needs a reference to [component HTML files as well](https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/4/files#diff-600980df8dee9e77b0a916d7a335e12dR30). I'm not an expert in Aurelia Webpack integration, but looks like Aurelia Webpack plugin when building the app resolves all `PLATFORM.moduleName(...)` as if they were plain ES imports. So if an HTML file is not imported,  Aurelia can't find it in runtime (because it is not bundled).

**Comment by ArtemGovorov** [comment]
Actually, after a bit of reading:
- https://github.com/jods4/aurelia-webpack-build/wiki/AureliaPlugin-options
- https://github.com/jods4/aurelia-webpack-build/wiki/Managing-dependencies

it looks like the `ModuleDependenciesPlugin` plugin from Aurelia webpack plugin can be used to wire up the dependencies in the config file, rather then adding them to your test files. Have sent you the new pull request https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/5.

Perhaps there's even a more elegant way to do it.

**Comment by Lloyc** [comment]
Thank you so much @ArtemGovorov. We will integrate these changes inside our project.

**Comment by ArtemGovorov** [comment]
After some more investigation, I have noticed that you're not using the latest version of the `wallaby-webpack` package. With the latest version, `ModuleDependenciesPlugin` is not required to make it work. Sent the pull request for the version update: https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/6

**Comment by ArtemGovorov** [comment]
Another good news - I found how to avoid doing `PLATFORM.moduleName` for project `,html` files as well. Updated the pull request with the change: https://github.com/JeanFrancoeur/wallaby-aurelia-kendo/pull/6

**Comment by Lloyc** [comment]
Thanks @ArtemGovorov. We'll need a longer trial to test it properly. Our trial version ended. 
![image](https://user-images.githubusercontent.com/11031281/32143543-8543fa10-bc81-11e7-9179-b8a73ce6cfaf.png)

**Comment by Lloyc** [comment]
Thank you @ArtemGovorov for the extended license. Everything is working!
