### ISSUE TITLE
Does wallabyjs run jest tests in same file concurrently?

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1355]
### Issue description or question

Jest test runner will run tests in different files concurrently but I believe it never runs tests in the same file at the same time.  Is this behavior possible with Wallaby?  I have files with tests which manipulate state shared within the test file (resetting it to an initial condition before/after each run) -- the tests are isolated but can't run at the same time.  I think I get this behavior with jest but seem to not with wallaby...

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      "!**/node_modules/**",
      "!lib/**",
      "!src/**/*.test.ts",
      "package.json",
      "tsconfig.json",
      ".secrets/**/*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*.ts",
      "serverless-services/**/*.yml"
    ],

    tests: ["src/**/*.test.ts", "!src/TestsDeployment/**/*"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: true,
    testFramework: "jest",

    workers: {
      recycle: false
    },

    delays: {
      run: 500
    },

    slowTestThreshold: 7000
  };
};
```

### Code editor or IDE name and version

Visual Studio v1.17.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> Does wallabyjs run jest tests in same file concurrently?

No, it doesn't. However, Wallaby may run just one test in the test file. Jest is not capable of operating on this level and if a test file changes, then it re-runs all tests in the test file. Wallaby is smarter, and for example if you are editing a single test, then wallaby will only re-run it on code changes. If execution of the test depends on some state set by other tests in the file, then things may break. 

In this is the case, it means that your tests are not isolated (as best practise prescribes) and depend on each other in some way. It's generally recommended to fix the tests so that each individual test can be run in isolation from others and wouldn't break. 

Having tests independent from each other already allows wallaby (and possibly in future other test runners as well) to run faster by re-running a minimal number of tests on your changes. Having dependent tests eliminates the possibility.

Anyway, if you still want Wallaby to behave like Jest and run all tests in a test file when the test file is changed/affected by code changes, then you may use the `runAllTestsInAffectedTestFile` setting:

```javascript
module.exports = function () {

    return {
      ...
      runAllTestsInAffectedTestFile: true
    };
};
```
