### ISSUE TITLE
jest snapshots updating without any action on my part

### ISSUE THREAD

**Issue by breathe** [wallabyjs/public#1356]
### Issue description or question

I'm seeing an issue where wallaby sometimes updates my jest snapshots without any interaction on my part.  I'm not sure the cause but it appears that sometimes the 'test name' is changing and with it the name of the generated snapshot...

### Wallaby.js configuration file

```javascript
module.exports = function() {
  return {
    files: [
      "!**/node_modules/**",
      "!lib/**",
      "!src/**/*.test.ts",
      "package.json",
      "tsconfig.json",
      ".secrets/**/*",
      "resources/**/*",
      "src/**/*.yml",
      "src/**/*.ts",
      "serverless-services/**/*.yml"
    ],

    tests: ["src/**/*.test.ts", "!src/TestsDeployment/**/*"],

    env: {
      type: "node",
      runner: "node"
    },

    debug: true,
    testFramework: "jest",

    workers: {
      initial: 1,
      regular: 1,
      recycle: false
    },

    delays: {
      run: 500
    },

    slowTestThreshold: 7000
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.1

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
You need to include your snapshots pattern to the `files` list:

```diff
module.exports = function() {
  return {
    files: [
      ...
+     'src/**/*.snap'
    ],

    ...
  };
};
```

**Comment by breathe** [comment]
@ArtemGovorov thanks for that -- I include .snap files and it seemed to resolve my problem for awhile but just ran into a variation of the same issue again.

For some reason tests are sometimes being renamed creating new snapshots which succeed when really the test should fail.  Here's an example snapshot file -- most of these tests should fail but for whatever reason the tests are renamed and new snapshot created ...

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`dispatchWatsonRequest should provide expected member response when invoked by member 1`] = `
<removed>
`;

exports[`dispatchWatsonRequest should provide expected non-member response when invoked by non-member 1`] = `
<removed>
`;

exports[`dispatchWatsonRequest should provide expected non-member response when invoked by non-member 2`] = `
<removed>
`;

exports[`dispatchWatsonRequest should provide expected not-logged-in response when invoked by not-logged-in user 1`] = `
<removed>
`;

exports[`handler should provide expected responses when invoked 1`] = `
<removed>
`;

```

`dispatchWatsonRequest should provide expected non-member response when invoked by non-member 2` snapshot was created for some reason rather than a failing run against the snapshot with name `dispatchWatsonRequest should provide expected non-member response when invoked by non-member 1`

**Comment by ArtemGovorov** [comment]
What you've described (creating snapshots `abc 1`, `abc 2`, etc.) is a standard Jest behaviour. If you (accidentally or deliberately) add more than one `toMatchSnapshot` call within a single test, then Jest starts creating multiple snapshot entries for the same test. Jest also doesn't stop on a failing snapshot check, so if you (accidentally or deliberately) add a `toMatchSnapshot` call after a failing snapshot check, then Jest will create a new snapshot entry for the current state of your snapshot.

Here is the demo of what I mean (note I'm using plain Jest CLI without Wallaby, ypu may get the same result with Wallaby):

![jest](https://user-images.githubusercontent.com/979966/32315202-f0a243a2-bff6-11e7-8943-1840533df11d.gif)

This example produces this snapshot file:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`component should work 1`] = `
Object {
  "a": 1,
}
`;

exports[`component should work 2`] = `
Object {
  "a": 12,
}
`;
```

that is similar to what you're getting. Hope it explains what's going on.

P.S. Also (if at any time you're happy with the state of tests/snapshots), you may remove obsolete ones (if they are obsolete) [by using the `Run line/file/project tests` Wallaby commands](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0). They'll do exactly the same as `jest -u` would do. Not though that, as with Jest, your other snapshot need to be in a desired state (passing) otherwise Jest (with or without wallaby) will also update failing snapshots.

**Comment by breathe** [comment]
@ArtemGovorov Its good to know that Run line/file/project tests automatically update snapshots -- this was entirely unexpected by me.  I've been using those commands to manually re-run tests when modifying resources that wallaby doesn't know about but which have an influence on the test results...  Obviously I don't like having tests with 'invisible to wallaby' dependencies but there are cases where that's the only to do it ...

I really think those commands need a new name -- `Update snapshots for tests matching line/file/project` -- and a new command added to allow running subsets of tests without updating the snapshots ...

**Comment by ArtemGovorov** [comment]
> I really think those commands need a new name -- Update snapshots for tests matching line/file/project -- and a new command added to allow triggering execution of subsets of tests without updating the snapshots

Agreed. This will also make the commands more discoverable.
