### ISSUE TITLE
decorator not handled after using result of issue 1359

### ISSUE THREAD

**Issue by pietgk** [wallabyjs/public#1361]
### Issue description or question

Decorators does not work after using the configuration given in issue https://github.com/wallabyjs/public/issues/1359

See Comment at the end of that issue for all the details.
Reproducable by updating https://github.com/ArtemGovorov/wallaby-1359
with new wallaby.conf.js and 
adding SampleView.js:

```javascript
/* eslint-disable react/prop-types */
import React, { Component } from 'react';
import { Text } from 'react-native';
import { observer } from 'mobx-react/native';

@observer
export default class Log extends Component {
  render() {
    return (
      <Text>SampleView</Text>
    );
  }
}
```

### Wallaby.conf.js configuration file

```javascript
// see https://github.com/ArtemGovorov/wallaby-1359 for simple working example 
// after issue https://github.com/wallabyjs/public/issues/1359#issuecomment-338633214
// 
module.exports = function (wallaby) {
  // eslint-disable-next-line
  console.log(wallaby);
  return {
    files: [
      { pattern: 'src/containers/SampleView.js', load: false },
      // { pattern: 'src/**/*.+(t|j)s*', load: false },
      { pattern: '!src/__tests__/*.test.ts', load: false },
    ],

    tests: [
      'src/__tests__/*.test.ts',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      'src/**/*.+(t|j)s*': wallaby.compilers.typeScript(),
    },

    preprocessors: {
      // eslint-disable-next-line global-require, import/no-extraneous-dependencies
      '**/*.js': file => require('babel-core').transform(
        file.content,
        { sourceMap: true, compact: false, presets: ['react-native'] }),
    },

    testFramework: 'jest',

    debug: true,
    // for node.js tests you need to set env property as well
    // https://wallabyjs.com/docs/integration/node.html
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

OSX Sierra

**Comment by ArtemGovorov** [comment]
There was a small issue in wallaby.js related to the `allowJs` option handling in your `tsconfig.json` file. The bug is fixed and the fix is published [in the latest core version 1.0.507](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

I have [updated the sample repo](https://github.com/ArtemGovorov/wallaby-1359/commit/25eeaf7637d1f6858027b74162eb02185a9a2171) with up-to-date config version, added the file with the decorator and `.babelrc` file that was missing (but probably is present in your real project).

I have also [updated the repo preprocessor](https://github.com/ArtemGovorov/wallaby-1359/blob/25eeaf7637d1f6858027b74162eb02185a9a2171/wallaby.conf.js#L27-L32) in the wallaby config. It needs to take care of cases when an original `.js` files is passed before it is compiled by TypeScript, and to rename it back to `.js` after te compilation because to avoid name conflicts wallaby TS compiler changes the extension of a compiled `.js` file to `.jsts`, so we need to change it back. It got a bit tricky because of the Babel compilation on top of TS compilation (plus `.js` files that you need to compile with TypeScript compiler).
