### ISSUE TITLE
Tests run successfully first time, then subsequently fail with Cannot find module '{Number}'​​

### ISSUE THREAD

**Issue by elbuilio** [wallabyjs/public#1372]
### Issue description or question

I am experiencing an error when running my tests with wallaby. The tests run successfully first time, then fail with the following error for any subsequent runs i.e. when i start typing some new test code.

```
​​[Error] Runtime error: Uncaught Error: Cannot find module '2601'​​
​​[Error] at http://localhost:60107/wallaby-webpack.js?1509536156303:1​​
```
The module number changes each time it fails. If I restart wallaby, the tests run successfully first time again, then fail for subsequent runs.

Any help on this would be greatly appreciated.

Many thanks :)

### Wallaby.js configuration file

```javascript
const wallabyWebpack = require("wallaby-webpack");
const webpackConfig = require("./webpack.config.base");

const wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
    return {
        name: "integration",
        files: [
            { pattern: "node_modules/babel-polyfill/dist/polyfill.js", instrument: false },
            { pattern: "node_modules/jquery/dist/jquery.js", instrument: false },
            { pattern: "node_modules/jquery-ui/dist/jquery-ui.js", instrument: false },
            { pattern: "node_modules/jasmine-ajax/lib/mock-ajax.js", instrument: false },
            { pattern: "packages/test-helpers/src/**/*.js", load: false },
            { pattern: "tests/helpers/**/*.js", load: false },
            { pattern: "tests/data/**/*.json", load: false },
            { pattern: "packages/**/src/**/*.js", load: false },
            { pattern: "packages/**/src/**/*.less", load: false },
        ],
        filesWithNoCoverageCalculated: [
            "mode_modules/**/*.js",
            "tests/**/*.js",
        ],
        tests: [
            { pattern: "tests/specs/**/*.tests.js", load: false },
        ],
        env: {
            kind: "chrome",
        },
        debug: true,
        testFramework: "jasmine",
        compilers: {
            "**/*.js": wallaby.compilers.babel({ babel: require("babel-core") }),
        },
        postprocessor: wallabyPostprocessor,
        bootstrap: () => {
            window.__moduleBundler.loadTests();
        },
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.17.2

### OS name and version

Windows 10

**Comment by elbuilio** [comment]
Thanks for the quick response @ArtemGovorov 

I have already tried that. The error happens for all my test files individually unfortunately.

There is a common import on all the test files which is from a **webpack alias'd package**. 

```@company/package-name```

If I comment this import out, the cannot find module error disappears, however I need the package for the tests to work.

There are many other alias'd packages which work ok without complaining.

**Comment by ArtemGovorov** [comment]
Hmm, interesting. There must be something in this package that confuses wallaby-webpack. 

- Are you using the latest version (0.0.44) of the `wallaby-webpack` module?
- Is the `@company/package-name` open sourced so that I can try to reproduce the issue? If not, try editing the package by commenting out its parts until you can find the bit that is causing the issue. If you can create/share a repro, I'm happy to have a look to see what's going on there.

**Comment by elbuilio** [comment]
Thanks again. I'm on the latest wallaby-webpack. Just looking at commenting out bits of the package.

One interesting thing is that it only appears to be impacting developers with VSCode. Atom and Sublime users do not experience this issue.

**Comment by elbuilio** [comment]
![wallaby](https://user-images.githubusercontent.com/15982892/32280891-269781b2-bf15-11e7-9a0b-e569d0ee0880.gif)

I tried commenting out all the imports in the problematic package, but it still happens in VSCode only. Also the number of the missing module seems to increment by 5 each time?!

It will be quite difficult to get a standalone repro of this, given the number of dependencies. Wondering if it would be possible to have a quick call e.g. using google hangouts? Unless you have any other suggestions based on the gif above?

Thanks :)

**Comment by ArtemGovorov** [comment]
> One interesting thing is that it only appears to be impacting developers with VSCode. Atom and Sublime users do not experience this issue.

It's interesting. VSCode and other editors are using the same core (where webpack compilation is done). 

- Does the issue show up on different machines with VS Code installed or just on your machine?
  - if it's showing up on different machines, please open VS Code Dev Tools, got to Console, paste `process.env`, expand & copy & paste the result here. Please review it before publishing as it may contain some sensitive data.
  - if it's showing up on your machine only, open the `c:\\Users\\tom.buil\\.vscode\\extensions` folder, and going up level by level to the root checking if there're any `node_modules` subfolders along the way (ie. check if `c:\\Users\\tom.buil\\.vscode\\extensions\\node_modules`, or `c:\\Users\\tom.buil\\.vscode\\node_modules`, or `c:\\Users\\tom.buil\\node_modules`, etc. exist).

> I tried commenting out all the imports in the problematic package, but it still happens in VSCode only.

So basically the issue is reproducible if you have a simple test like:

```javascript
import * as p from '@company/package-name'
it('fails on change', () => {
  console.log(p);
})
```
and `@company/package-name` doesn't even have any dependencies? Can you then just try to mock the module, for example by replacing its index.js file content with `module.exports = {}`? This way we'll find out if the issue is inside the module or perhaps it's the way webpack handles it.

> Also the number of the missing module seems to increment by 5 each time?!

Webpack controls module ids automatically, it looks like it has to recompile a few files in the module, but I'm not sure because the test on the screenshot is importing the `../../helpers` file, and not the `@company/package-name` module directly.

> It will be quite difficult to get a standalone repro of this, given the number of dependencies. 

From your GIF it looks like the issue doesn't need much to show up - a simple test is importing the `../../helpers` file, which I'm assuming is importing the `@company/package-name` module. And when the module is not imported, the issue doesn't show up. Is it correct? If yes, please try the simple code below to see if it's reproducible:

```javascript
import * as p from '@company/package-name'
it('fails on change', () => {
  console.log(p);
})
```

Also please do the following:
- leave only this simple test file in your `tests` list,
- remove the `@company/package-name` module dependencies like you did before,
- start wallaby and make sure editing the test is still causing the issue,
- share the full output (since the wallaby start) from the Wallaby Console,
- in the output, you'll see the link like `http://localhost:port/...`, copy the `port` bit, open the URL `http://localhost:port/____wallaby-bundle.js` in browser and share the output. Note that it may contain bundled code for your `@company/package-name` module, so you may send the file to hello@wallabyjs.com if you like instead of sharing it here.
- share your `webpack.config.base.js` file.

**Comment by elbuilio** [comment]
Thanks again Artem, particularly for the detailed response. I will take a look at this later today / tomorrow.

**Comment by Anupheaus** [comment]
Hi @ArtemGovorov, I am a colleague of @elbuilio and I also have the same problem, I've found that when wallaby tries to update itself based on changes it seems to add the module files affected (I presume) into the `__modules` directory in the instrumented folder.  I've noticed that the module number being requested is not found within the `___wallaby-bundle.js` file and is not one of the numbered files in the `__modules` directory that is generated when wallaby is responding to a change.  Is this significant?  Should the files within the `__modules` directory contain that module number that it is complaining about as a file?

I've tried various different configurations of webpack configuration and it seems to only be when we include the `.less` files into the mix instead of no-op'ing them.  However, we need the `.less` files to get some of our tests to work correctly.  I've also tried creating a smaller project and including less files with circular dependencies and other combinations of tests and I can't get wallaby to break with the same error at all.

**Comment by ArtemGovorov** [comment]
Hi @Anupheaus, 

> I've found that when wallaby tries to update itself based on changes it seems to add the module files affected (I presume) into the __modules directory in the instrumented folder. I've noticed that the module number being requested is not found within the ___wallaby-bundle.js file and is not one of the numbered files in the __modules directory that is generated when wallaby is responding to a change. Is this significant? Should the files within the __modules directory contain that module number that it is complaining about as a file?

All modules are initially bundled into the `___wallaby-bundle.js`, later when webpack incrementally reports that some of the modules are affected, they are written to the `__modules ` directory. It is ok if a module is not present in the `__modules`, as it may be inside the bundle file.

> I've tried various different configurations of webpack configuration and it seems to only be when we include the .less files into the mix instead of no-op'ing them.

Is the `@company/package-name` as described here https://github.com/wallabyjs/public/issues/1372#issuecomment-341108757 still causing the issue? Perhaps the module is referencing some `.less` files?

Could you please try the steps described here https://github.com/wallabyjs/public/issues/1372#issuecomment-341303562?

Also, given you say that it seems to only be when you include the .less files into the mix, what happens if you add a simple test file:

```javascript
import * as p from '../../anyLessFile.less' // valid path to any of your less files
it('fails on change', () => {
  console.log(p);
})
```
leave only this simple test file in your `tests` list, start wallaby and then start editing the file? Does the issue show up? Or it only shows up if some specific `.less` file are included? If so, try including them directly (without any app code) into the simple test. Hopefully this way you'd be quickly able to find the case when the issue is reproducible with the simple test and one or more imported `.less` files.

**Comment by ArtemGovorov** [comment]
Also, try updating `wallaby-webpack` package to 0.0.45, and add the `emitModulePaths: true` setting, and restart wallaby.js:

```javascript
const webpackConfig = require("./webpack.config.base");
webpackConfig.emitModulePaths = true;
```

This time the error message should contain the module path: `Runtime error: Uncaught Error: Cannot find module '{Number}' (module_path)`. If the `module_path` is `undefined`, then the issue is likely related to some circular dependencies between files/modules.

**Comment by elbuilio** [comment]
Hi Artem. Apologies for the delay in responding to your latest comments. We have been up against some deadlines, which I'm sure you will understand. In the meantime our VSCode devs have had to switch to running these particular tests in karma, as we ran out of time to investigate this. We still have about 3500 other tests running via wallaby successfully.

I will hopefully come back to look at this issue again soon.

**Comment by ArtemGovorov** [comment]
Hi Tom,
thanks for the update! Looking forward to sort out the issue for you whenever you have some time to get back to it.

**Comment by ArtemGovorov** [comment]
Closing the issue due to lack of activity. if it's still a valid issue for you, please try the steps listed above, or/and create a sample repo demonstrating the issue - we are happy to have a look into it.
