### ISSUE TITLE
yarn workspaces

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#1374]
### Issue description or question
I have a project that is using **yarn workspaces** to hoist and symlink packages to the project's root. The tests would always use the old code unless I force Wallaby to run the test explicitly. I have created a sample project to demonstrate this.

sample: https://github.com/thomastnguyen91/wallaby-yarn-workspaces

Thanks

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo!
I have sent the [pull request with the working config](https://github.com/thomastnguyen91/wallaby-yarn-workspaces/pull/1).

The issue is that in this case local project's code is being run for the referenced module, as opposed to running instrumented code from the wallaby cache. So [Jest configuration](https://wallabyjs.com/docs/integration/jest.html#jest-configuration) for Wallaby needs to be slightly [adjusted to re-map all scoped packages requests](https://github.com/thomastnguyen91/wallaby-yarn-workspaces/pull/1/files#diff-4e87b2c6dcfa10beeaf6797eaa6c66ecR39) to Wallaby cache with instrumented files:

```javascript
const path = require("path");

module.exports = function(wallaby) {
  return {
    ...

    setup: w => {
      const jestConfig = require('./package.json').jest;
      jestConfig.moduleNameMapper = {
        '^@private-package/(.+)': w.projectCacheDir + '/packages/$1',
      };
      wallaby.testFramework.configure(jestConfig);
    },
  };
};
```

I have also excluded nested `node_modules` from scoped packages, because not dong so may result in unnecessary copying of these modules to Wallaby cache and instrumenting them.

**Comment by thomastnguyen91** [comment]
I see. What would you do though if the name of the package doesn't match the name of the folder?

Such that `foo` was the name of the folder but `foo-foo` was the name of the package? Or vice versa.

I updated the provided sample with this use-case.

**Comment by ArtemGovorov** [comment]
The easiest way in this case would be to explicitly map the exceptions (of module names not following the folder name structure) first, and then have a [convention based mapper](https://github.com/thomastnguyen91/wallaby-yarn-workspaces/pull/2) for the rest.

A bit more robust way would be to dynamically create the `moduleNameMapper` based on package names:

```javascript
module.exports = function (wallaby) {
  return {
    ...

    setup: w => {

      let jestConfig = global._modifiedJestConfig;
      if (!jestConfig) {
        jestConfig = global._modifiedJestConfig = require('./package.json').jest;
        const path = require('path');
        const globby = require('globby');

        jestConfig.moduleNameMapper = globby.sync('packages/*/package.json').reduce((acc, v) => {
          const packageJsonPath = path.join(w.projectCacheDir, v);
          acc['^' + require(packageJsonPath).name] = path.dirname(packageJsonPath);
          return acc;
        }, {});
      }
      wallaby.testFramework.configure(jestConfig);
    },
  };
};

```

**Comment by maciejw** [comment]
damn :) @ArtemGovorov you have everything covered huh :)

**Comment by maciejw** [comment]
my 5 cents 

I had to do it this way
```javascript
 jestConfig.moduleNameMapper = globby
          .**sync(path.join(w.projectCacheDir, 'packages/*/package.json'))**
          .reduce((acc, v) => {
            **const packageJsonPath = v;**
            acc['^' + require(packageJsonPath).name] = path.dirname(
              packageJsonPath,
            );
            return acc;
          }, {});

```
otherwise node.exe will scan half of my disk :) 

for some strange reason I my cwd is different than yours

**Comment by ArtemGovorov** [comment]
@maciejw Thanks for the note! Updated my sample to include your change.

**Comment by maciejw** [comment]
@ArtemGovorov and remove second path.join inside reduce :)
