### ISSUE TITLE
Support ava-ts

### ISSUE THREAD

**Issue by Hazealign** [wallabyjs/public#1384]
### Issue description or question
[ava-ts](https://github.com/andywer/ava-ts) will be nice option for typescript users who used ava. 

### Wallaby.js configuration file

```javascript
const tsConfig = require('./tsconfig.json')

module.exports = (wallaby) => {
  return {
    name: 'Evidnet Server v2',
    files: [
      'src/**/*.ts'
    ],

    tests: [
      'test/**/*.spec.ts',
      'test/**/*.e2e-spec.ts'
    ],
    
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(tsConfig.compilerOptions)
    },
    env: {
      type: 'node',
      runner: 'node'
    },
    debug: true,
    testFramework: 'ava',
    delays: {
      run: 1000
    },
    slowTestThreshold: 500,
    lowCoverageThreshold: 85,
    reportUnhandledPromises: true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.18.0-insider

### OS name and version

Windows 10 Fall Creators Update

**Comment by ArtemGovorov** [comment]
Wallaby builds TypeScript on the fly anyway, why would you need ava-ts (with wallaby), if you may just use ava (with wallaby) and still use TypeScript?

**Comment by Hazealign** [comment]
I met #1383 in ava with typescript. But in ava-ts. it works very well.

![image](https://user-images.githubusercontent.com/1115741/32647504-ebdf7ca6-c634-11e7-8817-5fc33916beb1.png)

**Comment by ArtemGovorov** [comment]
If you create a sample repo where I could reproduce the issue, I'm happy to have a look. I'm pretty confident that I'll be able to help configuring wallaby without ava-ts once I can reproduce the issue.

**Comment by Hazealign** [comment]
https://github.com/Hazealign/test-server

Here's the sample repo. (It requires Redis in 6379 port.)

**Comment by ArtemGovorov** [comment]
Thanks for the repo! Have sent you the pull request to make it work: https://github.com/Hazealign/test-server/pull/1

The issue was that the `typeorm` that you're using is trying to load `.ts` files (as well as compiled `.js` files). As I have mentioned in the previous issue, Wallaby is compiling .ts files to .js and leaves .ts files lying around. I have added [wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) for all compiled `.js` files, and the preprocessor deletes corresponding `.ts` files, so that `typeorm` doesn't try to load them:

```diff
+    preprocessors: {
+      '**/*.js?(x)': f => (
+        require('fs').unlinkSync(require('path').join(wallaby.projectCacheDir, f.path.replace('.js', '.ts'))), 
+        f.content
+      )
+    },
```

Hope it makes sense.
