### ISSUE TITLE
Vue.js snapshots with Jest

### ISSUE THREAD

**Issue by AWolf81** [wallabyjs/public#1393]
### Wallaby.js configuration file

```javascript
// working setup for mocha tests
const webpackConfig = require('./build/webpack.test.conf.js')
const wallabyWebpack = require('wallaby-webpack')

module.exports = function (wallaby) {
  webpackConfig.resolve.alias = {'@': require('path').join(wallaby.projectCacheDir, 'src')}
  webpackConfig.externals = {vue: 'Vue'}
  webpackConfig.module.rules.find(r => r.loader === 'vue-loader').options.loaders.js = ''

  const wallabyPostprocessor = wallabyWebpack(webpackConfig)

  return {
    files: [
      {pattern: 'node_modules/vue/dist/vue.js', instrument: false},
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      // {pattern: 'node_modules/babel-polyfill/browser.js', instrument: false},
      {pattern: 'src/**/*.*', load: false},
      {pattern: 'src/**/*.test.js', load: false, ignore: true}
    ],

    // env: {
    //   type: 'browser'
    // },

    tests: [
      {pattern: 'test/**/*.spec.js', load: false}, // tests from https://github.com/ChangJoo-Park/vue-wallaby-webpack-template
      {pattern: 'src/**/*.test.js', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    setup: function () {
      // eslint-disable-next-line
      Vue.config.errorHandler = function (err) {
        throw err
      }
      // eslint-disable-next-line
      Vue.config.productionTip = false

      window.__moduleBundler.loadTests()
    },

    // testFramework: 'jest',

    hints: {
      ignoreCoverage: /ignore coverage/
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

    debug: true,

    screenshot_on_failure: true
  }
}

// webpack.test.conf.js

// This is the webpack config used for unit tests.

var utils = require('./utils')
var webpack = require('webpack')
var merge = require('webpack-merge')
var baseConfig = require('./webpack.base.conf')

var webpackConfig = merge(baseConfig, {
  // use inline sourcemap for karma-sourcemap-loader
  module: {
    rules: utils.styleLoaders()
  },
  devtool: '#inline-source-map',
  resolveLoader: {
    alias: {
      // necessary to to make lang="scss" work in test when using vue-loader's ?inject option
      // see discussion at https://github.com/vuejs/vue-loader/issues/724
      'scss-loader': 'sass-loader'
    }
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': require('../config/test.env')
    })
  ]
  // target: 'web',
  // node: {
  //   fs: 'empty'
  // }
})

// no need for app entry during tests
delete webpackConfig.entry

module.exports = webpackConfig

```

### Code editor or IDE name and version

Atom v1.22.0

### OS name and version

Windows 10 Pro (64bit)

### Repository with my latest code
https://github.com/AWolf81/Nonprofiters.com/tree/wallaby-setup

Branch wallaby-setup contains the setup.

### Description
I'm getting the following error message `Error: Cannot find module "fs"`. This seems like `vue-server-render` needs to run in a node environment. But I don't know how to fix this. 

Webpack is used to handle Vue files.

The snapshot test is in file `src/modal/Login.test.js`.  Just snapshot testing is not working. Beside that testing of Vue files seems to work properly. Not sure if setup could be simplified.

I'd also like to use jest for testing but I'm not sure if I'm using it correctly. Is there a way to check if the test framework is Mocha or Jest?

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo!

> I'd also like to use jest for testing but I'm not sure if I'm using it correctly. Is there a way to check if the test framework is Mocha or Jest?

You need to [use the `testFramework` setting](https://wallabyjs.com/docs/config/overview.html#testing-framework-setting) to specify the testing framework.

Currently you are running tests in browser environment and by default the browser environment is using Jasmine. To configure wallaby to run your tests with Jest, you may read this [Jest specific docs section](https://wallabyjs.com/docs/integration/jest.html). 

Webpack (and the bits related to it) is not required at all because Jest runs in node (so the `env: {type: 'node'}` setting is required). Wallaby will read Jest settings from your `package.json`, but one slight adjustment is required: because you [map module paths](https://github.com/AWolf81/Nonprofiters.com/blob/wallaby-setup/package.json#L21), in wallaby `setup` function you need to replace `<rootDir>` with wallaby project cache dir (so that the files are taken from wallaby cache where they are compiled and instrumented, and not from your local project).

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.*',
      '!src/**/*.test.js'
    ],

    tests: [
      'test/**/*.spec.js',
      'src/**/*.test.js'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
      '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    },

    testFramework: 'jest',

    setup: function (wallaby) {
      const jestConfig = require('./package.json').jest;
      jestConfig.moduleNameMapper = {
        "^@/(.*)$": wallaby.projectCacheDir + "/src/$1"
      };
      wallaby.testFramework.configure(jestConfig);
    },

    debug: true
  };
};
```

I have sent you the [pull request](https://github.com/AWolf81/Nonprofiters.com/pull/1) with the changes to make it work with Jest.
