### ISSUE TITLE
Support vim!

### ISSUE THREAD

**Issue by leyyinad** [wallabyjs/public#14]

**Comment by franleplant** [comment]
+1

**Comment by kapral18** [comment]
+1

**Comment by kevindurb** [comment]
+1

**Comment by hoschi** [comment]
+1

**Comment by jzgit** [comment]
+1

**Comment by bajtos** [comment]
+1

**Comment by slouffka** [comment]
+1

**Comment by railsnerd** [comment]
+1

**Comment by jeduden** [comment]
+1

**Comment by simlevesque** [comment]
+1

**Comment by mbrochh** [comment]
+1

**Comment by AndreiBarsan** [comment]
+1

**Comment by bikegriffith** [comment]
+1, the feedback loop and workflow you've enabled is nothing short of amazing.

**Comment by bustardcelly** [comment]
+1

**Comment by hojberg** [comment]
+1

**Comment by ElijahKaytor** [comment]
+1

**Comment by TylerNHansen** [comment]
+1

**Comment by RyanParsley** [comment]
+1

**Comment by captcodemonkey** [comment]
+1

**Comment by CheshireSwift** [comment]
+1

**Comment by realyze** [comment]
+1

**Comment by dsibiski** [comment]
+1

**Comment by AustinMatherne** [comment]
+1

**Comment by hellboy81** [comment]
+ infinity

**Comment by Devric** [comment]
+(x)

**Comment by davyengone** [comment]
+1

**Comment by onemanstartup** [comment]
There is a button "Subscribe". So stop +1, just subscribe and wait for it to happens.

**Comment by maximgladkov** [comment]
+1

**Comment by QuantumInformation** [comment]
+1

**Comment by nzbart** [comment]
+1

**Comment by Tuch** [comment]
+1

**Comment by unel** [comment]
+100500! =)

**Comment by asunar** [comment]
+1

**Comment by fvanwijk** [comment]
@onemanstartup It's Github's fault. See https://github.com/dear-github/dear-github. (Google 'dear github' for background info)

**Comment by matt-paul** [comment]
+1

**Comment by briemens** [comment]
+1

**Comment by al-the-x** [comment]
Sadly, while viewing from mobile, this is still the easiest way to subscribe to this thread. Mobile-_last_ design.

**Comment by kawikadkekahuna** [comment]
+1

**Comment by mattjbones** [comment]
+1

**Comment by FieryCod** [comment]
+1

**Comment by hewge** [comment]
+1

**Comment by retrocede** [comment]
+1

**Comment by alex-shamshurin** [comment]
+1 Yes and we need support via ALE.vim for async support.

**Comment by dimpu** [comment]
+1

**Comment by pmsorhaindo** [comment]
+1

**Comment by omenking** [comment]
Seriously, where the heck is the VIM support?

**Comment by pmsorhaindo** [comment]
+1

**Comment by hmorgancode** [comment]
+1

This would help me convince my company to get a few licenses- a solid portion of our heavy JS coders use vim.

**Comment by ultrox** [comment]
+1 Wallaby is awesome, Vimablly ftw

**Comment by phsantiago** [comment]
+1

**Comment by rafaelkallis** [comment]
+1

**Comment by jackolantern** [comment]
+1

**Comment by mictian** [comment]
+1

**Comment by pietvanzoen** [comment]
+1

**Comment by dacostarepublic** [comment]
+1

**Comment by c0ndu17** [comment]
+1

**Comment by andresattler** [comment]
+1

**Comment by heisian** [comment]
My brothers, where hast thou been!? Are we but the last of the holdouts against the threshes of Electron bloat? Let our voices ring in unison!

**Comment by floridait** [comment]
Maybe I will just write a plugin for it.

+1

**Comment by DoWhileGeek** [comment]
I'd say +1, but this ticket is over two years old, with (to the best of my knowledge) 0 response from the wallabyjs folks. Maybe they just dont serve our kind here?

**Comment by ajtakrajta** [comment]
Neovim 0.3.2 will support feature called "virtual text": https://twitter.com/Neovim/status/1059496809989632000

It looks it will be possible to easily display Wallaby's context messages. Any chance this will convince you to support at least neovim?

How about a crowdfunding for initial implementation?

**Comment by ajtakrajta** [comment]
Neovim 0.3.2 is released. 

Example of virtualtext feature usage: https://github.com/yardnsm/vim-import-cost/commit/404e9647b31a20940d09c943ba2c69e31d68e50d

**Comment by ajtakrajta** [comment]
...and Neovim 0.4 is released with tons of new stuff. Floating windows could be useful for Wallaby support.

https://github.com/neovim/neovim/commit/e2cc5fe09d98ce1ccaaa666a835c896805ccc196

**Comment by und3rdg** [comment]
+1

**Comment by oludiro** [comment]
+1

**Comment by eyaleizenberg** [comment]
2020 and still no Wallaby in Vim... 😿

**Comment by azat-io** [comment]
+1

**Comment by lucax88x** [comment]
The main reason why I will discontinue my membership.. :(

**Comment by willfish** [comment]
👍

**Comment by uWynell** [comment]
+1

**Comment by kingedward35** [comment]
+1

**Comment by aquillano** [comment]
+1

**Comment by inspmoore** [comment]
+∞ 
Support vim/nvim and I will personally write a thirteen syllable sonnet of praise for every team member!

**Comment by MatthD** [comment]
+1 for me, will be very helpful to code with vim :)

**Comment by Muslik** [comment]
+1

**Comment by rbutera** [comment]
+1

**Comment by javeoff** [comment]
+1

**Comment by caiobep** [comment]
Is there anything we as a community can do to help this happen?

I know that It might be very upsetting to have this thread resurrected from time to time. But it's tough for VIM users to change IDEs to use Wallaby and Quokka. Compared with all other text editors, it seems like VIM is the one that is not going anywhere since people have been using it since the early 90s, which is not the case for most IDEs.

**Comment by smcenlly** [comment]
While we know many people use VIM (or some flavour of VIM), unfortunately it accounts for a relatively low percentage of users compared to other editors and right now we are focusing feature development to benefit as many people as we can.

As a team, we have a barrier to entry in that we're not familiar with VIM or with VIM APIs for extension development. We don't even know if everything that Wallaby/Quokka need to do is supported by VIM and VIM APIs.

If someone has that expertise and is wants to work on a plugin, send us an email (hello@wallabyjs.com) and we can discuss how it might work (level of effort, etc.). Unfortunately any contributions would not be able to be open-source so that may be a bit of a blocker for people who may be interested in helping.

**Comment by lucax88x** [comment]
Appreciate your intervention!

If I can add my two cents about your "low percentage of users compared to other editors"

If you notice the [SO developer survey](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-integrated-development-environment) you can notice that vim + neovim take ~30%.

If that sounds appealing to you, then about the barrier within vimscript/lua, I'm pretty sure we can find a solution. 

Maybe raise a patreon, kickstarter, something like that to pay the developer, and eventually give some discounts to the guys that participated to the funding, would it be a good idea?

**Comment by smcenlly** [comment]
> If you notice the [SO developer survey](https://insights.stackoverflow.com/survey/2021#section-most-popular-technologies-integrated-development-environment) you can notice that vim + neovim take ~30%.

It's hard to try and determine true usage. We analysed the usage statistics across a variety sources, including the stack overflow survey. For stack overflow, we looked at the total number of responses for each editor we support vs. the total. So you can understand our thinking:

| Editor      | Responses |
| ----------- | ----------- |
Visual Studio Code | 58,026
Visual Studio | 26,970
Notepad++ | 24,262
IntelliJ | 23,467
Vim | 19,752
Android Studio | 18,141
Sublime Text | 16,714
PyCharm | 15,755
Eclipse | 12,955
Atom | 10,564
IPython/Jupyter | 10,310
Xcode | 9,040
Webstorm | 6,564
PHPStorm | 6,096
NetBeans | 5,839
Emacs | 4,327
Neovim | 4,071
Rider | 3,255
RStudio | 3,200
RubyMine | 1,219
TextMate | 678
**Vim / NeoVim** | 23,823
**TOTAL** | 281,205

Vim % of total works out to be 23,823 / 281,205 = 8.5%.

We know these numbers aren't necessarily representative of proper use, and I think some of the editors are counted twice. For example, some people may use VS Code in addition to Vim (Vim for backend code, VS Code for front-end, etc.). Similarly, some people may use VS Code because what they want/need in Vim isn't supported (e.g. remote containers, other extensions, etc.). 

I also suspect (hard to determine) that the % that use Vim for JavaScript/TypeScript development is lower than 8.5%, but it's the best measure we have.

I don't mean to start any sort of argument about usage statistics or our analysis of them, but I did want to share for transparency.

We really appreciate everyone's interest in this issue (and adding Wallaby support for Vim) and we will be talking about the priority of this issue over the next day or two.

**Comment by dahmc** [comment]
Since neovim now has first class Lua support, this might also make things a lot easier for implementation than a pure Vimscript approach, in case that's a big blocker as well.

**Comment by HowlingEverett** [comment]
I'd love to see some movement on this as well. To wade into the controversy a bit - Wallaby.js has an Atom plugin, and that was a flash in the pan editor that is now well below the usage numbers of vim/neovim. Given Microsoft has VSCode now, it's fair to say Atom is on the way out.

By comparison, vim/neovim users are die-hard enthusiasts unlikely to switch editors unless they're dragged away with excessive force. You're absolutely right that it's a small market (but...so was Atom, even in its ascendancy) but it's also a market that won't drain away if you capture it.

I obviously don't have any exposure to the closed-source parts of Wallaby's plugins, but I think it's a somewhat safe assumption that at least a few of them are written in Javascript running under Electron. It's not lightweight, but one option to ease the transition may be [vim-electrify](https://github.com/bryphe/vim-electrify) a vim plugin wrapper that basically runs Electron in a sub-process to allow asynchronous vim plugins written in javascript. My point being that even if the issue is that it's a bad business case to pay for a Lua reskill or hire to write a new plugin, there may be options to get something going.

**Comment by dahmc** [comment]
@rbutera There will not be an Onivim2, see https://github.com/onivim/oni2/issues/3811#issuecomment-910306404

**Comment by rbutera** [comment]
Just thought I might add this screenshot from the google trends page for `neovim` that may be of interest

![image](https://user-images.githubusercontent.com/6047293/194975855-a1a8b2e4-f681-42a2-bed4-f4e34de7b311.png)
[

**Comment by smcenlly** [comment]
Adding support for `neovim` is not on our short-term list of priorities but it is something that our team is keen to work on. If I had to guess, I would suggest we'd start looking at it early 2023 but it is just a guess.

RE: interest over time, the jump in interest from `2022-01-01` is because of improvements to Google Trends data collection. You can see this over a range of terms:

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/2074089/195215773-9c64ecdb-7d5e-4060-b2e4-8df808699d3c.png">

**Comment by undg** [comment]
Indeed something happened with google trends at beginning of last year.
![image](https://user-images.githubusercontent.com/5306983/210267876-a0246669-c177-42c9-866c-21bc61b871de.png)

**Comment by thedanielfactor** [comment]
+1, I have fully switched to NeoVIM and Wallaby is the ONLY thing I miss...  I would be willing to look at building a plugin if there was some sort of api.

**Comment by DaniBedz** [comment]
Lack of support for neovim is the only thing preventing me from renewing my licence. Please consider it.

**Comment by alexandermckay** [comment]
I love Wallaby.js so much that I use Visual Studio Code even though I want to be using Neovim.

🤞🤞🤞Pretty please add support for Neovim 🙏🙏🙏

**Comment by jellydn** [comment]
+1

**Comment by rbutera** [comment]
@smcenlly has there been any progress on the internal discussion regarding neovim support?

**Comment by arc41t3ct** [comment]
There are better tools now. These guys do not care.

**Comment by smcenlly** [comment]
@rbutera - thanks for your continued interest in this issue. Nothing has changed since my [last update](https://github.com/wallabyjs/public/issues/14#issuecomment-1275394359).

Having said that, we've recently added to our development team, and we do have members of our team actively using VIM. Like I had mentioned previously, our team is keen to work on VIM support. Unfortunately it is still not on our short-term list of priorities and we don't have any solid plans I can share, or a timeline we are committing to.

**Comment by javeoff** [comment]
I go to check if support added every month. I just waiting

**Comment by Console-buche** [comment]
Still hoping for neovim port ! <3

**Comment by rryter** [comment]
Also very much interested in this. Since it's a little bit more than a year since that last update, did anything change in the meantime @smcenlly? Thanks a lot!

**Comment by smcenlly** [comment]
For the last 6+ months, most of our team has been working on a comprehensive overhaul of Wallaby (we're calling it Wallaby 2.0) that will significantly boost performance and usability. This includes a brand new user experience (UX) and many other optimizations and updates. These same program of work will also translate to one of our other products, [Quokka.js](https://quokkajs.com), and some parts of it to our [Console Ninja](https://console-ninja.com) product.

Part of Wallaby 2.0 will be the release of a stand-alone version of Wallaby that runs **completely outside of the editor**. This will allow you to use Wallaby with any text editor (not just those with official Wallaby plugins). We're expecting the stand-alone version of Wallaby will be very useful to the VIM community. 

Once we have released Wallaby 2.0, we will evaluate whether we want to (or even need to) implement a first-class in-editor integration for VIM* editors.

**Comment by Console-buche** [comment]
THIS IS AWESOME. Thank you so much for the hard work can't wait to try it out on my nvim

**Comment by ArtemGovorov** [comment]
Wallaby 2 is live 🚀 https://wallabyjs.com/blog/wallaby-2.html, and it can now be used with [any editors, including Vim](https://wallabyjs.com/docs/intro/standalone/).

**Comment by MrFlashAccount** [comment]
it's been 9 years 🥹

**Comment by mirql** [comment]
> it's been 9 years 🥹

10 :3
