### ISSUE TITLE
Wallaby doesn't take import/exports into account when determining tests for rerunning

### ISSUE THREAD

**Issue by asvetliakov** [wallabyjs/public#1405]
### Issue description or question

Take a some generic structure:

src/ab/a.js
```js
export function a() {
    return "a";
}
```

src/ab/b.js
```js
export function b() {
    return "b";
}
```

**src/ab/index.js**
```js
export * from "./a";
export * from "./b";
```

src/consumer/acons.js
```js
import { a } from "../ab"
export function consumer() {
    return a();
}
```

src/consumer/bcons.js
```js
import { b } from "../ab";
export function consumer() {
    return b();
}
```

**src/consumer/acons.spec.js**
```js
import { consumer } from "./acons";
it("a consumer", () => {
    expect(consumer()).toBe("a");
});
```

**src/consumer/bcons.spec.js**
```js
import { consumer } from "./bcons";
it("b consumer", () => {
    expect(consumer()).toBe("b");
})
```

So both consumers are pointing to ```src/ab``` but using different imports

**Expected**
Changing ```src/ab/a.js``` re-runs only ```src/consumer/acons.spec.js``` 

**Actual**
Changing ```src/ab/a.js``` re-runs both ```src/consumer/acons.spec.js``` and ```src/consumer/bcons.spec.js``` (seen from logs with debug: true)

This is the big issue with large codebases and monorepos

**Comment by ArtemGovorov** [comment]
Wallaby does actually take import/exports into account when determining tests for rerunning. In this case the `src/consumer/bcons.spec.js` depends on the `src/ab/a.js` file, because in order to execute the spec, the `src/ab/a.js` file has to be executed. In other words, loading the `src/consumer/bcons.spec.js` causes the `src/ab/a.js` file to load. This creates a dependency between those files that Wallaby has to take into account.

> **Expected**
> Changing ```src/ab/a.js``` re-runs only ```src/consumer/acons.spec.js``` 

Consider this scenario:
- you don't have the `src/consumer/bcons.spec.js` file at all.
- your **src/ab/b.js** looks like

```js
boom;
export function b() {
    return "b";
}
```

You run your tests and they fail, because your only test file depends on a failing dependency. You click the stack trace, open `src/ab/b.js` and comment out the `boom` line. Do you expect wallaby to run your `src/consumer/acons.spec.js` file?

**Comment by ArtemGovorov** [comment]
Sorry, clicked send before completing the post. So

> Do you expect wallaby to run your `src/consumer/acons.spec.js` file? 

You do, because it is failing, the failure reason had been fixed and you want the test to pass.

The issue is not only with the global scope errors, it's just a simple example. If loading a test file causes another file to load, then the loaded file can potentially create many valid reasons (and/or side effects) that may affect the test.

**Comment by asvetliakov** [comment]
Yes, these are valid points. I understand them. But recently i run into scenarios when only simple change in react component triggers many test suites executions because this component is being re-exported with index.js. This is not very optimal.

 >your src/ab/b.js looks like
This is very opionated. If there will be consumers for ```b.js``` then it will fail for these tests only. It not - then it will fail then some consumer will be pointed to ```b.js```.  Yes, there could be global side effects for ```b.js```. But how much are you writing such code (with global side effects) in your daily work? I don't remember such single statement for a few past months.

So, due to possibility of side effects/similar things, it may be possible to introduce this feature enabled by some configuration flag only? May be with optional jsdoc comment to disable behavior for particular file.

**Comment by ArtemGovorov** [comment]
> But recently i run into scenarios when only simple change in react component triggers many test suites executions because this component is being re-exported with index.js. This is not very optimal.

Many of your test suites do depend on the component to at least load successfully. A simple change that's breaking the component code may break these tests. 

Importing the component directly to the test (and avoiding to import it via `index.js` exports) would solve the issue, wouldn't it? If components are exporting stuff that can be imported by `index.js`, then it can certainly be imported directly by tests. Not only it'll make wallaby (and Jest watch mode) run faster because of more efficient change tracking, it'll also make tests run faster because each individual test file will only be importing (and thus executing and compiling in node) only required dependencies and not the whole project with components.

> This is very opionated. If there will be consumers for ```b.js``` then it will fail for these tests only. It not - then it will fail when some consumer will be pointed to ```b.js```.

The problem is that the `a.spec` is also a consumer for `b.js`, because it loads it. So no matter if you have tests for `b.js`, or don't have them yet (or at all), or they are failing for a different reason, `a.spec` status depends on `b.js` code changes.

> Yes, there could be global side effects

Doesn't have to be global side effects produced by the module. Importing other modules (yours or third party), caching on a module level, lazy loading on a module level - all that in module `b.js` can make `a.spec` to change its status from passing to failing. The side effect may also be introduced by third party modules imported into your `b.js` module (thus not under your control, and worse - hardly discoverable).

> it may be possible to introduce this feature enabled by some configuration flag only? 

Ideally (that's what Wallaby is trying to do), your full test run results should be the same as incremental test run results. I.e. if there's a problem, you should know about it not only if you re-run all of your tests. What you're asking for contradicts this simple principle. 

Nevertheless, I have just added a setting to turn the loading phase dependency tracking off, you need to update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) and add the setting to your config:

```javascript
module.exports = function (wallaby) {

  return {
    ...
    ignoreFileLoadingDependencyTracking: true
  };
};
```

But I need to warn you, that using the setting may hurt (in some ways that it's even hard to predict).

For example, from the file loading dependency tracking perspective, the dependency between `a.spec` and `b.js` is not different from the dependency between `a.spec` and `a.js`. So disabling the tracking means that changing `a.js` global scope (like adding a new exported function) will also not trigger `a.spec` to run. Changing the function inside the `a.js` file will still cause `a.spec` to run as usually though (because it's another type of dependency that we are also tracking).

Anyway, as I said, I'd rather recommend importing components from tests, but if you'd like to give the setting a go, let us know how it goes for you.

**Comment by asvetliakov** [comment]
>Importing the component directly to the test (and avoiding to import it via index.js exports) would solve the issue, wouldn't it?
>To sum it up, I'd rather recommend importing components from tests, but if you'd like to give the setting a go,

Yes, it will solve the issue. But it's not always achievable if you're building your final package which you're importing via rollup or similar module bundler which will flatten the structure into single ```index.js``` file, so there won't be any internal packages. Also it's not an elegant way to write code:
```js
import { A } from "../../../../../packages/internal1/internal2/internal3/A"
```
It's hard to maintain and in many cases breaks tooling. Using URL-like imports (for example via jest moduleNameMapper and webpack alias) breaks [other things](https://github.com/facebook/jest/issues/4262) and it's not trivial to setup if you're building node service.

Tried the new setting, not sure i understand how does it work:

![untitled](https://user-images.githubusercontent.com/8881674/33177050-8d030edc-d061-11e7-8bdd-f0e24dfb6631.png)

The change in ```Tab.tsx``` triggers related ```Tab_Spec.tsx``` test but doesn't trigger ```Settings_Spec.tsx``` even if ```Tab``` imported directly in test.

In simple example in the first post it works for additional files importing the ``` { a } ```

Anyway, great improvement, since i'm usually mocking external components, Thanks!

**Comment by ArtemGovorov** [comment]
> Yes, it will solve the issue. But it's not always achievable if you're building your final package which you're importing via rollup or similar module bundler which will flatten the structure into single ```index.js``` file, so there won't be any internal directories. Also it's not an elegant to write such code:
```js
import { A } from "../../../../../packages/internal1/internal2/internal3/A"
```
> It's hard to maintain, introduces dependency to monorepo structure and in many cases breaks IDE tooling. Using custom mapped imports (for example via jest moduleNameMapper with webpack alias) breaks [other things](https://github.com/facebook/jest/issues/4262) and it's not trivial to setup them if you're developing plain node service.

I may be missing something, but if you have a [lerna monorepo](https://github.com/wallabyjs/public/issues/1265) with a package called `myComponents` and `myComponents` index.js looks like

```javascript
export * from "./myComponent1";
export * from "./myComponent2";
```

then in your spec file instead of
```javascript
import { myComponent1 } from "myComponents"
```

you may just do

```javascript
import { myComponent1 } from "myComponents/myComponent1"
```

Surely, if your component is located in a deeper folder like `myComponents/internal/myComponent1`, the import will look a bit worse:

```javascript
import { myComponent1 } from "myComponents/internal/myComponent1"
```

But it's not as bad as the relative import in your example, and shouldn't break any tooling (given that `import ... from "myComponents"` doesn't break the tooling).

The only issue I see here is that, as you've pointed put, it "introduces dependency to monorepo structure". I personally wouldn't bother about the dependency to monorepo structure, because with modern tooling, refactoring multiple `import { myComponent1 } from "myComponents/internal/myComponent1"` (for example as a result of the structure change) is not much harder than refactoring multiple `import { myComponent1 } from "myComponents"` (for example as a result of the component name change).

Also, as you have also mentioned, there are ways to solve it purely via a testing configuration (even without `moduleNameMapper` - [example 1](https://github.com/wallabyjs/public/issues/1265#issuecomment-341964487), [example 2](https://github.com/ArtemGovorov/wallaby-1265/blob/master/wallaby.js#L26-L29)).

> Tried the new setting, not sure i understand how does it work
> The change in ```Tab.tsx``` triggers related ```Tab_Spec.tsx``` test but doesn't trigger ```Settings_Spec.tsx``` even if ```Tab``` imported directly in test.

Yes, the new setting is supposed to work this way. Basically the new setting tells wallaby to completely ignore loading dependencies between files. So if a spec file imports any other files, but is not calling any functions in them, then the dependency between the spec and those files is ignored. There are also a few heuristic rules that may sometimes change the process.

**Comment by asvetliakov** [comment]
>but is not calling any functions in them, then the dependency between the spec and those files is ignored
So this won't introduce dependency in wallaby:
```js
import { Tab } from "..";
wrapper.find(Tab);
```

but these ones do:
```js
import { Tab } from "..";
Tab();
<Tab />
```
correct? Then this is exactly what i need 👍 

>then in your spec file instead of
You usually are not testing component from different package in other package. I'm having something like this:
consumerPackage/Component.js
```js
import { Comp1 } "myComponents";
...
```
consumerPackage/Component.spec.js
import ConsumerComponent from "./Component";
```

By default this will create dependency -> Component.spec.js -> consumerPackage/Component.js -> myComponents (package) -> myComponents/Comp1 (re-exported in myComponents). 

It's not achievable to import ```import { Comp1 } from "myComponents/Component";``` in this case if ```myComponents``` will be built via rollup or similar thing, which will flatten internal structure into single file (in separate compilation step)
And i believe it's useless to additionally import ``` "myComponents/Component"``` from ```Component.spec.js``` since there is already dependency chain to top-level ```myComponent``` package from ```consumerPackage/Component.js``` , correct?

Anyway i'm already satisfied of behavior with ```ignoreFileLoadingDependencyTracking: true```. My sources don't have any global side-effects and usually mocked for subject under test. So instead re-running 20-200 test suites i'm getting only few now.

**Comment by ArtemGovorov** [comment]
> So this won't introduce dependency in wallaby:
```js
import { Tab } from "..";
wrapper.find(Tab);
```

> but these ones do:
```js
import { Tab } from "..";
Tab();
<Tab />
```
>  correct? Then this is exactly what i need 👍 

Yes, it's correct.

> You usually are not testing component from different package in other package. I have something like this

Ah, ok, got it. 

> in this case in `consumerPackage/Component.js` if `myComponents` will be built via rollup or similar thing, which will flatten internal structure into single file (in separate compilation step)

I see. This obviously means that all consumers of the `myComponents` package (not just tests) will need to load the whole package even if they need just one simple component from it, but I'm guessing you're aware of that and it is an acceptable choice in your specific scenario.

> Anyway i'm already satisfied of behavior with ```ignoreFileLoadingDependencyTracking: true```. My sources don't have any global side-effects and usually mocked for subject under test. So instead re-running 20-200 test suites i'm getting only few now.

Great, I'm hoping you don't hit any issues when some errors are not caught during incremental runs (if you do - then using `Run project tests` command can be helpful to run, it's faster than the full restart).

**Comment by asvetliakov** [comment]
>will need to load the whole package even if they need just one simple component from it

webpack or rollup (in case of building another consumable lib built on top of other lib) will tree-shake it for production builds.

>Run project tests command can be helpful to run, 

This will skip instrumentation of files compared with full restart, correct? Thanks

**Comment by ArtemGovorov** [comment]
> webpack or rollup (in case of building another consumable lib built on top of other lib) will tree-shake it for production builds.

Fair enough.

> This will skip instrumentation of files compared with full restart, correct? 

Yes, and as well as many initialisation steps, file cache checking, testing framework loading, etc.
