### ISSUE TITLE
Vue with Typescript single file components

### ISSUE THREAD

**Issue by amontin** [wallabyjs/public#1406]
### Issue description or question
Any idea how I should configure my wallaby.js file to run tests against Vue single file components, with the script section written in Typescript? My current configuration is below, but it gives the following error when I try running wallaby: "TypeError: scriptCompiler is not a function​​" @ "wallaby-vue-compiler/index.js:16:29​​". 

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
      files: [
        'src/**/*.*',
      ],
      tests: [
        'test/**/*Spec.js'
      ],
      compilers: {
        '**/*.js': wallaby.compilers.babel({babelrc: true}),
        '**/*.ts': wallaby.compilers.typeScript(),
        '**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.typeScript()),
      },
      testFramework: "mocha",
    };
  };
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

OSX 10.11.6

**Comment by ArtemGovorov** [comment]
Wallaby TypeScript doesn't currently support single file components. Having said that, you may still run tests against them. 

Please share a sample project with with a dummy test and single file component, plus working mocha configuration (so that your test could run without wallaby), and I'll send you a pull request with wallaby configuration for it.

**Comment by ArtemGovorov** [comment]
Also looks like your config is missing webpack configuration. You are running your tests in browser, aren't you? Or in node?

Here is an [example of a Wallaby config for a project using Vue and TypeScript](https://github.com/jraller/Vote/blob/master/wallaby.conf.js). It probably contains more than you need, but hopefully you can get the idea. Also note that script sections are referencing Typescript files.

If the config doesn't address your question, please share a sample project with with a dummy test and a single file component, plus working mocha configuration (so that your tests could run without wallaby) and webpack config (if you have one) - happy to have look and help with Wallaby config for it.

**Comment by amontin** [comment]
Thanks for replying so promptly. I can work around this issue, and the config example is a great help. If necessary, I can reopen this issue in the future and post and sample project with an SFC.
