### ISSUE TITLE
"Node process reuse" doc confusion

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1407]
I've always found it a little confusing.

- https://wallabyjs.com/docs/config/workers.html
- https://wallabyjs.com/docs/integration/node.html#node-process-reuse

> wallaby by default tries to re-use previously created node.js process(es) to make the runs faster

To me, this sounds like it is "recycling" the processes.

But then as you continue reading it says to set `workers.recycle` to `true` to re-start processes, which I would argue is not recycling at all - its more like trashing them.

Until this day I always thought `wallaby.recycle` meant reuse.

---

Also, why not use the same value for `initial` and `regular` workers?

What happens to the difference? Are these workers terminated? Or do we cycle between them?

---

The  default you say is `regular = initial / 2`. Why?

---

Also from https://wallabyjs.com/docs/config/overview.htm:

> defaults property which allows you to set the default values for file object properties.

What do you mean by "file object properties"?

**Comment by ArtemGovorov** [comment]
> Until this day I always thought `wallaby.recycle` meant reuse.

Agreed, it is confusing. "re-use" in this context was meant to be "keep using the process as is", while "recycle" was meant to be "convert into a reusable material/state first".

Will come up with a better name and fix the docs/replace `recycle` with a better name.

> Also, why not use the same value for `initial` and `regular` workers?

Typically users want the initial start to be as fast as possible (so are ok to do the initial run at the full system capacity), while for regular/incremental runs they may not want to load their system too much (as it may affect their editors/other running tasks).

> What happens to the difference? Are these workers terminated? Or do we cycle between them?

Wallaby will cycle between them if necessary. But it's really just an implementation detail that shouldn't affect the way you're using the setting, because if there're no enough processes for some purpose, wallaby will always create them.

>Also from https://wallabyjs.com/docs/config/overview.htm:

>> defaults property which allows you to set the default values for file object properties.

> What do you mean by "file object properties"?

Both **`files`** and **`tests`** property element can either be a string representing a file name/name pattern, or an object that defines additional properties (like `pattern`, `instrument`, etc). 

I have added a link from the config overview to the [relevant docs section](https://wallabyjs.com/docs/config/files.html#overriding-defaults), so now there's some context.

**Comment by vjpr** [comment]
Thanks, all clear now!
