### ISSUE TITLE
Process exit hook to clear database connections

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1409]
I am encountering same issue as https://github.com/wallabyjs/public/issues/1088 using postgres database, where database connections are left open after running a few times.

`recycle: true` would probably solve my issue, but it would be cool to have some concurrency. I create a separate database for each `workerId`.

I tried adding this code to setup, but it was never called:

```js
      process.on('exit', () => {
        console.log('PROCESS EXITING!')
      })

      //catches ctrl+c event
      process.on('SIGINT', () => { console.log('sigint') });

      // catches "kill pid" (for example: nodemon restart)
      process.on('SIGUSR1', () => { console.log('sigusr1') });
      process.on('SIGUSR2', () => { console.log('sigusr2') });
```

Is there a way to catch the process being killed and clean up database connections then?

---

Another idea could be to track the `id` of the connection and kill it in the `setup`.

---

I think the solution is to kill all connections to the database at the start of every test, and because there is a database for each worker this allows concurrency.

```sql
SELECT pg_terminate_backend(pg_stat_activity.pid)
    FROM pg_stat_activity
    WHERE datname = current_database()
      AND pid <> pg_backend_pid();
```

**Comment by ArtemGovorov** [comment]
> Is there a way to catch the process being killed and clean up database connections then?

The thing is that without `recycle: true` the process is not killed (unless it hangs).

> Another idea could be to track the id of the connection and kill it in the setup.
> I think the solution is to kill all connections to the database at the start of every test,

Yes, cleaning in the `setup` function is what [we recommend](https://github.com/wallabyjs/public/issues/781#issuecomment-246082827). Setting the state required for your tests to run is best done here.

While we also expose the [teardown function](https://wallabyjs.com/docs/config/bootstrap.html#teardown-function), it suffers the same issue as `after/afterEach`, Wallaby (or any other test runner for that matter) can't guarantee that it'll always be called. The tool will do its best to call it, but there are always cases when it is not possible, when node process hangs. It may happen as a result of a testing framework crashing, async test callback no being invoked, introducing an infinite loop while typing (it's easy because wallaby runs tests frequently), etc.

**Comment by vjpr** [comment]
> The tool will do its best to call it, but there are always cases when it is not possible, when node process hangs.

That's why I was wondering about the process on exit hooks. To handle this case. Is it possible? How are they killed?

**Comment by ArtemGovorov** [comment]
When node process hangs (for example because of an infinite loop in it), no more JavaScript code will be executed in that process. So callbacks

```javascript
process.on('exit', () => {
        console.log('PROCESS EXITING!')
      })
```
will never be invoked.

You may try running this code:

```javascript
process.on('exit', () => {
  console.log('PROCESS EXITING!')
})

while(1){}

```

No matter how you kill the process, you'll never see the `PROCESS EXITING!` being logged.

So when node process hangs, we kill it from a master wallaby process (that spawns and monitors them). Exposing a callback (that'd be executed in the master process) is not desirable, because we need to keep it isolated from your test code/app, and you'd most likely want to load some app specific stuff, like a node module to connect a database, and other stuff that may potentially interfere with/break/load too much into/ the main process.

You may do everything you'd do in that callback, in the `setup` function. If you'd only like to execute some code after process had been recycled (and not after every test run), the you may do this:

```javascript
 module.exports = function () {
   return {
     ...

     setup: function (wallaby) {
       if(!global._clean) {
         // ... some code to execute if the worker process has just been created/recycled
         global._clean = true;
       }
     }
   };
 };
```

**Comment by vjpr** [comment]
Interesting, so when there is an infinite loop its impossible to break out of it without killing the process as you say. I just tried `SIGINIT` as well. No escape.

```
   console.log('started')

   process.on('SIGINT', () => { console.log('sigint') });

   while (1) {}
```

```
$ node test.js
started
^C^C^C^C^C^C^C^C^D
```

So I guess the lesson is that for all test cleanup like `test.after` and `wallaby.teardown` it should be assumed that they do not always run. I guess this has not been a problem so far because we have only had sequential test runners, so that all `after` stages ran until there was a loop.

Wallaby seems like a special case though.

While poking around I found this module: https://github.com/tjanczuk/tripwire. Their approach is to set a timeout for the event loop being blocked, then run a handler. This seems like it would be good for wallaby.

**Comment by vjpr** [comment]
>  Exposing a callback...may potentially interfere with/break/load too much into/ the main process.

What about executing the cleanup as another process (not in the main process)? Like the setup/teardown callbacks?

So that the cleanup methods would not be changing as the user edits their code.

Thinking practically, in my use case, I would have a `cleanup` function that would connect to the database, and clear all connections associated with the process's pid, and drop the database for that workerId.

**Comment by ArtemGovorov** [comment]
> So I guess the lesson is that for all test cleanup like test.after and wallaby.teardown it should be assumed that they do not always run. 

Correct, but not only for Wallaby, for any runner actually.

> I guess this has not been a problem so far because we have only had sequential test runners, so that all after stages ran until there was a loop, and that when a change is made, the entire test runner process restarts.
> Wallaby seems like a special case though.

The same thing can happen in AVA, Jest. Even in plain mocha if you create an infinite loop in your test, `after/afterEach` code will never run. With other runners it is even possible to kill the process in a middle in a way that `after/afterEach` will never run. It's just that wallaby runs your tests more frequently than other runners, so the chance of getting the case like this is higher.

There's a reason we recommend using `setup` function. Generally, in any test runner, `after/afterEach` is **not guaranteed to run after test(s)**. There are a few things that can prevent it from happening (process hanging/crashing/killing by user are frequent reasons). However, `before/beforeEach/wallaby setup function` **are guaranteed to run before tests**. So if your tests need to clear previous connections/clean DB/prepare DB/etc the best place to do it regardless of your test runner is `before/beforeEach/wallaby setup function`.

> How do you detect this btw?

Similar to the lib you've mentioned - by timeout. We monitor/ping worker processes from the master process, if a process is not responsive, we restart the worker.

> What about executing the cleanup as another process (not in the main process)? Like the setup/teardown callbacks?
> So that the cleanup methods would not be changing as the user edits their code.
> Thinking practically, in my use case, I would have a cleanup function that would connect to the database, and clear all connections associated with the process's pid, and drop the database for that workerId.

This could work, but it'd be the same as doing cleanup right in the `setup` function. Ie. right now you can `connect to the database, and clear all connections associated with the process's pid, and drop the database for that workerId` right in your `setup` function.

**Comment by vjpr** [comment]
> So right now you can connect to the database, and clear all connections associated with the process's pid, and drop the database for that workerId right in your setup function.

I am doing this now.

---

One more thing that is not possible without a process killed hook:

Say you create a database per `wallaby.sessionId` - there is no way to cleanup this database because you can never know the sessionId of a terminated worker unless you store it on disk somewhere.

Same goes to anything else relying on the `sessionId`.

**Comment by ArtemGovorov** [comment]
> Say you create a database per `wallaby.sessionId`

We wouldn't recommend relying on `wallaby.sessionId` for this (or anything persistent), `wallaby.workerId` suits the purpose much better.

> 2. Cleanup up system resources (dbs, db connections, tmp output, etc.) that do not affect other test runs, which cannot be done in `setup`.

If required, the global cleanup can be done on the master process exit (when wallaby stops).

```javascript
module.exports = function (wallaby) {

  process.on('exit', () => {
    console.log('PROCESS EXITING!')
    // do the cleanup
  });

  return {
    ...
  };
};
```

But again, for the same reasons as for a test worker cleanup/setup, if possible, I'd rather do the global cleanup on Wallaby start, rather than on stop/exit.
