### ISSUE TITLE
Preprocessed test files are not executed

### ISSUE THREAD

**Issue by m7r** [wallabyjs/public#1426]
### Issue description or question

I want to run tests from of https://github.com/PrismJS/prism.
I have a preprocessor that changes the file name and returns a javascript string.

In home ~/.vscode/extentions/WallabyJs.wallaby-vscode-1.0.68/projects/*/instrumented
the modified file is saved but the tests are not recognised.

If I put the js file into the test directory the test runs fine.
Any idea what to too?

File example:
boolean_feature.test
```
true
false

----------------------------------------------------

[
	["boolean", "true"],
	["boolean", "false"]
]

----------------------------------------------------

Checks for booleans.
```
-> boolean_feature.test.js
```js
import { tokenize, grammarFor } from '../../../src/core/prism.js'
import { simplify } from '../../token-stream-transformer.js'
describe('language-json', () => {
  it('checks for booleans', () => {
    const res = tokenize("true\r\nfalse", grammarFor('json'))
    expect(simplify(res)).toEqual([
	["boolean", "true"],
	["boolean", "false"]
])
  })
})
```

### Wallaby.js configuration file

```javascript
const test = require('./test/preprocessor')

module.exports = (wallaby) => {
  wallaby.defaults.files.load = false
  return {
    files: [
      'src/**/*.js',
      {pattern: 'test/token-stream-transformer.js', instrument: false}
    ],
    tests: [
      {pattern: 'test/lang/json/*.test', instrument: false, load: true}
    ],
    testFramework: 'jasmine',
    env: {
      type: 'browser',
      kind: 'chrome',
      report404AsError: true
    },
    debug: true,
    preprocessors: {
      '**/*.test': test
    }
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Wallaby can only run JavaScript tests (that are originally in JavaScript, or other supported languages as TypeScript or CoffeeScript).

In your case your original files are not JavaScript (or TypeScript/CoffeeScript), so despite that you convert them to JavaScript via a preprocessor, Wallaby is unable to instrument them, unless you [create your own compiler for the language that you're using](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler).

So you either need to list generated JavaScript files, eg. `boolean_feature.test.js`, in your `tests` list and then Wallaby will be able to instrument/run/show coverage in them, or you need to create a custom compiler for your `.test` files (and use it instead of a preprocessor), so that Wallaby will run them and show indicators for them as well if you need.
