### ISSUE TITLE
0% Coverage, Typescript

### ISSUE THREAD

**Issue by shavyg2** [wallabyjs/public#1435]
### Issue description or question

I get no output using wallaby.js.
is there something I am doing particularly wrong.

![image](https://user-images.githubusercontent.com/1460084/33994404-5df29494-e0a8-11e7-9d2e-b1eda7ab837a.png)

![image](https://user-images.githubusercontent.com/1460084/33994449-866b933a-e0a8-11e7-81fc-4e5baa92d207.png)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby){
    return {
        files:["src/*.ts"],
        tests:["src/*.spec.ts"],
        testFramework:"mocha",
        debug:true,
        env:{
            type:"node"
        }

    }
}
```

### tsconfig.json
```javascript
{
    "compilerOptions": {
        "target": "es5",
        "sourceMap": true,
        "lib": [
            "es2015",
            "es2015.promise"
        ]
    }
}
```

### Test File
```typescript
// src/test.spec.ts


import {expect} from "chai";

describe("Add",()=>{


    function add(x,y){
        return x+y;
    }


    it("should add",()=>{
        expect(add(1,2)).to.eql(2);        
    })
})
```

### Code editor or IDE name and version

Visual Studio Code v1.18.1

### OS name and version
Windows 10

**Comment by ArtemGovorov** [comment]
Your tests are marked with [grey indicators](https://wallabyjs.com/docs/intro/get-started-vscode.html#coverage-indicators), it means that they didn't run/execute (as you can also see Wallaby App shows `0 tests`).

If you open [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) output channel, you should see some errors:

```
​​[Error] File/pattern src/test.spec.ts is specified in the files list but also found in the tests list: src/*.spec.ts.
​​
​​[Error] 	If it's a test, make sure to exclude it from the files list, for example by adding { pattern: 'src/*.spec.ts', ignore: true } to the files list.
​​
​​[Error] 	If it's not a test, remove it from the tests list.​​
​​[Error] No files with tests found, check your tests list patterns.​​
```

The error is pretty descriptive, and if you do what is says and modify your config: 

```javascript
module.exports = function(wallaby){
    return {
        files:["src/*.ts", { pattern: 'src/*.spec.ts', ignore: true }], //<--
        tests:["src/*.spec.ts"],
        testFramework:"mocha",
        debug:true,
        env:{
            type:"node"
        }

    }
}
```

After that, your test will start executing as expected. 

Note that the code coverage will still be 0%, because code coverage metric calculation doesn't include your test files, only source files. Once you move the `add` function to a separate source file, then the coverage for the file will be calculated.

**Comment by shavyg2** [comment]
hey thanks, issue solved!!! love it!!

By the way i was looking at the issues and i see that your response is normally the same day. That is awesome stuff!! great support!!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
