### ISSUE TITLE
Feature Request: Use decorators to allow overwriting snapshots in Jest 

### ISSUE THREAD

**Issue by orta** [wallabyjs/public#1437]
### Issue description or question

Right now a failing snapshot test looks like:

![screen shot 2017-12-15 at 12 39 49 pm](https://user-images.githubusercontent.com/49038/34053509-1876acaa-e195-11e7-9724-ed606b63daaa.png)

Which is awesome. I'd love for wallaby to special case these failures and use decorators to add the links for "side-by-side diff", and ideally "replace snapshot" above the `expect` line.

( by decorators I mean these:

![screen shot 2017-12-15 at 12 38 59 pm](https://user-images.githubusercontent.com/49038/34053568-462ba934-e195-11e7-80fd-35f17b3f65db.png)
)

### Code editor or IDE name and version

Visual Studio Code v1.19

### OS name and version

OS X

**Comment by ArtemGovorov** [comment]
Thanks for the feature request! 

We've been experimenting with code lens some time ago and found them a bit distracting. When they permanently (or just for a long time) stay over some code block (like the `Debug` above the test definition in your example) they are great. However, for more transient things (like a test error related links), when they appear/disappear frequently and reserve/release back the vertical space they need to render, we found it to be a bit distracting. I wish there was an option to render them on the right hand side (like the error decoration), so that there's no vertical space flickering.

Anyway, we'll try to experiment a bit more to see if anything changed since the last time we tried code lens.

Also, as I'm sure you know, you can already run the `Show side-by-side diff` command or replace a snapshot with a single click and/or a keyboard shortcut. For example, you can run the `Show side-by-side diff` command from the hover:

![vsc_snapshot 1](https://user-images.githubusercontent.com/979966/34065751-efc65c94-e250-11e7-8f0d-188b3b1491b8.gif)
 
or from the command palette (or by using the `Cmd + Shift + R, D` shortcut), as well as the command to [update an individual snapshot](https://medium.com/@artem.govorov/jest-snapshot-testing-on-steroids-with-wallaby-js-a53008f619f0):

![1_zsfmuemxv6yl4e-a8lndaw](https://user-images.githubusercontent.com/979966/34065775-490672b2-e251-11e7-80d5-954b45345122.gif)

with the `Run line test` command for a test (or similar command for a test file and the whole project).

**Comment by ArtemGovorov** [comment]
After a bit more experimenting, we have decided not to use decorators (for [the reasons described here](https://github.com/wallabyjs/public/issues/1437#issuecomment-352149440)) and implement the requested feature a bit differently. 

So now you can use hovers or wallaby output to update snapshots. We have also added snapshot specific context commands to update test/file/project snapshots.

![sn](https://user-images.githubusercontent.com/979966/35262812-f478a0f6-0061-11e8-83be-60a787fcb123.gif)
