### ISSUE TITLE
Support Ava snapshots in Wallaby commands

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1440]
```js
import test from 'ava'

test('foo', async t => {
  t.snapshot(actual)
})
```

If I `run line tests` or `run file tests` from the intention the errors become fixed in the UI, but the snap files are not updated.

My `.snap` files are stored in `test/snapshots`. I use a monorepo too. Is this feature only working with Jest?

**Comment by ArtemGovorov** [comment]
> Is this feature only working with Jest?

Yes, we only support Jest snapshots in Wallaby commands (like `Run ...` and `Show diff ...`). Ava snapshots is a bit different beast.

Also merging this issue here https://github.com/wallabyjs/public/issues/1439

**Comment by ArtemGovorov** [comment]
`Run line tests`/`Run file tests` support for Ava snapshots has landed in the latest core 1.0.530 (and IntelliJ plugin v1.0.103).

`Show diff ...` support requires some changes in Ava, because it doesn't pass raw expected and actual values required to view the diff. Similar to our pull request https://github.com/avajs/ava/pull/1432, snapshot [assertion failure](https://github.com/ArtemGovorov/ava/blob/854203a728c4dff3ea61a3bcf49f1dfae04c7657/lib/assert.js#L304) also needs to pass the `raw.expected/actual` properties (if wallaby gets them, it can display the side-by-side diff). However, `result.actual/expected` seems to be some serialised values, and I'm not sure where/if Ava stores the `actual` value for the snapshot in memory. You're welcome to have a look.

**Comment by vjpr** [comment]
@ArtemGovorov Bug. When you have multiple snapshot tests in a file, when your run `Run line tests` on one of them, it appears to remove the other snapshots.

**Comment by ArtemGovorov** [comment]
> Feels like its just constraint from Ava.

It is indeed.

For example, if you have a test file `index.spec.js` looking like

```javascript
import test from 'ava';

test('abc', t => {
  t.snapshot({a: '1'});
});

test('xyz', t => {
  t.snapshot({a: '2'});
});
```

and the first snapshot is failing, then if you only run this test with Ava CLI with `update-snapshots` flag (equivalent of what wallaby is doing):

```
ava index.spec.js -u -m abc
```

then Ava will remove other snapshots from the corresponding snapshot file.

So looks Ava at the moment can't run a single test with snapshots update without removing other snapshots. With this Ava limitation you may either use `Run file test(s)` (but it'll update all snapshots in the file), or keep using `Run line test(s)` for individual snapshots, and once everything is passing, run `Run file test(s)` command once to restore all other snapshots in the snapshot file.

Hope it makes sense.

**Comment by vjpr** [comment]
@ArtemGovorov This feature is no longer working for me.

I was getting `Could not compare snapshot`, then I deleted the snapshots, and now it just shows passing.

**Comment by ArtemGovorov** [comment]
@vjpr Thanks for the report. The latest Ava version support has been added to [Wallaby Core 1.0.632](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by foxbunny** [comment]
> The latest Ava version support has been added

Does this include ava snapshots or just running tests? I don't get "Update snapshot" and "Side-by-side diff" functionality still.

**Comment by ArtemGovorov** [comment]
@foxbunny "Update snapshot" and "Side-by-side diff" functionality is not supported for Ava.

**Comment by foxbunny** [comment]
@ArtemGovorov Is it because of Ava's restrictions?

**Comment by ArtemGovorov** [comment]
@foxbunny More like a lack of exposed `actual`/`expected` properties in snapshot errors. `Show diff ...` support requires some changes in Ava, because Ava doesn't pass raw expected and actual values required to view the diff (Jest does do it for example). Similar to our pull request https://github.com/avajs/ava/pull/1432, snapshot [assertion failure](https://github.com/ArtemGovorov/ava/blob/854203a728c4dff3ea61a3bcf49f1dfae04c7657/lib/assert.js#L304) also needs to pass the `raw.expected/actual` properties (if wallaby gets them, it can display the side-by-side diff). However, `result.actual/expected` seems to be some serialised values, and we are not sure where/if Ava stores the `actual` value for the snapshot in memory.

**Comment by foxbunny** [comment]
Understood, thanks for clarifying.
