### ISSUE TITLE
Wallaby is rerunning all tests that have to do with code in a particular file

### ISSUE THREAD

**Issue by Guardiannw** [wallabyjs/public#1444]
### Issue description or question
It appears that wallaby is re-running all tests that have to do with the file that I changed in Node.  I thought that wallaby only re-ran the tests that actually dealt with the code that I am editing.

### Wallaby.js configuration file

```javascript
module.exports = function () {
    return {
        files: [
            '**/*.js',
            {pattern: '.env.test', instrument: false},
            '!**/*.spec.js',
            '!node_modules/**/*'
        ],

        tests: [
            '**/*.spec.js',
            '!node_modules/**/*'
        ],

        env: {
            type: 'node',
            runner: 'node'
        },
        testFramework: 'jest',
        workers: {
            initial: 1,
            regular: 1
        }
    };
};
```

### Code editor or IDE name and version

WebStorm 2017.3.1
Build #WS-173.3942.31, built on December 11, 2017
JRE: 1.8.0_152-release-1024-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.2

### OS name and version
OSX 10.13.2

**Comment by ArtemGovorov** [comment]
> wallaby is re-running all tests that have to do with the file that I changed in Node

By default in node Wallaby is re-running all tests that can break as a result of a file change.

> wallaby only re-ran the tests that actually dealt with the code that I am editing

For test files - yes (ie. if you are editing a particular test in a test file, only that test is will re-run). But for source files it is more complex. If you are importing/requiring a source file into your test file, then any changes in the file can potentially break the test run (even if your tests are not using anything from the loaded modules, but only loading it).

For example, if a test file imports a module:

```javascript
import a from './aModule'

it('test', () => {
  ...
});
```
then wallaby may need to re-run the test when `aModule` file changes, even if the imported a object (or anything from the module, or other modules imported by `aModule`) is not used in the test file at all. Wallaby works this way because imported modules may contains some logic executed on import (like some program scope logic, importing other modules, etc.) that may potentially break and make the importing test file fail, even though it is not directly testing anything from the module.

If you'd like to change the default mode, and ignore loading phase collected dependencies between files, you [may use the `ignoreFileLoadingDependencyTracking` setting](https://wallabyjs.com/docs/config/overview.html#ignoring-file-loading-chains-for-files-dependency-tracking-purposes). 

Hope it makes sense and addresses your question.
