### ISSUE TITLE
`node_modules` resolution issue

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1446]
### Issue description or question

This is more of an edge case, I have the following:

```sh
- fixtures
  - x
    - foo.js
- node_modules
- package.json
```

where `fixtures` contains test artifacts and `foo.js` has `require('make-error')` in it.

I'm writing test in `ava` and TypeScript and from CLI it works fine (i.e. when loading `foo.js`, it was able to look up and resolves `make-error` at `<root>/node_modules/make-error/package.json`.

When running wallaby, it fails with:
```sh
[Error] Runtime error: Error: ENOENT: no such file or directory, open './node_modules/make-error/package.json'​​
```

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    "files": [
      "tsconfig.*",
      "fixtures/**/*.js",
      "fixtures/**/*.json",
      "fixtures/**/*.ts",
      "src/**/*.ts",
      "!src/**/*.spec.ts"
    ],
    "tests": [
      "src/**/*.spec.ts"
    ],
    "env": {
      "type": "node"
    },
    compilers: {
      'src/**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
    },
    testFramework: 'ava'
  }
}
```

### Code editor or IDE name and version

Visual Studio Code v1.19.1

### OS name and version

OSX: 10.12.6

**Comment by ArtemGovorov** [comment]
Interesting, looks like the node module (or something else) is trying to resolve package.json using the working dir, and not a relative path (otherwise it should work).

Try adding the module path to your 'files' list:

"files": [
  { pattern: 'node_modules/make-error/**', instrument: false },
  ...
]

**Comment by unional** [comment]
Yes, that does move pass those errors.
Note that for this project, I need to do the same for the packages used during the transpilation, i.e. `typescript` and `plugin-typescript` etc.

Here is the final `wallaby.js` that works:

```js
module.exports = function (wallaby) {
  return {
    "files": [
      { pattern: 'tsconfig.*', instrument: false },
      { pattern: 'fixtures/**', instrument: false },
      "src/**/*.ts",
      "!src/**/*.spec.ts",
      { pattern: 'node_modules/make-error/**', instrument: false },
      { pattern: 'node_modules/global-store/**', instrument: false },
      { pattern: 'node_modules/systemjs-plugin-domture/**', instrument: false },
      { pattern: 'node_modules/aurelia-logging/**', instrument: false },
      { pattern: 'node_modules/@unional/logging/**', instrument: false },
      { pattern: 'node_modules/typescript/**', instrument: false },
      { pattern: 'node_modules/plugin-typescript/**', instrument: false }
    ],
    "tests": [
      "src/**/*.spec.ts"
    ],
    "env": {
      "type": "node"
    },
    compilers: {
      'src/**/*.ts': wallaby.compilers.typeScript({ module: 'commonjs' }),
    },
    testFramework: 'ava'
  }
}
```

You can check it out at https://github.com/unional/domture if it can help to discover the root cause.

In this project, it was `systemjs` and `webpack` trying to resolve these files/packages. That probably aligns with what you suspected.

**Comment by ArtemGovorov** [comment]
Thanks, I have checked out the project and it looks like adding used node modules is required in this case. This is because wallaby is running tests from its file cache (where all the files are properly instrumented), and webpack/systemjs are trying to resolve things relatively to this root cache folder, so (unless you specify a different root for modules for webpack and system.js in your code), adding used node modules is required in your case.
