### ISSUE TITLE
A interesting case for test failing in Wallaby but pass in CLI

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1450]
It is an edge case and likely Wallaby can't do anything about it.

I'm creating this issue so that you can aware this scenario exists.

The following test faile on Wallaby but pass in CLI:
```ts
test('failing predicate', t => {
  const actual = new Satisfier({ a: function () { return false } }).exec({ a: 1 })!
  t.is(actual.length, 1)
  assertExec(t, actual[0], ['a'], function () { return false; }, 1)
})
```
https://github.com/unional/satisfier/blob/21c8de7a89d83d2f8acf7fbd4ccb2979dbfea991/src/Satisfier.exec.spec.ts#L86-L90

The error is:
```sh
failing predicate​​​​ ​​​[1 ms]​​​​
    ​​
    ​Show side-by-side diff​
    
    function () { $_$wf(5); return $_$w(5, ‍85‍‌⁠82‌⁠), false; }
    ​​​​
    ​​- 'function () { $_$wf(5); return $_$w(5, 82), false; }'​​
    ​​+ 'function () { $_$wf(5); return $_$w(5, 85), false; }'​​
      at Object.assertExec ​src/testUtil.ts:13:4​
      at Test.fn ​src/Satisfier.exec.spec.ts:89:48​
```

The cause of the issue is that I'm using `Object.toString()` to get the representation of a function and compare them (this is roughly what `tersify` does to a function: https://github.com/unional/satisfier/blob/b6316ac92b60b293418c5ee07fd1925f8fa99def/src/testUtil.ts#L13).
Since Wallaby seems to run through some pipeline to bundle the file, two function instances are compiled to two different representations.

On CLI, since no such bundling is done, the test passes.

**Comment by ArtemGovorov** [comment]
It is indeed an interesting case. 

The issue here is that Wallaby runs tests with coverage collected, so it needs to insert different instrumentation instructions into those 2 different functions. Having said that, the issue is no wallaby specific, but code coverage specific (ie. if you run ava CLI with code coverage, you'd get a similar issue).

There are a couple of ways to make it work.

One solution is to [let wallaby know to stop instrumenting](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) your test functions:

```javascript
module.exports = function (wallaby) {

  return {
    ...
    hints: {
      allowIgnoringCoverageInTests: true,
      ignoreCoverage: /ignore coverage/ // or /istanbul ignore next/, or any RegExp
    },
  };
};
```

Then in your test you may ignore certain code blocks for code instrumentation purposes:
```javascript
test('failing predicate', t => {
  const actual = new Satisfier({ a: /*ignore coverage*/function () { return false } }).exec({ a: 1 })!
  t.is(actual.length, 1)
  assertExec(t, actual[0], ['a'], /*ignore coverage*/function () { return false; }, 1)
})
```

Note that you'll need to update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) as we have only recently introduce the `allowIgnoringCoverageInTests` (for a few reasons by default coverage hints are disabled in test files). 

Another solution is to construct the functions being compared in the test like this (so instrumentation won't reach them):

```javascript
test('failing predicate', t => {
  const actual = new Satisfier({ a: new Function('return function () { return false }')() }).exec({ a: 1 })!
  t.is(actual.length, 1)
  assertExec(t, actual[0], ['a'], new Function('return function () { return false }')(), 1)
})
```

Hope it makes sense.

**Comment by unional** [comment]
Thank you for your great work. 🌷
