### ISSUE TITLE
100% CPU usage while "idle"

### ISSUE THREAD

**Issue by zyklus** [wallabyjs/public#1454]
### Issue description or question

I start wallaby and it jumps to 100% and stays there "forever" (at least 3 hours).

From `ps aux`:

```sh
mark             48554 137.2  0.1  3218280  15880   ??  R     1:08PM  28:19.34 node --harmony /Users/mark/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/wallaby/server.js extended-core-ws --projectCachePath=/Users/mark/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.70/projects/7c507b3a478eb05b --configPath=/Users/mark/VoiceNGO/wallaby.js --lkp=/Users/mark/.vscode/extensions/.wlck --client=VSCode --phantomjs=/Users/mark/.vscode/phantomjs_v2.1.1/phantomjs --port=65097
```

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ['**/*.js', '**/package.json', '!**/seams/**/*', '!**/flow-typed/**/*', '!**/node_modules/**/*.js'],
    tests: ['**/test/*.test.js', '!**/node_modules/**/*.js'],
    debug: true,
    env: { type: 'node', runner: 'node' },
    compilers: { '**/*.js': wallaby.compilers.babel({}) },
    testFramework: 'jest',
  };
};
```

### Code editor or IDE name and version

VS Code v1.19.1

### OS name and version

OSX 10.12.6

**Comment by ArtemGovorov** [comment]
Does this sample work for you: https://github.com/wallabyjs/wallaby-jest-sample?

If yes, then I suspect that the issue is watching/traversing the `**/*.js` pattern (with a combination of not enough exclusions). Try removing all patterns that start with `**` from your config, and replacing them with less greedy ones like `src/**/*.js`.

**Comment by ckreutz** [comment]
I have the same issue. Are you sure @ArtemGovorov to replace in the compiler with src/**/*.js? 
  compilers: {
      'src/**/*.js': wallaby.compilers.babel(),
      'src/**/*.vue': require('wallaby-vue-compiler')(wallaby.compilers.babel({}))
    }
Because I get then in all tests this error:
describe('ListItems.vue', () => { SyntaxError: Unexpected token ')'

**Comment by ArtemGovorov** [comment]
> Because I get then in all tests this error:

Makes sense, because your test files are under `test/**/*.spec.js`, not in the `src` folder.

Compilers only match files previously matched by `files` or `tests` patterns, so it is ok for a compiler to specify `**/*.js` or `**/*.vue` pattern. For files/tests however you need patterns like [this](https://github.com/ChangJoo-Park/vue-wallaby-webpack-template/blob/master/wallaby.js#L16) and [this](https://github.com/ChangJoo-Park/vue-wallaby-webpack-template/blob/master/wallaby.js#L24).

If you are observing the same issue with `src` and `test` prefixed patterns in your `files` and `tests` lists, then please 

- share the full output from the [Wallaby Console output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) before it hangs,
- create a sample repo with you config files (wallaby, package.json, etc), where we could reproduce the issue. Hopefully, you can delete all of your source files and test files and still be able to reproduce the issue, so it'd possible to share the sample repo.

**Comment by vjpr** [comment]
@ArtemGovorov I've started seeing this recently too.

![screen shot 2018-03-11 at 4 12 09 pm](https://user-images.githubusercontent.com/281413/37255060-21cada88-2547-11e8-894e-abed42c301f2.png)

There are 3 node processes belonging to Wallaby that even persist after I exit IntelliJ.

**Comment by ArtemGovorov** [comment]
> When your force exit IntelliJ and Wallaby is still compiling/processing, the processes do not die...and I think I saw them restart when you try to kill one of them.

Are you sure those are wallaby processes? I know IntelliJ spins up one or two (I think one for TypeScript, and for something else) and re-creates them if you kill it (it monitors their existence).

**Comment by vjpr** [comment]
For the three processes from the screenshot, I checked the "Open files" and Wallaby was in there but nothing else notable.

**Comment by ArtemGovorov** [comment]
I'm puzzled then why this

> EDIT: So I fixed it by ignoring some build dirs (`.next` and `build`).

had helped and fixed the issue (because those folders do not seem to be related to wallaby at all, neither a webpack build if you're using Jest).

**Comment by vjpr** [comment]
Let me clarify. I changed the structure of my project recently and whenever I ran Wallaby I would see CPU 100% on all cores.

The issue was that I wasn't ignoring some files after the restructure - build output.

But, when I was dealing with this issue I had to kill IntelliJ because my whole Macbook was hanging. When I did this I noticed that there were processes left running.

**Comment by ArtemGovorov** [comment]
> These processes were compiling very large webpack bundles.

Are you using Jest?

**Comment by vjpr** [comment]
Nope. Ava.

**Comment by ArtemGovorov** [comment]
> These processes were compiling very large webpack bundles.
> Nope. Ava.

Then if those processes were indeed "compiling very large webpack bundles", those processes were not wallaby related, because Wallaby doesn't use webpack at all when running Ava tests (they run in node without any webpack processing).

**Comment by vjpr** [comment]
> "compiling very large webpack bundles"

I mean "Wallaby processing/instrumenting" the bundles.

When I looked in the Wallaby console before my PC hung, I could see it was processing these bundles - that should have been ignore and now are.

**Comment by ArtemGovorov** [comment]
Ah, got it, thanks! Will try to reproduce the issue locally.

**Comment by ArtemGovorov** [comment]
@vjpr Forgot to mention it, but the issue with hanging processes after unexpectedly quitting the IDE is now fixed in the latest version (one of the previously published versions actually).
