### ISSUE TITLE
VSCode -  Can not read the document under the property

### ISSUE THREAD

**Issue by ft1996** [wallabyjs/public#1459]
![jietu20180112-225400](https://user-images.githubusercontent.com/18325669/34880465-81653882-f7eb-11e7-9994-ddf212d6714f.jpg)

wallaby.js
```
module.exports = () => {
    return {
      files: [
        'style/*.css',
        'src/*.js',
        '*.html'
      ],
      tests: [
        'src/*.js'
      ],
      debug: true
    };
  };
```

Is not wrong configuration, I hope to attribute under the document category, can be done?

**Comment by ArtemGovorov** [comment]
With your configuration, Wallaby (just like Karma and other test runners) creates a sandbox HTML page with an empty body.

When you query for an element with the `wenben` id, it doesn't exist in the sandbox page, hence the error.

You need to create an element with the id first, [for example like it's done here](https://github.com/wallabyjs/public/blob/master/sample/jetbrains/test/calculatorJasmineSpec.js#L48), or just by using DOM API. At the end of your test run, you [may remove the element from the DOM](https://github.com/wallabyjs/public/blob/master/sample/jetbrains/test/calculatorJasmineSpec.js#L54), so that it doesn't interfere with other tests.

There are also many libraries that allow to import HTML fixtures in your tests, [for example this one](https://github.com/velesin/jasmine-jquery#html-fixtures).
