### ISSUE TITLE
console.log output repeat

### ISSUE THREAD

**Issue by ft1996** [wallabyjs/public#1498]
![qq20180206-152537](https://user-images.githubusercontent.com/18325669/35846529-00683d68-0b52-11e8-86f7-f6fb1b764e1e.png)

**Comment by ArtemGovorov** [comment]
It is possible and expected, if you call `restFun` multiple times, for example:

<img width="607" alt="screen shot 2018-02-06 at 5 31 36 pm" src="https://user-images.githubusercontent.com/979966/35846763-a2bc5b1a-0b63-11e8-8069-98cdfc7be49c.png">


If you are only calling the `restFun` once and still getting the repeated output, then please create a sample repo where we can reproduce the issue.

**Comment by ft1996** [comment]
https://gitee.com/hiday/html/blob/master/src/two.js    
The 219th lines under this file

**Comment by ArtemGovorov** [comment]
Thanks, the repeated output is expected in your case:

- the function and its call is located in the root scope of the file, meaning that it is called every time the file is loaded,
the `src/two.js` file is loaded by each [wallaby worker](https://wallabyjs.com/docs/config/workers.html), and because you have 2 test files (under your `tests` list pattern), it is loaded at least twice.

If you comment out move the `restFun(...[3,3,12,3,31,23])` call from the `src/two.js` to one of your tests, then it should display the output only once (because it'll be called only once).

Or you can set the [wallaby workers count](https://wallabyjs.com/docs/config/workers.html) to 1:
```javascript
module.exports = () => {
  return {
    ...
    workers: {initial: 1, regular: 1}
  };
};
```
and in this case the result will also be displayed once.

Hope it makes sense.

**Comment by ft1996** [comment]
I still have no effect after I amend the wallaby workers count to 1,But it's normal to write the code to the test. Thank you.
