### ISSUE TITLE
systemjs + webstorm issue.

### ISSUE THREAD

**Issue by WRidder** [wallabyjs/public#151]
I tried integrating wallabyjs in my existing project: [LeavyLip web-client](https://github.com/LeavyLip/webclient). I''m still setting up this project but came across wallabyjs and like to evaluate it with this project; if it all works fine you can count me as a new customer!

However, I encounter some errors and probably made a mistake in the configuration file: 
```
wallaby.js started
core v1.0.63
console.error: Potentially unhandled rejection [4] Error loading "app/app" at http://localhost:36541/app/app.js
Error loading "app/app" from "app/__tests__/app-spec" at http://localhost:36541/app/__tests__/app-spec.js
: http://localhost:36541/app/app.js (WARNING: non-Error used)
```

The files are configured in [wallaby.js config file](https://github.com/LeavyLip/webclient/blob/master/wallaby.js) like this:
```javascript
    files: [
      {pattern: "jspm_packages/system.js", instrument: false},
      {pattern: "config.js", instrument: false},

      {pattern: "app/**/!(*-spec).js", load: false}
    ],
    tests: [
      {pattern: "app/**/*spec.js", load: false}
    ],
```

Any clue what may be the issue here?

**Comment by ArtemGovorov** [comment]
I have sent you [the pull request](https://github.com/LeavyLip/webclient/pull/1) to make it work in your project. 

The issue was that wallaby.js at the moment doesn't support glob patterns like: `"app/**/!(*-spec).js"`, so I have broken down the pattern a bit. Wallaby core is using `minimatch`/`glob`, but there's also an implementation of it on the IDE side that unfortunately doesn't yet support patterns like this. [There's a plan](https://github.com/wallabyjs/public/issues/69) to improve it.

I have also included a couple of testing libraries that you're using to the `files` list and PhantomJs 1.x `Function.prototype.bind` shim required for React. If you'd like to use PhantomJs 2, that doesn't need the shim, you may do it [like described here](https://github.com/wallabyjs/public/blob/master/README.md#phantomjs-2), for example by installing (karma-phantomjs2-launcher)[https://www.npmjs.com/package/karma-phantomjs2-launcher], referencing the binary relative path from your `env.runner` setting.

**Comment by WRidder** [comment]
I can confirm this approach worked well; thanks for the great support!

**Comment by ArtemGovorov** [comment]
@WRidder Awesome, thanks!
