### ISSUE TITLE
Cannot find module error in tests when using headless Chrome

### ISSUE THREAD

**Issue by kubal5003** [wallabyjs/public#1514]
### Issue description or question

Wallaby was working fine for my project, but then something happened and we started getting errors like: 

```
Runtime error: Uncaught Error: Cannot find module '727'
Runtime error: Uncaught ReferenceError: exports is not defined
```

Most of the runs fail, but some are OK. I need to keep adding and removing a whitespace in the spec file I'm working on to make wallaby work! This is not the productivity improvement I was expecting while buying this product..  :(

### Wallaby.js configuration file

```var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

module.exports = function (wallaby) {
  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'test-config/spec-bundle-wallaby.js',
      'src/app/**/*spec.js'
    ],
    module: {
      loaders: [
        {
          test: /\.ts$/,
          include: /node_modules/,
          use: [
            {
              loader: 'awesome-typescript-loader',
              query: {
                sourceMap: false,
                inlineSourceMap: true,
                compilerOptions: {
                  removeComments: true
                }
              }
            },
            'angular2-template-loader'
          ]
        },
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.css$/, loaders: ['to-string-loader', 'css-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.html$/, loader: 'html-loader'},
        {test: /\.(png|svg)$/, loader: 'url-loader?limit=128000'}
      ]
    },
    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src')
      ]
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'test-config/matchers.ts', load: false, instrument: false},
      {pattern: 'test-config/spec-bundle-wallaby.js', load: false, instrument: false},
      {pattern: 'src/app/**/*.css', load: false},
      {pattern: 'src/app/**/*.scss', load: false},
      {pattern: 'src/app/**/*.html', load: false},
      {pattern: 'src/app/**/*.json', load: false},
      {pattern: 'src/app/**/*spec.ts', ignore: true},
      {pattern: 'src/app/**/*.d.ts', ignore: true},

    ],
    workers: {
      initial: 7,
      regular: 7
    },
    tests: [
      'src/app/**/*spec.ts'
    ],
    testFramework: 'jasmine',
    middleware: function (app, express) {
      var path = require('path');
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },
    env: {
      kind: 'chrome'
    },
    postprocessor: webpackPostprocessor,
    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version

WebStorm v2017.2.5

### OS name and version

OSX HighSierra 10.13.3

**Comment by ArtemGovorov** [comment]
> Wallaby was working fine for my project, but then something happened

This means that the issue is likely your project specific, I suspect some of the modules you have started to use lately may be causing it. Having said that, we are happy to help troubleshooting the issue and to help configure wallaby correctly for your case.

Ideally we'll need a sample project where we can reproduce the issue, but we understand that it may be hard to create. So let's try to isolate it first.

Please try this:
- set `emitModulePaths` webpack config property, and when the `Cannot find module ...` error shows up, it should now display the module name instead of a number. Please share the module name.
```diff
var webpackPostprocessor = wallabyWebpack({
  ...
+ emitModulePaths: true
})
```
- set [wallaby workers](https://wallabyjs.com/docs/config/workers.html) count to 1 (to make the issue causing spec finding easier)
```diff
module.exports = function (wallaby) {

  ...

  return {
    ...
+   workers: {initial: 1, regular: 1}
  };
};
```
- (if you don't know what spec file is causing the issue) edit the `tests` setting and comment out all specs
```javascript
tests: [
      // {pattern: 'src/**/*spec.ts', load: false}
    ],
```
- add one spec to the `tests` to see if the tests pass,
- keep adding spec files one by one, until you find the one causing the failure.

Once you find the spec that is causing the issue, check what modules are imported by it (and by modules that the spec imports). It's likely something that you started to use recently.

Also please do this:

- Share the `test-config/spec-bundle-wallaby.js` file and your `package.json`'s file `dependencies` and `devDependencies` sections.

- Edit your wallaby config to output more debugging info:
```diff
module.exports = function (wallaby) {

  ...

  return {
    ...
+   debug: true
  };
};
```
and when the error shows up, search the Wallaby Console output for `wallaby:project File cache`, open the folder, archive the `instrumented/____wallaby-bundle.js` file in there and send it to us to hello@wallabyjs.com.

**Comment by ArtemGovorov** [comment]
Could you also please 

- specify your version of Chrome browser,
- try switching to [Electron runner](https://wallabyjs.com/docs/integration/electron.html) (and removing the `workers: {initial: 1, regular: 1}` setting) to see if it helps.

**Comment by kubal5003** [comment]
Hi, sorry for late reply as I was travelling yesterday. First of all thank you for helping with tracing the problem.

I did add the `emitModulePaths` (nice! thank you!) and it seems that the module that breaks is the node_modules/@angular/core/esm5/testing.js which has all the basic infrastructure of Angular 5 testing utilities.

That means that if my tests are to blame this seems like a derived error and not the real source of the problem. The path to the file that is reported is correct and the file exists on disk. 

Chrome version installed: 64.0.3282.140 (I am guessing that wallaby is using whatever is installed? if not please tell me where to look )

Workers - set to 1, 1 as suggested. With excluding the tests and adding them gradually - I will try, however this might not be totally easy since we now have ~1200 tests in 228 spec files.

`test-config/spec-bundle-wallaby.js`

```
Error.stackTraceLimit = Infinity;

require('core-js/es6');
require('core-js/es7/reflect');

require('./matchers');

require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
require('zone.js/dist/proxy'); // since zone.js 0.6.15
require('zone.js/dist/sync-test');
require('zone.js/dist/jasmine-patch'); // put here since zone.js 0.6.14
require('zone.js/dist/async-test');
require('zone.js/dist/fake-async-test');

/**
 * RxJS
 */
require('rxjs/Rx');

var testing = require('@angular/core/testing');
var browser = require('@angular/platform-browser-dynamic/testing');

testing.TestBed.initTestEnvironment(
  browser.BrowserDynamicTestingModule,
  browser.platformBrowserDynamicTesting()
);

```

package.json dependencies: 
```
    "@angular/common": "^5.2.0",
    "@angular/core": "^5.2.0",
    "@angular/platform-browser": "^5.2.0",
    "@angular/platform-browser-dynamic": "^5.2.0",
    "@angular/router": "^5.2.0",
    "@ng-idle/core": "^2.0.0-beta.13",
    "@ngx-translate/core": "^9.1.0",
    "@ngx-translate/http-loader": "^2.0.1",
    "core-js": "^2.5.1",
    "dexie": "^2.0.1",
    "http-proxy-middleware": "^0.17.4",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "rxjs": "^5.5.6",
    "typescript-memoize": "0.0.4",
    "zone.js": "^0.8.20"
```
package.json dev dependencies:

```
 "@angular/compiler": "^5.2.0",
    "@angular/compiler-cli": "^5.2.0",
    "@ngtools/webpack": "^1.9.4",
    "@types/express": "^4.0.39",
    "@types/ip": "~0.0.29",
    "@types/jasmine": "^2.8.4",
    "@types/lodash": "^4.14.92",
    "@types/mongodb": "^3.0.1",
    "@types/node": "^9.3.0",
    "@types/selenium-webdriver": "^3.0.8",
    "angular-router-loader": "~0.8.2",
    "angular2-template-loader": "~0.6.2",
    "awesome-typescript-loader": "~3.4.1",
    "babel-polyfill": "^6.26.0",
    "codelyzer": "^4.0.2",
    "compression": "^1.7.1",
    "config": "^1.28.1",
    "copy-webpack-plugin": "^4.2.3",
    "css-loader": "~0.28.0",
    "es6-promise": "~4.1.0",
    "es6-promise-loader": "~1.0.2",
    "express": "^4.16.2",
    "express-handlebars": "latest",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.5",
    "html-loader": "^0.5.1",
    "html-webpack-plugin": "~2.30.1",
    "htmllint-cli": "0.0.6",
    "image-webpack-loader": "3.4.2",
    "imports-loader": "~0.7.1",
    "inquirer-directory": "^2.1.0",
    "ip": "~1.1.5",
    "istanbul-instrumenter-loader": "~3.0.0",
    "jasmine-spec-reporter": "^4.1.1",
    "js-sha256": "^0.7.1",
    "json-loader": "~0.5.4",
    "karma": "~2.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage": "~1.1.1",
    "karma-jasmine": "^1.1.1",
    "karma-junit-reporter": "^1.2.0",
    "karma-mocha-reporter": "^2.2.5",
    "karma-phantomjs-launcher": "~1.0.4",
    "karma-remap-coverage": "0.1.4",
    "karma-sourcemap-loader": "~0.3.7",
    "karma-webpack": "^2.0.9",
    "memory-cache": "^0.2.0",
    "mongodb": "^3.0.1",
    "node-sass": "^4.7.2",
    "npm-run-all": "^4.1.2",
    "plop": "^1.9.0",
    "protractor": "~5.2.0",
    "protractor-image-comparison": "^1.4.0",
    "raw-loader": "^0.5.1",
    "request-promise": "^4.2.2",
    "rimraf": "~2.6.1",
    "run-middleware": "^0.6.6",
    "sass-lint": "^1.12.1",
    "sass-loader": "^6.0.5",
    "source-map-loader": "^0.2.3",
    "string-replace-loader": "~1.3.0",
    "style-loader": "^0.19.0",
    "to-string-loader": "~1.1.5",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "tslint-loader": "~3.5.2",
    "typescript": "2.6.2",
    "wallaby-webpack": "^3.9.4",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.9.2",
    "webpack-dev-middleware": "^2.0.4",
    "webpack-dev-server": "^2.11.0",
    "webpack-hot-middleware": "^2.21.0",
    "webpack-md5-hash": "^0.0.6"
```

Recently we did not start using any new libraries (at least not that I'm aware of..) - last thing we did was I guess upgrade to Angular 5.2.0, but after that wallaby was working fine for a longer period as far as I recall.

**Comment by ArtemGovorov** [comment]
Thanks for providing the details!

- Does the error show up with the `workers: {initial: 1, regular: 1}` setting?
- Try switching to [Electron runner](https://wallabyjs.com/docs/integration/electron.html) (and removing the `workers: {initial: 1, regular: 1}` setting) to see if it helps.

**Comment by kubal5003** [comment]
I did trace the 'export is undefined problem' - the path that is shown is always referring to the currently modified spec file. I will continue to investigate (including Electron runner, send the bundle as requested etc.)

**Comment by aikrez** [comment]
I suddenly experienced the same problem with my Angular hybrid application:
 "angular": "1.6.9",
 "@angular/core": "5.2.5",
 "wallaby-webpack": "3.9.4",
"webpack": "3.11.0",
env: chrome

`Uncaught Error: Cannot find module '.\wallaby-bundle.js' (.\wallaby-bundle.js)
Uncaught Error: Cannot find module '272' (C:\Data\ari2\ari-ui-web-content\node_modules\@angular\core\esm5\testing.js)`

Setting workers: {initial: 1, regular: 1} does work for me when starting WallabyJS en writing code.

I noticed that when I get the error, and then change some code (comment), the error goes away.
When I restart WallabyJS, the errors are back

**Comment by ArtemGovorov** [comment]
It looks like there is an issue with the initial parallel run in Angular projects using headless Chrome as a runner.

I'm merging the following issues into this one (@Conrad777 and @jkyoutsey, please subscribe to this and post your further results here):
https://github.com/wallabyjs/public/issues/1507
https://github.com/wallabyjs/public/issues/1515

For those who are encountering the issue and for those who'll encounter it before we find out the reason, here are **2 confirmed workarounds**.

- you may set [wallaby workers](https://wallabyjs.com/docs/config/workers.html) count to 1 to disable parallel run:
```diff
module.exports = function (wallaby) {
  ...
  return {
    ...
+   workers: {initial: 1, regular: 1}
  };
};
```
- or you may switch to [Chrome via Electron runner](https://wallabyjs.com/docs/integration/electron.html).

While we haven't been able to reproduce locally the issue so far, from the reports it looks like the issue has something to do with the way headless Chrome runs in parallel. Presumably the issue was introduced in Chrome 64, that is why for most of you everything was working fine, the issue may have started to show up after your local Chrome update.

It also seems that there may be something else triggering the issue, because we have many users running wallaby with Chrome 64 without any problems.

We will investigate the data that we have further, however the progress depends on how fast we can get/create a project where we could reproduce the issue.

**If any of the affected users could share their project (perhaps privately), or could create an isolated smaller project where we could reproduce the issue, that would allow us to fix the issue very fast.**

**Comment by ArtemGovorov** [comment]
We have been able to reproduce the issue. It is an issue in headless Chrome, when running large (bundle) files. That is why we couldn't reproduce it before and that is why the issue only showed up for some user, the bundle size needs to be >=~7mb, and we were trying smaller projects.

To confirm that this is the case, you may clear `--headless` flag passed by Wallaby to Chrome by default:

```diff
    env: {
      kind: 'chrome',
+     params: { runner: ' '}
    },
```
and your tests should pass. However Chrome instance will be visible on your screen. Nevertheless, it is another workaround until the issue is fixed.

We'll be creating a small sample to submit to Chrome team, so that they could investigate the issue.

**Comment by ArtemGovorov** [comment]
Looks like we have found a flag in Chrome that can fix the issue in headless mode. 

@kubal5003 @Conrad777 @aikrez @jkyoutsey please try updating to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) v1.0.550, removing any workaround settings (if you have set any), and try running wallaby.

**Comment by aikrez** [comment]
I can confirm that there no more errors with v1.0.550 without workarround setting. Thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

**Comment by jkyoutsey** [comment]
I updated to latest core and still have the same issue.  With multiple workers I get this:
```
0 failing tests, 111 passing​​​​​
​​​​​​​​​​
​​Uncaught Error: Cannot find module './src/main/ui/wallabyTest.js' (./src/main/ui/wallabyTest.js)​​
​​at http://localhost:62281/wallaby-webpack.js?1518794237667:1​​
​​Uncaught Error: Cannot find module '295' (/Users/me/src/myapp/branches/me-70824-httpclient/node_modules/@angular/core/@angular/core/testing.es5.js)​​
​​at http://localhost:62281/wallaby-webpack.js?1518794237667:1​​
```

**Comment by ArtemGovorov** [comment]
@jkyoutsey Thanks for checking!

Could you please confirm if it the the headless Chrome issue by clearing the `--headless` flag passed by Wallaby to Chrome by default:

```diff
    env: {
      kind: 'chrome',
+     params: { runner: ' '}
    },
```

Please also try this set of flags:

```diff
    env: {
      kind: 'chrome',
+     params: { runner: '--headless --disable-gpu --deterministic-fetch --disk-cache-dir=/dev/null --disk-cache-size=1'}
    },
```

**Comment by jkyoutsey** [comment]
All tests DO run with
```
params: { runner: ' '}
```
All tests DO NOT run with
```
params: { runner: '--headless --disable-gpu --deterministic-fetch --disk-cache-dir=/dev/null --disk-cache-size=1'}
```

**Comment by konrad300** [comment]
Hello @ArtemGovorov,

Unfortunately, this issue still exists in Chrome Headless (also with params: { runner: '--headless ...') 
Have you got any chance to investigate this problem / check with Chrome team?

**Comment by ArtemGovorov** [comment]
@konrad300 Not yet, but the good news is that we think we have found a solution for the issue. It's already implemented and is planned to be published tomorrow. Will update the issue once the solution is released. In a meantime [any of these workarounds](https://github.com/wallabyjs/public/issues/1514#issuecomment-366115013) should help.

**Comment by ArtemGovorov** [comment]
We have implemented and published a fix that should eliminate the issue. Please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, and let us know how it goes. Note that [wallaby cache may need to be cleared](https://wallabyjs.com/docs/intro/troubleshooting.html#wallaby-was-working-but-then-stopped-working) after the update before the fix works for you.
