### ISSUE TITLE
Computer hangs with "Resource Temporarily Unavailable" when Wallaby is running

### ISSUE THREAD

**Issue by nickyhajal** [wallabyjs/public#1521]
### Issue description or question

Lately my computer has been occasionally doing lots of strange things (apps not working, browser tabs not loading, postgres can't connect).

If I try to open a new terminal tab, I get: 

```
[forkpty: Resource temporarily unavailable]
[Could not create a new process and open a pseudo-tty.]
```

I ultimately traced this back to Wallaby — if I stop Wallaby in VSCode, everything goes back to normal.

When I start Wallaby back up, it runs fine for awhile but within 20 minutes or so, I get that same issue.

Any help is very appreciated!

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'test';
module.exports = function(wallaby) {
  return {
    files: ['app/**/*.js', '.env.test', 'migrations/*.js'],

    tests: ['__tests__/**/*'],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    env: {
      type: 'node',
    },
    testFramework: 'jest',
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.20.1

### OS name and version

macOS 10.12.6

**Comment by ArtemGovorov** [comment]
I doubt the issue is wallaby specific, because we would get tons of similar reports from other users. 

I suspect the issue may be specific to what your tests are doing (or app under tests is doing). Maybe some resources are leaking.

There are a couple of ways to verify the assumption, please do the following:

- clone the repo https://github.com/wallabyjs/wallaby-jest-snapshots, run `npm i` and run wallaby on it for a few minutes. See if the issue shows up or not.
- in your real project, add the `workers: {restart: true}` setting to your wallaby config (see below), run it for a few minutes to see if it helps.

```diff
process.env.NODE_ENV = 'test';
module.exports = function(wallaby) {
  return {
    files: ['app/**/*.js', '.env.test', 'migrations/*.js'],

    tests: ['__tests__/**/*'],

    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },

    env: {
      type: 'node',
    },
    testFramework: 'jest',
+   workers: {restart: true}
  };
};
```

**Comment by nickyhajal** [comment]
Thanks for the quick response!

I think I figured this out - seems related to my code not closing postgres connections (and therefore building up too many processes as Wallaby kept rerunning).

Thanks again!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
