### ISSUE TITLE
Please consider an offline mode for wallabyjs.com/app

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [wallabyjs/public#1522]
### Issue description or question

http://localhost:51245/ is just an `<iframe>` around http://wallabyjs.com/app. That means it doesn't work in offline mode. Very inconvenient on airplanes!

**Comment by NikGovorov** [comment]
Hi @JoshuaKGoldberg,

Thanks for your feedback. Wallaby.js App supports offline mode, to install the app you need to open `http://localhost:51245` or `http://wallabyjs.com/app` once in your browser, after that even if you closed the browser and lost internet connection, the app should still work.

**Comment by JoshuaKGoldberg** [comment]
@NikGovorov if you initially open the tab while offline, does it still work?

**Comment by ArtemGovorov** [comment]
@JoshuaKGoldberg If you had opened the page at least once prior to that in past, then it will work (even if you closed your browser). Wallaby App is PWA now and opening the page is like "installing" Wallaby App (if it hasn't been installed, it won't work).

The only way to make it work without "installation" would be to ship Wallaby App with plugins/core, but we don't ship Wallaby App with plugins/core because they have different release cycles.

Hope it makes sense and answers your question.

**Comment by JoshuaKGoldberg** [comment]
That does, thanks you two!
