### ISSUE TITLE
Recompile fails when test files import from other test files

### ISSUE THREAD

**Issue by ian-craig** [wallabyjs/public#1523]
### Issue description or question
`TypeError: Cannot read property '0' of undefined​​` after editing a source file whose test file imports from another test file.

1. Start Wallaby and wait for compile & test
State: All tests passing and no errors
2. Edit a file covered by a test which imports from another test (e.g. `FooFactory.ts` in the below example)
State: `TypeError: Cannot read property '0' of undefined​​ at Object.<anonymous> .../FooFactory.test.ts`
3. Restart Wallaby
State: All tests passing again with no errors

It looks like this is related to the fact that the import is pulling from a file in the "tests" section of Wallaby's config rather than the "files" section.

Below is a contrived example of where this could be used. In essence we have a stub generator (`stubFooStore`) tightly coupled to a type, and as per DRY principle don't want to re-create this generator in other files which need exactly the same thing.

```ts
// Foo.ts
export class Foo {
    constructor (store: FooStore) {
        ...
    }
}

// FooFactory.ts
export const fooFactory = (store: FooStore) => {
    ...
    return new Foo(store);
};

// Foo.test.ts
export const stubFooStore = () => {
    // Create some compatible FooStore stub/spy
    return storeStub;
};

it("is an example test", () => {
    const store = stubFooStore();
    ...
});

// FooFactory.test.ts
import { stubFooStore } from "./Foo.test";

it("is an example test", () => {
    const store = stubFooStore();
    const foo = fooFactory(store);
    ...
});
```

Theoretically we could split `stubFooStore` into a separate file, but enforcing that would be more difficult and it seems like an unnecessary split. Jest is unaffected so our build & test runs do not pick up on the issue. 

Because this only happens _after_ an edit, it tooks us a while to track down what was causing this, so **if nothing else this should produce a meaningful error.**

### Wallaby.js configuration file

```javascript
module.exports = () => ({
	env: {
		type: "node",
	},
	files: [
		"package.json",
		"src/**/*.ts",
		"!src/**/*.test.ts",
		"src/**/*.tsx",
		"!src/**/*.test.tsx",
	],
	hints: {
		ignoreCoverage: /istanbul ignore next/,
	},
	testFramework: "jest",
	tests: [
		"src/**/*.test.ts",
		"src/**/*.test.tsx",
	],
});
```

### Code editor or IDE name and version

Visual Studio Code v1.20.0
Wallaby.js App v1.0.35, Core v1.0.551

### OS name and version

Windows 10 / Windows Server 2016

**Comment by ArtemGovorov** [comment]
Yes, this is a known behaviour of Wallaby. The files specified in the `tests` settings are entry points and are handled in a special way by Wallaby, so when an entry point gets imported by an entry point, then the tool gets confused.

> Theoretically we could split `stubFooStore` into a separate file, 

It is what we would recommend doing. It looks like it is a test helper, so the best place for it would be in its separate file. Placing it in one of your test files may not be a good idea for the reasons explained below.

> but enforcing that would be more difficult and it seems like an unnecessary split. 

If refactoring the test helper into a separate file is not desirable, then you can make wallaby work for this scenario by excluding the test file with helpers from the `tests` list, and including it into the `files` list. Something like:

```javascript
files: [
		"package.json",
		"src/**/*.ts?(x)",
		"!src/**/!(Foo.)test.ts?(x)",
	],
        ...
	tests: [
		"src/**/*.test.ts?(x)"
		"!src/**/Foo.test.ts?(x)"
	],
```

Essentially you are telling Wallaby that your `Foo.test.ts` file is a test helper (that happens to have tests that will run as well because another test file is importing them).

> it seems like an unnecessary split. Jest is unaffected so our build & test runs do not pick up on the issue.

There's at least one possible issue with your approach. Unless you are specifically excluding `Foo.test.ts` in your Jest test patterns (similar to the Wallaby config suggested above), then with Jest (without Wallaby) **all tests defined in your `Foo.test.ts` are running twice** - the first time when the `Foo.test.ts` file runs as a test file, and the second time when `FooFactory.test.ts` test file runs (and imports `Foo.test.ts` file). Even worse, if other test files are importing the `Foo.test.ts` to use the test helper, then all tests defined in your `Foo.test.ts` are running as many times as the file is imported. 

> if nothing else this should produce a meaningful error.

Totally agree, we will investigate how to detect the scenario and to display a meaningful error.
