### ISSUE TITLE
Comments are not preserved in instrumented code

### ISSUE THREAD

**Issue by Frizi** [wallabyjs/public#156]
I'm trying to write a wallaby preprocessor which relies on existance of comments in the source code. Unfortunately file.contents doesn't include these comments at all.

**Comment by ArtemGovorov** [comment]
Yep, it's a known limitation. With code instrumentation one can't rely on the original code structure because it is changed (including comments that are removed).

I'll have a look if I can preserve comments with the current instrumentation + code generation stack I'm using. 

Out of interest, could you please tell a bit more about your preprocessor and how does it use comments?

**Comment by Frizi** [comment]
I'm using [preprocess](https://github.com/jsoverson/preprocess), wchich is a simple regex based source text preprocessor. There are a few complex rules for specific comment blocks being transfered into code or generating arbitrary code, but all these are corner cases not essential to be instrumented.

Basic comment block/line preservation would be enough to enable simple `@if`-like clauses. That also means generating comment blocks originating from babel/coffeescript/typescirpt or whatever is natively supported.

**Comment by Frizi** [comment]
Alternatively, there could be a way to specify multiple compilers in pipeline-like format, similarly to how karma handles preprocessors. It can be done right now inside a compiler function to some degree, but then care must be explictly taken of merging source maps and fixing generated ranges. The drawback, this method requires explicit support for source maps, which AFAIK isn't strictly needed when processing files after instrumentation.

**Comment by ArtemGovorov** [comment]
@Frizi wallaby.js supports the pipeline of compilers (and preprocessors), you may specify an array of compilers (the same is true for preprocessors), like:
``` JavaScript
    compilers: {
      'src/**/*.js': [
          file => ({ code: '...', map: {}, ranges: []}),
          file => ({ code: '...', map: {}, ranges: []})
      ]
    }
```
`map` and to be a valid source map of the transformation and `ranges` should be set as [described here](http://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler). Wallaby.js in this case should merge source maps and ranges automatically.

**Comment by Frizi** [comment]
That looks promising, but in case of that specific plugin, is problematic. It doesn't emit source maps, at least in current version. It would work as expected as preprocessor though.

**Comment by ArtemGovorov** [comment]
Why would it work as a preprocessor? The transformation happens for some coverable code, so wallaby.js needs source maps either way to correctly map error stacks, etc.

**Comment by Frizi** [comment]
I guess it needs source maps either way. Can eventually be done. But then, it is not really generating any AST, so providing ranges is practically impossible and it cannot really work as a compiler.

**Comment by jwulf** [comment]
Hi Artem, I'm using [metascript](https://github.com/dcodeIO/MetaScript) and have the same problem - it relies on source code comments to work in preprocessing mode; and it doesn't produce source maps.

Could there be a switch to preserve comments during preprocessing, with the understanding that without source maps it won't report the correct line of unit test errors in the output?

**Comment by ArtemGovorov** [comment]
Hi Joshua,

> with the understanding that without source maps it won't report the correct line of unit test errors in the output?

Unfortunately without source maps in this particular case wallaby.js will be close to unusable, because much more than just test error lines will be broken: coverage indicators and inline messages will be rendered on wrong lines, wrong tests running as a result of code changes, and a few more possible issues.

**Comment by qraynaud** [comment]
I also needs the comments to be present in my files. Right now I have a function in JS that annotates functions arguments and can alter its result depending on the comments on the argument.

```js
annotate((test) => {}) // ['test']
annotate((/*!other*/test) => {}) // ['other']
```

This is a corner case of the function that is not recommended but all the related tests fail in wallaby which is sad to me since babel preserves the comment perfectly now.

**Comment by kesor** [comment]
Could this also cause Wallaby's Live Comments to not work in Babel preprocessed code?

**Comment by ArtemGovorov** [comment]
@kesor Unless you are specifically telling babel compiler not to emit comments, it should work because babel preserves comments. You may [clone this repo](https://github.com/wallabyjs/wallaby-babel-es7-sample/) (that is using babel), install deps, run tests and see the live comment working [on this line](https://github.com/wallabyjs/wallaby-babel-es7-sample/blob/master/test/userRepoSpec.js#L12) for example.

**Comment by qraynaud** [comment]
@ArtemGovorov: this issue has been open for nearly 3 years now. Can we hope for it to be fixed? I'm a customer and this keeps making me lose time which I believe is pretty sad!

**Comment by ArtemGovorov** [comment]
@qraynaud Unfortunately there's no close plan to implement the feature. We'll post some update here if the things change.

**Comment by smcenlly** [comment]
This is now available in the latest version of Wallaby.js, `Wallaby.js core v1.0.629`. Visit [our docs to read more about the preserveComments setting](https://wallabyjs.com/docs/config/overview.html#preserve-comments-setting).
