### ISSUE TITLE
Wallaby won't start

### ISSUE THREAD

**Issue by JRobber** [wallabyjs/public#1563]
### Issue description or question
It's been a while since I've used Wallaby and I can't get it to start.  
I get this error : `bad option: --harmony_arrow_functions` when trying to start it in the wallaby console.

I have tried :
* node version 9, and node version 8
* deleting wallaby core and forcing the re-install
* setting `env.params.runner` and `env.params.env` to an empty string as recommended in the troubleshooting section
* Uninstalling and re-install wallaby
* set environment variable `WALLABY_NODE=/usr/local/n/versions/node/9.8.0/bin`

I tested this against the calculator sample : `https://github.com/wallabyjs/calculator-sample.git`  This works for a co-worker, but not for me.

I've also tried your basic node config, your create-react-app config, all get the same error.

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX 10.12.5

**Comment by ArtemGovorov** [comment]
From the error message it looks like your license had expired a long time ago (before Apr 2016), so your Wallaby Core doesn't support latest node versions. 

You may either consider renewing your wallaby license to get access the newer version that supports Node 6, 7, 8, 9, or switch to Node 4. Note however that `create-react-app` won't work for you without the license renewal, because its current Jest version support was added after Apr 2016.
