### ISSUE TITLE
Wallaby with jest snapshotSerializers: jest-serializer-path

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#1565]
### Issue description or question
I am unsure how to configure Wallaby to work with [npmjs.com/package/jest-serializer-path](https://www.npmjs.com/package/jest-serializer-path). The ``snapshotSerializers`` doesn't seem to be running. Please advise what I am doing wrong here.

Example repo: [chrisblossom/wallaby-issue-1565](https://github.com/chrisblossom/wallaby-issue-1565)

### Wallaby.js configuration file

```javascript
/* eslint strict:off, global-require:off */

'use strict';

module.exports = wallaby => {
    return {
        files: [
            {
                pattern: 'src/**/__sandbox__/**/*',
                instrument: false,
            },
            'src/**/*.js',
            'jest.config.js',
            '.env',
            'src/**/*.snap',
            '!src/**/*.test.js',
        ],

        tests: [
            'src/**/*.test.js',
        ],

        env: {
            type: 'node',
            runner: 'node',
        },

        testFramework: 'jest',

        setup: w => {
            /**
             * https://github.com/wallabyjs/public/issues/1268#issuecomment-323237993
             */
            if (w.projectCacheDir !== process.cwd()) {
                process.chdir(w.projectCacheDir);
            }

            process.env.NODE_ENV = 'test';
            const jestConfig = require('./jest.config');
            w.testFramework.configure(jestConfig);
        },
    };
};
```

### Code editor or IDE name and version

```
WebStorm 2018.1 EAP
Build #WS-181.4203.9, built on March 13, 2018
JRE: 1.8.0_152-release-1136-b20 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
### OS name and version

``macOS 10.13.3``

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo! I have sent your the [pull request](https://github.com/chrisblossom/wallaby-issue-1565/pull/1) to get it working. 

`jest-serializer-path` uses its own `__dirname` for finding out the root location, instead of for example `process.cwd()` like many other modules do when they need the root path. So the module just needs t obe located in the wallaby tests folder.

Note that if you are using another described way to add the serializer:

```javascript
const serializer = require('jest-serializer-path')
expect.addSnapshotSerializer(serializer)
```

then no changes to your `setup` function is required (just the module inclusion in your `files` list).
