### ISSUE TITLE
Configuration for React Native with Typescript

### ISSUE THREAD

**Issue by robertohuertasm** [wallabyjs/public#1583]
Hi, I've been looking for a working configuration file for a `React Native` with `TypeScript` project but I can only find the example for a `CRNA` app. Can someone point me to the proper example in case it exists? I can't seem to make this work with the  `tsx` files.

Thanks for your help!

**Comment by ArtemGovorov** [comment]
Could you please share a sample repo with your current config demonstrating the issue? We are happy to take a look and help with the config.

**Comment by robertohuertasm** [comment]
Hello @ArtemGovorov, finally I found some time to set up a (project showcasing the issue](https://github.com/robertohuertasm/wallabyjs-react-native). Hope you can help me configure it! 😜

**Comment by ArtemGovorov** [comment]
Thanks. I have [sent you the PR](https://github.com/robertohuertasm/wallabyjs-react-native/pull/1) to make it work. You need to include `.tsx` pattern - it's the main reason why it didn't work. I have also added [babel preprocessor that runs after TypeScript compiler](https://wallabyjs.com/docs/integration/typescript.html#compiling-to-es6-and-using-babel) to do the same as your `ts-jest` config does (also passing `target: 'es5'` to TypeScript compiler as a workaround for [this Babel bug](https://github.com/babel/babel/issues/7627)).

**Comment by ArtemGovorov** [comment]
@robertohuertasm It sounds like a runtime error and looks like you may be missing [the `testEnvironment` Jest setting](https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string), because if I add `window` reference to any of your sample repo tests, plain Jest CLI (without wallaby) starts producing the `window is undefined` error. So I'm not sure if you just need to set it for wallaby (as the error doesn't seem to be wallaby specific), but if you only want to set it for wallaby, I have sent you the [PR with an example of how to do it](https://github.com/robertohuertasm/wallabyjs-react-native/pull/2). 

If it doesn't help, please update [your sample repo]((https://github.com/robertohuertasm/wallabyjs-react-native)) with an example of the issue that we can reproduce, happy to take a look.

**Comment by robertohuertasm** [comment]
@ArtemGovorov, thanks for your PR. In my real case, Ive still have some issues but I guess it's the problem with `no-hello-world` projects. Anyway, you've shown me the way and I really appreciate your help! ❤️
