### ISSUE TITLE
Strange error after triggering jQuery keyup event in test file

### ISSUE THREAD

**Issue by tmunin** [wallabyjs/public#1596]
### Issue description or question
I am now working on a project based on jQuery.
I create JSDOM and virtual window in wallaby config setup method.
After I added below code in a test file.

```
let expectedQty = 15;
let input = $(".saicle-sh input.125ml");
input.val(expectedQty);
input.trigger("keyup");
let actualQty = numeral($(".preview tr.saicle-sh.125ml .qty").text()).value();
should(actualQty).equal(expectedQty);
```
I found a strange error every time I start typing on source file as shown in these screenshots.
![screen-shot-1-before](https://user-images.githubusercontent.com/32817474/38162419-1fa61b36-350b-11e8-9521-07e9919a6fce.png)
![screen-shot-2-after-typing](https://user-images.githubusercontent.com/32817474/38162420-218f7ea6-350b-11e8-8878-3deba14c85ca.png)

I have to restart Wallaby to clear this error away. but, If I comment out the line input.trigger("keyup"), the wallaby system is back to its normal operation and work fine again. 

Do you know what might be the problem if I trigger jQuery event like this and also any work around suggestion?

### Wallaby.js configuration file

[wallaby.conf.js.zip](https://github.com/wallabyjs/public/files/1865401/wallaby.conf.js.zip)

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It may some JSDOM caching issue, but it's not something that we have seen it before.1

If it is indeed a caching issue of JSDOM or some other modules that you are using, then you may add the [`workers: {restart: true}` setting](https://wallabyjs.com/docs/config/workers.html) to see if it helps:

```diff
...
module.exports = function (wallaby) {
  return {
    ...

+   workers: {restart: true}
  };
};
```

If it's working with the setting, then the issue is not with wallaby, but with caching in your app/or modules (like `jsdom`).

So, with the setting wallaby will restart test worker node process and it does affect the performance a bit. If you'd like to avoid doping it, then we'll need to find out what and how is cached by your app/or modules, and then you may clear the cache in your `setup` function.

I have set a small repo https://github.com/ArtemGovorov/wallaby-1596 with your config and code, and it's working for me without any issues. Could you please try to clone, run `npm i` and see if wallaby is working for you on it? If it is working, please add the bits we are missing to reproduce the issue.

**Comment by tmunin** [comment]
Thanks for your help, Artem.
Adding `workers: {restart: true}` to my wallaby config file does solve the problem.
But, I notice a small delay in my work flow to get the test output.
That's why avoid doping is clearly a better option.

I have already put the code in your repo to reproduce this issue.
It seems like any code snippet that is added inside jQuery keyup callback introduces the bug.
Already make a pull request to your repo, thanks.

**Comment by ArtemGovorov** [comment]
Thanks for the update! Was able to find the reason - `jquery` module is caching stuff, so simply clearing its cache [using the way described in our docs](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) works:

```diff
...

module.exports = function (wallaby) {
  return {
    ...
    //setup virtual dom and browser in test environment
    setup: (wallaby) => {

+     delete require.cache[require.resolve('jquery')];

      ...
    },

    ...
  };

```


https://github.com/ArtemGovorov/wallaby-1596/blob/62318bb61c22c0afcc00a766545d1bd2c8996b4a/wallaby.js#L27

**Comment by tmunin** [comment]
Everything work perfectly now : )
Thanks a lot
