### ISSUE TITLE
Support wallaby configuration file tracking

### ISSUE THREAD

**Issue by johnrob1880** [wallabyjs/public#16]
So far, I love this! Using webstorm 9.0.3 and jasmine.js 2.1.3, I noticied adding files to the wallaby.json were not recognized until I restarted the run? I would create a [somefile].js file, create a [samefile].spec.js file, add them to the wallably.json and then start writing the test all while the wallaby session was running. The tests would all fail with undefined until I restarted the wallaby session? This was when I was using direct file names and not pattern matching for the source files in the wallaby.json file:

{
  "files": [
    "src/fx.js",
    "src/fx.core.js",
    "src/fx.core.ui.js"
  ],

  "tests": [
    "test/*spec.js"
  ],

  "testFramework": "jasmine@2.1.3"
}

**Comment by ArtemGovorov** [comment]
Thanks!

At the moment, every time you change the config - it has to be restarted. The reason is that some changes to the config file may affect the whole configuration. We'll address the issue somehow in future.

However, when using file patterns, the restart is not required, because the config doesn't change and wallaby picks up new files on the fly based on those patterns.
