### ISSUE TITLE
Output highlighting disappeared in VSCode 1.22.1

### ISSUE THREAD

**Issue by axelnormand** [wallabyjs/public#1611]
### Issue description or question

Hello, Just upgraded my VSCode on Windows to 1.22.1 and syntax highlighting has disappeared on the Output Tab for Wallaby.js Test.
It's just white text now. 
Also src links have disappeasred. There is no underline now on the .ts files to jump to the test file in question
I'm using react native + jest + typescript

Thanks.

**Comment by ArtemGovorov** [comment]
This is highly unlikely caused by anything in Wallaby. Due to the way [highlighting currently works in VS Code](https://github.com/Microsoft/vscode/issues/11005), it is possible that some other extension had  "stolen" the highlighting for output channels. Please try disabling other extensions (specifically those you've installed recently) to find out the conflicting one.

**Comment by axelnormand** [comment]
wow quick response. Many thanks.
Yup it was the "Code Runner" extension which i don't really use so have uninstalled.
