### ISSUE TITLE
Support nvm node version if .nvmrc exists

### ISSUE THREAD

**Issue by yairhaimo** [wallabyjs/public#1632]
### Issue description or question
Right now if you do not specify an env.runner Wallaby will use its own version of node or the system default one. Is there a way to have Wallaby use the correct node binary if an `.nvmrc` file exists in the repository?

### Example
`.nvmrc`'s content:
```
8
```
Resolves to: `$HOME_DIR/.nvm/versions/node/v8.7.0/bin/node`

### Wallaby.js configuration file

```javascript
  env: {
      type: 'node',
      runner: 'node' // <---
    },
```

Thanks!

**Comment by ArtemGovorov** [comment]
The `env.runner` setting allows to specify any path/command. You can point `node` to nvm, so that `runner: 'node'` resolves the correct version, or specify an absolute path `runner: '...../.nvm/versions/node/v8.7.0/bin/node'`, or create a helper (perhaps sharing it as a package makes sense because it may be useful to others) that resolves the path: `runner: resolveNvmNodePath()`.
