### ISSUE TITLE
Different test count to Karma

### ISSUE THREAD

**Issue by glendaviesnz** [wallabyjs/public#1655]
### Issue description or question
We get a different test count between wallaby and karma, but there are no console errors in wallaby to indicate that some tests may not be running - both wallaby and karma indicate that all tests are passing - see attached - any ideas why count might be 85 less in wallaby, our ideas on how to easily see which tests are not run by wallaby? Thanks.
![testcount](https://user-images.githubusercontent.com/3629020/39974470-327d41e6-577d-11e8-9a32-4f2de5cd4252.PNG)

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, use: [
            {
                "loader": "raw-loader",
                "options": {
                    "sourceMap": false,
                    "importLoaders": 1
                }
            },
            {
                "loader": "sass-loader",
                "options": {
                    "sourceMap": false,
                    "precision": 8,
                    "includePaths": [
                        "./src/styles"
                    ]
                }
            }
        ]},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ],
      alias: {
          '../../../assets/WebViewer.3.2.0/lib/WebViewer.js': path.resolve(__dirname, 'src/assets/WebViewer.3.2.0/lib/WebViewer.js')
      }
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'chrome'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.23.0

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
With your current config, Wallaby runs all `src/**/*spec.ts` test files, so whatever number of tests is in those file is reported. 

My guess would be that perhaps your karma config runs some other tests as well (that are not specified in your wallaby `tests` list), maybe e2e tests (that are excluded in your wallaby config)? From the tests difference number, looks like karma may be running a few more spec files that names are not satisfied by the specified test file pattern:
```js
    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],
```

You may see the full tree of tests that wallaby runs in [the Wallaby App](https://wallabyjs.com/docs/intro/get-started-wallaby-app.html). 

Another way to get the full list of tests that wallaby runs would be to open the [Wallaby Console output channel](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) in Vs Code and because you have the `debug: true` setting in your config, wallaby prints the names of all tests that it runs, maybe your could compare the list with what karma runs. You may also spot some issues/errors printed there that perhaps could provide some clues about the missing tests.

**Comment by glendaviesnz** [comment]
Thanks for this detail - it is probably going to be a while before we get the time to investigate this so feel free to close in the meantime - we will come back to you if we can't identify the issue with your suggestions.

**Comment by ArtemGovorov** [comment]
No worries, thanks, I'll close the issue for now but happy to re-open it when you have a chance to investigate it.
