### ISSUE TITLE
[Config question] Path-specific environment variables

### ISSUE THREAD

**Issue by seanpoulter** [wallabyjs/public#1673]
### Issue description or question

Hey @ArtemGovorov! Thanks for your previous help with the module aliasing in my Lerna repo. I'm still trying to work out more of the kinks.

Is there any way to set up the env variables before tests in each file are run? The setup requires:
* tests in `packages/module-a` need `MY_ENV` to be `test`
* tests in `packages/module-b` need `MY_ENV` to be `testing`.

Any ideas?

I can't seem to find the function that would be evaluated before each file is run in the docs to do something like:

```js
beforeTestsInFileRun(path) {
  process.env.MY_ENV = path.includes("packages/module-b") ? 'testing' : 'test'
}
```

**Thanks in advance!**

### Code editor or IDE name and version

Visual Studio Code v1.21.1

### OS name and version

OSX 10.13.4

**Comment by ArtemGovorov** [comment]
@seanpoulter How would you do it in plain mocha (without Wallaby)?

Two ways of getting it work come to mind. 

It really depends on whether you need the env variable just during the test file loading (when it is `require`-d and it is loading its dependencies), or before/during tests run, or both. 

One way I could suggest is to use Mocha hooks:

```js
  setup: w => {
    ...

    const mocha = w.testFramework;
    mocha.suite.beforeEach(function () {
      process.env.MY_ENV = mocha.suite.ctx.currentTest.file.includes("packages/module-b") ? 'testing' : 'test'
    });
  },
```

This way you'd be setting the variable before every test and can check what file is currently running. The hook is a but too late to use if your test file is importing some dependencies and you need the correct `process.env.MY_ENV` during the import of those dependencies.

Another way would be to patch `require`:

```js
  setup: w => {
    ...
    if (!global._moduleAliasesRegistered) {
      const {Module} = require('module');
      Module.prototype.require = new Proxy(Module.prototype.require, {
        apply: (target, thisArg, [path]) => (
          process.env.MY_ENV = path.includes(".test") && path.includes("packages/module-b") ? 'testing' : 'test',
          target.call(thisArg, path)
        )
      });
      global._moduleAliasesRegistered = true;
    }
   
  },
```

This way you'd be setting the variable before every test file is required, so the `process.env.MY_ENV` will be available during importing any modules from within the test file as well. However, because Mocha, as many other testing frameworks, first loads all test files, and only then executes tests, during tests execution phase, the `process.env.MY_ENV` will have the value corresponding the last test file that was loaded.

So the implementation of the `beforeTestsInFileRun` that you are looking for really depends on what you mean by `tests in file run`.
