### ISSUE TITLE
 Wallaby No Longer Shows Green Squares when test pass?

### ISSUE THREAD

**Issue by maccurt** [wallabyjs/public#1690]
My test are all passing but I don't see any green indicators that they are passing in Visual Studio Code. If I fail a test it does show the red/pink squares in the editor, but not the green squares anymore.

I am pretty sure it worked with the same configuration before, but there was a wallaby update.

### Code editor or IDE name and version

Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:38.209Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

### OS name and version

Windows
****  

var wallabyWebpack = require('wallaby-webpack');
var path = require('path');

var compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions);

compilerOptions.module = 'CommonJs';

module.exports = function (wallaby) {

  var webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
      'src/wallabyTest.js',
      'src/**/*.spec.js'
    ],

    module: {
      rules: [
        {test: /\.css$/, loader: ['raw-loader']},
        {test: /\.html$/, loader: 'raw-loader'},
        {test: /\.ts$/, loader: '@ngtools/webpack', include: /node_modules/, query: {tsConfigPath: 'tsconfig.json'}},
        {test: /\.js$/, loader: 'angular2-template-loader', exclude: /node_modules/},
        {test: /\.json$/, loader: 'json-loader'},
        {test: /\.styl$/, loaders: ['raw-loader', 'stylus-loader']},
        {test: /\.less$/, loaders: ['raw-loader', 'less-loader']},
        {test: /\.scss$|\.sass$/, loaders: ['raw-loader', 'sass-loader']},
        {test: /\.(jpg|png)$/, loader: 'url-loader?limit=128000'}
      ]
    },

    resolve: {
      extensions: ['.js', '.ts'],
      modules: [
        path.join(wallaby.projectCacheDir, 'src/app'),
        path.join(wallaby.projectCacheDir, 'src'),
        'node_modules'
      ]
    },
    node: {
      fs: 'empty',
      net: 'empty',
      tls: 'empty',
      dns: 'empty'
    }
  });

  return {
    files: [
      {pattern: 'src/**/*.+(ts|css|less|scss|sass|styl|html|json|svg)', load: false},
      {pattern: 'src/environments/*.ts', ignore: true},
      {pattern: 'src/**/*.d.ts', ignore: true},
      {pattern: 'src/**/*spec.ts', ignore: true},      
      {pattern: 'src/main.ts', ignore: true},      
      {pattern: 'src/test.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'src/**/*e2e-spec.ts', ignore: true}
    ],

    testFramework: 'jasmine',

    compilers: {
      '**/*.ts': wallaby.compilers.typeScript(compilerOptions)
    },

    middleware: function (app, express) {
      var path = require('path');
      app.use('/favicon.ico', express.static(path.join(__dirname, 'src/favicon.ico')));
      app.use('/assets', express.static(path.join(__dirname, 'src/assets')));
    },

    env: {
      kind: 'electron'
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};

**Comment by ArtemGovorov** [comment]
Could you please check if this sample project is working as expected for you https://github.com/wallabyjs/ngCliWebpackSample (showing green squares when tests are passing)?

If the project is working as expected, then the issue may be specific to your setup, in which case please create a sample repo demonstrating the issue, we are happy to take a look into.

If the project is not showing green squares, please try the following:
- uninstall the extension in VS Code, open the `~/.vscode/extensions` folder and delete all `WallabyJs.wallaby-vscode-1.0.*` subfolders in there. Then install the extension from teh scratch to see if it's working.
- if the previous step didn't help:
  - install [VS Code insiders build](https://code.visualstudio.com/insiders/), install wallaby extension only in it and try running your project. If it's working, then then the issue is likely related to one of other extension (that you may have installed recently).
  - open VS Code Dev Tools (`Help - Toggle Developer Tools` command), open Console and copy&paste any related errors/output from there.

**Comment by maccurt** [comment]
Will do, I will get back to you.

**Comment by maccurt** [comment]
I downloaded the sample project and npm'ed it and same result. I will uninstall the extensions next. Get right back to you

**Comment by maccurt** [comment]
I delete the extension and re-installed it and it all works now. Thanks!
