### ISSUE TITLE
Unexpected Identifier when trying to import ES6 module

### ISSUE THREAD

**Issue by j2is** [wallabyjs/public#1698]
I'm trying to import gsap into my js class, I receive an unexpected identifier error when calling the import. I don't believe my babel compilation is being configured correctly, for now I've commented it out. Please see [reduced test case repo](https://github.com/j2is/wallaby-test-2)

### Wallaby.js configuration file

```
module.exports = (wallaby) => {
  return {
    files: [
      'src/js/**/**/*.js*'
    ],
    tests: [
      'tests/unit/*Spec.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    debug: true,
    // compilers: {
    //   '**/**/*.js': wallaby.compilers.babel()
    // }
  };
};
```

Sublime Text v3.1.1 build 3176
OSX

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. You wallaby Babel config is correct, so you may uncomment it.

The issue is not Wallaby specific. If I run ` ./node_modules/.bin/jest`, Jest CLI produces the same error. You need to configure Jest to not ignore certain `node_modules` when transpiling your code. 

Actually error messages from Jest (CLI or in Wallaby Console) are pretty descriptive in terms of what to do in this case. The issue is that the `gsap` module is using ES modules, so to run then in node, Jest needs to know not to ignore the module when doing babel compilation.

If you are looking for a solution that works for Wallaby and don't care about running plain Jest CLI, then you may [pass the correct Jest config inside Wallaby setup function](https://wallabyjs.com/docs/integration/jest.html#jest-configuration), and this should do the trick:

```js
module.exports = (wallaby) => {
  return {
    files: [
      'src/js/**/**/*.js*'
    ],
    tests: [
      'tests/unit/*Spec.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    testFramework: 'jest',
    debug: true,
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },

    setup: wallaby => {
      wallaby.testFramework.configure({"transformIgnorePatterns": ["/node_modules/(?!gsap/)"]})
    }
  };
};
```

If you'd like to have both Wallaby and Jest CLI running correctly, then you may have your current Wallaby config (with `compilers` section uncommented), and create the `jest.config.js` file in your project's root, with the following content:

```js
module.exports = {
  "transformIgnorePatterns" : ["/node_modules/(?!gsap/)"]
};
```

This way both Wallaby and Jest CLI will read the config.

P.S. After fixing this issue, your test will still fail because you're using `this` in your tests and it's not defined within Jest tests.

**Comment by mesqueeb** [comment]
@ArtemGovorov I have read that TypeScript does not require setup. TypeScript is able to do anything Babel does (like importing es6 modules), so I had deleted Babel and make my builds with Rollup and TypeScript compiler.

However, now when I try Wallaby I get the same error as the OP.
`unexpected identifier` at `import 'something' from 'somewhere'`...

Do I have to re-install all babel related devDependencies to make Wallaby to work again?

This was my original `wallaby.conf.js`
```js
module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js',
      'dist/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    // I had deleted the compilers since I only use TypeScript and no Babel currently, but deleting the compilers breaks my Wallaby.
    compilers: {
      '+(src|test)/**/*.js': wallaby.compilers.babel({
        presets: ['@babel/preset-env', '@ava/babel-preset-stage-4'],
        plugins: ['@babel/plugin-proposal-object-rest-spread']
      })
    },
    testFramework: 'ava',
    debug: true
  }
}
```

**Comment by ArtemGovorov** [comment]
@mesqueeb You don't need any babel dependencies if you are relying of `typescript` module only to do your compilation. Looks like though you are using `.js` file extensions, so will need to add TypeScript compiler setting for `*.js` files as described at https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings. If you get stuck, please create a sample repo demonstrating the issue - we are happy to take a look and help.

**Comment by mesqueeb** [comment]
@ArtemGovorov That's very nice of you, thank you. I couldn't get it to work. I have a `ts` src but `js` dist and tests.
Here is [the repo](https://github.com/mesqueeb/is-what).

**Comment by ArtemGovorov** [comment]
@mesqueeb Thanks for the repo. I have sent you [the pull request](https://github.com/mesqueeb/is-what/pull/6) to make it work.
