### ISSUE TITLE
Unable to get Lerna and TypeScript monorepo working

### ISSUE THREAD

**Issue by Anupheaus** [wallabyjs/public#1714]
### Issue description or question
I've created a simple mono repo using Lerna, TypeScript, Yarn and Wallaby, and I was using this sample to make it work: https://github.com/wallabyjs/wallaby-typescript-sample/ but it doesn't seem to want to work (or rather, I can't get it to work).

I have added your gitlab handle to the mono repo (here: https://gitlab.com/Anupheaus/wallaby-test) so you can take a look (if possible and when convenient).

Thank you

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo.

I have created merge request with working wallaby config. The major change was just to add the [module alias as discussed with you here](https://github.com/wallabyjs/public/issues/1708#issuecomment-397475422).

I also had to import React and remove Enzyme (as it needs adapter setup that is missing in the repo). Probably in your real project you're setting React global somewhere in your setup scripts and configuring Enzyme, so it shouldn't be an issue.

Let me know if it works for you, if something doesn't work, feel free to add the repro to your sample repo, happy to take a look.

**Comment by Anupheaus** [comment]
Hi Artem,

Thank you ever so much, I do appreciate you fixing the repo and I did try the module alias and that fixed an initial problem but then I got stuck with something else and realised I'd probably have to go down the webpack route.

One thing I noticed about your changes is you switching to `node` environment, I should have said that I can't do that, there are a number of places I reference the `window` object and that doesn't work in `node`.  Is there any chance you could take a look at making it work with the browser env setting please?  I've modified it again as best as I can to this but still hitting issues 😢

**Comment by ArtemGovorov** [comment]
It doesn't look like your current codebase is ready for browser environment. I can see you are using `global` in some setup files and that will obviously not work in browser without some changes. 

> there are a number of places I reference the `window` object and that doesn't work in `node`

Have you considered using `jsdom`? That's what many users do (see an [example of a setup here](https://github.com/wallabyjs/public/issues/1487)) with mocha with or without Wallaby (and pretty much all users of Jest testing frontend, Jest doesn't even have an option to test in a real browser, only in `node` with `jsdom`).

If you'd like to configure wallaby to use `webpack`, then it is a whole different story, and your config will be significantly different. I'd suggest [this docs section](https://wallabyjs.com/docs/integration/webpack.html) as a start. For your module alias, you'll need to use Webpack's [`resolve.alias`](https://webpack.js.org/configuration/resolve/#resolve-alias) instead of the `module-alias` module.

**Comment by Anupheaus** [comment]
I am now using jsdom and it is working perfectly.

Thank you very much!
👍
