### ISSUE TITLE
IntelliJ: Jest snapshot file not created

### ISSUE THREAD

**Issue by foxbunny** [wallabyjs/public#1721]
### Issue description or question

I'm currently using Wallaby with IntelliJ IDEA Ultimate, Jest, and JS/Babel. If I have a test module that does not yet have a matching snapshot file, Wallaby will not create the snapshot for it but will still mark it as passing.

Once the snapshot is created (by running Jest manually in the terminal), Wallaby works as expected and can create new snapshots, manipulate existing ones, etc.

### Wallaby.js configuration file

```javascript
const babelConf = {
  sourceMap: true,
  plugins: [
    'ramda',
    'syntax-dynamic-import',
    'dynamic-import-webpack',
    'transform-decorators-legacy',
    'transform-object-rest-spread',
    'transform-class-properties',
    ['transform-react-jsx', {
      pragma: 'h',
    }],
    'jest-hoist',
  ],
  presets: [['env', {
    targets: { browsers: ['last 2 major versions', 'ie >= 11']},
  }], 'babel-preset-jest'],
}


module.exports = wallaby => ({
  files: [
    'package.json',
    'jest.config.js',
    'src/**/*.*',
    '!src/**/*.test.js',
  ],
  tests: [
    'src/**/*.test.js',
  ],
  env: {
    type: 'node',
  },
  testFramework: 'jest',
  debug: true,
  compilers: {
    '**/*.js': wallaby.compilers.babel(babelConf),
  },
  setup(wallaby) {
    var jestConfig = require('./jest.config')
    jestConfig.modulePaths[0] = jestConfig.modulePaths[0].replace('<rootDir>', wallaby.projectCacheDir)
    wallaby.testFramework.configure(jestConfig)
  },
})
```

### Code editor or IDE name and version

IntelliJ IDEA v2018.1
Wallaby version 1.0.115

### OS name and version

Windows 10

**Comment by foxbunny** [comment]
Additional info: I've just noticed that, even when there is a snapshot file, it will not create snapshots for new tests as I type. If I unfocus the editor, which triggers the auto-save feature, the snapshot is created at that moment. I would expect the snapshot to be created as I finish typing `.toMatchSnapshot()`.

**Comment by ArtemGovorov** [comment]
We have just checked both cases and couldn't reproduce them:
- wallaby creates snapshot files if they don't exist,
- wallaby adds snapshots in a snapshot file as you type.

It may be possible that you are actually hitting IDEA lags to refresh files that have already changed on disk.

Try removing a snapshot file, run wallaby, and open your file explorer to see if the file is created. IDEA will also show it if you run `Synchronize` context action on the project folder/subfolder.

Same happens to the snapshot file - because the changes are made outside of IDEA, it may lag to display them. But if you monitor the file size in explorer for example, you may see that the file size changes immediately after you finish typing `.toMatchSnapshot()`.

**Comment by foxbunny** [comment]
> It may be possible that you are actually hitting IDEA lags to refresh files that have already changed on disk.

It hadn't occured to me that could be the case. I'll check that. Thanks

**Comment by foxbunny** [comment]
Confirming that it is indeed the refresh issue.
