### ISSUE TITLE
Wallaby not getting the correct unit test total with Angular Jest

### ISSUE THREAD

**Issue by blopez2010** [wallabyjs/public#1723]
### Issue description or question
Wallaby is not loading nested files specs so unit tests totals are not correctly set in the bottom bar.

![image](https://user-images.githubusercontent.com/15872584/41802274-e63c39b6-763c-11e8-8c16-556aa1ff026a.png)

According to Jest, this is the correct unit test total (please omit the failing ones haha we are moving to Jest, that's why).
![image](https://user-images.githubusercontent.com/15872584/41802290-03fef54c-763d-11e8-890a-11fe3b7d4c9f.png)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  const jestTransform = file => require('jest-preset-angular/preprocessor').process(file.content, file.path, {
    globals: {
      __TRANSFORM_HTML__: true
    }
  });

  return {
    files: [
      'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'src/jest.setup.ts',
      '!src/**/*.spec.ts',
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.html': file => ({
        code: jestTransform(file),
        map: {
          version: 3,
          sources: [],
          names: [],
          mappings: []
        },
        ranges: []
      })
    },

    preprocessors: {
      'src/**/*.js': jestTransform,
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

macOS High Sierra v10.13.5

**Comment by ArtemGovorov** [comment]
From your screenshot it looks like Wallaby did not have a chance to run the spec file, so that is why Jest (when running from Wallaby) couldn't count the tests in the file. I expect this may have happened with a few of your spec files.

The scenario is quite possible because something else (and you need to see Wallaby Console/Wallaby Failing Tests output channels for details) can be blocking the tests from running. And the reasons may be different from those that are causing errors in your Jest CLI tests run, so the numbers may not match.

For example, there may be an issue in your Wallaby config that stops some of your spec files from even loading (which seem to be the case), so the numbers are different. You need to see Wallaby Console/Wallaby Failing Tests output channels for details. 

I would suggest to first get plain Jest CLI working, and once done see what Wallaby is reporting.

Hope it makes sense.
