### ISSUE TITLE
Firefox test runner environment

### ISSUE THREAD

**Issue by Gozala** [wallabyjs/public#1724]
From what I can tell right now there is no way I could run test in Firefox. Are there any plans to support it or browsers other than Chrome ?

Thanks

**Comment by ArtemGovorov** [comment]
> From what I can tell right now there is no way I could run test in Firefox.

Correct.

> Are there any plans to support it or browsers other than Chrome ?

No such close plans, but things may change in future.

**Comment by elgalu** [comment]
Why instead of trying to add support for more browsers you stick with Chrome and allow users to run the tests via Webdriver (aka Selenium) ? without IDE integration.

This way developers can iterate fast with Wallaby.js + IDE + Chrome headless and when they want to do cross-browser testing you delegate to Webdriver to run those slow tests.

i.e. provide a way to re-use the tests with a different runner.

**Comment by smcenlly** [comment]
Closing this feature request as we have no plans to add support for using FireFox as a testing environment. In the future we may support additional browser through something like https://playwright.dev.
