### ISSUE TITLE
Automatically update wallaby snapshots

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#1731]
### Issue description or question

Hi, is it possible to automatically update jest snapshots?
In jest I would run `jest --updateSnapshot --watchAll`

I tried to put this to `jest.config.js` to no avail.

Do not ask me why, but during development sometimes I like to do this.

### Code editor or IDE name and version

Visual Studio Code

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
There's no such option, and I doubt you'd be happy if we add one, because:
- you'll need to change your config and restart Wallaby to turn it on and off,
- when you forget to turn it off, you'd probably not be happy that Wallaby had overwritten all your snapshots.

Wallaby for VS Code does have the `Update project snapshots` command that you may use at any time to force all of the project's snapshots to be updated.
