### ISSUE TITLE
Is there a way to find all non console.log logs in my codebase before I checkin

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#1735]
### Issue description or question

I would like to be able to find and remove all non console.log logs before I checkin.  Example:
```javascript
var moobz='hi'
moobz //shows hi inline in my editor
```
I use this a lot to see whats in my moobz var but cant easily find and remove them later.  

### Wallaby.js configuration file
na

### Code editor or IDE name and version

Visual Studio Code v1.24.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Maybe a linter rule, but I'm not sure. 

These aren't Wallaby specific constructs, those are just identifier expressions (Wallaby just automatically logs them when it encounters them).

There is another more flexible way to [log in Wallaby with live comments](https://wallabyjs.com/docs/intro/advanced-logging.html#live-comments). So instead of adding `moobz` identifier expression, you may add the comment:

```
var moobz=... //?
```
and it'll print the value the same way. It's less to type, and you can easily find all occurrences of these comments with a simple search from your editor.

**Comment by bj97301** [comment]
@ArtemGovorov Oh now thats cool.  Thanks bud 👍

**Comment by bj97301** [comment]
Found some docs on it if anyone else is interested: https://wallabyjs.com/docs/intro/advanced-logging.html
