### ISSUE TITLE
Cant require a test file

### ISSUE THREAD

**Issue by bj97301** [wallabyjs/public#1747]
### Issue description or question

How can I require a test file in another test?  I always get that property of '0' bs. 

### Wallaby.js configuration file

```javascript
process.env.NODE_ENV = 'development'
module.exports = function(wallaby) {
    return {
        files: [
            'src/**/test.stripe_nocks.js',//<-------- thats the one I want to require 
            'src/**/*.js',
            'src/**/*.json',
            'test/*.js',
            '!test/index.js',
            '!src/**/test.*.js',
        ],
        tests: [
            'src/**/test.*.js',
            'test/index.js',
        ],
        env: {
            type: 'node'
        },
        compilers: {
            '**/*.js': wallaby.compilers.babel()
        },
        setup: function(w) {
            let chai = require('chai')
            let should = require('chai').should
            let chaiAsPromised = require('chai-as-promised')
            chai.use(chaiAsPromised)
            chai.use(should)
        },
        slowTestThreshold: 10,
        filesWithNoCoverageCalculated: ['src/**/router.js', 'src/entry.js', 'test/wait**']
    }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.24.1
### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
> How can I require a test file in another test?

If by "a test file" you mean a file with tests, then Wallaby doesn't support the scenario. It's not a good practise to import test files into other test files. One of the reasons why - the tests in the imported file will be executed multiple times, when you run the test file and when you run every other test file that imports the test file (and this is not specific to Wallaby). If there is something in the test file that is reusable, then a better solution is to refactor the reusable bit into a file of its own and import it where it is required (instead of importing test files and causing duplicated test execution).

Having said that, you may try to make it work in Wallaby by excluding the file from the `tests` list and not excluding it from the `files` list (right now with your config it is still excluded because exclusions override inclusions). Try this (but I would rather recommend refactoring as suggested above):

```js
files: [
            'src/**/*.js',
            'src/**/*.json',
            'test/*.js',
            '!test/index.js',
            '!src/**/test.!(stripe_nocks).js', // <--
        ],
        tests: [
            'src/**/test.*.js',
            'test/index.js',
            '!src/**/test.stripe_nocks.js',  // <--
        ],
```

**Comment by bj97301** [comment]
The `!(stripe_nocks)` did the trick.  Man, you guys thought of everything.  Thanks again @ArtemGovorov 

Regarding the test files importing other test files, couldnt agree more and you wont be enabling me to do something bad(hopefully).  My situation is more like I want to share a method that is only used in my tests.  I start it with `test.` so that it wont get included in my production code but it has no `it`s or `describe`s in it.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> My situation is more like I want to share a method that is only used in my tests.  I start it with `test.` so that it wont get included in my production code but it has no `it`s or `describe`s in it. 

Ah, got it, fair enough. You should be ok then as in your case the file is just an exclusion from the `tests` pattern (resolved with the `!(...)`).

**Comment by bj97301** [comment]
Good point.  Done and done.  Have a good one and thanks for the super quick reply.
