### ISSUE TITLE
"Module .. in the .. option" with module in files

### ISSUE THREAD

**Issue by Molt** [wallabyjs/public#1759]
Similar to #1755 I'm having trouble with getting a module not found error for a file which is included in Wallaby's list of files.

I am using Babel and Typescript which complicates my setup but I can't see what I'm doing wrong here.

There's a GH repo with this error reproduced [here](https://github.com/Molt/wallaby-module-not-found).

### Wallaby.js configuration file

```javascript
// const typescriptJson = require('./tsconfig.json');
// const babelCore = require('@babel/core');

module.exports = wallaby => ({
  // module.exports = () => ({
  name: "Wallaby",

  files: [
    "tsconfig.json",
    // These are all trying to add setupEnzyme.ts...
    "./src/setupEnzyme.ts",
    "src/setupEnzyme.ts",
    "**/setupEnzyme.ts",

    // This fixes the error but no tests run
    //"**/*.{js,jsx,ts,tsx}",

    "src/**/*.{js,jsx,ts,tsx}",
    "src/**/*.{css,sass,scss}",
    "!src/**/__tests__/**/*.{js,jsx,ts,tsx}",
    "!package.json"
  ],
  tests: ["src/__tests__/**/*.{js,jsx,ts,tsx}"],

  // Don't do coverage for these files, don't include them in the calculated code coverage
  // filesWithNoCoverageCalculated: ['src/setupEnzyme.ts'],

  compilers: {
    "**/*.{js,jsx,ts,tsx}": wallaby.compilers.babel({
      //    // babel: babelCore,
      //    // presets: ['react-app'],
    })
    // '**/*.{ts|tsx}': wallaby.compilers.typeScript({
    //  typescript: typescriptJson,
    // }),
  },

  env: {
    type: "node",
    runner: "node"
  },

  testFramework: "jest"
});

```
### Jest config
```javascript
module.exports = {
  roots: ["./src"],
  transform: {
    "^.+\\.tsx?$": "babel-jest",
    ".+\\.(css|sass|scss|png|jpg|ttf|woff|woff2)$": "jest-transform-stub"
  },
  testRegex: "/src/__tests__/.*\\.tsx?$",
  moduleFileExtensions: ["ts", "tsx", "js", "jsx"],

  // Set up code coverage
  //collectCoverage: true,
  //collectCoverageFrom: ["**/src/**.{js,jsx,ts,tsx}"],
  //coverageDirectory: "coverage",

  // Setup Enzyme
  snapshotSerializers: ["enzyme-to-json/serializer"],
  // Tried these with no luck...
  //setupTestFrameworkScriptFile: "./src/setupEnzyme.ts" // Works in Jest
  //setupTestFrameworkScriptFile: "src/setupEnzyme.ts" // Does not work in Jest
  setupTestFrameworkScriptFile: "<rootDir>/src/setupEnzyme.ts" // Works in Jest
};
```

### Code editor or IDE name and version
Visual Studio Code 1.25.1

### OS name and version
Windows 10, Latest update

**Comment by ArtemGovorov** [comment]
I have sent you 2 differents PRs with the working configs:
- https://github.com/Molt/wallaby-module-not-found/pull/1,
- https://github.com/Molt/wallaby-module-not-found/pull/2

The issue was that when Wallaby compiles TS with Babel (like was configured in your compilers pattern), it renames `.ts` to `.js`, so Jest couldn't find the `src/setupEnzyme.ts` file. 

So in the first PR I have configured it to use Wallaby TypeScript compiler (enabled by default for `.ts` files). And in the second one (which is an alternative for the first one), I have disabled the `src/setupEnzyme.ts` instrumentation (it disables compilation as well), so that Wallaby doesn't touch the file and Jest can load it via `babel-jest`.

I'd recommend picking the second option, but the first one works as well.

**Comment by theutz** [comment]
Hello! I think I'm having the same problem as @Molt , but the repo used here (and the PRs used for the solution from @ArtemGovorov ) have been taken down. Any chance we can get those back?

**Comment by ArtemGovorov** [comment]
@theutz Sure, here you go:
- https://github.com/ArtemGovorov/wallaby-module-not-found/commit/67c81b389276ab2071cd1ddd0123775bf16b8fa3
- https://github.com/ArtemGovorov/wallaby-module-not-found/commit/c334b5b08b32f27afca0b3fba3d9eb2682f9a50f

**Comment by theutz** [comment]
That was the trick! Thanks for the quick response!
