### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by andrewvmail** [wallabyjs/public#1773]
Just curious how people work, i find when Wallaby get stuck for what ever reason i hit the re-run button command + r on the run window. and wallaby have to go through its bootstrapping process again, (Writing to disk and caching processed tons of files). This process takes 40 seconds or so.  Sometimes i have to go do this a lot and i end up waiting a bunch, does people usually go through what i'm going through? is there a way to avoid or minimize the bootstrap process in one's work flow?

Cheers

**Comment by ArtemGovorov** [comment]
I'd suggest trying to run `Run project test(s)` command in this case (the shortcut depends on your IDE/editor). Having said that, it'd be interesting to find out why Wallaby gets stuck in the first place, maybe you could share some logs from Wallaby Console when it gets stuck?

**Comment by andrewvmail** [comment]
Thanks for the tip. I'll post the console logs soon.

**Comment by andrewvmail** [comment]
If wallaby's first run contain a broken test (eg ava callback expect a callback but doesn't finish) it hangs without any info and the error or console.log things doesn't bubble up on to the IDE, i found a work around by short circuiting the test t.end early before the broken code. 

Once wallaby gets going subsequent test broken or not, everything seems fine.

**Comment by ArtemGovorov** [comment]
Thanks for providing the details.

It looks like the issue is not with a broken test, but only in Ava and only with a scenario/test when a callback is expected in a test. If you simply have a failing test:

```js
const {test} = require('ava');

test('should work', t => {
  boom;
});
```

Wallaby will report the failure.

However, if it is `test.cb`, then there is an issue here is that Ava never exits/neither notifies when it is waiting for the callback (if something else is not letting the test process finish). 

For example, if you run the following test

```js
const {test} = require('ava');

test.cb('should work', t => {
  setTimeout(() => {}, 2147483647)
});
```

in Ava CLI or Wallaby, it'll be spinning forever.

If you comment out the `setTimeout` line, then Ava CLI will quickly report the failure, because it finishes runner process, however Wallaby works differently and keeps the process alive until some results are received from the test runner (but there are none in this case).

Having said that, Wallaby does actually report that something is wrong in its Console:

VS Code:

<img width="1130" alt="screen shot 2018-08-03 at 1 38 47 pm" src="https://user-images.githubusercontent.com/979966/43623094-cbe1dae2-9722-11e8-822f-aa3dc2b95875.png">

IntelliJ:

<img width="831" alt="screen shot 2018-08-03 at 1 39 34 pm" src="https://user-images.githubusercontent.com/979966/43623084-c79b899c-9722-11e8-9857-85e91ae474ba.png">

Hope it makes sense.
