### ISSUE TITLE
How to update manually in IntelliJ?

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#178]
As far as I know the core is updated automatically when running Wallaby, but when is the plugin updated?
According to the release notes, the newest core is 1.0.69 and newest plugin is 1.0.21.
Currently I'm running core 1.0.73 and plugin 1.0.18.

1. My core is newer than the release notes'. Are your release notes up to date?
2. There is no "update plugin" action available for the Wallaby plugin. Refreshing the plugin list in IntelliJ doesn't help either. How can I update to 1.0.21?

**Comment by ArtemGovorov** [comment]
Changelog is updated every week, sometimes every two weeks. The reason we don't update it on each version change is because we update quite frequently, so it's easier to post a summary or released changes. The next changelog update is planned for early next week.

Currently the latest core version is 1.0.73, IntelliJ plugin is at 1.0.24. 

As opposed to the core updates, plugin updates require user to agree if he would like to install it. When a newer plugin version is available, then after you (re)start wallaby.js configuration, it should notify you with a standard notification 'sticky balloon': `A new version of the wallaby.js plugin is available`.

If the balloon doesn't pop up, please check your Notification settings to make sure that all notifications (or wallaby.js notifications in particular) are not disabled.

<img width="680" alt="screen shot 2015-07-05 at 11 54 04 am" src="https://cloud.githubusercontent.com/assets/979966/8509993/a4fba792-230c-11e5-8e95-f742ba0f2e29.png">

If for some reason you can't install it via the notification, the only way to update it manually is by getting the [latest version from our website](http://wallabyjs.com/#download) and [installing it from disk](http://wallabyjs.com/docs/intro/install.html) (existing installed version will be replaced).

![](https://cloud.githubusercontent.com/assets/979966/8124019/96efa948-1117-11e5-978b-d46661a0aa44.png)

If automatic updates mechanism is broken for you (and you have Notifications enabled), please restart your IDE, then start wallaby.js and after that check if there's something interesting in the idea.log (Help - Show Log... menu item).

**Comment by fvanwijk** [comment]
Notifications were disabled... 
Thanks for pointing that out.

Nevertheless it's not correct that manually updating an outdated plugin is disabled in Preferences > Plugins (which seems to be an IntelliJ bug).
