### ISSUE TITLE
Doesn't respect disabled autosave in VSCode

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#1787]
### Issue description or question
Even with disabled autosave, `Wallaby` keeps reacting on every file change, instead of only when the file is saved.

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (wallaby) {
  return {
    files: [
      { pattern: 'jest.init.js', load: false, instrument: false },
      { pattern: 'package.json', load: false, instrument: false },
      { pattern: 'app/components/**/*.snap', load: false, instrument: false },
      'app/**/*.js?(x)',
      '!app/components/**/*.spec.jsx'
    ],
    tests: [
      'app/components/**/*.spec.jsx',
      '!app/components/ShipmentCardNew/AdminShipmentCardNew.spec.jsx',
      '!app/components/NavSidebar/NavSidebar.spec.jsx'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },
    testFramework: 'jest',
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    delays: {
      run: 1000
    },
    ignoreFileLoadingDependencyTracking: true,
    slowTestThreshold: 1000,
    maxConsoleMessagesPerTest: 5,
    debug: true
  }
}

```

### Code editor or IDE name and version

Visual Studio Code v1.25.1
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux: 18.04

**Comment by ArtemGovorov** [comment]
This is by design. Wallaby continuously runs your on every change, not only on file save. If you'd like to make Wallaby run tests less frequently, you may specify the delay between the last change and the test run [using the `delays.run` setting](https://wallabyjs.com/docs/config/overview.html#delays-setting).

**Comment by selfrefactor** [comment]
It feels wrong not to have an option for that. For big project. `wallaby` become more of a burden than help. Not happy.

**Comment by ArtemGovorov** [comment]
> It feels wrong not to have an option for that.

Please feel free to subscribe to the feature request at https://github.com/wallabyjs/public/issues/789

> For big project. wallaby become more of a burden than help. Not happy.

We have many users using Wallaby on large and even huge projects without any issues. Wallaby performance is not affected by the size of the project, it purely depends on how fast your tests are, because Wallaby is executing a minimum required number of tests for each change. So if (a subset of) your tests are running slowly without the feature, then they'll be running slowly even if the (Run on Save) feature was there.

Also, if you could provide an example of a Wallaby slowing down for a larger project, we are happy to investigate.

**Comment by selfrefactor** [comment]
I don't want to be rude in the light in your attempts, but I still not happy `wallaby` user and I wouldn't recommend it to anyone.

**Comment by ArtemGovorov** [comment]
Sorry to hear it. The [feature request](https://github.com/wallabyjs/public/issues/789) is there (as well as many other feature requests), and at some point we'll get to implement it, but unfortunately with limited resources we can't make everyone happy as quickly as we would love to.

**Comment by alecmce** [comment]
Running Wallaby, VSCode hangs during a file edit ... despite `{ delays: { runs: 1000 }}`. It is as if it tries to run babel over the code in its syntactically incorrect form, fails, hangs... I wait about 2 seconds and can complete typing, then it runs again and is fine. This is the issue that brought me here. I would desperately like to only re-run Wallaby on explicit file saves, to avoid this problem. For me, it also feels as though `{delays}` does not appropriately configure Wallaby to run 1000ms after the last edit, just 1000ms between edits (feels like a throttle not a debounce).

**Comment by smcenlly** [comment]
Please subscribe to notifications for the [feature request to only run on save](https://github.com/wallabyjs/public/issues/789). We have prioritized this feature and expect it to be available in less than one month from now.

**Comment by smcenlly** [comment]
We've now implemented the feature request to run only on save. Please check out the details [here](https://github.com/wallabyjs/public/issues/789#issuecomment-536867267)
