### ISSUE TITLE
atom-wallaby 1.0.24 Issue

### ISSUE THREAD

**Issue by lucidprogrammer** [wallabyjs/public#1789]
### Issue description or question
0 failing tests 0 passing even when there is a test
### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function(wallaby) {
  console.log(wallaby.localProjectDir);
  console.log("-----------------------");
  console.log(wallaby.projectCacheDir);
  return {
    files: [{ pattern: "src/*.js", load: false }],
    tests: [{ pattern: "test/**/*.js", load: false, instrument: false }],
    testFramework: "mocha",
    debug: true
  };
};
```

### Code editor or IDE name and version

Atom v1.26.1 64Bit with atom-wallaby 1.0.24

### OS name and version
Ubuntu 16.04.3 LTS

wallaby.projectCacheDir does have the test files, that is fine. 
Expected the following, but missing in this version of wallaby:
I should have seen 0 tests failed and 1 test passed. Also I expected the covered function with a green marker in the source file.

 (using standard mocha I see the test pass 1).

Changing {load: true} for tests gives the following error when run

Error: Missing tracer start subscription
at http://localhost:38781/__wallaby__/tracer.js:14
Error: Missing tracer start subscription

-------------

There is nothing fancy in the test as its a new repo.
test file
```
import { expect } from "chai";
import { x } from "../../src/state.js";

describe("suite 1", () => {
   it("something 1", () => {
      expect(1).to.eql(1);
   });
  it("something 2", () => {
    console.log("hello");
    expect(x()).to.eql(1);
  });
});
```
source file
```
const x = () => {
  return 1;
};
export {x};

```

**Comment by ArtemGovorov** [comment]
A few bits are missing in your config.

- `load: false` needs to be removed, the flag stops tests from loading and it's only used when tests are loaded later by some other code (for example by Wallaby Webpack integration);
- looks like you are running your tests in node (since you're using plain mocha as well), and Wallaby by default runs them in browser, so you need to add [the `env.type` setting](https://wallabyjs.com/docs/integration/node.html);
- you are using ES modules, so are likely using Babel to compile them to CommonJs when running mocha (without Wallaby), so need the corresponding [Babel setting in Wallaby config](https://wallabyjs.com/docs/integration/es-next.html).

```diff
// paste your config here
module.exports = function(wallaby) {
  console.log(wallaby.localProjectDir);
  console.log("-----------------------");
  console.log(wallaby.projectCacheDir);
  return {
    files: [{ pattern: "src/*.js", load: false }],
-   tests: [{ pattern: "test/**/*.js", load: false, instrument: false }],
+   tests: [{ pattern: "test/**/*.js" }],
+   env: {type: 'node'},
+   compilers: {
+     '**/*.js': wallaby.compilers.babel()
+   }
    testFramework: "mocha",
    debug: true
  };
};
```

If the solution suggested above doesn't work for you, please share the sample where plain Mocha is working and Wallaby isn't, we are happy to take a look and help you with the config.
