### ISSUE TITLE
No coverage for TypeScript Jest test unit under Lerna

### ISSUE THREAD

**Issue by stevefan1999** [wallabyjs/public#1794]
### Issue description or question
The tests passed flawlessly, but there're no coverages, although manually calling CLI for coverage is still fine.

Reproduction repo: https://github.com/stevefan1999/lerna-yarn-workspaces-example

### Wallaby.js configuration file

```javascript
module.exports = wallaby => {
  return {
    files: [
      '**/tsconfig.*',
      '**/package.json',
      'jest.config.js',
      'packages/**/*.+(js|jsx|ts|tsx)',
      '!**/rollup.config.js',
      '!packages/**/dist/**',
      '!packages/**/__tests__/*.+(js|jsx|ts|tsx)'
    ],
    filesWithNoCoverageCalculated: [
      '**/tsconfig.*',
      '**/package.json',
      'jest.config.js'
    ],
    tests: [
      'packages/**/__tests__/*.+(js|jsx|ts|tsx)'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      restart: true
    },
    testFramework: 'jest',
    compilers: {
      '**/*.tsx?': wallaby.compilers.typeScript({
        module: 'commonjs'
      }),
      '**/*.jsx?': wallaby.compilers.babel({
        babelrc: true,
        presets: ['jest'],
        plugins: []
      })
    },
    setup (wallaby) {
      const jestConfig = require('./jest.config.js')
      const rewriter = obj => obj.map(p => p.replace('<rootDir>', wallaby.projectCacheDir))
      jestConfig.roots = rewriter(jestConfig.roots)
      jestConfig.modulePaths = rewriter(jestConfig.modulePaths)
      wallaby.testFramework.configure(jestConfig)
    }
  }
}
```

### Code editor or IDE name and version

```
Version: 1.26.0
Commit: 4e9361845dc28659923a300945f84731393e210d
Date: 2018-08-13T16:29:31.933Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

### OS name and version
`Microsoft Windows [Version 10.0.17134.165]`

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

The issue is that your symlinks in the node modules created by lerna are pointing to original packages but in their package.json files `main` field is pointing to `dist` folders. It means that your Jest/Wallaby may only work after you have done a build and can only show coverage against the built files.

For example, if you clone your test repo and run `npm test` (without building), Jest will fail with the exact same errors as Wallaby.

In order to make Wallaby or Jest work with your project, you'll either need to update your Jest config to include module mapper to map your `@foo` workspace to `packages/$1/src`, or update Wallaby config to do the same. If you update your Jest configuration, no Wallaby config update is required. Otherwise, please find the working Wallaby config below:

```js
module.exports = wallaby => {
  return {
    files: [
      'jest.config.js',
      'packages/**/*.+(js|jsx|ts|tsx|json)',
      '!packages/**/dist/**',
      '!packages/**/node_modules/**',
      '!packages/**/__tests__/*.+(js|jsx|ts|tsx)'
    ],
    filesWithNoCoverageCalculated: [
      '**/tsconfig.*',
      '**/package.json',
      'jest.config.js'
    ],
    tests: [
      'packages/**/__tests__/*.+(js|jsx|ts|tsx)',
      '!packages/**/node_modules/**',
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    workers: {
      restart: true
    },
    testFramework: 'jest',
    compilers: {
      '**/*.tsx?': wallaby.compilers.typeScript({
        module: 'commonjs'
      }),
      '**/*.jsx?': wallaby.compilers.babel({
        babelrc: true,
        presets: ['jest'],
        plugins: []
      })
    },
    setup (wallaby) {
      const jestConfig = require('./jest.config.js')
      jestConfig.moduleNameMapper = {
        "@foo/(.*)": "<rootDir>/packages/$1/src/"
      };
      wallaby.testFramework.configure(jestConfig)
    }
  }
}
```
Please note that we have also cleaned up your `files`/`tests` lists to make it more efficient. 

Also, to make the module mapper work, you'll need to ensure consistent naming of you package `main` files, so we have renamed `main.ts` to `index.ts` (but you can alternatively rename your `index.ts`-s to `main.ts`-s).

We have submitted the [PR with the mentioned changes](https://github.com/stevefan1999/lerna-yarn-workspaces-example/pull/1).

Hope it helps.

**Comment by stevefan1999** [comment]
Thank you sir!
