### ISSUE TITLE
cant get wallaby to play ball with react-native 

### ISSUE THREAD

**Issue by andrewvmail** [wallabyjs/public#1798]
### Issue description or question

i created a project using ```create-react-native-app AwesomeProject```

```npm test ``` works

i dropped a minimal wallaby config that should work but im getting bellow error.

Failed to run compilers on src/App.js, TypeError: Cannot read property 'bindings' of null

I believe its related to this bug https://github.com/babel/babel/issues/7627

a repo to reproduce https://github.com/andrewvmail/react-native-wallaby

Thanks you!

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      'src/**/*.js',
      'package.json',
      '!src/**/__tests__/*.js',
      '!src/**/*.test.js',
    ],

    tests: [
      'src/App.test.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'jest',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: [
          'react-native',
        ],
      }),
    },
  };
};

```

**Comment by smcenlly** [comment]
We've seen this problem previously and the issue is due to Wallaby babel compiler using the latest version of babel found in your repo while react-native requires babel 6. It's throwing the error because it's trying to use babel 6 presets in babel 7.

All you need to do is to tell wallaby babel compiler to [use babel 6](https://wallabyjs.com/docs/integration/es-next.html#babel-compiler-version):

```diff
    ...
    compilers: {
      '**/*.js': wallaby.compilers.babel({
+       babel: require('babel-core')
-       ...
      })
    },
```

Note that you may skip presets/plugins, because wallaby will use your `.babelrc` anyway.

Please let us know if you're still having problems after updating your wallaby configuration.

**Comment by andrewvmail** [comment]
@smcenlly works! thanks

**Comment by manishjain-hrbl** [comment]
I can't get this to work with below: any ideas?
```
"react": "16.6.3",
"react-native": "0.57.8",
"metro-react-native-babel-preset": "0.51.1",
"babel-eslint": "10.0.1",
"babel-jest": "23.6.0",
"babel-plugin-jsx-property-alias": "2.0.0",
```
babel.config.js
```
'react-native': {
            presets: ['module:metro-react-native-babel-preset']
        },
```
