### ISSUE TITLE
Jest mock hoisting setup with mix of ts / js codebase

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#1818]
### Issue description or question

Simplified repro at https://github.com/kwonoj/wallaby-repro-mix-js-ts-jest

I am trying to setup large codebase having TS / JS code mixed, import order is also not guaranteed - some places JS imports TS module, and some other places TS imports JS as well.

For some reason, I couldn't make jest mock hoisting works with codebases - if I don't enable `preprocessor`, it of course fails to hoist mocks. If I do try to preprocess, it runs over all js files and creates some side effect (on repro repo, it's simply becomes undefined for mocks, while actual repo have various other failures like mocking failed by mock variable name is mangled, etcs)

Is it possible to configure enable hoisting correctly? 

Thanks in advance.

Attached repo, running it as-is will fail mock hoisting. Enabling preprocessor by uncommenting will fail by other reason.

### Wallaby.js configuration file

```javascript
const fs = require('fs');
const { compilerOptions } = require('./tsconfig.json');
compilerOptions.module = 'commonjs';

const { plugins, env } = JSON.parse(fs.readFileSync('./.babelrc', 'utf-8')
  .replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/gm, ''));
const babelConfig = {
  "presets": ["react"],
  "plugins": [
    ...plugins,
    ...env.test.plugins
  ],
}

module.exports = (wallaby) => ({
  files: [
    'js/**/*.js?(x)',

    'js/**/*.ts?(x)',

    { pattern: 'js/**/*.json', instrument: false, load: true },
    { pattern: 'js/**/*.less', instrument: false, load: true },
    { pattern: 'js/**/*.sdp', instrument: false, load: true },

    //{ pattern: 'js/modern/**/?(*.)jest.js?(x)', ignore: true },
    //{ pattern: 'js/modern/**/?(*.)jest.ts?(x)', ignore: true },
    { pattern: 'js/**/?(*.)jest.*', ignore: true }
  ],

  tests: [
    'js/**/?(*.)jest.js?(x)'
  ],

  env: {
    type: 'node',
    runner: 'node',
    params: { env: 'NODE_ENV=test' }
  },

  testFramework: 'jest',

  //preprocessors: {
  //  '**/*.js?(x)': file => require('babel-core').transform(
  //    file.content,
  //    {sourceMap: true, filename: file.path, presets: ['babel-preset-jest']})
  //},

  compilers: {
    '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions),
    '**/*.js?(x)': wallaby.compilers.babel(babelConfig)
  },

  debug: true,

  workers: {
    initial: 8,
    regular: 2
  },

  setup: (w) => {
    const path = require('path');

    const jestConfig = {
      restoreMocks: true,
      clearMocks: true,
      globals: { __JEST_DEV__: true },
      moduleNameMapper: {
        '@talls(.+)': `${path.resolve(wallaby.projectCacheDir, 'js/talls')}$1`,
        '\\.(css|less)$': 'identity-obj-proxy'
      }
    };

    w.testFramework.configure(jestConfig);
  }
});

```

### Code editor or IDE name and version

Visual Studio Code v1.? Latest
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

The preprocessor is normally required for JavaScript files compiled from TypeScript files (to run `babel-preset-jest` after TypeScript compilation just like `ts-jest` is doing). But for your case looks like you don't need a preprocessor because for JavaScript files Wallaby adds the `babel-preset-jest` automatically in `wallaby.compilers.babel(...)`, and all your `jest.mock` calls are done in JavaScript files (your tests are JavaScript).

Both errors that you are observing don't see to be related to hoisting.

The error that you see with the preprocessor commented out:

> ReferenceError: mockLogger is not defined

is expected because in your Wallaby config you are only using a part of your Babel config, and are not using the `env` preset. 

Because the `env` preset is not used, this code:

```javascript
import open from './open';

const mockLogger = { warn: jest.fn() };
jest.mock('@talls/get-logger', () => ({
	...
	getGenericLogger: () => mockLogger,
}));
```

is compiled to:

```javascript
jest.mock('@talls/get-logger', () => ({
	...
	getGenericLogger: () => mockLogger,
}));
var _open = require('./open');

const mockLogger = { warn: jest.fn() };
```

And while the hoisting is done correctly, the mock's `getGenericLogger` function is called during the  `require('./open')` call, and the `mockLogger` constant defined after the call, hence the error.

If you don't remove the `env` preset from your loaded `.babelrc`, then the original code gets compiled to 

```javascript
jest.mock('@talls/get-logger', () => ({
	...
	getGenericLogger: () => mockLogger,
}));
var _open = require('./open');

var mockLogger = { warn: jest.fn() };
```

so it is `var mockLogger` vs `const mockLogger`, and because `var` is hoisted by JavaScript, the 

> ReferenceError: mockLogger is not defined

error disappears.

The following config is using your `.babelrc` as is, and allows us to move to the next error (the one that you'd get with your preprocessor uncommented):

```javascript
const { compilerOptions } = require('./tsconfig.json');
compilerOptions.module = 'commonjs';


module.exports = (wallaby) => ({
  files: [
    'js/**/*.js?(x)',

    'js/**/*.ts?(x)',

    { pattern: 'js/**/*.json', instrument: false, load: true },
    { pattern: 'js/**/*.less', instrument: false, load: true },
    { pattern: 'js/**/*.sdp', instrument: false, load: true },

    { pattern: 'js/**/?(*.)jest.*', ignore: true }
  ],

  tests: [
    'js/**/?(*.)jest.js?(x)'
  ],

  env: {
    type: 'node',
    runner: 'node',
    params: { env: 'NODE_ENV=test' }
  },

  testFramework: 'jest',

  compilers: {
    '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions),
    '**/*.js?(x)': wallaby.compilers.babel()
  },

  debug: true,

  workers: {
    initial: 8,
    regular: 2
  },

  setup: (w) => {
    const path = require('path');

    const jestConfig = {
      restoreMocks: true,
      clearMocks: true,
      globals: { __JEST_DEV__: true },
      moduleNameMapper: {
        '@talls(.+)': `${path.resolve(wallaby.projectCacheDir, 'js/talls')}$1`,
        '\\.(css|less)$': 'identity-obj-proxy'
      }
    };

    w.testFramework.configure(jestConfig);
  }
});
```

So the next error is:

> TypeError: Cannot read property 'warn' of undefined

and it shows up when calling the `open` function from the `open.js` file:

```javascript
const x = getGenericLogger();

const open = () => {
  x.warn();
  return isValid();
};
```

This error is also expected. When this code runs:

```javascript
jest.mock('@talls/get-logger', () => ({
	...
	getGenericLogger: () => mockLogger,
}));
var _open = require('./open');

var mockLogger = { warn: jest.fn() };
```

and `require('./open')` is called, in the `open.js`, `x` is captured in the program scope:

```js
const x = getGenericLogger();
```

and while the `getGenericLogger` is already mocked, because the `var mockLogger` is assigned *after* it's `undefined` value is retrieved during the `getGenericLogger: () => mockLogger,` call.

The issue is not Wallaby specific, because if you run the same code with Jest CLI, it shows the same error:

<img width="420" alt="screen shot 2018-09-07 at 12 00 14 pm" src="https://user-images.githubusercontent.com/979966/45194265-a0a77380-b295-11e8-861d-3b25e94bbdc0.png">


Hope it makes sense. If you hit any other issues you need help with, please add some repro to your repository, we are happy to have a look.

**Comment by kwonoj** [comment]
Thanks for detailed explanation and insight. I could make progress on actual codebases using your guide. Appreciate for help.
