### ISSUE TITLE
Wallaby is using Chrome Canary instead of the stable build when both are installed.

### ISSUE THREAD

**Issue by fdeslandes-wk** [wallabyjs/public#1823]
### Issue description or question
Wallaby uses Chrome Canary instead of Chrome when it is installed and env: { kind: 'chrome' } is used.

My tests were failing (using babel presets-env transformer with 'last 1 Chrome versions' as target) and worked on other environments.  When I uninstalled Chrome Canary, they started working again.

Since usual babel presets are based on browserconfigs, which does not include Chrome Canary as a Chrome version, I think it would be better if Wallaby did not use Chrome Canary when there is another Chrome installed, or should add a (kind: 'canary') option to use Chrome Canary instead of using it when the (kind: 'chrome') option is used.

### Wallaby.js configuration file
```javascript
const babelTransform = file => babel.transform(file.content, {
    sourceMap: true,
    presets: [
      ['env', {
        targets: {
          browsers: 'last 1 Chrome versions',
          uglify: true,
        },
      }],
    ],
  });
...
env: {
      kind: 'chrome',
    },
...
preprocessors: {
      'src/**/*.js': babelTransform,
      'test/**/*.js': babelTransform,
      },
    },
...
```

### Code editor or IDE name and version

Visual Studio Code v1.27.2

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
You can specify an explicit version of chrome to use by adding an extra parameter to your `env` property, `runner`. For example:

```
env: {
      kind: 'chrome',
      runner: '/Users/user/path/to/chrome'
    }
```

If you do not specify a runner, the `CHROME_PATH` env variable will be used if set; otherwise a detected Chrome Canary will be used if found; otherwise, a detected Chrome (stable) will be used. This is by design.

**Comment by bashmish** [comment]
Setting `CHROME_PATH` didn't help me

![image](https://user-images.githubusercontent.com/137844/58959303-126d0900-87a5-11e9-8fc1-fb4edb83e878.png)

`env.runner` helps though, but I can't really commit it to GIT, because this is my machine specific configuration and I want to allow other people to run wallaby on other machines.

Any clue why:
- `CHROME_PATH` is not picked up by wallaby?
- Canary is used in the first place when I have a Stable Chrome installed on my machine (basically I have both Stable and Canary)?

**Comment by ArtemGovorov** [comment]
@bashmish Not sure what's going on yet, but let's investigate.

Wallaby is using [`chrome-launcher` package](https://github.com/GoogleChrome/chrome-launcher) to find/run an installed version of Chrome. For macOS the package is using the following locations: https://github.com/GoogleChrome/chrome-launcher/blob/master/src/chrome-finder.ts#L51-L69. 

- We have been using an older version of the `chrome-launcher` package, and have just updated to the latest. I don't think much had changed in the finder algorithm, but please update your Wallaby core 
[to the latest version 1.0.694](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and run Wallaby to see if it helps.

- Try logging `CHROME_PATH` in your Wallaby config to make sure it's being passed to Wallaby from VS Code (and to VS Code from your ENV), anywhere at the top of your Wallaby config add the following code (and check the output in the Wallaby Console output channel in VS Code):

```diff
+console.log(process.env.CHROME_PATH);
```
- Try creating an empty project, `npm init && npm i chrome-launcher`, and run:
```
node
> console.log(require('chrome-launcher/dist/chrome-finder').darwin());
```
to see what Chrome instances and in what order are returned for your environment.

**Comment by bashmish** [comment]
@ArtemGovorov thanks a lot for such a detailed debugging instructions!

```js
// wallaby.js

console.log('CHROME_PATH', process.env.CHROME_PATH);
// -> [Info]  CHROME_PATH undefined
// -> [Info]  Started Wallaby.js Core v1.0.695
```

```js
// node script using chrome-launcher package

console.log(require('chrome-launcher/dist/chrome-finder').darwin());
// -> [ '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary',                                                         │webpack building...
// ->   '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' ]
```

So looks like this is not a wallaby.js bug.

Any tip where I need to define the env var in macOS Mojave so that it is picked up by VS Code? Especially taking into account that the Terminal which I open in VS Code and all other terminals have CHROME_PATH defined. I have it in `.bash_profile`, also tried `.profile`, does not help.

**Comment by smcenlly** [comment]
> Any tip where I need to define the env var in macOS Mojave so that it is picked up by VS Code?

Sorry - not sure how to do this. A quick google search didn't reveal anything obvious. It seems like a few other people have the same problem with VS Code. Perhaps create a question in [VS Code](https://github.com/microsoft/vscode/issues/new/choose) repo?

**Comment by ArtemGovorov** [comment]
> Any tip where I need to define the env var in macOS Mojave so that it is picked up by VS Code? 

The only way I could find is describe at https://stackoverflow.com/a/45637716 (skip the firs part of the answer for VS Code terminal, the relevant part starts with `As for having the $PATH available everwhere in VS Code...`).

**Comment by bashmish** [comment]
@smcenlly @ArtemGovorov thanks for suggestions. I tried all of the proposals from https://stackoverflow.com/a/45637716 and none worked for me. I have a feeling that the problem is not that it is not passed to VS Code, but maybe it gets reset at some point in the extension environment. Just a guess.

For now I found an acceptable workaround for me: I renamed `Google Chrome Canary.app` to `Google Unstable.app` so that the order in the filesystem is different, that impacted `chrome-launcher` , so now it shows

```js
console.log(require('chrome-launcher/dist/chrome-finder').darwin());
// -> [ '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
// ->   '/Applications/Google Unstable.app/Contents/MacOS/Google Chrome Canary' ]
```

so stable Chrome is used by wallaby.js.
