### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by FishOrBear** [wallabyjs/public#1834]
Visual Studio Code v1.27.2
Windows 10.
wallabyjs.wallaby-vscode-1.0.94

error log:
```
​​TypeScript diagnostics (customize using `[jest-config].globals.ts-jest.diagnostics` option):​​
​​[91merror[0m[90m TS5056: [0mCannot write file '$$ts-jest$$/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.94/projects/aca2d93ca6c4ea10/instrumented/src/B.js' because it would be overwritten by multiple input files.​​
```

I didn't use the kangaroo for a while, and this configuration worked fine before. Today, I tried to run this configuration, and an error occurred.

The attachment is my simplified configuration and code.

[wallaby_test.zip](https://github.com/wallabyjs/public/files/2414654/wallaby_test.zip)

**Comment by FishOrBear** [comment]
https://github.com/TypeStrong/ts-node/issues/433

When I remove allowJs, run it successfully.

**Comment by ArtemGovorov** [comment]
Looks like your `jest.transform` setting is not correct. In the sample project it's set to:

```
".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
```

and `.(ts|tsx)` is supposed to be a *regular expression* that filters out (TypeScript) files, however the regular expression you've specified (which looks like a glob pattern rather than a reg exp) will match anything with `ts` in its path. For example the path like `path_with_ts_in_it.any` will match.

Changing it to a valid Reg Exp should help:

```diff
    "transform": {
-     ".(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js"
+     "^.+\\.tsx?$": "<rootDir>/node_modules/ts-jest/preprocessor.js"
    },
```
