### ISSUE TITLE
Keyboad short cuts to "Run Project Tests" and "Restart" would be very helpful

### ISSUE THREAD

**Issue by cResults** [wallabyjs/public#184]
I find myself spending a good bit of time mousing to the end of a line, waiting for hover, then mouse to click to expend tool menu, then mouse to click "Run Project Test".  And now that I'm working in a body of code that requires tests that check html files, I spend a good bit of time navigating in the Solution Explorer to find the wallaby.js file to right-click and restart.

I frequently press Ctrl-S to save the file I'm working in and it kicks off karma.  It would be awesome if it also caused wallaby to "Run Project Test".  How about Ctrl-W to restart wallaby.

An alternate pattern would be Ctrl-W to "Run Project Test" and the Ctrl-W-R to restart wallaby.

Having keyboard short-cuts would help developers to better leverage wallaby's strengths to aid in the development process.

Respectfully,

cResults

**Comment by fvanwijk** [comment]
You can set keyboard shortcuts for all kind of actions in Preferences > Keymap
![shortcuts](https://cloud.githubusercontent.com/assets/963136/8575684/a40ead28-259d-11e5-9e62-ec480b952eb8.png)

**Comment by cResults** [comment]
@fvanwijk.  I'm using Visual Studio and I don't have all the options that you have, however, thanks to your response, I've found that I can map the Restart.

I believe mapping keyboard shortcuts in Visual Studio, replaces default behavior.  In my ideal world, Ctrl-S would perform the default behavior of saving the file and also tell Wallaby to "Run Project Test".

**Comment by fvanwijk** [comment]
Sorry, could have guessed that, since you are talking about Solution Explorer :)

**Comment by ArtemGovorov** [comment]
We deliberately don't prescribe any shortcuts, these days it's hard to pick something that is not mapped to some other IDE command or third-party plugin feature, so we decided to leave it up to user.

As you've already found, you [can assign](https://msdn.microsoft.com/en-us/library/5zwses53.aspx) any keyboard shortcut you like to any wallaby action. I'm not sure if combining the default save and run tests behaviour would suit everyone, I'll have a look what we can do.

I personally use smart actions quite a lot. They are keyboard friendly, so you don't have to use your mouse to quickly invoke them - just  `Ctrl + .` in VS 2013 (or `Alt + Shit + F10` in VS 2015, or `Alt + Enter` in IntelliJ) on any line.

**Comment by cResults** [comment]
It appears from the post above that in Web Storm, wallaby offers the ability to map "Run all file tests" and "Run all project tests" as well as the other methods that show up in various menus.  These do not appear to be available for mapping in Visual Studio.

![image](https://cloud.githubusercontent.com/assets/5702582/8599400/3c799d3a-262e-11e5-9b8a-1ac6cc38b247.png)

Right now I'm running wallaby side by side with karma.  karma runs in Chrome, IE, FF, and others and it offers consistent, reliable, predictable test results.  It's short coming is that I have to save the changed files to get feedback and it has to run all the tests which includes a couple second wait.  

The only reason I was pursuing the keyboard shortcut is that @ArtemGovorov stated in another post that running all project tests is the answer to not trusting wallaby.  When wallaby updates, its awesome!!!, but I'm experiencing more and more cases where it doesn't.  I'm not talking about some test off on the edge that got broke by a change I made. I'm talking about making a change to an expect statement that should cause a passing test to fail (or vice versa) and after saving files karma sees the change and wallaby does nothing.  Then "Run all file tests" brings it back up to date.  Another thing I've experienced is copying a describe block with its tests and paste it below the block.  wallaby indicate grey for each of the lines pasted. I made changes to code in the beforeEach block and hit save.  Karma reflected failing tests and wallaby did nothing.  I made changes to expect statements and hit save.  Karma reflected passing tests and wallaby did nothing, stayed grey.  I then either clicked "Run all File tests" or "Run all project tests" and wallaby updated to show passing tests.

I only suggest "Run all tests" on file save" frankly because that is what karma does and its what you recommend for trusting wallaby. If "Run all FILE tests" brings wallaby current, which it seems to do most of the time, why do we need to run all tests to trust wallaby?  karma needs to run all tests, but wallaby is smarter than karma.  wallaby appears to know file dependency trees. So instead of running all tests, why not just run a broader set of tests on *file save* than it now appears to run while typing?  

If a test file is saved, run all the tests in the test file.  If a source file is saved run all the tests of test files that depend directly or indirectly on that source file.  This is more than is necessary to be run while I'm typing, but running a broader set of tests related to a file that's being saved should help keep wallaby up-to-date without requiring an extra action from me (the end user), as saving files is already a normal part of my process. ```Ctrl + .``` to run all tests is extra work that I shouldn't have to do to trust wallaby.   Additionally, this should limit the impact on your customers with large test suites.

You're the expert in this. I suspect I'm stating what you already know or have thought of.  If running all tests is really the only way to keep wallaby fully up-to-date, then you could make it a configurable setting in the wallaby.js file, that would run all tests any time a file is saved or not.

karma currently has my trust, but wallaby has a significantly higher awesomeness potential.  I hope it reaches it potential.

**Comment by ArtemGovorov** [comment]
> It appears from the post above that in Web Storm, wallaby offers the ability to map "Run all file tests" and "Run all project tests" as well as the other methods that show up in various menus. These do not appear to be available for mapping in Visual Studio.

Correct, other actions mapping is not yet supported in VS. We have the task in our backlog.

> If a test file is saved, run all the tests in the test file.

I think it's a good idea. Have added it to the task of adding the option to run all tests when can't do an incremental run. These 2 features together should improve the situation and improve the trust.

> run all tests is extra work that I shouldn't have to do to trust wallaby

While running all/more tests on save (and generally when wallaby doesn't have enough info in the dependency graph) should help and will be implemented as an option, it will only be masking the cases like this.

I agree that running tests manually is an extra work. However, I also think that running tests that were not affected is an extra work (that makes you as a user wait longer). That's one of the things that distinguishes us from Karma and makes wallaby special. We are constantly working on improving wallaby in this area.

> When wallaby updates, its awesome!!!, but I'm experiencing more and more cases where it doesn't

So far I'm aware of only a [couple of known and reproducible cases](https://github.com/wallabyjs/public/issues/119#issuecomment-104176598) when wallaby.js doesn't produce a reliable result incrementally comparing to its (or Karma) full run. You'd help the project a lot if you could **report all such cases**, and I'd be addressing them as soon as possible. 

I know they can be hard to reproduce and report, and I really appreciate your time and effort. I am using wallaby myself and do fix all the issues that I find. But I can't find everything alone and **I can only make wallaby awesome for you and others if you report these cases and I can reproduce them**. It may be a bug in wallaby.js, specific framework integration issue, OS or IDE specific issue, specific project configuration issue, etc. -  either way I have to reproduce it in order to fix it.

Unfortunately, I can't reproduce the two issues that you have mentioned above:

>  I'm talking about making a change to an expect statement that should cause a passing test to fail (or vice versa) and after saving files karma sees the change and wallaby does nothing.

Can't reproduce in [the sample repository similar to your setup](https://github.com/wallabyjs/wallaby-requirejs-middleware). Here is what I do:

![rec](https://cloud.githubusercontent.com/assets/979966/8613199/7e9baeaa-271f-11e5-9b1d-7d6e9019770b.gif)

What am I missing?

> Another thing I've experienced is copying a describe block with its tests and paste it below the block. wallaby indicate grey for each of the lines pasted. I made changes to code in the beforeEach block and hit save.

Also can't reproduce in the sample repository. Here is what I do:

![rec](https://cloud.githubusercontent.com/assets/979966/8613323/1f5cd43a-2721-11e5-9073-98536b627931.gif)

What am I missing?

**Comment by cResults** [comment]
I reported these two issues here on a close issue rather than open up two new issues, because wanted to let you know what I was experiencing and I knew it was unlikely you would be able to reproduce them. There have been a number of times that I wished that I had a screen capturing program recording the behavior I was observing, because apart from sending you our whole solution, which I can't do, I don't know how I'd be able to give you what you need to reproduce it. 

I believe in wallaby and I greatly appreciate your responsive customer service and in the short time I've used it I observed your commitment to continually making it better.  I hope that comes through in all my posts. So I will get you reproducible steps with the issues I report whenever I'm able. 

Respectfully,

cResults

**Comment by cResults** [comment]
Here's an example of some of the behavior I've been referring to.
![image](https://cloud.githubusercontent.com/assets/5702582/8657929/8e2a4498-296e-11e5-9a70-6ad334d86ecf.png)

Notice grey marker on the line with the expect statement.  At this point, Ctrl-S has be pressed and karma has run.  This block is inside a callback being passed to the Q promise done function which is returned by the _DraftsVM.Delete method. The block also calls jasmine done function passed in via the it.

Next I added in .not to 
```
expect(_DraftCache.Remove).not.toHaveBeenCalled();
```
Wallaby responded right away and told me of the failure.  I then pressed Ctrl-S to run karma tests.  

Then I removed the .not and wallaby did nothing.  I pressed Ctrl-S to run karma and wallaby still looks like this:
![image](https://cloud.githubusercontent.com/assets/5702582/8658257/b6655928-2970-11e5-8591-614aac941c2a.png)

I've typed in blocks of code with multiple expect statements that stayed grey implying to me that they weren't executing, while saving the test file multiple times to run karma.  This is the same type of thing that I was referring to when talking about copying and pasting blocks of code and wallaby staying grey.

I don't know if this is enough for you to reproduce or not. Please let me know if you have any questions.   I'm going to be out of the office until next week, but I'll try to check in here as I have opportunity.

Thank you for great product that is continuously getting better.

**Comment by cResults** [comment]
In the image below I typed a second expect statement that I expected to fail because I haven't written the code to make it pass.  karma fails the test when I save but wallaby tells me nothing even after save.

![image](https://cloud.githubusercontent.com/assets/5702582/8658959/526c58f4-2975-11e5-9c7f-fbe58d926601.png)

**Comment by cResults** [comment]
if there is a jasmine async errors.  ie the done function doesn't get called within 5 seconds.  While karma will indicate the specific test that failed, wallaby just marks every line in the test file grey.

**Comment by ArtemGovorov** [comment]
> There have been a number of times that I wished that I had a screen capturing program recording the behaviour I was observing

Screen recordings are nice, but not really helpful to me. I'm only using them to ask users if I'm reproducing their issue correctly or there's something they do differently. Users are often able to point out that I'm missing some steps to reproduce the issue.

> because apart from sending you our whole solution, which I can't do, I don't know how I'd be able to give you what you need to reproduce it.

I know it maybe too much to ask and not always possible, but the most helpful would be if the issue was extracted and placed to the [repository with your setup](https://github.com/wallabyjs/wallaby-requirejs-middleware). Doesn't have to be your production code, just a small sample where I can reproduce it. So once you hit some issue, if you gradually try to minimise the environment required to reproduce it by commenting out other tests and possibly dependencies to see if it's still reproducible, then extracting it to a separate file etc. to eventually commit to the sample repo, it'd be the fastest way to get it fixed.

I'll try to create tests similar to yours to reproduce these 2 issues, but there's a high chance I won't be able to reproduce them, as this looks like a pretty common scenario that have been thoroughly tested. The chances are that the reason of the issue is somewhere else - possibly in config, setup, dependencies, maybe other tests, etc. Anyway, thanks a lot for the screenshots and detailed description, I'll try to reproduce and let you know how it goes.

> if there is a jasmine async errors. ie the done function doesn't get called within 5 seconds. While karma will indicate the specific test that failed, wallaby just marks every line in the test file grey.

We have a known issue when wallaby marks all lines of the test file grey in this case, but, just as Karma, wallaby in this case displays the failing test in the Failing Tests console, doesn't it?

**Comment by ArtemGovorov** [comment]
As I have been suspecting, I still can't reproduce these 2 issues. 

After creating some code similar to yours (returning a promise, calling `done` from the promise callback, adding a function spy, etc.), here is what I do:

![rec](https://cloud.githubusercontent.com/assets/979966/8665077/1245cf72-2a23-11e5-8c49-75e4e6997a00.gif)

I have pushed the source code I'm using to [the above mentioned repository](https://github.com/wallabyjs/wallaby-requirejs-middleware), feel free to try it and possibly finding and adding something missing to make it fail.

Also next time you reproduce it, please check the content of the Wallaby Console and let me know if there's something interesting there.

**Comment by cResults** [comment]
I'll take a look at this next week.

**Comment by ArtemGovorov** [comment]
> It appears from the post above that in Web Storm, wallaby offers the ability to map "Run all file tests" and "Run all project tests" as well as the other methods that show up in various menus. These do not appear to be available for mapping in Visual Studio.

We have made all wallaby actions available for mapping in v1.0.12.
