### ISSUE TITLE
​​Error: Your test suite must contain at least one test, after removing last .only in JEST

### ISSUE THREAD

**Issue by kasvtv** [wallabyjs/public#1875]
### Issue description or question
While writing some **JEST** tests, after filtering out one test by turning `it` into `it.only` and then later remove `.only`, WallabyJS gives me the error `Error: Your test suite must contain at least one test`. It then requires me to restart it or make some random changes until at some point it syncs up and runs all the tests again.

### Wallaby.js configuration file

```javascript
/* eslint-disable global-require*/

process.env.TEST_ENV = 'wallaby';

module.exports = (wallabyJS) => ({
	files: [
		'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
		'jest.setup.js',
		'!src/**/*.test.js?(x)'
	],

	tests: ['src/**/*.test.js?(x)'],

	filesWithNoCoverageCalculated: [
		'src/entry.js'
	],

	env: {
		type: 'node',
		runner: 'node'
	},

	compilers: {
		'**/*.js?(x)': wallabyJS.compilers.babel()
	},

	testFramework: 'jest',

	delays: {
		run: 500
	}
});```

### Code editor or IDE name and version

Visual Studio Code v1.28.1
### OS name and version

Windows 10

**Comment by smcenlly** [comment]
Do you have this problem every time or is it intermittent? We've been unable to reproduce the issue in our sample projects. If you can reliably reproduce the problem, can you please provide a sample repo?

**Comment by Almenit** [comment]
I have the same issue. It's hard to see a pattern. More information in https://github.com/wallabyjs/public/issues/1642

**Comment by smcenlly** [comment]
@Almenit - Thanks for linking the issues. We'll need more information in order to keep trouble shooting this issue. 

@kasvtv - Can you please provide us with a sample repo of your project's structure (removing any application code you can't share) so that we can analyze your package.json, jest setup, use of babel, etc?

**Comment by smcenlly** [comment]
Hi @Almenit and @kasvtv - I wanted to let you both know that we have identified the cause of this issue. The problem was caused by a combination of Windows file system changed events and the way that VS Code flushes content to disk after write.

This has now been fixed. Please download the latest version of Wallaby for VS Code, v1.0.121. This will also download the latest version of Wallaby core, which is also necessary.
