### ISSUE TITLE
Error: spawn node ENOENT​​

### ISSUE THREAD

**Issue by selfrefactor** [wallabyjs/public#1877]
### Issue description or question
This is what Wallaby console output is:
```
​​[Error]     at onErrorNT (internal/child_process.js:379:16)
​​[Error]     at process._tickCallback (internal/process/next_tick.js:152:19)​​
​​[Error] Error: spawn node ENOENT​​
```

It goes in indefinite loop with these errors.

### Wallaby.js configuration file

```javascript
// paste your config here
// https://github.com/selfrefactor/rambdax/blob/master/wallaby.js
module.exports = function (wallaby){
  return {
    files: [
      'rambdax.js',
      'package.json',
      'src/**/*.js',
      '!src/**/*.spec.js'
    ],
    tests: [
      'src/**/*.spec.js'
    ],
    env: {
      type: 'node',
      kind:'chrome',
      runner: 'node'
    },
    projectCacheDir: 'node_modules',
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel()
    },
    workers: {
      reload: true,
      initial: 4,
      regular: 2
    },
    delays: {
      run: 1000
    },
    testFramework: 'jest',
    debug:true
  }
}
```

### Code editor or IDE name and version

Visual Studio Code latest
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux Ubuntu18.04

**Comment by ArtemGovorov** [comment]
The issue has the same nature as your previous one. You have runner path/command specified as `node`, but there's no `node` in your PATH (hence the error), so you'll either need

- to specify the same path in your `env.runner` as in your VS Code `wallaby.node` setting,
- or to configure nvm to have a default version of node (so that `node` command gets resolved to your nvm version of node),
- or, which is the simplest option, [do not use the `runner` in your Wallaby config](https://wallabyjs.com/docs/integration/node.html#node-version) (so it'll use the same node that it's running Wallaby with for your tests):

```diff
    env: {
      type: 'node',
-      kind:'chrome',
-      runner: 'node'
    },
```
