### ISSUE TITLE
Something is wrong with imports with latest vscode 1.28

### ISSUE THREAD

**Issue by lucax88x** [wallabyjs/public#1878]
### Issue description or question
 Since last vscode upgrade, the ts auto-import feature it automatically uses "absolute" paths instead of "relative" paths 

```typescript
import { ITodosState } from 'src/states/todos';
```

instead of

```typescript
import { ITodosState } from '../states/todos';
```

wallaby complains about that and cannot resolve this path

![image](https://user-images.githubusercontent.com/6294464/47088255-531c1000-d21e-11e8-9e7d-54d498287170.png)

I'm stuck because I do not know where I should give the possibility to wallaby to find modules in the "absolute" way.. must be something regarding the rootDir prop in the tsconfig?

you can find a repo [here](https://github.com/lucax88x/react-playground)

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
    const testPathExp = 'src/**/*.spec.ts?(x)';
  
    return {
      files: [
        'tsconfig.json',
        'tsconfig.test.json',
        'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
        {pattern: 'config/**/*.js', instrument: false},
        `!${testPathExp}`
      ],
  
      tests: [testPathExp],
  
      env: {
        runner: 'node',
        type: 'node'
      },
      compilers: {
        '**/*.js?(x)': wallaby.compilers.babel({
          babel: require('babel-core'),
          presets: ['react-app']
        })
      },
      preprocessors: {
        '**/*.js?(x)': file =>
          require('babel-core').transform(file.content, {
            compact: false,
            filename: file.path,
            presets: ['react-app'],
            sourceMap: true
          })
      },
  
      setup: () => {
        const jestConfig = require('./package').jest;
        Object.keys(jestConfig.transform || {}).forEach(
          k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
        );
        delete jestConfig.testEnvironment;
        wallaby.testFramework.configure(jestConfig);
      },
  
      testFramework: 'jest'
    };
  };
```

###  Code editor or IDE name and version

Visual Studio Code v1.28

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo.

The issue is not Wallaby specific, it's your Jest config's issue. If you run `yarn test`, you'll get the exact same error.

While TypeScript provides dev time experience, it doesn't do any runtime module resolutions or changes to the way modules are imported, so the compiled JavaScript code (that Jest will need to run) will still contain those absolute `src/actions/todos` imports. 

Now Jest in runtime sees the import, but it has no idea how to resolve it. To give it a hint, you may either use the [`moduleNameMapper` setting](https://jestjs.io/docs/en/configuration.html#modulenamemapper-object-string-string) or the [`moduleDirectories` setting](https://jestjs.io/docs/en/configuration.html#moduledirectories-array-string).

For example, with the `moduleDirectories` setting below, Jest will now that it needs to use your <rootDir> as a modules folder, and will try to resolve `"<rootDir>/src/actions/todos` when requested an absolute path like `src/actions/todos`:

```diff
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}",
      "!**/*.d.ts"
    ],
+   "moduleDirectories": ["node_modules", "<rootDir>"],
    "setupFiles": [
      "<rootDir>/config/polyfills.js"
    ],
```
