### ISSUE TITLE
Running tests cause Runtime error: [object ErrorEvent]​​

### ISSUE THREAD

**Issue by fuzzybair** [wallabyjs/public#1887]
### Issue description or question
Thanks for your help with [https://github.com/wallabyjs/public/issues/1886](url). It got some of my tests running, however I am now getting the following error.

​​​​​[Info]​​​​​ Fri, 26 Oct 2018 02:48:14 GMT wallaby:workers Sandbox (active) [0w14u] error: [object ErrorEvent]
​​[Error] Runtime error: [object ErrorEvent]​​
​​[Error] at :​​
​​​​​[Info]​​​​​ Fri, 26 Oct 2018 02:48:14 GMT wallaby:workers Failed to map the stack to user code, entry message: [object ErrorEvent], stack: [object ErrorEvent]
​​​​​[Info]​​​​​ at :

I am not allowed to share company code and I am unable to reproduce it in a simple application due to the lack of information in the above error message. Do you know what would cause this error? Is there a way to debug wallabyjs to see what "ErrorEvent" truly is?

NOTE: All tests are passing with Karma.

### Wallaby.js configuration file

see [https://github.com/wallabyjs/public/issues/1886](url) for an example.

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

Windows 10 (1709)

**Comment by ArtemGovorov** [comment]
The error is what we get from Angular/Zone.js and is not specific to Wallaby (under some circumstances, you may also reproduce it with Karma too). Unfortunately there's no easy way to debug it, however I may suggest something that may get rid of the error.

it is likely that the error is caused by some dependencies/shared state between your tests. Because Karma runs your specs sequentially, and Wallaby runs them in parallel chunks, Wallaby may reveal those types of issues in the tests (that are unfortunately are reported with this cryptic message from Angular).

What you can do to verify my assumption (and hopefully get rid of the error) is to configure Wallaby to run your specs sequentially (just like Karma) by [setting `workers` count to `1`](https://wallabyjs.com/docs/config/workers.html) in your Wallaby config:

```diff
 module.exports = function () {
   return {
     ...

+     workers: {
+       initial: 1,
+       regular: 1
+     }
   };
 };
```

If it doesn't fix the error, please check the output from [Wallaby Console](https://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting) to see if there any other errors reported there (like failure to load some resources).

**Comment by fuzzybair** [comment]
I am getting two errors 
ENOENT: no such file or directory, open '...\instrumented\fs.js'
ENOENT: no such file or directory, open '...\instrumented\path.js'
I am working on trying to reproduce it in a simple app But was wondering if you knew what it was. I think it may be related to CesiumJS because all tests are working except for that section.

**Comment by ArtemGovorov** [comment]
From the error message, it looks like some of your tests are using node `path` are `fs` modules (that are not available in browser). If there are some e2e tests (like Protractor ones) in the `'Content/**/*.spec.ts'` pattern, please exclude them in your `tests` list in Wallaby config.

**Comment by fuzzybair** [comment]
Thanks for all your help, I now have all the tests running some are failing but I think it is the result of an unstable test. with what i have i can set up a demonstration with my boss and get a set of licences for our team. He was open to it if i could show it working.

**Comment by ThatSpaceGuy** [comment]
Something that I was able to do, when I ran into this ([object ErrorEvent] in wallaby, yet tests pass in Karma), was to put a `try / catch` around the code that I suspected was throwing the error (not in the spec file, but in the component itself).  This allowed me to see what error was being thrown, so that I could address it.
