### ISSUE TITLE
Need help setting up React / Babel / Typescript / Snapshots

### ISSUE THREAD

**Issue by reywright** [wallabyjs/public#1888]
### Issue description or question

I already had set this up, but we introduced Typescript which broke the entire thing. I really would like to reinstate, just need help with the configuration

### Wallaby.js configuration file
https://github.com/reywright/wallaby-troubleshoot

All the relevant code is here. yarn install, then run yarn test to run the tests.

Visual Studio Code v1.28.2
OSX Mojave

**Comment by ArtemGovorov** [comment]
I have sent you the [pull request with the changes](https://github.com/reywright/wallaby-troubleshoot/pull/1). The major issue was that Typescript files were missing in your [`files` list](https://wallabyjs.com/docs/config/files.html). Also for your jest.mock calls to be correctly processed, the [documented preprocessor](https://wallabyjs.com/docs/integration/jest.html#jest-with-typescript-and-jestmock-calls) needed to be added.

While the config should work for you now, note that the version of Jest that you are using had issues with source maps, so you may notice that because of that Wallaby is displaying errors not on lines where the errors actually happen. To fix the issue, you may need to migrate to a more recent version of Jest.
