### ISSUE TITLE
create-react-app-ts testing fails with "Emit skipped" from ts-jest

### ISSUE THREAD

**Issue by furkle** [wallabyjs/public#1892]
### Issue description or question
I have copied the newest CRA-ts wallaby configuration I can find (https://github.com/lucax88x/react-playground/pull/1/commits/8d1107c986286d8a7e4121afb37b791de7def2b9). This seems like it almost works, but the setup file in which I configure Enzyme seems to produce a very vague error message from ts-jest (`TypeError: src\setupTests.ts: Emit skipped​​`).

### Wallaby.js configuration file

```javascript
// tslint:disable
module.exports = function(wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/setupTests.ts',
      'passages/**/*.+(js|jsx|ts|tsx)',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      {pattern: 'config/**/*.js', instrument: false},
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      runner: 'node',
      type: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
      })
    },
    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          compact: false,
          filename: file.path,
          presets: ['react-app'],
          sourceMap: true
        })
    },

    setup: () => {
      const jestConfig = require('./package.json').jest;
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.28.2

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
We cannot reproduce the issue by adding/configuring `setupTests.ts` to [react-playground](https://github.com/lucax88x/react-playground) and loading enzyme. Can you please provide either your `setupTests.ts` or a sample repo so we can see the problem first hand?

**Comment by smcenlly** [comment]
Thanks for providing the sample repo, this was a big help in diagnosing the issue. I've created a pull request with an updated wallaby.js configuration for you [here](https://github.com/furkleindustries/accelerator-core/pull/11). You can see the same thing below:

```diff
// tslint:disable
module.exports = function (wallaby) {
  const testPathExp = 'src/**/*.test.ts?(x)';
+ const compilerOptions = Object.assign(
+   require('./tsconfig.json').compilerOptions,
+   require('./tsconfig.test.json').compilerOptions);

  return {
    files: [
      'tsconfig.json',
      'tsconfig.test.json',
      'src/setupTests.ts',
      'passages/**/*.+(js|jsx|ts|tsx)',
      'src/**/*.+(js|jsx|ts|tsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      {pattern: 'config/**/*.js', instrument: false},
      `!${testPathExp}`
    ],

    tests: [testPathExp],

    env: {
      runner: 'node',
      type: 'node'
    },
    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({
        babel: require('babel-core'),
        presets: ['react-app']
-     })
+     }),
+     '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions)
    },
    preprocessors: {
      '**/*.js?(x)': file =>
        require('babel-core').transform(file.content, {
          compact: false,
          filename: file.path,
          presets: ['react-app'],
          sourceMap: true
        })
    },

    setup: () => {
      const jestConfig = require('./package.json').jest;
      Object.keys(jestConfig.transform || {}).forEach(
        k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]
      );
      delete jestConfig.testEnvironment;
+     jestConfig.setupTestFrameworkScriptFile = jestConfig.setupTestFrameworkScriptFile.replace('.ts', '.js');
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

Your issue was a combination of different settings and configuration so I'll document them here for posterity.

1. Unless configured otherwise, Wallaby will load project `tsconfig.json` files and directory overrides [the same way that TypeScript does](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html). Testing with `ts-Jest` provides a setting to provide the `tsconfig.json` file, in this case, `tsconfig.test.json`. Without this settings, wallaby was compiling using `"compilerOptions.module": "esnext"` instead of `"compilerOptions.module": "commonjs"`. I've updated your wallaby configuration to apply the tsconfig settings the same way that jest does.

2. The various TypeScript settings that you are using combined together perfectly to stop wallaby working for you.

### tsconfg.json compilerOptions.allowJs: true
Wallaby compiles all TypeScript files using the TypeScript compiler and then applies instrumentation/logging logic to display output to your editor. In this case, Wallaby was compiling your files to Javascript and then `ts-jest` attempted to do the same, except this time it attempted to compile the Javascript files generated by wallaby and was unable to overwrite them. If you do not plan to use any Javascript files in your project, setting `allowJs` compilation option to `false` would also fix your problem.

### tsconfg.json excludes
The excludes in your `tsconfig.json` file were also causing a problem between wallaby and jest because of inconsistency between the existence of `setupTests.ts` and `setupTests.js` file paths. If you removed `"src/setupTests.ts"` from your excludes, everything would work correctly. Equally you could also fix the problem by adding another exclude for the Javascript file: `"src/setupTests.js"`.

**Comment by furkle** [comment]
Perfect, thanks so much! This is incredibly helpful and I really appreciate you taking the time to fix and document this.
