### ISSUE TITLE
`Error running 'wallaby-server': Could not initialize class com.wallaby.javascript.i$a`

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#1899]
On run...

```
20:31	Error running 'wallaby-server': com.intellij.util.ui.EmptyIcon.create(I)Ljavax/swing/Icon;

20:31	Error running 'wallaby-server': Could not initialize class com.wallaby.javascript.i$a

20:31	Error running 'wallaby-server': Could not initialize class com.wallaby.javascript.i$a
```

```
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.3975.18, built on October 24, 2018
IntelliJ IDEA EAP User
Expiration date: November 23, 2018
JRE: 1.8.0_152-release-1343-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

**Comment by vjpr** [comment]
`v1.0.117`

The update doesn't show up in the plugins.

**Comment by vjpr** [comment]
![screen shot 2018-11-02 at 1 47 51 am](https://user-images.githubusercontent.com/281413/47887736-54198800-de41-11e8-8348-ddd66cea5ffe.png)

**Comment by ArtemGovorov** [comment]
It may happen if your license had expired. Please check your license expiration date (`Help - Manage Wallaby License`).

**Comment by vjpr** [comment]
![screen shot 2018-11-02 at 1 48 40 am](https://user-images.githubusercontent.com/281413/47887768-757a7400-de41-11e8-9041-395f7869a67f.png)

**Comment by ArtemGovorov** [comment]
Wallaby plugin is using its own mechanism for updates and shows up its own update prompt when an update for the plugin is available (unless the Notifications from Wallaby updates had been muted):

<img width="790" alt="screen shot 2018-11-02 at 10 51 05 am" src="https://user-images.githubusercontent.com/979966/47887868-4f7ac100-de8d-11e8-8b11-d2a95933d27e.png">

Either way, installing the latest from https://wallabyjs.com/download/ should help.

**Comment by vjpr** [comment]
Notifications are enabled.

**Comment by ArtemGovorov** [comment]
Thanks for checking. We have figured out what the issue is. IntelliJ EAP had introduced some breaking changes that prevent the previous version of the plugin (1.0.117) to start. And the plugin update check and notification is triggered *after* plugin starts (to avoid bothering you with any notifications if the plugin is not being used). 

We'll investigate how to improve the experience in these cases in future versions, but for now you need to download the latest plugin version from  https://wallabyjs.com/download/ and install it from disk.
