### ISSUE TITLE
Degree of parallelism?

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#192]
Just how parallel are the tests? One worker per file? per suite? per test?

**Comment by ArtemGovorov** [comment]
Short answer is one worker per test file.

There's also an algorithm that distributes test files between workers based on the size of each test file, so if there're more test files than [configured/available workers](http://wallabyjs.com/docs/config/workers.html), then each worker executes potentially more than one test files.

Parallel execution mostly takes place during the initial run, further (incremental) runs rarely need multiple workers. Incremental test runs often execute just one affected test or few tests, sometimes full test file, if required - a few affected test files in parallel. It depends on your code changes and dependencies between the code and covering tests.

Either way, these are implementation details that should not be influencing the structure of tests, because they may change. For example, we are planning to make some further improvements in the test distribution algorithm (such as considering each suite execution time to distribute tests more efficiently)

**Comment by DenisGorbachev** [comment]
Thank you for answering.
