### ISSUE TITLE
Failed to map the stack to user code

### ISSUE THREAD

**Issue by DenisGorbachev** [wallabyjs/public#193]
Reproduction steps:

1. .. follow #191...
1. `git checkout 8ebf080aa98febeaf825cfb9c01ee8700de9819a`

Environment: same as in #191 

The error doesn't originate in my code, that's correct, but shouldn't Wallaby display the error somewhere near `job.run` (in `test/Job/Save/SaveUsers.coffee`)?

**Comment by ArtemGovorov** [comment]
I'm getting this error:

<img width="1070" alt="screen shot 2015-07-13 at 8 31 18 pm" src="https://cloud.githubusercontent.com/assets/979966/8647760/28c0dce0-299e-11e5-9c35-049331bb0edf.png">

Wallaby finds error lines in the stack and in this case it doesn't display anything near `job.run` because there is nothing in the user code that it can highlight as the error. If some caught error doesn't have anything from your code in its stack, all wallaby can do is to display up to what point the code was executed. Normally the stack is preserved, but in this case it looks like `knex` doesn't preserve the stack originating from your test file, even with `longStackTraces` for promises.

**Comment by ArtemGovorov** [comment]
For example:

<img width="440" alt="screen shot 2015-07-13 at 8 53 16 pm" src="https://cloud.githubusercontent.com/assets/979966/8648112/4ec65804-29a1-11e5-8ddb-55f5843c3d3c.png">

As you can see even though the error originates from some code that can potentially be a third-party code and through the chain of promises, it is still correctly mapped in the test, because the error stack is preserved as it should be. 

Note that I'm not using `done` callback because if you return a promise from a test function, mocha understands it and makes the test passed or failed based on the promise result. I have noticed that you're not using this mocha feature in your tests, but perhaps you have a reason for that.

**Comment by DenisGorbachev** [comment]
Can't say for sure, but most probably, `knex` didn't truncate the stack traces intentionally. Most probably, they're just "lost" on the way. Is some setting that controls how stack traces are preserved? (anything like `longStackTraces`?)

---

Just for reference, here's how to reproduce the original case (sorry, I've hardcoded the connection string :) )

* Install PostgreSQL 9.4
* Create a user `foreach` with password `foreach`
* Create a `foreach_local` database
* Give `foreach` user access to `foreach_local` database

**Comment by DenisGorbachev** [comment]
Just found `Error.stackTraceLimit` and `--stack-trace-limit`. Anything else?

**Comment by ArtemGovorov** [comment]
I haven't used PostgreSQL much, so I'm a bit stuck trying to make it work. Is there a psql I can paste to create required environment?

`Error.stackTraceLimit` shouldn't be an issue. 

Anyway, from the symptoms it looks like your original error has the same reason for not displaying the error next to code and I think I found the reason. From the stack trace I have:
```
    at Pool._destroyPool (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/node_modules/pool2/lib/pool.js:487:16)
    at Pool.<anonymous> (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/node_modules/pool2/lib/pool.js:410:18)
    at Pool.<anonymous> (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/node_modules/pool2/lib/pool.js:444:17)
From previous event:
    at Client.acquireConnection (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/lib/client.js:200:12)
    at /Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/lib/runner.js:138:49
From previous event:
    at Runner.ensureConnection (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/lib/runner.js:137:26)
    at Runner.run (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/lib/runner.js:30:31)
    at Raw.Target.then (/Users/artemgovorov/Documents/WebstormProjects/backend-freshdesk/node_modules/knex/lib/interface.js:27:43)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

it looks like something (probably `knex` or one the modules it's using, judjing by the rest of the stack trace) schedules something in `setImmediate` in a way that the error in the callback is not handled to reject the promise. So something similar to this is happening:

<img width="374" alt="screen shot 2015-07-13 at 9 58 08 pm" src="https://cloud.githubusercontent.com/assets/979966/8649115/4e0fed18-29aa-11e5-82ef-7de477189ff7.png">

While ideally the code should be like this to preserve the stack:

<img width="384" alt="screen shot 2015-07-13 at 10 00 09 pm" src="https://cloud.githubusercontent.com/assets/979966/8649145/928a74a4-29aa-11e5-9cf7-37637c50ad91.png">

If that's the case, there's not much wallaby can do about it.

**Comment by DenisGorbachev** [comment]
Artem, thank you for great support.

Normally, I would have opened an issue on `knex`, but it looks like even more important issues are left unanswered in its tracker, so let's consider this case closed.
