### ISSUE TITLE
Don't see linked module

### ISSUE THREAD

**Issue by kirit0s** [wallabyjs/public#1938]
### Issue description or question
Wallaby don't see symlinked module ([repo](https://github.com/kirit0s/wallaby-link-shared-module)).

Workflow: I have shared module and when I write tests in app, I want to see execution in shared module (like if shared module inside node_modules without symlink and this folder exist in wallaby config).

![wallaby](https://user-images.githubusercontent.com/14249148/49951900-131a9600-ff0c-11e8-8458-1089a9e609e8.PNG)

### Code editor or IDE name and version

Visual Studio Code v1.30.0

### OS name and version

Windows 10 x64 (1803)

**Comment by smcenlly** [comment]
Thanks for the sample repo! I've created a [pull request](https://github.com/kirit0s/wallaby-link-shared-module/pull/1) to get this working for you.

The reason you're not seeing coverage is because when Wallaby runs your tests with `ava`, it's reading the contents of the symlinked files from disk instead of the files that Wallaby has instrumented to get code coverage.

What you need to do is update your wallaby configuration to resolve `shared` from wallaby's instrumented files. I'm not especially familiar with `ava` and whether it has built-in support for module mapping. If it does, I would recommend using its module mapping settings. If not, you can do what I've done to get this working.

1. Add `module-alias` npm package as a dev dependency, `npm install module-alias --save-dev`.
2. Update your wallaby configuration to ignore your `node_modules/shared` symlink folder and configure a wallaby `setup` function that configures your module mapping. See the updated wallaby configuration below:

```diff
module.exports = () => ({
- files: ['app/src/**/*.js', 'shared/src/**/*.js'],
+ files: ['app/src/**/*.js', 'shared/src/**/*.js', '!node_modules/shared/**'],
  tests: ['app/tests/**/*.test.js'],
  env: {
    type: 'node',
    runner: 'node',
  },
  testFramework: 'ava',
+ setup: function(wallaby) {
+   const path = require('path');
+   const moduleAlias = require('module-alias')
+
+   moduleAlias.addAlias('shared', path.join(wallaby.projectCacheDir, 'shared/src/app.js'));
+ }
});
```
