### ISSUE TITLE
Cannot find module wallaby.js in monorepo

### ISSUE THREAD

**Issue by unional** [wallabyjs/public#1941]
### Issue description or question
I'm using vscode and I try to get wallaby working in monorepo but get output error:

`Cannot find module '/<path to project root>/wallaby.js'​​`

I put `wallaby.conf.js` in each package under `packages/project-a` and `packages/project-b`.

It seems like wallaby can't pick them up.

I looked at the issues and it seems like many people can do it, can't figure out what I'm missing. 🙏 

### Wallaby.js configuration file

```javascript
{
  "files": ["src/**/*.ts", "!src/**/*.spec.ts"],
  "tests": ["src/**/*.spec.ts"],
  "env": { "type": "node" },
  "testFramework": "jest"
}
```

### Code editor or IDE name and version

Visual Studio Code v1.30

### OS name and version

OSX: 10.13.6

**Comment by smcenlly** [comment]
Wallaby can only have 1 configuration file for your open folder/workspace and the configuration file must be in the open folder/workspace root.

If you can't get it working, please provide us with a simple sample repo, we'd be happy to take a look.

**Comment by ArtemGovorov** [comment]
I'd also suggest trying to use Wallaby Select Config File command in VS Code, as the error message points to `wallaby.js`, while you mentioned `wallaby.conf.js`, so it may be an issue related to the config rename.

**Comment by ArtemGovorov** [comment]
Could you please share an example repo? We'll take a look to see how to support the scenario.

**Comment by unional** [comment]
While not a complete repo that needs two wallaby config, but here is an example:
https://github.com/unional/uni-cli

The folder structure is just very common `lerna` monorepo project.

We probably don't want wallaby to run all tests in all projects for each key stroke. 🌷

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. I have created an empty wallaby config file under `packages/uni-cli/wallaby.js`, ran VS Code `Wallaby.js Select Configuration File` command to select the config, started Wallaby and Wallaby picks the config up correctly (because it's showing the error about its incorrect structure):

<img width="897" alt="screen shot 2018-12-19 at 6 00 22 pm" src="https://user-images.githubusercontent.com/979966/50206734-10122080-03b8-11e9-8d0b-7d017c2c6458.png">

What am I missing?

> We probably don't want wallaby to run all tests in all projects for each key stroke. 

Actually Wallaby wouldn't do it anyway as it only runs tests related to a specific code change, so unless a change affects multiple projects, only few will run.

**Comment by unional** [comment]
Thanks. I'll give it a try. Once I get a good solution, I'll share it here. 🌷
