### ISSUE TITLE
Setup code to only run once

### ISSUE THREAD

**Issue by bugs181** [wallabyjs/public#1946]
### Wallaby.js configuration file

```
module.exports = function(wallaby) {
  var path = require('path')
  process.env.NODE_PATH = path.join(wallaby.localProjectDir, 'node_modules')

  return {
    files: [
      'code.js',
      'dbCommands.js'',
    ],

    tests: [
      'test/**.js',
    ],

    env: {
      type: 'node',
      runner: 'node',
    },

    testFramework: 'mocha',
    maxConsoleMessagesPerTest: 10000,
    slowTestThreshold: 30 * 1000, // 30 Seconds slow test

    setup: function(wallaby) {
      var mocha = wallaby.testFramework
      mocha.slowTestThreshold = 30 * 1000 // The above wasn't working?
    },
  }
}
```

### Code editor or IDE name and version
Visual Studio Code Version 1.30.1

### OS name and version
macOS Mojave 10.14 (18A391)

### Problem
Given the following example code, I cannot figure out how to create a `setup` function which is run ONLY once, while changing code in the rest of the file. I've tried to use a separate `describe` function, a `before` function placed in various places, and even the `setup()` function inside the `wallaby.js` config file. Nothing has worked so far. The `setup()` function inside wallaby config file would also be undesirable as each test I have, needs to have different setup code.

This setup function 'sets up' a temporary database and pushes a few items to it. The other code validates that the database is working. Logging the database, I can see that for every code change, new items are appended to the database which is undesirable.

### Example attempt:
```
before(function() {
  console.log('only run once')
})

describe('setup', function() {
  // Runs multiple times
})

describe('something', function() {
  it('should not re-run setup', function(done) {
    // Changes done here affect other describes, before hooks, etc
  })
})
```

Any help would be much appreciated.

**Comment by ArtemGovorov** [comment]
The `setup` function in wallaby config runs every time before (re)running your tests (all or affected only). When the test file runs, it's up to Mocha (how) to call various hooks and in what order (Wallaby doesn't affect Mocha's behaviour in this regard).

If you'd like to run something only once (per node test process), you may do something like:

```js
    setup: function(wallaby) {
      ...
      if (!global._ranSetup) { // or any global variable name you like
        ...
        global._ranSetup = true
      }
    },
```

You may also do a similar thing anywhere else in your code. 

Also, I'm not sure if the question/issue is really Wallaby specific, because Wallaby simply re-runs your Mocha tests (as if you would run them manually on changes), so the mechanism of making something to only run once (per process or per something else) is pretty much the same as without using Wallaby.

Either way, let me know if the solution above addresses your question. If it doesn't, please share the way how your setup code works outside Wallaby (in plain Mocha in watch mode for example), we are happy to take a look and help configuring Wallaby the same way.
