### ISSUE TITLE
Postprocessor run failure: Failed to parse...

### ISSUE THREAD

**Issue by paul-go** [wallabyjs/public#1947]
### Issue description or question

Cannot get Wallaby to run, due to parsing JS errors.
Fresh install, have never used Wallaby before.
The file that is failing to parse can be found at:
https://github.com/paul-go/Truth/blob/master/Core/System/VersionStamp.ts

The specific error I'm getting is:
```
[Error] ​​Postprocessor run failure: Failed to parse Core/System/VersionStamp.js, SyntaxError: Unsyntactic break (38:16)​​
[Error] ​​    at process.internalTickCallback (internal/process/next_tick.js:70:11)​​
```

However, commenting out the offending line caused a stream of other parsing errors.

### Wallaby.js configuration file

```javascript

module.exports = function(wallaby)
{
	return {
		files: [
			"Core/**/*.ts"
		],

		tests: [
			"CoreTests/**/*test.ts"
		],
		
		compilers: {
			"**/*.ts": wallaby.compilers.typeScript({ })
      	},
		
		env: {
			type: "node",
			runner: "node"
		},
		
		testFramework: "jest"
	}
}

```

### Code editor or IDE name and version

Visual Studio Code v1.3
### OS name and version

OSX 10.13.6

**Comment by smcenlly** [comment]
Thanks for the repo. There were three separate problems that needed to be fixed:

1) Your project configuration is using TypeScript 2.0.7. You need to add a dev dependency or else configure wallaby to use a more recent version.
2) Your wallaby configuration wasn't referencing all required files. I've provided a working version below.
3) You have a test that is running forever (both in wallaby and jest). This causes wallaby to never return a result because the test run never finishes.

**Problem 1 - TypeScript Version**

By default, wallaby.js is using your project local TypeScript compiler version (from the project `node_modules/typescript`), if there’s no local version, then wallaby falls back to the embedded TypeScript compiler version which is v2.0.7.

In your case, there is no project level TypeScript, and your `VersionStamp.ts` file uses `Numeric Separators` which were introduced in TypeScript 2.7.

The quickest fix for you is to add TypeScript as a dev dependency so that it exists in your `node_modules` folder. Alternatively, you can use a different version, by passing the TypeScript compiler via typescript options property. For example, the following config will make wallaby.js use TypeScript compiler from your installed node modules (which is the default option when you don’t specify the setting at all):

```javascript
  module.exports = function (w) {

    return {
      files: [
        'src/**/*.ts'
      ],

      tests: [
        'test/**/*Spec.ts'
      ],

      compilers: {
        '**/*.ts?(x)': w.compilers.typeScript({
            typescript: require('typescript')
        })
      }
    };
  };
```

**Problem 2 - Wallaby Configuration**

Your wallaby configuration was missing a few dependencies that are required by your tests. I updated your configuration to include all typescript files in CoreTests **except** those that are suffixed with `.test.ts`

```javascript
module.exports = function(wallaby)
{
  return {
    files: [
      "Core/**/*.ts",
      "CoreTests/**/*.ts",
      "!CoreTests/**/*test.ts"
    ],
    tests: [
      "CoreTests/**/*test.ts"
    ],
    env: {
      type: "node",
      runner: "node"
    },
    testFramework: "jest",
  }
}
```

**Problem 3 - Test that never finishes**

I had to comment out `Fsm.test.ts` as it seemed that `new X.Fsm()` was taking forever to execute. You can also see this when you run your tests in jest from the cli.

**Comment by paul-go** [comment]
Thanks for taking a look at this. (And sorry for the busted project, we're still pretty early). You might want to consider emitting the TypeScript version number being used to the console when a parse error is encountered. It really looks like a Wallaby bug otherwise.

FYI I've added a Wallaby config file to the root of our repo ... consider that a nice little free advertisement :-)
