### ISSUE TITLE
Markers in Sublime text light themes  always looks as black squares

### ISSUE THREAD

**Issue by lamartire** [wallabyjs/public#1952]
### Issue description or question

Alabaster theme (tonsky/sublime-scheme-alabaster#2):

![image](https://user-images.githubusercontent.com/13414205/50624609-0699c400-0f33-11e9-8294-67cd22286d4b.png)

[Screencast with reproducing](https://www.useloom.com/share/cd4e9487701f4cbdbbf55f3a200156ec).

This problem stable reproducing in other light themes. Just install ColorSublime package and switch some themes. The most of light themes will have black squares instead of test statuses. In some themes it resolves after relaunch wallaby, but in some it is not helpful.

### Wallaby.js configuration file

Independant.

### Code editor or IDE name and version

Sublime Text v3 build 3176

### OS name and version

OSX 10.14.2

**Comment by ArtemGovorov** [comment]
This is an (kind of) expected behavior. Some Sublime themes make gutter icons monochrome (as you may see on your screenshot - not just Wallaby gutter icons, some other too).  In Wallaby package these icons are simple colored PNGs (as you may check in the package `img/dots` folder), so it must be something that themes are setting to remove colors.

**Comment by tonsky** [comment]
Seems like wallaby (or sublime) multiplies png color by foreground color. Any scheme with foreground: #000 renders wallaby icons as monochrome. If you make foreground: #999 colors become distinguashable. foreground: #FFF makes them their original color.

Please re-check that you are using correct blending mode.

On the screenshot above there are also gitgutter icons that use colors from color scheme: markup.inserted, markup.deleted, markup.changed. They are black because no color is provided in scheme (different reason).

**Comment by tonsky** [comment]
Well GitGutter for example manages to draw colored icons still. Might worth a look

<img width="124" alt="screenshot 2019-01-06 at 17 31 48" src="https://user-images.githubusercontent.com/285292/50737347-07ec1a80-11d9-11e9-8fd2-650cd1a0df9a.png">

**Comment by ArtemGovorov** [comment]
> Well GitGutter for example manages to draw colored icons still.

Looks like it works because [you've set `foreground`](https://github.com/tonsky/sublime-scheme-alabaster/blob/master/Alabaster%20BG.sublime-color-scheme#L74-L84) for scopes [they're using for icons](http://jisaacks.github.io/GitGutter/coloring/). Wallaby icons will also be colored if you add the following rule to the theme:

```diff
+        {"scope": "wallaby",
+         "foreground": "#fff"}
```

Adding the rule is something that we are thinking of trying to automatically add to the currently used theme by changing its `.sublime-color-scheme` file. For now the workaround would be to add/modify the `Packages/User/<Name>.sublime-color-scheme` file and add the rule above to the `rules` array in the file (@lamartire), similarly to how GitGutter is [manually configured](http://jisaacks.github.io/GitGutter/coloring/), unless theme supports `markdown` scope that it's using. 

BTW, you may want to do it for https://github.com/tonsky/sublime-scheme-alabaster/blob/master/Alabaster.sublime-color-scheme too, because currently with it GitGutter icons are rendered black.

**Comment by ArtemGovorov** [comment]
We have added the support for themes with any foreground colors in the latest version 1.0.44 (published and should be available in an hour or so). Note that you may need to restart Wallaby (so that Sublime re-renders the indicators) for some themes after changing your current theme.

**Comment by lamartire** [comment]
@ArtemGovorov, oh, okay. I think it is not bad solution 👍

**Comment by lamartire** [comment]
Just foreground changing not works 🤔 
@ArtemGovorov , can you make some scopes for more easily theme configuration?
For example: `wallaby.failed`, `wallaby.passed`, `wallaby.uncovered` (grey icon)? I think, it can be really helpful and much visually for users.

**Comment by ArtemGovorov** [comment]
@lamartire No manual changes from your side are required. Update to the [latest version](https://github.com/wallabyjs/public/issues/1952#issuecomment-451823698), change your theme, restart Wallaby and it should work.

**Comment by lamartire** [comment]
Yeah, it works! Thank you @ArtemGovorov for fast reply and fix, and thank you @tonsky for help with problem localisation ❤️ 
Have a nice day, guys!
