### ISSUE TITLE
false/positive on TS2339: Property 'do' does not exist on type 'MyInterface'.

### ISSUE THREAD

**Issue by wpannell** [wallabyjs/public#1961]
### Wallaby.js configuration file

```javascript
const ngxWallabyJest = require('ngx-wallaby-jest');

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'tsconfig.json',
      'tsconfig.spec.json',
      'jest.config.js',
      'setup-jest.ts',
      '!src/**/*.spec.ts',
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({
        module: 'commonjs',
        noLib: false,
        noResolve: false,
        noEmitOnError: true,
        declaration: true,
      }),
    },
    preprocessors: {
      // This translate templateUrl and styleUrls to the right implementation
      // For wallaby
      'src/app/**/*.component.ts': ngxWallabyJest,
    },
    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
Licensed to WILLIE G PANNELL JR
Subscription is active until March 16, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1### OS name and version

### operating system:

  System Version:	macOS 10.14.1 (18B75)
  Kernel Version:	Darwin 18.2.0

**Comment by wpannell** [comment]
I would be pleased to know how to configure `wallaby.js` to fail on `TS2339: Property 'do' does not exist on type 'MyInterface' ` for either reference app.

**Comment by ArtemGovorov** [comment]
By default, Wallaby also [sets few default compiler settings](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings) that are not replaced by `tsconfig.json` compiler settings (to perform TypeScript compilation faster).

If you want wallaby to stop overriding them, then you may to do it in your wallaby.js config by adding the `useStandardDefaults: true` setting:

```javascript
const ngxWallabyJest = require('ngx-wallaby-jest');

const compilerOptions = Object.assign(
  require('./tsconfig.json').compilerOptions,
  require('./src/tsconfig.spec.json').compilerOptions,
  {module: 'commonjs', useStandardDefaults: true, types: ['node']});

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.+(ts|html|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      'tsconfig.json',
      'tsconfig.spec.json',
      'jest.config.js',
      'setup-jest.ts',
      '!src/**/*.spec.ts',
    ],

    tests: ['src/**/*.spec.ts'],

    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript(compilerOptions),
    },
    preprocessors: {
      // This translate templateUrl and styleUrls to the right implementation
      // For wallaby
      'src/app/**/*.component.ts': ngxWallabyJest,
    },
    testFramework: 'jest'
  };
};
```

Note that I had to override `types` in the config, because your `tsconfig.spec.json` file requires `jasmine` types that are not installed in the project. 
Also, before trying the new config, please update to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update) version, because we have fixed a recent issue with module lookup in the `useStandardDefaults` mode.

However, we **do not recommend** running Wallaby with the type checking in place. Doing so will likely duplicate what your editor is already doing, and create a lot of noise for you when you're using Wallaby and will result in coverage indicators breaking when type errors are detected (often). This will also slow down the feedback loop between writing code and running tests, which somewhat reduces the benefit of Wallaby.

Instead, we suggest relying on your editor for these errors which will give you the best user experience in terms of editor feedback + fast wallaby tests. You should of course rely on your build processes, etc. to fail hard on these errors.

**Comment by wpannell** [comment]
@ArtemGovorov thanks for this and your 1st-class support.

I understand your recommendation.  We need `wallaby.js` to report out the errors for the sake of the TDD workflow we practice.

Keep up the good work.
