### ISSUE TITLE
Feature Request: Only run tests if some are selected

### ISSUE THREAD

**Issue by BrendanAnnable** [wallabyjs/public#1974]
[Test selection](https://wallabyjs.com/docs/intro/selected-tests.html) is great for reducing the amount of work my IDE does when dealing with a large codebase.

My issue is that if I delete the test focus (e.g. by switching branches, which I often do), the default behaviour is to then run _all_ the tests. For large codebases this is slow and undesirable.

Ideally I'd love to be able to configure wallabyjs to run _zero_ tests if none are selected, rather than run _all_ the tests if none are selected.

Is this a configuration option that could be added?

Thank you!

**Comment by ArtemGovorov** [comment]
The feature has been implemented and [documented](https://wallabyjs.com/docs/intro/selected-tests.html#test-file-selection).  It is available in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

If you want to configure wallaby to run zero tests if none are selected, rather than run all the tests if none are selected, you may use the `runSelectedTestsOnly` setting:


```javascript
module.exports = function (wallaby) {
  return {
    ...
    runSelectedTestsOnly: false
  };
};
```

**Comment by BrendanAnnable** [comment]
Thank you! 🎉
