### ISSUE TITLE
Just purchased Wallaby, getting simple config issue preventing me from using it

### ISSUE THREAD

**Issue by onexdata** [wallabyjs/public#1999]
### Issue description or question
Cannot import modules that begin with './' in the working folder in Wallaby.

### Repo to reproduce the issue
https://github.com/onexdata/wallabyjs-issue

### Code editor or IDE name and version
VS Code latest (1.31.0)

### OS name and version
Windows 10

Using the config in the repo, I am able to get Jest to run the test, but not Wallaby. Wallaby fails saying it cannot find the import in the same folder as the index.js file it is able to find. I have no idea why.

**Comment by smcenlly** [comment]
Thanks for the sample repo. Because your project uses `Vue`, your configuration needed a few modifications (as per [our docs](https://wallabyjs.com/docs/integration/vue.html#vuecli-v3x)).

I've created a [pull request](https://github.com/onexdata/wallabyjs-issue/pull/1) for you that has the working changes.

I needed to add a new npm dev dependency for `wallaby-vue-compiler` so you will need to run `npm install` after merging.

Your working configuration now looks like this:

```javascript
module.exports = function(wallaby) {
  process.env.VUE_CLI_BABEL_TRANSPILE_MODULES = true;

  const compiler = wallaby.compilers.babel();

  return {
    files: [
      'jest.config.js',
      'package.json',
      'src/**/*.js?(x)',
      'src/**/*.vue',
      '!src/**/*.spec.js?(x)'
    ],

    tests: ['test/**/*spec.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': compiler,
      '**/*.vue': require('wallaby-vue-compiler')(compiler)
    },

    preprocessors: {
      '**/*.vue': file => require('vue-jest').process(file.content, file.path)
    },

    setup: function(wallaby) {
      const jestConfig = require('./package').jest || require('./jest.config');
      jestConfig.transform = {};
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest',
    debug: true
  };
};
```
