### ISSUE TITLE
Support for ES6 + browserify + angular (angular module not loaded when running spec)

### ISSUE THREAD

**Issue by sander78** [wallabyjs/public#200]
Hello,

We specify load:false with our files setup (because we use browserify and load the tests in the bootstrap function).
Unfortunately this results in de angular module not being initialized (in index.js). The file is served (properly translated to ES5) but is not loaded when running a spec test.
How can we trigger wallaby to load in the translated index.js file?

I have added a small demo project on github to demonstrate this problem:
https://github.com/sander78/wallaby-demo

Thanks in advance

**Comment by ArtemGovorov** [comment]
Hello,

Thanks for the repository, I have sent you [the pull request](https://github.com/sander78/wallaby-demo/pull/1).

The issue was that in your spec the `module` variable in `beforeEach(module("wallaby-test"));` is pointing to browserify supplied CommonJs module (that you can export things with), but what you need in this case is `angular.mock.module`. 

I have also set `instrument: false` to angular files, as you probably don't need the code coverage for them.

> How can we trigger wallaby to load in the translated index.js file?

Not sure if I'm answering the right question, as there's no `index.js` in the repository (this part is probably left from the original question), but if you'd like to load anything you may just `require` it from your spec:

<img width="388" alt="screen shot 2015-07-15 at 11 11 55 am" src="https://cloud.githubusercontent.com/assets/979966/8688695/8cc016c6-2ae2-11e5-8155-cc83f8d783fd.png">

You may also use ES6 modules `import` instead of `require` (and generally ES6 syntax) in your specs if you add the same preprocessor for `'test/**/*.js'` as you have for `'src/app/**/*.js'` in your config.

P.S. in your original question I have noticed you are suing patterns like:
```
{pattern: 'src/app/**/!(*spec|*mock).js', load: false},
{pattern: 'src/components/**/!(*spec|*mock).js', load: false}
```
I don't think wallaby currently supports such patterns, you may need to simplify them a bit, if it's an issue.

**Comment by fvanwijk** [comment]
I think it is because the unsupported blob patterns: https://github.com/wallabyjs/public/issues/69

**Comment by sander78** [comment]
Hello Artem,

Thanks for your suggested fix. You were right about module. Unfortunately this doesn't solve our problem. It was passing because our tests were not testing the right things.
I have added some small changes to the demo project to demonstrate this.

The karma tests are passing with karma.conf.js but wallaby still complains about the Angular module not being initialized (I think because load: false)

https://github.com/sander78/wallaby-demo

Thanks again for looking into this (really good support!!)

Sander

**Comment by ArtemGovorov** [comment]
@sander78 Thanks! 
I see what the problem is now. 

The issue was that your tests are not browserify-ed and it wasn't supported by wallabify package. Wallabify was always assuming that your tests are browserify-ed as well and are entry points. So just adding 
```
  require('../app/app');
  require('../app/my.controller');
```
to your spec would make it work in your current repo.

However, I understand that you may not want to change the way you structure your tests, so I have added the support for configurable entry points to make it work in the scenarios like supported in karma, and have sent you [the pull request](https://github.com/sander78/wallaby-demo/pull/3), please update `wallabify` package to 0.0.8 to make it work.

The changes to your config are pretty simple:
- you need to specify a pattern (or an array of patterns) in the wallabify options to tell it that not tests will be entry points of browserify build, but your source files instead: `entryPatterns: 'src/app/**/*.js'`.
- you need to remove `window.__moduleBundler.loadTests();` call because your tests are not browserify-ed and not loaded via module bundler.
- you need to set `load: true` (or remove the setting as it is the default value) for your tests, because you need to include your tests in the sandbox in a usual way (rather than using module bundler).

Please note however, that browserify-ing your tests and `require`-ing all dependencies from them is more performant in both karma and wallaby.

**Comment by sander78** [comment]
@ArtemGovorov thanks again!
Sorry for the late response, we had some shifting project priorities :)
Your solutions works besides a strange bug? that's happening now.

This is our actual project's wallaby.conf (not the demo project on github anymore)

```
var wiredep = require('wiredep');

var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
      debug: true,
      entryPatterns: ['src/**/*.js', 'test/testUtils.js', 'test/mock/moxConfig.js']
    });// , b => b.transform(require('babelify').configure({optional: ['runtime']})));
    // you may also pass an initializer function to chain other
    // browserify options, such as transformers
    // , b => b.exclude('mkdirp').transform(require('babelify'))



var bowerDeps = wiredep({
  directory: 'bower_components',
  exclude: ['bootstrap-sass-official', 'mox'],
  dependencies: true,
  devDependencies: true
});

module.exports = function () {
  return {
    files: bowerDeps.js.concat([
      'bower_components/jasmine-mox-matchers/src/jasmine-mox-matchers.js',
      'bower_components/mox/dist/mox.js',
      {pattern: 'src/app/**/*.html', load: false},
      {pattern: 'src/components/**/*.html', load: false},
      {pattern: 'src/app/**/*.js', load: false},
      {pattern: 'src/app/**/*.spec.js', ignore: true},
      {pattern: 'src/components/**/*.js', load: false},
      {pattern: 'src/components/**/*.spec.js', ignore: true},
      {pattern: 'test/testUtils.js', load: true},
      {pattern: 'test/mock/moxConfig.js', load: true}
    ]),

    tests: [
      'src/app/**/*.spec.js'
    ],

    preprocessors: {
      'src/**/*.js': file => require('babel').transform(file.content, {sourceMap: true, optional: ['runtime']}),
      'src/**/*.html': file => require('wallaby-ng-html2js-preprocessor').transform(file, {})
    },

    debug: false,

    postprocessor: wallabyPostprocessor
  };
};
```

Everything is working fine except I get this error:
Runtime error: Error: Cannot find module '/Users/sanderabbink/Library/Caches/IntelliJIdea14/wallaby/projects/e5dff542e2c2eed2/instrumented/src/app/main/forecast.controller.spec.js'

If i look in that directory the following files are present:
```
forecast.controller.js            
forecast.controller.js.bro.js           
forecast.controller.spec.js             
forecast.controller.spec.js.bro.js
```

If I open the file forecast.controller.spec.js and add a space or something. Wallaby picks up the file and then tests turn green. But if I restart wallaby I get the same error. If I remove this spec then some other test(s) throw this error.

I also tried this with the spec tests in a different folder then the production files -> same behaviour.

Any idea how this can happen? 
I also tested it on a different machine, same behaviour.

Regards,
Sander

**Comment by ArtemGovorov** [comment]
Hi Sander,

Thanks for providing the config. 

It looks like your tests are browserify-ed, even though you'd like them to be loaded into the sandbox as is. This happens because `entryPatterns: ['src/**/*.js', ...]` includes your tests as well. Excluding tests like this: `entryPatterns: ['src/**/!(*spec).js', ...]` should fix the issue.

A couple more notes about the config:

- Files `'test/testUtils.js', 'test/mock/moxConfig.js'` are both specified as entry points and in the files list with `load: true`. What specified as an entry point, will be loaded anyway, so it looks like you're loading them twice. If they need to be browserify-ed, you may leave them as entry points, but the should set `load: false` for them in the files list. And if you don't need them to be browserify-ed, you may remove them as entry points and leave `load: true` in the files list.

- By default wallaby.js instruments everything to collect and display the code coverage. You current configuration includes a list of bower dependencies (`bowerDeps.js`) and wallaby will instrument and display the code coverage for all those files. While sometimes it is required, usually it's not, so you may really improve wallaby.js startup time and test running performance if you set `instrument: false` to all files that you don't need the code coverage for. 

So where you have
``` JavaScript
files: bowerDeps.js.concat([...])
```

you may add:
``` JavaScript
bowerDeps.js.map(depPath => ({pattern: depPath, instrument: false})).concat([...])
```

I'd also suggest considering setting the `instrument` flag to `false` for these files (just guessing that you probably won't need the code coverage for them):
```
'bower_components/jasmine-mox-matchers/src/jasmine-mox-matchers.js',
'bower_components/mox/dist/mox.js',
{pattern: 'test/testUtils.js', load: true},
{pattern: 'test/mock/moxConfig.js', load: true}
```

**Comment by fvanwijk** [comment]
Instrumenting files is also handy for debugging. If you change some config or you want to log something to the console, you get immediate feedback when the files are instrumented. That's why I sometimes instrument my libraries. I'm quite sure that Sander wants to intrument those 4 files, which are ES5 files by the way, so do not need to be browserified.

**Comment by sander78** [comment]
@ArtemGovorov 
Thanks again for your quick reply. Finally got it working.
This is our current config

```
var wiredep = require('wiredep');
var buildConf = require('./build.conf');
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
      debug: true,
      entryPatterns: buildConf.applicationSources
    });
var _ = require('underscore');

module.exports = function () {
  return {
    files: [].concat(
      buildConf.applicationDependencies.map(depPath => ({pattern: depPath, instrument: false})),
      buildConf.specDependencies.map(sources => ({pattern: sources, load: true, instrument: false})),
      buildConf.applicationTemplates.map(template => ({pattern: template, load: true})),
      buildConf.applicationSources.map(sources => ({pattern: sources, load: false}))
    ),

    tests: buildConf.specSources.map(specPath => ({pattern: specPath, load: true})),

    preprocessors: buildConf.mapToProcessorConfig(
      {
        patterns: buildConf.applicationTemplates,
        processor: file => require('wallaby-ng-html2js-preprocessor').transform(file, {})
      },
      {
        patterns: [].concat(buildConf.applicationSources, buildConf.specSources),
        processor: file => require('babel').transform(file.content, {sourceMap: true, optional: ['runtime']})
      }
    ),

    debug: false,

    postprocessor: wallabyPostprocessor
  };
};
```
buildConf contains all patterns. We use globule to make a list of all files. This way patterns like:
```
applicationSources: globule.find('src/{app,components}/**/!(*spec).js'),
```
are supported. These patterns are also used in the karma config.
Nice that wallaby.conf.js supports ES6 by the way!

**Comment by ArtemGovorov** [comment]
@sander78 Nice, the config looks very clean!

p.s. it looks like you don't need the declared `var wiredep = require('wiredep');` anymore.

**Comment by ArtemGovorov** [comment]
@sander78 I really like the way you are reusing your dependencies between gulp/karma/wallaby with the build.conf.js file, might be an interesting topic for a blog post one could write (or even a micro node module to help managing/generating it if required). I think many people these days are using two or more tools that require the project file structure knowledge, and even though the idea of reusing these bits is pretty obvious, more than often I see these patterns/paths duplicated in the configs.
