### ISSUE TITLE
Support Jest testResultsProcessor

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#2001]
### Issue description or question

Hi, it seems that when runnign the Jest via wallaby, the **testResultProcessor** is not working. It may sound strange, but I'd like to have reporter enabled, would it be possible?

```
module.exports = {
 ...
  testResultsProcessor: 'luis/dist/bridges/jest/reporter',
  ...
};
```

**Comment by ArtemGovorov** [comment]
Unfortunately `testResultsProcessor` is not supported because Wallaby integrates with Jest runner API and `testResultsProcessor` is invoked on the CLI abstraction level.

You may try using [Jest reporters](https://jestjs.io/docs/en/configuration#reporters-array-modulename-modulename-options) for the same purpose, note however that:
- Wallaby parallelises Jest instances, so depending on your scenario you may need to set [Wallaby `workers`](https://wallabyjs.com/docs/config/workers.html) count to 1.
- Incremental Wallaby runs will only be reporting incremental execution results.
