### ISSUE TITLE
I need some help with setting up jest microservice setup

### ISSUE THREAD

**Issue by kvernon** [wallabyjs/public#2011]
### Issue description or question

I have a project that has subprojects using webstorm, nodejs, and jest. While I'm able to get WebStorm to --watchall with jest, it's slow. At least it will run all tests within all sub projects. My true desire is to have wallaby running instead. It's important to note that we don't run babble in this (or at least directly... I know jest does run some behind the scenes). But for the core files I've listed them below... We do use eslint aws-sdk, but I didn't feel these were important to call out. Hopefully this makes sense. 

Please (and more please) help!

```text
project-folder/
├── sub-project1/
│   ├── project.json
│   ├── {various-source-files}.js
│   └── test/
│       ├── {various-test-files}.test.js
├── sub-project2/
│   ├── project.json
│   ├── {various-source-files}.js
│   └── test/
│       ├── {various-test-files}.test.js
├── project.json
└── wallaby.js


```

### Wallaby.js configuration file
I tried using this as an example: https://wallabyjs.com/docs/integration/jest.html, but I've failed rapidly :(
```javascript
module.exports = function () {

  return {
    files: ['**/*.js', '!**/test/*.js'],

    tests: ['**/test/*.js'],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```
I've also tried matching patterns of 
```javascript
files: ['**/**/*.js', '!**/**/test/*.js'],
tests: ['**/**/test/*.js'],

//and

files: ['**/**/*.js', '!**/**/test/*.test.js'],
tests: ['**/**/test/*.test.js'],
```
### Code editor or IDE name and version

WebStorm v 2018.3.5 and 191 (eap)

### OS name and version

Windows 10
OSX mojave

**Comment by ArtemGovorov** [comment]
- Where is your Jest installed? In `project-folder/node_modules`?
- Where do your Jest config live? In each project? Are those configs mostly the same? Could you please share one/common one?
- By `project.json` did you mean `package.json`?

**Comment by kvernon** [comment]
Good morning @ArtemGovorov, 

Sorry for all the mess ups with my original post. You're right, it is package.json (I was even staring at when I was trying to show you the breakdown of the structure) :/

Also thanks for following up. We actually install jest in all package.json files

 ```
// updated to reflect package.json
project-folder/
├── node_modules (after npm i)
├── sub-project1/
│   ├── node_modules (after npm i)
│   ├── package.json
│   ├── {various-source-files}.js
│   └── test/
│       ├── {various-test-files}.test.js
├── sub-project2/
│   ├── node_modules (after npm i)
│   ├── package.json
│   ├── {various-source-files}.js
│   └── test/
│       ├── {various-test-files}.test.js
├── package.json
└── wallaby.js
```

we commonly have this in all our package.json files:

```
  ...
  "devDependencies": {
    "eslint": "^5.14.1",
    "eslint-config-google": "^0.12.0",
    "eslint-plugin-jest": "^22.3.0",
    "jest": "^24.1.0"
  },
 ...
```

So for the testing world. I can set up a WebStorm configuration for all files (every single jest file watch within the project and/or sub-projects), or do a similar one using the individual projects (https://www.jetbrains.com/help/webstorm/creating-and-editing-run-debug-configurations.html). 

The question is how would I approach this with wallabyjs?

Thanks again,
Kelly

**Comment by smcenlly** [comment]
Hi Kelly,

If your packages are the same versions between your different modules, you can create a single wallaby configuration that runs across all of your projects. We created as [sample](https://github.com/wallabyjs/wallaby-multi-project-sample) for you that demonstrates this with the project structure you provided.

If you have conflicting dependencies or you only want to test one project at a time, you can create separate wallaby configurations for each sub-project and have a different run configuration with a different `wallaby.js` configuration for each project. Please note: if you do this, each `wallaby.js` configuration (e.g. `wallaby-sub-project1.js`, `wallaby-sub-project2.js`) will need to be your `project-folder` root.

If you decide to have a separate configuration for each sub-project, you should be able to take the wallaby.js configuration from the [sample](https://github.com/wallabyjs/wallaby-multi-project-sample) that we've provided and strip it down so that it only includes the files for your sub-project.

**Comment by kvernon** [comment]
@smcenlly -- holy hell! Thank you all very much for helping me! This is outstanding. 

What I was finding was that the `watchall` was slow, but the only way to currently do this, which is why I would consider sub wallaby configs. Obviously this nails it perfectly, and I appreciate this.
