### ISSUE TITLE
Wrong coverage report in Wallaby App

### ISSUE THREAD

**Issue by davegomez** [wallabyjs/public#2023]
The coverage report in the Wallaby App is wrong because the application is not taking the information from several files that are being tested as you can see in the next screenshot:

<img width="669" alt="coverage" src="https://user-images.githubusercontent.com/282903/54192664-e2a4b280-448e-11e9-8bbe-f2f9c6eefbb3.png">

You can find the configuration file in [this repository](https://github.com/davegomez/silky-charts/blob/master/wallaby.js) and even run the project if you need to.

Visual Studio Code v1.32.1
macOS Mojave

On the other side I'm having some issues with another project that is using lerna to handle scoped packages and is not reporting any error but is also not running any test.

I already try different things I found around the docs and the GH issues to make Wallaby to run in monorepo projects but haven't be able to make them run.

The project is https://github.com/davegomez/silky

Thanks for any help you can provide in this.

**Comment by ArtemGovorov** [comment]
Could you please point out what exactly is incorrectly calculated on the screenshot? I can't immediately spot anything wrong.

**Comment by davegomez** [comment]
Sorry I thought about it but didn't do it. What is wrong is all the files marked as "n/a" in the list, this is causing the App to report a coverage of 72% when Jest is reporting 98%. The problem started with a couple of files a few weeks ago but now is considerable.

**Comment by ArtemGovorov** [comment]
>  What is wrong is all the files marked as "n/a" in the list, this is causing the App to report a coverage of 72% when Jest is reporting 98%. The problem started with a couple of files a few weeks ago but now is considerable.

Thanks, we'll be looking into it shortly.

> On the other side I'm having some issues with another project that is using lerna to handle scoped packages and is not reporting any error but is also not running any test.
> I already try different things I found around the docs and the GH issues to make Wallaby to run in monorepo projects but haven't be able to make them run.

Not sure what issues did you have, because you haven't shared your Wallaby config, but I have [created a simple one](https://github.com/davegomez/silky/pull/1) mostly copy/pasting from our docs at https://wallabyjs.com/docs/integration/jest.html, and it seems to be working fine.

**Comment by ArtemGovorov** [comment]
> Sorry I thought about it but didn't do it. What is wrong is all the files marked as "n/a" in the list, this is causing the App to report a coverage of 72% when Jest is reporting 98%. The problem started with a couple of files a few weeks ago but now is considerable.

Just cloned your repo and it shows me 93.53% coverage. Wallaby is using a form of branch coverage and it is close to Jest reported 93.27% branch coverage.

<img width="1021" alt="Screen Shot 2019-03-12 at 10 13 34 pm" src="https://user-images.githubusercontent.com/979966/54199229-21c91700-4514-11e9-98eb-c4de56a5f999.png">

Unfortunately your original screenshot doesn't indicate the issue either, because it just shows some files in a middle of the tree.

Have you tried refreshing Wallaby App? Also try stopping Wallaby, running `killall node` and starting it again (maybe it is connecting to an orphaned core version).

**Comment by davegomez** [comment]
Thank you as always @ArtemGovorov. The second Wallaby config is not published because is not working yet and I forgot to do it before asking you for help. Thanks a lot for the PR.

Is too early in the morning here 😣

About the Wallaby App the `killall node` command did the trick, didn't know that this may happen. The weirdest thing is that is being happening since a few weeks ago, so I wonder how long this process was there running in the bg.
