### ISSUE TITLE
Runner seems to stop and start when a file is saved

### ISSUE THREAD

**Issue by dericgw** [wallabyjs/public#2037]
### Issue description or question
When I start Wallaby, everything seems to work. However, whenever I make a change and save a file, all of the gutter icons disappear and Wallaby seems to not be working. I have tried to start and stop Wallaby, restart VS Code and cannot figure out what is causing this.

Here are some images of it working and it not working:

Normal
![Normal and working](https://d2ddoduugvun08.cloudfront.net/items/2k3v3A1J0L23123M1Z1S/normal.png)

Broken
![Broken](https://d2ddoduugvun08.cloudfront.net/items/182D082j3a1Q172p031T/broken.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/**/*.+(js|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)',
      '!src/**/*spec.js?(x)',
      { pattern: 'config/jest/*.js', instrument: false },
      { pattern: 'src/serviceWorker.js', instrument: false },
    ],

    tests: ['src/**/*spec.js?(x)'],

    env: {
      type: 'node',
      runner: 'node'
    },

    compilers: {
      '**/*.js?(x)': wallaby.compilers.babel({})
    },

    filesWithNoCoverageCalculated: ['config/*', 'src/serviceWorker.js'],

    setup: wallaby => {
      const jestConfig = require('./package.json').jest;
      delete jestConfig.transform['^.+\\.(js|jsx)$'];
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.32.3?

### OS name and version

Windows 10

**Comment by smcenlly** [comment]
This looks like the same problem as #2038 .

We isolated the cause of this issue, which was a combination of Windows file system changed events and the way that VS Code flushes content to disk after write. Wallaby was receiving 0 bytes from the file system for the changed files, which is why your files were empty.

This has now been fixed. Please download the latest version of Wallaby for VS Code, v1.0.121. This will also download the latest version of Wallaby core, which is also necessary.
