### ISSUE TITLE
ReferenceError: $_$wp is not defined 

### ISSUE THREAD

**Issue by thegnuu** [wallabyjs/public#2041]
### Issue description or question

I am currently trying to get my configuration working in a web worker library. Unfortunately I am not able to publish my complete source, but I was able to create a repository to reproduce the error.

https://github.com/thegnuu/wallaby-error

I had a look at the related issues, but unfortunately I was not able to resolve my issue.

### Wallaby.js configuration file

https://github.com/thegnuu/wallaby-error/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v1.32.3 

### OS name and version

macOS 10.14.4

**Comment by smcenlly** [comment]
Thanks for providing the sample repo. The error that you're receiving is originating from Tiny-Worker. Tiny-Worker spawns a new process and runs `src\worker\test.js` in the new process, which doesn't have any of the Wallaby runtime loaded. Wallaby does not support running instrumented files in spawned processes.

What you can do to fix this is set `instrument` to `false` for your worker code. The impact of this is that file code coverage reporting will be disabled and changes to your worker files will not trigger automatic test execution. Please find a sample config that works for your project below:

```diff
module.exports = function () {

  return {
    files: [
      'tsconfig.json',
+     { pattern: 'src/worker/test.js', instrument: false },
      'src/**/*',
      '!src/**/*.spec.ts'
    ],

    tests: ['src/**/*.spec.ts'],

    hints: {
      ignoreCoverage: /istanbul ignore next/,
      ignoreCoverageForFile: /ignore file coverage/
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};
```

I'm not sure of the level of effort involved, but if you need/want instrumentation on your workers files, you could consider creating a mock for Tiny-Worker so that everything runs in the same process.

**Comment by thegnuu** [comment]
@smcenlly Thank you very much for your fast response, I don't need the coverage of the worker in this case, those files will be generated by another package anyway, which will include all the tests. For my 'execution helper' it is fine to omit the worker tests...

But I know now what caused the issue and I should be able to mock everything once I think it might be necessary to test this as well.

Everything works now as expected :)
