### ISSUE TITLE
Don't rerun all tests after remove .only

### ISSUE THREAD

**Issue by kevinbarabash** [wallabyjs/public#2071]
### Issue description or question

I noticed that whenever I remove `.only` from a test, wallaby reruns all tests even if I haven't made any change to any other tests or source code.  I have a project with over 9000 tests.  The entire test suite takes about 2 minutes to run.  Waiting 2 minutes every time I remove `.only` really puts a damper on things.  I was wondering if there's anyway wallaby could cache test results and only rerun tests for files that have changed in between when I added and removed the `.only`.

### Wallaby.js configuration file

```javascript
const babelConfig = require("./build-settings/babel.config.js");

module.exports = function (wallaby) {
    return {
        files: [
            'packages/wonder-blocks-*/**/*.js',
            'package.json', // <--
            { pattern: 'config/jest/*.js', instrument: false },
            'shared-unpackaged/**/*.js',
            'utils/**/*.js',
            'packages/wonder-blocks-*/package.json',
            { pattern: 'packages/wonder-blocks-*/dist/**/*.js', instrument: false },
            '!packages/wonder-blocks-*/**/*.test.js',
            '!packages/wonder-blocks-*/node_modules/**',
            '!shared-unpackaged/**/*.test.js',
        ],

        filesWithNoCoverageCalculated: [
            'config/jest/*.js',
            'packages/wonder-blocks-*/dist/**/*.js',
            'utils/**/*.js',
        ],

        tests: [
            'packages/wonder-blocks-*/**/*.test.js',
            'shared-unpackaged/**/*.test.js',
        ],

        compilers: {
            "packages/wonder-blocks-*/**/*.js": wallaby.compilers.babel(babelConfig),
            "shared-unpackaged/**/*.js": wallaby.compilers.babel(babelConfig),
            "utils/**/*.js": wallaby.compilers.babel(babelConfig),
        },

        env: {
            type: 'node',
            runner: 'node',
            params: {
                runner: "--max_old_space_size=4096"
            },
        },

        testFramework: 'jest',

        setup: function (wallaby) {
            const path = require("path");
            const jestConfigPath = path.join(
                wallaby.localProjectDir,
                "./config/jest/test.config.js",
            );
            const jestConfig = require(jestConfigPath);
            delete jestConfig.transform;
            jestConfig.moduleNameMapper = {
                "^@khanacademy/(.*)$":
                    wallaby.projectCacheDir + "/packages/$1",
            };
            // for example:
            // jestConfig.globals = { "__DEV__": true };
            wallaby.testFramework.configure(jestConfig);
        },

        // debug: true,
    };
};
```

### Code editor or IDE name and version

Visual Studio Code v1.33.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby re-runs all tests because while one of your tests has `.only`, and your testing framework only runs this test, you may potentially change source files in such a way that Wallaby doesn't know what tests are related to what source files, and needs a full test run to rebuild the dependency tree and continue to run tests incrementally correctly.

We'll investigate the idea of minimising the number of times when the full run is required.

For now, an alternative to the existing behaviour is to use the `automaticTestFileSelection` setting:

```
module.exports = function (wallaby) {
  return {
    ...
    automaticTestFileSelection: false
  };
};
```

With the setting Wallaby will work closer to how Jest works and run only one test in the test file (but potentially depending on your changes other test files too because of the parallelisation), but will not need to re-run all tests after `.only` is removed.

Also, given how large your test number is, and if you often find yourself working on different independent test files/parts of your code base, you may consider using test file selection with files comments: https://wallabyjs.com/docs/intro/selected-tests.html#test-file-selection, plus the `runSelectedTestsOnly` setting, so that Wallaby never runs all of your tests (unless you have and use another Wallaby config that has no setting and runs all tests as usual).

**Comment by kevinbarabash** [comment]
@ArtemGovorov the settings you suggested help big time.  Thank you!

**Comment by kevinbarabash** [comment]
One thing I have noticed is that even with `runSelectedTestsOnly`, startup time is still slow b/c it still instruments all files in the project.  Would it be possible to instrument files as they're required?

**Comment by ArtemGovorov** [comment]
>  still instruments all files in the project.

It should only happen once after Wallaby config changes (because changing the config invalidates Wallaby cache). Subsequent Wallaby starts (without config changes) should not trigger unchanged files instrumentation.

**Comment by kevinbarabash** [comment]
Cool.  I've been making lots of changes to my config file, I guess I should stop doing that.
