### ISSUE TITLE
Test fixtures have unwanted processing

### ISSUE THREAD

**Issue by TrevorBurnham** [wallabyjs/public#2074]
### Issue description or question

I'm writing a project that processes JavaScript, so it has some `.js` files in a `fixtures/` directory for testing. These fixtures aren't intended to be compiled; they're read in my tests with `fs.readFileSync`, and are never referenced with `import` or `require` statements. However, I can't seem to find a way to get Wallaby to leave them alone. When `fs.readFileSync` runs against one of those fixtures, it gets a processed version.

You can replicate in this repo: https://github.com/TrevorBurnham/eslint-auto-disable Running `yarn test` shows that the tests pass; running Wallaby yields a failure due to comparing the processed versions of the fixtures. I've tried adding the `fixtures/` directory to a `.babelignore` file at the root of my project, but this doesn't seem to have any effect.

I've confirmed that the problem goes away if I remove the `.js` extensions from the fixtures (and include their new extensions in the `files` blob). Is it possible to modify my Wallaby configuration to include these `.js` files unprocessed?

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ['src/**/*.js', '!src/**/*.test.js'],
    tests: ['src/**/*.test.js'],

    env: {
      type: 'node',
      runner: 'node',
    },

    // Being very specific here to avoid compiling the contents of `src/tests/fixtures`
    compilers: {
      'src/transform.js': wallaby.compilers.babel(),
      'src/tests/transform.test.js': wallaby.compilers.babel(),
    },

    testFramework: 'jest',

    debug: true,
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.33.1

### OS name and version

macOS 10.14.4

**Comment by smcenlly** [comment]
Yes, it is possible to exclude these files from being instrumented by wallaby. The [files](https://wallabyjs.com/docs/config/files.html#file-object) section of our docs describes the various options that are available. What you'll want to do is create another pattern in your files with `instrument` set to false. I've updated your configuration file to do this for you (see below). 

Using the sample that you provided, I get an error when running `yarn test` but this may be because I'm using windows and there are some line ending differences. While the test doesn't work for me, I can confirm that your fixtures `.js` files are no longer modified by Wallaby.

```javascript
module.exports = function(wallaby) {
  return {
    files: [
      { pattern: 'src/tests/fixtures/*.js', instrument: false },
      'src/**/*.js', 
      '!src/**/*.test.js'
    ],
    tests: ['src/**/*.test.js'],

    env: {
      type: 'node',
      runner: 'node',
    },

    compilers: {
      'src/transform.js': wallaby.compilers.babel(),
      'src/tests/transform.test.js': wallaby.compilers.babel(),
    },

    testFramework: 'jest',

    debug: true,
  };
};
```

**Comment by TrevorBurnham** [comment]
Thanks! I've confirmed that the updated configuration works. 🥇
