### ISSUE TITLE
Failing to resolve function import

### ISSUE THREAD

**Issue by Sam-Jeston** [wallabyjs/public#2077]
### Issue description or question

When Wallaby is first started from the editor, all tests pass, and all line markers are green. If I open [this file](https://github.com/input-output-hk/cardano-js-sdk/blob/develop/src/Wallet/lib/get_next_address.ts#L25) and create an edit of any sort (a console.log on the line specified will recreate the issue), then Wallaby reports this error in it's console, and tests start failing:

```
    __1.addressDiscoveryWithinBounds is not a function 
      at ​src/Wallet/lib/get_next_address.ts:25:2​
      at ​src/Wallet/lib/get_next_address.ts:25:2​
```

The following commands from the repo all pass as expected when Wallaby is reporting this error:

1. npx tsc
2. npm test (which runs both eslint and mocha)

The repository in question is open source, and I have recreated the issue on two machines.

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'src/**/*.ts',
      '!src/**/*.spec.ts'
    ],

    tests: [
      'src/**/*.spec.ts'
    ],
    env: {
      type: 'node'
    },
    testFramework: 'mocha'
  }
}
```

### Editors confirmed

I have confirmed this issue in both Visual Studio Code and Webstorm:

Visual Studio Code: 1.33.1
WebStorm: Build #WS-183.6156.10

### OS name and version

I have also confirmed this issue on both OSX and Ubuntu:

OSX: 10.14.4
Linux: Ubuntu 18.04

**Comment by smcenlly** [comment]
Thanks for the sample repo, was a big help to see what was going on.

Wallaby has actually found a bug in your code that you didn't see with `mocha` (having said that, you also don't see it every time in wallaby).

You can duplicate your problem in `mocha` by updating your mocha configuration file as shown below:
```
--require ts-node/register
--require source-map-support/register
--recursive
--exit
src/Wallet/lib/select_inputs.spec.ts
src/test/SelectInputsForTransaction.spec.ts
```

What's going on here is that unlike `mocha`, wallaby runs your tests in parallel and the order of test execution is not guaranteed. In your initial test run, your test files happen to be ordered in a way that everything works, but in subsequent runs, the same order is not guaranteed. The mocha configuration we provided orders your tests in a way that will always break.

The root cause of the issue is that there is a circular dependency between your files which means that based on your context, sometimes the file has run completely (i.e. exports have been set) and at other times the file won't be loaded because it's currently being loaded but there are no exports available yet. 

Here is the issue we found:

**src\Wallet\lib\get_next_address.ts**
```
import { AddressType, addressDiscoveryWithinBounds, Address } from '..' // src\Wallet\index.ts
```
**src\Wallet\index.ts**
```
export { addressDiscoveryWithinBounds } from './lib' // src\Wallet\lib\index.ts
```
**src\Wallet\lib\index.ts**
```
export * from './get_next_address' // RECURSIVE CALL
```

If this pattern is common in your files, you might want to check for other circular references.

**Comment by Sam-Jeston** [comment]
Thanks for the solution @smcenlly, much appreciated.
