### ISSUE TITLE
Usage with typeorm and jest

### ISSUE THREAD

**Issue by asmadsen** [wallabyjs/public#2081]
### Testing typeorm with wallaby
When Wallaby is running the tests, Typeorm don't seem to be able to resolve the relations between the the entities. From my experience digging around in the Typeorm sourcecode the error Appears in typeorm/metadata-builder/EntityMetadataBuilder.ts. Where it traverses the collected entity metadata, comparing the class constructors looking for the relation type, this is where jest will find the correct relation type whilst wallaby will not.

### Reproduction repo
[https://github.com/asmadsen/wallaby-jest-typeorm](https://github.com/asmadsen/wallaby-jest-typeorm)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
	var path = require('path')

	process.env.NODE_PATH +=
		path.delimiter + path.join(wallaby.projectCacheDir, 'src')

	return {
		files: [
			'tsconfig.json',
			'tests/tsconfig.json',
			'src/**/*.ts'
		],

		tests: ['tests/**/*.spec.ts'],

		env: {
			type: 'node',
			runner: 'node'
		},

		testFramework: 'jest',
	}
}
```

### Code editor or IDE name and version

WebStorm 2019.1.2
Build #WS-191.7141.49, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

### OS name and version

OSX 10.14.5

**Comment by smcenlly** [comment]
Thanks for the providing the sample repo. The problem is caused by a difference between how `jest` runs your tests and how `wallaby` runs your tests.

Your TypeScript code is being run by `jest` using `ts-node` whereas `wallaby` first compiles your TypeScript code to Javascript using the TypeScript compiler, and then runs your code as Javascript. The path to entities in your `Post.spec.ts` file is:

```
			entities: [
				__dirname + '/../src/entities/**/*.ts'
			],
```

which is correct for jest, but for wallaby, the extension needs to be changed to `.js` (Javascript).

There are a number of ways you can do this, one of the simpler ways is to add a setup section to your configuration that includes a new `process.env` setting and then switch on that in your code. So you would update your wallaby.js configuration file to look like this:

```
module.exports = function (wallaby) {
	var path = require('path')

	process.env.NODE_PATH +=
		path.delimiter + path.join(wallaby.projectCacheDir, 'src')

	return {
		files: [
			'tsconfig.json',
			'tests/tsconfig.json',
			'src/**/*.ts'
		],

		tests: ['tests/**/*.spec.ts'],

		env: {
			type: 'node',
			runner: 'node'
		},

		setup: () => {
			process.env.entityPath =  '/../src/entities/**/*.js';
		},

		testFramework: 'jest',
	}
}
```

You would then switch on `process.env.entityPath` in your createConnection code:

```
connection = await createConnection({
    type: 'sqlite',
    database: './test.sql',
    entities: [
        __dirname + (process.env.entityPath ? process.env.entityPath : '/../src/entities/**/*.ts')
    ],
    synchronize: true,
    dropSchema: true
})
```

---

One other thing that I noticed is that you're including the `tsconfig.json` for both your root and your tests directory. Wallaby only loads the tsconfig in your root directory, so you may run into some unexpected behavior if you need the compilerOptions from your `tests` directory. If you need to, you can override your wallaby TypeScript configuration ([see how in our docs](https://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings)).
