### ISSUE TITLE
Inconsistent jest results testing rxjs observables with jest-marbles

### ISSUE THREAD

**Issue by shwanton** [wallabyjs/public#2083]
### Issue description or question
Running the same test using the `jest` cli and `wallaby` inside vscode has inconsistent results.
When I use the `concat` operator, the jest cli reports passing tests but wallaby shows an error:

```
    Expected observable to have the following subscription points: 
      ["^------!"] 
    But got: 
      ["^------!", "^------!", "^------!"] 
```

I've created a repro here: https://github.com/shwanton/wallaby-jest-marbles

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    files: ["src/index.js"],
    tests: ["src/index.test.js"],
    env: { type: "node", runner: "node" },
    testFramework: "jest",
    debug: true,
  };
};
```

### Code editor or IDE name and version

Visual Studio Code v. 1.34.0

### OS name and version

OSX 10.14.5

###  Jest CLI

```bash
yarn run v1.16.0
$ jest
 PASS  src/index.test.js
  ✓ should be an observable with subscription (8ms)
  ✓ should concatenate two cold observables with subscriptions (3ms)

Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.255s
Ran all test suites.
✨  Done in 3.77s.
```

### Wallaby output inside vscode

```
1 failing test, 1 passing 

  ​​​​ should concatenate two cold observables with subscriptions​​​​ ​​​[97 ms]​​​​
     
    Expected observable to have the following subscription points: 
      ["^------!"] 
    But got: 
      ["^------!", "^------!", "^------!"] 
     
    Difference: 
     
    - Expected 
    + Received 
     
      Array [ 
        "^------!", 
    +   "^------!", 
    +   "^------!", 
      ] 
     
    From console: 
       
      x 
      at cold(bObservable) ​src/index.test.js:19:2​
       
      a 
      at cold(aObservable) ​src/index.test.js:18:2​
       
      a 
      at a$.pipe(concat(b$)) ​src/index.test.js:21:2​
       
      b 
      at cold(aObservable) ​src/index.test.js:18:2​
       
      y 
      at cold(bObservable) ​src/index.test.js:19:2​
       
      b 
      at a$.pipe(concat(b$)) ​src/index.test.js:21:2​
       
      x 
      at a$.pipe(concat(b$)) ​src/index.test.js:21:2​
       
      y 
      at a$.pipe(concat(b$)) ​src/index.test.js:21:2​
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the sample repo.

The issue is caused by using live comments and causing some `jest-marbles` side effects.

Wallaby live comments have some built-in smarts to display Observable values, so

```js
const a$ = cold(aObservable); // ? 
```

internally becomes

```js
const a$ = cold(aObservable);
a$.forEach(v => {
  console.log(v);
});
```

and the code above breaks your assertion. 

The issue is not specific to Wallaby and you may reproduce the same issue by removing all live comments and pasting the snippet above, in this case Jest CLI will also produce the same result. I have sent you the pull request to reproduce the issue in Jest CLI.

So unfortunately inspecting values in an observable via Wallaby live comment or `.forEach` breaks Jest/`jest-marbles`. The best solution I can suggest is not to use live comments (or `.forEach`) on observables that are being asserted by `jest-marbles`.

**Comment by shwanton** [comment]
> The issue is caused by using live comments that are causing some jest-marbles side effects.

That was it... Thank you for helping me figure out what was going on here. 
Observables always have tricky edge case behavior!
