### ISSUE TITLE
Can't get wallaby to work with jest tests. (angular cli / nest)

### ISSUE THREAD

**Issue by appsolutegeek** [wallabyjs/public#2084]
I am trying to get wallaby to work inside of webstorm, I get a constant running icon.

![image](https://user-images.githubusercontent.com/2370364/58413045-1481ea00-8078-11e9-8837-5d3d4a062488.png)

### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'libs/**/src/**/*.ts',
      '!libs/**/src/**/*.spec.ts'
    ],

    tests: [
      'libs/**/src/**/*.spec.ts'
    ],

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'jest'
  };
};

```

but running it via the CLI then it works

![image](https://user-images.githubusercontent.com/2370364/58413125-56ab2b80-8078-11e9-9edf-07dad66a7629.png)

### Code editor or IDE name and version

WebStorm v2019.1

### OS name and version

OSX

**Comment by appsolutegeek** [comment]
Here is the jest in the root of the project

```
module.exports = {
  testMatch: ['**/+(*.)+(spec|test).+(ts|js)?(x)'],
  transform: {
    '^.+\\.(ts|js|html)$': 'ts-jest'
  },
  resolver: '@nrwl/builders/plugins/jest/resolver',
  moduleFileExtensions: ['ts', 'js', 'html'],
  collectCoverage: true,
  coverageReporters: ['html']
};
```

I am using a MONO repo with NRWL/NX but this should not make a difference .. as the jest inside each LIB is

```
module.exports = {
  name: "normal-lib",
  preset: "../../jest.config.js",
  coverageDirectory: "../../coverage/libs/normal-lib"
}

```

It just inherits from the very root.

**Comment by appsolutegeek** [comment]
I must admit, its a little slow on the commnd line too :-) 3 seconds to run this

```
  it("should be defined", () => {
    expect(true).toBeTruthy()
```

```
➜  nest-common git:(master) ✗ npx jest
 PASS  libs/nest-correlation/src/lib/correlation.service.spec.ts
  CorrelationService
    ✓ should be defined (21ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.263s, estimated 8s
Ran all test suites.
```

**Comment by appsolutegeek** [comment]
No icon visualization in the border saying coverage or not - I think its because its not finished

![image](https://user-images.githubusercontent.com/2370364/58414057-8f4c0480-807a-11e9-8299-f36c064dc63f.png)

**Comment by appsolutegeek** [comment]
Also, becasue I am using a mono repo (NX), there are node_modules in the root and under very /libs/[library_name] So I added

```
    files: [
      'libs/**/src/**/*.ts',
      '!libs/**/src/**/*.spec.ts',
      '!**/node_modules/*.*'
    ],

    tests: [
      'libs/**/src/**/*.spec.ts',
      '!**/node_modules/*.*'
    ],
```

**Comment by appsolutegeek** [comment]
My bad! - I run wallaby with DEBUG and i noticed it was important all the node_modules so I added this - I presume this is the recommended way ?

```
    files: [
      'libs/**/src/**/*.ts',
      '!libs/**/src/**/*.spec.ts',
      '!**/node_modules/**/*'
    ],

    tests: [
      'libs/**/src/**/*.spec.ts',
      '!**/node_modules/**/*'
    ],
```

My original glob above was wrong... I have now corrected to what i think is correct.

I presume I should exclude this on tests and also on files - otherwise it will search them ?

**Comment by smcenlly** [comment]
It looks like your project configuration is a little different from what we see most people using. I think the easiest thing to do to help get you up and running is for you to send us a cut-down sample repo with the same structure, packages, etc. but only a couple of dummy source/test files. 

If you prefer to get things working yourself, I have commented on a few things that you've said and provided you with links to relevant docs.

## Jest with TypeScript and Wallaby
Wallaby works a little differently than Jest in how your TypeScript is run. Jest uses ts-jest whereas Wallaby first compiles your TypeScript using the TypeScript compiler, performs its own instrumentation and then runs it in `node`. Because wallaby is performing the compilation, you should remove the `jest.transform` in your wallaby configuration (see example below).

```
setup: function (wallaby) {
      var jestConfig = require('./jest.config');
      delete jestConfig.transform;
      wallaby.testFramework.configure(jestConfig);
    }
```

You will also need to make sure that your `jest.config.js` is included in your wallaby files list.

## Nested Jest Configurations
**Your nested jest configurations will not be read for each sub-project**. Wallaby runs a single jest instance, which is your root jest configuration. All Wallaby configuration files must be at the root level of your open project. You can have multiple wallaby configuration files at the root level for sub-projects or you can configure a single wallaby/jest configuration for all projects at the root level. If you have multiple configurations for each sub-project then you will need to make sure that you copy the relevant jest configuration files in your wallaby `files` configuration.

## Wallaby and Mono Repos
If you have node modules outside of your `project root\node_modules` folder, you need to configure the node runner with additional information on how to load these. [Our docs](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) describe how to do this but I've also copied below:

For example, if you have a core subfolder with its own node modules, you may add:

```
var path = require('path');
process.env.NODE_PATH += path.delimiter + path.join(wallaby.localProjectDir, 'core', 'node_modules');
```

to your configuration file. Wallaby.js will set the setting to all created test workers, so your tests will be able to resolve local node modules from the subfolder.

**We recommend excluding `node_modules` from your `files` configuration unless the packages that you're using need a special compile-time transformation (e.g. they're written in TypeScript but not transpiled to Javascript)**

## Wallaby Indicators Missing
The continous progress icon and lack of coverage indicators seems to indicate that there's something wrong with your configuration and wallaby is never finishing its test run. Adding the Wallaby `debug` flag set to `true` in your configuration file might point you in the right direction. 

---

If you're still stuck and trying to configure this yourself, please send us your wallaby configuration file, details of your project structure, full `jest` configuration and `package.json`. We're happy to help!

**Comment by ArtemGovorov** [comment]
You may also take a look into this repo https://github.com/Steven-Harris/nrwl-jest-wallaby/blob/master/wallaby.js (where we have been helping one of our users to get his similar stack config working).

**Comment by appsolutegeek** [comment]
@ArtemGovorov @smcenlly Thanks for all the help, I now have it setup correctly and working.

I setup the mono repo adding of additional node_modules, as per your comment, I think its working

```
  /*** Start for processing multiple node_modules (mono repo) ***/
  const isDirectory = source => lstatSync(source).isDirectory()

  const getDirectories = source =>
    readdirSync(source)
      .map(name => join(source, name))
      .filter(isDirectory)
      .filter(source => existsSync(join(source, "node_modules")))

  const nodeModuleDirs = [...getDirectories(join(__dirname, "apps")), ...getDirectories(join(__dirname, "libs"))]

  for (const dir of nodeModuleDirs) {
    process.env.NODE_PATH += delimiter + join(dir, "node_modules")
  }
  /*** End for processing multiple node_modules (mono repo) ***/
```
