### ISSUE TITLE
No gutter coverage

### ISSUE THREAD

**Issue by ha404** [wallabyjs/public#2091]
### Issue description or question

None of my coverage is getting picked up in the gutter:
<img width="59" alt="Screen Shot 2019-05-29 at 10 28 46 AM" src="https://user-images.githubusercontent.com/567126/58578026-aca8dc00-81fc-11e9-943a-ad3d82209000.png">

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => {
  return {
    files: ['src/**/*.js', '!src/**/__tests__/*.js', 'testing/jest.setup.js', 'src/**/*.gql'],
    tests: ['src/**/__tests__/*.js'],
    workers: {
      initial: 2,
      regular: 2,
      restart: true,
    },
    env: {
      type: 'node',
      runner: 'node',
    },
    testFramework: 'jest',
    compilers: {
      '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') }),
    },
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v1.34.0

### OS name and version

OSX 10.14.3

**Comment by smcenlly** [comment]
We're going to need a little more information in order to be able to help you. Could you please add another setting to your wallaby configuration `debug: true` and then provide the following:

1) Your `package.json` file
2) Your `jest` configuration (if outside of `package.json`)
3) Your `babel` configuration (if you use babel)
4) The output of your `Wallaby Console` and `Wallaby Tests` output windows
5) Details of where you're not seeing indicators (test files and code files? or just code files?)
6) A screenshot/snippet of the actual code where you're not seeing indicators

Instead of providing the above, it would minimize turn-around time if you're able to provide us with a simple sample repo that has the same problem.

**Comment by korniychuk** [comment]
Hello! I have the same problem, however only for files with code, .spec files covered.
It happens when I compile my project via webpack. It looks like I did some wrong configuration.

![image](https://user-images.githubusercontent.com/11693557/58822689-c2753180-8640-11e9-89d3-5490debd8381.png)

**Web Storm:** 2019.1.3
**OS:** 10.14.4
**Wallaby.js** core v1.0.693
**Wallaby Node version:** v10.15.0

**wallaby.conf.js:**
```javascript
'use strict';

const wallabyWebpack = require('wallaby-webpack');
const webpackMerge   = require('webpack-merge');

const commonConfig = require('./webpack.common')({ env: 'test' });

const wallabyPostprocessor = wallabyWebpack(
  webpackMerge(
    commonConfig,
    {
      entryPatterns: [
        // 'src/**/*.js',
        'src/**/*.spec.js',
      ],
    },
  ),
);

module.exports = function (w) {

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.spec.ts', ignore: true },
    ],

    tests: [
      { pattern: 'src/**/*.spec.ts', load: false },
    ],


    postprocessor: wallabyPostprocessor,

    testFramework: 'mocha',


    env: {
      kind:   'chrome',
      // runner: '/Users/user/path/to/chrome',
      params: { runner: '--web-security=false --headless' }
    },


    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true,

  };
};
```

I created a separate branch with minimal code example https://github.com/z-brain/calc/tree/wallaby.js-broken-caverage

Thanks!

**Comment by korniychuk** [comment]
Hello, @smcenlly ! I have the same problem, however only for files with code, .spec files covered.
It happens when I compile my project via webpack. It looks like I did some wrong configuration.

![image](https://user-images.githubusercontent.com/11693557/58822689-c2753180-8640-11e9-89d3-5490debd8381.png)

**Web Storm:** 2019.1.3
**OS:** 10.14.4
**Wallaby.js** core v1.0.693
**Wallaby Node version:** v10.15.0

**wallaby.conf.js:**
```javascript
'use strict';

const wallabyWebpack = require('wallaby-webpack');
const webpackMerge   = require('webpack-merge');

const commonConfig = require('./webpack.common')({ env: 'test' });

const wallabyPostprocessor = wallabyWebpack(
  webpackMerge(
    commonConfig,
    {
      entryPatterns: [
        // 'src/**/*.js',
        'src/**/*.spec.js',
      ],
    },
  ),
);

module.exports = function (w) {

  return {
    files: [
      { pattern: 'src/**/*.ts', load: false },
      { pattern: 'src/**/*.spec.ts', ignore: true },
    ],

    tests: [
      { pattern: 'src/**/*.spec.ts', load: false },
    ],


    postprocessor: wallabyPostprocessor,

    testFramework: 'mocha',


    env: {
      kind:   'chrome',
      // runner: '/Users/user/path/to/chrome',
      params: { runner: '--web-security=false --headless' }
    },


    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true,

  };
};
```

I created a separate branch with minimal code example https://github.com/z-brain/calc/tree/wallaby.js-broken-caverage

Thanks!

**Comment by smcenlly** [comment]
Thanks for the sample repo, I'm not sure if this is the same problem that @ha404 had, so I will leave the issue open. In your case, since you are using TypeScript, you need to remove the `.ts` extension from your webpack `resolve.extensions` (there's a brief section with a sample on this in [our docs](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript)).

In your case, you can fix the error by updating your `config\wallaby.conf.js` as shown below

```diff
 'use strict';

  const wallabyWebpack = require('wallaby-webpack');
  const webpackMerge   = require('webpack-merge');

  const commonConfig = require('./webpack.common')({ env: 'test' });

+ commonConfig.resolve.extensions = commonConfig.resolve.extensions
+   .filter(item => item !== '.ts');

  const wallabyPostprocessor = wallabyWebpack(
    webpackMerge(
      commonConfig,
      {
        entryPatterns: [
          // 'src/**/*.js',
          'src/**/*.spec.js',
        ],
      },
    ),
  );
...
```

Please note that the wallaby runtime expects all wallaby configuration to be referenced in the project root `wallaby.conf.js` file and includes a mechanism that automatically resets its cache when this file changes. You may need to change the wallaby configuration file content (`wallaby.conf.js` in your project root) after applying this change. Just adding a space somewhere inside it will be sufficient.

**Comment by ha404** [comment]
It's okay, my issue magically fixed itself. Thanks!

**Comment by korniychuk** [comment]
@smcenlly Thanks a lot! It works :)
