### ISSUE TITLE
Test framework [mocha] is not supported

### ISSUE THREAD

**Issue by NodeGuy** [wallabyjs/public#211]
I'm trying to get started with Wallaby.  I purchased WebStorm and installed the Wallaby 1.0.25 plugin.

I created a new project with the following `wallaby.json`:

```JSON
{
  "files": [
    "lib/*.js"
  ],

  "tests": [
    "test/*.js"
  ],

  "testFramework": "mocha"
}
```

When I run the Wallaby configuration I get the following error message:

`Test framework [mocha] is not supported`

**Comment by ArtemGovorov** [comment]
When wallaby.js starts, it prints its core version to the Wallaby Console tab, what version does it print for you?

**Comment by ArtemGovorov** [comment]
If the printed version is not the latest (v1.0.82) and you have previously installed wallaby.js, please try stopping wallaby.js, clearing its cache folder and starting it again.
On Mac OSX the cache folder is here: `~/Library/Caches/WebStorm10/wallaby` folder. 
On Windows the cache folder is here: `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.<PRODUCT><VERSION>\system\wallaby` folder.

It also looks from your config that you are testing a node.js app, so you need to [specify env.type setting](http://wallabyjs.com/docs/integration/node.html) as well, otherwise wallaby will try to run your tests using PhantomJs.

**Comment by NodeGuy** [comment]
The Wallaby Console tab doesn't print a core version number:

<img width="644" alt="screen shot 2015-07-27 at 2 18 14 pm" src="https://cloud.githubusercontent.com/assets/2148537/8913993/79237d38-346a-11e5-9945-a4493a27b41c.png">

When I download the latest from the front page of your website I get `wallaby-intellij-v1.0.25.zip`.

Clearing the cache fixed the problem and now Wallaby reports "core v1.0.83".

Thanks for the tip about the env.type setting.
