### ISSUE TITLE
Event Handler issues with Wallaby.js

### ISSUE THREAD

**Issue by petermierau** [wallabyjs/public#2130]
### Issue description or question
I'm testing code that attaches and removes event handlers onto the window object. However this is causing reoccurring problems where Wallaby.js reports that some long running code has been detected.

I'm afraid that different test cases event handlers are messing things up. (An event handle meant for B is being picked up by Class A instead.) 

```
class PortManager{
    constructor(){
        this._createPorts();
        this._createMessageResponder();
        this._createTemporaryMessageSystem();
    }

    _createPorts(){
        let messagePorts = new MessageChannel();
        this._port = messagePorts.port1;
        this._clientPort = messagePorts.port2;
    }

    _createTemporaryMessageSystem(){
        window.addEventListener("message",this._passPortAndTearDown.bind(this),false);
    }

    _passPortAndTearDown(event){
        window.removeEventListener("message",this._passPortAndTearDown,false);
        let iframe = document.getElementsByTagName("iframe")[0];
        console.log(iframe);
        iframe.contentWindow.postMessage("",'*',[this._clientPort]);
    }

    _createMessageResponder(){
        this._port.onmessage = this._handleMessage.bind(this);
    }

    _handleMessage(event){
        let command = this._getCommand(event.data);
        let response = null;
        if(command === "openFile") response = openCommandManager(event.data);
        else if(command === "createFile") response = createFileCommandManager(event.data);
        else if(command === "closeFile") response = closeFileCommandManager(event.data);
        else if(command === "deleteFile") response = deleteFileCommandManager(event.data);
        else if(command === "writeData") response = writeDataCommandManager(event.data);
        this._send(response);
    }

    _getCommand(eventData){
        return eventData.command;
    }

    _send(response){
        this._port.postMessage(response);
    }
}
```

Testing for if addEventListener is called is one mocha test. Notice that this test never reaches the eventListener teardown phase. So I'm thinking that these eventListeners are carried thru the other tests, thereby interfering with other tests.

I want a way to reset the global testing scope when a testing files that modify the global event handlers, so that I don't have ghost event handlers.

Example     
### Wallaby.js configuration file

```
// Wallaby.js configuration

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack({
    mode: 'development',
    entry: './src/index.js',
    output: {
        filename: 'main.js',
    },
    devtool: 'source-map'
    }
);

module.exports = function (wallaby) {
    return {
        // set `load: false` to all source files and tests processed by webpack
        // (except external files),
        // as they should not be loaded in browser,
        // their wrapped versions will be loaded instead
        files: [
            // {pattern: 'lib/jquery.js', instrument: false},
            {pattern: 'src/**/*.js', load: false}
        ],

        tests: [
            {pattern: 'test/**/*Spec.js', load: false}
        ],

        testFramework: 'mocha',
        env: {
            kind: 'chrome'
        },
        debug:false,

        postprocessor: wallabyPostprocessor,

        setup:function () {
            // required to trigger test loading
            let mocha = wallaby.testFramework;
            mocha.ui("tdd");
            window.__moduleBundler.loadTests();
        },
        hints: {
            ignoreCoverageForFile: /ignore file coverage/,
            ignoreCoverage : /ignore coverage/
        },
    };
};
```

### Code editor or IDE name and version

WebStorm v2019.1.1

### OS name and version

Linux Fedora 30

**Comment by smcenlly** [comment]
Without looking at your entire project, it's difficult to figure out what's going wrong. If I had to guess, I'd suggest that you have at least one test that creates a new instance of `PortManager` that doesn't call `window.message`.

If you haven't already done so, please also check your Wallaby console for errors. It will appear as a tab within Wallaby's execution results window in WebStorm. You may also try setting the wallaby `debug` [setting](https://wallabyjs.com/docs/config/overview.html#debug-setting) to `true` for additional information about your execution run that may assist you.

Your wallaby configuration's [setup](https://wallabyjs.com/docs/config/bootstrap.html#setup-function) and [teardown](https://wallabyjs.com/docs/config/bootstrap.html#teardown-function) functions allow you to configure your testing framework/sandbox environment before a test run starts and when a test run ends. You may re-initialize your event listener in the setup function or remove it in the teardown function.

If the information above doesn't help, are you able to provide us with a sample repo?

**Comment by petermierau** [comment]
That is intentional by default since I'm testing that other features of code work. 

I already use the setup function and since I'm using Chrome as my testing enviroment I don't have access to the teardown (since that's just for Node.js according to the docs).

Here is the repo, commit that provides https://github.com/petermierau/WolfPack-OS/commit/2f418f1f255338219170d2d52586c2f452e650d5 `Some long running code has been detected: one of your tests is taking more than 5000ms to execute.
The last recorded console.log: undefined`

However commenting out one of the problematic tests in BridgeClientSpec or BridgeServerSpec causes this issue to appear:
`Some long running code has been detected: test "should cache the last item stored with the same name only" is taking more than 5000ms to execute.
The last recorded console.log: undefined
Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,
and restarting wallaby to make sure that it is this test/file causing the issue and not something else.
Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.
Pinging test runner sandbox...
Sandbox is responsive. The issue may have the asynchronous nature, like a missing callback.`
The code that is apparently slow now is Cache.js being tested with CacheSpec.js. CacheSpec.js wasn't touched whatsoever so there should be no reason that it's now spontaneously failing.

Please tell me how I can fix it.

**Comment by ArtemGovorov** [comment]
Thanks for providing the repo. 

Some of your tests are actually failing and mocha is not reporting them as failing (and mocha breaks after encountering such test and can't run any more tests after it causing the `Some long running code has been detected` hangs). 

When this test https://github.com/petermierau/WolfPack-OS/commit/2f418f1f255338219170d2d52586c2f452e650d5#diff-22e266075bd6f172e72539dd6bdb467cR35 runs, it both is failing synchronously (this [iframe doesn't exist](https://github.com/petermierau/WolfPack-OS/blob/wallaby/coreIssue/src/libs/BridgeServer.js#L78)) in the middle and yet fully completes executing. This is possible because [dispatchEvent/addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent#Return_Value) used in your code have the following behavior: `Exceptions thrown by event handlers are reported as uncaught exceptions; the event handlers run on a nested callstack: they block the caller until they complete, but exceptions do not propagate to the caller.` Because of that, Mocha gets confused because test is both reporting an error and successfully finishes its execution, and can not execute any more tests after this one.

The issue is not specific to Wallaby (plain mocha in browser behaves the same way). However we have managed to fix Wallaby integration with mocha to correctly handle this case. 
The fix is available [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), and once you update, you should see correct results (2 failing tests in this case):

<img width="1047" alt="Screen Shot 2019-07-09 at 2 46 04 pm" src="https://user-images.githubusercontent.com/979966/60860087-4f229900-a258-11e9-96f6-121949297f43.png">

**Comment by petermierau** [comment]
Thank you so so much! This is something that I would have never caught myself.

You help and support and response is extremely top notch!
You've gotten yourself a permanent customer!

😁 Thanks for solving something I would have never gotten myself!
