### ISSUE TITLE
No Chrome Installations Found - MacOS 10.15 Beta

### ISSUE THREAD

**Issue by denizcoskun** [wallabyjs/public#2138]
### Issue description or question

I am getting the following error after upgrading to MacOS Catalina Beta. Could you help me out? Thank you.

```
[Info]  Started Wallaby.js Core v1.0.610
[Info]  Wallaby App (realtime reports) is available at: http://localhost:51245
[Error] Error: No Chrome Installations Found 
[Error]     at process._tickCallback (internal/process/next_tick.js:68:7) 
```

### Wallaby.js configuration file

I use this repo: https://github.com/wallabyjs/ngCliWebpackSample

### Code editor or IDE name and version

Visual Studio Code v 1.36.1

### OS name and version

OSX Catalina 10.15 Beta

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This is fixed in the latest version of wallaby core, v1.0.709. You should receive the update automatically when you next restart your editor. If for some reason wallaby doesn't update for you, you may [force wallaby.js core to update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Just for the sake of documentation, another option for you would have been to explicitly set the Chrome runner path in your wallaby.js configuration file ([mentioned in our docs](https://wallabyjs.com/docs/integration/chrome.html)). For example:

```
module.exports = function () {
  return {
...
    env: {
      kind: 'chrome',
      runner: '/Users/user/path/to/chrome'
    }
...
  };
};
```
