### ISSUE TITLE
Fails to process tests with iterator and yield

### ISSUE THREAD

**Issue by FourSpotProject** [wallabyjs/public#2171]
### Issue description or question
When using an iterator with yield inside, Wallaby.js does not process those tests and fails to execute it when using the spread operator:

![wallabyjsiteratorbug](https://user-images.githubusercontent.com/4338556/62525506-d6ebcb00-b837-11e9-9e10-39b96b821fea.png)

Line 8 is shown as not covered and in line 12 an error is displayed ('TypeError: instance.permute(...).slice is not a function').
However, the test runs using Jest.

A bug repo is available here: https://github.com/FourSpotProject/wallabyjsiteratorbug

### Versions

Windows 10
Visual Studio Code v1.36.1
Wallaby.js core: v1.0.714
Wallaby.js App v1.0.61

Cheers :)

**Comment by smcenlly** [comment]
Thanks for the sample repo. Please switch your project to use our new [automatic configuration feature](https://wallabyjs.com/docs/intro/config.html#automatic-configuration). This feature is currently only available for Jest v24+, but your project meets those requirements.

In order to use automatic configuration, `npx jest` needs to successfully run your tests in your project directory. In your case, this doesn't work because your jest config, `jest.conf.js` is a not the standard configuration filename that is found automatically by jest.

To switch to using automatic configuration, please do the following:
1) Delete `wallaby.conf.js`
2) Rename `jest.conf.js` to `jest.config.js` (as per [jest docs](https://jestjs.io/docs/en/configuration))
3) In in VS Code, run the `Wallaby.js: Select Configuration` command and then select `Automatic Configuration <project directory>`.

If you are using Wallaby with Jest v24+ in other projects, you can do the same for those projects as well.

**Comment by FourSpotProject** [comment]
Perfect, works like a charm again. Thanks!
