### ISSUE TITLE
Live Comments for CoffeeScript

### ISSUE THREAD

**Issue by Alexsey** [wallabyjs/public#2177]
The docs are saying that Live Comments are not available in CoffeeScript due to [this issue](https://github.com/jashkenas/coffeescript/issues/2365) but, actually, it has been resolved more than two years ago

**Comment by smcenlly** [comment]
Thanks for letting us know about the update. This may fix live comments in some places, but after some testing, it appears mostly broken. Take the following example:

**CoffeeScript**
```coffeescript
###
COMMENT WORKS
###

describe 'Student', ->
  it 'should report grade', ->
    student = new Student score: 75; # NO COMMENT IS OUTPUT
    expect(student.grade()### COMMENT IS IN THE WRONG PLACE ###).toBe('C')
```

**Compiler Output**
```javascript
  (function() {
    /*
    BLOCK COMMENT
    */
    describe('Student', function() {
      return it('should report grade', function() {
        var student;
        student = new Student({
          score: 75
        });
        return expect(student.grade())./* COMMENT IS IN THE WRONG PLACE */toBe('C');
      });
    });
  }).call(this);
```

---

We will update our docs to indicate that Live Comments don't work due to CoffeeScript's comment migration behavior.
