### ISSUE TITLE
Ionic 5 / Angular 8

### ISSUE THREAD

**Issue by derekkinzo** [wallabyjs/public#2181]
### Issue description or question
Configure wallaby for ionic project. See repo here: https://github.com/derekkinzo/ionic-wallaby

### Wallaby.js configuration file
https://github.com/derekkinzo/ionic-wallaby/blob/master/wallaby.js

### Code editor or IDE name and version
Visual Studio Code v1.37.1

### OS name and version
OSX Mojave 10.14.6

**Comment by smcenlly** [comment]
Thanks for the sample repo! The reason this isn't working is because your `polyfills.ts` file is referencing zone-flags with a TypeScript file extension (`.ts`). You can fix this by changing your import:

```diff
- import './zone-flags.ts';
+ import './zone-flags';
```

With that change, everything will work for you.

Wallaby for webpack does not support file imports with explicit .ts extension, because Wallaby's TypeScript compiler renames .ts files to .js. You could add a preprocessor to rename compiled files back to .ts, but removing the `.ts` should work for you (with and without Wallaby). You can read more in [this previous issue](https://github.com/wallabyjs/public/issues/2055#issuecomment-482765666).

---

Regarding your other issue that you mention in our forums, `asset.slice is not a function.`:

This issue was caused by our configuration assuming that your test assets were limited to [file-based assets and not globs](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/asset-configuration.md#project-assets). We've update our configuration to only work for file-based assets which means that you may use the configuration from our website without any changes. If you need access to assets from your tests, then you will have to configure them to be loaded in the middleware section.

**Comment by derekkinzo** [comment]
Worked great. Thanks!
