### ISSUE TITLE
Wallaby reports "Jest encountered an unexpected token"

### ISSUE THREAD

**Issue by natan-mobileheartbeat** [wallabyjs/public#2195]
### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

Visual Studio Code v1.?
WebStorm v?
IntelliJ IDEA v?
Atom v1.?
Visual Studio v?
Sublime Text v3 build ?

### OS name and version

Windows
OSX
Linux

**Comment by natan-mobileheartbeat** [comment]
Hi @ArtemGovorov ,
Wallaby was working great in recent weeks. As of yesterday we can't get it to work. This is the error 
I am running the latest version of wallaby 1.0.136
that we get for every single test:
```
Jest encountered an unexpected token

This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

Here's what you can do:
 • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
 • If you need a custom transformation specify a "transform" option in your config.
 • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

You'll find more details and examples of these config options in the docs:
https://jestjs.io/docs/en/configuration.html

Details:
./setupTests.js:1
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { configure } from 'enzyme';
                                                                                                ^

SyntaxError: Unexpected token {

	at setupTests.js:1
```

Please advise,
Natan

**Comment by ArtemGovorov** [comment]
Not sure what the issue is caused by, but it looks like it may be one of your dependency updates or some changes in your project.

I have tried your sample project https://github.com/natan-mobileheartbeat/wallaby-setup and Wallaby is working for me on it (I have also tried renewing `react-scripts` just in case, but Wallaby is also working). Could you please try your sample repo to see if it's still working for you, and if it is, please update the sample repo so we could reproduce the issue.

**Comment by natan-mobileheartbeat** [comment]
Thanks for you response. I will look into that.
