### ISSUE TITLE
describe.only and it.only are not recognized

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#224]
both these cases work ok on Karma (and normal mocha runner)

![image](https://cloud.githubusercontent.com/assets/656739/9028170/788e4f7e-396f-11e5-88b1-085e930e1102.png)

![image](https://cloud.githubusercontent.com/assets/656739/9028168/6021063e-396f-11e5-871b-e2e1960aa0f1.png)

**Comment by ArtemGovorov** [comment]
It should work:

![only](https://cloud.githubusercontent.com/assets/979966/9029067/ccb76b16-39cf-11e5-9618-5281dfdfc525.gif)

Perhaps you didn't set `testFramework` to `mocha` in your config? It's using Jasmine by default for browser tests. Jasmine's equivalent for `.only` is `fit` and `fdescribe`.

![only](https://cloud.githubusercontent.com/assets/979966/9029114/c381372e-39d0-11e5-821e-5dba7b15e61d.gif)

**Comment by DinisCruz** [comment]
great setting the framework on the config file did the trick

![image](https://cloud.githubusercontent.com/assets/656739/9083570/4446a680-3b63-11e5-8768-750010db651f.png)

Thanks

**Comment by DinisCruz** [comment]
Humm, now I have the side effect that the errors are not showing in the UI (only on the Failing tests window)

![image](https://cloud.githubusercontent.com/assets/656739/9086745/1e0a55e6-3b7e-11e5-97ef-5b4565e5628b.png)

Any idea why?


Note: if I remove the 'mocha' reference in the config file

```coffee
module.exports = (wallaby)->
  console.log '[in Wallaby]'

  config =
    files : [ 'bower_components/angular/angular.js'
              'bower_components/angular-route/angular-route.js'
              'bower_components/angular-mocks/angular-mocks.js'
              'bower_components/angular-foundation-bower/mm-foundation-tpls.min.js'
              'bower_components/angular-slider/slider.js'
              'bower_components/angular-ui-router/release/angular-ui-router.min.js'
              'bower_components/chai/chai.js'
              'bower_components/sinonjs/sinon.js'
              'src/**/*.coffee'  ]
    tests : [
              'test/**/*.coffee' ]

    #testFramework: 'mocha'

  return config
```

it works as expected 

![image](https://cloud.githubusercontent.com/assets/656739/9086783/67fb996c-3b7e-11e5-800f-412144410970.png)

**Comment by ArtemGovorov** [comment]
@DinisCruz Karma behaves the same way. It's [mocha + angular-mocks issue](https://github.com/mochajs/mocha/issues/1677). When an error is thrown by chai inside the `inject` function, the function wraps the error making it not inherit from `Error` anymore, and this makes mocha unhappy. You may find more details in the related issue.

When you comment out the `testFramework: 'mocha` in the config file, you are changing the testing framework to jasmine (it's the default value for browser tests) and jasmine doesn't have the issue, so it works. If your tests are testing framework agnostic, and it seems they are, you may keep using Jasmine + chai if you like. A few things will work differently though. For example, as I have mentioned earlier, jasmine doesn't have `it.only` and `describe.only`, but has [`fit` and `fdescribe`](http://jasmine.github.io/2.1/focused_specs.html) instead.

P.S. I have noticed you have listed your bower components in your config file without setting [`instrument: false` flag](http://wallabyjs.com/docs/config/files.html#file-object). It makes wallaby to instrument and collect the code coverage for them as well (you may actually open `bower_components/angular/angular.js` and others and see the code coverage). I'd recommend setting the flag to false for the libraries, so that wallaby doesn't do unnecessary work (assuming that you don't really need the code coverage for all those files) and may execute your tests even faster.
