### ISSUE TITLE
Bug: reportConsoleErrorAsError not reporting console.error as failing test

### ISSUE THREAD

**Issue by thehig** [wallabyjs/public#2251]
I opened [this](https://github.com/wallabyjs/public/issues/1686) issue a while back, and it's happening again. I have updated the same repository and it exhibits the same issue as before 

Sample Repo: https://github.com/thehig/wallaby-report-error

**Comment by smcenlly** [comment]
Thanks for reporting the error. Something had changed in the latest version of `jest` that had broken our integration that reports console errors as test failures.

This is fixed in the latest version of Wallaby core (v1.0.770). Wallaby should update automatically when you restart your editor. If it does not update, you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

I also saw that your project is compatible with our [automatic configuration](https://wallabyjs.com/docs/intro/config.html) feature, which will allow you to use Wallaby without a configuration file. Having said that, automatic configuration does not support reporting console errors using the `reportConsoleErrorAsError` setting. 

If you want to switch to use automatic configuration, you can duplicate the `reportConsoleErrorAsError` behavior by creating a `src/setupTests.js` file and setting the content to:

```javascript
const spy = jest.spyOn(global.console, 'error')

afterAll(() => {
  expect(spy).not.toHaveBeenCalled();
});
```
