### ISSUE TITLE
Documentation is wrong

### ISSUE THREAD

**Issue by jmb-qhr** [wallabyjs/public#2270]
### Issue description or question

PLEASE NOTE: If you are using If you are using Jest >= v24 or Angular CLI >= v8.2 and using a
wallaby configuration file, switching to use automatic configuration may resolve your problem.

https://wallabyjs.com/docs/intro/config.html#automatic-configuration

The wallabyjs documentation states that an Angular project with a version greater than 8.2 will be able to use the automatic configuration feature. This appears to be wrong as I am currently running a project with Angular 8.2.8. Angular 8.2.8 comes with Webpack 4.35.2 which is a lower version than your auto configuration allows for. I think that the documentation should be updated with either correct Angular versions, or at least state that you will have to find a way of updating webpack that won't piss off your Angular dependencies.

**Comment by smcenlly** [comment]
The documentation is correct, referring to `Angular CLI` version v8.2+, not the `@angular/core` package or some other angular package. I am assuming your are incorrectly referring to the version because `Angular CLI` does not have a version 8.2.8 (latest 8.2.x is 8.2.2). If you have used [Angular CLI](https://cli.angular.io/) (>= v8.2.0) to generate your project, then automatic configuration will work for you.

If you have an older Angular project or a project that was not generated using the Angular CLI tool, you may [configure Wallaby to run your Angular project using a configuration file](https://wallabyjs.com/docs/integration/angular.html#manual-configuration-wallabyjs-file).

If you have trouble configuring your project with a configuration file, let us know, we're happy to help.
