### ISSUE TITLE
Tried running wallabyjs on Lodash Library source code to get a better insight of the source code which resulted in following error

### ISSUE THREAD

**Issue by agarwalprashant** [wallabyjs/public#2272]
### Issue description or question

[Error] Runtime error: .\test\Strings-category-methods.test.js:2 
[Error] import assert from 'assert'; 
[Error]        ^^^^^^ 
[Error] SyntaxError: Unexpected identifier 
[Error]     at Module._compile (internal/modules/cjs/loader.js:721:23) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:653:32) 
[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3) 
[Error]     at Module.require (internal/modules/cjs/loader.js:690:17) 
[Error]     at require (internal/modules/cjs/helpers.js:25:18) 
[Error]     at .\node_modules\mocha\lib\mocha.js:250:27 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at Mocha.loadFiles (.\node_modules\mocha\lib\mocha.js:247:14) 
[Error]     at Mocha.run (.\node_modules\mocha\lib\mocha.js:576:10) 
[Error]     at WebSocket.emit (events.js:198:13) 
[Error]     at afterWrite (_stream_writable.js:485:3) 
[Error]     at onwrite (_stream_writable.js:476:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3) 
[Error]     at Zlib.processCallback (zlib.js:548:8) 
[Info]  2019-11-16T03:57:53.499Z workers Sandbox (active) [vnskn] error: Unexpected identifier
[Error] Runtime error: .\test\Arrays-category-methods.js:2 
[Error] import assert from 'assert'; 
[Error]        ^^^^^^ 
[Error] SyntaxError: Unexpected identifier 
[Error]     at Module._compile (internal/modules/cjs/loader.js:721:23) 
[Error]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10) 
[Error]     at Module.load (internal/modules/cjs/loader.js:653:32) 
[Error]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12) 
[Error]     at Function.Module._load (internal/modules/cjs/loader.js:585:3) 
[Error]     at Module.require (internal/modules/cjs/loader.js:690:17) 
[Error]     at require (internal/modules/cjs/helpers.js:25:18) 
[Error]     at .\node_modules\mocha\lib\mocha.js:250:27 
[Error]     at Array.forEach (<anonymous>) 
[Error]     at Mocha.loadFiles (.\node_modules\mocha\lib\mocha.js:247:14) 
[Error]     at Mocha.run (.\node_modules\mocha\lib\mocha.js:576:10) 
[Error]     at WebSocket.emit (events.js:198:13) 
[Error]     at afterWrite (_stream_writable.js:485:3) 
[Error]     at onwrite (_stream_writable.js:476:7) 
[Error]     at InflateRaw.afterTransform (_stream_transform.js:94:3) 
[Error]     at Zlib.processCallback (zlib.js:548:8) 

Below is my wallaby configuration file - 

module.exports = (wallaby) => {
  return {
    files: [

      { pattern: 'node_modules', instrument: false },
      '*.js'

    ],
    tests: [
      'test/*.js'
    ],
    testFramework: 'mocha',
    setup: function (wallaby) {
      // wallaby.testFramework is jasmine/QUnit/mocha object
      wallaby.testFramework.ui('tdd');

      // you can access 'window' object in a browser environment,
      // 'global' object or require(...) something in node environment
    },

    env: {
      // kind: 'chrome'
      type: 'node'
    },
    debug: true,
    trace: true
  };
};

**Comment by agarwalprashant** [comment]
My Node version is  - v10.16.0

**Comment by smcenlly** [comment]
We've created a configuration file for you that will work with the lodash library. There were a few weird things going on in the tests for lodash that we needed to account for, (1) manually specify the loadash node_modules library, and (2) push to process arguments (`argv`) that was expected by `test\utils.js`. We also updated your configuration file to use `esm`, also used by the `test:wip` package script.

```javascript
module.exports = function() {
  return {
    files: [
      '*.js', 
      '.internal/*.js', 
      { pattern: 'node_modules/lodash/**/*.js', instrument: false }, 
      'test/*.js', 
      '!test/*.test.js', 
      '!wallaby.js'
    ],

    tests: ['test/*.test.js'],

    env: {
      type: 'node',
      params: {
        runner: `-r ${require.resolve('esm')}`
      }
    },

    setup(w) {
      const path = require('path');
      const lodashPath = path.join(w.localProjectDir, 'node_modules/lodash/lodash.js');
      process.argv[process.argv.length - 1] !== lodashPath && process.argv.push(lodashPath);
    }
  };
};
```

**Comment by agarwalprashant** [comment]
Thanks **@smcenlly** for your quick reply. Although that configuration file works perfectly for lodash source code, I am getting one small error in wallabyjs tests console which I am pasting down below - 

```
1 failing test, 397 passing  ​Launch Coverage & Test Explorer​
  
  ​​​​merge should treat sparse array sources as dense​​​​ ​​​[2 ms]​​​​
     
    false == true 
      at Context.<anonymous> ​test/merge.test.js:125:4​
```

**Comment by smcenlly** [comment]
Yes - we got the same error. This is an existing error in the lodash codebase. You will get the same error running `npm test:wip`.

**Comment by agarwalprashant** [comment]
@smcenlly  I appreciate your help. BTW, awesome tool. :)

**Comment by agarwalprashant** [comment]
With the **above-provided configuration file**, wallaby does not run on any of the test files ending with .js extension in the test folder, for example, compact.js ( C:\Users\Prashant\Desktop\javascript-workspace\lodash\test\compact.js ) or unzipWith.js ( C:\Users\Prashant\Desktop\javascript-workspace\lodash\test\unzipWith.js). Wallaby only cover test files with extensions *.test.js.

I am attaching a screenshot of the to better explain the issue.
![Capture](https://user-images.githubusercontent.com/8237463/69168707-333fd580-0b1d-11ea-9f06-c4e119e42b69.PNG)

**Comment by smcenlly** [comment]
The configuration file that we provided mimicked the tests that were running from the package using `npm run test:wip`. The number of tests passing/failing are the same between the wallaby configuration file and the lodash package run script.

We cannot determine how to run the other tests in the lodash library outside of wallaby (`npm run test` fails, as does `npm run test:fp` and `npm run test:main`). In fact, many of the files that contain tests that don't have the `.test.js` suffix appear to be broken (which we assume is why they don't have the suffix). For example, `compact.js` will error with `identity is not defined` because no variable is defined before it is used on line 32.

We took a look at a few other files in the test directory without the `.test.js` suffix and they also had problems that stopped them from running:

* `test/__proto__-property-bugs.js`: will error on line 48 (groupBy) because the second parameter being passed is a string and groupBy is expecting a function.
* `test/ary.js`: will error on line 4 because `../ary.js` file does not exist.
* `test/assignIn.js`: will error on line 2 because `../extend.js` file does not exist.

It's probably best to contact the lodash team to understand the state of their tests and why they're broken. You may update your Wallaby configuration test patterns to tell it to run the additional tests but because they are so broken, Wallaby is not able to start.

If you're simply playing around with the project, the easiest way to see this for yourself is to add the suffix `.test.js` to those files you want to see execution results. For example, rename `compact.js` to `compact.test.js`.
