### ISSUE TITLE
Annotations produced by wallabyjs are not shown completely

### ISSUE THREAD

**Issue by agarwalprashant** [wallabyjs/public#2273]
### I am attaching a screenshot of my VSCODE editor to better explain the issue

![array-flatten - wallabyjs](https://user-images.githubusercontent.com/8237463/68995958-af39e380-08b9-11ea-9970-d80cbab047fd.PNG)

Line 21 on the left side shows string 'test' being passed to **flattenDown** function on the right-hand side window. Ideally,on line 80 the variable value should show 't','e','s','t' and result variable on line 86 should show ['t'] ['t','e'] ['t','e','s'] ['t','e','s','t'] annotations produced by wallaby,but it does not show the annotations as expected.Is this a bug?? Please correct me If I am wrong anywhere.

For more clarity on the issue I am attaching a screenshot of annotations produced by quokkajs on the same file.

![Capturequokka](https://user-images.githubusercontent.com/8237463/68996070-1906bd00-08bb-11ea-90e8-26b4d8d8e843.PNG)

**Comment by ArtemGovorov** [comment]
There are [a few ways to log expressions](https://wallabyjs.com/docs/intro/advanced-logging.html) in Wallaby and Quokka. Identifier expression logging, ie. when you type `a` to log its value, only logs the first value in Wallaby by design (in Quokka it logs all values). 

This is done to avoid slowing down your tests by undesired logging when you're typing a variable name, and keep typing to access its methods/properties. In Quokka it is less of a concern due to a smaller/faster samples.

In order to get the expected result, you may use live comment on line 80: 
```
value//?
``` 
(or `console.log(value)`)

**Comment by agarwalprashant** [comment]
Thanks for your quick reply. console.log(value) seems to work as expected. For some reason though, 
 //? or /*?*/ still seems to log just the first value.

**Comment by ArtemGovorov** [comment]
> For some reason though, //? or /?/ still seems to log just the first value.

Try updating Wallaby core to [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update), it should help.
