### ISSUE TITLE
Copy large amount of files into instrumented folder (that don't get deleted on re-run)

### ISSUE THREAD

**Issue by DinisCruz** [wallabyjs/public#228]
Hi, since there doesn't seem to be a way to use virtual paths in the wallaby.js config file (see https://github.com/wallabyjs/public/issues/68), is there a way to copy files in a way that they don't get deleted between runs (or wallaby engine restart)?

**Comment by ArtemGovorov** [comment]
Hello,
wallaby.js caches files (listed in `files` and `tests` lists) and doesn't *normally* delete instrumented the files between runs. It does delete them on any wallaby config file change, but not during subsequent runs and the engine restart.

Anyway, you may not need to copy files or specify them in your `files` list if you don't need to instrument them, but still need to use them in your browser tests. [Middleware function](http://wallabyjs.com/docs/config/middleware.html) in your config allows you to specify files and folders that you'd like wallaby web server to serve as is, from any folder.

Let me know if it helps, otherwise please provide a bit more details on why do you need to copy the files into instrumented folder and about the nature of those files.

**Comment by DinisCruz** [comment]
nice, that middleware function will solve one of the issues I had with another config http://wallabyjs.com/docs/config/middleware.html (this one https://github.com/TeamMentor/TM/blob/Dev/wallaby.js )

Since the files to copy are quite substantial (and wallaby seems to be quite slow at copying the files, even with flags set to not instrument them), in this case my 'solution' was able to copy the files into the projects folder (which is not touched during runs or config/file changes)
