### ISSUE TITLE
loggers like Winston or log4js dont seem to work with Wallaby/Quokka

### ISSUE THREAD

**Issue by marcelh-gh** [wallabyjs/public#2322]
### Issue description or question

**With log4js**
```
import { getLogger } from "log4js";

const mylogger = getLogger("TestCategory");

mylogger.level = "debug";
mylogger.debug("debug message");
mylogger.info("info message");
```

**With Winston**
```
import * as winston from "winston";

const mylogger = winston.createLogger({
    level: "info",
    transports: [
        new winston.transports.Console({
            format: winston.format.combine(
                winston.format.timestamp(),
                winston.format.json()
            )
        })
    ]
});

mylogger.info("info message");
mylogger.error("error message");
```

Both work fine within node but produces no output at all in Quokka.

### Wallaby diagnostics report

    editorVersion: "1.41.1",
    pluginVersion: "1.0.168" (Wallaby),
    pluginVersion: "1.0.275" (Quokka),
    editorType: "VSCode",
    osVersion: "win32 10.0.18363",
    nodeVersion: "v12.13.0",
    coreVersion: "1.0.829",

**Comment by smcenlly** [comment]
`Winston` and `log4js` log providers do not use the same underlying method that Wallaby/Quokka use to log values, which is why this is not working for you. 

Wallaby and Quokka intercept `console.log` calls only (e.g. not `console.warn`, not `console.error`, not `stdout`, not `stderr`). This is described in our [Wallaby docs](https://wallabyjs.com/docs/intro/advanced-logging.html#via-consolelog), and [Quokka docs](https://quokkajs.com/docs/index.html#live-logging).

In the case of Winston/log4js, they are actually writing to `process.stdout`, `process.stderr`. Neither of these are captured by Wallaby or Quokka, and this is by design.

---

For Wallaby, you should be able to mock out Winston/log4js in your [Wallaby setup function](https://wallabyjs.com/docs/config/bootstrap.html) similar to what is described in https://github.com/wallabyjs/public/issues/1080 (if you want to do this and run into problems, let us know and we can assist).

For Quokka, if you are loading existing code that includes logging, and instead want to log as `console.log`, you could do a similar thing by creating a [Quokka plugin](https://quokkajs.com/docs/extensibility.html) that intercepts Winston/log4js module loading and replaces the calls you are using with `console.log`.

**Comment by marcelh-gh** [comment]
@smcenlly as always thank you for the blazing fast response! :-)
I had checked the referenced Wallaby & Quokka docs before and once again after your response.
Unfortunately I don't see this described there. If this is by design, it should better be mentioned there.

What is the rationale for the design decision? You don't want to pollute the Quokka/Wallaby output with regular logging of the monitored app? That would make sense.
But since the loggers in question all have a "debug" loglevel, you could support showing just those messages. If there is a performance penalty by reading stdout/stderr you might consider a flag in the Wallaby config to switch this feature on/off.

**Comment by smcenlly** [comment]
Hey @marcelh-gh, re: our docs - we detail how to you may log:

> There are 3 major ways to log something in wallaby.js and quickly inspect the output inline, or inside the Failing Tests/Line tests view, in all supported editors.
>
> * Via console.log: ... `console.log(anything)`
> * Identifier expressions: ... just type variable name and get it's value(s) displayed
> * Live Comments: ... Inserting the special comment //? (or /*?*/)

As we do not support process.stdout, console.warn, console.error support, we don't detail these as supported ways to log in our docs.

---

The rational for what we currently provide is to maintain a non-obtrusive developer experience when writing code/tests and Wallaby is turned on. E.g. if you have lots of logging in your application your inline message displays could make your developer experience very distracting/frustrating. RE: logger levels: right now, Wallaby/Quokka are hooking into deeper runtime components (e.g. console.log) which are well removed from loggers and the concept of logging levels. Generally speaking, most people want their code to appear as just their code when using Wallaby _**unless**_ they have a problem, at which point they can use one of the methods above (as well as our [show value shortcut](https://wallabyjs.com/docs/intro/advanced-logging.html#show-value--copy-value)).

If you disagree with the rational and would like to open a feature request for either Wallaby and/or Quokka to add support for other output mechanisms (e.g. console.error, stdout), please do so and we'll evaluate over the next few weeks. 

If you have the time to try mocking out your logging library in the Wallaby setup function that we suggested in the previous reply, we'd be interested to know what your experience is like. Do the log messages get in the way?

**Comment by marcelh-gh** [comment]
@smcenlly thanks for your detailed reply.

Yeah, I obviously had read those sections in the docs. I guess, it would be nice to have just a one liner to clarify that other reporting (stdout etc) is not supported.

I generally agree with your rationale.
In terms of not supporting log levels:
I do think that it could be nice to be able to use existing debug level logging to track down the problem in case a test fails. Probably not for small unit tests but for larger integration tests it would be helpful. Not a high priority issue though.

Cheers,
Marcel
