### ISSUE TITLE
UI to run selected tests only

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#2323]
### Issue description or question

I feel I miss pretty much obvious thing, so please bear with me 🙏 

Flow I'd like to do is basically something like this:

- did not start wallaby at all, just open editor
- go to one test cases like `a.spec.js`
- open wallaby command, select `run file tests`
- wallaby starts boot up for relative files around `a.spec.js`, run / observe given test's file changes

Something would similar to run specific files in other test runner, for example `jest a.spec.js` to trigger specified matching test only.

I read https://wallabyjs.com/docs/intro/selected-tests.html, it looks like mostly related with scoping test via test suite's scope (`it.only` etcs) or give a specific comment to test suites. Is there way to achieve above cases via ui only?

bit of background detail, our entire test suite is currently too large. While I could not able to fully setup wallaby config for our repo yet, initial exploration takes huge time just trying to load / transpile all files specified in configs (plain cli test runner takes 10-30min depends on local system spec) and I feel this'll be blocker if dev need to wait this amount of time to load up whole suite while majority of cases dev will work on few test files per each PRs.

**Comment by kwonoj** [comment]
Slightly unrelated: what'd be the best strategy to start wallaby if the entire test suite is large enough so taking quite long? like, just plain cli run against full suite takes ~30min and starting wallaby takes nearly equivalent time - something I can't recommend to colleagues to wait for 30min to get feedback from wallaby.

**Comment by ArtemGovorov** [comment]
There's no way to do it from the UI at the moment, however we do have a workflow that we recommend for large/huge projects where sometimes you may want to work only on certain spec files and still get the feedback from Wallaby.

1. Create a config file (for automatic Jest configuration) and in the file [specify that Wallaby should not run all tests to start with, but only selected test files](https://wallabyjs.com/docs/intro/selected-tests.html#test-file-selection).

```js
module.exports = function (wallaby) {
  return {
    autoDetect: true,
    runSelectedTestsOnly: true
  };
};
```

2. Start Wallaby normally, it should start instantly because it will not run ANY tests yet.

3. Open the spec file you'd like Wallaby to run and anywhere in the file add `// file.only` comment. Wallaby will run the test file and will only be running the test file on changes. If you want to work with multiple spec files, you may add the same comment to any number of them, and Wallaby will only run those selected spec files.

**Comment by kwonoj** [comment]
@ArtemGovorov thanks, it is helpful and I'll give it a go. Will there be som possibility feature requst to mark test via some ui instead of comments?

**Comment by ArtemGovorov** [comment]
> Will there be som possibility feature requst to mark test via some ui instead of comments?

Yes, I have marked the issue as feature request (and renamed it a bit).

**Comment by kwonoj** [comment]
Thanks! :bowing_man:

**Comment by NikGovorov** [comment]
Hi @kwonoj,

[Exclusive Test Run](https://medium.com/@wallabyjs/exclusive-test-runs-421ed9491a0d) feature  that we released yesterday should cover the requested scenario.

![vsc_test_focusing](https://user-images.githubusercontent.com/129254/77497784-e50b5c00-6e99-11ea-85b2-8dd1a2e5c0ec.gif)

**Comment by faceyspacey** [comment]
That's awesome. I'm glad I found this thread. It would also be very helpful in the Wallaby web app via an *identical user experience to the test filtering buttons.* 

Using the file explorer in your IDE is a lot slower than this UX, and has you scrambling between 2 separate UIs. Also, there doesn't seem to be a way to "remove from exclusive test run" and in the usage I imagine, you'd be doing a lot of back-and-forth (toggling which rows are in the test run, and which are not) like you do with the filtering buttons.
