### ISSUE TITLE
Typescript with javascript

### ISSUE THREAD

**Issue by Alexzanderk** [wallabyjs/public#2330]
So, the project has files with extension ts and js and some js import inside ts

Problem that I have is `Uncaught ReferenceError: exports is not defined`

```javascript
//  wallaby.js
module.exports = function() {
  return {
    files: ['src/**/*.ts', 'src/**/*.js'],

    tests: ['test/**/*spec.ts'],

    setup: function() {
      global.expect = require('chai').expect;
    },
  };
};
```

typescript config
```javascript
{
  "compilerOptions": {
    "target": "es6",
    "module": "commonjs",
    "lib": ["dom", "es6", "es2017", "esnext", "esnext.asynciterable", "es2019", "es2020"],
    "sourceMap": true,
    "outDir": "./dist",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "declaration": false,

    "allowJs": true,
    "composite": false,
    "removeComments": true,
    "noImplicitAny": false,
    // "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noImplicitThis": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "typeRoots": ["node_modules/@types"],
    "baseUrl": ".",
    "rootDir": "src"
  },
  "exclude": ["node_modules"],
  "include": ["./src/**/*.ts", "src/scripts/click.script.js"]
}
```

screenshot
![image](https://user-images.githubusercontent.com/16296369/74106693-8439f580-4b71-11ea-8de2-6ca88d16a3d9.png)

**Comment by smcenlly** [comment]
The reason this isn't working for you is that your Wallaby configuration is running your tests in the browser (chrome headless) but TypeScript is configured to use node module resolution. Node.js / CommonJS uses the **exports** keyword. However, `commonjs` doesn't run in browser without a module loader or module bundler.

Is your code/tests browser-based? If so, what bundler are you using to transform your compiled TypeScript to run in the browser?

If you are happy to run your code in `node` instead of the browser, you may update your configuration file as shown below:

```javascript
module.exports = function() {
  return {
    files: ['src/**/*.ts', 'src/**/*.js'],
    tests: ['test/**/*spec.ts'],
    setup: function() {
      global.expect = require('chai').expect;
    },
    env: {
      type: 'node'
    }
  };
};
```

If you want to run your code in the browser, you will need to configuration Wallaby to use your bundler (e.g. see [our Webpack docs](https://wallabyjs.com/docs/integration/webpack-built-in.html)) or else override your Wallaby TypeScript compiler options ([see our docs](https://wallabyjs.com/docs/integration/typescript.html)) so that the TypeScript compiled code runs in the browser without being bundled.

If you need further assistance, can you please provide us with your [Wallaby diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report) along with details of how your tests are being run outside of Wallaby + any relevant configuration files (e.g. babel, webpack, etc.).
