### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Leif-Frederiksen** [wallabyjs/public#2403]
- Issue Type: `Performance`
- Extension Name: `wallaby-vscode`
- Extension Version: `1.0.194`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.44.1`

(https://github.com/wallabyjs/public/files/4527671/WallabyJs.wallaby-vscode-unresponsive.cpuprofile.txt)
allabyJs.wallaby-vscode-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by smcenlly** [comment]
Thanks for reporting the issue.

Your CPU profile shows that the high CPU load is operating system time during file copy operations when Wallaby is updating itself. This is likely caused by your virus scanner as Wallaby is extracting `.js` files that your virus scanner is processing. If you continue to receive reports outside of Wallaby updating itself, please let us know and provide us with an updated CPU profile.
