### ISSUE TITLE
Invalid Code Coverage for Ternary Statements

### ISSUE THREAD

**Issue by DmacMcgreg** [wallabyjs/public#2408]
### Issue description or question

![image](https://user-images.githubusercontent.com/3266023/80522879-386e3f80-895b-11ea-8be1-184636320649.png)

Seems as though the coverage report is showing these lines as being covered, when they really are not.
I'm absolutely sure I'm not toggling this link such that it would be showing both possible options
![image](https://user-images.githubusercontent.com/3266023/80522695-fa711b80-895a-11ea-9d0d-0bc9d52d5039.png)

Here is proof from the jest coverage.

**Comment by smcenlly** [comment]
This appears to be working for us (see screenshot below). There might be something else in your code that is causing the problem. Could you please create a sample repo for us that has the problem so that we can replicate?

![image](https://user-images.githubusercontent.com/2074089/80540956-a2372980-89ed-11ea-8bae-a790be7fa627.png)

**Comment by DmacMcgreg** [comment]
Thanks for the response.
I haven't had the time yet to fully strip the repo of sensitive info, so I'm working on that. Might take a bit of time, so I'll respond back when I can!

Cheers

**Comment by smcenlly** [comment]
Closing this issue out as old as we haven't heard back and do not have a reproduceable sample.
