### ISSUE TITLE
WallabyApp: Offline Version 1.0.64 | Online 1.0.69

### ISSUE THREAD

**Issue by dadiborn** [wallabyjs/public#2447]
Was fallowing instructions for offline installation _(https://wallabyjs.com/docs/intro/offline.html)_ and found that offline version of WallabyApp is not latest.
localhost:51245 >> 1.0.**64**
wallabyjs.com/app >> 1.0.**69**

**Comment by smcenlly** [comment]
We previously only updated the offline version of WallabyApp on demand. We've now updated our processes so that the offline version is always up-to-date with what you will find online. You may obtain the latest version using the link referenced in the offline section of our docs, https://wallaby-downloads.s3.amazonaws.com/wallaby-app.zip.
