### ISSUE TITLE
How to configure wallaby to work with shared configurations lib

### ISSUE THREAD

**Issue by Niryo** [wallabyjs/public#2486]
### Issue description or question
All of my project's configurations are coming from a shared repo that sits inside my node_modules folder.
What is the best way to configure wallaby in that case?
I am using jest + tsc

**Comment by smcenlly** [comment]
Does `npx jest` work from your project root? If so, there is no need to configure Wallaby, you may simply use Wallaby with [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration). 

If that doesn't help you, can you give a more concrete example of how your project a structured in terms of file layout and what configuration comes from the shared `node_modules` module? Please also provide details about how your tests are configured to run outside of Wallaby.

**Comment by Niryo** [comment]
nope, running `npx jest` can't work. 
we have a special lib dependency called `runner`, and we use it to run all of our tools. for example `runner unitTests` will run all the unit tests, using jest, and the runner will run this command:
```
./node_modules/.bin/runner -c ./node_modules/runner/src/jest-config.json --rootDir /Users/niryo/git/project ./src ./__tests__ --setupFiles /Users/niryo/git/project/jest-setup
```

same goes for tsc- `runner tsc` will result in:
```
 ./node_modules/.bin/tsc -p ./node_modules/runner/src/moduleTsconfig.json
```

so the project structure is pretty normal, but we don't hold configuration files. the runner bring everything.

**Comment by smcenlly** [comment]
Thanks for providing the additional information. There are two ways that you can proceed with the configuration: use automatic configuration or set up a manual configuration file.

### Configure Wallaby/Jest to work with automatic configuration (recommended)

To do this:

a) You will need to create a jest configuration that runs using `npx jest` from your project root. For example, create `wallaby.jest.config.js` with the content:

**wallaby.jest.config.js**
```javascript
//  Note: it's possible you will need some additional jest settings for your project

const jestConfig = require('./node_modules/runner/jest-config.json');

module.exports = {
  ...jestConfig,
  setupFiles: ['./jest-setup.js']
};
```

b) At this point, Wallaby still won't work because it follows Jest's convention and will look for `jest.setup.js` instead of `wallaby.jest.config.js`. Create a `wallaby.js` configuration file to tell Wallaby to use `wallaby.jest.config.js`:

**wallaby.js**
```javascript
module.exports = () => {
  return {
    // tell wallaby to use automatic configuration
    autoDetect: true,

    testFramework: {
      // the jest configuration file path
      // (relative to project root)
      configFile: 'wallaby.jest.config.js'
    }
  }
};
```

At this point, you should be able to start Wallaby by selecting the configuration file: `wallaby.js`.

### Configure Wallaby/Jest with manual configuration

Configuring Wallaby with manual configuration is a little more complex. Unfortunately we can't provide this configuration without more information about your project structure (dependencies, tsconfig.json, jest.config.js). We used our TypeScript create-react-app as a starting point but you will probably need to modify and extend to support your project. We recommend reading our [jest docs](https://wallabyjs.com/docs/integration/jest.html) (select manual configuration) and referring to our [project examples](https://wallabyjs.com/docs/intro/examples.html) if you run into problems.

```javascript
module.exports = function(wallaby) {
  process.env.BABEL_ENV = 'test';
  process.env.NODE_ENV = 'test';

  return {
    // update file patterns to find all project files but make sure test entry points are excluded
    files: [
      { pattern: 'src/setupTests.ts', instrument: false }, 
      'src/**/*.+(ts|tsx|jsx|json|snap|css|less|sass|scss|jpg|jpeg|gif|png|svg)', 
      '!src/**/*.test.ts?(x)'
    ],

    // update tests patterns to include all test entry points
    tests: ['src/**/*.test.ts?(x)'],

    env: {
      type: 'node'
    },

    preprocessors: {
      '**/*.js?(x)': file =>
        require('@babel/core').transform(file.content, {
          sourceMap: true,
          compact: false,
          filename: file.path,
          presets: [require('babel-preset-jest'), require("@babel/preset-env")]
        })
    },

    setup: wallaby => {
      const jestConfig = require('./node_modules/runner/jest-config.json')
      Object.keys(jestConfig.transform || {}).forEach(k => ~k.indexOf('^.+\\.(js|jsx') && void delete jestConfig.transform[k]);
      delete jestConfig.testEnvironment;
      wallaby.testFramework.configure(jestConfig);
    },

    testFramework: 'jest'
  };
};
```

---

If you decide to go with the second method and cannot get the configuration working, please provide us with a cut-down sample repo with one sample test (can be very simple - e.g. `expect(true).toBe(true)`) so that we can see your project structure. We'll then be able to configure your project for you. Alternatively, providing us with your `package.json` `dependencies` and `devDependencies` as well as your `tsconfig.json` and `jest.config.json` _should_ be enough for us to determine a configuration for you.

**Comment by Niryo** [comment]
worked perfectly with auto configuration:) 
Thanks!
