### ISSUE TITLE
Not working for angular cli project with webstorm with automatic configuration

### ISSUE THREAD

**Issue by johannesjo** [wallabyjs/public#2519]
I am trying to run tests for this project:
https://github.com/johannesjo/super-productivity

But after a while I just get the following error in the Wallaby Console:
```
wallaby.js started
core v1.0.962
Execution progress: 50 tests
Some long running code has been detected: test "l = s > r  -> update local" is taking more than 5000ms to execute.
The last recorded console.log: { remote: 0, local: 0.003, lastSync: 0.003 } 1600798626.672
Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,
and restarting wallaby to make sure that it is this test/file causing the issue and not something else.
Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.
Pinging test runner sandbox...
The sandbox is not responsive. Check for possibly recently introduced infinite loops.
```

`ng test` runs fine.

**Comment by smcenlly** [comment]
Thanks for reporting the problem, and for the sample repo.

We identified that the cause of your issue was your use of `window.alert` in `check-for-update.util.ts`. Wallaby was not patching this method while Angular was, which meant that Wallaby was waiting for the user to dismiss the prompt, which never happened.

The latest version of Wallaby core, `v1.0.963` fixes this issue. Wallaby should update for you automatically, but if it does not (or if you want to update immediately), you may [force a core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by johannesjo** [comment]
Thank you very much! This resolves the issue for me.
