### ISSUE TITLE
required applicationinsights throws "Module not found"

### ISSUE THREAD

**Issue by whyld4900** [wallabyjs/public#2525]
Repo that has error:
https://github.com/whyld4900/wallaby-appinsights-error

Based from this example:
https://github.com/wallabyjs/wallaby-webpack-electron

Error I see: 
`Module not found: Error: Can't resolve 'async_hooks' in '.\node_modules\cls-hooked' `

If you comment out the require it works:
https://github.com/whyld4900/wallaby-appinsights-error/blob/e650be5c0a3252042d08bc7014251039a7ff9521/src/Person.js#L4

How can I resolve this? 
It would be nice to just provide a mock for applicationinsights, or whatever else is fine too.

**Comment by smcenlly** [comment]
Thanks for the sample repo.

It looks like your problem is not related to Wallaby but instead an issue with how you are trying to use `applicationinsights`.

`applicationinsights` is meant for node.js applications, but you are running your tests in a browser environment (electron), not `node.js`. We found an [online article](https://community.powerbi.com/t5/Developer/Application-Insights-External-NPM-Dependency-Error-packaging/td-p/993771) describing your problem and recommending to use the `@microsoft/applicationinsights-web` package. Maybe that makes sense in your case?

I'm assuming that the repo that you provided to us is a cut-down repo of your actual project? Are you able to update the sample repo to show us how your tests are running outside of Wallaby? If you're using Webpack, you should have a Webpack configuration. Last year we released native support for webpack instead of using the `wallaby-webpack` package. The [native webpack integration](https://wallabyjs.com/docs/integration/webpack-built-in.html) allows you to use your existing webpack loaders (e.g. for your test environment) which may simplify your configuration. From our docs:

_The key difference with the built-in webpack postprocessor is that it integrates with webpack’s loaders to perform instrumentation which allows you to use the same loaders as you use in your test, development and production webpack configurations such as babel-loader for ES6/ES7/ES8, ts-loader or awesome-typescript-loader for TypeScript and coffee-loader for CoffeeScript. If you are using the open source wallaby-webpack postprocessor then unlike the built-in method, you must additionally configure wallaby preprocessors and compilers. This also means that the compiler setting for the built-in webpack postprocessor is no longer necessary._

> It would be nice to just provide a mock for applicationinsights, or whatever else is fine too.

There are a couple of ways you can do this:
1. Use Webpack's [NormalModuleReplacementPlugin](https://webpack.js.org/plugins/normal-module-replacement-plugin/) to replace your `applicationinsights` module with your mock.
2. Update your Wallaby configuration with a preprocessor that clears or replaces the javascript for `applicationinsights` (see below).

**Sample Wallaby.js clearing applicationinsights module with pre-processor**
```diff
"use strict";

var wallabyWebpack = require("wallaby-webpack");
var webpackPostprocessor = wallabyWebpack(
  {
    node: {
      setImmediate: false,
      dgram: "empty",
      fs: "empty",
      net: "empty",
      tls: "empty",
      child_process: "empty",
    },
  },
  { setupFiles: ["./test/setup.js"] }
);

module.exports = function (wallaby) {
  return {
    files: [
      { pattern: "src/**/*.js", load: false },
+     // Need to include all files in node_modules/applicationinsights folder so it is processed by Wallaby (note the use of wildcard)
+     { pattern: "node_modules/applicationinsights/**/*.*", load: false, instrument: false }
    ],

    tests: [{ pattern: "test/**/*.spec.js", load: false }],

    env: {
      kind: "electron",
    },

    compilers: {
      "**/*.js": wallaby.compilers.babel(),
    },

+   // Clear the content of all applicationinsights javascript files
+   preprocessors: {
+     'node_modules/applicationinsights/**/*.js': file => ''
+   },

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    },
  };
};
```

**Comment by whyld4900** [comment]
NormalModuleReplacementPlugin was the way to go. ty!

**Comment by rocketnova** [comment]
@smcenlly Just wanted to say thank you for your extremely helpful response in this thread that helped me debug an issue totally unrelated to Wallabyjs. Thank you also for the thorough documentation on https://wallabyjs.com/docs/integration/webpack.html#normalmodulereplacement-plugin
