### ISSUE TITLE
Line endings mismatch 

### ISSUE THREAD

**Issue by seebees** [wallabyjs/public#2537]
### Issue description or question

I use Wallaby.js to help with Node.JS development, I would like to also support the browser tests.
I added a config file that I can swap between.
As I understand it that is the "best way"...

But running the browser tests,
when I try and debug test failures,
the line numbers do not line up.

Here is a PR to the new configuration files:
https://github.com/aws/aws-encryption-sdk-javascript/pull/443

any help would be appreciated :)

**Comment by smcenlly** [comment]
I'm trying to get the [aws-encryption-sdk-javascript repo](https://github.com/aws/aws-encryption-sdk-javascript) up and running (first without your changes) but am having some troubles. Can you give me a hand?

I did the following:
1. Cloned repo
2. Ran `npm install`
3. Ran `npx lerna bootstrap`
4. Ran `npm test`

I get the following error:

```
10 10 2020 09:05:10.442:ERROR [karma-server]: UnhandledRejection: TimeoutError
infrastructure_error Error: TimeoutError
    at ClientRequest.<anonymous> (/home/smcenlly/repos/aws-encryption-sdk-javascript/node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/src/remoteProvider/httpRequest.ts:17:14)
    at ClientRequest.emit (events.js:314:20)
    at Socket.emitRequestTimeout (_http_client.js:769:9)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:326:22)
    at Socket._onTimeout (net.js:482:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
10 10 2020 09:05:10.446:ERROR [karma-server]: Error: TimeoutError
    at ClientRequest.<anonymous> (/home/smcenlly/repos/aws-encryption-sdk-javascript/node_modules/@aws-sdk/credential-provider-imds/dist/cjs/remoteProvider/src/remoteProvider/httpRequest.ts:17:14)
    at ClientRequest.emit (events.js:314:20)
    at Socket.emitRequestTimeout (_http_client.js:769:9)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:326:22)
    at Socket._onTimeout (net.js:482:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aws-encryption-sdk-javascript@0.0.1 karma: `karma start karma.conf.js`
npm ERR! Exit status 1
```

**Comment by seebees** [comment]
There are test that use KMS. To run all the browser tests you will need to have some AWS credentials that have KMS access. These are keys for public testing.

An inline policy that will work :

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "KMS-Public-CMK-Key-Access",
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt",
                "kms:Encrypt",
                "kms:GenerateDataKey"
            ],
            "Resource": "arn:aws:kms:us-west-2:658956600833:key/*"
        }
    ]
}
```

**Comment by seebees** [comment]
Also, `npx lerna bootstrap` is not required.

**Comment by smcenlly** [comment]
Thanks - I have it up and running. I didn't realize it needed access to AWS to run the tests. We use named profiles for everything so have no `[default]` credential.

**Comment by smcenlly** [comment]
There are two separate issues that were causing your runtime code to not map correctly to your original source code. These issues would result in coverage indicators, error details, and inline values not displaying correctly and in some cases they would not display at all.

1. Your TypeScript compiler settings are not correct for `ts-loader` to correctly emit source maps (this is required for Wallaby's line mappings to work correctly). From [ts-loader configuration docs](https://github.com/TypeStrong/ts-loader#configuration):

> If you want to be able to debug your original source then you can thanks to the magic of **sourcemaps** [...] for ts-loader to produce sourcemaps, you will need to set the [tsconfig.json](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html) option as `"sourceMap": true`.

Please note that when you add this setting, you will also need to either delete the setting `inlineSourceMap` or else set it to false.

2. Your custom loader `wallaby.cred.loader.js` is modifying your original source code, shifting everything down by 1 line but the source map that it is returning is unchanged. This will cause all lines reported by Wallaby to be offset by 1. If you know that the first line of your test files do not have any values that need to be reported by Wallaby, you can fix this pretty easily by changing your code to use a semi-colon as the separator instead of newline.

**wallaby.cred.loader.js**
```diff
const credentialsPromise = require('@aws-sdk/credential-provider-node').defaultProvider()()

module.exports = async function (source, map) {
  this.cacheable()
  var callback = this.async()
  const credentials = await credentialsPromise
  var prepend = `var credentials = ${JSON.stringify(credentials)};`
- const newSource = prepend + '\n' + source
+ const newSource = prepend + ';' + source
  callback(null, newSource, map)
}
```
