### ISSUE TITLE
unexpected typescript auto-compilation behavior blasts similarly-named source files

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#2544]
I have a TypeScript test fixture file (`foo.ts`).  My test does not rely upon compilation of `foo.ts`.  `foo.ts` is not compiled by my test suite, nor is it executed (it's statically analyzed, fwiw).

However, it _appears_ Wallaby is compiling this file into `foo.js` (as I find in the instrumented directory).  The Wallaby config file does not reference TypeScript (nor is there a `tsconfig.json` anywhere in my project's sources or tests), so I imagine this happens automatically.  That seems like the right thing to do in most cases (though I'd imagine most TS projects have a config file).

This would not be worth mentioning, except that if a `foo.js` _already exists_ (this is a distinct file, unrelated to `foo.ts`), it will be overwritten by the automatic compilation--which is exactly what happened.  

It's _possible_ Wallaby is _not_ the culprit here, but since the overwriting _only_ happens in Wallaby's instrumented dir, it seems likely.  

Fortunately, it's easy to work around--I renamed `foo.js` to `bar.js`.  `foo.js` is still being compiled from `foo.ts`, but my tests do not attempt to do anything with it.

Anyhow: assuming this is plausible, is there a way to disable automatic TS compilation?  Further, would it make sense to  disable the behavior if a `tsconfig.json` does not exist?  Or would that negatively impact Quokka, which likely wants this behavior?

(If you want to see the config, it's in [this branch](https://github.com/mochajs/mocha/tree/boneskull/experimental/detect); the problem files are in `test/integration/fixtures/cli`)

**Comment by smcenlly** [comment]
> However, it appears Wallaby is compiling this file into foo.js (as I find in the instrumented directory). The Wallaby config file does not reference TypeScript (nor is there a tsconfig.json anywhere in my project's sources or tests), so I imagine this happens automatically. That seems like the right thing to do in most cases (though I'd imagine most TS projects have a config file).

This is correct, Wallaby matches all TypeScript and CoffeeScript files by default and will use its own built-in compilers and default compiler settings if you don't have them as a part of your project. This is by design and will only happen if the TypeScript/CoffeeScript file is a valid match as per your `files`/`tests` configuration.

> It's possible Wallaby is not the culprit here, but since the overwriting only happens in Wallaby's instrumented dir, it seems likely.

No - this is definitely something that Wallaby is doing. Wallaby has no way of knowing whether the foo.js that was there already was generated by TypeScript a project file and is an expected behavior.

> Anyhow: assuming this is plausible, is there a way to disable automatic TS compilation? Further, would it make sense to disable the behavior if a tsconfig.json does not exist? Or would that negatively impact Quokka, which likely wants this behavior?

We wouldn't want to change the current behavior as it would be a breaking change for some of our users (both for Wallaby.js and Quokka.js). You may disable the TypeScript compiler completely by updating your configuration file to not instrument TypeScript files and by also overriding the default compiler setting for TypeScript (see below).

**Wallaby.js Configuration**
```diff
module.exports = () => ({
  files: [
+    // At the top of your files config (the order is important), exclude TypeScript files from being instrumented by Wallaby
+    { pattern: '**/*.ts', instrument: false },

    ...
  ],

  ...

+ // Override the compilers section to never transform TypeScript files
+ // Note: this will not work if you have any TypeScript files that are *not* excluded from instrumentation
+ compilers: {
+   '**/*.ts': file => file
+ },

  ...
});
```

**Comment by boneskull** [comment]
Thanks, will use this config.
