### ISSUE TITLE
Wallaby.js not running tests that use Angular's fakeAsync function

### ISSUE THREAD

**Issue by awshelley-beckman** [wallabyjs/public#2558]
### Issue description or question

I have some tests that use Angular's fakeAsync() environment.  Those tests are always marked green, even when they should be failing.  All of the lines inside these test are marked grey, indicating that they are not being run.

Tests that do not use fakeAsync() work as expected.

```typescript
import { fakeAsync } from '@angular/core/testing';
import { expect } from 'chai';

describe('GripperCorrelationComponent', () => {

  it('This test fails, the way I expect it to.', () => {
    expect(true).to.be.false;
  })

  it('This test passes.', fakeAsync(() => {
    expect(true).to.be.false;   // This line is marked gray, as if it didn't run.
  }));

});

```

### Wallaby diagnostics report
It's 3201 lines long---github won't even let me paste it in.  Here's a pastebin instead.
https://pastebin.com/CKSRHtQK

**Comment by NikGovorov** [comment]
Does `ng test` work on the project?

**Comment by NikGovorov** [comment]
From the logs that you attached I can see two issues:

1. `Uncaught Error: Test file src/app/utils/testing-helpers.spec.ts is being imported from other test files. 
This may cause tests in the file to be executed more than once (when the test file runs and every time it gets imported).
If the test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing the new helper file where required.` 

By default for Angular CLI projects Wallaby treats all *.spec.ts files as `test` files internally, hence you should remove `.spec` postfix from the file name.

2. `Expected to be running in 'ProxyZone', but it was not found.` happens because in your `test.ts` file you import 
```javascript
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/mocha-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import 'zone.js/dist/zone-patch-promise-test';
```
instead of 
```javascript
import 'zone.js/dist/zone-testing';
```

**Comment by smcenlly** [comment]
I'm closing this issue since we haven't heard back, assuming @NikGovorov's suggestion fixed your problem. If not, please let us know and we'll re-open the issue.

**Comment by awshelley-beckman** [comment]
Thanks for the suggestion.  It worked like a charm!
