### ISSUE TITLE
Mocha v8.2.1 issue

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#2564]
### Issue description or question

Using Mocha v8.2.1, I'm occasionally hitting this error when wallaby tries to re-run its tests:

```
Cannot dispose while the mocha instance is still running tests. 
    at createMochaInstanceAlreadyRunningError (/Users/boneskull/projects/boneskull/mrca/node_modules/mocha/lib/errors.js:330:13) 
    at Mocha.dispose (/Users/boneskull/projects/boneskull/mrca/node_modules/mocha/lib/mocha.js:609:11) 
    at WebSocket.emit (events.js:315:20) 
    at afterWrite (_stream_writable.js:466:5) 
    at onwrite (_stream_writable.js:446:7) 
    at InflateRaw.afterTransform (_stream_transform.js:103:3) 
    at Zlib.processCallback (zlib.js:587:8) 

Mocha instance is currently running tests, cannot start a next test run until this one is done 
    at createMochaInstanceAlreadyRunningError (/Users/boneskull/projects/boneskull/mrca/node_modules/mocha/lib/errors.js:330:13) 
    at Mocha._guardRunningStateTransition (/Users/boneskull/projects/boneskull/mrca/node_modules/mocha/lib/mocha.js:905:11) 
    at Mocha.run (/Users/boneskull/projects/boneskull/mrca/node_modules/mocha/lib/mocha.js:963:8) 
    at processTicksAndRejections (internal/process/task_queues.js:93:5) 
```

[Report here](https://gist.github.com/boneskull/2906b3f62d20998b72fb3d4cc018e86c)

When this occurs, Wallaby does not recover gracefully; it will not run tests.  Further changes to the code cause Wallaby to run tests again.

Mocha (in particular, _I_) recently changed how it handles rejected `Promise`s; I made a problematic change (which caused all unhandled rejections to emit an error, which should not happen if `node` should only _warn_ on unhandled rejection, as it does by default prior to v15.0.0) in v8.2.0, and corrected this in v8.2.1, so that only unhandled rejections _emitted by Mocha itself_ cause errors.

This is likely one of those errors; my hunch is that they were happening behind-the-scenes but were eaten by either Mocha or Wallaby.  

I'd like to determine if this is something Wallaby needs to handle and suppress, or if it's something I need to address on my side.

If the fix should happen in Wallaby, you can likely add a `catch` (or `unhandledRejection` listener) which looks for an `Error` containing prop `code` with value `'ERR_MOCHA_INSTANCE_ALREADY_RUNNING'` and ignore it.

**Comment by boneskull** [comment]
you can also grab this error code via a constant out of Mocha's source:

```js
require('mocha/lib/errors').constants.INSTANCE_ALREADY_RUNNING // 'ERR_MOCHA_INSTANCE_ALREADY_RUNNING'
```

**Comment by smcenlly** [comment]
Could you please provide us with your Wallaby diagnostics report? 

We had the same error reported recently (see https://github.com/wallabyjs/public/issues/2560#issuecomment-723702941) but the cause was related to how Wallaby delayStart() being called unnecessarily. Perhaps you have the same problem?

**Comment by boneskull** [comment]
report is linked

**Comment by boneskull** [comment]
also my config file

```js
'use strict';

module.exports = () => ({
  files: [
    'src/**/*.js',
    'package.json',
     'test/expect.js',
    {pattern: 'test/integration/fixtures/**/*', instrument: false},
    {pattern:'node_modules/debug/**/*', instrument: false}
  ],
  filesWithNoCoverageCalculated: [
    'test/expect.js'
  ],
  tests: ['test/**/*.spec.js'],
  compilers: {
    // do not auto-compile typescript
    '**/*.ts': v => v
  },
  env: {
    type: 'node',
    runner: 'node',
    params: {
      // runner: `-r ${require.resolve('esm')}`,
      env: `DEBUG=mrca*,cabinet*;NODE_PATH=${__dirname}`
    }
  },
  debug: true,
  preservePaths: true,
  runMode: 'onsave'
});
```

**Comment by smcenlly** [comment]
Sorry about the request for report - missed the link... taking a look right now

**Comment by smcenlly** [comment]
This was a wallaby problem, caused by https://github.com/mochajs/mocha/commit/fbe3ce4f7d5c27fec3fa1e32ee86b23b169e02d2.

Wallaby reuses node processes for subsequent test runs and sometimes multiple mocha instances may be running at the same time in the same process (e.g. when the test running is still executing and you make a change and Wallaby starts the new test run). When this happens, Wallaby disposes Mocha to ensure that everything is cleaned up properly. The problem is intermittent depending on whether a test run is in progress for a worker thread when another test run is requested.

What we've done for now is to override Mocha's internal `_state` property before calling `dispose()`. We know that's not a great solution but it seems to work for now. Ideally we'd like a way of stopping the test run immediately and disposing it before we create another mocha instance.

The latest version of Wallaby, `v1.0.988`, fixes your problem.

**Comment by boneskull** [comment]
ok, noted. we don't have any API to "stop the test run" other than causing the process to exit in various ways. I can look in to what that'd take.
