### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by sgruhier** [wallabyjs/public#2567]
is wallaby compatible with angular 11
I have that error
```
‌[Error] Automatic Angular CLI configuration error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs' 
[Error] Require stack: 
[Error] - ./node_modules/@angular/cli/commands/test-impl.js/wallaby.js 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```

**Comment by smcenlly** [comment]
We [recently updated Wallaby](https://github.com/wallabyjs/public/issues/2566#event-3995908789) to support the latest version of Angular 11, available in version `v1.0.989`.

If you're still having problems on the latest version, can you please provide us with your Wallaby diagnostics report?

If you have an older license, you may [request a trial](https://wallabyjs.com/download/) from our website to try the latest version.

**Comment by sgruhier** [comment]
thanks
it's weird, the message was talking about jest-cli. I added jest to my package.json. Then I restart wallaby and it updated to latest version. Then I removed jest from package.json
It's like wallaby update wasn't able to be done because of that error.
Anyway, now it works fine
thanks

**Comment by smcenlly** [comment]
Glad to hear that it's working for you now. 

The reason you probably had the issue before is that when Wallaby starts, it will use the current downloaded version and only then go and check for a new version. This means that when you first start Wallaby, you're using an older version. If you had stopped/restarted Wallaby a few minutes later, everything should have worked fine for you with the updated version. This normally wouldn't cause a problem unless the previous version was breaking for you, like it was in your case. The message about Jest is expected and what happens when Wallaby's cannot detect your project testing configuration automatically.
