### ISSUE TITLE
Angular 11 auto config support

### ISSUE THREAD

**Issue by michael-letcher** [wallabyjs/public#2569]
### Issue description or question

Please add automatically config support for Angular 11

```bash
‍[Info]  Started Wallaby.js Core v1.0.977
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Cannot find module '@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs' 
[Error] Require stack: 
[Error] - ./node_modules/@angular/cli/commands/test-impl.js/wallaby.js 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```

Angular has moved the contents of this folder to 

`@angular-devkit/build-angular/src/webpack/configs`.

I've tried running from this folder, with the following errors:

```bash
‍[Info]  Started Wallaby.js Core v1.0.977
[Error] Failed to load configuration file: Automatic Angular CLI configuration error: A project for '.' directory cannot be detected. 
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
```

### Wallaby diagnostics report
NA

**Comment by ArtemGovorov** [comment]
Angular 11 support has been recently added in Wallaby Core v1.0.989: https://github.com/wallabyjs/public/issues/2566.

From the supplied log, it looks like your license had expired because you are a few versions behind. To get the latest version with Angular 11 support you may [renew your license](https://wallabyjs.com/store/personal/#select-wallaby). If you want to try it first to make sure it's working, you may get a trial license from https://wallabyjs.com/download/.

**Comment by michael-letcher** [comment]
Ahh, just had to force a Core update and we away. Cheers!
