### ISSUE TITLE
SyntaxError when running in fresh CRA project

### ISSUE THREAD

**Issue by adamShaleen** [wallabyjs/public#2576]
### Wallaby errors upon start

I created a fresh create-react-app project to use with wallaby's automatic configuration, but am getting a SyntaxError upon starting the plugin.

I cannot get the diagnostic report as the plugin errors upon loading

Wallaby v1.0.251
VScode v1.51.1
Jest v26.6.3
node v10.16.1
npx v6.14.4

Steps to reproduce:
create a new create-react-app project
`npx create-react-app my-app`

Start Wallaby with Automatic project wide configuration
Wallaby console output:
```
[Error] stack:[]};if(t.spec){var a=n[t.spec]=n[t.spec]||[];a.push(o)}else e.globalErrors||(e.globalErrors=[]),e.globalErrors.push(o)}}),this._processValueExplorerValues(r),debug("Processed console.log entries"),_.each(t.loadingSequence,function(t,n){_.each(t,function(t){var r=i._structure.filesById[t];r&&!i.settings().ignoreFileLoadingDependencyTracking&&(r.testFilesLoadedFrom=r.testFilesLoadedFrom||{},r.testFilesLoadedFrom[n]=runAlways);var s=i._structure.testFilesById[t];if(n!==t&&s){var o=i._structure.testFilesById[n];o&&e.globalErrors.push({message:"Test file '"+o.path+"' is importing or is causing import of another test file '"+s.path+"'.\nThis may cause tests in the '"+s.path+"' file to be executed more than once (when the test file runs and every time it gets imported).\nIf the '"+s.path+"' test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing th 
[Error] SyntaxError: Invalid regular expression flags 
[Error]     at createScript (vm.js:56:10) 
[Error]     at Object.runInThisContext (vm.js:97:10) 
[Error]     at Module._compile (module.js:542:28) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at Module.runMain (module.js:604:10) 
[Error]     at run (bootstrap_node.js:389:7) 
[Error]     at startup (bootstrap_node.js:149:9) 
```

**Comment by smcenlly** [comment]
This is working for us. Can you please provide us with your Wallaby diagnostics report? To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

If the diagnostics report is not generating for you, can you please provide your full Wallaby console log so that we can see your Wallaby.js Core version (at the top of the log) as well as a copy of your newly created repo.

**Comment by adamShaleen** [comment]
As stated originally, the Application errors upon startup/never completes the startup.  As such, I am unable to run the diagnostics report.

Here is the entire log printout:
```
‍[Error] /Users/redacted/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.251/wallabye4709b/server.js:24 
[Error] stack:[]};if(t.spec){var a=n[t.spec]=n[t.spec]||[];a.push(o)}else e.globalErrors||(e.globalErrors=[]),e.globalErrors.push(o)}}),this._processValueExplorerValues(r),debug("Processed console.log entries"),_.each(t.loadingSequence,function(t,n){_.each(t,function(t){var r=i._structure.filesById[t];r&&!i.settings().ignoreFileLoadingDependencyTracking&&(r.testFilesLoadedFrom=r.testFilesLoadedFrom||{},r.testFilesLoadedFrom[n]=runAlways);var s=i._structure.testFilesById[t];if(n!==t&&s){var o=i._structure.testFilesById[n];o&&e.globalErrors.push({message:"Test file '"+o.path+"' is importing or is causing import of another test file '"+s.path+"'.\nThis may cause tests in the '"+s.path+"' file to be executed more than once (when the test file runs and every time it gets imported).\nIf the '"+s.path+"' test file contains some test helper code, try refactoring the reused code into a file of its own and use it by importing th 
[Error] SyntaxError: Invalid regular expression flags 
[Error]     at createScript (vm.js:56:10) 
[Error]     at Object.runInThisContext (vm.js:97:10) 
[Error]     at Module._compile (module.js:542:28) 
[Error]     at Object.Module._extensions..js (module.js:579:10) 
[Error]     at Module.load (module.js:487:32) 
[Error]     at tryModuleLoad (module.js:446:12) 
[Error]     at Function.Module._load (module.js:438:3) 
[Error]     at Module.runMain (module.js:604:10) 
[Error]     at run (bootstrap_node.js:389:7) 
[Error]     at startup (bootstrap_node.js:149:9) 
```

**Comment by smcenlly** [comment]
Could you please:

1. Attach your `/Users/redacted/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.251/wallabye4709b/server.js` file to this issue so that we may inspect it to see if it is somehow corrupted?
2. Delete your Wallaby core folder ` /Users/redacted/.vscode/extensions/wallabyjs.wallaby-vscode-1.0.251/wallabye4709b` and then restart VS Code; Wallaby will then re-download the latest version, which will fix your problem if the files are somehow corrupted.

If you're still having a problem after that, we suspect that your issue is environmental. If you have access to another machine, could you please see if you have the same problem there (we cannot reproduce your problem on Windows/Mac/Linux using your version of Node.js)? We also found a [similar issue with eslint](https://github.com/eslint/eslint/issues/12538#issuecomment-555443501) and for one person, the problem was nvm not pointing to the correct node version:

> For me, this turned out to be something to do with nvm, updating it to the latest version got it working again.

**Comment by adamShaleen** [comment]
See attached 
[server copy.txt](https://github.com/wallabyjs/public/files/5655214/server.copy.txt)

`server.js` file.

Deleted the core folder and re-started without any change.

Upgraded to the latest version of NVM without any change.

**Comment by smcenlly** [comment]
The `server copy.txt` is exactly the same as the shipped version of Wallaby.js so there's no corruption issue.

**Could you also please:**
1. Try installing and using a different version of `node.js`? 
1. Provide us with a copy of newly created `create-react-app` project in case there is an issue with the project itself?

If you're still online and want to talk through this over real-time chat, we also have a [discord channel](http://wallabyjs.com/chat) that we can use to minimize any wait time for you.

**Comment by smcenlly** [comment]
I'm going to close this issue since we haven't heard back and cannot reproduce your problem. Our assumption is that there is something wrong with your environment but without your feedback we cannot confirm.

Please let us know if you're continuing to have problems and we'll re-open this issue.
