### ISSUE TITLE
Failing test does not highlight red when called through an intermediary function

### ISSUE THREAD

**Issue by ryall** [wallabyjs/public#2577]
### Issue description or question

When using an intermediary function for tests, the test highlights green, even if the test is failing. I would expect the failing test to highlight red.

![](https://i.imgur.com/ZZITcIJ.png)

```ts
function repetitiveTest(expectTrue) {
  return () => {
    expect(expectTrue).toBeTrue();
  }
}

it('tests true', repetitiveTest(true));
it('tests false', repetitiveTest(false)); // This should be red
```

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This behavior is actually expected and is a result of how you have structured your code. With your code structure, when using any other test runner, you will see that stack traces do not reference your tests, which is why Wallaby is not reporting correctly.

To determine the path of a failing test (and the failing test itself), Wallaby needs a correct stack trace to be reported that shows that the error is related to the test.

Normally when you define a function for your test, it will be an inline function, which will nest the stack traces within the context of the `it()` block. For example:

```javascript
it('tests true', function () { 
   expect(true).toBeTrue();
});
```

When you pass a function (as you are doing) instead of creating an inline function, the stack trace starts to report a little differently. In your case, you will see a stack trace of :

```
  // test('tests true', repetitiveTest(false));

  at Object.<anonymous> (my.test.js:3:24)
```

When you define an inline function, the stack trace for any errors will be within the context of the `it()` block with a stack trace that maps to your test:

```
  // test('tests true', () => repetitiveTest(false)());

  at src/App.test.js:3:24
  at Object.<anonymous> (src/App.test.js:9:26)
```

---

In your case, we believe that it would be best to convert your tests to inline format (see below) as not only will this allow Wallaby to correctly report failing tests, it will also correct stack traces outside of Wallaby.

```javascript
function repetitiveTest(expectTrue) {
  return () => {
    expect(expectTrue).toBeTruthy();
  }
}

test('tests true', () => repetitiveTest(true)());

test('tests true', () => repetitiveTest(false)());
```
