### ISSUE TITLE
Configuration fails with npm workspaces

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#2599]
### Issue description or question

We have an oss project (https://github.com/par-gen/par-gen) which does not work with neither the automatic configuration nor the manual configuration.

- With the automatic configuration no tests are found (may be the case, because we need `NODE_OPTIONS=--experimental-vm-modules` to run our tests. But `NODE_OPTIONS=--experimental-vm-modules npx jest` does run sucessfully.
- With simple configuration file (with `files`, `tests`, `env` set to node and with flags) wallaby spawns a lot of processes and keeps allocating memory and CPU without every finishing first startup.

### Wallaby diagnostics report

Not available due to the description above.

**Comment by smcenlly** [comment]
Thanks for providing the link to your OSS project.

You can get Wallaby running on your project by overriding your [automatic configuration default](https://wallabyjs.com/docs/intro/config.html#overriding-automatic-defaults) to specify the `NODE_OPTIONS` as an [environment variable for Wallaby's test runner](https://wallabyjs.com/docs/config/runner.html) processes.

You can do this in an external configuration file, or within your `package.json` within a `wallaby` section ([described in our docs](https://wallabyjs.com/docs/intro/config.html#configuration-in-packagejson)).

The configurations (config file and package.json) are provided below. If you are using a configuration file, make sure that you select for Wallaby to use the configuration file instead of automatic configuration. If you add a `package.json` configuration, you can continue to start Wallaby as you do today.

**Wallaby.js configuration file**
```javascript
module.exports = () => {
  return {
    // tell Wallaby to use automatic configuration
    autoDetect: true,

    // tell Wallaby to start its test runner processes with NODE_OPTIONS environment variable
    env: {
      type: 'node',
      params: {
        env: 'NODE_OPTIONS=--experimental-vm-modules'
      }
    }
  }
};
```

**package.json**
```javascript
{
...
  "wallaby": {
    "env": {
      "type": "node",
      "params": {
        "env": "NODE_OPTIONS=--experimental-vm-modules"
      }
    }
  }
}
```

---

We also noticed that Wallaby was taking a long time to execute the tests in `packages/dfa/lib/dfa.test.js`. The test with 50,000,000 iterations is taking a lot longer in Wallaby vs. with `jest`. This is expected as Wallaby adds a little bit of overhead to your test execution times to provide its features. This time is normally not noticeable (e.g. is usually a small fraction of a millisecond for a single test) but when running in a tight loop (e.g. 50M iterations), this can slow things down. You may like to investigate our [code coverage hints](https://wallabyjs.com/docs/intro/coverage.html) to exclude specific source files from code coverage calculations, which may fix your problem, or else exclude this test (or run with a smaller number of iterations) when using Wallaby (when `process.env.WALLABY_ENV` exists).

**Comment by KnisterPeter** [comment]
Thanks
