### ISSUE TITLE
Wallaby slow response times after changes

### ISSUE THREAD

**Issue by vandammeb** [wallabyjs/public#2616]
### Issue description or question

Recently, the feedback wallaby produces has been coming in much slower than usual (can take up to a minute after changing a single test)

Example: https://streamable.com/qbf43d

### Wallaby diagnostics report

[diagnostics.txt](https://github.com/wallabyjs/public/files/5913345/diagnostics.txt)

**Comment by smcenlly** [comment]
We have analyzed your log, and in terms of the events and where time is being spent, this is what we can see:

### Initial Test Run (Successfully ran 4059 tests)
Time | Duration (seconds) |  
-- | -- | --
5:51:36 PM | 5.49 | Start Wallaby / Initialize Project
5:51:41 PM | 107.95 | Webpack/Typescript Compilation
5:53:29 PM | 34.55 | Run all tests
5:54:04 PM | 3.31 | Merge test results from multiple workers
5:54:07 PM | - | Send Results to IDE
**TOTAL EXECUTION TIME** | 151.30 |  

### File Change 1 (Execution Cancelled due to file change)
Time | Duration (seconds) |  
-- | -- | --
5:54:57 PM | 0.06 | File changed in Editor
5:54:57 PM | - | Webpack/Typescript Compilation (does not complete)
5:55:23 PM | - | File changed again in Editor
5:55:23 PM | 26.62 | Webpack compilation cancelled
**TOTAL EXECUTION TIME** | 26.68 |  

### File Changed 2 (Successfully ran 16 tests)
Time | Duration (seconds) |  
-- | -- | --
5:55:23 PM | 5.31| File changed in editor / cancel current test run
5:55:29 PM | 26.14 | Webpack/Typescript Compilation
5:53:29 PM | 1.64 | Run affected tests
5:54:07 PM | - | Send Results to IDE
**TOTAL EXECUTION TIME** | 33.09 |  

---

_Note: The logs indicated that you changed `speed-test-connection-level.enum.spec.ts` in your editor twice after the initial test run was complete. It looks a successful change takes ~33 seconds to process and the second change was made ~26 seconds after the first change so you would have needed to wait a little over a minute to see any results. This behavior is expected if you make multiple changes to the same file (Wallaby cancels any in-progress tests)._

In terms of performance, can you please let us know the total time that it takes to run your tests outside of Wallaby (e.g. using `ng test`). Do you see a similar execution time to our initial test run? (`2 minutes and 30 seconds)`.

Our logs indicate that the majority of time is spent compiling TypeScript and bundling Webpack. Has anything in your project changed recently that would have increased TypeScript compilation times or Webpack bundling times? E.g. change `tsconfig.json` settings, adding a lot more TypeScript files to your project, upgrading dependencies, etc.? Are you able to see if the performance of your project returns to previous behavior by reverting to a previous commit from a few weeks/months ago?

Another thing to do to try isolate your problem is to double check whether the performance issue is caused by your project configuration, application files, etc. or whether it is a result of changes to Wallaby (note: we haven't changed anything in our TypeScript/Webpack compilation in the last few months, but there may be something else going on). Since you are using IntelliJ, we recommend following our [offline installation instructions for IntelliJ](https://wallabyjs.com/docs/intro/offline.html) and installing Wallaby server version `v1.0.1001` (see step 2) from `Installing from scratch`. Wallaby `v1.0.1001` was released on December 23rd, 2020 and we're assuming Wallaby was still behaving well for you at that time. If you need an earlier release version, let us know what date you'd like to go back to and we can provide a different version for you.

I'm going to assume that your project is closed source and you can't do this, but if your project is open source, or you are able to share with us privately, we'd also be happy to take a look at what's going on for you.

**Comment by smcenlly** [comment]
If you need further assistance, could you also please [enable Wallaby's trace option](https://wallabyjs.com/docs/intro/troubleshooting.html#more-debug-information) to provide us with additional debug information and then send us the updated diagnostics report?

**Comment by smcenlly** [comment]
We've been experimenting today with the latest version of Angular (v11) and it looks like incremental compilation in Angular v11 is quite slow. We're not sure if this is a change from Angular v10 (testing it at the moment). Is it possible that you recently updated your project to use Angular v11 and were using a previous version before now?

If the issue is new to Angular v11, the best case scenario is that we will be able to update Wallaby to improve the processing speed for Angular v11. The worst case scenario is that this is a regression in the speed of Angular v11 and something that the Angular team will need to improve.

We'll post back when we have an update to share (either today or tomorrow).

**Comment by smcenlly** [comment]
Another update: it looks like this problem is related to Wallaby and doesn't occur using `ng cli`. We'll let you know when we have a fix.

**Comment by vandammeb** [comment]
@smcenlly thanks for following up on this, do you need me to look into any of the suggestios you made in prior replies?

**Comment by smcenlly** [comment]
No, thanks for checking. Please wait for our next update.

**Comment by NikGovorov** [comment]
Thanks for reporting the issue. It is fixed and the fix is published in [the latest core version](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by vandammeb** [comment]
@smcenlly @NikGovorov thx!
