### ISSUE TITLE
Wrong title in Show side-by-side diff

### ISSUE THREAD

**Issue by martinduo** [wallabyjs/public#2624]
When testing two  objects to be equal as shown below:
expect(planIras1).toEqual(_modulePlanObject.zz.iras)

The "Show side-by-side diff" display is reversed.
The way it is shown, the correct title should be "Actual vs Expected"
See image. The expected data is green. The actual is the red.

![image](https://user-images.githubusercontent.com/879852/107855855-ec5d9000-6df2-11eb-9f30-6b6a5aba30be.png)

**Comment by martinduo** [comment]
Maybe a more correct title would be Received vs Expected.

**Comment by smcenlly** [comment]
The standard format of expectation libraries is:

> ```javascript
> expect(actualValue).toEqual(expectedValue)
> ```

For example, you can see this in [Jasmine API](https://www.npmjs.com/package/jasmine-expect#-api), [Jest API](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/jest/index.d.ts#L860).

So for the example:

```javascript
expect({ value: "actual" }).toEqual({ value: "expected" });
```

Wallaby correctly displays:

![image](https://user-images.githubusercontent.com/2074089/107864037-77e32980-6ea4-11eb-9bdc-64cbc5a29dcd.png)

> Maybe a more correct title would be Received vs Expected.

The terms used, `expected` and `actual` are the most correct terms for us to use and are standard in testing assertion libraries, including [node.js](https://nodejs.org/api/assert.html).

---

If for some reason you expected vs. actual values are not being reported correctly for your testing library, please provide your Wallaby diagnostics report and some details of the assertion library that you are using so that we can confirm there is a problem.

**Comment by martinduo** [comment]
Thanks for your explanation. I was not familiar with that documentation.
