### ISSUE TITLE
Can wallaby monitor new files?

### ISSUE THREAD

**Issue by hagishi** [wallabyjs/public#2628]
After starting wallaby I want to automatically monitor newly created files. 
Is this possible?

**Comment by ArtemGovorov** [comment]
Yes, by design Wallaby automatically monitors newly created files. However, we have recently updated Wallaby dependency that stopped Wallaby on Mac from picking up new files. The issue has been fixed and the fix is published in [the latest core v.1.0.1030](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
