### ISSUE TITLE
Uninstalled unexpectedly

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#263]
I can remember an update balloon notification this week. Now I restarted IntelliJ after a couple of days and Wallaby is gone. It is not in the "plugins" list anymore. The only thing that is left of Wallaby is the "balloon notifications" setting.
Reïnstalling makes everything work again, but this is really weird.

Any idea how this could happen?

**Comment by ArtemGovorov** [comment]
As far as I remember, when you install any plugin update, IntelliJ schedules some actions to be performed for the next IDE start to complete the installation. If I'm not mistaken the scheduled actions are saved somewhere on disk, not sure where, maybe in some temp folder, maybe not. Anyway, it's possible that in a couple of days that scheduled update file was corrupted/deleted, maybe tmp folder was cleaned up. It's the only idea I have about how it could happen, because nothing has changed in wallaby update mechanism in several months. 

Anyway, please let me know if you have a similar issue with future updates.

**Comment by fvanwijk** [comment]
I had this issue again today, however the use case is different. An IntelliJ update was done a couple of hours ago and I restarted immediately (IntelliJ asks for a restart).

Now Wallaby is uninstalled and I have to reinstall Wallaby using the zip file.

**Comment by ArtemGovorov** [comment]
It may happen if IntelliJ had changed its installation folder (as a result of the version change), and for some reason didn't copy all plugins to the new one. I have seen it a couple of times, but there's nothing in wallaby plugin that control/affects this process, so I'm not sure the issue is on the wallaby plugin side.
