### ISSUE TITLE
All indicator icons are grey

### ISSUE THREAD

**Issue by martinduo** [wallabyjs/public#2649]
### Issue description or question

Today Wallaby is running but all indicator buttons are grey, no red, no green. What happened?
I ran Wallaby `Copy Diagnostics Report` and got the info  pasted below.
I am naming my test files as *.test.js not *.spec.js as shown there. Is that the problem? All has worked before today.

### Wallaby diagnostics report

module.exports = () => {
  return {
    files: ['src/**/*.js'],
    tests: ['src/**/*.spec.js'],
    env: {
      type: 'node',
    },
  }
}

**Comment by martinduo** [comment]
After several hours with VSCode being left up, the colors have returned. And now I reloaded and the colored icons appeared right away, as before.

**Comment by smcenlly** [comment]
Since Wallaby is now working for you, I'm going to close this issue. This problem can happen when there's something wrong with your tests. Normally you would have some error information displayed in your Wallaby Console window.

If the problem happens again, please provide your full Wallaby Diagnostics report as well as the output of your Wallaby Console window.
