### ISSUE TITLE
More precise error message position 

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#266]
Is there possible to make position of error message more precise
![2015-09-18 wallaby atom mongo set not defined](https://cloud.githubusercontent.com/assets/341600/9956932/a4a26a62-5dfc-11e5-8bb3-4bb38aa3d37b.png)

to make error localizing easier:

![2015-09-18 wallaby atom mongo set not defined i want to](https://cloud.githubusercontent.com/assets/341600/9956934/a8adc7b4-5dfc-11e5-9b62-2631bcdb2da9.png)

**Comment by fvanwijk** [comment]
The error happens **inside** the `findOneAndUpdate` method, which is called at the first line (or the seventh...). The JS runtime cannot see that the `$set` value is passed in the fourth line afaik.

You could make debugging easier for yourself by setting some parameters before the function call so that you can make the `findOneAndUpdate` statement a one liner:

```javascript
var query = { ... },
  doc = { $set: $set },
  options = { sort: [[...]], returnOriginal: false,
  callback = function (err, result) { ... };

db.collection(collName).findOneAndUpdate(query, doc, options, callback); // "before each" hook: $set is not defined
```

**Comment by hellboy81** [comment]
IMHO in your code is harder to localize errors, as in my first sample

**Comment by ArtemGovorov** [comment]
I think it's a limitation of wallaby.js. If `$set` is not defined somewhere above (before it is passed to `findOneAndUpdate`), then the original code execution in node reports the correct line, but wallaby does report `findOneAndUpdate` call line (major reason is because wallaby.js doesn't execute your original code, but instrumented version of it, so some 'precision' in terms of positions is lost). I'll add the 'enhancement' tag.

**Comment by hellboy81** [comment]
OK, this issue can be fixed?

**Comment by ArtemGovorov** [comment]
Theoretically yes, at least for node.js. I'll have to look deeper, it may require a lot of work to fix comparing to the benefits that it brings.

**Comment by geekflyer** [comment]
Hi @ArtemGovorov . I'm having a similar (but I guess not exactly the same) issue:

In my code I'm using a lot of Bluebird promises with the longStackTraces feature enabled.
Now with some bugs I've noticed that the stack trace when running my tests via mocha is way more detailed. In particular it tells me which exact character / function invocation caused the issue, whereas wallaby just tells me the line. When there's a line with multiple nested function invocations this information is very useful and makes it much easier to spot the root cause.

Here's a simple example:

This is the source code:
```js
  const resultSet = await client.execP(query, {rowsAsArray: true});
```

the error occurs when calling `execP`.

Here's the error message I get with wallaby:
```txt
test/HdbDataManager.test.ts HdbDataManager create a table, populate it, extract it to disk and recreate it from disk [130 ms]

	sql syntax error: incorrect syntax near "$": line 1 col 112 (at pos 112)
		at src/db.ts:57
		at src/db.ts:30
		at src/HdbDataManager.ts:159
		at src/HdbDataManager.ts:47
		at src/HdbDataManager.ts:126
		at test/HdbDataManager.test.ts:81
```

And here's the same with mocha runner
```txt
 3) HdbDataManager create a table, populate it, extract it to disk and recreate it from disk:
     Error: sql syntax error: incorrect syntax near "$": line 1 col 112 (at pos 112)
      (No stack trace)
  From previous event:
      at Object.<anonymous> (lib/src/db.ts:57:34)
      at next (native)
      at lib/src/src/db.js:7:65
      at __awaiter (lib/src/src/db.js:3:12)
      at Object.hasPrivilege (lib/src/src/db.js:52:12)
      at HdbDataManager.<anonymous> (lib/src/HdbDataManager.ts:159:54)
      at next (native)
      at lib/src/src/HdbDataManager.js:7:65
      at __awaiter (lib/src/src/HdbDataManager.js:3:12)
      at HdbDataManager.getObjectDefinition (lib/src/src/HdbDataManager.js:114:16)
      at HdbDataManager.<anonymous> (lib/src/HdbDataManager.ts:90:12)
      at next (native)
      at lib/src/src/HdbDataManager.js:7:65
      at __awaiter (lib/src/src/HdbDataManager.js:3:12)
      at HdbDataManager.saveObjectToFile (lib/src/src/HdbDataManager.js:58:16)
      at Context.<anonymous> (lib/test/HdbDataManager.test.ts:81:26)
      at next (native)
      at fulfilled (lib/test/test/HdbDataManager.test.js:4:58)
```

You can see that the stack trace in mocha points to line 57 and character 34 which is exactly where the `execP` function starts. Wallaby only points to line 57.

Could this be fixed in a next release?

Does this have to do something with the precsision of the sourcemaps internally created by wallaby? Perhaps it would be good to have to flag to control this precision.

**Comment by ArtemGovorov** [comment]
> Does this have to do something with the precision of the sourcemaps internally created by wallaby? 

Yes, wallaby.js uses a lightweight version of source maps to achieve better performance. When we've been making the decision to go with the lightweight version of source maps, we did consider scenarios that you've mentioned.

In your example the `execP` is the obvious source of the error. There're no other function calls, and in case if `client` or `query` wasn't defined there'd be another descriptive error message.

In most of cases we've been observing, the line number + the error message is more than enough to see where the error is. 

The main case where the column number is really essential, is when there's a line with multiple nested function invocations, all or most of them are library code (otherwise there'll be a stack entry inside one of those functions), and the error message content is not immediately logically pointing to the right place.

While I totally agree that the column number makes it much easier to spot the root cause in that case, given that the case is not very common, the goal of having a better performance had outweighed the convenience of having the column number.

> Could this be fixed in a next release?

We'll add function names soon, as for the column numbers we'll have a look into this in a next few weeks, but I can't provide any ETA on it.

**Comment by smcenlly** [comment]
We have made (and continue to make) various improvements to Wallaby's source map support that we expect addresses this issue (as well as others). Closing this issue. If there are specific problems around error reporting/mapping, please create a new issue.
