### ISSUE TITLE
Does Wallaby work work with Stencil?

### ISSUE THREAD

**Issue by SKopsap** [wallabyjs/public#2672]
### Issue description or question

Wallaby not working with Stencil, or I am doing something wrong... guidance needed...

Hi, I am a junior developer trying to get wallaby to work with a stencil project I am working on... I setup the configeration file as follows:

```javascript

module.exports = function (wallaby) {
  return {
    files: [
      'src/**/*.js'
    ],

    tests: [
      'test/**/*Spec.js'
    ],
    testFramework: 'Jest',
    preserveComments: true,
    reportConsoleErrorAsError: true,
    slowTestThreshold: 200,
    runMode: 'onsave'
  };
}

```

**Comment by smcenlly** [comment]
Testing within Stencil is broken up into two distinct types: **Unit tests** and **End-to-end** (e2e) tests.

Wallaby can run Stencil **Unit tests** but cannot run **e2e tests**.

Under the covers, `stencil` is using `jest` to run your tests. It dynamically sets the jest configuration for your tests in the CLI code when you run `stencil test --spec`. Unfortunately this means that both Wallaby and the `jest` CLI do not have the configuration settings it needs to run your tests. In order to use Wallaby you must first configure your project to run `jest` for your unit tests from the CLI using `npx jest`. Once you have that working, you may start Wallaby for `jest` using automatic configuration (instructions provided in our [docs](https://wallabyjs.com/docs/integration/jest.html)) and everything will work for you.

We are not super familiar with stencil (and obviously not familiar with your project) but we were able to configure jest to run on a simple getting started project by adding a single file:

**jest.config.js**
```javascript
module.exports = {
  preset: '@stencil/core/testing',
};
```

If that doesn't work for you, you may need to ask someone with more stencil experience for advice on getting jest to run from the CLI for your project.
