### ISSUE TITLE
Is it possible to ignore a directory but still using the automatic configuration? 

### ISSUE THREAD

**Issue by SMH110** [wallabyjs/public#2697]
### Issue description or question
Hi,
I have some tests (pact tests) that I like to run them in the test pipeline only as they take long time to run locally, and they cause vscode to run out of memory.
I tried to create my own wallaby.js  file following [this example ](https://github.com/wallabyjs/wallaby-create-react-app-ts) but didn't find my configuration as good as the automatic configuration and faced many issues such as `jasmine is not defined` . so I was wondering if there's a way to ignore a directory and still use the automatic configuration.

**Comment by smcenlly** [comment]
Can you tell us how you're running your tests outside of Wallaby?

In order to override any automatic configuration defaults, you may use a Wallaby Configuration file or add a `wallaby` section to your `package.json` file, specifying the `autoDetect`: `true` setting and then any Wallaby settings that you want to add/override:

**wallaby.js configuration file**
```javascript
module.exports = () => ({
   autoDetect: true,

   // Override other settings...
   ...
});
```

**Comment by SMH110** [comment]
Thank you this is answered my question.
I managed to exclude some tests and everything seems to work fine
```js
module.exports = function () {
  
    return {
        autoDetect: true,
        tests: ["src/**/*.test.ts?(x)", "!src/**/*.Pact.test.ts"],
    };
};

```
