### ISSUE TITLE
Unreadable code images

### ISSUE THREAD

**Issue by martinduo** [wallabyjs/public#2699]
### Issue description or question
I'm an enthusiastic user of Wallaby wirh React on VBCode and Windows 10. However I'm color blind and I really can not use your documentation because of the dark mode with the low contrast text. on your images and video tutorials. By any chance could you supply a light mode version of those items? Since I just started getting the Output Inspector window, I want to learn how to use it.

### Wallaby diagnostics report

<module.exports = () => {
  return {
    files: ['src/**/*.js'],
    tests: ['src/**/*.spec.js'],
    env: {
      type: 'node',
    },
  }
}

**Comment by smcenlly** [comment]
Hi @martinduo - we can absolutely help with this. I'm sorry that you had a problem, accessibility is important to us and we weren't aware that people may be having difficulties so really appreciate your feedback.

Is your problem the VS Code start page or are your referring to specific pages of our website?

If the images are a problem it seems like high contrast might be better than a light mode output. Do you also have trouble distinguishing the visual indicators? In the past we have provided some steps to customize these for VS Code, so we can help with that also.

In addition to addressing your immediate concerns, we'll review other parts of our product/docs for similar accessibility issues.

**Comment by martinduo** [comment]
Thanks for your reply. I was reading the email of April 27 where you
announce the Webinar on May 26th. In the email you have links to Output
Inspector and Test Profiler. I clicked on Output Inspector and got this. I
think it can be improved . I'm running on a 27" 3840 x 2160 monitor set at
150% scale.

[image: image.png]

BTW, several months ago when I was a new user, I asked about documentation
and was told to look at a video (made at an earlier Webinar?). That had
good information but suffered from the same dark mode theme. I was able to
get some help from it but I gave up after a short time. Maybe this
upcoming Webinar can provide a better video?

**Comment by smcenlly** [comment]
For some reason the image didn't come through. Besides the black screen, I'm wondering if part of the problem is that the responsive nature of our webpage is making the images too small to read effectively with your zoom.

If you open this url in a new tab, is it any easier for you?

[https://wallabyjs.com/assets/img/vsc-output-inspector-value.gif](https://wallabyjs.com/assets/img/vsc-output-inspector-value.gif)

**Comment by martinduo** [comment]
I've attached the images, maybe these will be available for you.

The "Image in a new tab.png" is somewhat easier to read, but the content is
different, it seems like some of the hard to read syntax lines are not
present.

In the "Image from April email link.png" image, notice the lines 21, 55,
57, 39, 41. I can barely make them out.

I have been using the NetBeans Light Theme for years, and all those
different colors on a dark background is really visually jarring. It's hard
to ignore the colors and just read the code for its flow, especially if
some lines are almost invisible. Sorry to be so negative about a great
product, but that's my user feedback.

**Comment by smcenlly** [comment]
Unfortunately the images still haven't come through. I don't think you can attach them by replying to the email, you will need to add them via the github website.

[https://github.com/wallabyjs/public/issues/2699](https://github.com/wallabyjs/public/issues/2699)

**Comment by martinduo** [comment]
Here are the two images that I have tried to send before via email. The comments in my last post still apply.

**Image in a new tab**
<img width="1078" alt="Image in a new tab" src="https://user-images.githubusercontent.com/879852/118275946-10ce1480-b495-11eb-94d8-4c78c9bb156c.png">

**Image from April email link**
<img width="752" alt="Image from April email link" src="https://user-images.githubusercontent.com/879852/118275943-10357e00-b495-11eb-83a2-87ca47ea5eac.png">

**Comment by smcenlly** [comment]
Thanks for providing the images.

> The "Image in a new tab.png" is somewhat easier to read, but the content is different, it seems like some of the hard to read syntax lines are not present.

Some of our images (such as the `Output Inspector` video) are actually quite high definition but are resized in our docs. If the new tab was easier to read, it is likely that you were looking at an image that was resized from a larger resolution. We're going to provide a new overlay that allows you to view videos/images full-screen to improve readability. This should make it easier to see the detail in videos and screenshots.

> In the "Image from April email link.png" image, notice the lines 21, 55, 57, 39, 41. I can barely make them out.

This is actually by design but we can understand how/why this is problematic for you. Those lines are intentionally greyed out as we don't expect people to normally read them; they are provided for context only. Having said that, depending on your theme (and any accessibility issues you have), our opacity settings may require adjustment. As of today, we have added a new setting to VS Code to allow you to adjust this (accessible via VS Code settings), `wallaby.dimmedTextOpacity`. You may set it up to 100 although we'd recommend experimenting with what works for you:

![image](https://user-images.githubusercontent.com/2074089/118572687-5e63bd80-b7c4-11eb-9f13-52b7b6b0eb65.png)

I've also included the same Output Inspector image using the NetBeans Light theme (below):

![image](https://user-images.githubusercontent.com/2074089/118568049-51da6780-b7ba-11eb-8320-a0320195826e.png)

---

> I have been using the NetBeans Light Theme for years, and all those different colors on a dark background is really visually jarring. It's hard to ignore the colors and just read the code for its flow, especially if some lines are almost invisible. Sorry to be so negative about a great product, but that's my user feedback.

I understand where you're coming from but unfortunately the cost of recording multiple different themes isn't feasible for us. Equally, I think users familiar with the default VS Code dark theme (which we use for screenshots/videos) may find it harder to interpret the NetBeans Light theme because it's missing the colors they use as visual indicators for understanding their code. While we want/need our website/docs to be accessible, we also try and target how most users will have their editor configured. We have an internal backlog item to review providing light themed images/videos that we expect to review in September/October timeline.

In the meantime, one of our next big initiatives that we are already working on is an interactive tutorial for Wallaby for VS Code. This will run in your editor with your current theme so I also think that this will help you (and many others).

> BTW, several months ago when I was a new user, I asked about documentation and was told to look at a video (made at an earlier Webinar?). That had good information but suffered from the same dark mode theme. I was able to get some help from it but I gave up after a short time. Maybe this upcoming Webinar can provide a better video?

For a few months, we were inadvertently using a low-quality version of the Webinar record. In February 2021, we replaced this with a [higher quality version](https://www.youtube.com/watch?v=HmWefc-8X8c&t=1s). While still using a dark theme, it may be easier for you to view. If you have the time to check it out, we'd appreciate your feedback as to whether the HD version is OK for you.
