### ISSUE TITLE
Nx/Nrwl support not works well

### ISSUE THREAD

**Issue by tamascsaba** [wallabyjs/public#2707]
We use nx with multiple angular application, previously everything works well with automatic configuration, but few days ago its stops working.

The reason wallaby reads only the global `jest.config.js` and ignore apps jest config files, so `setupFilesAfterEnv`, `moduleNameMapper`, ''moduleDirectories missing and the test run fail with lot of unexpected error. 

Core version:
core v1.0.1055

**Comment by smcenlly** [comment]
Have you recently updated your NX dependencies? Could you please share your [Wallaby Diagnostics report](https://wallabyjs.com/docs/intro/troubleshooting.html#diagnostics-report)?

**Comment by smcenlly** [comment]
Unfortunately we can't replicate your issue using either the latest version of Wallaby or the version of Wallaby that you are using. We created a new nx workspace with two angular apps and all tests are running for us.

Since the version of Wallaby you are using, we have made a number of improvements to how we detect and run Jest multi-project mono-repos. (https://github.com/wallabyjs/public/issues/2687, https://github.com/wallabyjs/public/issues/2689). We have also fixed an angular jest problem on April 21st, 2021 due to a recent change in angular jest-builder that may be affecting you.

Could you please update to use the latest version of Wallaby to see if that fixes your problem? If your license has expired, you may [request a trial](https://wallabyjs.com/download/#try-it-free) or else email us for a license (hello@wallabyjs.com).

If it's still not working for you in the latest version, could you please provide us with a sample repo that has the same problem?

**Comment by smcenlly** [comment]
Closing this issue out as we haven't heard back.
