### ISSUE TITLE
wallaby doesn't work with typescript and webpack together

### ISSUE THREAD

**Issue by slikts** [wallabyjs/public#271]
I tried adapting the wallaby webpack sample to TS and it doesn't work: https://github.com/slikts/wallaby-webpack-sample/commit/dd960923655a294b17d4587beee8afd98006ae9c

It can't import the chai module and there is no output from the test.

**Comment by ArtemGovorov** [comment]
Wallaby.js needs to compile Typescript/CoffeeScript in order to display coverage for it. It means that you'll have to use wallaby built-in TypeScript compiler and will not need webpack ts-loader plugin for wallaby.

However, because wallaby TypeScript compiler is actually a postprocessor behind the scenes and Webpack also requires a postprocessor, the scenario is not yet supported by wallaby. I'll add the support for the scenario and will share the working config with you, stay tuned!

**Comment by ArtemGovorov** [comment]
Ok, so I have added multiple postprocessors supports, so now (once updated to core v1.0.103 - should happen automatically next time you restart wallaby/IDE) your sample should work with the config like this:

``` JavaScript
var babel = require('babel');
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({});

module.exports = function () {

  return {
    files: [
      {pattern: 'src/*.ts', load: false}
    ],

    tests: [
      {pattern: 'test/*Spec.*s', load: false}
    ],

    postprocessor: webpackPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

Note that you don't need to configure wallaby TypeScript compiler because it's on by default. If you need to pass some compiler options from your `tsconfig` file, you may need to explicitly add TypeScript compiler and its configuration to wallaby config [like described here](http://wallabyjs.com/docs/integration/typescript.html#typescript-compiler-settings).

**Comment by slikts** [comment]
Thanks, it works now.
