### ISSUE TITLE
Do not modify `color_scheme` on Sublime Text 4

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#2710]
### Issue description or question

Sublime Text plugin modifies `color_scheme` on start automatically which is not convenient.

If I have `color_scheme: auto` setting  then Wallaby plugin tries to update it and set to `Packages/Color Scheme - Wallaby/auto` which produces an issue:
```
Error loading colour scheme Packages/Color Scheme - Wallaby/auto: Unable to open Packages/Color Scheme - Wallaby/auto 
```

`Preferences.sublime-settings`

```json5
{
	// Sets the colors used within the text area.
	// The value "auto" will switch between the "light_color_scheme" and
	// "dark_color_scheme" based on the operating system appearance.
	"color_scheme": "Mariana.sublime-color-scheme",
	// Controls the "color_scheme" when set to "auto"
	"light_color_scheme": "Breakers.sublime-color-scheme",
	"dark_color_scheme": "Mariana.sublime-color-scheme"
}
```

**Comment by mdreizin** [comment]
Please see more details about a new version at https://www.sublimetext.com/blog/articles/sublime-text-4.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This has been fixed in the latest version of Wallaby for Sublime Text, `v1.0.65`. To update to the new version, you may use the `Package Control: Upgrade Package` command. 

Please note that you may need to manually repair your Sublime Text preferences file if it was corrupted by Wallaby.

If you use Quokka.js, you will also need to update the Sublime Text Quokka package.
