### ISSUE TITLE
Show which test is causing an unresponsive sandbox

### ISSUE THREAD

**Issue by davidakerr** [wallabyjs/public#2738]
For error messages such as :
`'2021-06-22T10:22:40.815Z workers Sandbox is responsive. The issue may be asynchronous in nature (for example, a missing callback).\n',`

Is it possible to narrow in on which tests are causing the issues ?

I cannot share the report as it contains company information

**Comment by ArtemGovorov** [comment]
If Wallaby can detect what tests are causing an unresponsive sandbox, it normally prints the names as a part of error message, also when Wallaby can detect files causing an unresponsive sandbox, it also prints their names. However, sometimes it's not possible to determine any test/file names. Please check Wallaby Tests output channel for the full error message (or check error messages in Wallaby Console around the message that you have pasted in the issue description), because there may be some more details regarding the error there.
