### ISSUE TITLE
Don't use U+200b in Story View

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [wallabyjs/public#2740]
Issue Type: <b>Bug</b>

If anyone uses plugins that reveal possible problemetic characters like U+220B or U+FFEF or others this adds noise to the actual view.

![image](https://user-images.githubusercontent.com/86342787/123222588-5f2cf500-d4d0-11eb-9d35-2e409c0f7aed.png)

Extension version: 1.0.297
VS Code version: Code 1.57.0 (b4c1bd0a9b03c749ea011b06c6d2676c8091a70c, 2021-06-09T17:18:42.354Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5400 CPU @ 3.70GHz (4 x 3696)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.22GB free)|
|Process Argv|--crash-reporter-id 2ecdc59c-7d55-48a0-beaf-451bf71a6cf4|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
pythonvspyt602:30300191
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyt639:30300192
pythontb:30283811
pythonvspyt551cf:30311713
vspre833:30321513
pythonptprofiler:30281270
vshan820:30294714
pythondataviewer:30285071
vscus158:30321503
pythonvsuse255cf:30323309
vscorehov:30309549
vscod805:30301674
binariesv615:30325510

```

</details>

**Comment by smcenlly** [comment]
Wallaby Test Story viewer uses special characters to achieve its formatting. This is by design and fully supported by VS Code.

Wallaby has a number of different read-only views in VS Code using [Virtual Documents](https://code.visualstudio.com/api/extension-guides/virtual-documents) which may contain special (invisible) characters. The advice from the VS Code team for extension authors is:

> ... The rule for everyone is check the scheme of documents and then decide if you want to do something with/for the document.
> -- https://code.visualstudio.com/api/extension-guides/virtual-documents#events-and-visibility

The extension that is providing the special inline characters is not checking the scheme of the document before analyzing your document. If you can tell us which extension you're using, we can help you raise this issue with the extension authors.

**Comment by sschneider-ihre-pvs** [comment]
That is pretty unfortunate, https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins is doing a good job actually, why is that kind of formatting necessary, what happened to good old LF?

**Comment by nhoizey** [comment]
How would my extension know about all possible schemes and decide which ones to ignore? 🤨

**Comment by ArtemGovorov** [comment]
@nhoizey Maybe by default Gremlins should only check `file` scheme, and possibly [untitled documents](https://github.com/microsoft/vscode/blob/17bf4db58f2ee3f3d5b1a9060ddfc0bf95092fc1/src/vs/vscode.d.ts#L112)? Maybe there should also be a setting so that users can add additional schemes that they want to check?
