### ISSUE TITLE
Wallaby doesn't work at all in VSCode

### ISSUE THREAD

**Issue by jardicc** [wallabyjs/public#2757]
### Issue description or question

When I start wallaby it waits for an update that never happens. Therefore it doesn't work at all. It couldn't verify update integrity before. I disabled automatic updates and tried offline update. The first time it did work. But when I tried to enable automatic updates again because I want updates then it broke again.

### Wallaby diagnostics report
- there is nothing in my clipboard

**Comment by smcenlly** [comment]
Could you please open the VS Code Developer Tools with the `Developer: Toggle Developer Tools` and then tell us if you see any errors in the `console`?

You may need to uninstall Wallaby for VS Code and then delete the extension directory (by default: `~/.vscode/extensions/wallabyjs.wallaby-vscode-*`) and then reinstall to get the console to output any messages.

You should also be able to uninstall Wallaby and delete the extension directory and reinstall with the offline installation instructions to continue using Wallaby while we identify the automatic update issue.

It is possible that you are behind a corporate proxy server or firewall which needs to be configured in VS Code in order for for Wallaby's automatic updates to work:

<img alt="image" src="https://user-images.githubusercontent.com/2074089/127405030-a3ea7e7d-97fa-4571-aac0-9743843b25dc.png">

**Comment by jardicc** [comment]
I see this in console 
![image](https://user-images.githubusercontent.com/13526959/127850837-b5423969-1516-4cac-a902-5ae0e91ce42a.png)

**Comment by jardicc** [comment]
After extension uninstall and install again via VSCode marketplace

![image](https://user-images.githubusercontent.com/13526959/127851329-251f36d5-b278-4f5d-be89-0e0dfb7a4dd1.png)

**Comment by jardicc** [comment]
I tried offline installation once again and now the offline method works. I don't use any VPN or proxy server. I am in home office.

**Comment by smcenlly** [comment]
Glad to hear you got it working. Closing this issue.

**Comment by jardicc** [comment]
The problem is that I can't auto-update otherwise it would break again.

**Comment by smcenlly** [comment]
Could you please **email us (hello@wallabyjs.com)** and provide your `.wallaby` folder in your user home directory? You may try to send it as an attachment but it may get blocked by our mail server. Alternatively, you may upload to a cloud storage provider and send us a link to download it.

Wallaby verifies the update matches our digital signature once the update has been downloaded. This is what is failing in your case. The reason for this would either be because you are being a proxy server and it is not configured properly OR because the file is being modified after being downloaded by Wallaby (e.g. by your virus scanner).

You may also try disabling your virus scanner temporarily and reinstalling Wallaby once you disable the offline installation. If that works for you, you may try disabling your virus scanner from your `~/.wallaby` folder.

**Comment by smcenlly** [comment]
I'm closing this issue as we haven't heard back.

**Comment by jardicc** [comment]
hmm I started new project. Configured wallaby files and now 
![image](https://user-images.githubusercontent.com/13526959/128637681-f96c0923-ae3b-485d-89c4-d819a010b020.png)

But auto-updates are disabled 
![image](https://user-images.githubusercontent.com/13526959/128637701-769f825e-e060-4c53-ae12-366f62ce3b6c.png)

**Comment by jardicc** [comment]
apparently `wallaby` and `wallaby-app` folder within the extension folder were removed for no reason. Any idea why?

**Comment by smcenlly** [comment]
@jardicc - I assume that VS Code updated itself and/or the Wallaby extension and removed the old folder.

You may disable extension auto-updates using the VS Code command: `Extensions: Disable Auto Update for all extensions`. Auto updates are also disabled if you install a specific version of the extension:

![](https://user-images.githubusercontent.com/10746682/51469413-9a5ff280-1d71-11e9-9b15-2cddd8b90938.png)
