### ISSUE TITLE
Critical failure, v1.0.219 won't start on IntelliJ IDEA 2018.3

### ISSUE THREAD

**Issue by elads-sl** [wallabyjs/public#2763]
### Issue description or question

On IntelliJ IDEA Ultimate 2018.3
Wallaby v1.0.219 won't start with the following errors:
![image](https://user-images.githubusercontent.com/48408690/127886941-74700ffc-55e0-4af9-858a-fe12a03a9bd1.png)

I've been using wallaby for over 2 years and my previous version 1.0.217 worked just fine up until 5 minutes ago when I unfortunately chose to update.

```
TypeError: Cannot read property 'name' of undefined
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

Process finished with exit code 0
```

### Wallaby diagnostics report

Report unavailable.

**Comment by smcenlly** [comment]
While we investigate your issue, can you please downgrade to a previous version and confirm that it fixes your problem?

https://plugins.jetbrains.com/plugin/15742-wallaby/versions

Could you also please tell us the expiry date on your Wallaby license? You can access this by using `Help | Wallaby.js | Manage License` menu item.

**Comment by smcenlly** [comment]
We have tried the latest `IntelliJ IDEA 2018.3` with Wallaby `v1.0.219` and everything is working for us.

Could you please clone our [calculator sample repo](https://github.com/wallabyjs/calculator-sample) and see if it works for you? Depending on your system, you may need to create a run configuration and point it to the `wallaby.js` configuration file in your project root (instead of using automatic configuration).

If the calculator sample also doesn't work for you, then it is likely that somehow your Wallaby installation has become corrupted. In this case, please uninstall the Wallaby plugin from your editor, and then also delete the `wallaby` directory from your editor’s `System` directory. The location of this folder differs by editor version and operating system version, refer to the [JetBrains documentation](https://intellij-support.jetbrains.com/hc/en-us/articles/206544519-Directories-used-by-the-IDE-to-store-settings-caches-plugins-and-logs) to determine where the `System` directory is located for your editor and operating system. After doing this, please close all instances of your editor and then reinstall the extension.

If the calculator sample **does** work for you, then could you please provide us with your `package.json` dependencies as well as your Wallaby configuration? If you're using jest or babel, please provide us with your configuration for those files as well. If you're using Angular, please also provide your `angular.json` configuration file.

**Comment by elads-sl** [comment]
I'll start with where I'm at, no change. Unfortunately wallaby still doesn't work.

license ends April 20, 2022

full system reboot - no effect
downgraded to 1.0.217 - no effect
tried to run on the calculator sample - no effect
removed wallaby directory, reinstalled 1.0.219 - no effect
removed wallaby directory, reinstalled 1.0.217 - no effect

on windows 10, build 19042.1110

this whole mess started when I upgraded so I'm not sure where to go from here.

**Comment by ArtemGovorov** [comment]
> downgraded to 1.0.217 - no effect

It looks like the issue is not related to Wallaby update, likely some change in your environment may have caused it. 

Can you please try to install a most recent node.js version (side-by-side or instead of your current node version) and edit your Wallaby Run Configuration in IDEA to point Wallaby to that node exe then in the `Node.js` run configuration field.

**Comment by elads-sl** [comment]
upgraded my IntelliJ version to 2021.2 - no effect
upgraded node version from 8.11.4 -> 11.11 - WORKS
reverted to 8.11.4 - back to the same issue

the exact version I need to be able to use is 8.17.0, which I just tested and it doesn't work, same issue.

**Comment by ArtemGovorov** [comment]
Thanks for checking the node version. Looks like one one Wallaby recent dependency updates doesn't support node v8.x anymore. We have rolled back the dependency version and released the new version of core. If you restart your editor and then start Wallaby (or start and restart it once it updates), the issue should be resolved.
