### ISSUE TITLE
Cannot use Wallabyjs due to constant "Wallaby.js is updating and will be started automatically when the update is complete" message

### ISSUE THREAD

**Issue by MrClyfar** [wallabyjs/public#2773]
### Wallaby.js is updating and will be started automatically when the update is complete

Wallabyjs version v1.0.306
Version: 1.59.0 (system setup)
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.19041

I updated Wallabyjs today, and when I execute any Wallaby command I get this message...

> Wallaby.js is updating and will be started automatically when the update is complete

I followed the advice given here #2584 such as uninstalling, deleting folders, but nothing works.

Any advice would be appreciated.

**Comment by smcenlly** [comment]
Could you please uninstall Wallaby for VS Code and then delete:
1. the extension directory (by default: `~/.vscode/extensions/wallabyjs.wallaby-vscode-*`) 
2. the wallaby user folder `~/.wallaby`

Then re-install to see if that fixes your problem.

If it does not fix the problem, please immediately open the VS Code Developer Tools with the `Developer: Toggle Developer Tools` and then provide any errors that you see in the `console`?

If you see an error `Error while unzipping wallaby.js core file: could not verify core version`, can you please **email us (hello@wallabyjs.com)** and provide your `.wallaby` folder in your user home directory? You may try to send it as an attachment but it may get blocked by our mail server. Alternatively, you may upload to a cloud storage provider and send us a link to download it.

Wallaby verifies the update matches our digital signature once the update has been downloaded. This is what would be failing if you see this error. The reason for this would either be because you are being a proxy server and it is not configured properly OR because the file is being modified after being downloaded by Wallaby (e.g. by your virus scanner).

You may also try disabling your virus scanner temporarily and reinstalling Wallaby if you have this problem.

**Comment by MrClyfar** [comment]
Hello.

Thanks for the response.

I enabled the developer tools window, and tried to execute a wallaby command. I saw the following in the `console` output...

> Error: Error while downloading wallaby.js core, status code: 403. This may occur when you are behind proxy. Try setting VS Code's 'Http: Proxy' settings to fix the problem.

So this does point to a proxy config issue on our network that is stopping wallaby from making network requests. I will liaise with our InfoSec team to help sort this out.

Thanks again.

**Comment by smcenlly** [comment]
> So this does point to a proxy config issue on our network that is stopping wallaby from making network requests. I will liaise with our InfoSec team to help sort this out.

Yes - it sounds like a proxy issue. You may configure your proxy in VS Code's settings (note: this is not a Wallaby setting):

![image](https://user-images.githubusercontent.com/2074089/129813315-684e8711-d192-46da-990a-d8cc7f251048.png)

Alternatively, you may perform an offline installation ([instructions here](https://wallabyjs.com/docs/intro/offline.html)) if you are unable to configure your proxy correctly.
