### ISSUE TITLE
force-reload a module? clear cache?

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#278]
I'm using [babel-plugin-rewire](https://github.com/speedskater/babel-plugin-rewire).  I'm not sure where I should be filing the bug.  Basically, it ends up stuffing a bunch of extra code in my modules.  One bit of code there is a `Object.defineProperty()` call, wherein the property is *not* `configurable`.  

Wallaby runs the code the first time, then after I type, it fails:

```
Fri, 25 Sep 2015 07:08:45 GMT wallaby:workers Running tests in sandbox [worker #0, session #c2fme]
Runtime error: TypeError: Cannot redefine property: __Rewire__
    at Function.defineProperty (native)
    at Object.<anonymous> (./src/fs.js:180:12)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/boneskull/Library/Caches/PyCharm40/wallaby/projects/d7bf9f4c924d0815/instrumented/src/bindle.js:25:11)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/boneskull/Library/Caches/PyCharm40/wallaby/projects/d7bf9f4c924d0815/instrumented/test/bindle.spec.js:25:18)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

Will make an issue in [babel-plugin-rewire](/speedskater/babel-plugin-rewire) as well.

**Comment by ArtemGovorov** [comment]
Could you please share a sample or real project repo where I could reproduce the issue to have a look what can be done?

**Comment by boneskull** [comment]
I pushed some code [here](https://github.com/boneskull/hobo/tree/dev).  `.wallaby.js` is the config file

**Comment by ArtemGovorov** [comment]
What happens is `babel-plugin-rewire` generates additional code that creates those a few `__...__` properties on various objects depending on the context. Wallaby tries resets caches for user code when re-using node processes, however in this case the properties are set on node modules, such as `fs` (or `graceful-fs`) that we don't reset caches for. There're a couple of things that can be done (apart from adding the `configurable` flag in the `babel-plugin-rewire`).

First, I have noticed you're setting `recycle: true` in the root config object, but it's supposed to be set in the [`workers` property](http://wallabyjs.com/docs/config/workers.html). This way everything will work for you (but node processes will be re-created for each run).

If you'd like to keep re-using node processes (which is more performant), then as you have correctly pointed out the properties have to be configurable. The PR you've sent to the `babel-plugin-rewire` should fix the issue. Another solution that doesn't require the library modification would be to juts monkey-patch `Object.defineProperty` that `babel-plugin-rewire` is using to set the properties and make it add the `configurable` flag whenever it sets its properties:

```javascript
module.exports = function () {
   return {
     files: [
       ...
     ],

     tests: [
       ...
     ],

    bootstrap: function () {
      if (!Object._originalDefineProperty) {
        var propertiesToMakeConfigurable = Object.create({
          __Rewire__: 1,
          __set__: 1,
          __ResetDependency__: 1,
          __GetDependency__: 1,
          __get__: 1,
          __RewireAPI__: 1
        });
        Object._originalDefineProperty = Object.defineProperty;
        Object.defineProperty = function () {
          if (propertiesToMakeConfigurable[arguments[1]]) {
            arguments[2].configurable = true;
          }
          return Object._originalDefineProperty.apply(this, arguments);
        }
      }
    }
   };
 };
```

It should work without setting `workers.recycle` flag and allows to keep using once created node workers.

Another (non related to the topic) issue I have spotted is that when you are doing this: `'test/*.spec.js': file => fixture + file.content` without providing a source map for the transformation, wallaby will not be able to map error stacks correctly because of the line shift (without a corresponding source map). A better alternative would be to just require the fixture from the wallaby bootstrap function.

**Comment by boneskull** [comment]
Thanks for the help.

> A better alternative would be to just require the fixture from the wallaby bootstrap function.

I'm unsure how to do that when the fixture itself is written in ES6.

**Comment by ArtemGovorov** [comment]
Depending on the node version, it may be enough to pass [`--harmony` flag](http://wallabyjs.com/docs/config/runner.html#node-js) to the runner. 

If it's not an option, you may try just doing:
```
bootstrap: function (wallaby) {
  eval(require('babel').transform(require('fs').readFileSync(wallaby.localProjectDir + 'test/fixture.js')).code);
}
```
in your bootstrap function.

**Comment by ArtemGovorov** [comment]
Oh, actually, just including `test/fixture.js` to your `files` list should be enough. It'll be transformed by your babel preprocessor, you you may just `require('test/fixture.js')` in the bootstrap function.

**Comment by boneskull** [comment]
The PR was accepted into `babel-plugin-rewire`, so that solves that problem.  

The following worked:

```js
'use strict';

var babel = require('babel');

module.exports = function wallabyConfig() {
  return {
    files: [
      'test/fixture.js',
      'src/**/*.js',
      'package.json'
    ],
    tests: [
      'test/*.spec.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    preprocessors: {
      '**/*.js': file => babel.transform(file.content, {
        sourceMap: true,
        plugins: ['babel-plugin-rewire']
      })
    },
    testFramework: 'mocha',
    debug: true,
    bootstrap: function bootstrap(wallaby) {
      var path = require('path');
      require(path.join(wallaby.projectCacheDir, 'test', 'fixture'));
    }
  };
};
```

`wallaby.localProjectDir` is of course the project directory, and `test/fixture.js` there is in ES6.  However, in the cache dir, it's been preprocessed, so I use `wallaby.projectCacheDir` in `bootstrap()`.
