### ISSUE TITLE
Performance comments on awaited methods not showing

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2782]
`core v1.0.1135`/IntelliJ 2020.3

### Issue description or question
Performance comments not working on awaited/async methods (see below screenshot).
Is this intentional?
![image](https://user-images.githubusercontent.com/31244330/131118750-46880ae5-2a8d-4cf2-9c54-77cf9ffe42d6.png)

Thanks.

**Comment by smcenlly** [comment]
Wallaby version `1.0.1136` now supports performance comments on promises, which addresses your scenario.

**Comment by greenmooseSE** [comment]
I just upgraded to `core v1.0.1136` but it is still not working for me.  I tried isolating it in repo  [wallaby_example](https://github.com/greenmooseSE/wallaby_example/tree/try-wjAwaitPerfComment) with test [Bar.jest.test.ts](https://github.com/greenmooseSE/wallaby_example/blob/ab2a40de9186d7da527fd6f18916635740f0c453/test/Bar.jest.test.ts#L15-L18) however it seems to timeout occasionally and succeed occasionally. However the perf comment is not working nonetheless. 

![image](https://user-images.githubusercontent.com/31244330/131316967-2b70ddf3-b111-4eb0-85ad-a3b8d7c05556.png)

![image](https://user-images.githubusercontent.com/31244330/131317040-817c1235-881c-4cd8-a634-dee5b12964af.png)

```
wallaby.js started
core v1.0.1136
Runtime error: AssertionError: expected spy to have been called exactly once, but it was called 0 times
Finished executing 6 affected test(s) in 2.37 second(s)
Finished executing 4 affected test(s) in 2.05 second(s)
```

**Comment by smcenlly** [comment]
Thanks for the sample repo. It was a big help in understanding why you're having an issue.

Because you're using TypeScript and your `target` is set to `ES6`, at runtime your code is not actually using the `await` keyword. Instead, it's being transformed into a `yield` statement, which is why Wallaby's not working in this case.

**Original TypeScript code**
```typescript

describe("Bar jest tests", () => {
    async function sleep(ms: number): Promise<void> {
        await _sleep(ms);
    }

    function _sleep(ms: number): Promise<void> {
        return new Promise((resolve) => setTimeout(resolve, ms));
    }

    it("can run a test", () => {
        console.log('Foo');
    });

    it("can display perf for awaited method", async () => {
        await sleep(100); /*?.*/
        console.log('foo'); /*?.*/
    });
});
```

**Transformed code**
```javascript
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
describe("Bar jest tests", () => {
    function sleep(ms) {
        return __awaiter(this, void 0, void 0, function* () {
            yield _sleep(ms);
        });
    }
    function _sleep(ms) {
        return new Promise((resolve) => setTimeout(resolve, ms));
    }
    it("can run a test", () => {
        console.log('Foo');
    });
    it("can display perf for awaited method", () => __awaiter(void 0, void 0, void 0, function* () {
        yield sleep(100); /*?.*/
        console.log('foo'); /*?.*/
    }));
});
```

---

In fact, you will also see that Wallaby's live value display `//?` (without the performance indicator) also doesn't work in this case. `ES6` is actually pretty old (released in 2015) and so you may like to consider switching to a more recent version (`await supported from `ES2018`). If you don't want to target this for production, you may instead target just for running your tests.

In the meantime, we'll investigate whether there's anything we can do to support live comments and performance testing for `yield` scenario but off the top of my head I'm not sure if this will be possible.

**Comment by greenmooseSE** [comment]
Targeting `ES2018` is fine for this project, thanks!
