### ISSUE TITLE
SWC custom compiler

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#2810]
### Issue description or question

I want to compile my `ts` files with swc. Does Wallaby bundle one?

Do I need to write a custom compiler? In this case, what should `ranges` be?

I'm using something like the following:

```
function compile(filename, code, opts) {
  const defaultSourceMap = true
  //const defaultSourceMap = 'inline' // originally
  const finalOpts = {
    ...opts,
    sourceMaps: opts.sourceMaps === undefined ? defaultSourceMap : opts.sourceMaps,
  }
  const output: swc.Output = swc.transformSync(code, finalOpts)
  return {
    map: output.map,
    code: output.code,
    ranges: ranges,
  }
}

```

**Comment by ArtemGovorov** [comment]
If you are using Jest, then you don't need a custom swc compiler, the standard swc Jest transform should work. If you are not using Jest, you will need to create a custom compiler, because Wallaby doesn't bundle one for swc.

> In this case, what should ranges be?

`ranges` should be an array of the original source code coverable ranges (*any original code regions that you want to be displayed as either covered or not covered*), where each location is an array of the range `[start line, start column, end line, end column]`. I don't know if (like Typescript built-in compiler) swc provides a way to visit AST, but for Wallaby bundled Typescript compiler we collect the ranges from the AST provided by the built-in Typescript compiler.

Here's an example of ranges in a custom compiler: https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler.
