### ISSUE TITLE
Rerun tests upon modified 'dependency' ?

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#2844]
#### Scenario
I have a `src/swagger.yml` file. Then I have a test generating a REST api client from this file to `src/generated/apiClient` , and also copies `swagger.yml` to `src/generated/apiClient`.\
Then I have a test `apiClientIsUpToDate` verifying the 2 `swagger.yml` files are identical, if not it fails (so one does not forget to re-generate client when the yml-file change).

#### Question
Is there a trick/way/setup/config to rerun the `apiClientIsUpToDate` automatically whenever `src/swagger.yml` is modified?

Thanks.

**Comment by smcenlly** [comment]
I can think of a couple of ways that you might be able to do this, but it really depends on your testing framework. Can you please tell us what you're using?

If for example, you are using Jest, then you would want to first get this working outside of Wallaby. For example, you could create a custom jest transformer that transforms your `swagger.yml` file to something like:

```javascript
export default `swagger: "2.0"
...`
```

and then import it in your test... then Jest/Wallaby should track the changes and re-execute as you change the swagger file (I've not tested it, but it should work).

You could also do a similar thing if using `webpack`, or with a [Wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html). I think the important thing you need to do is covert the swagger file so that it is imported/tracked as a javascript dependency.

I think this answers your question so I'll close the issue, but feel free to reply if you have further questions or need clarification/assistance.

**Comment by greenmooseSE** [comment]
I got it working via `Jest --watch`, but cannot get it to work with wallabyJS, I can create a sample solution this/next week which hopefully reproduces it,

FWIW, what I did was:
Add a `jest-swagger-transformer.js`:
```js
"use strict";
module.exports = {
    process(fileContent) {
        return (
            "module.exports = " + JSON.stringify(fileContent) + ";"
        );
    },
};
```
In `jest.config.js` I added the `transform` and `moduleFileExtensions`:
```js
    transform: {
        '^.+\\.yml$': '<rootDir>/jest-swagger-transformer.js',
    },
    moduleFileExtensions: ["js", "json", "ts", "tsx", "jsx", "node", "yml"]
```
And then in test I used:
```js
const swaggerSrc = require('../../../src/swagger.yml')
const swaggerDst = require('../generated/apiClientTsAutoRest/swagger.yml');
    it("TypeScript api client is up to date", async () => {
        let swaggerSrcContent : any = swaggerSrc;
        let swaggerDstContent : any = swaggerDst;
        expect(swaggerSrcContent).toStrictEqual(swaggerDstContent);
    });
});
```

When I then modify the src-yml file `jest --watch` reruns the test (and fails/succeeds accordingly) but wallabyJS doesn't.

**Comment by smcenlly** [comment]
It seems to be working for us. We created a [sample repo](https://github.com/wallabyjs/wallaby-2844) where it is working. Could you please try our repo and confirm it's working for you also. Try changing the contents of `test.yml` after starting Wallaby and it should break; undo your changes and the test should pass again.

**Comment by greenmooseSE** [comment]
Thanks, yes that works fine for me as well. I'll update this issue if I find the culprit or have a sample repo ready.
