### ISSUE TITLE
Can't activate my license

### ISSUE THREAD

**Issue by gabrielnemeth** [wallabyjs/public#2852]
Hi,

I've tried to activate my wallabyjs license, but I can't because it has some trouble with node. I guess the problem is that I'm using nvm. After I click on the `Activate Licence` button I get an error: `Wallaby Notification: Error starting wallaby.js server, Cannot run program "node" (in directory "/home/gabriel/.wallaby"): error=2, No such file or directory`
But if I run `which node` I get a proper response.
```
❯ which node
/home/gabriel/.nvm/versions/node/v14.18.1/bin/node
```

I'm on pop_os! 20.04
IDE: Intellij 2021.2.3
Wallabyjs: 1.0.225
Node via nvm: 14.18.1

I couldn't copy the diagnostics report because that does not work either.

**Comment by smcenlly** [comment]
Could you please try and set your node.js path explicitly in your Wallaby run configuration?

![image](https://user-images.githubusercontent.com/2074089/142787252-fc53850e-d77a-4774-9cd5-a8cf8d6013d4.png)

**Comment by gabrielnemeth** [comment]
The only change is that now I'm able to run wallaby inside my project, but the license manager still couldn't fetch the data:

![license](https://user-images.githubusercontent.com/11211316/142906039-36e70a23-9d83-47c5-804d-f778006f3acb.png)

**Comment by smcenlly** [comment]
Could you please use your license key instead of your email address? It should work for you. If you have lost your license key, you can get your license key for your email address from: https://account.wallabyjs.com.

From the Event Log, something still doesn't seem right. Please let us know if it's working for you once you use the license key instead of email address.
