### ISSUE TITLE
Consider patching `.toString()` in instrumented functions to return original source

### ISSUE THREAD

**Issue by xanf** [wallabyjs/public#2854]
### Issue description or question
Let me just share a screenshot of one of my snapshots (it's vue component):

![Screenshot from 2021-11-26 16-52-05](https://user-images.githubusercontent.com/200997/143598572-e6cc3e4c-8c51-4b50-854d-5302a66ad1a2.png)

While I understand the root of this problem (function was instrumented by Wallaby) it would be great to make such snapshots consistent with "normal" jest

**Comment by ArtemGovorov** [comment]
Thanks for creating the issue. You are absolutely correct about the root of the problem.

An easy solution is to [exclude the function in question from the instrumentation](https://wallabyjs.com/docs/config/coverage.html#stopping-code-coverage-calculation-for-code-blocks-inside-a-file) with a `/* ignore coverage */` comment above the function declaration. 

> it would be great to make such snapshots consistent with "normal" jest

Without collecting code coverage Jest doesn't modify functions code, however Jest is using Babel/Instanbul code instrumentation by default for code coverage, and the code is modified too in that case. So I would expect it actually be resulting in a similar problem when running Jest with coverage on. Have you tried running your Jest CLI tests with `--coverage` flag to see if Jest CLI test run behaves in a similar way?

**Comment by xanf** [comment]
I believe we are using v8 coverage provider effectively avoiding this issue
:) But yes, if we're trying to run it with old ibstanbul one - same problem

сб, 27 нояб. 2021 г., 03:36 Artem Govorov ***@***.***>:

**Comment by ArtemGovorov** [comment]
In our experience v8 coverage was causing other issues (less accurate coverage in some cases). It's also still marked as "experimental" in [Jest docs](https://jestjs.io/docs/configuration#coverageprovider-string), with Istanbul being a default option at the moment. We may add support for it at some point too, for now I'd suggest the solution with `/* ignore coverage */` for functions with snapshot-ed bodies. Did you have a chance to try if it's working for you?

Side question: since you have been using v8 coverage provider, have you been generally happy with v8 coverage provider (stability, coverage accuracy, proper source mapping in case of TypeScript)?

**Comment by xanf** [comment]
Unfortunately, based on my experience it is still unpredictable - like 95% of time everything is ok, but sometimes unrelated code change may trigger coverage problems in other place :) Good news - this "problems" are at least stable (flaky builds is the last thing I would like to have). Unfortunately does not have much to tell about TypeScript - we're not using it in GitLab, so no hardcore everyday experience

**Comment by smcenlly** [comment]
Closing this issue as we do not intend to patch `toString()` on instrumented functions. There are technical limitations that currently prevent this from working in terms of how/where we instrument files. We also expect that outside of very small code files, this would degrade performance considerably in terms of both instrumenting/parsing files (with memory issues) and loading files during test execution.
