### ISSUE TITLE
Test fail hints are too verbose in some projects

### ISSUE THREAD

**Issue by caleblawrence** [wallabyjs/public#2857]
Test fail hints are too verbose (and goes off screen sometime): 
![image](https://user-images.githubusercontent.com/2174747/143939731-0b14c256-ba7b-4481-b83f-7d97581df191.png)

I expect it to just look like this:
![image](https://user-images.githubusercontent.com/2174747/143939797-e477e3fe-06e2-4ab9-b304-a4d392ec83fd.png)

In the tutorial project it works as expected but in my work project it does not and I have no idea what could be causing this so I thought I'd ask here and see if anyone might know?

I cannot figure out what is making it this verbose. This is my `package.json`: 
```json
  "devDependencies": {
    "@types/jest": "^27.0.3",
    "dotenv": "^8.0.0",
    "eslint": "^6.8.0",
    "jest": "^27.2.0",
    "prettier": "^1.19.1",
    "standard": "^12.0.1",
    "webpack": "^5.41.1"
  }
```

I'm not using any custom wallaby config.

**Comment by ArtemGovorov** [comment]
Thanks for raising the issue. The difference was in the Jest version (26 in tutorial vs 27 in your project). We have updated our Jest integration to address the scenario correctly. The fix is published in [the latest Wallaby Core v1.0.1181](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
