### ISSUE TITLE
Error when running WallabyJS on Angular 12 project with Jest & auto config

### ISSUE THREAD

**Issue by pbrianmackey** [wallabyjs/public#2884]
This project was upgraded recently from Angular 8 to 12.  I also just migrated from Karma/Jasmine to Jest.  This is a fairly large project with about 1,000 tests.

Jest v27.4.5
‍​[Info]​ Started Wallaby.js Core v1.0.1196  (Just ran the update wallaby.js Force Core Update cmd in VS Code.)
Ran:  Wallaby.js: Reset Wallaby Cache

```
​​[Error] Runtime error: ReferenceError: window is not defined​​
​​[Error]     at WebSocket.emit (events.js:400:28)​​
​​[Error]     at afterWrite (internal/streams/writable.js:466:5)​​
​​[Error]     at onwrite (internal/streams/writable.js:446:7)​​
​​[Error]     at InflateRaw.afterTransform (internal/streams/transform.js:103:3)​​
​​[Error]     at Zlib.processCallback (zlib.js:607:8)​​
```

jest.config.js

```
require('jest-preset-angular/ngcc-jest-processor');

module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  watchPathIgnorePatterns: ['<rootDir>/src/environments/environment.test.ts'],
  testPathIgnorePatterns: ['<rootDir>/src/environments/environment.test.ts'],
};
```

Already ran `.\node_modules\.bin\jest --clearCache`

`.\node_modules\.bin\jest` runs just fine.  

`npx jest` errors out:

```
ngcc-jest-processor: running ngcc
Determining test suites to run...

Test Suites: 0 of 112 total
Tests:       0 total
Snapshots:   0 total
Time:        0 s, estimated 69 s
vents.js:377
      throw er; // Unhandled 'error' event
      ^

Error: write UNKNOWN
    at afterWriteDispatched (internal/stream_base_commons.js:156:25)
    at writeGeneric (internal/stream_base_commons.js:147:3)
    at WriteStream.Socket._writeGeneric (net.js:798:11)
    at WriteStream.Socket._write (net.js:810:8)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at WriteStream.Writable.write (internal/streams/writable.js:303:10)
    at DefaultReporter.__clearStatus (C:\Git\DW\UI\node_modules\@jest\reporters\build\DefaultReporter.js:157:14)
    at Status._callback (C:\Git\DW\UI\node_modules\@jest\reporters\build\DefaultReporter.js:95:12)
    at Status._emit (C:\Git\DW\UI\node_modules\@jest\reporters\build\Status.js:251:30)
    at Timeout._onTimeout (C:\Git\DW\UI\node_modules\@jest\reporters\build\Status.js:260:14)
Emitted 'error' event on WriteStream instance at:
    at WriteStream.onerror (internal/streams/readable.js:750:14)
    at WriteStream.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processTimers (internal/timers.js:497:9) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'write'
}
```

**Comment by smcenlly** [comment]
>  I also just migrated from Karma/Jasmine to Jest.

I'm not sure about what your tests are doing, but if you are migrating existing tests (you mentioned ~1000 tests) from Karma to Jest, I would expect to run into some problems. Karma runs your tests using the browser, while Jest uses node (and can emulate a browser-like environment with JSDOM).

I would suggest staring with a fresh Angular 12 project, and then configure Jest there first before trying to then migrate/update your tests to work with Jest.

> npx jest errors out:

We're not sure what would be causing this error and it is unrelated to Wallaby. Perhaps the team from [`jest-preset-angular`](https://github.com/thymikee/jest-preset-angular) will be able to help you? 

Once you have `npx jest` working from the command line, Wallaby should work for you also.

**Comment by pbrianmackey** [comment]
I just want to be sure that you noticed that .\node_modules\.bin\jest runs just fine.  I see you closed the question because of npx.  I'm not really sure how npx plays into this and somehow means that this can be closed as non-wallaby related. 

As I mentioned I can run the standard jest command just fine.  All the tests PASS

**Comment by pbrianmackey** [comment]
Update:  Actually `npx jest` works fine now in Powershell and bash.  There was something wrong w/ my project that I resolved.  But Wallaby still fails exactly the same way.

**Comment by smcenlly** [comment]
I just want to be sure that you noticed that .\node_modules\.bin\jest runs just fine. I see you closed the question because of npx. I'm not really sure how npx plays into this and somehow means that this can be closed as non-wallaby related.

> `npx jest` should be using your project's local version of Jest to run your tests. If not, it will install its own version and use that.

Can you please share your Wallaby diagnostics report? From our issue template:

Wallaby Diagnostics Report is a simple JSON text report that contains some basic information
about your Wallaby config and project that is required to start troubleshooting most of Wallaby issues.

To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

--

If the diagnostics report is not generating, can you please share your Wallaby Console output as well as your `package.json`?
