### ISSUE TITLE
spyOnProperty Jasmine error when spying on a function

### ISSUE THREAD

**Issue by alaingmail** [wallabyjs/public#2911]
### Issue description or question

I'm using VS Code for an Angular 10 project on Windows 10.
All Jasmine tests run without errors via ng Test.

Running the same tests via Wallaby and VSCode I get errors like (**Error: <spyOnProperty> : selectList is not declared configurable**) when using **spyOnProperty** to mock the output of an imported function e.g. 

```
import * as selectors from './selectors'; -> contains external functions e.g. selectList

spyOnProperty(selectors, 'selectList').and.returnValue(
  () => 'list'
);
```

**Comment by smcenlly** [comment]
We need a bit more detail in order to reproduce your problem.

We created a new Angular 10 project and `SpyOnProperty` appears to be working for us. I expect that there's some code related to your `selectors` class that may be causing the problem.

Can you please try the example below and let us know if it works for you in your existing project?

**spy.spec.ts**
```typescript
class Person {
  private firstName: string;
  private lastName: string;

  constructor(firstName, lastName) {
    this.firstName = firstName;
    this.lastName = lastName;
  }

  get fullName() {
    return `${this.firstName} ${this.lastName}`;
  }
}

describe('SpyOnProperty Tests', () => {
  it('should work', () => {
    const person = new Person('John', 'Doe');
    expect(person.fullName).toBe('John Doe');
    const spy = spyOnProperty(person, 'fullName').and.returnValue(
      'dummy stubbed name'
    );
    expect(person.fullName).toBe('dummy stubbed name');
  });
});
```

If our example works, and your code still does not, can you please create a minimal reproducible sample as we have done above so that we can see all of the code related to `spyOnProperty` not working?

Could you also please provide your Wallaby Diagnostics report. To share the report:

- start Wallaby in your project;
- wait until it reports some results (finishes running tests);
- run `Copy Diagnostics Report` command:
  - in VS Code, Atom, or Sublime editor execute Wallaby `Copy Diagnostics Report` command from your editor command palette; 
  - in JetBrains IDEs or VS use Wallaby `Help | Wallaby.js | Copy Diagnostics Report` menu item;
- paste generated report from your clipboard below (feel free to review and edit the report if required).

**Comment by smcenlly** [comment]
I also found some others [on StackOverflow](https://stackoverflow.com/questions/58852549/error-spyonproperty-function-is-not-declared-configurable) who had the same problem:

> I have experienced the same problem when I tried to upgrade project from Angular 8 to 9, there is no answer that I could find on Google, however I figured out a way how to solve it in my project.
> 
> In tsconfig.json, change target to es5.
>

**Comment by smcenlly** [comment]
Closing this issue as we haven't heard back. I'm assuming that StackOverflow (or something else) helped you identify and fix the problem. If not, please reply and let us know and we will re-open the issue. Please also don't forget to provide us with a working sample that has the same problem.
