### ISSUE TITLE
Does not work with JEST + YARN workspaces + Typescript

### ISSUE THREAD

**Issue by BrandonALittle** [wallabyjs/public#2927]
### Issue description or question
I am trying to use WallabyJS in a monorepo that has two packages, under a `/packages` folder. The structure looks like:
```
/packages
    /api-1
    /api-2
```

There is a `tsconfig.json` and a `jest.config.ts` in each package folder.

I am not using a wallaby config file (how is it supposed to be named anyway??...your docs don't say as far as I can tell).

My root level `.yarnrc.yml` contains the recommended block of code:
```
packageExtensions:
  jest-config@*:
    dependencies:
      ts-node: "*"
      jest-runtime: "*"
```

Now when I try to start WallabyJS, I receive output errors related to Typescript, like:
```
'Const declarations' require an initialization value. (19:19) 
 
  17 | const userLevel = 1 
  18 | 
> 19 | const gamePlayInput: GQLGamePlayInput = { 
     |                    ^ 
```

### Wallaby diagnostics report

I would rather not paste this here.

**Comment by ArtemGovorov** [comment]
There are a multiple options to run Wallaby: you may run it for an individual package folder or for all packages from the repo's root. If you are using VS Code, you may run `Wallaby.js Select Configuration` command to select what tests to run.

If you are running Wallaby fo the root of your repo (default option), then what Wallaby is trying to run Jest for your repo's root (just like `yarn run jest` would do). So if `yarn run jest` works when ran from your repo's root, then Wallaby should work too. Can you please check if `yarn run jest` works for you? if it doesn't, you may need to create Jest config in your repo's root, so that Jest CLI (and Wallaby) work when running from the repo's root. You may need to use the [`projects` Jest setting](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig).

If you don't need/want to run all of your tests at once, you may run `Wallaby.js Select Configuration` command and select a specific package folder with tests that you want to run.

> I am not using a wallaby config file (how is it supposed to be named anyway??...your docs don't say as far as I can tell).

You shouldn't need a config file in your case, but if you will need it in future, you may name it as it's [recommended in our docs](https://wallabyjs.com/docs/intro/config.html#configuration-file).

If the options suggested above don't address your issue, please also attach your Wallaby Diagnostics report. The steps to generate the report may be found in [the new issue template](https://github.com/wallabyjs/public/issues/new).

**Comment by BrandonALittle** [comment]
Thank you for the info. 

No, `yarn run jest` does not work. It fails on the same typescript syntax as shown above.

I tried adding a root Jest config with a projects setting. Didn't work.

Choosing a specific folder for Wallaby's configuration also did not work.

My Jest tests run fine with a jest.config that is shared (but is not at the root) between workspaces. I can run each workspace's test suites without issue, and without typescript or module-resolution related errors.

I will consider sending the diagnostics output, but I didn't expect so much trouble from software I purchased myself.

**Comment by smcenlly** [comment]
In most cases, Wallaby will run `jest` tests without any special configuration or setup if `npx jest` / `yarn run jest` works from your project root.

It sounds like your project may be a little different from most and so we'll need a little bit of additional information to help you.

Is your project open source (or somehow available) so we can see the structure? Or did you create it using a publicly available CLI tool? If not, the diagnostics report that we requested may help.

**Comment by tharrison4815** [comment]
I've used this with a lerna monorepo (with yarn) and I found the best solution was to right click on the folder for the package that I wanted to run tests for and to click `Wallaby.js: Configure and Start`.

**Comment by smcenlly** [comment]
Closing this issue as no further action appears to be required.
