### ISSUE TITLE
Open source license and mono repo

### ISSUE THREAD

**Issue by dvilchez** [wallabyjs/public#2939]
### Open source license down't work with mono repo

I am working on this project https://github.com/Xuaps/tesla. It is a mono repo with two project on it, a typescript project "app" and a Python project "functions". None of the possible configuration for wallaby's works. Closest project fails because it is unable to find the information about the GitHub project and project directory because jest is not installed. I have tried to install jest globally but it doesn't work either.

**Comment by ArtemGovorov** [comment]
Unfortunately our OSS license doesn't support scenarios where tests can't run from the repo's root. If you can make Jest CLI run your your repo's root, then Wallaby will work too. Alternatively you may consider purchasing a personal license and run Wallaby on your `app` project without any restrictions.

**Comment by jacob-8** [comment]
> Unfortunately our OSS license doesn't support scenarios where tests can't run from the repo's root.

@ArtemGovorov so what you're saying is that a repo like https://github.com/jacob-8/kitbook doesn't qualify as an open source project simply because I've set up a couple packages? Wallaby is failing to recognize my project as open source.

**Comment by ArtemGovorov** [comment]
@jacob-8 No, it's not what I was saying. Wallaby doesn't verify the status of your project based on its nested packages. What I was saying is that Wallaby OSS license only supports running from the root of a valid repo (and not when an individual package is opened as a project because it is not a valid OSS repo root). So if you can run your tests from within the root of repo, then Wallaby should be able to do it too. 

If you are running tests from the repo's root and it doesn't work for you, we are happy to investigate. Please email us hello@wallabyjs.com a zipped archive of your current `~/.wallaby` and `~/.quokka` folder contents (please exclude any nested directories, we only need files in the root of those folders); it should be a very small zip file.

If you would like to open individual packages as projects in your editor and run tests in that opened project, you may consider our commercial license that should support these scenarios.

**Comment by jacob-8** [comment]
I run my tests from the root of the monorepo using `pnpm --filter site test` which fires off the `test` script command in my  `packages/site` package.json, and this folder includes my `vitest.config.js` file. So I'm guessing that even though I run the command from root, this doesn't actually count as running tests from root because it's running a script defined in a different `package.json`?

It will would helpful for Wallaby to post an example of how to use it in a monorepo. I've never seen a monorepo where tests for sub packages were run from the root package.json file except in the pnpm filtering method just described.

**Comment by smcenlly** [comment]
> I run my tests from the root of the monorepo using `pnpm --filter site test` which fires off the `test` script command in my  `packages/site` package.json, and this folder includes my `vitest.config.js` file. So I'm guessing that even though I run the command from root, this doesn't actually count as running tests from root because it's running a script defined in a different `package.json`?

Correct, the command is effectively setting `cwd` to your `site` project and running the `test` script from there.

> It will would helpful for Wallaby to post an example of how to use it in a monorepo. I've never seen a monorepo where tests for sub packages were run from the root package.json file except in the pnpm filtering method just described, which is truly running from root.

It is quite common for mono-repo projects to be set up to run all tests from the root (or to easily allow it). For example, if you are using jest, you can configure jest in your mono-repo root to run all projects with the [`projects`](https://jestjs.io/docs/configuration#projects-arraystring--projectconfig) setting.

Unfortunately, vitest does not include mono-repo support ([see issue here](https://github.com/vitest-dev/vitest/issues/256)) so that may cause things to not work in your case. If you configure `vitest` to run from your repo root (i.e. add dependencies, add test script, and configuration) then Wallaby will work in your case with the OSS license.

**Comment by jacob-8** [comment]
> vitest does not include mono-repo support

Thanks for the helpful information! I will watch that issue.
