### ISSUE TITLE
Debugger: Stepping into third party code (node_modules)

### ISSUE THREAD

**Issue by bgoscinski** [wallabyjs/public#2965]
I'm using WallabyJS in VSCode. My Project is built with Vue3, TS and Jest 27.

My test is throwing error somewhere in third party code (library installed through npm). I was trying to debug it using WallabyJS's debugger:

1. I hit "Debug" code lens above the throwing test
2. I use step over/run to active line to proceed to the line that is calling to the third party code
3. I hit "Step Into"
4. Instead of stepping into the third party code the line is marked in red (as failing). Stepping into any of the calls to my own code works flawlessly

![stepinto](https://user-images.githubusercontent.com/5730169/161818490-643b9b49-a2ac-48d7-87eb-b28b75e3a5a6.gif)

Is there a way to step into third party code?

Right now the workaround I'm using is to run the same test directly in jest and attach VSCode debugger to it. While it works it's far from ideal because it's breaking my flow, it forces me to stop wallaby (because my debugger keyboard shortcuts are configured to work differently depending on if wallaby is on or off) and start wallaby all over again after the debugging session. It's painful :)

**Comment by smcenlly** [comment]
> Is there a way to step into third party code?

By default, Wallaby does not allow you to step into 3rd party code. This is by design and is also partly a technical limitation.

In order to provide a debugger experience for your test/source files, Wallaby must analyse them and add some special instructions to those files before executing them (effectively modifying them in a way that doesn't change the runtime behaviour). Doing this on all node modules would slow down your test startup times (and in many cases in not necessary).

In order to use Wallaby's debugger on your 3rd party code, you will need to ensure that the code in transformed and included in your code coverage calculations in your jest configuration. I assume it's a node-module, in which case you would probably need to change your `testpathIgnorePatterns` and `transformIgnorePatterns` settings. This [stackoverflow post](https://stackoverflow.com/questions/58086182/jest-ignore-all-node-modules-except-1-package) may help. Once you do this, you should be able to step into your 3rd party module.
