### ISSUE TITLE
Wallaby exhausting db connections (Prisma)

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#2980]
The typical way to connect a Prisma client is with a module level variable:

```
export const prisma = new PrismaClient()
```

As wallaby does a lot of module reloading, this often leads to "too many clients already" errors.

I've tried a bunch of things to have this happen only once, but can't figure it out. Any advice?

Thanks

**Comment by smcenlly** [comment]
For external resources (e.g. database) that need to be set up and torn down after your tests, there are a few things that you need to be aware of when using Wallaby.

The first thing to be aware of is that by default Wallaby runs your tests in multiple processes. If you have a singleton database connect (e.g. database is configured to be hosted on a specific port) then you will either need to constrain Wallaby to run in a single process, or else set up your database connection once when Wallaby starts and then re-use it for each process running tests. You can change this behaviour with Wallaby's `workers.initial` and `workers.regular` settings.

Wallaby also reuses node worker processes between test executions. In contrast, when you run your tests from the CLI, a new process is created for each test execution. This means that you may rely (inadvertently) on a new process being created for each test run. You can change this behavior with Wallaby's `workers.restart` setting.

You can read more about the workers settings [here](https://wallabyjs.com/docs/config/workers.html).

**Wallaby.js configuration file to limit concurrency and create new processes for each test run**:
```javascript
module.exports = () => ({
  workers: {
    initial: 1,
    regular: 1,
    restart: true,
  }
});
```

Ideally you would not limit concurrency or restart processes between test runs because it will make running your tests slower. Wallaby allows you define [setup](https://wallabyjs.com/docs/config/bootstrap.html#setup-function) and [teardown](https://wallabyjs.com/docs/config/bootstrap.html#teardown-function) functions to perform some setup/teardown after your tests run. You could initialise your database in these functions (i.e. database instance on a specific port for each worker process).

**_Important Note:_** Wallaby (and other testing frameworks) don't necessarily guarantee that teardown functions will execute. If you need to rely on something being cleaned up correctly between test runs, we recommend checking/cleaning up in your setup function, which is guaranteed to run before every test run.

---

I understand that's a lot of information and there's a bit to get your head around. If it's easier for you to provide us with a sample project that uses Prisma the same way that you're using it in your project, we'd be happy to create the configuration for you.

**Comment by tslocke** [comment]
Thanks very much for the detailed reply.

I've changed the code that initialised Prisma from:

```ts
export const prisma = new PrismaClient()
```

To
```ts
export let prisma: PrismaClient

export function connect() {
  prisma = new PrismaClient()
}
```

And added a simple setup function like this.

```ts
const {connect} = require('./src/database')

module.exports = function () {
  return {

    setup: function (wallaby) {
      connect()
    }
  };
};
```

But it seems like `connect` is not getting called. I tried adding a console.log to setup and checking for it in the Wallaby console. I didn't see the output but maybe console output from setup is not supported anyway.

Another quick question: what would be the best way to ensure `connect` gets called both for Wallaby runs and CLI runs?

**Comment by smcenlly** [comment]
We've created a sample repo for you that shows how you can create the instance in your setup function and pass it to your tests ([see here](https://github.com/wallabyjs/wallaby-2980)).

Based off your configuration file, I have assumed that you're using `jest`. Because of how jest works (isolating your dependencies between tests, etc.), you will need to pass the client via `globalThis`.

Also, the setup function is executed in the context of the test runner, not in the context of the configuration file. This means that you cannot use objects/variables defined within the configuration file code as you did with `const {connect} = require('./src/database')`.

I think our example should be enough for you to understand how to structure your configuration but if not, let us know.

Also, if the code is not running, please be sure to configure Wallaby to [use a configuration file](https://wallabyjs.com/docs/intro/config.html#configuration-file) instead of automatic configuration. If you don't do this then nothing will run for you.
