### ISSUE TITLE
Nx hybrid frameworks libs : karma and Jest, create configuration to run jest specs

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#2992]
### Issue description or question

We are currently looking into migrating all our karma libs to Jest. 
but by the time we migrate everything, we'll end up with a Hybrid version, with some tests still with Karma, and others with Jest. 

In the documentation : https://wallabyjs.com/docs/integration/nrwl.html#karma-or-hybrid-test-frameworks

You explain that wallaby is not able to manage several test runners at the same time. And you suggest to create a configuration for each test runner. 

The automatic configuration, works to run all karma tests. 
But I try to configure another WallabyJs command to run Jest tests. 
I followed your docs, to configure with Jest : https://wallabyjs.com/docs/integration/jest.html

So I configured my intellij with this: 
![image](https://user-images.githubusercontent.com/1046806/169028767-26e84edb-4bbb-4813-93be-85842802680c.png)

And this file: 
```js
module.exports = () => {
  return {
    testFramework: {
      // the jest configuration file path
      // (relative to project root)
      configFile: './src/jest.config.js',
    },
  };
};

```

but it doesn't run the Jest tests, it still runs the Karma tests. 

What do I have to do to run the Jests with Wallabyjs.

**Comment by manudss** [comment]
# Wallaby diagnostics report
[wallaby.reports.json.txt](https://github.com/wallabyjs/public/files/8715872/wallaby.reports.json.txt)

**Comment by smcenlly** [comment]
The reason that you're having the issue is that Wallaby first tries to detect and configure using your Angular configuration before it tries to configure using Jest. In your case, because you have the karma tests configured in your Angular configuration, Wallaby is running karma.

We have extended Wallaby to allow you to define which types of automatic configuration is supported. Please update to the latest version of Wallaby core, `v1.0.1270` and update your configuration as shown below, it should work for you:

**wallaby.js configuration**
```javascript
module.exports = ({
  autoDetect: ['jest','angular'],
  testFramework: {
    configFile: './src/jest.config.js',
  },
});
```

**Comment by manudss** [comment]
Hello,
Thanks for the correction. I just tested it, it works well. It's great, thanks.
Maybe, you should update your documentation, on the Hybrid Framework part of nx and on the jest page.

- https://wallabyjs.com/docs/integration/nrwl.html#karma-or-hybrid-test-frameworks
- https://wallabyjs.com/docs/integration/jest.html

Regards,
