### ISSUE TITLE
[Question] recommended practices to trigger test based on native modules rebuild?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#3003]
### Wallaby diagnostics report

Hi, this is a question regarding the behavior of wallay. I may not know if there's an existing way to achieve this.

I'm working on some codebases in transpiler, swc (https://github.com/swc-project/swc) or its plugins. There are some fixture snapshot test cases run on javascript (jest) to confirm its transformation behavior. Usual workflow to verify changed code is

- run native build (`cargo build`)
- run jest separately
- check transformed output passes fixture snapshot

since first / second is isolated, when I try to run snapshot test via wallaby running native build doesn't retrigger test, nor update loaded module to use newer compiled binary unless stop & restart test, which is not much different to manually re run test.

I presume this is probably bit tricky as wallaby need to know 1. if there are external changes to existing module in memory 2. try to reload those modules - but also curious if there's some workaround to achieve this? It'll potentially boost workflow a lot for some cases.

Thanks.

**Comment by smcenlly** [comment]
Is it only the native modules that are changing when you run `cargo build`? If you were to also change the JavaScript files that call into them (e.g. update checksum / timestamp, etc. - even if only in `dev` mode) then I can see how you might be able to get Wallaby to work with your workflow. Wallaby looks at your JavaScript imports to determine which tests use which modules and how/when to reload them. If these are linked in `node_modules` there may be a little more that you need to do to get Wallaby working (e.g. update your jest configuration to transform these imports).

I think you would also need to use Wallaby's [workers.restart setting](https://wallabyjs.com/docs/config/workers.html) to make Wallaby always recycle the test runner process so that it reloads the native module.

Do you have a simple sample that you can reference or describe how we can run? We are happy to take a look for you and see if we can work out a way to provide you with your desired workflow.

**Comment by kwonoj** [comment]
>  If you were to also change the JavaScript files that call into them (e.g. update checksum / timestamp, etc. - even if only in dev mode)

I tried this, but doesn't seem to retrigger invalidating existing native modules loaded.

> I think you would also need to use Wallaby's [workers.restart setting](https://wallabyjs.com/docs/config/workers.html) to make Wallaby always recycle the test runner process so that it reloads the native module.

Probably this explains, as node.js module cannot be invalidated once loaded?

> Do you have a simple sample that you can reference or describe how we can run?

I have a private repo work in progress, hope to make it as public soon. Will try to share once it's ready to peek.

**Comment by smcenlly** [comment]
> Probably this explains, as node.js module cannot be invalidated once loaded?

I'm not sure how too invalidate native modules (or if you can), but yes, the workers setting should take care of this for you. It will slow things down a little but depending on your project/tests, you may not notice.

**Comment by smcenlly** [comment]
I'm going to close this issue for now. If/when you have a sample to share and need some help, either reply here and we will re-open the issue or else raise a new issue and we can take it from there.

**Comment by kwonoj** [comment]
Cool, will do. Thanks!
