### ISSUE TITLE
Cannot set properties of undefined (setting '0')

### ISSUE THREAD

**Issue by kevinbeal** [wallabyjs/public#3013]
### Issue description or question

I am getting this error with increasing frequency. Usually it appears after I've removed the `.only` that focuses a test, but just now it happened after clearing my jest cache and restarting Wallaby. 

I'm sorry I don't know what else to say about it. 

### Wallaby diagnostics report

[wallaby-report.txt](https://github.com/wallabyjs/public/files/8943245/wallaby-report.txt)

**Comment by kevinbeal** [comment]
This is the same issue I was experiencing on this issue: https://github.com/wallabyjs/public/issues/1086

**Comment by smcenlly** [comment]
When Wallaby runs your code, it add some additional instructions to collect code coverage, etc. When you get this error it means that there's misalignment between Jest's cache and the version of your file that Wallaby thinks its running. It's entirely possible that there's a Wallaby problem but Wallaby's integration with Jest's cache is fairly simple (is just a wrapper over the top of what Jest does). We believe that the issue may lie in your dependencies and would like to rule that out.

I've taken a look through `ts-jest` changes since the version being used by your project `27.0.5` and there are definitely some changes/fixes around file caching. Is it possible for you to update your dependencies (e.g. `nrwl`, `jest`, `ts-jest`, etc.) to see if that fixes your problem?

Another interesting item to note that I discovered today is that `ts-jest` is [moving to `esbuild/swc` as their default compiler](https://kulshekhar.github.io/ts-jest/docs/getting-started/presets#the-presets) and the TypeScript compiler will be their legacy option.

> Starting from v28.0.0, ts-jest will gradually opt in adoption of `esbuild/swc` more to improve the performance.

We ourselves have been using `jest` with `swc` for a while now on some of our internal projects and it runs well. You may like to try this for your project (if you can). You can also read [our blog post](https://wallabyjs.com/blog/optimizing-typescript.html) comparing the performance. I haven't done this myself but I believe you can configure `nrwl` to use `swc` instead of TypeScript ([see here](https://nx.dev/packages/js/executors/swc)).

---

If upgrading dependencies or trying `swc` isn't an option, can you please send us your `package-lock.json` or `yarn.lock` file so that we can see exactly what version of dependencies you are using? We will then be able to try and reproduce your issue using the same versions of your dependencies.

**Comment by kevinbeal** [comment]
Confirmed that ditching `ts-jest` resolves my issue. Or at least, the usual reproduction steps don't reproduce it. Thanks a lot @smcenlly !

For anyone coming across this, I had `babel-jest` on all of my react libs/apps and the `cannot set properties` error never originated from those locations. The issue was always with `ts-jest`. Getting `babel-jest` to work on the express apps and other libs which weren't React required some configuration I wasn't able to get working, but using SWC per @smcenlly 's suggestion worked well.

For react apps, I have `jest.config.js` files that look like this:

```javascript
module.exports = {
    displayName: "testlib",
    preset: "../../jest.preset.js",
    transform: {
        "^.+\\.[tj]sx?$": [
            "@swc/jest",
            { jsc: { transform: { react: { runtime: "automatic" } } } }
        ]
    },
    moduleFileExtensions: ["ts", "tsx", "js", "jsx"],
    coverageDirectory: "../../coverage/libs/testlib"
};
```

For other apps/libs, I did the same but without the swc options, like:

```javascript
module.exports = {
    displayName: "testlib",
    preset: "../../jest.preset.js",
    transform: {
        "^.+\\.[tj]s$": "@swc/jest" // <- here
    },
    moduleFileExtensions: ["ts", "js"],
    coverageDirectory: "../../coverage/libs/testlib"
};
```
