### ISSUE TITLE
Avoiding multiple module instances (vitest)

### ISSUE THREAD

**Issue by tslocke** [wallabyjs/public#3032]
This is quite possibly a vitest issue, and not a Wallaby issue.

My project uses ProseMirror, which has an issue when multiple instances of one of the modules (`prosemirror-state`) are loaded.

Since switching from jest to vitest, I'm getting test fails because of this. I found a fairly simple workaround so this is not crucial, but  I'm wondering if there is any way to avoid the module getting loaded multiple times.

Note this is an intermittent issue with vitest itself - I sometimes get the same error on the command line, but only on the first run. If I press `a` to re-run the tests, they consistently pass.

With Wallaby, they consistently fail.

Is there any way to prevent a certain module from being reloaded?

Thanks

**Comment by tslocke** [comment]
Update: this is possibly a vitest issue:

https://github.com/vitest-dev/vitest/discussions/1637

**Comment by smcenlly** [comment]
We'd have to see how/why your tests are failing in order to try work out a solution. Given that it's also a problem with `vitest`, I think if you fix `vitest` so it runs on the first run, then Wallaby should start working also.


Did you try playing around with `vitest` globalSetup? It may help you initialize what you need before your tests run (https://vitest.dev/config/#globalsetup).

**Comment by smcenlly** [comment]
I'm not sure there's much we can do to solve this for you. I'm going to close the issue out. If you get it working on startup in vitest and Wallaby still isn't working for you, please let us know and we can re-open.
