### ISSUE TITLE
ReferenceError: jest is not defined with Angular 14.1.2

### ISSUE THREAD

**Issue by glyxerin3** [wallabyjs/public#3050]
When running tests with wallaby and jest with automatic configuration in Angular using jest.spyOn function is getting a ReferenceError: jest is not defined for this line.

The same configuration when running jest from command line without wallaby with jest --watchAll is running without errors.

### Steps to reproduce

**1. Create new Angular project**

`ng new justTesting`

**2. Install jest and librarys**

```
npm i -D @testing-library/angular @testing-library/user-event @testing-library/jest-dom
npm i -D jest @types/jest jest-preset-angular
```

**3. create ./setup-jest.ts**

with following content

`import 'jest-preset-angular/setup-jest';`

**4. create ./jest.config.js**

with following content

```
module.exports = {
  preset: 'jest-preset-angular',
  setupFilesAfterEnv: ['<rootDir>/setup-jest.ts'],
  globalSetup: 'jest-preset-angular/global-setup',
  testPathIgnorePatterns: [
    '<rootDir>/src/test.ts'
  ]
};
```

**5. create ./tsconfig.spec.json**

with following content

```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "module": "CommonJs",
    "types": [
      "jest"
    ]
  },
  "files": [
    "src/test.ts",
    "src/polyfills.ts"
  ],
  "include": [
    "src/**/*.spec.ts",
    "src/**/*.d.ts"
  ]
}
```

**6. Create minimum test sample ./src/app/app.component.spec.ts**

with following content

```
describe('jest testing', () => {

  it('', () => {
    const spy = jest.spyOn(window, 'fetch');
    expect(true).toBeTruthy();
  });

});
```

**7. Run wallaby**

Output:
```
wallaby.js started
core v1.0.1301
- Generating browser application bundles (phase: setup)...
Wallaby App (realtime reports) is available at: http://localhost:51245
Finished executing 4 affected test(s) in 420 millisecond(s)

1 failing test, 3 passing  Launch Coverage/Test Explorer

src/app/app.component.jest.spec.ts jest testing  [1 ms]

	ReferenceError: jest is not defined
		at t.<anonymous> src/app/app.component.spec.ts:4:5
```

**Comment by ArtemGovorov** [comment]
Thanks for providing the steps to reproduce the issue. 

By default, Wallaby detects that you are using Angular CLI project, so it tries to run your test just like your `ng test` command would do. And if you run `ng test` command in the sample project, it will result in the exact same error, because Jasmine/Karma will run and not Jest.

You may either 
- [install `@angular-builders/jest` fix your `angular.json` file](https://stackoverflow.com/questions/50786359/can-i-run-jest-through-the-angular-cli) so that `ng test` runs Jest. In this case Wallaby automatic configuration will just work.
- if you don't want `ng test` to work, you may make Wallaby run Jest directly (just like `npx jest` would do) in your project. In order to do it, add the following code to your `package.json`:
```diff
...
+  "wallaby": {
+    "autoDetect": [
+      "jest"
+    ]
+  }
```

**Comment by glyxerin3** [comment]
It worked, thanks very much! :)
