### ISSUE TITLE
Files are not loaded from CDN

### ISSUE THREAD

**Issue by anderdb** [wallabyjs/public#306]
I have a test suite that is currently set up for Karma that I'm trying to get running under wallaby.js.  In Karma, I can reference a file on a CDN by adding the URL to the files array in karma.conf.js.  In wallaby.js, if I add a file by URL, it seems to be completely ignored.  Tests that reference anything from these files fail due to the missing dependencies.  I see no other errors related to this and nothing about these files in the debug output.  If I download these dependencies and add the local file to the files array, everything is great.  

Am I doing something wrong or does wallaby.js not currently support this?

Thanks!

**Comment by ArtemGovorov** [comment]
You're not doing anything wrong, wallaby.js does not currently support it. Please have a look to https://github.com/wallabyjs/public/issues/281 for a workaround. You may either create a file that downloads a file or files from CDN like described in the referenced issues or just download dependencies locally for tests. I do recommend downloading and reference files locally, because in wallaby your tests will run much more frequently than karma. So (even considering caching) it's just more performant to have them locally.

**Comment by anderdb** [comment]
Thanks for the quick response.  I'd honestly rather have these dependencies be local anyway so this is just more reason to do so.
