### ISSUE TITLE
Error in wallabyjs How to ignore some files not usefull for Wallabyjs ? 

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#3067]
Error in wallabyjs with some files that I do not wants to be used by tests runner (files specific for Cypress) how to ignore them ? 

### Issue description or question

Hello, How I can ignore files in Wallabyjs tests. We migrated to Angular 14. and since then, Wallaby has problems. With files that are dedicated to e2e tests with Cypress. So that Wallabyjs should not to manage this file, but it has an error: 
```shell
libs/wam/util/e2e/src/lib/functions/app.function.ts:1:50 - error TS2315: Type 'Chainable' is not generic.

1 export const setApplyConfig = (enable: boolean): Cypress.Chainable<JQuery<HTMLBodyElement>> =>
```

I am with the automatic configuration on Angular. I tried to ignore the files in the package.json in this way, but it does not work. 

```json
"wallaby": {
    "autoDetect": true,
    "files": [
      "!src/libs/wam/util/e2e/*",
      "!libs/wam/util/e2e/src/lib/functions/app.function.ts",
      "!src/apps/idaas-portal-e2e/*",
      "!src/apps/wam-portal-e2e/*",
      "!src/apps/iga-portal-e2e/*"
    ]
  }
```

Thanks in advance,

### Wallaby diagnostics report

See here : https://gist.github.com/manudss/e9a1735989867a59d8665df21362a434
Too long for Github.

**Comment by smcenlly** [comment]
Your configuration shows that you're using `autoDetect` and you're override the `files` section of your configuration, but not the `tests` section (where the tests to run are configured). Please set the `tests` configuration section and it should work for you. It should look something like:

```javascript
"wallaby": {
    "autoDetect": true,
    "files": [
      "!src/libs/wam/util/e2e/*",
      "!libs/wam/util/e2e/src/lib/functions/app.function.ts",
      "!src/apps/idaas-portal-e2e/*",
      "!src/apps/wam-portal-e2e/*",
      "!src/apps/iga-portal-e2e/*"
    ],
    "tests": [
      "**/*.spec.ts",
      "!src/apps/idaas-portal-e2e/*",
      "!src/apps/wam-portal-e2e/*",
      "!src/apps/iga-portal-e2e/*"
    ]
  }
```

**Comment by manudss** [comment]
Thanks for the answer. But it doesn't really work in my case. No more tests are found by WallabyJS. So it doesn't work anymore. 
What I would like is the automatic configuration, works as before. Detects well, the right code, and what is useful to run. But being able to ignore some files that Wallaby was trying to run (when it shouldn't!). 
So, I would like to just ignore some files, which are under some directories. And let Wallaby do the rest. 

Is this the right way? If not, I didn't quite understand how it works.

**Comment by smcenlly** [comment]
> What I would like is the automatic configuration, works as before. Detects well, the right code, and what is useful to run. But being able to ignore some files that Wallaby was trying to run (when it shouldn't!).

Ideally automatic configuration should just work for you without overriding either `files` and `tests`. I had assumed that since you're overriding `files` you'd be happy to override `tests` also.

If you can provide us with your project (or a representative sample) that has the same problem, we'd be happy to identify why automatic configuration is not working for you. It may well be a Wallaby defect but in most cases, it is a problem with your project configuration itself, and we have seen a number of similar problems not running tests correctly after Angular upgrades not working properly.

Do you get the same problem on a freshly created Angular 14 project? If not, you may try and compare your project configuration with the new project and identfiy/fix the differences.

> So, I would like to just ignore some files, which are under some directories. And let Wallaby do the rest.

If you don't want to set `tests` explicitly, and instead would like to append some patterns, then you can instead override automatic configuration (described in [our docs](https://wallabyjs.com/docs/config/files.html#overriding-automatic-configuration)). Example below:

```javascript
module.exports = () => ({
  files: {
      override: (patterns) => {
          return [...patterns, "!apps/web/**/*"];
      }
  },
  tests: {
      override: (patterns) => {
          return [...patterns, "!apps/web/**/*"];
      }
  },
});
```
