### ISSUE TITLE
Wallaby App on WSL2 not working

### ISSUE THREAD

**Issue by Noriller** [wallabyjs/public#3073]
### Issue description or question

I'm trying to open the wallaby app in a project in wsl2.

I've tried using the "http://wallabyjs.com/app/#/tests?server=wsl2ip"  or the "http://wsl2ip:port/#/tests", tried also "http://wsl2ip:port/#/test?server=wsl2ip"

but all of them try the websocket as localhost instead of the wsl ip.

---
Wallaby version: v1.0.347 - offline install
Wsl2:
- Distributor ID: Ubuntu
- Description:    Ubuntu 18.04.6 LTS
- Release:        18.04
- Codename:       bionic

**Comment by smcenlly** [comment]
If you're running multiple Wallaby projects at the same time and they are not all on WSL then it's possible that you have a problem because some of your network connections are local to the Windows machine and some are local to the WSL instance and the correct network path cannot be resolved.

---

We are assuming that you are using VS Code, is that correct?

We have tested the latest version of Wallaby on with VS Code on WSL and it appears to be working for us. Can you please try the following:

1. Restart your Windows Machine (to reset the network stack, etc.)
2. Start a single instance of VS Code, remoted in to your WSL instance / project.
3. Start Wallaby
4. Click on the `​Launch Coverage & Test Explorer` link in the `Wallaby.js Tests` Output window to open Wallaby App

<img width="776" alt="image" src="https://user-images.githubusercontent.com/2074089/190021506-891b8591-7910-4208-a172-fc5ae4de557f.png">

5. At this point you should see Wallaby App
6. If you see a `Reset Server` option on the bottom right of Wallaby App, please click the `Reset Server` link:

<img width="888" alt="image" src="https://user-images.githubusercontent.com/2074089/190021784-490a337d-fe90-4169-9302-4867d7d638a1.png">

7. If you needed to click `Reset Server`, close the browser tab, and launch it again using the `Launch Coverage & Test Explorer` link. If your WSL instance is correctly configured, Wallaby should now work for you.

---

If Wallaby is still not working, please create a new project on your WSL instance that uses `express` to launch a simple web server (note: you will need to initialize a new `package.json` and install `express`):

**index.js (simple web server)**
```javascript
const express = require('express');
const app = express();
const port = 3000;

app.get('/', (req, res) => {
  res.send('Hello World!')
});

app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
});
```

After you have created this file/project, start it with `node index.js` and you should see:

```
Example app listening on port 3000
```

Then on your Windows desktop, open a browser tab: `http://localhost:3000`. You should see:

<img width="544" alt="image" src="https://user-images.githubusercontent.com/2074089/190022333-e79d4a2f-19c4-46df-a97b-1afe4b9eb815.png">

If this doesn't work for you, then you will need to troubleshoot your WSL instance and get this working before Wallaby will work for you. You may try temporarily disabling your Windows Firewall to see if that's the cause of your problem, and if so, work out the correct permissions. Once you fix this, Wallaby App should also work for you.

If `express` is working for you, but Wallaby still is not, please let us know.

**Comment by Noriller** [comment]
Today I started it... all normal...

乁| ･ 〰 ･ |ㄏ

thank you
