### ISSUE TITLE
Error : window is not defined

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#3086]
### Issue description or question

Hi, 

I have this error when trying to run wallaby on my project. 
" window is not defined" 

But I have no information, where this error is :

```
Runtime error: ReferenceError: window is not defined
    at WebSocket.emit (node:events:526:28)
    at afterWrite (node:internal/streams/writable:497:5)
    at onwrite (node:internal/streams/writable:477:7)
    at Zlib.cb (node:internal/streams/transform:202:7)
    at Zlib.processCallback (node:zlib:612:8)

```
I don't know if this error come from my code ? or from wallabyjs ? 

Any Idea about the cause ? 

Many thanks. 

### Wallaby diagnostics report

[Diagnostic report](https://gist.github.com/manudss/806e7fe1c3b63c4b53e11d947991b999)

**Comment by smcenlly** [comment]
Thanks for your diagnostics report.

Your diagnostics report shows that Wallaby is failing to parse your Angular configuration and is then defaulting to use `jest` as the testing framework which is not running in the browser, which is why you have the error.

The specific error being reported is:

```
2022-09-30T13:30:59.734Z angular/cli config Error: ENOENT: no such file or directory, open
'C:\dev\idaas_front_end\src\libs\wam\feature\application\delete\shared\src\test.ts'
```

I'm guessing that perhaps `src\libs\wam\feature\application\delete\shared\src\test.ts` is referenced from your angular configuration somewhere (e.g. `angular.json`) but no longer exists? Could you please check and see if you can fix this?

If you continue to have errors (could be another similar problem), please also inspect the diagnostics report as it may help you determine what else needs fixing.
