### ISSUE TITLE
Configure/fix code frame deemed responsible for failing tests

### ISSUE THREAD

**Issue by Gregoor** [wallabyjs/public#3090]
Hey folks,

This is probably more of a Jest, than a Wallaby question but I'm not entirely sure so I thought I'd risk posing it here as well. I'm looking to simplify my project's testing API where I am aiming for something like this:
```ts
testThing((t) => {
  t(33);
  t(44);
  t(42);
})
```
Now I don't know how to get Jest & Wallaby to show the correct code frames for failed expect's. This is my current stab at an implementation:
```ts
const testThing = (callback: any) => {
  callback((n: any) => {
    test(n.toString(), () => {
      expect(n).toBe(42);
    });
  });
};
```

Which results in the `testThing` definition to be shown for every failed test case (I'd instead want L12 & L13 to be shown in red):

<img width="463" alt="image" src="https://user-images.githubusercontent.com/4051932/195164502-9ac6ffe2-6e3a-4cf1-ac2e-4d15e068d7b6.png">

Here's a replit if you want to see it in action: https://replit.com/@grgr/jest-frame-issue#thing.test.js

**Comment by smcenlly** [comment]
We don't really have a solution we can share to help you with what you want to do.

To get decent test/error reporting you really have to work within the testing framework, which you're not really doing in your example. Having said that, I understand what you're trying to do would lead to a much simpler code base and we have wanted to do similar things in our codebase in the past. We end up compromising how we structure our tests to fit within testing frameworks we use.

Your example is a little contrived so we can't really offer any concrete advice on how to suggest structuring your tests but if you have a concrete example you can provide, we'd be happy to review and if it's not too much effort we could suggest what we would do.

Some of the approaches we take include introducing mocks or proxies to isolate expected / received values so we can evaluate them in the context of a well defined `test` entry point. We also sometimes may have a single test that has a number of expectations for all cases (e.g. `33`, `44`, `42`); when we do this, failures may only impact a single test, but at least we have. better error handling (e.g. can see failing at line `13` instead of line `6`). Hope that makes sense and perhaps helps.

**Comment by Gregoor** [comment]
Thankslots for sharing your nuanced thoughts on this! I am glad to hear that I am not the only one who struggles with making his testing framework fit the problem at hand. It feels to me like a testing library with the "right" primitives has yet to be invented.

My concrete example is not too far from the provided code, but it tests different code transformations. So in terms of minimal API for passing in actual/expected, it'd look like this:
```ts
testAction(["moveNode", "RIGHT"], (t) => {
  t("[1, 2];", 1, "[2, 1];");
});
```

Where the minimal version that actually works wrt showing the failed expecations on the correct line would look more like this (where the `t` function would not call `it` anymore):
```ts
testAction(["moveNode", "RIGHT"], (t) => {
  it("does a transform", () => {
    t("[1, 2];", 1, "[2, 1];");
  });
});
```

Since that forces me to also name all test cases, even though they are self-descriptive, and since I have like ~300 tests already, with the intention of growing them quickly, I am keen to move closer to the minimal solution.

So yeah, maybe there is not much I can do here, and I'll just continue biting the bullet of not visually seeing which test case actually failed.

**Comment by smcenlly** [comment]
I'm still not sure exactly what your `testAction` code is doing...

I would suggest perhaps ending up with a structure like:

```javascript
it("does a transform", () => {
    expect(testAction('moveNode')).toBe(true);
    expect(testAction('RIGHT')).toBe(true);
});
```

And your testAction can return true/false based on the expected outcome (or if you want, the exact value that you're expecting). Maybe still a little more verbose than you want, but now if a specific test case fails, you'll go straight to it...

Not sure what else we can offer so I'm closing this issue. Hope it helps.
