### ISSUE TITLE
Wallaby incompatible with vitest 0.25.8 #3130

### ISSUE THREAD

**Issue by bad4iz** [wallabyjs/public#3131]
why did you close my issue?  I have the latest version . I have provided you with screenshots.
https://github.com/wallabyjs/public/issues/3130

my wallaby.js v1.0.256
my upgrade license expired on December 10th.

- vitest doesn't work I
- can't run on vscode
- I can't copy Diagnostics Report

**Comment by bad4iz** [comment]
![image](https://user-images.githubusercontent.com/16918043/208360588-741f8f7f-cbf7-4c54-be8c-7fb8981a32fd.png)
were there fixes in these versions?

**Comment by bad4iz** [comment]
now I tried it under the os license . the project you provided is from here https://github.com/wallabyjs/public/issues/3130#issuecomment-1356954605. wallaby version 1.0.256. the error is the same.
```
Failed to initialize wallaby vitest.
Could not find vitest utils.
Error: Could not find vitest utils.
```

**Comment by ArtemGovorov** [comment]
> why did you close my issue? I have the latest version . I have provided you with screenshots.

Wallaby consists of 2 parts, [plugin and core](https://wallabyjs.com/docs/intro/how-it-works.html#plugin-and-core). Plugin is evergreen (everyone one has access to the latest version). Wallaby Core is versioned separately and from the log you have [shared here](https://github.com/wallabyjs/public/issues/3130#issuecomment-1357125413):

> core v1.0.1355

you are not using the latest version of the core. This is because your license upgrades period has expired recently and v1.0.1355 is the latest version that you may use with the license.

> vitest doesn't work I

The latest Vitest version support was added after v1.0.1356+ of the core. This is why it's not working for you.

> can't run on vscode

The screenshot you have provided is simply a warning that you are using an outdated version of Wallaby core (because of the expired license). You may suppress the notification in Wallaby extension settings for VS Code. Please note that the latest version of Vitest will still not work for you because of the reasons described above.

If you have any more questions, please let us know. We are happy to answer even in the closed issue.

**Comment by bad4iz** [comment]
Yes , that 's right . The os license has no expiration date (yet). why isn't it working?

**Comment by ArtemGovorov** [comment]
> The os license has no expiration date (yet). why isn't it working?

It's possible that after switching to the OSS license, your Wallaby core component has not been updated yet (happens automatically at some point). Please check your Wallaby Output channel in VS Code (or Wallaby Console in JB IDEs) for the Wallaby Core version that it prints there when you start the project.

**Comment by bad4iz** [comment]
thank you for coming up with so much detail. and for such quick answers. You are the best.
