### ISSUE TITLE
Wallaby is not running the code coverage testing consistently

### ISSUE THREAD

**Issue by KoichaDev** [wallabyjs/public#3132]
Hello supporter,

I am a paid user! I am having an issue with the Wallaby not running properly on `Run File test` or `Smart Start`. What happens is that as soon as I try to change something some code lines on the unit test, then the wallaby.js + Quokka.js is not running the code coverage constantly as it used to. 

I am not sure if it's because I am running on the latest update from the Visual Studio Code I am using, or if something is wrong with your extension if you guys have updated something new.

Can you please take a look at this issue?

Thank you for your help

**Comment by smcenlly** [comment]
Could you please create a configuration file in your project root to run Wallaby. You configuration file should look like this:

**wallaby.js**
```javascript
module.exports = () => ({
   autoDetect: true,
   debug: true,
   trace: true,
});
```

After creating the file, you will need to run the VS Code command, `Wallaby.js: Select Configuration` and then select the configuration file (instead of using automatic configuration).

After doing that, please start Wallaby:
1. Using `Wallaby.js: Start` to run all tests in your project, and then make a change with coverage updating correctly.
2. Using `Wallaby.js: Smart Start` and then make a change with coverage not updating correctly.

In both cases, after performing the action, please capture the `Wallaby Console` output window content and provide that to us.

Please also provide your `package.json` file so that we can see your `dependencies` and `devDependencies`.

**Comment by KoichaDev** [comment]
hello again! 

For some odd reason, everything seems to work fine from my part. I don't know what happened.

**Comment by smcenlly** [comment]
I'll close the issue for now. If you have problems again, please reply to this issue or else open a new issue and provide teh details requested above.
