### ISSUE TITLE
Wallaby stops running

### ISSUE THREAD

**Issue by mwehlou** [wallabyjs/public#315]
Using Wallaby trial 1.0.44 and Web Storm 10.0.4, I'm experiencing a lot of halts where I have to restart Wallaby to make it show anything. One easily reproducible stall is as I'm showing in the included screen capture. I also included the toy project. (I'm a beginner at Javascript, so I wouldn't exclude some horrible mistake, but the stalls shouldn't be happening, IMHO.)
Since Github doesn't let me upload neither the project ZIP nor the MP4 movie, please pick them up here:

https://db.tt/VDPxjByF

**Comment by ArtemGovorov** [comment]
Hi Martin,

Thanks for the sample project, it's helpful.
The issue is in your wallaby config - `tests` list [should only contain tests](http://wallabyjs.com/docs/config/files.html#properties), in your case it also includes the test test help and loading it as test causes all of the issues that you are observing. If you move it to the `files` list, everything should be ok:

``` JavaScript
module.exports = function () {
    return {
        files: [
            '*.js',
            'bin/*.js',
            'routes/*.js',
            'views/*.js',
            'test/helpers/*.js'
        ],
        tests: [
            'test/*Spec.js'
        ],
        env: {
            type: 'node',
            params: {
                runner: '--harmony --harmony_arrow_functions'
            }
        }
    };
};
```

Please let me know if it helps.

**Comment by mwehlou** [comment]
Artem,

Yes, that was the problem. Seems obvious in hindsight. Thx!
