### ISSUE TITLE
Cannot setup Wallaby with custom Webpack config

### ISSUE THREAD

**Issue by letehaha** [wallabyjs/public#3169]
### Issue description

This issue is a continuation of my question in [another thread](https://github.com/wallabyjs/public/issues/2900#issuecomment-1436122591).

I'm using a postprocessor to use a custom `webpack` config, and when I'm passing `testFramework.configFile` I'm getting: 

`​​[Error] Failed to load configuration file: TypeError: Cannot read properties of undefined (reading 'indexOf')​​`.

I'm using `jest: 27.0.6`, and `webpack: 5.75.0`.

Outside of Wallaby, my test run looks like this:

```
node compiler/index.js --env test --web
&& node ../node_modules/jest/bin/jest.js
--config ./test/unit/jest.config.js
```

Compiler takes all the files from the `./client/src` and `./client/test/unit` and stores the compilation result in the `./client/test/unit/.compiled` folder, which is then specified as `rootDir` in `jest.config.js`.

```
/** @type {import('jest').Config} */
const config = {
	verbose: true,
	rootDir: './.compiled',
	testEnvironment: 'jsdom',
}

module.exports = config
```

With Wallaby I'm trying to do the same – take the `webpack` config to compile files and use the custom jest config to run over compiled files.

To provide a reproduction repository I'll need to make a lot of movements, so would be nice if it will be possible to resolve the problem without a reproduction repo. If not, then will try to create one.

### Wallaby diagnostics report

There's no report (VS Code), since as I understand Wallaby cannot even start because of the wrong configuration. 

That's my Wallaby config:

```
const webpackConfig = require('./compiler/web')[0]

module.exports = function (wallaby) {
	return {
		// set `load: false` to all source files and tests processed by webpack
		// (except external files),
		// as they should not be loaded in browser,
		// their wrapped versions will be loaded instead
		files: [
			{ pattern: 'client/src/**/*.+(js|vue)', load: false },
		],
		tests: [
			{ pattern: 'client/test/unit/**/*.spec.js', load: false },
		],
		testFramework: {
			configFile: './client/test/unit/jest.config.js',
		},
		postprocessor: wallaby.postprocessors.webpack(webpackConfig),
	}
}
```

**Comment by smcenlly** [comment]
When you run your `jest` tests with Wallaby (in fact any testing framework), Wallaby needs to run on the original source files in order to correctly instrument your files for test coverage, stack trace (and more). Unfortunately transformed files source maps, etc. is not sufficient for Wallaby to function correctly due to some of the advanced features / functions that Wallaby provides.

What this means is that your current configuration (where you have split compilation vs. test) is not supported.

In order to use Wallaby to run your tests, you will need to ensure that `npx jest` works from the command-line on your source files (not  `./.compiled` files).

Without seeing your project, it's difficult to understand whether this is even possible, or the level of effort involved in creating a jest configuration to perform the appropriate transformations, etc. to run your source files directly with `jest`. Having said that, most people are running `jest` directly on the source files, and you'll definitely notice some benfits (such as faster test execution times).

If you're able to provide a project, we'd be happy to take a quick look and see if we can help you with your jest configuration (or at least point you in the right direction).

**Comment by letehaha** [comment]
Thanks @smcenlly, I probably missed that very important detail ! Will try to setup everything up in a common way soon and drop a note here.

**Comment by smcenlly** [comment]
I'm going to close this issue for now. If you have problems after getting `jest` working from the CLI with `npx jest` (and running on source files) either reply here and we'll re-open the issue, or else create a new issue.

**Comment by letehaha** [comment]
Thanks, @smcenlly that works. Hope it will be possible to add Webpack config to Jest, so the bundle compilation result will be synced with the "real", non-test-env one, but that's another story :)
