### ISSUE TITLE
can't test the string value of a function

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#317]
```js
expect(String(func)).to.equal('');
```

```js
	expected '() => {\n        $_$wf(5);\n    }' to equal ''
```

perhaps the `.toString()` of instrumented functions should be patched to return the value of the original function's `String` value?

**Comment by boneskull** [comment]
fwiw other coverage tools (istanbul) seem to account for this.  my real use case is:

```js
const _ = {
  noop: () => {
  }
}

describe('noop()', () => {
  it('should do absolutely nothing', () => {
    expect(String(_.noop).replace(/\s+/g, '')).to.equal('()=>{}');
  });
});
```

since asserting something actually does nothing isn't feasible, the next best thing would be asserting the function is empty.

**Comment by ArtemGovorov** [comment]
Yeah, it's a known limitation of code coverage/code instrumentation based tools, the executed code is not the same so any code reflection based assertions may fail. Overriding `.toString()` will make the code instrumentation (much) slower. 

> asserting something actually does nothing

In case of using code coverage tools, the function technically does something - it reports its code coverage. So no matter what tools do to hide the fact - essentially it's just fooling tests. And if such a test can be easily fooled by overriding `.toString()`, which can make any function look like its doing nothing, then what's the point? 

If you want to test it, then perhaps creating a separate (test) file excluded from runs code coverage/instrumentation could work. Another possible thing to do is removing code coverage instructions as well as spaces in your test or having some conditional logic to avoid executing test if running with code coverage - but it'll make the test to contain instrumenter specific strings/regexp/logic.

I have tried running istanbul
```
 istanbul cover test.js
```
on `test.js`
``` JavaScript
var f = function () {
};
require('assert').ok(String(f).replace(/\s+/g, '') === 'function(){}');
```
and it fails because String(f) is `function (){__cov_I0JmBovyUsngkLVDCQHL$A.f['1']++;}`.

I have been trying to find some settings that I am perhaps missing to make it work, but only found https://github.com/gotwarlost/istanbul/issues/209 and https://github.com/gotwarlost/istanbul/issues/310 issues indicating that instanbul seems to work the same way as wallaby does.

Do you have a working sample with instanbul that I could have a look into to see how it handles the case?

**Comment by boneskull** [comment]
@ArtemGovorov yes.  [digs-common](/digsjs/digs-common)

**Comment by boneskull** [comment]
see `test/utils.spec.js`

**Comment by boneskull** [comment]
(requires nodejs >=4.x)

**Comment by boneskull** [comment]
when running `grunt test --verbose`, you can see the command it executes.  something like:

```shell
$ node node_modules/istanbul/lib/cli.js cover -x node_modules/** --dir=coverage --report=lcov --report=text-summary node_modules/mocha/bin/_mocha -- --require test/fixture test/definitions/**/*.spec.js  test/**/*.spec.js
```

**Comment by ArtemGovorov** [comment]
Thanks. It looks like for whatever reason istanbul doesn't instrument empty arrow functions.
If you change it to use normal function expression:
```JavaScript
    noop: function(){
    },
```
your test will be failing. Not sure why is it not consistent, perhaps one of the scenarios is a bug of instanbul - not sure which one. BTW if you add something to the function, even:

```JavaScript
    noop: () => {
    '';
    },
```
instanbul will also insert instrumentation instructions, so it doesn't solve the general issue of providing an original string value of a function. Just has that one specific behaviour of non instrumenting an empty arrow functions.

Unfortunately, I can't do the same in wallaby. The reason is that unlike instanbul and other coverage tools that only collect coverage, wallaby also tracks dependencies between files, based on the instrumented code. So for example, when you declare an empty function and some tests are already calling it, later on when you start adding code the function, because the function is instrumented, wallaby is able to only run those tests that invoke the function and not all of your tests.

Based your idea, as a pretty unobtrusive workaround, I may suggest adding this line to your `.wallaby.js` bootstrap function:
``` JavaScript
    bootstrap: function bootstrap(wallaby) {
      require('./lib/utils').noop.toString = () => '()=>{}';
      var path = require('path');
      require(path.join(wallaby.localProjectDir, 'test', 'fixture'));
    }
```

**Comment by boneskull** [comment]
good idea, thanks.

**Comment by fritx** [comment]
https://github.com/gotwarlost/istanbul/issues/310#issuecomment-189893653

My solution:

```js
fnstr = fnstr.replace(/__cov_(.+?)\+\+;/g, '')
```
