### ISSUE TITLE
Debug buttons are missing in new WebStorm UI

### ISSUE THREAD

**Issue by Philipp3211** [wallabyjs/public#3172]
While having the [new UI](https://www.jetbrains.com/help/webstorm/new-ui.html) activated in WebStorm, the debug buttons are missing:
![image](https://user-images.githubusercontent.com/93536358/221181052-8ab8eb09-2906-4959-9148-afb3c0fa40e3.png)

When having the old UI activated, the buttons are shown:
![image](https://user-images.githubusercontent.com/93536358/221181673-61acc19b-5d43-46aa-a92a-d63ce03a5026.png)

You are still able to break inside a test via the context menu, but without these buttons you are for instance unable to leave the debugger while having stopped at a breakpoint.

**Comment by smcenlly** [comment]
Thanks for reporting. We are aware of the issue and working towards a fix. We don't have an ETA right now but expect to address within the next few weeks. In the meantime, you can use the [keyboard shortcuts](https://wallabyjs.com/docs/intro/time-travel-debugger.html?editor=jb#debug-actions) or else revert to using the non-beta UI.

**Comment by smcenlly** [comment]
Please update to the latest plugin of Wallaby for IntelliJ editors (`v1.0.263`). When using the new UI, the debug icons will now appear within the `Debugger` tab. You will need to navigat to the `Debugger` tab in order to see them.

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/2074089/228694538-9ac2d1f7-2b20-49ee-bd10-3ae08a7929a5.png">
