### ISSUE TITLE
Breaking change in the latest version of Chrome

### ISSUE THREAD

**Issue by joldseyhsi** [wallabyjs/public#3183]
### Issue description or question
Regression in wallaby after updating to chrome v. 110.0.5481.178

‌[Error] Test run failure: Sandbox load failed, status: failed: Using unsafe HTTP verb GET to invoke /json/new. This action supports only PUT verb.

**Comment by smcenlly** [comment]
Thanks for reporting the problem. This was not a regression in Wallaby, but instead a breaking change in the latest version of Chrome for the chrome remote debugger communication protocol.

This has been fixed in the latest version of Wallaby, `v1.0.1394`. Please update to the latest version, it will fix your problem.

**Comment by Philipp3211** [comment]
For those running on an older Wallaby version, you can switch your browser in your `wallaby.ts` as a workaround:
```
module.exports = () => ({
    autoDetect: true,
    env: {
        kind: 'electron'
    }
});
```

**Comment by massimocode** [comment]
This version of Chromium works fine for me: https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win_x64/1058982/ Of course that's the Windows 64-bit build, added to the config as follows:

```
    env: {
      kind: "chrome",
      runner: "C:\\Users\\BlahBlah\\chrome-108\\chrome.exe"
    },
```
