### ISSUE TITLE
ES6 + React + Webpack + JSDom setup help

### ISSUE THREAD

**Issue by chrisblossom** [wallabyjs/public#320]
(Following tutorial http://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html)

I am trying to get ES6 + React + Webpack + JSDom working without success. My code is located:

https://github.com/chrisblossom/voting-client

Please advise what I am doing wrong.

Failing Tests:
```
TypeError: Cannot read property 'cache' of undefined
	at test/components/voting_spec.jsx:1

Error: Cannot find module '../../src/components/voting'
	at test/components/voting_spec.jsx:1
```
Wallaby Console:
```
wallaby.js started
core v1.0.142
Runtime error: TypeError: Cannot read property 'cache' of undefined
    at Object.<anonymous> (./test/components/voting_spec.jsx.wbp.js:1:85)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Array.forEach (native)
Runtime error: Error: Cannot find module '../../src/components/voting'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (./test/components/voting_spec.jsx:7:41)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
```

**Comment by ArtemGovorov** [comment]
Wallaby.js doesn't support Webpack for node.js environment, only for browser environment. I mean it may or may not work, but I have never tested the scenario, so the first `Cannot read property 'cache' of undefined` error may be something related.

Anyway, don't see the point of using webpack at all for your node.js tests running by wallaby (of course you still use it for production builds, just no reason to use it for running tests with wallaby). 

Node.js is perfectly capable of `require`-ing stuff; the environment is already simulated (using node with jsdom as opposed to browser/phantom) - so why use an additional compilation step that gives nothing except slowing down tests and making the setup more complicated? IMHO faster your tests run and simpler the environment for running them - better.

Below is a config that works (I just removed webpack stuff and added `require.extensions['.jsx'] = require.extensions['.js'];` to your bootstrap function to address the issue of `require`-ing jsx files).

```JavaScript
const babel = require('babel-core');
const fs = require('fs');

const babelConfig = (() => {
  const file = __dirname + '/.babelrc';

  try {
    fs.accessSync(file, fs.R_OK);
  } catch (error) {
    return {babel};
  }

  try {
    const config = JSON.parse(fs.readFileSync(file));
    config.babel = babel;
    return config;
  } catch (error) {
    throw error;
  }
})();

module.exports = wallaby => {
  return {
    files: [
      'src/**/*.js*',
      'test/test_helper.js'
    ],

    tests: [
      'test/components/*spec.jsx'
    ],

    compilers: {
      '**/*.js*': wallaby.compilers.babel(babelConfig),
    },

    env: {
      type: 'node',
      runner: 'node'
    },

    testFramework: 'mocha',

    bootstrap: function bootstrap() {
      require.extensions['.jsx'] = require.extensions['.js'];
      require('./test/test_helper.js');
    }
  };
};
```

If you are not happy about the solution and would strongly prefer to use webpack with node.js in wallaby, please let me know and I'll have a look into what it'll take to add the support for it in node.js environment.

**Comment by chrisblossom** [comment]
@ArtemGovorov Thank you for the quick reply (again)! I wasn't using webpack for any particular reason other than I thought I had to.

Everything seems to be working great now except when the test called 'does update DOM when prop changes'  inside file https://github.com/chrisblossom/voting-client/blob/master/test/components/voting_spec.jsx breaks/changes the test seems to fail until Wallaby is restarted. I am guessing it is a react / immutable issue and not a problem with Wallaby, but just wanted to verify.

**Comment by ArtemGovorov** [comment]
It looks like the issues with state. Wallaby.js by default tries to re-use node workers and if some library caches some state, things may be broken during subsequent runs.

There are 2 way to fix it.

First, is to configure wallaby to re-create node workers for each run. This way it's going to act as usual runner - run tests, destroy node process, create node process for the next run, etc. While it'll be more isolated, this will obviously be as slow as the normal test runner (slower than the default wallaby mode when node processes are re-used). Well, maybe not as slow as a normal runner, because wallaby will still be able to run test in parallel and leverage its ability to only run those tests that were affected, but still.
```
module.exports = wallaby => {
  return {
    ...
    bootstrap: function bootstrap() {
      ...
    },

    workers: {recycle: true}
  };
};
```

The second solution is to find a way to reset whatever caches the state. Adding this to the bootstrap function:
```JavaScript
    bootstrap: function bootstrap() {
      Object.keys(require.cache)
        .filter(function (k) {
          return ~k.indexOf('node_modules/fbjs') || ~k.indexOf('node_modules/react');
        })
        .forEach(function (k) {
          delete require.cache[k];
        });
      require.extensions['.jsx'] = require.extensions['.js'];
      require('./test/test_helper.js');
    },
```
removes `fbjs` and all modules starting with `react` from node cache and it seems to help and make it work (if it doesn't try returning `true` from the filter function to see if removing all node modules helps, and then try adding some restrictions). Perhaps there's a better way to just reset those node modules state via their API, but I'm not an expert in using those modules.
