### ISSUE TITLE
Global Setup and Teardown is not complete, waiting for 5000ms before recycling worker (Angular v15)

### ISSUE THREAD

**Issue by azaeng04** [wallabyjs/public#3234]
### Issue description or question

I got Angular v15 running with Jest, but when running it with Wallaby the Global Setup and Teardown environment does not recycle and then it tries to recycle it again and never ends. Goes into a loop.

https://github.com/wallabyjs/public/assets/13921692/1f8dd0a6-473a-4bf6-9d70-6a54e3a79f22

### Wallaby diagnostics report

Diagnostic report was too long had to attach a text file

[wallaby-log.txt](https://github.com/wallabyjs/public/files/11832467/wallaby-log.txt)

**Comment by smcenlly** [comment]
When you have a `globalSetup` or `globalTeardown` defined defined, Wallaby will try and gracefully finish their execution when you make file changes and a test run is in progress. 

The message that you're seeing is an expected diagnostic message that Wallaby reports when your global setup is still running and another test run has been scheduled.

In your case, it looks like the message is being aggressively displayed because of a misconfiguration of your project.

Your **wallaby.js** configuration file (from your diagnostic report):
```javascript
process.env.TS_JEST_LOG = 'ts-jest.log';

module.exports = (wallaby) =>
({
    autoDetect: true,
    testFramework: {
        configFile: './jest.config.ts'
    },
})
```

Shows that you are outputting the `ts-jest` log in your project root. Every time this file changes, Wallaby is detecting the file change and attempting to cancel and restart your test run, which is leading to the excessive logs in your Wallaby Console output.

If you are going to output the `ts-jest` log, you should exclude it from either your `jest` configuration, or your Wallaby configuration. For example:

```javascript
process.env.TS_JEST_LOG = 'ts-jest.log';

module.exports = (wallaby) => ({
  autoDetect: true,
  testFramework: {
    configFile: './jest.config.ts',
  },
  files: {
    override: (filePatterns) => {
      filePatterns.push('ts-jest.log')
      return filePatterns;
    },
  },
});
```

I believe this will solve your problem. If you're still having issues, please let us know.
