### ISSUE TITLE
Feature request: Show minimal info

### ISSUE THREAD

**Issue by damms005** [wallabyjs/public#3237]
In the Value Explorer, just too much is shown. Too much info to the extent that the real value is sandwiched in between too much!

See screenshot below how difficult it is to locate "100" -- which, for opening the Value Explorer, is exactly what I am looking for.

![image](https://github.com/wallabyjs/public/assets/9839355/8128193a-2251-42a9-873d-f3ce08f01e77)

Suggestion: extension settings option to simply display the minimum. e.g.:

> line 63: 100

**Comment by ArtemGovorov** [comment]
@damms005 Thanks for the feature request. We have re-arranged the data in the Value Explorer nodes to address the concern. The fix is available in Wallaby extension v1.0.361+

<img width="503" alt="Screen Shot 2023-06-27 at 11 52 59 am" src="https://github.com/wallabyjs/public/assets/979966/9d1c1e07-6a4c-4a3c-aa87-b686a9984d67">
