### ISSUE TITLE
Angular + Typescript + JSPM (ES6 Modules) -> WallabyJS Configuration ?

### ISSUE THREAD

**Issue by OClement** [wallabyjs/public#325]
Hi,

I created a [SatckOverflow question](http://stackoverflow.com/questions/33575808/angular-typescript-jspm-es6-modules-wallabyjs-configuration) with some details about this but have yet to receive an answer.

Anyone can help with this?
I tried different avenues with no success so far. Details with config are at SO
*(Let me know if you prefer me replicating the whole question here instead of linking*

Thank You

**Comment by ArtemGovorov** [comment]
It's better to create your questions/issues in this repo. I do monitor StackOverflow, but not very frequently.

The first error `ReferenceError: Can't find variable: module at jspm_packages/github/angular/bower-angular-mocks@1.4.7.js:1` is probably thrown because it requires angular and angular is only loaded via System.js when you import it. Besides, 1.4.7 is for testing angular 1.x apps, and as far as I understand, you are trying to test angular 2 app?

Other errors are a combination of a couple of issues:
- you need to set `load: false` for your tests, they are loaded by System.js in your `bootstrap` function.
- you need to have [matching module format](http://wallabyjs.com/docs/integration/systemjs.html) in TypeScript and System.js config (doesn't matter what format you use - you may use any, just has to match):

``` JavaScript
module.exports = wallaby => {
  return {
    ...
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        module: 4, // <--- System.js
        emitDecoratorMetadata: true,
        experimentalDecorators: true
      })
    },
    ...
    bootstrap: function (wallaby) {
      wallaby.delayStart();

      System.meta = {
              "*": {
                "format": "register" <--- System.js
              }
            };

      var promises = [];
      for (var i = 0, len = wallaby.tests.length; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }

      Promise.all(promises).then(function () {
        wallaby.start();
      });
    }
  };
};
```

If the above given solution doesn't work, could you please create a sample repository with your config and everything else so I may have a look?

**Comment by OClement** [comment]
Thanks for you reply
I've tried what you mentioned and a few other things but still haven't had any luck;

Note: I'm using angular 1.x not 2.0

As for the module config:

>* In my own code, I want to use Es6 Modules
>* When telling Wallaby to load angular-mocks from JSPM, it loads `bower-angular-mocks@1.4.7.js` which in turn loads the proper package using CommonJS: 
    * `module.exports = require("github:angular/bower-angular-mocks@1.4.7/angular-mocks");`
    * Because the `main` prop of it's package.json point to `angular-mocks.js`, I guess this is what it will actually be loaded in the end. This file however uses the **Global Format**

How should I configure both the Typescript's Compiler and System then?
I think this is really confusing and wasn't able to find clear documentation on either Wallaby of Jspm/System docs that clarify what it is actually expecting in what context

I tried setting Typescript's Compiler to 5 (Es6) and System.meta Format to "esm" (Es6) and also tried to set the compiler to 4 (SystemJs) and System.meta to "register"; both methods won't work

Thanks for your help!

[I created a repo here](https://bitbucket.org/oclement/jspmtsnges6/src)
--

**Comment by ArtemGovorov** [comment]
Thanks for the repo! It's much easier now when see what you're doing.

You may find the working wallaby.js config below.
The changes I have made include:
- removing `'jspm_packages/system-polyfills.js'`from the `files` list as it gets loaded by system.js anyway (is not the issue related change, just to clean things up).
- moving `angular-mocks` loading to the bootstrap function and loading it via system.js import. It wasn't working for you because as you have noticed, the package is using CommonJS and when you include it in the files list, wallaby.js is just trying to load it via `script` tag, so it fails. I have added it as a first promise to be loaded before all of your tests in the bootstrap function. Alternatively, you may just `import` it from you specs just like you import `ng`.
- setting TypeScript module to 4 (System.js). You may also use 2 (AMD). Using 5 (ES6) is possible, but doesn't make much sense because you're doing compilation with wallaby anyway, so why leaving it for System.js to do in runtime?
- using `scriptLoad: true` in System.js config in the bootstrap function to make system.js load scripts via `script` tags to make inline error messages work. 

You may also use `module: 1` (CommonJs) for your TypeScript compiler and remove the `scriptLoad: true` setting, but in this case, because System.js will be loading the code via XHR and `eval`-ing it, PhantomJs will not be able to report correct error stacks, so wallaby.js will not be able to display inline error messages. I have [updated the docs](http://wallabyjs.com/docs/integration/systemjs.html) to reflect it.

``` JavaScript
module.exports = function (wallaby) {
  
  wallaby.defaults.files.instrument = false;

  return {
    files: [
      'jspm_packages/system.js',
      'app/config/system.config.js',
      '!app/**/*.spec.ts',
      '!app/**/*.d.ts',

      {pattern: 'app/**/*.ts', instrument: true, load: false},

      'app/**/*.html'
    ],

    tests: [
      {pattern: 'app/**/*.spec.ts', load: false}
    ],

    env: {
      runner: "node_modules/karma-phantomjs2-launcher/node_modules/phantomjs2-ext/lib/phantom/bin/phantomjs"
    },

    preprocessors: {
      'app/**/*.ts': require('wallaby-gulp-adapter')(require('gulp-inline-ng2-template')({base: 'app', target: 'es5'}))
    },

    // CompilerOptions from https://github.com/Microsoft/TypeScript/blob/master/src/compiler/types.ts
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({
        module: 4, // or 2 -> AMD, or 1 -> CommonJs (but you will not have inline error messages support)
        emitDecoratorMetadata: true,
        experimentalDecorators: true
      })
    },

    // serving node modules contents as is if/when requested
    middleware: function (app, express) {
      app.use('/node_modules',
        express.static(
          require('path').join(__dirname, 'node_modules')));


      app.use('/jspm_packages', express.static(require('path').join(__dirname, 'jspm_packages')));
    },

    bootstrap: function (wallaby) {
      wallaby.delayStart();

      System.config({
        meta: {
          'app/*': {
            scriptLoad: true
          }
        }
      });

      var promises = [];

      for (var i = 0, len = wallaby.tests.length; i < len; i++) {
        promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
      }

      System.import('angular-mocks')
        .then(function () {
          return Promise.all(promises).then(function () {
            wallaby.start();
          });
        });
    },

    testFramework: 'jasmine',

    debug: true
  };

};
```

**Comment by OClement** [comment]
That looks great! thanks for the solution, but more importantly for the explanation!
It makes much more sense now!

It seems to work just fine now, 

I'll add that Wallaby is a great product, and with great support!

Thanks again

O.
