### ISSUE TITLE
VS Code and Vitest: "Automatic Jest configuration error: Module jest-cli is not found in '.'."

### ISSUE THREAD

**Issue by casamitjana** [wallabyjs/public#3261]
### Issue description or question

When trying to start Wallaby.js in a Vitest project, it fails with the error:

```
‌[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'. 
[Error]  
[Error] We've also tried to automatically configure Wallaby.js for other frameworks 
[Error] Automatic Vitest configuration error: 
```

The project is the sample [Next.js with Vitest](https://github.com/vercel/next.js/tree/canary/examples/with-vitest) and not using a Wallaby configuration file. I was also able to reproduce with a plain [React with Vitest project](https://stackblitz.com/edit/vitest-dev-vitest-qmhoqm).

I've tried to apply the fixes described on https://github.com/wallabyjs/public/issues/2254 but nothing worked for me.

Steps to reproduce:

1. `yarn create next-app --example with-vitest with-vitest-app`
2. `cd with-vitest-app`
3. ensure minimum Vitest version supported is present `yarn add --dev vitest@0.14.0`
4. ensure Vitest runs correctly with `yarn test`
5. `code .` to switch to VS Code (I'm running lattest version) from here
6. ensure latest Wallaby is in use "Wallaby.js: Force Core Update"
7. select Wallaby configuration "Wallaby.js: Select Configuration" and "Automatic Configuration: `<project directory>`"

**Expected:** Wallaby should start.

**Outcome:** the reported error.

Alternatively, you can also try with a non Next.js project by downloading this project's files: https://stackblitz.com/edit/vitest-dev-vitest-qmhoqm and trying to configure Wallaby after `npm i`.

### Wallaby diagnostics report

I couldn't attach a report because Wallaby won't start.

**Comment by smcenlly** [comment]
Thanks for creating a nice comprehensive set of instructions to try reproduce your issue.

Wallaby is working for us, both when we follow your step-by-step instructions and when we use the sample repo.

--

We *think* that perhaps your problem is that you are running on an older version of Wallaby, but we're not sure. In your Wallaby Console, you should see the wallaby version being reported:

```
‍​[Info]​ Started Wallaby.js Core v1.0.1463
```

Can you please confirm that you're using the latest version? If you're not, please [request a trial license](https://wallabyjs.com/download/#try-it-free) and check if the latest version works for you.

If you are using the latest version, could you please make sure you are using the latest LTS node (v18.x)?

**Comment by casamitjana** [comment]
Thanks for the quick reply @smcenlly. I have individual licenses for Quokka and Wallaby.

Not being on latest would be quite unexpected as I've forced at least twice (as described on my instructions). I was running this:

```‍​[Info]​ Started Wallaby.js Core v1.0.1462```

But after forcing another core update I'm now running:

```‍​[Info]​ Started Wallaby.js Core v1.0.1463```

Alas, this didn't make any difference. I'm getting the very same error. I'm using nnm and my default Node version is v18.17.0.

I tried on a second machine with the same VS Code profile and it worked just fine, same as you. The only difference between the too that I can think of it creating the problem is that the failing one is running a [public beta of macOS Sonoma](https://www.apple.com/uk/macos/sonoma-preview/)  [Version 14.0 Beta (23A5312d)]. In hindsight I should have mentioned it but I didn't even think of it, I've forgotten about it in my day to day as everything else works just fine.

Since this might be turning into a Sonoma report, I'll also add another issue which while not related to Vitest, perhaps it is to my system: on this machine, in some decently sized Jest projects Wallaby never seems to complete the starting cycle on VS Code's status bar (the `[====.   ]` never ends), while I can open and see the tests on the browser view. This code is private so it might be tricky for me to provide a repro.

Is this a setup you can try perhaps? I haven't seen any comments on your blog or Discords regarding Sonoma support.

**Comment by smcenlly** [comment]
It definitely seems like there's something environmental going on with your machine. I doubt it would be because of MacOS Sonoma, but it's possible. At any rate, it's not something we have the ability to set up to test (but again, I doubt it's the problem).

Could you please create a Wallaby Configuration file (or else adjust your package.json) for the projects that are not working for you? You can refer to our [configuration instructions](https://wallabyjs.com/docs/intro/config.html) for how to use a configuration file. Can you please set:

**wallaby.js configuration file**
```javascript
module.exports = () => ({
  debug: true,
  trace: true
});
```

or

**package.json**
```json
...

  "wallaby": {
    "debug": true,
    "trace": true
  }
}
```

This will give you additional output in the Wallaby Console that may help us diagnose why it's not working for you. Please reply with the update Wallaby Console output for both projects that have issues.

**Comment by smcenlly** [comment]
We have an idea as to what may be causing your problem. When Wallaby is unable to find `node` in your system path, if you are using VS Code, then Wallaby will automatically fallback and try run using VS Code's electron node process.

We've seen some similar problems in the past when this has happened and think perhaps it's the same problem that you are having.

We have updated Wallaby core, `v1.0.1464` to no longer do this. Please update to the latest version and see if it fixes your problem. If Wallaby **was** running using Electron, you may receive an error telling you that you need to specify the `node` executable location.

**Comment by casamitjana** [comment]
You got it right @smcenlly. I did get the error message and when navigating to VS Code Wallaby: Node setting, the path turned out to be a previous version of nvm's Node (`/Users/casamitjana/.nvm/versions/node/v16.20.1/bin/node`), which I had removed to upgrade to `v16.20.1`.

After changing the path to `/Users/casamitjana/.nvm/versions/node/v18.17.1/bin/node` everything is now working correctly.

Thanks for your help.
