### ISSUE TITLE
No tests are recognized, so no tests are run

### ISSUE THREAD

**Issue by manudss** [wallabyjs/public#3296]
### Issue description or question

For several days now, when I launch wallaby, no test is launched. 

```
0 failing tests, 0 passing

2023-11-13T10:39:35.264Z project Test run started; run priority: 3
2023-11-13T10:39:35.292Z project Running all tests
2023-11-13T10:39:35.391Z project Test run finished
2023-11-13T10:39:35.392Z project Test run data re-queued
```

### Wallaby diagnostics report

https://gist.github.com/manudss/cc4b9a5ad4355b593e048dccd2992e7f

**Comment by smcenlly** [comment]
Thanks for your diagnostics report and sorry to hear you're having problems.

I tried using the `package.json` dependencies from your project, and Wallaby (in my sample project) wouldn't start for me  because of the [NX_DAEMON](https://nx.dev/concepts/more-concepts/nx-daemon) running in the background. I wonder if this is possibly causing problems for you too.

We've updated Wallaby to explicitly tell NX to **NOT** use the NX_DAEMON when running your tests.

---

We recently added support for `jasmine@4.x` and `jasmine@5.x` when running browser tests. Previously, Wallaby was always using `jasmine@3.10.0`. We can see from your project that you are using `jasmine-core@5.1.0`, but we can also see that you have various other testing frameworks installed as dependencies of your project (e.g. `jest`, and `mocha`). It's possible that due to conflicting dependencies, our recent `jasmine` version support changes have broken something for your project now that we support future versions of `jasmine`.

---

Can you please try the following:

1. Update to the latest version of Wallaby core, `v1.0.1500`, and restart Wallaby. You should be able to just restart your IDE and start Wallaby.js to force the update.
2. If that doesn't fix your problem, please create and use a Wallaby.js configuration file (instead of automatic configuration) with the following settings:
```javascript
module.exports = () => ({
  autoDetect: true,

  // Force Wallaby to use Jasmine 3.10.0
  testFramework: 'jasmine@3.10.0',

  // Leave these option to provide additional
  // log information if you're still having
  // trouble with Wallaby after trying this
  // configuration.
  debug: true,
  trace: true,
});
```

3. If you're still having problems, can you please provide us with your Wallaby Console output. It should have a lot more information logged with the `debug: true` and `trace: true`settings.

**Comment by manudss** [comment]
Thanks @smcenlly , It's works with new version of WallabyJS. Thanks.
