### ISSUE TITLE
Syntax Error: Parse Error suddenly occurred without changes to code / spec

### ISSUE THREAD

**Issue by wilgert** [wallabyjs/public#33]
Suddenly Wallaby stopped working giving a ```Runtime Error: SyntaxError: Parse error``` in the Wallaby Console. Enabling debug mode doesn't really give me any more info:
```Thu, 05 Mar 2015 10:18:58 GMT project Sandbox (active) [dab7i] error: SyntaxError: Parse error```

The normal karma test runner has no problems running my test suite (in Chrome in stead of PhantomJS).
Even when checking out an older commit that worked yesterday the error still happens.

Software Versions:
```OS: Windows 8.1```
```IDE: PHPStorm 8.0.3```
```Wallaby.js plugin: 1.0.2```

**Comment by ArtemGovorov** [comment]
So it worked before?
The reason for "SyntaxError: Parse error" without any additional description (PhantomJs doesn't give much more unfortunately) is normally something inside those files that are not instrumented, such libraries or other files that you set `instrument: false` to. Did any of such files change recently?

**Comment by wilgert** [comment]
No, i did not do a NPM install/bower install or something. I just made some changes to the code and spec and suddenly it did not work anymore.
I also do not have any files that have ```instrument: false``` in wallaby.conf.js.
PHPStorm does not indicate any Syntax Errors in my files.

**Comment by ArtemGovorov** [comment]
It may not be a syntax error as such, just the way phantom reports it. Anyway, as it worked before, it seems like it may be the changes related. 

Try reverting to the state where you're 100% sure it worked, then stop wallaby, change your wallaby.conf.js (you can even just add some space to it) and start wallaby again. If it works, try gradually applying your changes to try to find out what exactly breaks it. It'd be awesome to know what exactly breaks it, so that I can try to see if I can do something to make wallaby avoid it in future or provide better error message.

**Comment by wilgert** [comment]
O.k. i'm gonna try that.

**Comment by wilgert** [comment]
```
SelectedSellables.prototype.setOrderType = function orderType(orderType) {
            this._orderType = orderType;
        };
```
This function in my Service is causing the syntax error. When I comment it out: no error. When I remove the comment the syntax error occurs.

**Comment by wilgert** [comment]
Actually changing it to this fixed it:

```SelectedSellables.prototype.setOrderType = function setOrderType(orderType) {
            this._orderType = orderType;
        };
```

**Comment by ArtemGovorov** [comment]
Nice find! So it looks like PhantomJs is not happy about the function name being the same as parameter name. I'll have have a look what I can do about it. Thanks for your help!
