### ISSUE TITLE
How to copy actual value

### ISSUE THREAD

**Issue by DiamondYuan** [wallabyjs/public#3306]
### Issue description or question
![image](https://github.com/wallabyjs/public/assets/9692408/e24aed8c-c3d2-4c65-a4c6-3fd9556f4a9c)
### Wallaby diagnostics report

I click copy actual when expect is different from Actual.

I expect to get [1,2,3] . This way I can paste it directly into the source code

I actually get 

```
Array [1,2,3]
```

**Comment by smcenlly** [comment]
In your example, you will see that Wallaby is reporting the value that is provided by `vitest` (see CLI output below):

<img width="203" alt="image" src="https://github.com/wallabyjs/public/assets/2074089/4df46cdc-d311-4354-b0bc-52a6275423d3">

---

Due to how `vitest` reports expected vs. actual values, sometimes the actual value will be truncated or may not be the same as shown in your code. However, we've updated Wallaby to omit the `Object` and `Array` when output these values from `vitest`. Please update to Wallaby core `v1.0.1511`, it will no longer show the prototypes for plain objects and array.
