### ISSUE TITLE
Move core to the latest stable node version (so that ES6 features can be used in config file)

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#331]
Hello @ArtemGovorov,

Here is config:

```js
'use strict';

console.log('findIndex', [].findIndex);

module.exports = () => {
    return {
        files: [
            'lib/**/*.js'
        ],

        tests: [
            'test/**/*Spec.js'
        ],

        env: {
            type: 'node'
        }
    };
};
```

Here is console output:

```
wallaby.js started
core v1.0.142
findIndex undefined
```

**Comment by ArtemGovorov** [comment]
It's expected. Wallaby.js itself is using node.js version that doesn't fully support ES6. Having said that, you may use `findIndex` in your code and tests (just not in config), if your [node version](http://wallabyjs.com/docs/integration/node.html#node-version) supports it and you add `runner: 'node'` to your `env` setting:

``` JavaScript
env: {
            type: 'node',
            runner: 'node'
        }
```

The issue with fully using ES6 in config file will be gone once we update the internal node.js version.

**Comment by mdreizin** [comment]
Thanks @ArtemGovorov for the response.

My `node` version supports `findIndex()`, but ``findIndex` is always `undefined`.

```
node -v
v4.1.2
```

`runner` is set to `node`.

```
node wallaby.js
findIndex function findIndex() { [native code] }
```

Please reopen it, because you made on the spot decision to close it.

**Comment by ArtemGovorov** [comment]
I understand that your version supports `findIndex`, what I'm saying is that Wallaby.js itself is using node.js version that doesn't fully support ES6. It ships with that version and is not using your local one.
You may still use your local one for tests with `env` setting like I described above and your tests and code will work fine with `findIndex`, but you can't use the function in wallaby config (because the node version that wallaby uses to run the config doesn't support it).

The issue of fully using ES6 (including the `findIndex `) in config file will be gone once we update the internal node.js version in wallaby.js.

**Comment by mdreizin** [comment]
@ArtemGovorov I understand, but could you please tell me how much time need to migrate `core` to the latest version of `node` that support `ES6`?

**Comment by ArtemGovorov** [comment]
It's not hard to switch to the latest the node version, however there's a chance that something may work differently in the new node version and our tests will not catch it, so it may potentially affect lots of users. We do plan to switch, however it wasn't a high priority task, because it only affect the config file and nothing else.

**Comment by ArtemGovorov** [comment]
I'll leave the issue opened until the node version switch, so you'll get the notification when it happens.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks.

Anyway users should know what kind of `node` version you are using and then they can use related features.

**Comment by mdreizin** [comment]
@ArtemGovorov I have just renamed title to `ES6 support`, but it would be nice if you rename it to more relevant to make sure that it would not confuse users.

**Comment by ArtemGovorov** [comment]
I have been running a few tests and everything seems fine, so I have updated the node version to 4.2.2 for IntelliJ platform in v1.0.46 (you may need to restart your IDE to get the update).

**Comment by mdreizin** [comment]
@ArtemGovorov Big thanks. I have just updated and it works perfect now.
