### ISSUE TITLE
Display the number of skipped/ignored/pending tests

### ISSUE THREAD

**Issue by hellboy81** [wallabyjs/public#334]
Instead of 

```
No failing tests, 3 passing 
```

As I mentioned  `3 passing` is mocha status message and has only information about `it`-count.

Can you also information how many `describe`-s are passing?

May be this message is more descriptive:

```
No failing tests, 3 assertions in 1 test case passing 
```

**Comment by hellboy81** [comment]
Also info about ignored tests count can be useful

**Comment by fvanwijk** [comment]
Why describes? A `describe` is used to structure your tests, you can nest them. Therefore you cannot count them. It makes more sense to count the `expects`, but still I think that counting the `it`s gives you the most precise information about failing/passing tests.

Regarding showing ignored tests: +1

**Comment by ArtemGovorov** [comment]
Agreed with Frank, `describe` may be tricky to count. Overall visibility will be increased in the [Test Explorer](https://github.com/wallabyjs/public/issues/144) that we're working on now.

**Comment by brettjacobson** [comment]
@hellboy81 are you using just one describe() per test file?  If so I understand your request; we used to do the same, but I've been gradually getting our team to start nesting describes to better organize the specs in the file, and I agree that if you do any nested describes, the overall count of describes becomes meaningless.

What about a count of the number of files that were read in due the "tests" specifier from the wallaby.json file?  I could see how that might be an interesting metric for my team, because I could see the number growing from day to day, but I don't know that this number would be necessary to know "all the time".

I *do* agree that the number of ignored tests is a number that needs to be known all the time, so +1 for displaying that next to the number of passing tests.

**Comment by ArtemGovorov** [comment]
> What about a count of the number of files that were read in due the "tests" specifier from the wallaby.json file?

We can definitely add the metric to the Test Explorer.

> number of ignored tests is a number that needs to be known all the time

Just to make sure we are all on the same page, by ignored tests you mean those marked as `xit`/`it.skip` or within `xdescribe`/`describe.skip` (depending on whether it's jasmine or mocha)?

**Comment by brettjacobson** [comment]
@ArtemGovorov Yes, xdescribe/xit is what I meant.

**Comment by hellboy81** [comment]
May be also code coverage metrics can be added?

- green markers count
- grey markers count
- overal markers count

etc..

**Comment by ArtemGovorov** [comment]
@hellboy81 It's planned as part of https://github.com/wallabyjs/public/issues/38, not sure if the coverage metrics are good to have on the Failing Tests screen.

**Comment by snorkpete** [comment]
Any update on when/if a display of skipped tests may be added?

**Comment by ArtemGovorov** [comment]
@snorkpete When we have some update regarding the feature, we'll post it here, so please fell free to subscribe.

**Comment by jhwegener** [comment]
Hey this feature would be very nice for us, too!

**Comment by NikGovorov** [comment]
Hi All,

The feature was implemented and released in the latest version of the editor extensions, core and wallaby app.

![vsc_jb_app_skipped_todo](https://user-images.githubusercontent.com/129254/83220443-54613d00-a1b6-11ea-9374-b94f3b4fce58.gif)
