### ISSUE TITLE
Running with nextJS and TS - "Wallaby has stopped, results are no longer available."

### ISSUE THREAD

**Issue by greenmooseSE** [wallabyjs/public#3353]
### Issue description or question
(using Rider)

I tried a simple starter project to get Jest running with nexTJS, and followed guide at https://github.com/greenmooseSE/wallaby.labs.public/tree/try/wallabyWithNextJsAndTs  and creating Wallaby configuration with automatic config (i.e. no config file). 

This works when running via `npm run test`, but wallaby fails immediately with some "garbage" in console output and at the end of output I can see below error
```
SyntaxError: Unexpected token 'u', "function _0"... is not valid JSON
    at JSON.parse (<anonymous>)
    at new AnyMap (<...>\node_modules\@cspotcode\source-map-support\node_modules\@jridgewell\src\any-map.ts:20:37)
```

The repro project can be found at https://github.com/greenmooseSE/wallaby.labs.public/tree/try/wallabyWithNextJsAndTs .

### Wallaby diagnostics report
Menu is grayed out

### Notes
* It is working if I use `jest.config.js` instead of `jest.config.ts` (see below [change](https://github.com/greenmooseSE/wallaby.labs.public/pull/1/files)). But is this a known issue or am I missing something in configuration for using the typescript dito?
![image](https://github.com/wallabyjs/public/assets/31244330/7d8fee4e-0d2f-4dbe-9bbc-c6a0d73b605b)

**Comment by smcenlly** [comment]
Your sample repo (branch: `try/wallabyWithNextJsAndTs`) is working for us with `Rider 2023.3.4`, `node@18.19.0`, and Wallaby core `v1.0.1551`.

Is it possible that your license has expired? If so, there was likely a compatibility issue with jest that is fixed in the latest version of Wallaby vs. the version you are using. If you provide your diagnostics report when you have the issue, we will be able to confirm for you or else investigate why it's not working for you.

**Comment by greenmooseSE** [comment]
Thanks for reply. Today after Window updates/reboot it I can no longer repro it. Weird...

**Comment by smcenlly** [comment]
I *think* I saw that you renewed your license shortly before you raised the issue. If this is the case, it's possible (and easily explained) by your Wallaby version being out of date.
