### ISSUE TITLE
Making Wallaby's gutter indicators play nicely with data driven tests?

### ISSUE THREAD

**Issue by SamPruden** [wallabyjs/public#3357]
I'm evaluating Wallaby for use on a project which has a large number of data driven Vitest tests, and I'm finding that the editor integration isn't working quite as well as I'd like.

The current way the tests are defined is roughly
```
testParser("fooParser", {
    "some input value": "some expected output",
    "some other input": "some other output",
    // ...
});
```
where `testParser` is a function which calls `test` once for each test case. Understandably, Wallaby doesn't know how to show nice pass/fail indicators in the IDE (VSCode) on each line of the data definition, corresponding to each test.

I thought I might be able to fix that by doing something more like
```
testParser("fooParser", "some input value", "some expected output");
testParser("fooParser", "some other input", "some other output");
// ...
```
where `testParser` now generates one test for each call. I'd hoped it would see that each call to `testParser` is responsible for a test and give me appropriate pass/fail indicators in the gutter, but alas not.

Is there some trick to making Wallaby play nicely with this data driven testing pattern? Perhaps some way I can restructure the tests, something I can do within Wallaby itself, or some dark magic secret to how Wallaby recognises Vitest tests which would allow me to register `testParser` as a custom test function?

**Comment by ArtemGovorov** [comment]
@SamPruden Wallaby's decision on whether to show a line of code with a red indicator (and display an error message next to it) is based on a very simple logic: whether or not the line is a part of the error stack. 

In case of the `testParser` that simply calls `test` at some point, Vitest (as the majority of other testing frameworks), doesn't connect places where test is defined and where/when it's called. This is because it runs test file in 2 stages: 
- first, to get all test functions first (the ones being passed to the `test` as an arg after the test's name),
- second, then to run those test functions.

So by the time test function is called, it's call stack is not connected to a place where it has been passed to `test`. So when test is running and failing, neither Vitest (nor Wallaby) can not highlight/report the line.

One straightforward way to make it work as you expect that comes to mind, is to restructure the code a bit to connect test error stack with the stack of where `testParser` is being called from.

For example:

```
const testParser = (i, toBoom) => {
  const err = new Error(); // capture stack here, when `testParser` is called

  test('my test ' + i, () => {
    try { // wrap test body
      if (toBoom) {
        boom;
      }
    } catch (e) {
      e.stack += err.stack; // when test throws, add `testParser` call stack to the error stack
      throw e;
    }
  })
}

testParser(1, true); // now the test error will show up here

testParser(2, false);
```

will make 

<img width="765" alt="Screenshot 2024-04-08 at 1 17 17 pm" src="https://github.com/wallabyjs/public/assets/979966/0a145e12-97aa-4d16-93d6-9aef93bc183d">

In case if you want to preserve a single `testParser` call, with params on different lines, you may connect a line with a specific param to the test error stack by having a function that produces an error for that line, for example:


```
const testParser = (n, inputs) => {
  inputs.forEach((input, i) => {
    input.e();
    test('my test ' + i, () => {
      try {
        expect(input.v).toBe('some expected output')
      } catch (e) {
        e.stack += input.e().stack;
        throw e;
      }
    })
  });
}

testParser("fooParser", [
  {v: "some expected output", e: () => new Error()},
  {v: "some other output", e: () => new Error()},
]);
```

In this case the result is that the line with failed assertion data is highlighted:

<img width="1112" alt="Screenshot 2024-04-08 at 2 02 16 pm" src="https://github.com/wallabyjs/public/assets/979966/a9de13fb-e575-47a7-9474-01b07ff497c4">

Hope this helps.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update, glad to hear it helped! 

It should also now look a little bit more helpful in Vitest CLI output too, as the solution is not specific to Wallaby and the CLI output should have the stack entry pointing to the `testParser` line for failures.
