### ISSUE TITLE
Support ClojureScript?

### ISSUE THREAD

**Issue by danielcompton** [wallabyjs/public#337]
Is it possible to support ClojureScript with wallaby? Source maps are available with ClojureScript.

**Comment by ArtemGovorov** [comment]
It is definitely possible. There's only one thing required - a custom wallaby compiler for ClojureScript. There's [the guide how to create one](http://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler).

The compiler is just a function that takes in the original ClojureScript file and is supposed to return an object with 3 things: generated JavaScript source code (that will be executed), source map (for the transformation from the original code to the generated JavaScript) and an array of the original source code coverable ranges  (so that wallaby knows what to display in your editor). 

While I don't expect you to have any issues providing the first two, it may be tricky to get coverable ranges. If you don't have an access to the ClosureScript Abstract Syntax Tree (because the package/parser that you use doesn't support it) or you don't care much about logical branches coverage, then your coverable ranges may just be your ClosureScript lines (you can get them by splitting your original `file.content` by `\n`, iterating over the lines and getting the ranges from each line content). Please note that it's for the worst case scenario and it is better to provide the actual coverable ranges to get the correct coverage in logical statements, etc.

**Comment by seanpoulter** [comment]
Thanks for all your thoughtful replies @ArtemGovorov. This is still helpful. 👏  Any chance you've heard of anyone taking this on?

**Comment by ArtemGovorov** [comment]
@seanpoulter Thanks, unfortunately I don't recall hearing from anyone about taking this one. 

Having said that, since my response things had become simpler for certain testing environments. For example, if you are using Jest (and have a working Jest transformer for ClosureScript, similar to existing ones like the [one for TypeScript](https://github.com/kulshekhar/ts-jest/blob/master/src/ts-jest-transformer.ts#L96-L101)), then no Wallaby config code is required to make it work. Wallaby should be able to [run Jest in automatic mode](https://wallabyjs.com/docs/integration/jest.html#starting-wallaby-on-a-project-with-configured-jest), and display code coverage in the original source file. The code coverage displayed in the original source file will depend of the quality of the source map generated by the transformer (even if it's a basic source map, it should be enough for most of cases).

I'm not sure if Jest transformer for ClosureScript exists yet, but even if it doesn't, it shouldn't hopefully be too hard to write one if ClosureScript can be transpiled to JS with a source map. Once done, the transformer can be used by wider Jest community, and by anyone using Wallaby with Jest.

**Comment by seanpoulter** [comment]
How interesting! A Jest transformer would open it up to both communities to use! I'll explore in that direction and follow-up if I find something interesting. Thanks again @ArtemGovorov!
