### ISSUE TITLE
Support for PNPM

### ISSUE THREAD

**Issue by andyturner** [wallabyjs/public#3378]
We've recently had to switch over to using https://pnpm.io/ for our Angular packages and I'm finding that Wallaby no longer works. The tests work fine with ng test though. 

You can reproduce this quite easily by building a fresh Angular app with 'ng new', which automatically installs the packages using npm. Wallaby will work fine with that project. If you then delete node_modules and package-lock.json, then run pnpm install (assuming pnpm itself is installed), you'll find that Wallaby can no longer start up. I notice that there's some mention of pnpm support introduced for issue https://github.com/wallabyjs/public/issues/3142, but that was for v1.0.1398 and I'm already on v1.0.1518.

‍​[Info]​ Started Wallaby.js Core v1.0.1518
​[Info]​ - Generating browser application bundles (phase: setup)...
​​[Error] Failed to load configuration file: Automatic Angular CLI configuration error: Unable to load webpack module.
​​
​​[Error] 
​​
​​[Error] We've also tried to automatically configure Wallaby.js for other frameworks
​​
​​[Error] Automatic Jest configuration error: Module jest-cli is not found in '.'.
​​
​​[Error] Automatic Vitest configuration error: Vitest dependency not found.​​
​​[Error] Please refer to our docs: https://wallabyjs.com/docs/config/overview.html ​​

**Comment by smcenlly** [comment]
Thanks for reporting your issue.

Wallaby does support `pnpm` for Angular, but there are some extra steps that need to be taken for projects that use `webpack` that we were unaware of.

Wallaby needs to dynamically load `webpack` for your project and it's only listed as a nested dependency in your project, so this causes Wallaby to fail because `pnpm` isolates these dependencies. You will need to ensure `webpack` is hoisted to your `node_modules` folder. You can do this by either:
- add `public-hoist-pattern[]=webpack` to `<rootDir>/.npmrc`, or
- run `pnpm add webpack --save-dev` to add an explicit dependency.

We've updated the error message in the latest version of Wallaby to describe what you have to do when `webpack` doesn't load for projects using `pnpm`.

**Comment by andyturner** [comment]
Yes, the explicit webpack dependency worked for me. Thanks! I guess I need to renew my licence and get it upgraded.
