### ISSUE TITLE
Testing Library Tests Failing when running with Wallaby

### ISSUE THREAD

**Issue by christiannwamba** [wallabyjs/public#3383]
### Issue description or question

When I run wallaby start, some test are throwing that: TestingLibraryElementError: Unable to find an element with the text: 

```ts
  it('should return correct optimistic result when fetching after error', async () => {
    const key = queryKey()
    const error = new Error('oh no')

    const results: Array<UseQueryResult<string>> = []

    function Page() {
      const query = useQuery({
        queryKey: key,
        queryFn: async () => {
          await sleep(10)
          return Promise.reject(error)
        },
        retry: false,
        notifyOnChangeProps: 'all',
      })

      results.push(query)

      return (
        <div>
          <div>
            status: {query.status}, {query.fetchStatus}
          </div>
          <div>error: {query.error?.message}</div>
        </div>
      )
    }

    function App() {
      const [enabled, setEnabled] = React.useState(true)

      return (
        <div>
          <button onClick={() => setEnabled(!enabled)}>toggle</button>
          {enabled && <Page />}
        </div>
      )
    }

    const rendered = renderWithClient(queryClient, <App />)

    await waitFor(() => rendered.getByText('status: error, idle'))

    fireEvent.click(rendered.getByRole('button', { name: 'toggle' }))
    fireEvent.click(rendered.getByRole('button', { name: 'toggle' }))

    await waitFor(() => rendered.getByText('status: error, idle'))

    expect(results).toHaveLength(4)

  })
```

Error:

```
 TestingLibraryElementError: Unable to find an element with the text: status: error, idle. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible. 
     
    Ignored nodes: comments, script, style 
    <body> 
      <div> 
        <div> 
          <button> 
            toggle 
          </button> 
          <div> 
            <div> 
              status:  
              pending 
              ,  
              paused 
            </div> 
            <div> 
              error:  
            </div> 
          </div> 
        </div> 
      </div> 
    </body> 
     
    Ignored nodes: comments, script, style 
    <html> 
      <head /> 
      <body> 
        <div> 
          <div> 
            <button> 
              toggle 
            </button> 
            <div> 
              <div> 
                status:  
                pending 
                ,  
                paused 
              </div> 
              <div> 
                error:  
              </div> 
            </div> 
          </div> 
        </div> 
      </body> 
    </html> 
```

and some other tests: Invalid Chai property: toBeInTheDocument 

```ts
  it('setQueryData - should respect updatedAt', async () => {
    const key = queryKey()

    function Page() {
      const state = useQuery({ queryKey: key, queryFn: () => 'data' })
      return (
        <div>
          <div>data: {state.data}</div>
          <div>dataUpdatedAt: {state.dataUpdatedAt}</div>
          <button
            onClick={() => {
              queryClient.setQueryData(key, 'newData', {
                updatedAt: 100,
              })
            }}
          >
            setQueryData
          </button>
        </div>
      )
    }

    const rendered = renderWithClient(queryClient, <Page />)

    await waitFor(() => rendered.getByText('data: data'))
    fireEvent.click(rendered.getByRole('button', { name: /setQueryData/i }))
    await waitFor(() => rendered.getByText('data: newData'))
    await waitFor(() => {
      expect(rendered.getByText('dataUpdatedAt: 100')).toBeInTheDocument()
    })
  })
```

Error:

```
 Invalid Chai property: toBeInTheDocument 
     
    Ignored nodes: comments, script, style 
    <html> 
      <head /> 
      <body> 
        <div> 
          <div> 
            <div> 
              data:  
              newData 
            </div> 
            <div> 
              dataUpdatedAt:  
              100 
            </div> 
            <button> 
              setQueryData 
            </button> 
          </div> 
        </div> 
      </body> 
    </html> 
```

These tests don't fail when I run the test from the terminal. I was able to reduce the amount of failing tests by cleaning up after each test but I still have a few tests failing.

### Wallaby diagnostics report

Commit was too long after submitting diagnostic report but I am happy to upload it somewhere.

**Comment by ArtemGovorov** [comment]
> Commit was too long after submitting diagnostic report but I am happy to upload it somewhere.

Can you please upload it as a public [GitHub Gist](https://gist.github.com/)?

**Comment by christiannwamba** [comment]
Also the test file I am working with is public in case you want to reproduce: https://github.com/TanStack/query/blob/main/packages/react-query/src/__tests__/useQuery.test.tsx

**Comment by smcenlly** [comment]
Thanks for providing your diagnostics report and the link to the repo.

Based on your diagnostics report, it looks like you're not using the latest version of the repo.

We tried to reproduce your problem by cloning [https://github.com/TanStack/query](https://github.com/TanStack/query) and using commit `46359542f00203c0fdf8931073a2d8a49ab71f37`, which seems to align with your diagnostic report dependencies.

We needed to create `vite.config.ts` in the project root with the same content specified in your diagnostics report:

```typescript
import { defineConfig } from 'vitest/config'

export default defineConfig({
    test: {
      environment: 'jsdom',
  
  },
})
```

After running `pnpm install` and `pnpm run build`, we started Wallaby on `packages/react-query/src/__tests__/useQuery.test.tsx`.

We receive the same test results in Wallaby as we do when running from the CLI. In both Wallaby and the CLI, we have 67 failing tests, 72 passing tests.

---

We noticed that neither Wallaby nor vitest work from the CLI without first running `pnpm run build`. I'm assuming that this means that the tests are not being run on the source code but on the transpiled code instead. This means that your coverage indicators and error messages will point to your transpiled code instead of your source code. To get the full benefit of Wallaby, you will want to run your tests on the source code. You will need to update your vitest / project configuration to do this. First get this working from the CLI, then try Wallaby again.

Regarding your error, could you please create a branch from the current state of your repo and share with us? Then we can try to reproduce your issue.

**Comment by christiannwamba** [comment]
Thanks for clarifying. Just tried running directly with vitest and getting similar behavior.
