### ISSUE TITLE
Experimental-vm-modules by default when using vscode

### ISSUE THREAD

**Issue by adcreare** [wallabyjs/public#3403]
### Enable experimental-vm-modules by default when using vscode without .env or package json setting.

Using the automatic configuration of wallaby, typescript, jest and ESM. 
In webstorm I'm able to use wallabyjs and have vm-modules enabled simply by adding NODE_OPTIONS="--experimental-vm-modules" to my shell file.  When I run wallabyjs webstorm seem to pass those env settings on and its all good. 

However vscode seems to ignore this shell setting for some reason. 
I do have the workaround of using a .env file per-project, but that's a pain because we have a lot of repos that I'd have to add this into, just for vscode. 

I can add a wallaby section to the package.json like this
```
 "wallaby": {
    "env": {
      "params": {
        "runner": "--experimental-vm-modules"
      }
    }
  }
} 
```

Are any of the wallaby team aware of any workaround for this issue that's a more global setting, vs the project setting options I've listed above?

**Comment by smcenlly** [comment]
The reason that this is working when you launch WebStorm and not VS Code is because your `NODE_OPTIONS` environment variable is set differently when you launch each. For example, if you were to set this variable from a Terminal session in the command-line, and then launch VS Code, the NODE_OPTIONS environment variable **should** be set.

We have seen this in the past, and it's not something we can handle as part of Wallaby, it's how the environment variables are being set / passed to both VS Code and then to Wallaby.

**Comment by adcreare** [comment]
Thanks @smcenlly - unfortunately vscode only passes on two NODE_OPTIONS values and `experimental-vm-modules` isn't one of them, I think because it's electron app. 
Hence hoping there might be a more global config at the wallaby level I could set. 
Might just have to stick with webstorm!
