### ISSUE TITLE
Quokka Not Displaying Output or Live Values

### ISSUE THREAD

**Issue by jonasboardwalker** [wallabyjs/public#3414]
### Issue description or question

I'm experiencing an issue with Quokka version `v1.0.592`. After installation, Quokka fails to display any output or live values in Visual Studio Code. I have a paid license and installed this specific version due to license constraints. Despite various troubleshooting steps, the problem persists, and I receive errors in the Developer Tools console (detailed below).

#### Environment

- **Quokka Version**: v1.0.592 (Paid License)
- **VSCode Version**: 1.94.2
  - **Commit**: 384ff7382de624fb94dbaf6da11977bba1ecd427
  - **Electron**: 30.5.1
  - **Node.js**: 20.16.0
  - **OS**: macOS 14.0.0 (Darwin arm64)
- **Node Versions Tested (via nvm)**:
  - 16.13.1
  - 18.12.1
  - 18.19.0
  - 19.2.0
  - 21.6.2
  - 23.1.0
- **Extensions**: All disabled except Quokka

#### Steps Taken

- Disabled all other VSCode extensions
- Tested with multiple Node versions via `nvm`
- Deleted and reinstalled the Quokka extension

#### Error Details

In the VSCode Developer Tools console, I consistently receive the following error:

```plaintext
[WallabyJs.quokka-vscode] Cannot read properties of undefined (reading 'filename')
mainThreadExtensionService.ts:79 TypeError: Cannot read properties of undefined (reading 'filename')
    at I._start (vscode-file://vscode-app/Users/jonasboardwalker/.vscode/extensions/wallabyjs.quokka-vscode-1.0.592/dist/index.js:6:59205)
    at vscode-file://vscode-app/Users/jonasboardwalker/.vscode/extensions/wallabyjs.quokka-vscode-1.0.592/dist/index.js:6:48160
```

#### Additional Notes

Any guidance on resolving this issue would be greatly appreciated, as Quokka is not operational in my current setup despite the above efforts. Thank you for your assistance!

P.S I tried to install lates version and get the same error. Output is not outputting anything

**Comment by smcenlly** [comment]
In mid-September, VS Code included a breaking change that means that versions of Quokka before `v1.0.652` will not work on the latest version of VS Code; there is nothing we can do to fix this for previous versions.

You have a number of options to get Quokka working:

1. Use the older version of VS Code. [Microsoft docs](https://code.visualstudio.com/docs/supporting/FAQ#_how-do-i-opt-out-of-vs-code-autoupdates) describe how to use the previous version:

> You can install a previous release of VS Code by uninstalling your current version and then installing the download provided at the top of a specific release notes page.


2. Use the latest version of Quokka and switch to use Community Edition.
3. Use the latest version of Quokka and renew your license to continue using PRO features.

Unfortunately, we do not have another solution. This is the first time in 5 years that there's been a breaking change to VS Code that's stopped Quokka from working, but it is outside of our control and we don't have the ability to fix old versions. If you choose not to renew and want to use the older version of Quokka supported by your license then unfortunately it also means you won't be able to use the latest version of VS Code because of their breaking change.
