### ISSUE TITLE
Config template empty with JetBrains plugin

### ISSUE THREAD

**Issue by matchatype** [wallabyjs/public#3421]
### Issue description or question

Wallaby cannot be setup through the configuration panel. When trying to add a new config, the template seems empty... Cannot even try creating a new one. Also, clicking on the Wallaby config type itself seems to not be working properly (the UI feels stuck and it takes quite a few seconds for me to regain control of the UI and being able to cancel the operation or move to another config type).

![CleanShot 2024-11-11 at 09 06 23@2x](https://github.com/user-attachments/assets/27e9dd5b-2928-49e7-a2b8-be47f54a2145)

![CleanShot 2024-11-11 at 09 09 18@2x](https://github.com/user-attachments/assets/c563e0fe-5cf0-4ccb-9991-d9b56c7257ca)

### Wallaby diagnostics report

I'm not able to share any report because I'm not able to run Wallaby in the first place.

**Comment by smcenlly** [comment]
Can you please provide us with your WebStorm version?

Can you also please provide us with your WebStorm logs, we're looking for any Wallaby specific errors? You can access the logs in WebStorm using `Help->Show Log in Finder`.

**Comment by matchatype** [comment]
- WebStorm version: 2024.3 RC (2024.2.4 behaves the same way)
- Wallaby plugin version: 1.0.309

I emailed the logs requested.

**Comment by smcenlly** [comment]
Thanks for providing the logs; this helped us see what was going on.

Interestingly, we didn't have the problem yesterday in 2024.2.4 but we did have the problem in 2024.3.

There was a breaking change in the latest version that has been fixed in the Wallaby for JetBrains plugin `v1.0.311`. Please update to the latest version of the Wallaby plugin, it should fix your problem.
