### ISSUE TITLE
Where is Quokka V2?

### ISSUE THREAD

**Issue by DarrellDenlinger** [wallabyjs/public#3436]
The Wallaby/Quokka website says that Quokka V2 is out and is the default version. I don't see it anywhere. All I can get for a VS Code extension is V1.0

**Comment by smcenlly** [comment]
Please note that for technical reasons, the version of the extension still starts with `v1.0`.

Quokka v2 was released on the 22nd of November, 2024 from `v1.0.664` (for VS Code). If you are using `v1.0.664+` then you should see Quokka v2 in VS Code instead of the older output view.

Please check your Quokka plugin version in VS Code. You will see Quokka v2 functionality after updating to the latest version.
