### ISSUE TITLE
Not rerunning tests in Webstorm when changing basefile

### ISSUE THREAD

**Issue by BraunreutherA** [wallabyjs/public#348]
First thanks for a great tool! 

When I change a test file the tests start to run again. But if I produce an error, for example calling an undefined function the test will fail which is ok. if I change the undefined function back to the working version the tests won't rerun and I hav to restart wallaby which is not as intended. What can I do?

Thanks,
Alex

**Comment by ArtemGovorov** [comment]
Could you please create a small sample with your configuration demonstrating the issue? I can't reproduce the issue on a simple sample:

![w](https://cloud.githubusercontent.com/assets/979966/11327068/c01c4e90-91c6-11e5-8bdb-1ab4332186d9.gif)

**Comment by BraunreutherA** [comment]
Hi, thanks for the fast reply I found out, that I had to kill the worker processes. I'm using sails.js and use the same wallaby config as in this project: https://github.com/bredikhin/sailsjs-mocha-testing-barrels-fixtures-example/blob/master/wallaby.js 

So for now it works - just a bit slower. I was using the teardown function to call sails.lower() - maybe you have an answer for this. But if not its okay for the moment :)

**Comment by ArtemGovorov** [comment]
Ok, thanks for the update. Process killing sometimes is the only way (depending on what and how you do in your tests).

My guess is that it didn't work for you because `sails.lower()` is async function, while `teardown` is sync. 

Anyway, I have updated the sample config here - https://github.com/wallabyjs/sailsjs-mocha-testing-barrels-fixtures-example/blob/master/wallaby.js to lower sails in the bootstrap before each run (if the app was created), try running the new config to see if it works for you (without killing node processes).

**Comment by BraunreutherA** [comment]
Wow - that's what I call a great support! It works like a charm :)

**Comment by ArtemGovorov** [comment]
@BraunreutherA Awesome, thanks! :)
