### ISSUE TITLE
Possible issue - Date formatting?

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#351]
I've possibly found an issue, ultimately it's probably something I'm failing to configure. But I'm running some Jasmine tests which essentially are stringifying a date:

    var options = { year: "numeric", month: "short", day: "numeric" };
    console.log(new Date("01/01/2013").toLocaleDateString("en-gb", options));

Running this in Chrome using Jasmine I get the following output `1 Jan 2013`.
If I log this through Wallaby however I get `Tuesday, January 01, 2013`.

I'd like to get Wallaby matching Jasmine, I've read that I can change the environment variables for `PhantomJS` but the obvious thing to look at is the locale using the `TZ` variable - but I'm already specifying the locale as `en-gb`. So I'm a little unsure what I need to re-configure?

**Comment by ArtemGovorov** [comment]
The issue here is that `toLocaleDateString()` depends on the browser's implementation and also depends on the platform.

PhantomJs 1.9.x (which wallaby uses by default), doesn't fully support it, on Windows it outputs `Tuesday, January 01, 2013`, on my OSX it outputs `1/1/2013`. 

PhantomJs 2 (which you may use [with wallaby.js as well](http://wallabyjs.com/docs/integration/phantomjs2.html)) outputs `1 January 2013`, 

Safari also outputs `1 January 2013`.

So it boils down to what you're trying to test. If you'd like to test that your dates look like you expect in Chrome (but not in Safari for example), then you may add some browser detection in your tests, like
```
if (chrome){ 
// or !phantomJs or isWallaby, etc. it's just a pseudo code
  it('chrome specific test', function() {

  })
}
```

Another solution is to add `toLocaleDateString` override/polyfill in wallaby bootstrap function that will work the way you expect it to.

In a long term, we plan to [support real browsers](https://github.com/wallabyjs/public/issues/29), so that you'll be able to select where you'd like to run your tests in, and it may address the issue as well.
