### ISSUE TITLE
Using Wallaby.js with require-self

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#367]
I wanted to get rid of the various:

```javascript
import Foo from '../../foo.js';
```

and use:

```javascript
import {Foo} from 'my-module';
```

instead. So I used `require-self` npm module, which basically adds in `node_modules` a file named `my-module.js` which just does a `module.exports = require ('..');`. It works like a charm, but not with Wallaby.js (I blogged about it [here](http://code.fitness/post/2015/11/npm-require-self.html)).

I cannot figure out how to configure the files so that I can use the `require-self` trick in my module. See for instance [electrum-store](https://github.com/epsitec-sa/electrum-store/tree/broken-require).

I tried this:

```javascript
    files: [
      {pattern: 'test/test-helper.js'},
      {pattern: 'src/store/**/*.js'},
      {pattern: 'node_modules/electrum-store.js'},
      {pattern: 'src/*.js'}
    ],
```

but Wallaby.js complains with this error message:

> `module.exports = require('..');` &rarr; Error: cannot find module '..'

How should I set up Wallaby.js to get this working?

**Comment by ArtemGovorov** [comment]
Wallaby uses its own [cache of instrumented files, except for `node_modules`](http://wallabyjs.com/docs/intro/troubleshooting.html#39-cannot-find-module-39-or-39-file-not-found-39). 

When you add your `node_modules/electrum-store.js` to the files list, it ends up in the wallaby cache and tries to resolve the required `..` path in there, but the rest of modules are not there, so it fails.

The solution would be to just remove `{pattern: 'node_modules/electrum-store.js'},` from the list.

Please let me know if it works for you.

**Comment by epsitec** [comment]
You are right, it works without including `node_modules/electrum-store.js`.

What I was not aware of, though, is that code imported through `import {Store} from 'electrum-store';` would in fact be my _compiled_ code taken from `lib/...` rather than from `src/...`.

Editing `Store` in the source file no longer produces real-time updates in Wallaby.js.

So in the end, I won't be able to use `require-self` when developing.

**Comment by ArtemGovorov** [comment]
It looks like so. Wallaby.js needs to compile files itself to be able to create source maps, instrument files, etc, to provide the real-time experience.

One of the things I was going to suggest is to include the `node_modules/electrum-store.js` to your files list and rewrite it in the `bootstrap` function to `require` your `src` folder:

``` JavaScript
 bootstrap: function (w) {

      var srcIndexPath = require('path').join(w.projectCacheDir, 'src', 'index.js');
      require('fs').writeFileSync(
        require('path').join(w.projectCacheDir, 'node_modules', 'electrum-store.js'),
        'module.exports = require("' + srcIndexPath + '");');
...
```

But it's not working, because it creates a circular reference: test files require `src/index`, `src/index` requires `./store/store.js`, `./store/store.js` requires `electrum-store.js`, which is if mapped to  `src/index` produces a circular reference. Your current setup works because your `electrum-store.js` is mapped to `lib/index`.

So the major issue affecting wallaby.js is that with your current code structure, it doesn't seem possible to run code purely from the `src` folder from your tests.

**Comment by epsitec** [comment]
Thank you for your time.

**Comment by ArtemGovorov** [comment]
Unless there's a way to break the circular reference, which I don't see a clean way to do. Perhaps some hack with copying `src/index` file from the `bootstrap` and also `require`-ing the copy from tests (by [patching the require function](https://github.com/wallabyjs/public/issues/362#issuecomment-160861716) and making it require the index file copy if requested from tests) can do the trick.

**Comment by epsitec** [comment]
The hacks you mention are far over my head ;-)

**Comment by epsitec** [comment]
For the curious, see https://github.com/wallabyjs/public/issues/453 which provides a working solution of the `require` patch.
