### ISSUE TITLE
es6-modules error "can't find variable module"

### ISSUE THREAD

**Issue by Gregoor** [wallabyjs/public#37]
First of all, thanks spyjs and wallabyjs! I'm really impressed by your work.

I started using wallaby with babel, which works fine (the examples helped) but now I'm also trying to use the es6 module style but wallaby does not seem to like it, giving me the following error: ` "can't find variable module"`.

Is there any way around this or do we just have to wait until es6-modules are a native part of io/node?

**Comment by ArtemGovorov** [comment]
Thanks a lot, I'm glad you like spy-js and wallaby.js!
Does the same code (transpiled by babel) work in browser without wallaby.js? In any case, could you please provide a simple sample (source file and wallaby config) that doesn't work?

**Comment by Gregoor** [comment]
Quick response :) Thanks for taking the time, I hope I didn't make a trivial mistake. I tried to boil it down to the bare minimum: https://github.com/Gregoor/wallaby-test

**Comment by ArtemGovorov** [comment]
Thanks for creating the repo!
Have sent you a pull request to the repository https://github.com/Gregoor/wallaby-test/pull/1
The main show stopper was that wallaby is using browser environment by default, to switch to node `env.type` had to be set, more options described here - https://github.com/wallabyjs/public#environment-setting
Feel free to close the issue if it works for you.

**Comment by Gregoor** [comment]
Thank you for the awesome support, it works now :)

Out of interest, why does it work without env in [this case](https://github.com/wallabyjs/wallaby-es6-sample/blob/master/wallaby-babel.js)?

**Comment by ArtemGovorov** [comment]
By default (without `env.type: 'node'`) wallaby.js is using PhantomJs to run tests. In [that case](https://github.com/wallabyjs/wallaby-es6-sample/blob/master/wallaby-babel.js) it works because transpiled result works fine in browser environment (PhantomJs). But when you start using modules, babel by default transforms them to CommonJs format, that is not supported by browser (PhantomJs). In order to work in browser, babel preprocessor needs to be configured to use [AMD or custom formatter](https://babeljs.io/docs/usage/modules/), depending on what is used in your browser code. 

So, for example, If you are running browser tests and using require.js, then AMD would be used. In wallaby.js you can use both, babel preprocessor to transform your code to AMD and [require.js support](https://github.com/wallabyjs/wallaby-requirejs-sample).

**Comment by Gregoor** [comment]
That does make sense, I get a little confused with all those different enviroments and module loaders.

Once again, thanks for all the detailed help and the awesome tools. I can't remember the last time writing test has been fun. Keep it up :)
