### ISSUE TITLE
Issue in testing React-redux-es6-webpack application with wallaby.js

### ISSUE THREAD

**Issue by dixyxavier** [wallabyjs/public#370]
How should I configure and write test cases for React-redux-es6-webpack application with wallaby.js. Please specify how to run the test cases also. I use visual studio code as editor

I have gone through https://github.com/wallabyjs/wallaby-webpack-es6-react and http://dm.gl/2015/03/11/wallaby-react/ But it throws error. I think I missed something in configuration.  The following isthe url to repo. https://github.com/dixyxavier/tada-todo-sample
Please help me out

Thanks in advance :)

It doesn't read react module. 

![image](https://cloud.githubusercontent.com/assets/7081634/11621447/0e4ee926-9ce2-11e5-9499-81bbb8083e5b.png)
![image](https://cloud.githubusercontent.com/assets/7081634/11621449/1472ed16-9ce2-11e5-931c-e675c1ded976.png)
![image](https://cloud.githubusercontent.com/assets/7081634/11621457/27d89d92-9ce2-11e5-9ab2-25e672e934b1.png)
![image](https://cloud.githubusercontent.com/assets/7081634/11621423/c842f4e0-9ce1-11e5-9fee-bab9f68ad947.png)
![image](https://cloud.githubusercontent.com/assets/7081634/11621354/35592a8c-9ce1-11e5-8144-3877607de5f1.png)

**Comment by ArtemGovorov** [comment]
None of the errors on your screenshots are wallaby.js related. In fact, it doesn't look like you've even started wallaby.js.

Since you're using TypeScript, I'd suggest you [install tsd](https://github.com/DefinitelyTyped/tsd), then install all the typings for the modules that you use. Then it perhaps makes sense to rename `.ts` files to `.tsx` since you use JSX inside them. Then you need to configure your webpack to actually compile your TypeScript files so that your `node server` actually works. Then you need to install a few missing modules, like `babel-preset-stage-2`, `typescript`, `react-tools`, `wallaby-webpack`, etc.

Once you get your project working without wallaby.js, you may start with [this tutorial](http://wallabyjs.com/docs/intro/get-started-vscode.html) to see how to start wallaby.js and how to troubleshoot it. It may be worth looking into [TypeScript compiler notes](http://wallabyjs.com/docs/integration/typescript.html) because you'll need to configure the compiler as you're using TypeScript/TSX. BTW, the whole compilers section is missing in your wallaby config, so you'll need to add it as well:
``` JavaScript
    compilers: {
      '**/*.js*': babelCompiler,
      //... also typeScript compiler configuration is required
      }
```

Once you have your project running without wallaby and when running wallaby you start getting any wallaby.js specific errors in your "Wallaby Console", please let me know, so I'll get the latest version of your sample project and we'll take it from there.
