### ISSUE TITLE
Configure typescript/angular2/ionic2 to work with wallabyjs

### ISSUE THREAD

**Issue by nampdn** [wallabyjs/public#379]
Hi, I'm new to wallabyjs. I was very confused. Trying to config ionic2 to work with wallaby.js. (written by typescript, angular2 and webpack).

The basic structure of ionic2 like [this](https://github.com/driftyco/ionic-conference-app/tree/typescript) project.

Here is my wallaby.json file:

```json
{
  "files": [
    "www/app/**/*.ts",
    "www/app/*.ts"
  ],

  "tests": [
    "tests/*Spec.ts"
  ]
}
```

It has error when run with webstorm like this:

>ReferenceError: Can't find variable: require
	at www/app/about/about.ts:1

This is the about.ts file:

```typescript
import {Page} from 'ionic-framework/ionic';

@Page({
    templateUrl: 'app/about/about.html'
})

export class AboutPage{
    constructor(){

    }
}
```

Please help me to solve this.

**Comment by ArtemGovorov** [comment]
> ReferenceError: Can't find variable: require

It means that while TS compiler has compiled ES6 `import` to CommonJs, but browser environment has no idea about what `require` is, it's supposed to be `webpack`-ed. 

The project that you have referenced is using webpack, so I suggest looking into the [wallaby.js doc section on how to configure Webpack](http://wallabyjs.com/docs/integration/webpack.html).

I'm also not sure how Ionic works (specifically how does it load templates), as I didn't have much experience with it, but you may also need to [inline your templates](https://github.com/wallabyjs/wallaby-typescript-angular-seed/blob/master/wallaby.js#L34).

P.S. Note that these 2 lines in your config are excessive, as the first pattern includes the second one:
```
"www/app/**/*.ts",
"www/app/*.ts"
```

**Comment by nampdn** [comment]
Hi, I have commit the demo repo of my project and add you as a collaborator.
Maybe you don't have to run it, run `npm install` and wallaby.js on the Webstorm IDE.
But if you want to run it on the browser. Hit this npm command: `npm install -g ionic@beta`
I think a lot of ionic developer need your tool. Please help me to configure it.

**Comment by ArtemGovorov** [comment]
@nampdn Sure, let me know if you have any questions/issues with configuring wallaby after reading the doc section on Webpack and trying to configure wallaby like described there.

**Comment by nampdn** [comment]
Hi, I follow this demo project, install all of its dependency, now it works great!
But can you should me what are the limitation of trial mode / purchased mode?
And where I can get more function to test, eg: `to`, `equal`, `it`, .. (Sorry, because I'm not familiar with testing)

**Comment by ArtemGovorov** [comment]
@nampdn In trial mode wallaby.js will periodically stop and require you to restart your editor to keep working with it.

`it`, `equal`, `to`, etc. come from testing framework/assertion library. Wallaby.js supports a few testing frameworks, like [jasmine and mocha](http://wallabyjs.com/docs/integration/overview.html#supported-testing-frameworks). You may start with [jasmine](http://jasmine.github.io/2.4/introduction.html) or [mocha](https://mochajs.org/). Jasmine has built-in assertions, if you choose to use mocha you may use any assertion library, for example [chai](http://chaijs.com/).

**Comment by nampdn** [comment]
Thanks for quickly response. I will purchase it as soon as possible.
Now, I'm using `chai`, how can I use other framework like jasmine and mocha?

**Comment by ArtemGovorov** [comment]
You may set the framework via the [testFramework setting](http://wallabyjs.com/docs/config/overview.html#testing-framework-setting).

**Comment by nampdn** [comment]
Thanks!

**Comment by Barryrowe** [comment]
Hey @nampdn is your demo repo live with your changes after you got this working? The wallaby config looks like it just contains files and tests, and I don't see wallaby-webpack in your dependencies at all. Just curious because it sounds like you've solved a problem we've been banging our heads against all morning, and I'd love to see how you got this working.

**Comment by ArtemGovorov** [comment]
@Barryrowe do you have a sample repo with some tests and wallaby config (that's not working for you) so I may have look into? Happy to help with the configuration.

**Comment by Barryrowe** [comment]
@ArtemGovorov Working on getting that up now

**Comment by Barryrowe** [comment]
@ArtemGovorov  Here is the repo [ng2-introduction](https://github.com/Barryrowe/ng2-introduction) 

currently the error I'm getting is: 
​TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')
on the app.ts line 1 import, which is 'angular2/core'

I guess we're expecting webpack to build the require/import chain, but I'm not sure how we tell it to properly do so.

**Comment by nampdn** [comment]
@Barryrowe I solved my problem but I haven't committed it to my repo yet. You can follow [this repo](https://github.com/slikts/wallaby-webpack-sample) which I followed to. Read its dependency and install all of it does the trick for me.

**Comment by Barryrowe** [comment]
@nampdn  Thanks. That's the repo we've been referencing, but still having problems.

**Comment by nampdn** [comment]
@Barryrowe  I have updated my package.json and wallaby.js file. Please check it out, may it help you.

**Comment by Barryrowe** [comment]
@nampdn I think I see the difference. Your tests aren't currently requiring any classes marked as Components, which I believe is where our issue comes up.

If I comment out the import of our main component the basic tests run, but it's the angular2 dependencies that start causing things to fail.

**Comment by nampdn** [comment]
That's the things I haven't touched to. Although I really want to test with @Component and other UI elements.

**Comment by ArtemGovorov** [comment]
@Barryrowe Sent you [the pull request](https://github.com/Barryrowe/ng2-introduction/pull/1). PhantomJs doesn't support ES6 Map that angular is using internally (hence the `TypeError: 'undefined' is not a constructor (evaluating 'new exports.Map()')` error), so I have referenced the polyfill to make it work.

Please note that you may use any other polyfill instead of the babel one (it just has to support `Function.prototype.bind` if you are using the default PhantomJs, or use [PhantomJs2](http://wallabyjs.com/docs/integration/phantomjs2.html) in which case on polyfills for some ES6 features are required but not the `Function.prototype.bind` as it's supported by Phantom2). You may  even remove the polyfill and add individual polyfills (for Map and whatever else is required) right in the `bootstrap` function if you like.

Please also note that if you're intending to support browsers that do not support ES6 in your app, they will have the exact same error. So you may need to include the polyfill in your prod bundle (or find out what's the recommendation from angular docs on the matter).

**Comment by Barryrowe** [comment]
Thanks @ArtemGovorov, that makes sense. We'll make sure to get our webpack flow right for publishing! You're providing the best support for a product I've seen in a long while.

**Comment by btroncone** [comment]
@ArtemGovorov The previous config is working for basic components but I am running into issues when using Angular 2 'beforeEachProviders' in order to provide mock dependencies. The error 'TypeError: 'null' is not an object (evaluating 'dom_adapter_1.DOM.getXHR')' is being thrown. 

Initially I expected it to be something wrong with my syntax but I swapped out examples working with Karma from https://github.com/AngularClass/angular2-webpack-starter and ran with Wallaby and am receiving the same errors. An example failing file can be found here: https://github.com/AngularClass/angular2-webpack-starter/blob/master/src/app/home/home.spec.ts

Any direction you can give would be appreciated, thanks!

**Comment by ArtemGovorov** [comment]
@btroncone I have created [the working wallaby.js config](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js) for the angular2-webpack-starter project.

In the this project there is [this file](https://github.com/AngularClass/angular2-webpack-starter/blob/master/spec-bundle.js) that loads required dependencies for tests and [this call specifically](https://github.com/AngularClass/angular2-webpack-starter/blob/master/spec-bundle.js#L45) is required to get rid of the `TypeError: 'null' is not an object (evaluating 'dom_adapter_1.DOM.getXHR')` error. 

You need to load the file in wallaby.js as well. It's not just a script that you may include into the `files` list with `load: true`, because the file `require`-s things so has to be `webpack`-ed. To load the file with webpack before tests, you may list it in the [`entryPatterns`](http://wallabyjs.com/docs/integration/webpack.html#entry-patterns) configuration option for wallaby-webpack. Please note, that as described in the docs, [entry patterns, including tests, are `.js` files](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js#L4), despite the fact that tests are `.ts` files, because by the time wallaby loads them, they are already compiled.

A couple more notes:
- I also had to add webpack config for loading html/css, because there are used it tests.
- I have updated the wallaby-webpack package to fix the shared cache issue, so please **update the wallaby-webpack package to 0.0.11 for your project**.
- `spec-bundle.js` file contains some code that wallaby doesn't need, it's these statements:
``` JavaScript
var testContext = require.context('./test', true, /\.spec\.ts/);
var appContext = require.context('./src', true, /\.spec\.ts/);
...
appContext.keys().forEach(appContext);
testContext.keys().forEach(testContext);
```
They don't seem to be breaking anything in wallaby, but if you find out that they are breaking something, you may conditionally exclude them (with `if (!global.wallaby) ...`) or just by creating a copy of the file for wallaby.js without these statements.

**Comment by btroncone** [comment]
@ArtemGovorov Thank you very much for your help, you have been extremely responsive as always. Keep up the outstanding work, we look forward to seeing what's in store for WallabyJS in 2016!
