### ISSUE TITLE
Can not use es6 import statement with jspm and angular2

### ISSUE THREAD

**Issue by duncanhunter** [wallabyjs/public#388]
I have a simple working  angular2/jspm app with wallabyjs. It works fine until I try and use an import statement and the tests go from green to grey squares.

You can see the repo here https://github.com/duncanhunter/angular2-jspm

![image](https://cloud.githubusercontent.com/assets/2058227/12034856/a6004c74-ae8a-11e5-8112-8efe6dffb40a.png)
Figure: Working test runner with no import statement

![image](https://cloud.githubusercontent.com/assets/2058227/12034918/35a19d42-ae8b-11e5-8ffe-e648fd5da022.png)
Figure: Test runner is not working when import statement added

![image](https://cloud.githubusercontent.com/assets/2058227/12035010/2b74273a-ae8c-11e5-8386-63efbb11b536.png)
Figure: Another example of the test runner not working with import statement

#### wallaby.js
```javascript
module.exports = function (wallaby) {

    return {
        files: [
            { pattern: 'jspm_packages/system.js', instrument: false },
            { pattern: 'config.js', instrument: false },
            { pattern: 'app/**/*.ts', load: false },
            { pattern: 'app/**/*.spec.ts', ignore: true }
        ],

        tests: [
            { pattern: 'app/**/*.spec.ts', load: true }
        ],

        compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
                emitDecoratorMetadata: true,
                experimentalDecorators: true,
                module: 4
            })
        },

        middleware: (app, express) => {
            app.use('/jspm_packages',
                express.static(
                    require('path').join(__dirname, 'jspm_packages')));
        },

        bootstrap: function (wallaby) {
            wallaby.delayStart();

            var promises = [];
            for (var i = 0, len = wallaby.tests.length; i < len; i++) {
                promises.push(System['import'](wallaby.tests[i].replace(/\.js$/, '')));
            }

            Promise.all(promises).then(function () {
                wallaby.start();
            });
        }
    };
};
```

**Comment by ArtemGovorov** [comment]
Thanks for the repo, have sent you [the pull request](https://github.com/duncanhunter/angular2-jspm/pull/1) with the config fix.

- added polyfills to the `files` list, the very first one is only required for PhantomJs 1.9.8 which is used by default, if you move to [PhantomJs 2](http://wallabyjs.com/docs/integration/phantomjs2.html).
- added html files to the `files` list as they are loaded by your code, so wallaby needs to know about them.
- set `load: false` for tests in your `tests` list, tests are loaded later in the `bootstrap` function, setting [`load: true` makes wallaby to include your tests via script tag](http://wallabyjs.com/docs/config/files.html#file-object) and that's not going to work with system.js.
- in the `bootstrap` function I modified System.js config to serve `.js` files and remove TypeScript loader that you defined for your files in `config.js`. Wallaby.js has its own typeScript compiler configured in your wallaby.js file, so no need to compile anything with System.js loader dynamically.
- (optional) to make error messages be displayed not only in the [Failing Tests](http://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests) output channel, but also in the status bar (when the cursor is on a line with an error), System.js needs to be configured (`scriptLoad: true` in `meta`), like [described in the docs section](http://wallabyjs.com/docs/integration/systemjs.html). In the pull request, I have done it only for specs, because when I do it for `app/*` it stops loading `app.html` file. Not sure how to configure system.js to use `scriptLoad: true` for everything but html files.

I have also recently made some changes to wallaby.js core, please make sure you have the latest core installed. You may find the core version in the Wallaby.js Console output channel when you start it:
<img width="320" alt="vsc_console" src="https://cloud.githubusercontent.com/assets/979966/12045839/6257e71c-aef7-11e5-92ec-afda7b5a9eeb.png">

The latest core version is **1.0.157** at the moment, the core gets updated automatically within a few minutes after wallaby.js is started. If you'd like to force the update, go to your `/users/user_name/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.x/` folder, delete `wallaby` subfolder there and restart your VS Code.

Wallaby.js also logs a lot of useful data (like details of the error with green indicators turing grey, etc.) to the Wallaby Console, you may have a look how to use it in [the docs section](http://wallabyjs.com/docs/intro/get-started-vscode.html#troubleshooting).

Let me know if the pull request works for you.

**Comment by duncanhunter** [comment]
Thank you for both fast help and an awesome product! Pull request worked.

I updated to phantomjs2 and have been able to do some simple tests of an angular component.
