### ISSUE TITLE
Wallabyjs WebPack Typescript Babel

### ISSUE THREAD

**Issue by IcodeNet** [wallabyjs/public#393]
Hi,

I have an issue with setting up wallabyjs.

We have a strange (interim)  configuration where our source files are in ts but the tests still in js.
We use webpack and  babel  and have the following configuration :

    // Wallaby.js configuration for Webpack + TypeScript

    var babel = require('babel-core');
    var webpack = require('webpack');
    var path = require('path');
    var wallabyWebpack = require('wallaby-webpack');
    var config = require('./webpack.config');

    var wallabyPostprocessor = wallabyWebpack(config);

    module.exports = function (wallaby) {
    return {

        files: [
            { pattern: 'node_modules/react-tools/src/test/phantomjs-shims.js', instrument: false },

            // to avoid loading react into each test manually
            { pattern: 'node_modules/es5-shim/es5-shim.js', instrument: false },
            { pattern: 'node_modules/es5-shim/es5-sham.js', instrument: false },

            { pattern: 'wwwroot/**/*.ts', load: false },
            { pattern: 'wwwroot/tests/**/*Spec.js', ignore: true }
        ],

        tests: [
            { pattern: 'wwwroot/**/*Spec.js', load: true }
        ],

        compilers: {
            'wwwroot/**/*.ts*': wallaby.compilers.typeScript({
                module: 1  // commonjs
                
            }),

            'wwwroot/tests/**/*.js?': wallaby.compilers.babel({
                babel: babel,
                presets: ['es2015']
            })
        },

        testFramework: "jasmine",

        postprocessor: wallabyPostprocessor,

        debug: true,

        bootstrap: function () {
            wallaby.delayStart();

            // required to trigger tests loading
            window.__moduleBundler.loadTests();
        }
    };
    };

When I try to run wallabyjs I get a number of errors in the form:
    Mon, 11 Jan 2016 16:05:28 GMT wallaby:workers Sandbox (active) [mb33f] error: SyntaxError: Parse error

Any help to resolve this would be appreciated.

Thanks

**Comment by ArtemGovorov** [comment]
You may have a look into [the wallaby cache](http://wallabyjs.com/docs/intro/troubleshooting.html#instrumented-code-and-generated-test-page) and the generated sandbox page to see how the files that it tries to load look like to see if you can spot what is wrong. 

I suspect this pattern `wwwroot/tests/**/*.js?` doesn't include your `.js` files so they are still in ES6, hence the parsing error, try changing the pattern to `wwwroot/tests/**/*.js*`.

Please let me know it helps.

**Comment by ArtemGovorov** [comment]
Also, you need to set `load: false` for your tests:
```
{ pattern: 'wwwroot/**/*Spec.js', load: true }
```
because you don't want them to be loaded via script tags because you load them in your `bootstrap` function and don't need the line in your `bootstrap` function:
```
wallaby.delayStart();
```
(it allows to do something async before starting tests and then call `wallaby.start();` to run tests, but you're not doing anything async in your `bootstrap` function, so no need to delay the test run).

**Comment by ArtemGovorov** [comment]
One more thing, when you load your webpack config: `var config = require('./webpack.config');`, make sure you remove unnecessary loaders, such as babel loader (because wallaby uses its own compiler so you don't need the webpack one), and other settings that wallaby doesn't need, from the object. Perhaps it's even easier to start with passing an empty object and then add things that you need. You may read more about [webpack configuration for wallaby in the docs section](http://wallabyjs.com/docs/integration/webpack.html).

**Comment by IcodeNet** [comment]
Thanks Artem. 
I will give it a go.

**Comment by ArtemGovorov** [comment]
@IcodeNet Closing the issue for now, please let me know if the solution didn't work for you.
