### ISSUE TITLE
Unable to determine why "Cannot find module ..." 

### ISSUE THREAD

**Issue by david-m-forster** [wallabyjs/public#396]
Configured wallaby.js to use commonjs but when I start wallaby from Visual Studio I am unable to get past the following error:

    ​​​​​Error: Cannot find module 'C:\Users\david\AppData\Local\Temp\.wallaby\projects\9xD9iczjJFRSUAPsANmEAkmg64=\cache\instrumented\test\src\UtilTests.js'

this occurs when parsing the test entry point: _main.js
```
require('../../src/Common/Polyfills.js')();

// create any mocks or stubs here, prefix with 'Mock' or 'Stub'
var Util = require('../../src/Common/Util.js')();
var TestCommonStrings = require('./Common/Strings.js')(Util);
require('../src/UtilTests.js')(TestCommonStrings, Util);
```
if I look at this folder location (i.e wallaby cache) the file does indeed exist. some times the line before (i.e the one starting with: var TestCommonStrings =) will fail with the same type of error.

My wallaby config file is as follows:
```
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({
    // browserify options, such as
    entry: 'test/src/_main.js'
  }
  // you may also pass an initializer function to chain other
  // browserify options, such as transformers
  // , b => b.exclude('mkdirp').transform(require('babelify'))

);

module.exports = function () {
  return {
    // set `load: false` to all of the browserified source files and tests,
    // as they should not be loaded in browser,
    // their browserified versions will be loaded instead
    files: [
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'lib/**/*.js', load: false }
    ],

    tests: [
      { pattern: 'test/src/**/*.js', load: false }
    ],

    testFramework: 'mocha',

    postprocessor: wallabyPostprocessor,

    debug: true,

    bootstrap: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    }
  };
};
```
Any ideas greatly appreciated
David

**Comment by ArtemGovorov** [comment]
Only test files (files with `describe`/`it`) should be listed in the `tests` list. As I can see from your config and `_main.js` file, at least 3 files in the `tests` don't look like test files: `test/src/_main.js`, `test/src/UtilTests.js`, `test/src/Common/Strings.js`

Try:
``` JavaScript
files: [
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'lib/**/*.js', load: false },
      { pattern: 'test/src/_main.js', load: false },
      { pattern: 'test/src/UtilTests.js', load: false },
      { pattern: 'test/src/Common/Strings.js', load: false }
    ],

    tests: [
      { pattern: 'test/src/**/*.js', load: false },
      { pattern: 'test/src/_main.js', ignore: true },
      { pattern: 'test/src/UtilTests.js', ignore: true },
      { pattern: 'test/src/Common/Strings.js', ignore: true }
    ],
```

If there're some other files in `tests` that are not test files, please do the same. Perhaps your test file names satisfy some pattern, like `*Spec.js` or something like that, so it may make sense to adjust your main tests pattern to reflect that and add a pattern like `{ pattern: 'test/src/**/*!(Spec).js', load: false },` to  your `files` list (instead of listing exclusions one by one).

Please let me know if it helps.

**Comment by ArtemGovorov** [comment]
BTW, thanks for providing your wallaby config and the `_main.js` file content, it's really helpful for understanding why the error occurs.

**Comment by david-m-forster** [comment]
Great, thanks for the quick response. Based on what you said I have a slightly better understanding of how the config file works. With that in mind I was about to rework the config as follows:

```
var wallabify = require('wallabify');
var wallabyPostprocessor = wallabify({

});

module.exports = function () {
  return {
    // set `load: false` to all of the browserified source files and tests,
    // as they should not be loaded in browser,
    // their browserified versions will be loaded instead
    files: [
      { pattern: 'src/**/*.js', load: false },
      { pattern: 'lib/**/*.js', load: false },
      { pattern: '!test/src/**/*Tests.js', load: false }
    ],

    tests: [
      { pattern: 'test/src/**/*Tests.js', load: false }
    ],

    testFramework: 'mocha',

    postprocessor: wallabyPostprocessor,

    debug: true,

    bootstrap: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests();
    }
  };
};
```
as you can see, the only files that have describe() tests in them end in "Tests.js" otherwise all files should be included.

All good but `test/src/_main.js` is not executed. After some further investigation I realized that our test pattern does not work with wallaby. The main problem is we have a single entry page that composes the entire dependency tree and then injects the dependent components into the test.

Some background:
We use a dependency injection pattern such that each require returns a function that expects as arguments, instances of other objects. You can see in the original posts _main.js that UtilTests.js is required then executed with the components that depend upon it - namely TestCommonStrings and Util. UtilTests.js looks like this:
```
module.exports = function Test_UtilTests_Module (
    TestCommonStrings,
    Util
) {
    describe('Type assertion tests', function () {
        it('should assert string types', function () {
            expect(Util.isType('foobar', 'string')).to.be(true);
        });
        // lines removed for brevity
    });
    // lines removed for brevity
};
```

So we need `test/src/_main.js` to execute the tests as it knows how to compose and call the test's returned require function with the appropriate arguments (dependencies). 

I think we will need to restructure our unit tests to make each test file a browserify "entry page". Unfortunately we have a few hundred test files. Good news is that it is doable.

**Comment by ArtemGovorov** [comment]
@david-m-forster got it, thanks for the update. Yeah, with the current structure when test files can only be executed by some common entry point, it will not be possible to leverage wallaby.js killer features. For example, it will not be able to execute only affected tests or run tests in parallel, because all of the tests depend on a single file. So the only way for any runner to run your tests is to run all of them.

One way you may make your test files not exactly self-sufficient, but less verbose is to do something like:
``` JavaScript
window.Util = require('../../src/Common/Util.js')();
window.TestCommonStrings = require('./Common/Strings.js')(Util);
```
in your `_main.js` file and then just use the globals in test:

``` JavaScript
describe('Type assertion tests', function () {
        it('should assert string types', function () {
            expect(Util.isType('foobar', 'string')).to.be(true);
        });
    });
```

That would work for some global-like dependencies. Test specific dependencies may be required right from test files. And if there're not too many test specific dependencies, then the change should be pretty straightforward.

Either way, please let me know how you end up re-structuring your tests if you decide to do so. Happy to help if you hit any bumps configuring wallaby for the new structure.

**Comment by david-m-forster** [comment]
good point about performance - we will definitely need to revisit out build process.

attaching the dependencies to the windows object is a good idea. i created a new module and export them via a public interface but the window-global approach reduces the refactor work a little.

thanks for your help. as an ncrunch user I am really happy to see wallabyjs in action. we can now start reviewing where we need to get better unit test coverage. Cheers
