### ISSUE TITLE
Guide for beginners how to use WallabyJS with Sinon

### ISSUE THREAD

**Issue by MikeyMCZ** [wallabyjs/public#405]
Hello.
I'm trying to make WallabyJS to work on our project. However I have issues with using Sinon in our tests. I have created simplest possible project that sort-of represents our tests. You can find it on GitHub and maybe it can be used as a reference for others who are trying to do the same in the future.
[wallabyjs-sinon-example](https://github.com/MikeyMCZ/wallabyjs-sinon-example)
When I try to run the tests from the example I'm getting error *Can't find variable: sinon*. I don't mind to use any test framework. And I'm trying to run it from Visual Studio Code.
If possible can someone point me what is wrong, what to add or what needs to be changed so I can get it working?
Thank you.

**Comment by ArtemGovorov** [comment]
Hello,
Thanks for the project. You need to have sinon somewhere in your project and need to add it in your `files` list so it gets loaded by wallaby.js. For example, if you add `sinon.js` in your `lib` folder, you may add 
``` JavaScript
{ pattern: 'lib/sinon.js', instrument: false },
```
to your `files` list and it should work for you.

**Comment by MikeyMCZ** [comment]
It is still failing (changes are pushed to the project):
- when default test framework (Jasmine) is used - *Can't find variable: sinon*
- when switched to *Mocha* framework I get - *"before each" hook: Can't find variable: sinon*

**Comment by ArtemGovorov** [comment]
`sinon.js` has to be in the list before `require.js` because it has to be loaded first, otherwise you'll have to require it with require.js but it looks like you are using it as global in your tests. So just make the `{ pattern: 'lib/sinon.js', instrument: false },` line to be the first line in the `files` list.

Another issue I have noticed is that your `EventHandler` module doesn't return anything, but it's not sinon related, and your failing tests will report about anyway.

**Comment by MikeyMCZ** [comment]
Nice! **Thank you very much** and sorry for beginner's questions. Example in GH was updated.

**Comment by ArtemGovorov** [comment]
Awesome, glad it helped. Please feel free to ask any questions, happy to help.
