### ISSUE TITLE
Test failing with Wallaby but not Karma

### ISSUE THREAD

**Issue by ccoffey** [wallabyjs/public#413]
I have found a test which fails using Wallaby but not Karma. I have [forked calculator-sample](
https://github.com/ccoffey/calculator-sample/commit/142999af63f4aa4553e6089a95a6960a2f1525a4) to create a minimum not working example.

If you run ```karma start``` you will see 

```PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 10 of 10 SUCCESS (0.008 secs / 0.009 secs)```

If you run WallabyJs you will see

```test/calculatorSpec.js calculator model should set head title 3 ms
Expected '' to be 'hello'.
at test/calculatorSpec.js:10:4```

Any help would be appreciated!

**Comment by ArtemGovorov** [comment]
Nice find, thanks for the report! Wallaby.js sandbox page just didn't have a title tag at all. A workaround would be to create a tile before trying t set it. Anyway, the issue is fixed and the updated core (v1.0.161) is published, should be updated automatically in a few minutes. 

If you need the update immediately, please let me know your IDE/editor and I'll describe how to force the update.

**Comment by ccoffey** [comment]
Wow, that was quick, thanks for fixing this! I am using atom.

**Comment by ArtemGovorov** [comment]
Try restarting wallaby.js now. If the core is not updated after the restart, then close Atom, open your `user/.atom/packages/atom-wallaby/` folder, delete `wallaby` subfolder there and start Atom.

**Comment by ccoffey** [comment]
That worked, thank you very much
