### ISSUE TITLE
Does not seem to run with more than one worker.

### ISSUE THREAD

**Issue by pietvanzoen** [wallabyjs/public#417]
I'm using Wallaby in Rubymine on a jasmine/requirejs testing setup. As best as I can tell wallaby is running all the specs with just one worker. When I log the workerId as illustrated in the docs it logs as `undefined`.

```
bootstrap: function (wallaby) {
	console.log('Setup');
	console.log('Current worker id: ' + wallaby.workerId);
	console.log('Current session id: ' + wallaby.sessionId);
},
```

Is there a way to confirm how many workers are being used? Even if I manually set the number of workers it only seems to run with one.

Any advice would be appreciated.

**Comment by ArtemGovorov** [comment]
Your observation is totally correct. For require.js specifically wallaby.js is only using 1 worker to run tests. It may change in future, you'll not have to configure anything to make it work.

[`workerId` and `sessionId`](http://wallabyjs.com/docs/config/bootstrap.html) are only available in node.js environment, not in the browser environment, that's why you see undefined.

**Comment by ArtemGovorov** [comment]
BTW, it only affects the initial run and often not really significantly. During incremental runs (that obviously happen much more frequently) because of the nature of typical changes and the fact that wallaby only runs affected tests, only one worker is used most of the time regardless whether it's require.js/webpack/browserify/plain script tags.

**Comment by pietvanzoen** [comment]
Ok thanks for the info! Additional workers for the initial run would definitely be handy. With 2.5k tests in our app the initial run takes around 1.5 minutes. For low level helpers that are included in most of the app the affected tests can include a significant number of tests which take a while on the one worker.

Everything else about wallaby is fantastic so far. Good job!

**Comment by ArtemGovorov** [comment]
Thanks!

> With 2.5k tests in our app the initial run takes around 1.5 minutes.

Yeah, in this case parallel run may certainly help. We have the task in our backlog, I'll update the issue once it's ready.

> When making changes to low level helpers that are included in most of the app the affected tests

Agreed. Though such things don't tend to change much after they've been written and tested, do they?
