### ISSUE TITLE
Wallaby not reporting warning/error when React required prop is missing

### ISSUE THREAD

**Issue by ccoffey** [wallabyjs/public#425]
For example when I omit the required prop *pear* in a test for the component *PostPreview* and run my tests with Karma I get the following output.

<img width="873" alt="screen shot 2016-01-27 at 12 14 44 pm" src="https://cloud.githubusercontent.com/assets/456400/12613141/9cc9765a-c4ef-11e5-8270-43d67b09806e.png">

Wallaby does not report the issue even with the flag ```debug=true```.

<img width="982" alt="screen shot 2016-01-27 at 12 15 48 pm" src="https://cloud.githubusercontent.com/assets/456400/12613171/c22be450-c4ef-11e5-8239-f0161459c5ff.png">

**Comment by ArtemGovorov** [comment]
Could you please create a sample where I could reproduce it? You may use [this sample](https://github.com/wallabyjs/wallaby-react-component) as a starting point.

**Comment by ccoffey** [comment]
I forked [wallaby-react-component](https://github.com/ccoffey/wallaby-react-component/commit/81d76a408a56f8c551c55392304b3abe986cf4cc) to make a minimum working example. However, I didn't have enough time to add a *karma.conf.js* to show that Karma will log the following error/warning when any test creates a UserProfile without providing the required prop *requiredBool*.

```ERROR: 'Warning: Failed propType: Required prop `requiredBool` was not specified in `UserProfile````

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

Apparently it's not an error (as an uncaught exception or a failed assertion), but just a `console.warn` or `console.error` from react.

Wallaby doesn't report those in the Failing Tests panel (because these are not failing tests). If some of the tests (affected by those messages) are failing, then you may see the logged data for **those specific tests** (unlike karma that just dumps those messages without a relation to any test).

![atm](https://cloud.githubusercontent.com/assets/979966/12637794/a65278e4-c5e3-11e5-8341-8a5fbef30406.gif)

You may also show related log output for any covered line by clicking a coverage indicator for the line in the gutter or invoking `Show Line Tests` command.

Now I understand that this is not helpful in your scenario where you'd like to be able not to miss those errors. I have to think more about the way to display those for you without affecting those who don't care about console output (even if it's `console.error`) and would like to see anything unless actual tests are failing. The issue is that wallaby doesn't have a console where the output from all tests is displayed. Probably except the one in Developer Tools, would it work for you if those messages were displayed there as errors?

**Comment by ccoffey** [comment]
>You may also show related log output for any covered line by clicking a coverage indicator for the line in the gutter or invoking Show Line Tests command.

These are the kinds of errors I really want to catch as I'm developing. 

>I have to think more about the way to display those for you without affecting those who don't care about console output (even if it's console.error) and would like to see anything unless actual tests are failing

How about a config option *logLevel*? The default could be to not show console.error and a more sensitive setting could display console.error in the Wallaby console?

>The issue is that wallaby doesn't have a console where the output from all tests is displayed. Probably except the one in Developer Tools, would it work for you if those messages were displayed there as errors?

Not really, I am not in the habit of keeping Developer Tools open all of the time. I really think it makes more sense to have a single console where all development related messages are displayed.

**Comment by ArtemGovorov** [comment]
> How about a config option logLevel? The default could be to not show console.error and a more sensitive setting could display console.error in the Wallaby console?

This could work. I can even make those tests that cause `console.error` to be displayed as failed when the option is set.

**Comment by ccoffey** [comment]
>This could work. I can even make those tests that cause console.error to be displayed as failed when the option is set.

This would be really great. In my mind these tests should really be failing! In fact its been a bit of a pain with Karma trying to figure out which tests are actually creating React elements with missing props. If you look at the original output I posted you will see that no test name, filename or line number is printed with the errors.

**Comment by ArtemGovorov** [comment]
[The `reportConsoleErrorAsError` setting](http://wallabyjs.com/docs/config/overview.html#report-console-error-as-test-run-error) is added in core v1.0.168.
