### ISSUE TITLE
SublimeText 3: Gutter status icons hidden under those from other plugins

### ISSUE THREAD

**Issue by JamesHenry** [wallabyjs/public#436]
I have never written a Sublime package before, so I am not sure if you can even do anything about this, but I thought I would report it nonetheless...

I spent a while trying to debug why I was not getting status icons in the gutter of ST3, despite having feedback in the console that my tests were running, and it turned out it was because the GitGutter plugin's (general title of the issue is just an assumption that this will come up in other similar plugins) git diff icons were taking precedence and being shown instead.

**Comment by ArtemGovorov** [comment]
Thanks for the investigation and for the report. We'll have a look into how to fix it.

**Comment by ArtemGovorov** [comment]
So in Sublime Text it's not possible to have multiple gutters, and one has to choose what icons from what plugin to see. There's [this long discussion](https://github.com/jisaacks/GitGutter/issues/113) in the GitGutter repo and there's a solution to make GutGutter not to overwrite the icons:

- create `GitGutter.sublime-settings` text files,
- paste the following content there:
```
{
  // Do not set GitGutter icons in these regions
  // Useful for making sure GitGutter does not override other
  // regions, (e.g. Bookmarks, Linter/BracketHighlighter icons.)
  "protected_regions": ["wallaby_state1", 
                                    "wallaby_state2",
                                    "wallaby_state3",
                                    "wallaby_state4",
                                    "wallaby_state5"]
}
```
- save the file to your Sublime installation folder + `Packages/User/` (or `Data/Packages/User/` if you're on Windows) subfolder.

We will also add a command to toggle wallaby indicators visibility, so that one may use/see other plugins icons.

**Comment by JamesHenry** [comment]
Thanks a lot for looking it that and for providing the workaround!

**Comment by PWKad** [comment]
You should add a link to this in the sublime installation walk through if you can.

**Comment by ArtemGovorov** [comment]
@PWKad Thanks for the suggestion, [done](http://wallabyjs.com/docs/intro/install.html#gitgutter).
