### ISSUE TITLE
VSCode messages to the right of code

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#437]
Do you plan to add more convenient messages (errors and console.log) to VS Code that displayed to the right of code lines like in other IDEs?

**Comment by ArtemGovorov** [comment]
[VS Code API currently doesn't allow to do it](https://code.visualstudio.com/Docs/extensionAPI/vscode-api#TextEditorDecorationType), and because extensions are hosted in a separate process we can not hack into the DOM.

Here is [the feature request](https://github.com/Microsoft/vscode/issues/2521) if you'd like to subscribe to it.

**Comment by andr2** [comment]
@ArtemGovorov thank you. Subscribed!

**Comment by ArtemGovorov** [comment]
The feature is implemented and will be supported from version 1.3 of the VS Code editor. If you'd like to start using the feature now, you may use [the VS Code 1.3 insiders build](https://code.visualstudio.com/insiders).

![vsc](https://cloud.githubusercontent.com/assets/979966/16034451/4171df8a-3255-11e6-824b-bb5d37c37112.gif)
