### ISSUE TITLE
Support Jest Framework

### ISSUE THREAD

**Issue by oscarlgz** [wallabyjs/public#44]
Jest is built on top of Jasmine.

https://facebook.github.io/jest/

**Comment by alexeygolev** [comment]
+1

**Comment by endragor** [comment]
Any milestones here? Would love to try Wallaby.js, but this is the deal breaker.

**Comment by ArtemGovorov** [comment]
I'll have a look into it in the next few days. If it's easy, I'll implement it straight away, if not I'll give the estimates here.

**Comment by ArtemGovorov** [comment]
Started working on supporting Jest, so far so good, simple stuff is working fine.
![jest](https://cloud.githubusercontent.com/assets/979966/7604375/13921a76-f985-11e4-9820-c8a5f2d26858.gif)
Is there some medium-large OSS project with Jest tests you could recommend so that I try to run wallaby on it for testing?

**Comment by hrmoller** [comment]
Could this be an option? https://github.com/kriasoft/react-starter-kit - no tests though...

**Comment by ArtemGovorov** [comment]
Done - https://github.com/wallabyjs/wallaby-jest-sample
