### ISSUE TITLE
Typescript project cannot find some global names

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#446]
Thanks to your help, I've been using this configuration (https://github.com/ReactiveX/RxJS/blob/master/wallaby.js). Today I noticed wallaby displays error messages with current configuration,

> Error: Cannot find global type 'Boolean'.
​  Error: Cannot find global type 'Function'.
​  Error: Cannot find global type 'IArguments'.
​  Error: Cannot find global type 'Number'.
​  Error: Cannot find global type 'Object'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/CoreOperators.ts (91,28): Cannot find name 'Date'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/CoreOperators.ts (92,35): Cannot find name 'Date'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/CoreOperators.ts (91,28): Property 'timeout' of exported interface has or is using private name 'Date'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/CoreOperators.ts (92,35): Property 'timeoutWith' of exported interface has or is using private name 'Date'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/Observable.ts (68,76): Cannot find name 'Function'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/Observable.ts (83,18): Cannot find name 'Function'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/Observable.ts (83,94): Cannot find name 'Function'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/Observable.ts (153,17): Cannot find name 'Error'.
​  Error C:/Users/ojkwon/.vscode/extensions/WallabyJs.wallaby-vscode-1.0.10/projects/ddbe36e3d49e53fc/instrumented/src/Observable.ts (160,44): Property 'call' does not exist on type '(value: T) => void'.
....

that compiler cannot reference some common names. Can I get some help to resolve this? wallaby core version's 1.0.176.

Attached debug log / full error output as reference.

[wallaby_debug.txt](https://github.com/wallabyjs/public/files/122007/wallaby_debug.txt)
[wallaby_error.txt](https://github.com/wallabyjs/public/files/122008/wallaby_error.txt)

**Comment by ArtemGovorov** [comment]
Hi, thanks for the report. The latest version of wallaby.js reads and merges `tsconfig.json` compiler settings and it looks like the `"declaration": true,` from the `tsconfig.json` is causing these errors. Just override it in wallaby config by adding:

```javascript
  compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
      ...
      declaration: false
    })
  },
```
and it should work for you.

**Comment by ArtemGovorov** [comment]
I have also just made it to be `false` by default, so when your gets updated to the v1.0.177, you don't even have to change your config.

**Comment by kwonoj** [comment]
Thanks, just noticed core has been updated and works nicely. I'll close this on my end. Thanks again!

**Comment by ArtemGovorov** [comment]
Great, thanks for the update. 

BTW, we now support `tsconfig.json` format in wallaby settings, so instead of using numeric constants, you may now do:
```javascript
  compilers: {
    '**/*.ts': wallaby.compilers.typeScript({
      module: 'commonjs',
      target: 'es5',
      preserveConstEnums: true
    })
  },
```

**Comment by MartinMason** [comment]
I don't believe this issue is completely closed. I have an Aurelia/JSPM/Typescript project that was working with version 1.0.174. With version 1.0.176 I was getting the same issue as above. Attached is my wallaby.js file that was working with 1.0.174. [wallaby.js](https://files.zenhub.io/56b969621eb6820e435fabb1)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

With debug: true, there's a couple of weird messages presented that might lead to the source of the issue. 

Tue, 09 Feb 2016 04:22:59 GMT wallaby:postprocessor New TypeScript language service is required

And here's where it aborts:
Tue, 09 Feb 2016 04:22:59 GMT wallaby:middleware ENOENT: no such file or directory, open 'C:\Users\Martin\AppData\Local\Temp\.wallaby\projects\bN9jAgq5m17N5nQddBJ7+fgCy00=\cache\instrumented\client\tests\unit\sudokuChecker\sudokuCell.spec.ts.js'

**Comment by ArtemGovorov** [comment]
@MartinMason May I see your `tsconfig.json` file as well please?

**Comment by ArtemGovorov** [comment]
@MartinMason Also, what version of TypeScript are you using? 

The latest version of core is v1.0.177, could you try running with it?

**Comment by MartinMason** [comment]
Hi Artem. Thanks for looking into this. [tsconfig.json](https://files.zenhub.io/56b9f689c7438c6402f4978e)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

Seems like a stupid answer, but I'm not sure what version of Typescript I'm using. I recently upgraded VS Extensions probably 2 weeks ago. Thought I was running 1.7.5 as that's the version specified in package.json but when I run tsc -v on cmd line, message returned is 1.5.3 so that could be my problem. Path system variable points to c:\Program Files (x86)\Microsoft SDKs\TypeScript\1.7\

**Comment by MartinMason** [comment]
Here's a github repo with the most minimal Typescript / Wallaby setup I can come up with and it's still not working in VS2015. Let me know what else I can try.
https://github.com/SoftwareMasons/JustTypescript

**Comment by ArtemGovorov** [comment]
Hi Martin,
thanks for the config and the repo. Setting `noEmitOnError: false` in your wallaby config should work for you:
```
compilers: {
            '**/*.ts': wallaby.compilers.typeScript({
              ...
              noEmitOnError: false
            })
```

I have also made it the default value, so if you update to core v1.0.178, then you don't even have to make the change.

**Comment by ArtemGovorov** [comment]
@MartinMason 

Re: downgrading the core
Currently we don't officially support manually downgrading the core version (that's why there's nothing on the topic in the troubleshooting docs section). Though it's technically possible and we can email you the instructions (specific to your IDE/editor) on how to do it if it's really required.

Re: TypeScript version
Sorry for poorly formulated question, I was wondering not about the globally installed one, but about the one you're using in your project (the one specified in package.json). By default, wallaby.js is using this local version (though you may pass any other `typescript` compiler instance in the config).

**Comment by MartinMason** [comment]
Hi Artem,

Fantastic. I never got a chance to test the noEmitOnError: false solution. Core version 1.0.178 fixed the issue. Thank you so much.
