### ISSUE TITLE
Error: Can not start node.js process

### ISSUE THREAD

**Issue by danpaz** [wallabyjs/public#451]
I installed the wallaby extension for VS code but was unable to get it working for my node project with mocha tests. I think it may have trouble finding the node executable because I am using nvm on my machine. I tried using the `env.runner` property to specify the path to node directly, but that still did not work.  

![image](https://cloud.githubusercontent.com/assets/5665333/12958390/7600e16e-cfff-11e5-9462-070920becedb.png)

wallaby.conf.js
```js
module.exports = function () {
  return {
    files: [
      'lib/**/*.js'
    ],
    tests: [
      'test/**/*.js'
    ],
    env: {
      type: 'node',
      runner: '/Users/danielpazsoldan/.nvm/v4.2.1/bin/node'
    },
    debug: true
  };
};
```

VS Code version 0.10.8
Node 4.2.1
Wallaby extension 1.0.10

**Comment by ArtemGovorov** [comment]
You've correctly set the runner in the config, because you will need it as well. Another thing you'll have to do if you don't have node path in your `PATH`, is to add your node path in VS Code `settings.json` file (Code - Preferences - User Settings):
```
{
    ...
    "wallaby.node": "/Users/danielpazsoldan/.nvm/v4.2.1/bin/node"
}
```
I have just added the feature and published the new version, so you'll need to update your extension to the latest version v1.0.11, have also [updated the docs section](http://wallabyjs.com/docs/intro/install.html#visual-studio-code) to describe it.

**Comment by danpaz** [comment]
Works great, thanks!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for checking!
