### ISSUE TITLE
Instrumentation error in event handler 'Cannot read property of undefined'

### ISSUE THREAD

**Issue by ddura** [wallabyjs/public#456]
I seem to be having some kind of scoping issue with the instrumentation generated in the source file. I am trying to come up with a small example out of my more complex one but the issue stems from an event handler defined for a child process.

Basically the source being instrumented causes a 'TypeError: Cannot read property 'N' of undefined', N being the number for the instrumentation.

Is there a specific pattern I should be following in cases such as this? I have tried numerous types of 'class' patterns to see if that helps, but no go. Thoughts?

```
function MyClass() {
}

MyClass.prototype.doSomething() {
    var _this = this;
    // ... setup a child process
    process.on('exit', function(code,signal) {
        _this.doSomethingElse(); // IN INSTRUMENTED CODE THIS LINE WILL CREATE ERROR
    });
}

MyClass.prototype.doSomethingElse() {
}
```

**Comment by ddura** [comment]
Well, I went ahead and tried to isolate this issue in a smaller project, and can't. But I am running into another problem. I am hoping if I can resolve this problem, it will help narrow down the above problem. I have attached a sample VSCode project.

When running the tests using Wallaby, the test never completes and fails. But if I run from mocha on the command line or via a launch profile setup in VSCode (included) the test runs successfully.

Attached is the sample VSCode project.

[wallaby-event-instrument-error.zip](https://github.com/wallabyjs/public/files/126829/wallaby-event-instrument-error.zip)

**Comment by ArtemGovorov** [comment]
Thanks for the sample project!
I have been observing 2 separate issues:
- `Debugger listening on port 5555` being reported as an error.
- `TypeError: Cannot read property 'N' of undefined` after a few edits in any of the files.

Regarding the first issue: when you are forking child process with `,execArgv: ['--debug=5555']` node debugger reports its presence via STDERR, so wallaby was reporting it as an error. I have fixed it in the latest core version v1.0.179 (will be updated automatically).

Regarding the second issue: your test is structured in a way that you don't wait for the callback:
```
        _workerProcess.on('exit', function(code, signal) {
            _onWorkerExit.call(_this,code, signal)
        });
```
The promise in the test gets fulfilled when the worker process sends a message, and the test is finished after it, so there's no guarantee that `_workerProcess.on('exit'` callback will be invoked within the test. It happens to work in mocha and it will also work in wallaby if you disable [node process reuse](http://wallabyjs.com/docs/integration/node.html#node-process-reuse):
```javascript
...
module.exports = function (wallaby) {
    ...
    return {
        ...
        workers: {recycle: true}
    };
};
```
This way wallaby work more like mocha and it should work for you. But by default it tries to reuse node processes and what happens is that once your tests are complete, wallaby cleans up instrumentation infrastructure, but shortly after that your `_workerProcess.on('exit'` callback gets invoked, and wallaby errors because by then there no infrastructure for the instrumented code it want to run because the test run is finished.

If you'd like to keep reusing node processes in wallaby, you may need to re-structure your tests to guarantee that they finished executing all code that you're expecting to be covered before exiting.

Hope it makes sense, let me know if it addressees the issue.

**Comment by ddura** [comment]
Works like a charm! Thanks for the quick turnaround and the fix! Great product, some of the best money I have spent on a dev tool in a while.

**Comment by ArtemGovorov** [comment]
@ddura Awesome, thanks for the update!
