### ISSUE TITLE
angular/browserify/bulk-require/fs.readdirSync issue

### ISSUE THREAD

**Issue by chrisns** [wallabyjs/public#458]
Hey all!

I'm working on getting this angular gulp browserify seed to work

I think I'm most the way there, current issue that I'm not quite sure how to solve is something that originates from bulk-require and results in this error:
`TypeError: undefined is not a constructor (evaluating 'fs.readdirSync(abs)')`

hoping someone can help (there's no doubt of other problems but this is the current ones that blocking me getting much further).

https://github.com/chrisns/angularjs-gulp-browserify-boilerplate
Any help greatly appreciated!
Thanks in advance

**Comment by ArtemGovorov** [comment]
After spending few hours fighting various issues, I have created the pull request - https://github.com/chrisns/angularjs-gulp-browserify-boilerplate/pull/2.

`bulk-require` uses [`static-module`](https://github.com/substack/static-module) to find occurrences of `require('bulk-require')`, however it fails to find it in the code instrumented by wallaby, because the original code is changed from 
```javascript
const bulk = require('bulk-require');
```
to something like
```javascript
const bulk = (w(), require('bulk-require'));
```
and it break `static-module` search. 

It should be possible to implement by adding an additional check for `SequenceExpression` in [`static-module` source code](https://github.com/substack/static-module/blob/master/index.js#L94). Before someone creates a pull request to `static-module, one may just set `instrument: false` to `app/js/**/index.js` pattern so that wallaby won't be touching files where `require('bulk-require')` is invoked. The drawback is that wallaby will not show code coverage for those files, but they look like some boilerplate code anyway.

The changes I have made:
- removed some props that didn't seem to to anything.
- added `presets` property to babelify transform, [it seems it's required](https://github.com/babel/babelify/issues/103).
- changed entry patterns to only include `wallaby-main.js` and tests.
- removed angular from the `files` list, because `main.js` requires it, and there'll be `Angular loaded twice` issue.
- removed angular-mocks from the `files` list because it requires angular and now loaded in `wallaby-main.js`.
- added `babel-polyfill` because PhantomJs doesn't support promises that are used.
- set `instrument: false` to `app/js/**/index.js` pattern to resolve the issue that you've described originally.

**Comment by ArtemGovorov** [comment]
With the `bundler.transform(require('babelify'), {presets: ["es2015"]});` change, apparently you may remove `{presets: ["es2015"]}`, but for some reason `babelify/browserify` tries to read `.babelrc` not from the local project folder, so you'll need to add the file to the `files` list so ends up in wallaby cache:

```
    files: [
      '.babelrc',
      ...
    ],
```

**Comment by chrisns** [comment]
You're my hero! thank you so so much!
