### ISSUE TITLE
Cant find variable bard - Problem using bardJS module loading in angular tests

### ISSUE THREAD

**Issue by chaaya** [wallabyjs/public#466]
I created a public repo to demonstrate the issue I am having using bardjs for module loading in angular tests.
After som googling I found this article, http://briantroncone.com/?p=463. Tried it with no success.

> ReferenceError: Can't find variable: bard

I am using wallbyjs with **Atom**.

https://github.com/chaaya/wallabyBardJS

**Comment by ArtemGovorov** [comment]
Have sent you [the pull request](https://github.com/chaaya/wallabyBardJS/pull/1). 

There were a few issues in it, the error you were getting was because  `gulpConfig.karma.files` contains some absolute paths, while wallaby needs relative paths.

Things I have fixed:
- added `phantomjs-polyfill`, angular 1.5 needs it (removed the polyfill from the `setup` function).
- got rid of the `gulpConfig.karma.files` usage. Wallaby needs relative paths, sinon/chai/sinon-chai dependencies have to be listed as well, libraries need to have `instrument: false` flag, test pattern has to be excluded. You may read more [about files/tests configuration in the docs sections](http://wallabyjs.com/docs/config/files.html).
- added `window.expect = window.chai.expect;` to the setup function, so that the global `expect` variable may be used tests.

**Comment by chaaya** [comment]
Thanks so much for your help! Amazing support from you guys, big thumbs up!
