### ISSUE TITLE
How to load file that contains inline source map

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#467]
First let's start with the use case.

I'm testing a project using babel/webpack loaders. For debugging purposes, everything is instrumented.

```
files: [
  'node_modules/lodash/lodash.js', // ES5 global
  'node_modules/angular/angular.js', // ES5 global
  'node_modules/angular-mocks/angular-mocks.js', // ES5 global
  'src/jasmine-mox-matchers.js' // unit under test, ES6
],
tests: [
  'test/spec/matchers-spec.js' // ES6
]
```

in jasmine-mox-matchers.js I have:

```
import {expectMatcher} from 'testception';
```

This imports the file `node_modules/testception/dist/testception.js` which is a (webpacked to umd) ES6 file containing inline source maps. Everything works fine this way.
Note that I did not include this file in the 'files' list, despite the docs say I had to do this.

I wonder why `testception.js` is not instrumented, because it is imported in the instrumented file `jasmine-mox-matchers.js`. Perhaps I have to load it explicitely, like it's written in the docs, so let's do that by adding `testception.js` to the files list but this gives the error in both `load: false/true` cases:

```
wallaby:project Error: Failed to run compilers on node_modules/testception/dist/testception.js, Error: node_modules/testception/dist/testception.js: Invalid mapping: {"generated":{"line":8,"column":0,"lastColumn":null},"source":null,"original":{"line":null,"column":null},"name":null}
    at SourceMapGenerator_validateMapping [as _validateMapping]
```

When I recompile `testception.js` with a separate source map file, everything is ok again. I even have the file instrumented. It doesn't make a lot of sense to instrument this file, because it is a compiled file. When I load the src file, everything is ok and instrumented again :).

### Summarizing question
It's not such a problem that I don't have an external file instrumented easily, but when I was struggling with the config I started to become totally confused when to load files in Wallaby and in what way. (Karma is the next stage, which makes it even more confusing.)

For my general understanding, there are several module formats the file that you want to load can have:
1. ES5 file with globals, so normally loaded in a script tag. Loading order is important.
2. Transpiled file in ES5 + CommonJS format
3. Transpiled file in ES5 + requirejs format
4. ES6 file with ES6 exports

If I want to load (+ instrument?) such a file, what is the best way to do this, per situation 1-4?
Note that for 2-4 I could do `import {x} from './path/to/file'` or `import {x} from 'modulename'` in my spec/src, which also has effect on the way I need to load the file with Wallaby?

Please help me understand this matter and perhaps improve the docs. When I'm a pro at this, I will definitely write a blog post about this.

Thanks a lot.

**Comment by ArtemGovorov** [comment]
> Note that I did not include this file in the 'files' list, despite the docs say I had to do this.

Docs are actually [stating that if you are using a module bundler, such as webpack, then you don't need to list your modules](http://wallabyjs.com/docs/config/files.html). It's also specifically stated in the [webpack dedicated part of the docs](http://wallabyjs.com/docs/integration/webpack.html#files-and-tests).

Generally the answer for webpack (and other module bundlers): don't put **external** modules in your `files` list (unless you'd like to load the globally like you do with `lodash` and `angular`).

This means that you don't instrument those external modules that you `require` or `import`. You can do it in many cases, for example when imported module is in CommonJs or ES6 imports/exports format, but not in your case (webpacked with source maps).

It depends on how you configure and use webpack, but in typical apps one would have very few files with `load: true` in wallaby config file. With webpack you normally don't use globals, but `require`/`import` other parts of your app and external modules.

When you `require`/`import` something that is not an external module, you need to list it in your `files` list with `load: false`. Order doesn't matter, because the file itself is not something that will be loaded into the sandbox as is (hence the `load: false`). This also means that you may use broader glob patterns as opposed to listing files one by one.

When you specify files in the `files` list (with `load: false` or `load: true`), they end up in the wallaby file cache. The file cache mostly mirrors your file structure and allows to change files (instrument them), create new ones if required, etc., without polluting your local project folder.

[With webpack](http://wallabyjs.com/docs/integration/webpack.html), you specify a `postprocessor` and a `setup` function:
```javascript
postprocessor: wallabyPostprocessor,

setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    }
```
So, when wallaby processes your file changes, it runs webpack postprocessor, which in its turn runs webpack on the wallaby file cache. The result of the webpack compilation (let's name a virtual bundle) is executed when `window.__moduleBundler.loadTests();` is invoked. 

This is when everything with `load: false` flag that needs to be executed is actually executed. So if your test does `import {x} from './path/to/file'`, that's when the `/path/to/file` content is actually loaded (the file in its turn `import` other files, etc.).

Regarding your 1-4 list of types of modules (and this should probably answer the question in the issue title): if something is transpiled not by wallaby (compiler/preprocessor/postprocessor), then it doesn't make much sense to instrument it with wallaby, because **wallaby needs to be able to process original files first** to be able to provide the code coverage for them.

Regarding the question itself: "If I want to load (+ instrument?) such a file, what is the best way to do this, per situation", to summarise my answer in context of webpack:
- don't put **external** modules in your `files` list, unless they are ES5 file with globals that you would like to load in the sandbox. Note that many webpack users are actually `import`-ing/`require`-ing these modules as well as opposed to loading them globally. For example, they configure `angular` or `jquery` [as external library](http://stackoverflow.com/questions/22530254/webpack-and-external-libraries) and then `import {..} from 'angular` and let webpack to do the rest.
- if some file is `require`-ed or `import`-ed from a test or some file that a test `require`-s or `import`-s, then the file needs to be in the `files` list (normally as a part of a broad pattern like `src/**/*.js`) with `load: false`.
- module format of a file doesn't matter as long as webpack can be configured to compile it correctly.

Hope it makes sense and explains the whole thing in general. Happy to answer your questions if you have some.

**Comment by fvanwijk** [comment]
> Docs are actually stating that ...
Hmm how could I miss that :( Perhaps was too focused on the `load` part of the docs.

Anyway, your elaborate explanation helps me a lot understanding how Wallaby works under the hood and helps me determining how I have to structure my (webpack) projects.
I also hope that others will also benefit from your answer.

Thanks a lot for taking the time for this reply.
