### ISSUE TITLE
More Robustness for 3rd party errors

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#470]
Is there any way to make wallaby slightly more leniant in it's processing? For example I've got this recent issue after including materialize.

```
​​​​​TypeError: 'undefined' is not a function (evaluating 'document.querySelectorAll.bind(document)')
		at dist/external/min/materialize.min.js:3
		at dist/external/min/materialize.min.js:3
```

I'm planning on logging a bug with them, but part of the problem is we're including this via bower and until this rep puts in a fix (if indeed they do) it's preventing me running some of my tests.

**Comment by ArtemGovorov** [comment]
When there are some global errors during loading included libraries, we often can't run any tests, sometimes simply because PhantomJs would not load them. Also trying to run anything in this state may easily cause other obscure errors. I'd suggest to simply removing the library from wallaby config `files` list in such cases, until the issue with it is sorted out.

As for the issue itself, I have described the solution in [the other issue](https://github.com/wallabyjs/public/issues/471). Another solution BTW would be to use [PhantomJs2](http://wallabyjs.com/docs/integration/phantomjs2.html), that doesn't need the polyfill.
