### ISSUE TITLE
Price

### ISSUE THREAD

**Issue by alphashuro** [wallabyjs/public#472]
### $100 PER EDITOR is a bit too expensive

I use about 5 editors in total, Sublime Text, Atom, VSCode, Visual Studio, and Web-storm, and I occasionally switch between editors depending on my needs. I have tried Wallaby.js and absolutely loved it, and I proclaim it as an unliveable-without tool. I was not disappointed at all when I tried it in atom and it alerted me about my lack of a licence, I quickly opened up your website to buy the licence and give you my money because I thought 'this is definitely worth it, these guys deserve my money'. 

I was a bit shocked to see the price tag of $100, but after a split second of thinking I decided to press buy because it was so worth it, my wallet was just going to have to take the pain. I noticed there was another of my editors listed, also with a $100 price tag, and began to realize that for each of my editors I was going to have to pay, $100. So the conclusion is that I, one user, have to pay $500. Even though I don't actually use these editors at the same time, I can't actually swap my licence between editors... Being a user of 5 editors, I am extremely pained and heart broken by this hefty price tag, and would have to save for months to be able to account for that on my budget. For a developer who doesn't earn thousands, I cannot afford to spend that much on this, and yet I cannot live without it. It has caused me to leave all my other editors and submit to using the trial licence available for sublime text. But since this is expiring soon, I have realized I will be left living like a normal human again, scarred by the experience of wallaby that I can not afford for a few months.

Please consider providing cheaper options, or making a licence reusable between editors. I'm certain I'm not the only one betrayed by this price tag...

**Comment by ArtemGovorov** [comment]
We actually offer the 'Freedom' license (the one at the end of the price list), it is the license that can be used in all editors that we support. So it only costs $140 for all 5 editors, and not $500.

**Comment by ArtemGovorov** [comment]
Regarding the price, I don't think this technical issues/questions repo is the best place to discuss it, so I've sent you an email explaining our pricing.

**Comment by danieldram** [comment]
I would also like to discuss the price.. That's pretty expensive. I love Wallaby and have been a big supporter of it, but I can't even recommend it to others at this price..

**Comment by alphashuro** [comment]
Ahh thank you Artem, I had not realized that option was available way at the bottom of the page, I TLDRd the page too early. Daniel makes a good case as well though, $140 makes it really difficult for many people to access wallaby. I've been telling my friend about it and as soon as he found out the price he was immediately discouraged. I do believe you have good reasons for charging so much for it, but please try to provide an option for people who can't afford the hefty price tag.

**Comment by alphashuro** [comment]
By the way I did not receive your email

**Comment by ArtemGovorov** [comment]
Our pricing was designed to allow us building a sustainable business. And while we totally understand that our product is not cheap, we can't both make everyone happy about the price and keep developing, testing and maintaining a quality product.

As you may guess, developing, testing and maintaining a quality software development tool for 5 different editors with a few different versions, for 3 operating systems with a few different versions, in 7 programming languages - is not cheap either.

Also, I always encourage people to consider the product value as well, not just the price in isolation. **Wallaby.js price for a professional developer is $8-12 dollars per month (and $4-6 dollars per month after the first year).** We believe that our tool at the very minimum should make you productive enough to cover the $8-12 expense per month. In fact, for many of our customers it **pays off its full year price within a few days of their work with the tool**.

Hope it makes sense.

**Comment by ArtemGovorov** [comment]
@alphashuro I have used the gmail one from your Github profile. Have duplicated my email to you above anyway.

**Comment by danieldram** [comment]
Thank you for responding Artem.
I agree with you. But imagine trying to encourage a developer friend to buy? It's really uncomfortable suggesting to a friend to spend $100 on something and gives the wrong idea sometimes. That's why I can't suggest it to others now. 

When I did suggest it, it was at the time. Free for a good period of time, so people were willing. But now, just today.. A developer friend of mine, who I showed it to.. Was kind of speechless. 

So instead of making it $100 dollars, how about as you mentioned.. You make it $4-$8 a month? 

Sreen-o-matic does this pricing strategy and so do almost all online popular video learning businesses. With Pluralsight or Team Treehouse, you pay the $40 a month but get full access to all the content for the month. With the $100 price tag, we only get the license for one editor and thats it. 

In any event, I unfortunately decided to just use browserify to compile down a spec.js file and use a combination of console.log() and http-server for my npm packages now. I can't expect other developers who don't even know, to pay such a huge price to run my tests in an open source NPM package.

**Comment by alphashuro** [comment]
I see, it does make sense indeed. But as @danieldram suggested, how about providing the option to actually _pay_ $8-$12 per month? It would make the payment a lot easier on us. Of course I could save up the same amount for 12 months to raise the funds, but that would be 12 months I would have to spend without wallaby :(

**Comment by ArtemGovorov** [comment]
@danieldram Regarding your friend reaction, well, as I have said, we can't make everyone happy. With any price tag there'll be some people who'll be surprised by the price. Even it's free, there'll be people surprised or unhappy about something else.

Thanks for your feedback!
Subscription model with a lower entry price is something that we may consider adding in future.

**Comment by eggyal** [comment]
I think it's worth bearing in mind that (at $100 individual/$160 company) Wallaby costs more than an entire IDE (e.g. WebStorm at $59 individual/$129 company).

It seems that it's asking a huge investment for a relatively small part of one's development workflow.

For me, I've decided to make that investment—but I did have to think very hard about it.  If it helps support the development of Wallaby so that some of the (many) open issues can be closed off, that's a price worth paying.  If issues remain unresolved for months on end (the oldest open issue is over a year old) then I'm not so sure...

**Comment by ArtemGovorov** [comment]
@eggyal Well, some of the IDEs that we support are absolutely free, some cost [thousands dollars](https://www.visualstudio.com/en-us/products/how-to-buy-vs.aspx). I personally don't think comparing prices for completely different products is helpful to decide whether a product is worth buying or not.

We appreciate your support and are constantly working on adding new features (our internal issue list is 3 times bigger than the public one). When issues are bugs, we try to fix them immediately, so you won't find many. 

However, when an issue is a feature/enhancement, then unfortunately it may end up never be implemented. The reality is that some of them may be out-of-scope, some receive less priority for various reasons, etc. If you'd like the tool to prosper and get better, please trust us to select what and when to implement. 

I also don't think that checking how old some of the issues are, is not a good way to see how healthy the project is. You may find tons of 3-4-5 year old issues in the [WebStorm issue tracker](https://youtrack.jetbrains.com/issues/WEB), it doesn't mean it's a bad or unsupported IDE.

**Comment by fvanwijk** [comment]
Suppose that your hour rate is $ 100 and you spend 2 hours debugging your build pipeline using ES6, Webpack and Jasmine with all kinds of loaders en preprocessors until it works. This will cost you $200.

The other option is buying Wallaby (**including** the excellent support!) for $ 129, stop the frustration of debugging the pipeline, open a Github issue and post your config file. Artem will fix your build pipeline within a day, you will learn a lot and as bonus you may have discovered a Wallaby bug. And you saved $ 71.

J/k, my point is that the $129 is indeed a lot if you compare it with Webstorm or other software.
However, you need to compare Wallaby with 'not having Wallaby'. If Wallaby saves you $ 129, just buy it and it will return the cost of investment.
If you think it's not worth it or your company doesn't want it, don't complain and move along.

**Comment by lacymorrow** [comment]
I very much enjoy the idea of Wallaby, nice work building a great tool!

I do find it ironic that the quote used to justify your pricing references free software (the "cost" being the time spent setting up the tool) 😄 :

> Linux is only free if your time has no value.

**Comment by jukefr** [comment]
Well since $140 is worth about **15 hours of work** for me, and taking into consideration the fact I need to feed myself.
I opted **to spend** an hour of my life to simply _"refactor"_ the licensing part of the app. Works great !
I appreciate the fact that the devs conceived in their mind that not everybody works in Silicon Valley for 120K a month, seing how easy the _"refactor"_  was.
