### ISSUE TITLE
Better way to debug?

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#487]
I recently made a small change to some code that hits a huge number of tests that run in Wallaby. This affected where files are requested in some delay loading code that we're using in our tests. 

This as I expected broke most of the tests running in Wallaby, so I worked out what I needed the relative path to be and updated it within some of my code. I expected this to fix all of the tests, but it only resolved about 50%. Now I'm left wondering what's wrong.

If I run all the tests then I get a whole bunch of failures. If I try to focus in on those that are failing and run just the file tests they all pass. This is strange as I've not encountered this before and I believe the tests are all truly standalone. But I'm left not knowing how to debug further.

Is there any way of running/seeing the tests in the sandbox environment through a web browser so I can do some better debugging? I've tried using the last screenshot to see what's going on but normally it's empty (or is displaying most of my content off screen so isn't very helpful).

**Comment by ArtemGovorov** [comment]
@IPWright83 We have the feature request that you may subscribe to https://github.com/wallabyjs/public/issues/74. 

However, even if we had this today, I'm not sure setting breakpoints would help you much to find out what the problem is.

It sounds like there's an issue where some of your tests are leaving some state that other tests depend on. When you run a specific test or a test file, it may pass because nothing else interferes with it. But when you run all of your tests, some specs fail because other test files may have changed your global state in some way.

Just like I would do if I was getting the issue in browser page tests, I would try to bisect my list of tests to find out what test file is causing the issue. Before doing so, I'd temporarily set [wallaby worker count to one](http://wallabyjs.com/docs/config/workers.html), so that it doesn't run tests in parallel (which may make finding the problematic spec file harder).

Hope it makes sense.

**Comment by IPWright83** [comment]
It was actually due to relative paths and the different sandboxes - what I'd typically do was debug the network requests (which you can kinda do with the Wallaby console) but it is hard to go through and match up with a single individual test at times.
