### ISSUE TITLE
How to get the path of the project?

### ISSUE THREAD

**Issue by togakangaroo** [wallabyjs/public#497]
I am running wallaby over tests that operate on a sqlite database. I want the db file to be in a constant location inside of my project root. So typically I would do something like `../data/db.db`. Unfortunately, since wallaby copies files to run them I cannot use a relative path.

How can I a) test whether this is being run in wallaby and b) properly path this to my project directory?

### Code editor or IDE name and version

Atom v1.x

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
The easier way would be to just **add your `data/db.db` in the `files` list in your config** so the DB gets copied to the wallaby build output folder, so that your tests/code can keep using relative paths.

If the solution above is not an option for some reason, you may use [wallaby setup function](http://wallabyjs.com/docs/config/bootstrap.html#setup-function):
```javascript
setup: function(wallaby) {
  global.isBeingRunInWallaby = true;
  global.dbPath = wallaby.localProjectDir + '/data/db.db'
  // or you may monkey-patch fs.readFile(...)
  // or whatever is used to read your db file,
  // so when called with the `data/db.db` path
  // then read it from wallaby.localProjectDir + '/data/db.db' instead
}
```
However adding a test runner specific logic in your code is not great, so I would recommend the first solution with adding the DB file to the `files` list.

**Comment by togakangaroo** [comment]
cool thanks!
