### ISSUE TITLE
(webpack 2) wallaby-webpack - Cannot resolve file or directory (missing: /undefined.webpack-loader.js')

### ISSUE THREAD

**Issue by bZichett** [wallabyjs/public#502]
Hi.  I enjoy and benefit greatly from working with wallaby and had it working with requirejs, but I refactored my code to use webpack, and I am having the toughest of times to get my tests up and running.  I've already wasted a good amount of time trying to debug the following error(s) (the same object is repeated around 7 times in the dependenciesErrors array) 

It seems to be something 'silly', but all of the assigned directories (APP, LIB etc) aren't undefined which was my obvious first guess at debugging.

```javascript
dependenciesErrors: 
   [ { [ModuleNotFoundError: Module not found: Error: Cannot resolve 'file' or 'directory' /directory/spa]
       name: 'ModuleNotFoundError',
       message: 'Module not found: Error: Cannot resolve \'file\' or \'directory\' /directory/spa',
       details: 'resolve file\n  /directory/spa/undefined doesn\'t exist\n  /directory/spa/undefined.web-loader.js doesn\'t exist\n  /directory/spa/undefined.webpack-loader.js doesn\'t exist\n  /directory/spa/undefined.loader.js doesn\'t exist\n  /directory/spa/undefined.js doesn\'t exist\nresolve directory\n  /directory/spa/undefined doesn\'t exist (directory default file)\n  /directory/spa/undefined/package.json doesn\'t exist (directory description file)',
       missing: [Object],
       module: [Circular],
       error: [Object],
       dependencies: [Object],
       origin: [Circular] }, ......

  name: 'vendor',
  built: true,
  cacheable: true,
  issuer: null,
  building: undefined } { [Error: Cannot resolve 'file' or 'directory' /directory/spa]
  details: 'resolve file\n  /directory/spa/undefined doesn\'t exist\n  /directory/spa/undefined.webpack-loader.js doesn\'t exist\n  /directory/spa/undefined.web-loader.js doesn\'t exist\n  /directory/spa/undefined.loader.js doesn\'t exist\n  /directory/spa/undefined.js doesn\'t exist\nresolve directory\n  /directory/spa/undefined/package.json doesn\'t exist (directory description file)\n  /directory/spa/undefined doesn\'t exist (directory default file)',
  missing: 
   [ '/directory/spa/undefined',
     '/directory/spa/undefined.webpack-loader.js',
     '/directory/spa/undefined.web-loader.js',
     '/directory/spa/undefined.loader.js',
     '/directory/spa/undefined.js' ] }
```

**Notes:**:

1. My webpack config obviously works with webpack-dev-server and production builds but if you need to see it or anything else in my repo let me know. 
2. I replaced a longer directory path with "/directory/spa"

I've a slight feeling this might have to do with an external dependencies package.json file but I am not sure.  I've tried many things, but I admit I've little knowledge about wallaby internal infrastructure to be able to properly diagnose this.  

### Wallaby.js configuration file

```javascript
var configs = require('./gulpfile').unbaffledConfigs
var wallabyWebpack = require('wallaby-webpack');

var devConfig = configs.developmentWebpackConfig
devConfig.eval = 'source-map'
var wallabyPostprocessor = wallabyWebpack(devConfig);

var APP = 'core/'
var BOWER = 'bower_components/'
var LIB = 'lib/'
var DIST = 'build/'
var NODE_MODULES = 'node_modules/'

module.exports = function (wallaby) {

	var fs = require('fs')

	return {
		debug: true,
		files: [


			// VENDOR
			{pattern: (BOWER + 'jquery/dist/jquery.min.js'), instrument: false, load: false},
			{pattern: (BOWER + '**/*.js'), instrument: false, load: false},

			// VENDOR - TESTING
			{pattern: (BOWER + 'chai/chai.js'), instrument: false},
			{pattern: (BOWER + 'sinon.js'), instrument: false}, // http://sinonjs.org/
			{pattern: (BOWER + 'sinon-chai.js'), instrument: false}, // http://chaijs.com/plugins/sinon-chai

			// CORE MODULES
			{pattern: (APP + '**/*.js'), load: false},

			// IGNORE
			{pattern: (APP + '**/*-test.js'),    ignore: true},
			{pattern: (APP + 'views/tags/app/**/*.js'),    ignore: true},
			{pattern: (APP + 'views/tags/lib/**/*.js'),    ignore: true},
			{pattern: (LIB + '**/*.js'),          ignore: true},
			{pattern: (DIST + '**/*.js'),        ignore: true},
			{pattern: (NODE_MODULES + '**/*.js'), ignore: true},
			{pattern: ('gulpfile.js'),            ignore: true},

		],

		tests: [
			{pattern: APP + '**/*-test.js', load: false}
		],

		testFramework: 'mocha@2.2.4',

		compilers: {
			'**/*.js': wallaby.compilers.babel()
		},

		postprocessor: wallabyPostprocessor,

		setup: function () {
			// required to trigger test loading
			window.__moduleBundler.loadTests();
		}

	}
};

```

### Code editor or IDE name and version

IntelliJ IDEA v15.0.4 build 143.2287

### OS name and version

Linux

Thanks for your time and if you need to check my account, the email I paid for wallaby with is bzichett@gmail.com)

**Comment by ArtemGovorov** [comment]
May I see your webpack config please?

> `/directory/spa/undefined`

It does seem like something somewhere incorrectly creates paths, but your wallaby config looks ok in that regard, as you are using constants for your paths prefixes.

There are normally few things that wallaby config needs to override in it (like remove babel loader because it is using its own compiler, make some paths absolute, etc.), but in your case you are mostly using it as is. Maybe we are dealing with [one of these issues](http://wallabyjs.com/docs/integration/webpack.html#module-resolution-issues), but may be something  else as well.

A couple of other things that may or may not be related to the issue:

> `devConfig.eval = 'source-map'`

I'm not familiar with the setting, what does it do? Perhaps you meant to [set `devtool` option](http://wallabyjs.com/docs/integration/webpack.html#source-maps-and-devtool-option)?

A few other things:
- you don't need these in your `files` list (they are not included by any other patterns, so no need to excluded them):
```javascript
{pattern: (LIB + '**/*.js'),          ignore: true},
{pattern: (DIST + '**/*.js'),        ignore: true},
{pattern: (NODE_MODULES + '**/*.js'), ignore: true},
{pattern: ('gulpfile.js'),            ignore: true},
```
- you may not need these:
```javascript
{pattern: (BOWER + 'jquery/dist/jquery.min.js'), instrument: false, load: false},
{pattern: (BOWER + '**/*.js'), instrument: false, load: false},
```
I'd rather suggest to use a more efficient [approach described here](http://wallabyjs.com/docs/integration/webpack.html#module-resolution-issues).

**Comment by bZichett** [comment]
Ah one more pretty important thing I forgot to mention.  I'm using the webpack2 beta since I was attracted to the new additions posted here: https://gist.github.com/sokra/27b24881210b56bbaff7

Any idea if this could be the issue? (I haven't tested with webpack since I'd have to mess around with my config file quite a bit.

I'll post that config after you confirm this wouldn't be the issue (don't want to bother you if it is)

**Comment by ArtemGovorov** [comment]
Thanks the note that you are using webpack2. 

As it's not released yet and is still in beta, I don't think it makes sense to update the wallaby docs just yet. 

For the same reason certain things may not work in `wallaby-webpack` package. I have been testing previous webpack2 beta builds in it, have made few changes (like [this one](https://github.com/jeffling/wallaby-webpack/commit/c198047dde20dc0aa7626ce818077471dc2d0fb4) and [this one](https://github.com/jeffling/wallaby-webpack/commit/9af92bf575a2ca6a15e7946fa2de5ae9b6c8eceb)) to support the API changes, and my simple test projects did work. 

Having said that, it looks like new webpack2 beta builds are still changing few things here and there, so I wouldn't be surprised if some things are broken in the integration.

Your current webpack config will not be very helpful, because I won't be able to tell what's wrong, as I haven't used webpack2 much and the majority of wallaby-webpack users are using 1.x, so I don't yet have much experience troubleshooting webpack2 integration issues yet. 

However, I'd love to make it work for you even before the official webpack2 release (and for others in future), so would really appreciate if you could create a simple repo reproducing some/all of your issues, I'll jump in and address them in `wallaby-webpack`.

**Comment by ArtemGovorov** [comment]
*Update*: I have been doing some more testing with the latest webpack 2 beta build (`2.1.0-beta.4`) and have found some issues. I have fixed them and just published in the new `wallaby-webpack@0.0.17` version. The issues I have fixed don't look like those that you've encountered, but it's still worth updating the package if you decide to create a sample project demonstrating those that you've encountered.

**Comment by bZichett** [comment]
`wallaby-webpack@0.0.17` fixed the issue in this thread. 

If I have time on the weekend I'll try to compare what exactly happened per my configuration and the changes from 0.16 -> 0.17.

I feel kind of silly for jumping the gun on webpack2.

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
