### ISSUE TITLE
test failure; cannot reproduce on command-line

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#522]
### Issue description or question

I have a test failing in Wallaby that passes on the command line.  I'm using the following command to run my tests:

```shell
$ mocha --require test/fixture --compilers=js:babel-core/register --recursive --timeout 0
```

The salient flag here is `--timeout 0`.  I need to fully disable timeouts because Mocha won't play nice with libraries that monkeypatch timers.  Indeed, I'm using such a library ([async-listener](https://www.npmjs.com/package/async-listener)).

Here's the problem test:

```js
describe(`and when the function throws an error`, () => {
  beforeEach(() => {
    test.func = () => {
      setTimeout(function bzzt () {
        throw new Error('foo');
      }, 50);
    };

    return test.run();
  });

  it(`should end in state "failed"`, () => {
    expect(test.current)
      .to
      .equal('failed');
  });
});
```

The test itself isn't actually the issue, afaik.  Yes, the assertion fails, but the important bit is that function `bzzt()` *is never called by Wallaby* as per the coverage indicators.  I can confirm `bzzt()` is called when running `mocha` directly in both Node.js v4 and v5.  My system installation is v5, which is what I assume Wallaby is using, as per `runner: 'node'`, below.

I don't know what's going on here.  So I made this ticket.  :smile:

### Wallaby.js configuration file

```javascript
'use strict';

/* eslint import/no-require:0 */

module.exports = function wallabyConfig (wallaby) {
  return {
    files: [
      'src/**/*.js',
      'test/fixture.js',
      'package.json',
      {
        pattern: 'node_modules/mocha-ui-bdd/lib/**',
        instrument: false
      }
    ],
    tests: [
      'test/**/*.spec.js'
    ],
    env: {
      type: 'node',
      runner: 'node'
    },
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    testFramework: 'mocha',
    bootstrap: function bootstrap (wallaby) {
      wallaby.testFramework.timeout(0); // <-- this should do it, right?
      require(require('path')
        .join(wallaby.projectCacheDir, 'test', 'fixture'));
    },
    debug: true
  };
};

```

### Code editor or IDE name and version

PyCharm, latest Wallaby as of now.

### OS name and version

El Capitan

**Comment by ArtemGovorov** [comment]
In your code sample, what is `test` and when `test.func` is invoked?

**Comment by ArtemGovorov** [comment]
Ok, I'm guessing `return test.run();` should be `return test.func();`? 
Anyway, here is what happens. Wallaby needs to know when mocha is done running tests, so when mocha says that tests are over, wallaby stops collecting the code coverage and does other require clean up. Here is how wallaby subscribes to mocha event:

```javascript
mocha.reporter(function (runner) {
    runner.on('end', function () {
      // we stop collecting the coverage here
    });
});
```

So generally, a test like:
```javascript
it('a test', () => {
setTimeout(function bzzt () {
        throw new Error('foo');
      }, 50);
});
```
will always pass and the `throw new Error('foo');` line will never be covered, because mocha reports that test run is finished before it executed. 

Now why does it execute - my guess is that the command line mocha (as a node app) doesn't exit before all timeouts are finished. And because mocha must be subscribed to the `process.on('uncaughtException'`, it will catch and report the error. The problem is that mocha has already reported `runner.on('end'` by then, so integrations can't really report it.

Does it make sense?

**Comment by boneskull** [comment]
Sorry, should have given you more context.

> In your code sample, what is test and when test.func is invoked?

`test` is an object with a `run()` function, which returns a `Promise`.  The `run()` function executes `test.func`.

> Ok, I'm guessing return test.run(); should be return test.func();? 

No, it's correct as written.

You are right about this:

> ```
it('a test', () => {
setTimeout(function bzzt () {
        throw new Error('foo');
      }, 50);
});
```
will always pass and the throw new Error('foo'); line will never be covered, because mocha reports that test run is finished before it executed.

However, that is not what's happening here.  `test.func` is not a "Mocha test".  What I'm doing in these tests is asserting that an exception, thrown asynchronously, will put the `test` object in

**Comment by boneskull** [comment]
When I tell Wallaby my `testFramework` is `mocha`, is it using its own copy of Mocha?  Can I make it use a custom one?

**Comment by boneskull** [comment]
...it's a race condition somewhere.  Reducing the timeout on `test.func`'s `setTimeout()` call from `50` to `0` causes the error to be thrown.  However, the test still doesn't pass.  Wallaby reports this in its debug log:

```
Thu, 17 Mar 2016 19:39:12 GMT wallaby:workers Sandbox (active) [8lcxc] error: Error: foo
Runtime error: Error: foo
    at bzzt [as _onTimeout] (./test/unit/ui/test.spec.js:289:51)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by boneskull** [comment]
Indeed, *increasing* the timeout to `1000` causes Wallaby to miss the function, however command-line `mocha` still calls it.

**Comment by boneskull** [comment]
Does Wallaby itself do any monkeypatching of globals?

**Comment by boneskull** [comment]
Not that I'd necessarily *accuse* Wallaby of such a thing. :smile:

**Comment by ArtemGovorov** [comment]
> When I tell Wallaby my testFramework is mocha, is it using its own copy of Mocha? Can I make it use a custom one?

It is still using its own (latest supported). There's no way to set a custom version, but I'm planning to just allow using locally installed mocha node package with a fallback to the embedded one.

> What I'm doing in these tests is asserting that an exception, thrown asynchronously, will put the test object in a "failed" state.

It still looks to me that what's happening is what I described in the [one before the last paragraph here](https://github.com/wallabyjs/public/issues/522#issuecomment-197801776). When you decrease the timeout, the error is reported because node processes are reused, so it's caught and reported. But it happens *after* wallaby receives the `'end'` event from mocha runner for the test run, so the run results are reported without the error.

However it's hard to definitely tell without seeing the full picture, and perhaps I'm totally wrong. It depends on how/when the `beforeEach` returned promise is fulfilled. If it was fulfilled *after* the exception, then there shouldn't be any issue.

If you could share a sample that I could run, I may look into it to definitely tell what's going on.

> Does Wallaby itself do any monkeypatching of globals?

It does for some globals, but always in a way that the original function is always invoked.

**Comment by boneskull** [comment]
@ArtemGovorov OK, I may have to extract a sample from the project or otherwise share it with you (it's private, currently).

> It does for some globals, but always in a way that the original function is always invoked.

This may be part of the issue, because it's crucial the original function is *not* invoked.

Apparently zone.js now works in node, so I'm going to see if I have better results there.  If not, then I'll give you access to some code, somehow.

**Comment by boneskull** [comment]
Trying zone.js I'm having *better* results, though the node implementation is far from perfect.  However, it seems to conflict with Wallaby.js anyway:

```
Sat, 19 Mar 2016 10:11:15 GMT wallaby:workers Sandbox (active) [nc0ac] error: TypeError: Cannot read property 'cancelTask' of undefined
Sat, 19 Mar 2016 10:11:15 GMT wallaby:workers Failed to map the stack to user code, entry message: TypeError: Cannot read property 'cancelTask' of undefined, stack: TypeError: Cannot read property 'cancelTask' of undefined
    at /Volumes/alien/projects/boneskull/mocha3/node_modules/zone.js/dist/zone.js:116:19
    at clearTimeout (eval at createNamedFn (/Volumes/alien/projects/boneskull/mocha3/node_modules/zone.js/dist/zone.js:936:18), <anonymous>:3:39)
    at /Users/boneskull/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:15:23696
    at Array.forEach (native)
    at d (/Users/boneskull/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:15:23676)
    at Object._.in:stop (/Users/boneskull/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:15:25473)
    at WebSocket.<anonymous> (/Users/boneskull/Library/Caches/WebStorm2016.1/wallaby/wallaby/server.js:15:24285)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
    at Receiver.self._receiver.ontext (/Users/boneskull/Library/Caches/WebStorm2016.1/wallaby/wallaby/node_modules/ws/lib/WebSocket.js:682:10)
Runtime error: TypeError: Cannot read property 'cancelTask' of undefined
    at /Volumes/alien/projects/boneskull/mocha3/node_modules/zone.js/dist/zone.js:116:19
    at clearTimeout (eval at createNamedFn (/Volumes/alien/projects/boneskull/mocha3/node_modules/zone.js/dist/zone.js:936:18), <anonymous>:3:39)
    at Array.forEach (native)
    at emitTwo (events.js:100:13)
    at WebSocket.emit (events.js:185:7)
Sat, 19 Mar 2016 10:11:16 GMT wallaby:workers Sandbox [nc0ac] is not responsive, recycling worker instance
```

Zone.js monkeypatches `global.WebSocket`.  I'm not sure how that impacts Wallaby in this case, but it's obviously not great...

**Comment by boneskull** [comment]
FWIW, swapping out async-listener for Zone.js causes my tests to pass in Wallaby as written above, with the caveat I must `import 'zone.js'` at the top of my test file.  This weekend I'll shelve my work, revert and try to `import 'async-listener'` in the same manner and see if the tests pass in Wallaby.

**Comment by boneskull** [comment]
I also switched from PyCharm to WebStorm, though it probably doesn't matter.

**Comment by ArtemGovorov** [comment]
I haven't used neither `zone.js`, nor `async-listener`, but if there's a sample I could try, I may also have a look into what is going on there.

>  I must import 'zone.js' at the top of my test file.

So importing it once in your `test/fixture.js` doesn't work?

**Comment by boneskull** [comment]
@ArtemGovorov OK, I'll see what I can produce for you.  

> So importing it once in your test/fixture.js doesn't work?

No, it causes other weird errors.  Probably best for you to just take a look.

**Comment by boneskull** [comment]
@ArtemGovorov 

The code in [this gist](https://gist.github.com/boneskull/b40dfac3b324f06ff999) replicates my issue as per my original report.  If you need to see the Zone.js-related issues as well, I can create an implementation based on that, as well.

**Comment by ArtemGovorov** [comment]
@boneskull Thanks a lot for putting together the gist.

As you've suspected, the issue was the conflict between how wallaby overrides some globals and the way `async-listener` overrides them. For some reason, [`async-listener` only patches `setTimeout` if it was equal to `require('timers').setTimeout`](https://github.com/othiym23/async-listener/blob/master/index.js#L137) and wallaby was only patching `setTimeout` and not the `require('timers').setTimeout`. I'm now patching both in wallaby, so it should be ok. Let me know how if works for you.

*Not related to the issue:*

Please note that with the number of different things that `async-listener` patches (and because it doesn't seem have a way to `unpatch` them), you *may* run into some transient issues because wallaby re-uses node processes to run tests. 

It may not be happening now, but may happen if you're going use some libs that may use things patched by `async-listener`. If you do run into such issues (like tests are passing initially but sometimes incremental runs are failing when you edit code/tests), just set [`workers: { recycle: true }`](http://wallabyjs.com/docs/config/workers.html), so that node processes are re-created. 

Obviously it's less performant than reusing node processes, but until `async-listener` supports a way to undo everything it does, it may be the only option. Though one also may try to clean up things in the [`teardown` function](http://wallabyjs.com/docs/config/bootstrap.html#teardown-function).
