### ISSUE TITLE
Checking Code Coverage - Pre Push Hook??

### ISSUE THREAD

**Issue by imjakechapman** [wallabyjs/public#525]
I can't seem to find anything in regards to wallaby to making sure code coverage is checked and a specific percentage and all written tests are passing before allowing a push to github using a pre push hook. 

Do you have any solutions available or sending me in the right direction?

**Comment by ArtemGovorov** [comment]
Hi,

It's currently not possible, because there's no way to run wallaby.js without being hosted as an editor/IDE plugin. We have the feature request you may subscribe to: https://github.com/wallabyjs/public/issues/72. We also have the feature request for the code coverage report: https://github.com/wallabyjs/public/issues/38.
