### ISSUE TITLE
babel-node: "Failed to load configuration file:  Files property must be non-empty array of files/file patterns"

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#530]
### Issue

Currently I'm trying to use `babel-node` as `Node.js` interpreter for `wallaby`.

I tried to use the same config for some my projects and I was surprised that it worked for many of them and also it didn't work for some of them.

I am using:

```
"babel-node": "6.6.5"
```

I have got the error:

```
wallaby.js started
core v1.0.208
Failed to load configuration file:  Files property must be non-empty array of files/file patterns
```

### Wallaby.js configuration file

```javascript
export default wallaby => {
    return {
        files: [
            'src/**/*.js'
        ],
        tests: [
            'test/**/*.spec.js'
        ],
        testFramework: 'jasmine',
        env: {
            type: 'node'
        },
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babelrc: true
            })
        }
    };
};
```

### Code editor or IDE name and version

WebStorm 2016.1

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Wallaby core expects config file to export a function.
Your `babel-node` compiled config [exports an object](https://babeljs.io/repl/#?evaluate=true&presets=es2015%2Ces2015-loose%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=true&loose=true&spec=true&code=export%20default%20wallaby%20%3D%3E%20%7B%0A%20%20return%20%7B%0A%20%20%20%20files%3A%20%5B%0A%20%20%20%20%20%20'src%2F**%2F*.js'%0A%20%20%20%20%5D%2C%0A%20%20%20%20tests%3A%20%5B%0A%20%20%20%20%20%20'test%2F**%2F*.spec.js'%0A%20%20%20%20%5D%2C%0A%20%20%20%20testFramework%3A%20'jasmine'%2C%0A%20%20%20%20env%3A%20%7B%0A%20%20%20%20%20%20type%3A%20'node'%0A%20%20%20%20%7D%2C%0A%20%20%20%20compilers%3A%20%7B%0A%20%20%20%20%20%20'**%2F*.js'%3A%20wallaby.compilers.babel(%7B%0A%20%20%20%20%20%20%20%20babelrc%3A%20true%0A%20%20%20%20%20%20%7D)%0A%20%20%20%20%7D%0A%20%20%7D%3B%0A%7D%3B) and not a function as expected by wallaby.

**Comment by ArtemGovorov** [comment]
The solution would be not to use ES6 exports and just use `module.exports`:
```javascript
module.exports = wallaby => {
    return {
        files: [
            'src/**/*.js'
        ],
        tests: [
            'test/**/*.spec.js'
        ],
        testFramework: 'jasmine',
        env: {
            type: 'node'
        },
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babelrc: true
            })
        }
    };
};
```
Anyway, I think using `babel-node` as node for wallaby core may be a bit of an overkill. From what I [read in the docs](https://babeljs.io/docs/usage/cli/#babel-node) using babel-node may slow down wallaby startup. 

I also have a suspicion that there will be a slowdown for your source code and tests as well. Because first wallaby.js will compile your source code with babel that you have configured in your config, then `babel-node` will compile the compiled code once again. And while wallaby babel compiler caches compiled files on disk (so there's no recompilation, only for a changed file), `babel-node` will recompiled everything every time (because it stores the cache in memory and it gets reset for every test run).

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks alot for the response. I know about this workaround and I used it for now, but I don't have any ideas why it worked for some projects and in this time it didn't work for the rest.

Anyway thanks for help and I just want to let you know about this issue.

**Comment by ArtemGovorov** [comment]
You mean the exact same config worked in other projects? If so, it's really puzzling and I have no idea how it could work. Nothing changed in wallaby in how it loads the config since day one (it has always required a function), perhaps when it worked you have used a different version of `babel-node` that was compiling things differently?

**Comment by mdreizin** [comment]
@ArtemGovorov Yes, I'm using the same config for all projects and the same version of `babel-node`. Can I provide any additional information?

**Comment by ArtemGovorov** [comment]
Well, since it's the exact same config and project source files don't matter (because in this case wallaby fails before it has a chance to load them), there has to be something else different between a project where it works and a project where it doesn't. Not even sure what would be the meaningful difference. I don't think project name or wallaby config file name matters. So honestly I'm not even sure what additional information to ask for, except perhaps a copy of a project where it works (you may remove all files from it, it shouldn't matter as long as it still works).

Regardless whether we find out why some projects worked, I have made some changes to the core to make it always work for this case. The support is available in the latest core v1.0.209.

**Comment by mdreizin** [comment]
@ArtemGovorov I am much obliged to you for your help.

**Comment by mdreizin** [comment]
@ArtemGovorov How to get `core v1.0.209`?

**Comment by ArtemGovorov** [comment]
In WebStorm it gets automatically updated after the next wallaby.js restart (with 20 minute interval between new version checks). If it wasn't updated, try restarting your IDE and starting wallaby.js - it should be updated.

**Comment by mdreizin** [comment]
@ArtemGovorov Unlucky it didn't work for me, but I have just removed:

`rm -rf ./wallaby/wallaby`

and got new version.

Now it works fine as I expected.

Thank you so much.

**Comment by mdreizin** [comment]
@ArtemGovorov I have tested it and it worked fine without any issues.

**NOTE**: You need to have latest `WebStorm EAP`. Please see more info http://blog.jetbrains.com/webstorm/2016/03/webstorm-2016-1-eap-build-145-596-bug-fixes/

```
WebStorm WS-145.596.9
Build #WS-145.596, built on March 24, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

with the following config:

```js
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "transform-runtime"
  ],
  "ignore": [
    "node_modules/",
    "wallaby/"
  ]
}
```

**Comment by QuantumInformation** [comment]
I am pointing it to this config for auto config but get the same error:

```js
const config = {
  testEnvironment: "node",
  moduleFileExtensions: ["js", "json"],
  transform: {
    "^.+\\.(js|mjs)$": "@foo/dev.jest/transformer.js"
  },
  roots: ["<rootDir>/src"],
  collectCoverageFrom: ["<rootDir>/src/**/*.js", "!<rootDir>/src/**/*.test.js"],
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80
    }
  },
  coverageDirectory: "coverage",
  clearMocks: true
};

module.exports = config;
```

We run jest and all test run without needing files prop.
