### ISSUE TITLE
Mocha preferred in nodejs rather than jasmine ?

### ISSUE THREAD

**Issue by binarysqueeze** [wallabyjs/public#534]
Hi,

can anyone tell me why wallaby support jasmine (by default) in the browser and mocha (by default) in nodejs ?

I know this can be changed, I just wanted to know the reason behind it, if anything specific. I have been using jasmine for the browser and I was about to continue using it for nodejs but notice there seems to be a preference here.

Any ideas ?

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
The reason is pretty simple, we have tried to set the default option to be what most users would expect it to be. When wallaby.js was created, jasmine was a bit more popular option for the browser testing, so it became the default option in wallaby settings. In the node land mocha was much popular so it became the default option there.

There's absolutely no technical or support preference, we were and are supporting both mocha and jasmine equally.
