### ISSUE TITLE
Loading mocha with custom interface?

### ISSUE THREAD

**Issue by kwonoj** [wallabyjs/public#536]
### Issue description or question
I have migrated test runner from jasmine to mocha, along with adapting custom interfaces at https://github.com/ReactiveX/rxjs/blob/master/spec/helpers/testScheduler-ui.ts .

in local node.js environment, command line can be constructed as below

```sh
--require spec-js/helpers/test-helper.js
--require spec-js/helpers/ajax-helper.js
--require spec-js/helpers/marble-testing.js
--ui spec-js/helpers/testScheduler-ui.js

--recursive
```

to require dependencies, then specify custom ui - is there way to achieve via wallaby configuration? 

I did quick try such as 

```js
bootstrap: function (w) {
    // Global test helpers
    ....
    var mocha = wallaby.testFramework;
    require('./spec/helpers/testScheduler-ui');
    mocha.ui('testscheduler-ui');
  }
```

but mocha can't locate custom interface.

### Wallaby.js configuration file

https://github.com/ReactiveX/rxjs/blob/master/wallaby.js

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
First of all you need to remove `testFramework: 'jasmine',` from the config as you are not using jasmine, but mocha now. Here is the solution for custom UI:

```javascript
bootstrap: function (w) {
    var path = require('path');
    // Global test helpers
    ....
    delete global.asDiagram;
    var mocha = wallaby.testFramework;
    mocha.ui(path.resolve(w.projectCacheDir, 'spec/helpers/testScheduler-ui'));
  }
```

Note that I have also added `delete global.asDiagram;`. 
Here is why: [wallaby for node by default re-uses node processes](http://wallabyjs.com/docs/integration/node.html#node-process-reuse), but the `spec/helpers/testScheduler-ui.ts` sets up the environment in way that breaks the process reuse.
For example, you capture 
```javascript
const diagramFunction = global.asDiagram;
```
and later on setting 
```javascript
context.asDiagram = ...
``` 
where the `diagramFunction` is used.
The problem is that the `context` is the `global` for the root suite, so after one run, all of your `asDiagram(...)(...)` tests will stop executing.

There may be some other issues like that in the file, I didn't spot anything else though. If you hit some, the solution would be either to try and make the file node process re-use friendly, or adjust things in the `bootstrap` (like I did with the `asDiagram`), or, if nothing else helps, you may [turn off the process re-use by setting `workers.recycle: true`](http://wallabyjs.com/docs/integration/node.html#node-process-reuse) and make wallaby behave more like mocha CLI in that regard.

There's also a failing test in your `spec/observables/from-promise-spec.ts` file, the one that is throwing a global error. The issue with it that it only removes mocha original exception handler, but wallaby has its own, so it reports the error. You may slightly modify the test to remove *all* `uncaughtException` handlers and put them back in the test handler:

```javascript
if (typeof process === 'object' && Object.prototype.toString.call(process) === '[object process]') {
    it('should globally throw unhandled errors on process', (done: MochaDone) => {
        const originalException = process.listeners('uncaughtException');
        process.removeAllListeners('uncaughtException');
        process.once('uncaughtException', function (error) {
            originalException.forEach(l => process.addListener('uncaughtException', l));
            ...
        });
...
```

**Comment by kwonoj** [comment]
Appreciate for help, it works great :)
