### ISSUE TITLE
Please consider adding an "offline" mode for installing wallaby.js

### ISSUE THREAD

**Issue by tsawan** [wallabyjs/public#571]
### Feature request

Please consider adding a configure option so wallaby can work in offline mode. This will help using wallaby on machines with limited/no internet access by manually copying required dependencies.

**Comment by ArtemGovorov** [comment]
Just to make it clear, wallaby can work without internet access, but to install it the first time the internet may still be required (as it downloads some dependencies, as you know).

**Comment by terwalsh** [comment]
Hi Artem, I am behind a corporate firewall that will not allow any outside connections (I know - groan).  Is there any way possible to do it manually?  I can copy and paste files/dependencies across if it helps.  At the moment I am doing a lot of sketching on my laptop with a licensed copy of Wallaby, which is fantastic btw but this is becoming unworkable.  Cheers, T

**Comment by ArtemGovorov** [comment]
@terwalsh 
> I can copy and paste files/dependencies across if it helps

This may work if your laptop has the same OS that the target machine has. What OS are you using and what editor?

**Comment by terwalsh** [comment]
Webstorm with Mac on my laptop and I can use Webstorm but on Windows for work.

I thought I could achieve an offline install as I specified electron in my wallaby.config of the project I'm currently working on and I can install this locally but Wallaby still wants to download phantom.  I built a Windows 8 VM this morning hoping to simulate an offline install so I have this ready to go if it helps.

Thanks for the speedy reply Artem!

**Comment by ArtemGovorov** [comment]
Try this:
- Copy the `~/Library/Caches/WebStormX/wallaby` folder (where `X` is your Webstorm version) to the `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.WebstromX\system\` folder on your Windows machine;
- Open the `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.WebstromX\system\wallaby` folder on your Windows machine, then open the `phantomjs_v1.9.8` subfolder and rename the `phantomjs` file to `phantomjs.exe`. It doesn't matter that we're just renaming OSX built phantom, because you're using Electron runner, but if you ever need Phantom runner, you will need to download the one for Windows and place it there.
- Open the `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.WebstromX\system\wallaby` folder on your Windows machine, then open the `node_v4.2.2` subfolder, delete the `node` file there, download and copy any node.exe compatible with your OS and with version >= 4.2.2. For example, for 64bit Windows, you [may use this one](https://nodejs.org/dist/v4.4.5/win-x64/) or [this one for x86](https://nodejs.org/dist/v4.4.5/win-x86/). Note that you may override the version later in your wallaby Run Configuration settings in WebStorm, if you do that, it's important to just have some node.exe there.

**Comment by terwalsh** [comment]
Hey Artem, this works a treat.  Thank you so much for your prompt assistance!  T

**Comment by andreashoffmann** [comment]
Hi Artem,

I have the same problem in a corporate environment using Visual Studio 2013/2015. Do you have some instructions for that, too?

THX

**Comment by ArtemGovorov** [comment]
@andreashoffmann Should be a bit easier on Windows:
- Install wallaby extension in some unrestricted environment on Windows for Visual Studio 2013/2015, and run it at least once on any project, so it downloads all the required dependencies.
- Install wallaby extension in the restricted environment. Copy the `<SYSTEM DRIVE>\Users\<USER ACCOUNT NAME>\.wallaby` folder from the unrestricted environment to the corresponding folder in the restricted environment.

**Comment by Janatbek** [comment]
What are required dependencies?
Can I download them manually into that folder?

**Comment by ArtemGovorov** [comment]
@Janatbek I have sent you the link here because you said you are using Visual Studio, but apparently you are using VS Code. 

Please follow the instructions for your editor described here: https://wallabyjs.com/docs/intro/troubleshooting.html#offline-installation.

**Comment by kubal5003** [comment]
In corporate network a good solution is to configure Fiddler proxy to forward the traffic to a locally downloaded file (Autoresponder rules). This solution does work if you're able to get those files somehow before, which for me was not really a problem.

**Comment by smcenlly** [comment]
We have no plans to add a separate offline installation kit, but instructions for offline installation are [detailed in our docs](https://wallabyjs.com/docs/intro/offline.html).
