### ISSUE TITLE
Wallaby, Webpack and React Hot Loader

### ISSUE THREAD

**Issue by marclar** [wallabyjs/public#59]
I'm trying to get Wallaby working for a project based on [this admin template](https://wrapbootstrap.com/theme/rubix-reactjs-powered-admin-template-WB09498FH).

The template is great and I only need to run the dev server to get immediate feedback while coding. Fantastic time savings, just like Wallaby offers.

Unfortunately, the template doesn't come with any tests, and I'm having a hell of a time trying to add a test for Wallaby that'll run with this template's React components. Any given component might include another component by calling `require()`, which fails. And trying to test individual components fails because they use node syntax like `module.exports = Sidebar;` instead of a pure JS closure like I see in the TodoMVC sample.

I realize this may be a complex scenario -- retrofitting tests onto a project with React-Router, React-Hot-Loader, Webpack Dev Server, etc.

Any pointers? I'm happy to buy you a license if you can help me figure it out. :money_with_wings:

**Comment by ArtemGovorov** [comment]
Wallaby.js supports webpack (and browserify) - https://github.com/jeffling/wallaby-webpack, so CommonJs in supported.
It's pretty simple to set up, especially if you already have some webpack config. You may start with this sample https://github.com/wallabyjs/wallaby-webpack-sample (it uses ES6 modules exports and imports, but you may just remove babel preprocessor and use good old `module.exports` and `require()`)
Please let me know if it works for you, otherwise please share some code/example that doesn't and we'll try to make it work.

**Comment by marclar** [comment]
Thanks so much, @ArtemGovorov. I've tried combining some of your sample projects, but still haven't figured it out. I'm guessing it's just a misunderstanding of how webpack works, or how JSX is compiled prior to testing with Wallaby.

Anyway, I put together a stripped-down version of my project and added some configuration from **wallaby-webpack** and **wallaby-react-component**. That repo is here: https://github.com/marclar/wallaby-test-config

Your React components are in `/src/jsx/app/components`, e.g. [UserProfile.jsx](https://github.com/marclar/wallaby-test-config/blob/master/src/jsx/app/components/UserProfile.jsx).

My existing React components (that I want to test) are in `/src/jsx/app/common`, e.g. [sidebar.jsx](https://github.com/marclar/wallaby-test-config/blob/master/src/jsx/app/common/sidebar.jsx).

If you `npm install` then run `gulp`, it'll open a browser automatically and you can see the live reloading working with the existing components.

If you run Wallaby, you'll see it works with your components.

However, when I add a line like `var Fluxxor = require('fluxxor');` to the top of a component, it breaks.

**Comment by ArtemGovorov** [comment]
@marclar Thanks for creating the repo! You were very close to make it work. I have sent you a pull request with a couple of changes. The main issue was that `'src/jsx/app/components/**'` was specified as a string and by default it means `load:true`, so all of the files there are loaded in browser (with `<script>` tag). However, in case of webpack we don't want it, because everything is loaded differently. Webpack analyzes the source code, starting from entry points (tests) it traverses dependency tree and compiles everything into something that browser can execute, it wraps every file source code to provide an implementation for `require` and `module.exports`. So everything that is supposed to be `require()`-d should have `load:false`. Otherwise, the file is just loaded normally (with `<script>` tag), so trying to use `require()` inside it causes the error you have been observing.

Certain things that are globally available may need to be loaded separately (with `<script>` tag), so would need to have `load:true` (default value). For example, I have noticed that React itself is not `require()`-d anywhere in your jsx files, so it does make sense to have it without `load:false`, just like you have.

Other changes I have made are mostly to make my components CommonJs friendly by exporting them with `module.exports` and importing with `require` from within each other and `avatarSpec.jsx`.

**Comment by marclar** [comment]
Man, you're the best -- thank you.

And thanks for the explanation; makes sense now.

I wonder if it would be good to change the name of the `load` attribute to `browser` or something. Granted, I'm unfamiliar with most of the code and how it works, but when I list file paths, I assume they'll be "loaded", whatever that means. That because they're referenced, they'll be included in the execution context somehow.

To say "here's a file but don't load it" is a bit confusing -- whereas saying "here's a file but it's not meant for the browser" seems a little more clear.

Maybe off-topic, but where is the "sandbox HTML" generated? Is it a virtual DOM representation provided by PhantomJS?

**Comment by ArtemGovorov** [comment]
I see your point and I was struggling to get a good name for the setting.

When files are listed it means that wallaby will track them, so when some of the files changes locally, it will be copied to wallaby cache and, if required, instrumented and, if required, will trigger related tests to run. More details described [in the doco](https://github.com/wallabyjs/public#file-object).

`load:true` for JavaScript files basically means `loadFileImmediatelyViaScriptTag`, while `load:false` means that wallaby should do whatever it does (cache, instrumentation, tests triggering), but not add `<script src="thatFile.js" />` to the generated sandbox. But including `ViaScriptTag` in the name is not a good choice, because it only applies to JS files, but there are also CSS files and images.

You are correct that listed files will be included/loaded in the execution context somehow, in case of webpack it happens when you call `window.__moduleBundler.loadTests();` in the bootstrap function. However, the same argument can be applied to the suggested `browser` name - all the files will end up in browser anyway.

Maybe we should try to reflect loading timing in the name - in case of `load:true` the file is loaded immediately, in case of `load:false` it will be loaded later. BTW, it may never be loaded (for example if nothing `require`s it).

Sandbox HTML is regenerated for each run, it sits in memory and is served from wallaby.js web server when tests run. It's pretty simple: list of `script` tags of files with `load:true`, few `script` tags with testing framework parts, `script` tag with `bootstrap` function.
