### ISSUE TITLE
Error reporting in atom, text with < and >

### ISSUE THREAD

**Issue by epsitec** [wallabyjs/public#595]
HTML code found in `describe()` or `it()` functions is not escaped before displaying the
error message in Wallaby.js panel:

![wallaby-6](https://cloud.githubusercontent.com/assets/3872435/15174732/5a546160-1763-11e6-9b2e-df9423aefec2.png)

**Comment by ArtemGovorov** [comment]
Good find, thanks. Fixed in the core v1.0.227, should be updated automatically within a few minutes (or you may [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update)). Note that in this specific case, after the core is updated, the editor restart is required.

**Comment by epsitec** [comment]
Thanks a lot. As always, your quick response makes me wonder how many Artem clones you have ;-)
