### ISSUE TITLE
Wallaby License reminder is very annoying

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#599]
### Wallaby License remindes shows in each IDE window on each start

Wallaby reminds about the license expiration in a very annoying way. It should not appear more than 1 time.

![2016-05-19 at 13 01](https://cloud.githubusercontent.com/assets/11071/15391569/1c16d882-1dc2-11e6-867b-46582fd6f386.png)

### Code editor or IDE name and version

IntelliJ IDEA v2016

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
It's a pretty standard behavior for the IntelliJ platform. If you have some plugins that are not up-to-date or a newer version of the IDE, it'll do the same.

It's pretty easy to turn the notification off: 

<img width="815" alt="screen shot 2016-05-19 at 9 06 26 pm" src="https://cloud.githubusercontent.com/assets/979966/15391639/9f16405e-1e05-11e6-8c6b-f6f7168bd83e.png">

Just select `No popup` option instead of the default `Sticky balloon`.

**Comment by ArtemGovorov** [comment]
I have also added a shortcut to mute the notification group right from the popup, so in the latest v1.0.61 it looks like:

<img width="496" alt="screen shot 2016-05-19 at 10 19 08 pm" src="https://cloud.githubusercontent.com/assets/979966/15393501/0e02aa7e-1e11-11e6-8564-f8244cbb7410.png">
