### ISSUE TITLE
Post processor fails for relative paths

### ISSUE THREAD

**Issue by nim23** [wallabyjs/public#615]
### Issue description or question
Here is a link to sample repo https://github.com/nim23/wallaby-test which tries to replicate the scenario of a real life project I am working on. In [Application.spec.js](https://github.com/nim23/wallaby-test/blob/dev/src/javascript/components/Application.spec.js) as soon as I `import Application from './Application.jsx'` wallabify fails to import the relative module dependencies causing wallaby to fail. 

### Wallaby.js configuration file

```javascript
'use strict'
let wallabify = require('wallabify')
let babel = require('babel')
let wallabyPostProcessor = wallabify({})

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false},
      {pattern: 'src/utils/karma.polyfill.js', instrument: false},
      {pattern: 'src/**/*.json', instrument: false, load: false},
      {pattern: 'src/**/*.js*', load: false},
      {pattern: 'src/**/*.spec.js', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*.spec.js', load: false}
    ],

    postprocessor: wallabyPostProcessor,

    setup: function () {
      // required to trigger tests loading
      window.__moduleBundler.loadTests()
    },

    compilers: {
      'src/**/*.js*': wallaby.compilers.babel({
        stage: 2
      })
    },

    debug: true
  }
}
```

### Code editor or IDE name and version
Visual Studio Code v0.10.x

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Have sent you the pull request: https://github.com/nim23/wallaby-test/pull/1

Browserify needs `extensions` set to be able to compile `jsx` (hence was the error with JSX files), so I just copied the setting [from your config file](https://github.com/nim23/wallaby-test/blob/dev/gulp/config.js#L49).
I have also remove a file that doesn't exist from your `files` list.

Note that you also need to 
```javascript
npm install babel-polyfill --save-dev
```
because you are using it in your wallaby config `files` (and it is required), but it's not in your `package.json`.

**Comment by nim23** [comment]
Thanks for the pull request, really looking forward to using wallaby in my current project. Love the instant feedback of the test, as the previous way of running the test was a bit tedious on my current project.
