### ISSUE TITLE
how to test expressjs middlewave ?

### ISSUE THREAD

**Issue by sliuqin** [wallabyjs/public#619]
I want to test a express app, but can't find a example.

**Comment by ArtemGovorov** [comment]
There're not many wallaby specific hints in testing an express app. You just create a [node.js config for wallaby](https://wallabyjs.com/docs/integration/node.html) and run your mocha (or other testing framework) tests with wallaby. One wallaby.js specific note is, if you are going to spin up a web server, you may either [limit workers count or use `0` as a port so that wallaby could create many express servers in parallel](http://stackoverflow.com/questions/30178023/avoiding-eaddrinuse-when-using-wallaby-js-with-an-express-project).

Regarding how you write your express app tests is totally up to you. There are lots of different approaches covered: [example 1](http://stackoverflow.com/questions/34516951/express-middleware-testing-mocha-chai), [example 2](http://stackoverflow.com/questions/8831984/how-do-i-test-my-express-app-with-mocha?rq=1).

If you have an app with express tests that you're having issues configuring wallaby.js for, let me know by sharing a link and I'll have a look.

**Comment by sliuqin** [comment]
@ArtemGovorov  , thanks for you reply. 

I have fix the `EADDRINUSE` error with the new `wallaby.js`
```
module.exports = function (wallaby) {
  return {
    files: [
      'src/app/**/*.js',
      'src/utils/**/*.js',
      'package.json',
      'src/test/init.js',
      'public/test/**/*',
    ],

    tests: [
      'src/test/**/*Spec.js'
    ],
    testFramework: 'mocha',

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        babelrc: true,
      })
    },
    env: {
      type: 'node',
      runner: 'node',
      params: {
        env: 'DEBUG=ibe-*;NODE_ENV=test;WALLABY=1;'
      }
    },
    workers: {
      initial: 1,
      regular: 1,
      recycle: true
    }
  };
};

```

and get the correct test response ：
<img width="906" alt="homespec js - ibe-home - -projects-ibetterme-parse-ibe-home webstorm today at 10 12 02 pm" src="https://cloud.githubusercontent.com/assets/590735/15651705/dc26dd9e-26b3-11e6-8eac-38e64be7c33b.png">

BUT，wallaby show it not cover the code.
<img width="522" alt="home js - ibe-home - -projects-ibetterme-parse-ibe-home webstorm today at 10 13 29 pm" src="https://cloud.githubusercontent.com/assets/590735/15651730/f05db17a-26b3-11e6-9097-b3af31c6ae86.png">

**Comment by sliuqin** [comment]
work for me now . thanks
