### ISSUE TITLE
Hook 'setup' (in wallaby.js) causing issues when tests are re-run ; explained inside

### ISSUE THREAD

**Issue by ianjohnspain** [wallabyjs/public#625]
Hi,

I seem to be getting issues when running tests, the first time the tests run OK and then when I break something and the tests re-run they report the following error

```
Runtime error: TypeError: Cannot read property '0' of undefined
    at Object.<anonymous> (./src/test/javascript/server/testConfiguration.js:2:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

 specifically this is the line thats failing (which is find in a js file that is called from my wallany 'setup' hook, explained below.

`require('module').Module._initPaths();`

This is the wallaby config file, notice my hook, setup

### Wallaby.js configuration file

```
module.exports = function (wallaby) {
  return {
    files: [
      'src/main/javascript/server/**/*.js'
    ],

    tests: [
      'src/test/javascript/server/**/*.js'
    ],

    testFramework: 'mocha',

    env: {
      type: 'node',
      params: {
        env: 'NODE_PATH=' + wallaby.projectCacheDir
      }
    },

    setup: function (wallaby) {
      require('src/test/javascript/server/testConfiguration'); // setup globals and workaround for require 
    }
  };
};
```

You will notice above, this calls into the testConfiguration.js file which is displayed below. This is so that I can using standard require (src/.......) and not require(../../../.. etc AND it also sets up some globals that I use.

Can anyone help, maybe I am using the wrong hook ? I did try the "bootstrap" hook, but same thing happened.

### testConfiguration.js called from hook

```
require('module').Module._initPaths(); //when re-rerunning the tests it seems to error on this line.

var chai = require('chai');
var chaiAsPromised = require('chai-as-promised');
chai.use(chaiAsPromised);
```

```javascript

```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Hi,

The issue is that `tests` pattern contains some files that are not file with tests and wallaby requires that [only actual test files should be specified in the tests list](https://wallabyjs.com/docs/config/files.html#tests), i.e. the files with specs/tests (for example with describe/it for mocha/jasmine).
The `testConfiguration.js` file satisfies the `tests` pattern, but not a file with tests.
If your test names follow some naming pattern, like `*-spec.js`, you may use it in your config:
```javascript
files: [
      'src/main/javascript/server/**/*.js',
      'src/test/javascript/server/**/*.js',
      '!src/test/javascript/server/**/*-spec.js',
    ],
tests: [
      'src/test/javascript/server/**/*-spec.js'
    ],
```
(and include the rest of the files to the `files` list if required).

Please let me know it helps.

**Comment by ianjohnspain** [comment]
thanks @ArtemGovorov, this indeed works. Is there anyway to support this without renaming files to have a suffix ?

I tried using the       '!src/test/javascript/server/testConfiguration.js'

but this didn;t seem to work.

If there is no other way then I will refactor all the files, just thought it would be possible to do it without being forced to refactoring)

Thanks again

**Comment by ArtemGovorov** [comment]
If there's no naming pattern that your test files follow, you may individually exclude all not test files from the `tests` list and include them into the `files` list. So this should work:
```
files: [
      'src/main/javascript/server/**/*.js',
      'src/test/javascript/server/testConfiguration.js'
    ],
tests: [
      '!src/test/javascript/server/testConfiguration.js',
      'src/test/javascript/server/**/*.js',
    ],
```
if the `testConfiguration` is **the only file that is not a test file** in the `src/test/javascript/server` folder. Otherwise you'll need to do the same for all files that are not tests in the `src/test/javascript/server` folder.

**Comment by ianjohnspain** [comment]
Thanks again, it now works, maybe it was the order. Anyway, all working now. Thanks again for the help.
