### ISSUE TITLE
Ignoring require('.css') with wallaby and TypeScript (Jest)

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#628]
### Issue description or question

I'm able to fully ignore `.css` imports using my `jestPreprocessor` (it filters lines requiring css files out completely). However, wallaby doesn't seem to notice that and reports an error in the form of:

![image](https://cloud.githubusercontent.com/assets/5240018/15755032/04f90eec-28c9-11e6-9b24-5b8c31eb2fd8.png)

Is there any way I can tell wallaby to just shut up and ignore it?

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            'wp-content/**/*.tsx',
            'wp-content/**/*.ts',
            'typings/**/*.d.ts',
            'test-utils/*',
            '!wp-content/**/__tests__/*',
        ],
        tests: [
            'wp-content/**/__tests__/*-test.tsx',
            'wp-content/**/__tests__/*-test.ts',
        ],
        env: {
            type: 'node',
            runner: 'node',
        },
        testFramework: 'jest',
        bootstrap: function (wallaby) {
            wallaby.testFramework.configure({
                'scriptPreprocessor': 'jestPreprocessor.js',
                'testRegex': '__tests__/.*\\.(js|ts|tsx)$',
                'moduleFileExtensions': [
                  'js',
                  'ts',
                  'tsx',
                  'json'
                ],
                'unmockedModulePathPatterns': [
                  'react',
                  'react-dom',
                  'react-addons-test-utils',
                  'enzyme',
                  'sinon',
                  '<rootDir>/test-utils/Mocks',
                ],
            });
        }
    };
};

```

**Jest Preprocessor**

```js
/* eslint-env node, es6 */
const tsc = require('typescript');
const fs = require('fs');
const DEBUG_FILE = false;

module.exports = {
    process(src, path) {
        if (path.endsWith('.ts') || path.endsWith('.tsx')) {
            return transpile(src, path, DEBUG_FILE);
        }
        return src;
    },
};


// Debug function to help weed out transpiled nonsense that negatively affects testing
function transpile(src, path, debugFile) {
    if (!debugFile) {
        return (
            tsc.transpile(
                src, {
                    module: tsc.ModuleKind.CommonJS,
                    jsx: tsc.JsxEmit.React,
                },
                path, []
            )
            .replace(/(}\)\()(.*\|\|.*;)/g, '$1/* istanbul ignore next */$2')
            .replace(/(var __extends = \(this && this.__extends\))/g, '$1/* istanbul ignore next */')
            .replace(/(var __assign = \(this && this.__assign\) \|\| Object.assign)/g, '$1 /* istanbul ignore next */')
            .replace(/^(require|import).*\.css.*;$/gm, '')
        );
    }

    const fs = require('fs');
    const code = tsc.transpile(
        src, {
            module: tsc.ModuleKind.CommonJS,
            jsx: tsc.JsxEmit.React,
        },
        path, []
    )
    .replace(/(}\)\()(.*\|\|.*;)/g, '$1/* istanbul ignore next */$2')
    .replace(/(var __extends = \(this && this.__extends\))/g, '$1/* istanbul ignore next */')
    .replace(/(var __assign = \(this && this.__assign\) \|\| Object.assign)/g, '$1 /* istanbul ignore next */')
    .replace(/^(require|import).*\.css.*;$/gm, '');


    if (path.endsWith(debugFile)) fs.writeFileSync('DEBUG_FILE.js', code);
    return code;

}
```

### Code editor or IDE name and version

Atom Latest

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment]
Wallaby uses its own TS compiler (to compile your TS code, collect code coverage, etc.), so it doesn't use your `jestPreprocessor` at all.

The easiest way to get rid of loading CSS files with `jest` would be to use the [`moduleNameMapper`](http://facebook.github.io/jest/docs/api.html#modulenamemapper-object-string-string)

```javascript
 bootstrap: function (wallaby) {
            wallaby.testFramework.configure({
                // you may remove the `scriptPreprocessor` as it's not used anyway
                'moduleNameMapper': {
                    '.*\.css$': require('path').join(wallaby.localProjectDir, 'jestPreprocessor.js')
                },
                ...
```
I'm just pointing all `.css` require/import calls to existing file, your `jestPreprocessor.js` in this case, but it doesn't even matter what the file is, can be anything, even a dummy empty file.

**Comment by dsifford** [comment]
Thank you so much (again) for the clarification @ArtemGovorov 

I greatly appreciate how patient and helpful you've been!

**Comment by Floriferous** [comment]
How do you solve this if you don't use jest? 

Why doesn't something like this work:
```js
files: [
   // other stuff...

    { pattern: '!node_modules/**/*.css', ignore: true },
],
```

**Comment by smcenlly** [comment]
Without a bit more detail, our guidance may be a little wrong. If what we've said below doesn't help you, please create a new issue for us with a sample repo that duplicates your problem.

I'm assuming as per the title of this issue, you have a `require` statement that imports a `.css` file and you don't want to import that file. The logic that imports your `.css` is in your TypeScript file that you want to run, so ignoring your `.css` classes in your Wallaby files isn't going to help you.

You need to either change the code that wallaby runs for you to remove the `require`/`import` statement or you need to change the module resolution at runtime so that it resolves a different (e.g. empty) file.

You could configure a [preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) to strip the `.css` imports. If you do this, you may also need to produce a source map (depending on how your files are structured and the extent of the change), which could be complex.

Another option is to change the module resolution of your `,css` imports, which is the solution provided above for `jest`. You can either find/use an existing module mapping library, or you can write your own. We're familiar with `module-alias`, but I believe you would need to specify each `.css` file with this library, which may not be possible for you. Please find an example that uses `module-alias` below:

```javascript
module.exports = () => ({
  files: ['app/src/**/*.js', '!app/src/**/*.css'],
  tests: ['app/tests/**/*.test.js'],
  env: {
    type: 'node',
    runner: 'node',
  },
  setup: function(wallaby) {
    const path = require('path');
    const moduleAlias = require('module-alias')

    moduleAlias.addAlias('myfile.css', path.join(wallaby.projectCacheDir, 'app/src/dummy.js'));
  }
});
```

If you can't find an existing library or want to write your own module mapping function, I would suggest looking at [`module-alias` source](https://github.com/ilearnio/module-alias/blob/master/index.js). Specifically, you will need to duck punch `require('module')`'s `_resolveFilename` function.
