### ISSUE TITLE
Wallaby is not *just* working in new Node versions

### ISSUE THREAD

**Issue by dijs** [wallabyjs/public#633]
### Issue description or question

Error in dev console:
`Wallaby Console: node: bad option: --harmony_arrow_functions`

### Wallaby.js configuration file

```javascript
module.exports = function(wallaby) {
  return {
    env: {
      type: 'node',
    },
    files: [
      'lib/react/widgets/Foo.js',
    ],
    tests: [
      'lib/react/widgets/test/testFoo.js',
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel(),
    },
    debug: true,
  };
};

```

### Code editor or IDE name and version

Atom v1.8.0

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Seems like your version of wallaby.js core is too old because the issue has been fixed quite a while a go (perhaps you haven't used wallaby for a while). The core should be updated automatically after you start wallaby within a few minutes, you may also [force the core update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by fvanwijk** [comment]
Forcing core update for IntelliJ fails on my machine, because Wallaby isn't even starting. Wallaby version 1.0.58 (to be updated) and Node 6.3.1.

When Wallaby starts I see the console error:
> /usr/local/bin/node: bad option: --harmony_arrow_functions

You could improve the docs by stating that you have to start Wallaby with a clean config (to be sure that `<IntelliJ cache dir>/wallaby/node_v4.2.2/node` is used)

**Comment by ArtemGovorov** [comment]
@fvanwijk There's [the troubleshooting docs note on it](https://wallabyjs.com/docs/intro/troubleshooting.html#error-unrecognized-flag---harmonyarrowfunctions-or-bad-option---harmonyarrowfunctions), I have just also improved it the way you've suggested (added a note about the clean config).
