### ISSUE TITLE
timeout of 2000ms exceeded

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#639]
Hi,

I'm running quite complex sync test that runs over 2 seconds.
I cannot make wallaby to stop crashing on 2000 ms interval, how can I achieve that?

Thanks

**Comment by ArtemGovorov** [comment]
Wallaby.js itself doesn't set any constraints on the test run time, however testing frameworks do. You didn't share your config, but because you've mentioned 2000ms I'm guessing you are using `mocha`, because `jasmine` has 5000ms default timeout. You may increase the timeout like [described here](http://stackoverflow.com/questions/23492043/change-default-timeout-for-mocha) for a test/spec or using [wallaby `setup` function](https://wallabyjs.com/docs/config/bootstrap.html) (where `mocha` object is passed as `wallaby.testFramework`) for all tests.

**Comment by tomitrescak** [comment]
Yea, I read all those documents, but am still getting the same result:

```
module.exports = (wallaby) => {
  var load = require;

  return {
    files: [
      "imports/parser.js",
      "client/src/tests/stubs.js",
      "client/src/*.ts",
      "client/src/config/*.ts",
      "client/src/visitors/*.ts",
      "client/src/visitors/factories/*.ts",
    ],
    tests: [
      { pattern: 'client/**/*.yaml', instrument: true, load: false, ignore: false },
      "client/src/tests/*.ts"
    ],

    compilers: {
      "**/*.ts*": wallaby.compilers.typeScript({
        module: "commonjs",
        jsx: "react"
      })
    },
    setup: function(wallaby) {
      wallaby.testFramework.DEFAULT_TIMEOUT_INTERVAL = 5000;
      //var mocha = wallaby.testFramework;
      //mocha.setup({ timeout: 5000 });
    },
    env: {
      type: "node"
    },
  };
};
```

**Comment by ArtemGovorov** [comment]
> `wallaby.testFramework.DEFAULT_TIMEOUT_INTERVAL = 5000;`

This is for `jasmine`, but you are using `mocha`. And `mocha.setup` is for browser as [specified in the comment](http://stackoverflow.com/a/31251705/146850), but you're using node environment.

Not sure what else have you been trying, but taking the first example from the SO question I referenced worked for me, it is also [covered in mocha docs quite well](https://mochajs.org/#timeouts):
```javascript
describe('calculator', function() {
  this.timeout(5000);
  ...
```
Also setting the timeout in the `setup` function using `mocha` node API as follows works for me:
```javascript
    setup: function (wallaby) {
      var mocha = wallaby.testFramework;
      mocha.timeout(5000);
    },
```

If nothing from above works for you, please create a sample repo demonstrating the issue.

**Comment by tomitrescak** [comment]
Thanks, that helped.

**Comment by onetom** [comment]
I suspect there is still an issue here, because I consider `wallaby.testFramework.timeout(5000)` a workaround.

I have a `test/mocha.opts` file which contains `--timeout 5000` and it is respected if I run `pnpx mocha` or `pnpm test` directly (with `"test": "mocha"` in `package.json`).

While I've added `test/mocha.opts` to the `files` array of `wallaby.js`, I'm still getting a `2000ms` timeout.

**Comment by ArtemGovorov** [comment]
@onetom Not sure I understand the issue correctly, does calling `wallaby.testFramework.timeout(5000)` work for you? 

> While I've added `test/mocha.opts` to the `files` array of `wallaby.js`, I'm still getting a `2000ms` timeout.

Wallaby doesn't use (and never used) `mocha.opts` file.

**Comment by BenjaminWenzel** [comment]
> Wallaby doesn't use (and never used) mocha.opts file.

Just why?

Using a `mocha.opts` file and additionally configuring `wallaby.js` could lead to inconsistent options. For example you could execute tests through command line and everything seems to be fine, although `wallaby.js` tells you, that something about your tests is incorrect.

**Comment by ArtemGovorov** [comment]
@BenjaminWenzel Mainly because mocha's CLI runner `mocha.opts` handling logic is [implemented in a non reusable way](https://github.com/mochajs/mocha/blob/master/bin/_mocha), so we'd need to re-implement the same in Wallaby. Also the majority of the options are not relevant in Wallaby. What we should probably do is to support those few relevant options, such as `timeout` by reading `mocha.opts` file.

**Comment by BenjaminWenzel** [comment]
@ArtemGovorov That would be great
