### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#640]
Artem. I am writing a two pass transpiler and I wanted to speed up my test by pre-caching the first pass of the transpiration that is done by external library.

The problem is, that when the tests are run, they are always run in the new context. Is there a possibility to access some "global" object where I can store my caches in my tests that can be re-used along multiple test runs? These caches would empty only on wallaby restart or programatically.

**Comment by ArtemGovorov** [comment]
Could you please provide a more detailed example of what you are trying to do, ideally some source code, so that could better understand the problem before trying to come up with a suggestion?

**Comment by tomitrescak** [comment]
I have a test case files (.yaml) files which hold hundreds of different transpiration cases.
These cases are first processed with an external tokeniser and then I am writing a transpolar that writes a new code using tokens.

Old code:

```
for each case C ...
   let a = tokeniser(C.input);
   let b = myFunctionality(a);
   expect(b).to.beEqual(C.output)
```

Now, I want to cache the results of the tokeniser SOMEWHERE so that it permits between test runs

```
for each case C
   if (!cache[C.id]) {
      cache[C.id] = tokeniser(C.input)
   }
   let a = cache[C.id];
   let b = myFunctionality(a);
   expect(b).to.beEqual(C.output)
```

Does this make it clear? Please let me know. Thanks!

**Comment by ArtemGovorov** [comment]
> I want to cache the results of the tokeniser SOMEWHERE so that it persists between test runs

If we are talking about the same [wallaby config from the other issue](https://github.com/wallabyjs/public/issues/639#issuecomment-224788504), then you may just cache your data in any global property you like, because wallaby reuses node processes so the global context persists. For example,

```javascript
it('should be able to cache in global context', () => {
    if (!global.cache) {
      global.cache = {};
      global.cache.test = 1;
    }
    console.log(global.cache.test);
});
```

Though I'm not sure what's supposed to happen if the `C.input` changes. You'll have to somehow invalidate the cache, perhaps by checking the file timestamps.

An alternative solution (if it can be applied in your case), would be to use a [wallaby.js preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) to apply all the transformations you need to your `yaml` files and save them as JSON files, so that you may just easily `require(./transpiled.json)` in your tests. This solution essentially moves the transformations to happen before your tests run and in this case wallaby will only automatically regenerate a JSON file if source YAML file has changed.

I guess both solutions have their pros and cons. You obviously have more knowledge about your scenario than I do to make the right choice.

**Comment by tomitrescak** [comment]
Thanks Artem, that helped!
