### ISSUE TITLE
testing mocha with mocha

### ISSUE THREAD

**Issue by boneskull** [wallabyjs/public#641]
So there's:

```js
{
  testFramework: 'mocha'
}
```

Which means "load the latest version of Mocha".

How can I hack this beast to load the version of Mocha present in the current working directory?

**Comment by boneskull** [comment]
(Also, I'm having trouble understanding how I can tell Mocha to use a certain interface--`bdd`, `tdd`, `qunit`, etc?)

**Comment by ArtemGovorov** [comment]
I have just added the option to specify a path for any version of mocha in the core v1.0.244 (`testFramework.path`, see the example below). Note that in your case wallaby will be loading mocha (as a testing framework) and reusing it over test runs for testing mocha (as a source code). So if you need to update mocha (as a testing framework), you'll need to restart wallaby to use the latest. Or use the [`workers.recycle = true` option](https://wallabyjs.com/docs/config/workers.html) so that wallaby always loads the latest mocha (as a testing framework), but this case may be tricky as you may be in a middle of something and would prefer to use more or less stable version, so the option with caching may be a better one.

Regarding the interface, you may use the wallaby [`setup` function](https://wallabyjs.com/docs/config/bootstrap.html) to get access to the instantiated mocha and set it up before running tests. See the example below.

```javascript
module.exports = wallaby => {
  return {
    ...

    testFramework: {
      type: 'mocha',
      
      // path: 'mocha' // <- this will load mocha from node modules
      
      // or, this will load mocha from any path
      // path: require('path').join(wallaby.localProjectDir, 'src/index.js')
    },

    setup: function (wallaby) {
      // this is the result of `new Mocha()` call,
      // where `Mocha` is imported from the path above
      var mocha = wallaby.testFramework;
      mocha.ui('tdd');
    },

    env: {
      type: 'node'
      ...
    }
  };
```

**Comment by boneskull** [comment]
Too awesome.  Thanks!
