### ISSUE TITLE
"babel-node" as "node" interpreter produces a lot of warnings "it exceeds the max of 100KB"

### ISSUE THREAD

**Issue by mdreizin** [wallabyjs/public#651]
### Issue description

I'm using `babel-node` as `node` interpreter and I get on initial start:

```
[BABEL] Note: The code generator has deoptimised the styling of "/Users/mdreizin/Library/Caches/WebStorm2016.2/wallaby/wallaby/server.js" as it exceeds the max of "100KB".
wallaby.js started
core v1.0.244
```

How get rid of this warnings?

### Wallaby.js configuration file

```javascript
export default wallaby => {
    return {
        files: [
            'src/**/*.js',
            'test/fixtures/**/*.js'
        ],
        tests: [
            'test/**/*.spec.js'
        ],
        testFramework: 'jasmine',
        env: {
            type: 'node'
        },
        compilers: {
            '**/*.js': wallaby.compilers.babel({
                babelrc: true
            })
        }
    };
};
```

### `.babelrc` configuration file

```json
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ],
  "ignore": [
    "node_modules/",
    "/wallaby/"
  ]
}
```

### Code editor or IDE name and version

WebStorm v11
IntelliJ IDEA v15

### OS name and version

OSX

### Repo

https://github.com/mdreizin/webpack-config

**Comment by ArtemGovorov** [comment]
Reproduced the issue and tried to change your `.babelrc` as follows:
```
{
  "presets": [
    "es2015"
  ],
  "plugins": [
    "add-module-exports",
    "transform-runtime"
  ],
  "ignore": [
    "node_modules/",
    "**/wallaby/wallaby/**"
  ]
}
```
and the issue had gone. An interesting thing is that now I can't reproduce it even if I revert the change.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks.

**Comment by mdreizin** [comment]
@ArtemGovorov What do you think if this `ignore` pattern will be added automatically in case of `babel`?

**Comment by ArtemGovorov** [comment]
@mdreizin If you mean automatically added by wallaby, then I don't see how it's possible. By selecting `babel-node` as your node version, you are executing wallaby.js core with it. So even before wallaby.js core is loaded (and has a chance to do anything automatically), `babel-node` tries to compile it.

**Comment by mdreizin** [comment]
@ArtemGovorov I see, thanks ;)

**Comment by mdreizin** [comment]
Hello @ArtemGovorov, I would like to inform you that this issue still exists.

```
[BABEL] Note: The code generator has deoptimised the styling of "~/Library/Caches/WebStorm2016.2/wallaby/wallaby/server.js" as it exceeds the max of "100KB".
```

Adding `**/wallaby/wallaby/**` will not solve the issues.

Please try to:

- create empty project or clear existing wallaby cache;
- select `bebel-node` as `node` interpreter;
- start `wallaby`;

After cache will be populated you will not get such issue. I suppose that wallaby should copy `.babelrc` to appropriate place (working directory) or you need to add some core exclusion automatically in case of:

```js
compilers: {
    '**/*.js': wallaby.compilers.babel({
        babelrc: true
    })
}
```

**Comment by ArtemGovorov** [comment]
I had a deeper look and here is what happens. You're using `babel-node` to launch wallaby.js core, so wallaby config file, and anything it configures, is not even relevant at this stage. It's not wallaby.js cache that gets hit and used, it's `babel-node` cache at `~/.babel.json` file (if you delete the file, you'll get the warning).

After having a look into the `babel-node` code, I don't see it using `.babelrc` at all, the file is simply not relevant either. Also there's nothing wallaby core can do, because the warning comes from `babel-node` that compiles the core before it runs. Anyway, doesn't seem to be a big deal as it only happens once and then it's all in `babel-node` cache.

**Comment by mdreizin** [comment]
@ArtemGovorov Thanks for investigation ;)

I also reviewed code, but I have found that:

- `babel-node` uses `babel-core`;
- `babel-core` calls `babel-register`;
- `babel-register ` uses `OptionManager` which is aware about `babelrc: true` https://github.com/babel/babel/blob/master/packages/babel-register/src/node.js#L68

**Comment by ArtemGovorov** [comment]
Hmm, I'm sorry for the quick conclusion, you are indeed correct - `babel-node` indeed tries to use `.babelrc`. 

The issue is that babel is not using the current working directory (your project) `.babelrc` file, but instead it is [trying to find `.babelrc`](https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/options/build-config-chain.js#L54) in the wallaby plugin folder, because wallaby core is started via an absolute path. If would work if it was also trying to find the `.babelrc` in the current working directory (`process.cwd()`), but it's not doing it unfortunately.

The only way wallaby core could fix it if we ship wallaby core with `.babelrc` placed in its folder. Sounds hacky and redundant, but I don't see any other way.
