### ISSUE TITLE
nodejs error: `cannot find module`

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#663]
After reading docs and issues, I understand that I have to load dependencies using `files`, except for `node_modules` dependencies.

I am loading a child process using `fork`. Child process has a dependency in other module which is located in `node_modules`, and I am getting this error (Error: Cannot find module) altho it is located in node_modules). I tried to load it manually but in my case I have many dependencies and I should load them one by one (which can be really frustrating)

I created a simple example for it:

```js
var cp = require('child_process');
const join = require('path').join;

var child = cp.fork(join(__dirname,'./server'));
```

server.js is a simple http server:

```js
const http = require('http');
const my-other-node-module = require('my-other-node-module'); //node_module dependency
const server = http.createServer();
server.on('request', function(req, res) {
  res.writeHead(200, {'Content-Type': 'text/plain'});

  res.write('Hello World!');
  res.end();
});

server.listen(4000);

module.exports = server;
```

My test is:

```js
const expect = require('chai').expect;
const fetch = require('node-fetch');
const aServer = require('../index2');

describe('bla', () => {
  it('should be ok', function(done) {
    this.timeout(10000);
    setTimeout(() => { //workaround for this sample
      fetch('http://localhost:4000').then(res => {
        expect(res.status).to.equal(200);
        done();
      });
    }, 5000);
  });
});

```
### Wallaby.js configuration file

```javascript
module.exports = function () {
  return {
    files: [
      'index.js'
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    env: {
      type: 'node'
    }
  };
};

```

**EDIT**
I also tried telling wallaby where node_modules are:
```js
process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'core', 'node_modules');
```

It did not help...

### Code editor or IDE name and version
Atom v1.8

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
You were close to make it work. Setting `process.env.NODE_PATH` should do the trick, however you must have taken it from another example where the person had `core` subfolder with node modules. In your case it should look like:
```javascript
process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');
```

I have tried running your sample, and after fixing this issue, I started seeing `EADDRINUSE` for the server port. This happens because wallaby.js by default [reuses node processes](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) and your server is never stopped. I'm not sure how your real tests are organised, but you may either need to to some cleanup, for example in the `teardown` function, or just use the `workers.recycle = true` option as described in the referenced docs section. Recycling workers is a bit slower than cleaning up, but provides more isolation from the previous test runs, so it depends on your project specifics - some of our users prefer one way, others prefer another.

So the working config for the sample may look like this:

```javascript
module.exports = function (wallaby) {
  process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');
  return {
    files: [
      'index.js',
      {pattern: 'server.js', instrument: false}
    ],

    tests: [
      'test/**/*.spec.js'
    ],

    env: {
      type: 'node'
    },

    workers: {recycle: true}
  };
};
```

Please let me know if it addresses the issue.

**Comment by yanivefraim** [comment]
Thanks for the quick answer. The example had the `EADDRINUSE`, this is my fault (I was too lazy to fix example). My real code does not have this issue.

However, I did try you suggested solution:
```js
process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');
```

and it did not work. I have to add my node_modules dependencies manually. After adding dependency manually it started to ask for dependency of dependency and so this became a real headache. 

BTW - I'm still using npm 2 here (hope to upgrade soon). Will try to play with it and see if npm 3 might work..

**Comment by ArtemGovorov** [comment]
It should not depend on the npm version. I have created [your sample repo here](https://github.com/wallabyjs/wallaby-663), works for me in your setup (Atom + OSX). Could you try running the sample locally?

**Comment by yanivefraim** [comment]
After testing again, this solution worked:

```js
process.env.NODE_PATH += ':' + require('path').join(wallaby.localProjectDir, 'node_modules');
```

(I now have other issues, but no more `cannot find module`. 10x!)
