### ISSUE TITLE
Module undefined when hot reloading changed files

### ISSUE THREAD

**Issue by kennethlynne** [wallabyjs/public#669]
### Issue description or question
Running mocha tests manually works just fine.
And all tests pass and act as expected on first run in wallaby.

![image](https://cloud.githubusercontent.com/assets/390817/16322303/7bd00ac2-39a2-11e6-8a62-033917c903ff.png)

However if I change certain files, wallaby seem to do some magic reloading that breaks something, and the module is suddenly undefined.

![image](https://cloud.githubusercontent.com/assets/390817/16322362/df51c900-39a2-11e6-94f4-36270c0f7867.png)

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      'typescript/src/**/*.ts',
      'typescript/src/**/*.tsx',
      {pattern: 'typescript/src/**/*.spec.ts', instrument: false, load: false, ignore: true},
      {pattern: 'typescript/src/**/*.spec.tsx', instrument: false, load: false, ignore: true}
    ],
    tests: [
      'typescript/src/**/*.spec.ts',
      'typescript/tests/**/*.ts'
    ],
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript({module: 'commonjs'}),
      '**/*.tsx': wallaby.compilers.typeScript({jsx: 'react', module: 'commonjs'})
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha'
  };
};

```

### Code editor or IDE name and version
WebStorm v11

### OS name and version
OSX

Node 6.2.1

**Comment by ArtemGovorov** [comment]
This normally happens when `tests` pattern contains some files that are not files with actual tests like [wallaby.js requires](https://wallabyjs.com/docs/config/files.html#tests). Please double check these patterns:
```
'typescript/src/**/*.spec.ts',
'typescript/tests/**/*.ts'
```
only include files with tests. Any non-test files, like helpers, etc., have to be in the `files` list.

Non-related note: you may simplify your `compilers` section a bit:
```javascript
compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({jsx: 'react', module: 'commonjs'})
},
```

**Comment by kennethlynne** [comment]
Thanks you!

When I moved all test files into the tests folder, and reconfigured wallaby like so:
```
module.exports = function (wallaby) {
  return {
    files: [
      'typescript/src/**/*.ts?(x)'
    ],
    tests: [
      'typescript/tests/**/*.ts'
    ],
    compilers: {
      '**/*.ts?(x)': wallaby.compilers.typeScript({jsx: 'react', module: 'commonjs'})
    },
    env: {
      type: 'node'
    },
    testFramework: 'mocha'
  };
};
```
The error that only happened once in a while when one touched certain files, happened every time, on first run also now.

**Comment by kennethlynne** [comment]
Maybe related to this:

We have a store, some actions that import that store, some sagas that import those actions, and the store itself imports the sagas, so a circular dependency it seems

**Comment by ArtemGovorov** [comment]
> When I moved all test files into the tests folder

`tests` should only contain files [with actual tests](https://wallabyjs.com/docs/config/files.html#tests) in them. It's not necessary to move anything, you just have to make sure that all of your files are listed somewhere and that there're no files that are not test files in the `tests` list.

For example, if your test files are following some naming pattern, like end with `.test` or `Spec`, you may do this:
```javascript
files: [
      'typescript/**/*.ts?(x)',
      '!typescript/tests/**/*.test.ts?(x)'
    ],
tests: [
      'typescript/tests/**/*.test.ts?(x)'
    ],
```

If it doesn't help, please create a sample repo demonstrating the issue, I'm happy to have a look.

**Comment by kennethlynne** [comment]
I still could not get it to work sadly. I sent an excerpt from our codebase now. The problem happens whenever you change index.spec.ts in sagas/, and store/index.ts

**Comment by ArtemGovorov** [comment]
@kennethlynne Replied to your email - I haven't received any attachments in it unfortunately, could you please try sending it again?

**Comment by ArtemGovorov** [comment]
It is indeed an issue with the circular dependency. Mocha and wallaby can run all tests because a first running spec file doesn't exercise the circular dependency and loads a part of the chain. When the `typescript/src/sagas/index.spec.ts`, that executes the circular dependency path, runs after it, it's ok. But when you edit the test file in wallaby after it, wallaby only runs this test file and the circular dependency issue is hit.
It's not specific to wallaby.js, but to the fact on running that test alone. For example, if you change you `package.json` `test` command to only run that test:
```
"test": "mocha \"compiled/src/sagas/index.spec.js\"",
```
you'll hit the exact same issue in mocha as well.

The best solution is to get rind of the circular dependency as the whole app depends on the fragile execution order. If you can't not get rid of it for some reason, you may add this [setup](https://wallabyjs.com/docs/config/bootstrap.html) function to the config to make it work:

```javascript
module.exports = function (wallaby) {
  return {
   ...
    setup: function(){
      require('./typescript/src/modules/authentication/actions/AuthenticationActions')
    },
  };
};
```
Requiring this file from the middle of the circular chain before each execution, allows to load this part of the chain, so when the test runs, it'll be ok.

**Comment by kennethlynne** [comment]
Ok great, thanks @ArtemGovorov , and I appreciate the detailed explanation!
