### ISSUE TITLE
.coffee files should be preprocessed when not instrumented

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#67]
I have added a node_module to my project and included the .coffee file in the `files` list. I expected the file to be processed by the coffee preprocessor, but this only happens when `instrumented` is `false`.

I don't want libraries to be instrumented, so please let non-instrumented files begin preprocessed as well.

**Comment by ArtemGovorov** [comment]
You are using browser tests (not node.js tests) and referencing .coffee file from one of the installed node_modules in your files list with `instrument: false` and it doesn't work, is it correct?

Normally, node modules have a pre-compiled JavaScript version inside, referencing it instead of the CoffeeScript one would be be more efficient as in this case coffee preprocessor won't have to run at all.

But if you'd still like to use a library written in CoffeeScript and would like wallaby to compile it for you but not instrument, you may use a specific preprocessor for that, [as described here](https://github.com/wallabyjs/public#preprocessors-setting):

``` javascript
module.exports = function () {

  return {
    files: [
      {pattern: 'node_modules/lib/a.coffee', instrument: false},
      'src/app.coffee'
    ],

    tests: [
      'test/test.coffee'
    ],

    preprocessors: {
      'node_modules/**/*.coffee': file => require('coffee-script').compile(file.rename(file.path + '.js').content)
    }
  };
};
```
Note that you need to run `npm install coffee-script` or `npm install coffee-script -g` if you haven't already to install CoffeeScript locally or globally.

Please let me know if addresses the issue.

**Comment by fvanwijk** [comment]
Thanks for your quick reply.

It is indeed concerning a node_module that only has coffee files: `jasmine-before-all`. Compiling using the script you provide does the trick. Thanks.

NB: Note that you are mixing up coffee script and javascript in the code examples in the docs.

**Comment by ArtemGovorov** [comment]
Awesome, thanks.

> Note that you are mixing up coffee script and javascript in the code examples in the docs.

Could you please point out where? Can't find it.

**Comment by fvanwijk** [comment]
It's in all but one code blocks in the section called *Preprocessors setting* as well as [your comment]:(https://github.com/wallabyjs/public/issues/67#issuecomment-93296258)

```javascript
file => require('coffee-script').compile(file.rename(file.path + '.js').content)
```

Looks as coffee script to me. Should be:

```javascript
function (file) { return require('coffee-script').compile(file.rename(file.path + '.js').content) }
```

**Comment by ArtemGovorov** [comment]
Ah, got it. It's actually ES6 arrow functions. Wallaby.js uses io.js internally and it supports some ES6 features, including arrows, so you may use them in wallaby configuration.
