### ISSUE TITLE
wallaby gets stuck when spyobj created

### ISSUE THREAD

**Issue by dkuida** [wallabyjs/public#678]
I develop a node project , using jasmine
when I try to use spyobj then wallaby gets stuck, also a consequence is that there is no autocomplete for the methods, so it is either the version of jasmine that is used does not support node or I configure it wrong.

### Wallaby.js configuration file
```javascript
'use strict';

module.exports = function () {
    return {
        files: [
            'controllers/**/*.js',
            'services/**/*.js',
            'lib/**/*.js',
            'config/**/*',
            'spec/helpers/**/*.json'
        ],

        tests: [
            'spec/**/*Spec.js'
        ],

        testFramework: 'jasmine',

        env: {
            type: 'node',
            runner: 'node'
        }
    };
};
```

the test file is 
```
'use strict';

const SkillsRoute = require('../controllers/skillsRoute');
const mockery = require('mockery');
const sut = new SkillsRoute();

const requestMock = jasmine.createSpyObj('request');
mockery.registerMock('request', requestMock);
/** scenario def


 */

describe('skills route', () => {
    it('', function () {
        /**arrange*/
        const req = {};
        const res = {};
        const next = {};
        sut.searchWithString(req, res, next);
        /**act*/
        expect(requestMock).toHaveBeenCalled();
        /**assert*/
        
    });
});
```
the SUT
```
'use strict';

const RouteBase = require('../lib/routeBase');

class SkillsRoute extends RouteBase {
    searchWithString () {

    }
}

module.exports = SkillsRoute;

```
I use
WebStorm 2011.1
### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
`createSpyObj` [requires 2 parameters](http://jasmine.github.io/2.0/introduction.html#section-Spies:_<code>createSpyObj</code>), otherwise it [throws the string](https://github.com/jasmine/jasmine/blob/11cfaae42ab31a494e005d36f49d8c1e089fed3b/src/core/base.js#L114). Wallaby shouldn't be hanging and should report the error, but because jasmine throws the string and not an error, wallaby hangs. I'll investigate how to better report such errors, but you should be able to just pass correct values to make it work for you.
