### ISSUE TITLE
Helper test function

### ISSUE THREAD

**Issue by andr2** [wallabyjs/public#681]
I want to make a helper for promise-based functionality.

Here is the code:
```javascript
asyncEqual<T>(act: MPromise<T>, exp: T) {
	return done => {
		act.then(v => {
			assert.equal(v, exp);
			done();
		})
	}
}

it("test", asyncEqual(1, 2));
```

When it is executed there is only `assert.equal(v, exp)` line in asyncEqual is marked by red and `it` line is green.
Is there any possibility to make `it` line red?

IDE: VSCode insiders
OS: Windows 10

**Comment by ArtemGovorov** [comment]
The issue here is that the error stack doesn't include this line:
```javascript
it("test", asyncEqual(1, 2));
```
so wallaby can't highlight the line as red, because according to the error details, it didn't happen on the line. It makes sense, because the line doesn't contain any executable statements that fail. The test will still be displayed as failed in the Wallaby Tests output channel. 

This is not wallaby specific issue, so if you run this code in any other test runner, you'll see that the provided error stack doesn't include the line with the test. The only way to get the line highlighted is to make it appear in the error stack. Probably the easiest way would be to have some executable statements in it that fail, and thus end up in the error stack. For example this should work:
```javascript
it("test", done => asyncEqual(1, 2)(done));
```

Hope it makes sense and addresses your question.

**Comment by andr2** [comment]
Yes, you are right. Thank you for help!
