### ISSUE TITLE
Proxyquireify does not work with Wallaby

### ISSUE THREAD

**Issue by Sanjo** [wallabyjs/public#682]
### Issue description or question

Proxyquireify does not work with Wallaby. I tried the recipe that is linked in the documentation https://wallabyjs.com/docs/integration/browserify.html. I have it working with Karma, so it must be something about how Wallaby works, that I don't understand.

### Reproduce

Project: https://github.com/Sanjo/wallaby-browserify-sample/tree/proxyquireify

Commit: https://github.com/Sanjo/wallaby-browserify-sample/commit/3c56bbc58eb67b249d5219326bb146e3d4fd02b3

### Code editor or IDE name and version

WebStorm 2016.1.3

### OS name and version

Linux (Ubuntu 14.04)

**Comment by ArtemGovorov** [comment]
I cloned the project, switched to the commit and it's failing to load the config file because `fs` and `path` variables are not defined. After declaring
```javascript
var fs = require('fs');
var path = require('path');
```
everything works for me (tests run and pass).
What happens in your case? Does it throw any errors? How exactly doesn't it work?
One thing to check may be the `'proxyquireify/node_modules/detective'` path used in the recipe, it relies on the fact that the module wasn't pulled up to the root node_modules, please check if it exists in your case.

**Comment by Sanjo** [comment]
Oh sorry, I must have ran the Wallaby config of my real project.
After going through every aspect of the full config I finally found the error.
The wallabify initializer function was accidentally part of the first options argument.
After fixing that it works.
