### ISSUE TITLE
Question: Run a set of tests in series?

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#707]
### Issue description or question

I'm creating some (Jasmine) specs, some of which are hitting a database, and it'd be handy if they could be run in series as a batch. For example:

- Check db empty
- Create new entry / Verify it's there
- Update the entry / Verify the update
- Delete the entry / Verify it's gone

I know that I could set the worker count, but ideally I'd like just this spec to run within a single thread, and I want to run all specs if anything changes?

I'm guessing the best way is to set the worker count to 1 - and really repeat the steps (before update code, create the entry) to try and reduce side affects within the tests? As I've got a single storage mechanism I'm not going to be able to truly isolate them.

**Comment by ArtemGovorov** [comment]
With multiple spec files hitting the same entities in a single database, setting the worker count to 1 is your best option. During incremental runs (most of the time) wallaby is using one process anyway, so you'll highly likely not spot the difference anyway.

I have also seen some people creating multiple databases: as many databases, as many parallel workers they have, so that every worker process works with its own DB. Wallaby [`setup` function](https://wallabyjs.com/docs/config/bootstrap.html) gets the `workerId` number that could be used as the identifier of the database to create/populate/setup the worker's DB.

**Comment by IPWright83** [comment]
Just to verify though - will Wallaby's optimisation to only run affected tests get in the way? E.g. If it runs spec 1, 3, 4 but misses out number 2 that might cause issue. Is that a likely problem I'm going to encounter?

**Comment by ArtemGovorov** [comment]
@IPWright83 Yes, if some test depends on any other tests in some way, that may actually break things in wallaby because it may only run some of your tests. Not just in wallaby though, such brittle tests can easily break during refactoring, and generally dependent tests are considered evil for a few other reasons. A solution to make each test self-sufficient is to use [jasmine's `beforeEach`](http://jasmine.github.io/2.0/introduction.html#section-Setup_and_Teardown) hooks to make sure a test has everything it needs to complete in isolation.

**Comment by ArtemGovorov** [comment]
Another thought - if you'd like a few tests to run as one test, and even though few smaller isolated tests are better in a long term, perhaps it makes sense to just have one test that will always be executed as a batch of arrangements/assertions in any test runner.

**Comment by IPWright83** [comment]
@ArtemGovorov that is true (not sure why I didn't think of that). I guess my test is a bit of an exception - I believe Wallaby's designed for unit tests, whereas technically this is an integration test which carries some baggage with it. I might look at moving them to a single test though. Thanks :+1:
