### ISSUE TITLE
Question - is it possible to run existing build configurations

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#712]
I have an existing build with its configurations (running it using `npm run build`). It runs babel, copies files to dist and creates a main bundle and a bundle for tests. 

Now, when creating wallaby.js configurations I see that I am kind of duplicating my build. I understand that using wallaby's preprocessors etc. should have better performance (is it true?), but this behaviour can cause duplicate maintenance and duplicate effort.

Is it possible to use my existing commands from wallaby.js? Something like running  `npm run build` from wallaby? Not sure how fast it will be, but I want to give it a try..

**Comment by ArtemGovorov** [comment]
> existing build with its configurations (running it using `npm run build`)

From an external tool perspective, `npm run build` is just a black box. The output of the black box (the bundle for tests) is not enough to provide you the live editing experience that wallaby provides. Even a simple `copies files to dist` already would make it hard/impossible for wallaby to understand and do many things it needs to do.

Put simple, wallaby needs to perform certain operation in a middle of the build to be able to do the code coverage/analysis/advanced source mapping and other magic it does. It also needs to keep the map between the original files (where you expect to see the coverage and live feedback) and whatever is compiled, and have its own (virtual, instrumented) bundle to run.

> duplicate maintenance and duplicate effort

Well, I'd say it's *some* additional effort, but not a duplication. 

First, in wallaby config you reuse a lot of your other configs, like `babelrc`, `webpack.config`, `tsconfig`, etc. Since you're reusing them, the maintenance is specific to your *test* build. Apart from listing files/tests, typical wallaby config just orchestrates few build steps on a high level, with details hidden in the other config files. So it's only when you change your high level build details you need to touch wallaby config: like say switching from ES6/Babel to TypeScript, or from LESS to SASS.

Second, your *test* build is not necessarily the same as your *production* build. It may (should) adjust things so that the tests run faster. For example, if `.scss` files are just imported in your code, but no assertions are made and neither their structure is used in the code, the the preprocessor could just remove those imports from the code, as opposed to be compiling them. The same applies to any other assets that could be removed or simplified for testing in terms of loading.

Hope it makes sense and answers your question.

**Comment by yanivefraim** [comment]
Thanks a lot for the detailed question!
