### ISSUE TITLE
Wallaby process quits after a few test runs

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#722]
### Wallaby stops working in IntelliJ Idea

After a few runs of test (several minutes), wallaby jus stops working. Restarting it doesn't work. The only way to fix it is to re-start Idea.

![2016-08-02 at 18 47](https://cloud.githubusercontent.com/assets/11071/17337105/a1edef72-58e1-11e6-9a42-ca162ce65dfa.gif)

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test'; // Set babel into test env to disable HMR

const testRunnerConfig = require('test-runner-config');
const testFiles = require('./testFiles');
const files = testRunnerConfig.getWallabyFiles(testFiles);

module.exports = function(wallaby) {

  return Object.assign(files, {
    env: {
      type: 'node'
    },

    compilers: {
      '**/*.js*': wallaby.compilers.babel()
    },

    testFramework: 'mocha',

    bootstrap: function bootstrap() {
      require('./testSetup');
    }

  });
};
```

### Code editor or IDE name and version

IntelliJ IDEA v2016.2

### OS name and version

OSX 10.11.5

### Wallaby version

1.0.70

**Comment by ArtemGovorov** [comment]
Do you have any other plugins running at the same time? Approx how many tests does the project have? After it happens again, could you please attach the `idea.log` file (`Help - Show Log in Finder`)?

**Comment by ArtemGovorov** [comment]
Also, the next time it happens, could you please how does the IDEA process memory consumption looks like?

**Comment by ArtemGovorov** [comment]
One more thing, do you have a valid license entered for this machine/IDE? The behaviour looks like the trial version limitation (when you don't have an entered license), but it should warn you with popups (unless you have turned them off in the `File | Settings | Appearance & Behavior | Notifications` Wallaby Expired License, Wallaby License and Wallaby Updates):

<img width="677" alt="screen shot 2016-08-03 at 8 18 12 am" src="https://cloud.githubusercontent.com/assets/979966/17347372/e14831fc-5952-11e6-966a-8c3efc5b2574.png">

**Comment by okonet** [comment]
Yes, it was suddenly in trial mode!

Why did I even get an update if it isn't supported? 😠

<img width="361" alt="2016-08-03 at 09 36" src="https://cloud.githubusercontent.com/assets/11071/17357602/ebd8c9f0-595d-11e6-8844-4b6bfa6a01cc.png"> 

How do I downgrade to the latest supported version?

**Comment by okonet** [comment]
Also, it would be great to get some more information in the console if it's not working because of trial mode. Not silently not working :(

**Comment by ArtemGovorov** [comment]
> Why did I even get an update if it isn't supported?

Not sure, it's not supposed to update from an expired version. Perhaps you have installed the newer version from our website (maybe after updating the IDE)?

You may get the latest supported version for you license here: https://wallabyjs.com/license/ by using the Latest Covered Version Form.

**Comment by ArtemGovorov** [comment]
> Also, it would be great to get some more information in the console if it's not working because of trial mode. Not silently not working :(

In your case `Wallaby License` notifications would have warned you about it, but you must had them turned off. In order to not receive the license renewal notifications it is enough to mute the `Wallaby Expired License` notification group, not all other wallaby groups.

I'll add the console message for the case as well.

**Comment by okonet** [comment]
After installing the appropriate version of the plugin from the web-site, I started getting this:

![2016-08-03 at 12 03](https://cloud.githubusercontent.com/assets/11071/17361803/8f956e40-5972-11e6-84cd-f7669ce12cc9.png)

I have version 1.0.64 installed, which is the version I'm getting on the web-site:

![2016-08-03 at 12 05](https://cloud.githubusercontent.com/assets/11071/17361809/97f16c88-5972-11e6-91f5-b1edf9cffd1a.png)

**Comment by ArtemGovorov** [comment]
First of all, I'm sorry to hear about the experience. We have clearly missed some scenario where an unexpected update leads to the case. I'd like to get to the bottom of why this happened and to fix it.

> BTW I didn't install anything manually, it did auto-update me to the latest incompatible version.

Of the core or of the plugin? Because wallaby.js does not install the plugin automatically (and never did). That's why I mentioned I wasn't sure how it could happen, because the plugin updates are *only* installed for not expired versions and what's even more important *only* when you click that you'd like to update in the popup (and you seemed to have the popups from wallaby disabled anyway). So I'm really puzzled as to how the plugin greater than v1.0.64 was installed. The only scenario I can think of is a directly installed newer version, but you've mentioned it was automatic. The incorrect core version was installed as a part of the incorrectly installed plugin version (that was not expected to happen).

Either way, to get everything working please do this:
- close your IDE,
- got to `~/Library/Caches/IntelliJIdea2016.2/wallaby/`,
- delete the `wallaby` subfolder in there,
- download and install [this plugin version](https://github.com/wallabyjs/public/files/400616/wallaby-intellij-v1.0.64.zip),
- start wallaby.

It should automatically download the supported core version and work.

**Comment by okonet** [comment]
> Of the core or of the plugin? Because wallaby.js does not install the plugin automatically (and never did). 

I might actually have downloaded the version from wallabyjs.com when upgrading to 2016.2 (I can't remember for sure, though) or it was an update popup (which I still has enabled — I've disabled only wallaby license ones).

Either way, downloading the previous version as you suggested before, didn't help since the core version didn't match. In this case, I'd expect the plugin to download the proper version itself.

The steps above did help to resolve it.
