### ISSUE TITLE
Debugger support

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#74]
The way Wallaby handles `console.log`s is really cool, but setting breakpoints and stepping through the code is still King of the Hill, especially when objects are large or when you want to step in a function.
Please enable debug mode for Wallaby if possible.

**Comment by ArtemGovorov** [comment]
Agreed, there are be some improvements planned in this area, full debugger support is also something that I'll look into.

**Comment by mvestergaard** [comment]
http://www.ncrunch.net/ has a really neat way of handling this.
http://www.ncrunch.net/Content/Home/featureEasyDebugging.png Something like that would be very nice, if possible!

**Comment by mulyoved** [comment]
+1

**Comment by patrykziem** [comment]
+1

**Comment by DenisGorbachev** [comment]
+1

**Comment by mdoleh** [comment]
+1

**Comment by cref** [comment]
+1

**Comment by usefulthink** [comment]
+1

**Comment by rochdev** [comment]
+1

**Comment by lburgess** [comment]
+1

**Comment by ludydoo** [comment]
+1

**Comment by hellboy81** [comment]
+infinity

**Comment by mercadis** [comment]
+1

**Comment by olofd** [comment]
+1

**Comment by QuantumInformation** [comment]
+1

**Comment by yaroslavya** [comment]
+1

**Comment by areel** [comment]
+1

**Comment by cbrwizard** [comment]
+1

**Comment by tamasfoldi** [comment]
+1

**Comment by developermj** [comment]
+1

**Comment by dlo1957ca** [comment]
+1

**Comment by idan315** [comment]
+1

**Comment by hellboy81** [comment]
Debugging unit tests is anti-pattern!

**Comment by olofd** [comment]
Haha @hellboy81

**Comment by hellboy81** [comment]
@olofd  Yeah! You should write unit tests for your buggy tests!

**Comment by olofd** [comment]
@hellboy81 are you serious? we all know debugging a unit test enviornment can be really helpful. Besides that, unit tests can seems like black magic for beginners, debugging can help people understand underlying frameworks like karma or jasmine. Sure helpt me when I started writing tests.

**Comment by hellboy81** [comment]
@olofd RTFM  **xUnit Test Patterns**, Chapter _16_, Behavior Smells,  Page **248**

**Comment by fvanwijk** [comment]
Throwing a book title plus page number at us does not make your point valid and does not add anything to the discussion. There are a lot of behavior smells mentioned in that paragraph. Could you please elaborate?

You may refer to [Frequent Debugging](http://xunitpatterns.com/Frequent%20Debugging.html).

> Another productivity-sapping smell is Frequent Debugging (page X). Automated unit tests should obviate the need to use a debugger in all but rare cases since the set of tests that are failing should make it obvious why the failure is occurring. Frequent Debugging is a sign that the unit tests are lacking in coverage or are trying to test too much functionality at once.

A lot of people are having troubles writing good unit tests - noting that most people are even not writing unit tests at all. Your solution is to tell them that their tests will become better by pointing them at a book and telling them that their code smells instead of giving them a debugger?

50 Percent of the tests fail because the test is wrong, not the source. You could decrease that value by simplifying your tests (and your code). Debugging could help you with that.

Nevertheless this issue is not per se about debugging the test. It's just about debugging any running code using a breakpoint, because it may give you more insight than using `console.log`.

**Comment by ludydoo** [comment]
@hellboy81 Relating to this feature request, who cares if debugging the unit tests is an anti-pattern ? If a test fails I want to know why and inspect/drill down my objects, It's just a pain to do it with console.log. Being able to set a breakpoint would just allow me to do that. @ArtemGovorov Is there any update on this feature ?

**Comment by ArtemGovorov** [comment]
@ludydoo It's a very big one, I'll announce it separately when we start working on it.

**Comment by croogie** [comment]
+1

**Comment by asnov** [comment]
+1

**Comment by aaweb** [comment]
+1

**Comment by arg20** [comment]
+1

**Comment by jmwnoble** [comment]
+1 for Visual Studio.  Along with the test summary this would be the single most useful enhancement, to work through complex logic / large objects.

**Comment by akilhoffer** [comment]
+1 for WebStorm debugging

**Comment by tomRedox** [comment]
+1, it's absolutely invaluable with nCrunch in VS

**Comment by Robert923** [comment]
I would find this very helpful.

**Comment by pimterry** [comment]
+1 - I'm running my tests in Electron; just having an easy 'open tests in Chrome' button that opened up in the sandbox with tests running so I can debug in detail from there would be perfectly fine for me (and presumably easier than any deeper more involved debugger support).

**Comment by rcazangi** [comment]
+1

**Comment by roelleor** [comment]
+1

**Comment by ctrlplusb** [comment]
Please don't +1 peeps. It adds nothing but noise. Rather thumbs up the original post. x

**Comment by OliverKK** [comment]
+1

**Comment by arranbartish** [comment]
@ArtemGovorov - There doesn't seem to be much info on this in the last couple of weeks. 

- Is this being actively worked on right now?

**Comment by ArtemGovorov** [comment]
@arranbartish We are planning to start prototyping something lightweight soon. In its first iteration it's not going to be the full debugger support with stepping/breakpoints, but should hopefully cover a few areas like variable inspection.

**Comment by mhelvens** [comment]
I'm not sure I understand this feature request. There are already immersive test-frameworks with debugging support that people can use. Wallaby is meant for instant but non-intrusive feedback while coding. Stepping / breakpoints does not seem to fit in Wallaby's purview.

I use Wallaby to continuously run my Mocha tests, but when I need more sophisticated debugging, I simply *run Mocha*.

The best Wallaby can do here, I think, is to seamlessly integrate with existing test-runners / debuggers (rather than reinvent the wheel). Perhaps by equipping test failures / errors with a link that auto-configures them to break at the failed state and then starts them.

**Comment by Robert923** [comment]
I agree with mhelvens - I just want the ability to kick-off a debug session on a failing test using the IDE's built-in debugger.

**Comment by ArtemGovorov** [comment]
> The best Wallaby can do here, I think, is to seamlessly integrate with existing test-runners / debuggers (rather than reinvent the wheel).

> I just want the ability to kick-off a debug session on a failing test using the IDE's built-in debugger.

It is exactly what we're planning to do *eventually*. We certainly don't want to build a new debugger for every editor that we support. The idea is to re-use as much as possible in terms of an existing editor debugger support implementation. 

Also, it's worth mentioning that there's nothing we can re-use in testing frameworks themselves to add the debugger support. From the debugger point of view, testing frameworks and their runners are just JavaScript programs. It's an editor debugger UX support plus execution engines (PhantomJs, Electron, node) debugger support that we'll need to integrate with.

When I mentioned that we are planning to start prototyping something lightweight soon, and it's not going to be the full debugger support yet, I meant that we're experimenting with a way to inspect any variables/objects in a way that fits in Wallaby's purview. Like when you can inspect variables when a breakpoint is hit, but without actually setting any breakpoint. I'll share some more details once we start playing with it.

**Comment by Robert923** [comment]
Interesting!   I look forward to seeing it.  :-)

**Comment by cyppher** [comment]
+1

**Comment by faceyspacey** [comment]
+2

**Comment by stevenh77** [comment]
+1

**Comment by colombod** [comment]
+1

**Comment by pearljamik** [comment]
+ 1

**Comment by ptomaszi** [comment]
+1

**Comment by elbuilio** [comment]
+1

**Comment by Martaver** [comment]
+1

**Comment by Palid** [comment]
+1

**Comment by westacotta** [comment]
+1

**Comment by FishOrBear** [comment]
Jest extension already has `debug`

**Comment by DmitryMakhnev** [comment]
+1

**Comment by 4alexandr** [comment]
+1

**Comment by ArtemGovorov** [comment]
Update: With the new [Value Explorer](https://wallabyjs.com/docs/intro/value-explorer.html) feature (plus [Live Value Display](https://wallabyjs.com/docs/intro/advanced-logging.html#live-value-display) feature) you can explore values anywhere in your code and tests just as you would in a classical debugger, but without having to start and attach a debugger, place any breakpoints (or even add a `console.log` statement). Right now it's only available for VS Code, but JetBrains IDEs support is on its way.

**Comment by maksimr** [comment]
@ArtemGovorov Do you have any plans to support IDEA's debugger? It would be super awesome. 
Because debugger allows not only to explore a value but also stop executing the code and play with code in this specific state.

**Comment by oliversturm** [comment]
Are there any updates on debugger support? I'm looking at VS Code.

I like what the value explorer does, and I use live values all the time. However, this isn't a full replacement for debugger support, for two important reasons:

1. I have multiple tests running even against simple functions. Some test successful behavior, others test error behavior. Live values end up displaying a number (possibly a large number) of different values a variable held during one of the test runs, but I can't see which test run is associated with which variable value. I work around this sometimes using `.only` on my test, but there are still cases where this doesn't really help... which brings me to

1. Live values don't help much when debugging algorithms. Even the shortest logic (say a `reduce` call) can be hard to evaluate using live values only. Some of my tests execute call chains through several functions, or add algorithmic complexity in other ways - debuggers work step by step, which is occasionally the only (good) way to find an issue.

I believe it is quite easy to integrate a configuration in VS Code that runs a specific test in the debugger - I'll look into this right now, I've done it before but don't remember the details. However, it would be great if I could simply start such a debug session directly from Wallaby.

**Comment by oliversturm** [comment]
I found where I had used a VS Code configuration before to start tests for debugging. This block allows me to highlight the name of a test in the editor and hit F5 to run that particular test in the debugger.

```
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/jest/bin/jest.js",
        "--runInBand",
        "${relativeFile}",
        "-t",
        "${selectedText}"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen",
      "port": 9229
    }
```

This is a reasonably convenient workaround, but I guess it shouldn't be really hard to add a feature to Wallaby that does the same thing with automatic detection of the test my caret is currently in.

**Comment by ctrlplusb** [comment]
> This is a reasonably convenient workaround, but I guess it shouldn't be really hard to add a feature to Wallaby that does the same thing with automatic detection of the test my caret is currently in.

Great! Are you opening a PR then? 😛

**Comment by oliversturm** [comment]
I didn't realize this projected accepted PRs. Where's the source code of the VS Code plugin?

**Comment by ctrlplusb** [comment]
A bit of tongue in cheek.

**Comment by smcenlly** [comment]
We have been working on a Debugger experience for Wallaby for the last little while. We will release this as a BETA feature later this week.

**Comment by ArtemGovorov** [comment]
Here's the Wallaby Debugger preview if you haven't seen it on Twitter yet:

![ttd](https://user-images.githubusercontent.com/979966/70578380-419f7f80-1bf9-11ea-80be-edf9696aa797.gif)

**Comment by oliversturm** [comment]
That looks very good. Hadn't seen it, my question was coincidence. Looking forward to the Beta!

**Comment by smcenlly** [comment]
Today we released our new [time travel debugger](https://wallabyjs.com/docs/intro/time-travel-debugger.html) that addresses this request. Time Travel Debugger is currently a BETA feature and is only available for VS Code. Support for IntelliJ editors will be available in January 2020. If you have problems/feedback, please let us know.

**Comment by maksimr** [comment]
Waiting support for **IntelliJ IDEA** in **2020**

**Comment by smcenlly** [comment]
@maksimr - in case you have not already seen, we made this available last week.

**Comment by maksimr** [comment]
@smcenlly yup, I saw and have used it.

Unfortunately, it doesn't work so well in our project. So I still use IDEA's debugger :(

**Comment by Martaver** [comment]
I also get no values in the Value Explorer for a test I am debugging... I
am expecting a watch for variables in the scope of the code the debugger is
currently targeting, but I never get any values displayed. Only the files
that are loaded.

**Comment by ArtemGovorov** [comment]
@maksimr Mind sharing what exactly doesn't work for you? If it's more convenient for you, please open a separate issue.

**Comment by ArtemGovorov** [comment]
@Martaver Wallaby debugger by default doesn't capture any values. To see any variable in the scope of your code that the debugger is targeting, you need to [simply select the variable right in your code](https://wallabyjs.com/docs/intro/time-travel-debugger.html#inspecting-runtime-values) (for example, on the screenshot in the referenced docs section, `operand1` is selected right on the line being debugged; it can also be selected when the parameter passed into the function `function(operator, **operand1**, ...) {`).

**Comment by maksimr** [comment]
@ArtemGovorov sure :)

1. We very often use "Step Into" for library functions. Currently, wallaby just moves over these library functions
2. Possibility to evaluate any expression in this context. For example, I very often use  "Quick Evaluate Expression" which allows me to play with code and fetch different properties which I interested
3. To see any variable take **too** long time for us (I have attached a gif)

Thanks a lot! If you need more information I would be glad to provide it

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/616193/74131252-00295180-4bf5-11ea-993e-24aea49831c1.gif)

**Comment by ArtemGovorov** [comment]
@maksimr Thanks for sharing!

> Possibility to evaluate any expression in this context. For example, I very often use "Quick Evaluate Expression" which allows me to play with code and fetch different properties which I interested

The workflow we currently recommend and are using it ourselves is to simply type any expression right in the editor in the context being debugged (and then select it, as any other expression in the code). One major pro of the approach is that your editor becomes your Quick Evaluate/Watch window (that we find more convenient often times), major drawback is that you need to delete the code afterwards (which is also true for Wallaby live comments, and hopefully is not a big deal). I can see however this approach can be an issue for you given that variable evaluation is taking a long time.

> To see any variable take too long time for us (I have attached a gif)

This is not good. Does it take a long time to execute the test itself? For example, if you simply type `element` at the end of the test (without the debugger started), is it also taking a while before it gets evaluated? Also, could you please go to Wallaby Console tab, clear it, select a variable, wait until it gets evaluated, open and share your Wallaby Console output?

**Comment by maksimr** [comment]
> For example, if you simply type element at the end of the test (without the debugger started), is it also taking a while before it gets evaluated?

Yup, It takes a long time to execute the test itself. We have  ~4500 tests
`Finished executing 11 affected test(s) in 1.32 second(s)`

> Also, could you please go to Wallaby Console tab, clear it, select a variable, wait until it gets evaluated, open and share your Wallaby Console output?

`Finished executing 1 affected test(s) in 1.2 second(s)`
![image](https://user-images.githubusercontent.com/616193/74143261-8fd9fa80-4c0b-11ea-8e61-89c56ae1adfe.png)

**Comment by Robert923** [comment]
I've been using it, but ran into the same two issues:

1. It won't step into library code (even if that library is my own code - see [Lerna](https://lerna.js.org/))

I tried adding "./packages/mypackage/src/**/*.ts" and "./packages/mypackage/dist/**.js" as source code to the wallaby.js file, but unfortunately to no avail.

2. Watching/examining variables is a time consuming process

#2 is definitely the most frustrating - I find I can't even just have the cursor on the variable, but rather the entire variable has to be selected.   Then, after a single "step forward", the variable is lost and I have to re-select and re-do the keyboard shortcut.  This makes it very slow to see state changing over time.  Additionally, I often can't even see the variable until I expand the list on the left - and oftentimes the variable value is so far to the right that I have to expand the left panel significantly - meaning lots of keyboard and mouse movement just to see the value.

Much better is to just show the variables that have been evaluated in scope!

**Comment by Martaver** [comment]
I feel like there's no need to reinvent the wheel here... the age old
locals in scope and breakpoints combo, as well as being to step forward and
back and have the scope update accordingly is about as good as it gets.

**Comment by ArtemGovorov** [comment]
First of all, we really appreciate your feedback.

One thing I'd like to clarify is that with Wallaby's Time Travel Debugger we are not aiming to repeat the classical debugger experience. At the same time, where it makes sense we do want to implement classical debugger features.

The classical debugger experience is already available for most testing frameworks in VS Code and JetBrains IDEs and you can use it side-by-side with Wallaby when required. For this reason, we are not looking to provide the same experience/features that are already available to you.

Rather than duplicating features of a classical debugger, with Wallaby Time Travel Debugger we are trying is to enable a **continuous debugging workflow**, that is closer to the Wallaby-style of fast change-to-result feedback loop experience. While some things are super-fast with Wallaby time-travel debugger (e.g. step forward/step back), because of our approach other things come at a cost (e.g. time to evaluating a value). We have tried to mitigate evaluation cost with our [recent proxy value feature](https://wallabyjs.com/docs/intro/advanced-logging.html#object-proxy) that allows you to see when a value set/get occurs. Conceptually, and in terms of performance, the cost of evaluating a variable/expression/etc. in the debugger is the same as it normally is when using Wallaby (actually a little faster because only your test is running).

Our major focus is to make Wallaby's debugging workflow seamless and non-distracting. With Wallaby Time Travel Debugger we don't want you to have to perform the ceremony of attaching a debugger, setting some breakpoints, restarting the debugger on changes or if we missed some executed line, taking the editor to a special mode that needs to be stopped to keep going with your changes.

Instead, we want you to be able at any time with one click to bring the execution to any line, to quickly travel backward and forward (as required) to discover the context around it, to type anything in that context to change the execution (to see if the change is fixing some test, or to evaluate any expressions right in your editor), to keep the debugger on even if your changes are complex (ideally you can almost forget that debugger is still on until the next time you need it).

Thanks again for the ideas, they have already stimulated some good discussion in our team. We'll continue to think them through as Wallaby's debugger evolves.

**Comment by Robert923** [comment]
Thanks @ArtemGovorov  - appreciate that!  :-)

One other minor issue - I can't seem to display more than one variable at a time.   I was checking that two values (long, hex strings) were the same, but of course I can't select them both at the same time.   And, each time I selected the other variable, the code was re-run and the values were re-generated - making it very hard to compare!

**Comment by ArtemGovorov** [comment]
@Robert923 Thanks! Multiple variables watching is on our list to implement :)

**Comment by Martaver** [comment]
Hi Artem,

Thanks for the in-depth reply - seriously, it's really great to know that
our comments are being considered. One of the reasons I really respect and
trust Wallaby!

I'd like to throw down a little challenge with a few things you said, if
you don't mind, for you and your team to consider.

The vision of a continuous debugging workflow is right on. The bottom line
is getting developers to be able to understand why their code isn't doing
what they think it should as fast as possible. In my mind there are only a
few things that are required in order to be able to do this:

   1. Be able to narrow down execution around the problem. Basically, it's
   going to be nasty if you have run the entire application over and over
   again in order to iterate your debugging. Wallaby's approach already does
   this inherently - we can update code and have the test update in real time.
   This is why we heart Wallaby!
   2. Be able to select a point in the execution and see what all the
   variables at that point in time hold.
   3. Be able to step forward and backward through code, in order to be
   able to see what how those variables change.
   4. I would also argue that being able to set 'watches' on particular
   variables is incredibly important too, so you can narrow focus.

Wallaby already nails 1. Some parts of 2 and 3 exist. 4. is kind of met,
because I can console.log variables... But without having all the variables
easily at our fingertips, we're kind of crippled as developers.

Let me explain my point of view - if you think about a developer trying to
debug a problem, a lot of the time we have no idea what could be going
wrong, and so might not have a 'good guess' why a value is coming up
incorrect. In this case, where do you begin? From this perspective, our
goal is to use the debugger to explore the execution and find something we
don't already know. It's this need to discover unknowns that makes it
important to have everything visible at once, at their fingertips.

Debugging is a process of convergence... start with a scope of everything
and narrow it down, over and over again as you learn more about the problem.

Starting from a point where everything is hidden, and requiring developers
to console.log, or otherwise specifically target variables in order to get
any visibility is contrary to this.

I really see that Wallaby can improve upon the experience of the
traditional 'break within execution' style of debugging. It's fast and
execution of a single can be repeated in milliseconds, over and over
again... it's incredibly responsive and puts the ability to explore and
tinker at the developer's fingertips, friction free. But in order to
complete the picture we really need to be able to start with the full
picture of variables and subsequently narrow it down.

Thanks again for developing such a solid piece of software, and for
listening to your customer!

**Comment by FacePalmDev** [comment]
currently 2022... Has this been looked at yet?
