### ISSUE TITLE
Support ava-spec

### ISSUE THREAD

**Issue by arealmaas** [wallabyjs/public#743]
### Issue description or question

Wallaby doesn't seem to pick up tests from ava-spec using the jasmine-syntax.
https://github.com/sheerun/ava-spec
### Wallaby.js configuration file

``` javascript
module.exports = function (wallaby) {
  return {
    files: [
      'app/src/**/*.ts',
      {pattern: 'app/tests/**/*', instrument: false, load: true, ignore: false},
      '!app/src/**/*.spec.ts',
      '!app/tests/unit/tests/**/*'
    ],
    tests: [
      'app/src/**/*.spec.ts',
      'app/tests/unit/tests/**/*.ts'
    ],
    compilers: {
      '**/*.ts': wallaby.compilers.typeScript()
    },
    env: {
      type: 'node'
    },
    testFramework: 'ava'
  };
};

```
### test with ava-spec

``` javascript
describe('the greatest test of all', async(it: any) => {

  it('should be true', t => {
    t.true(true);
  });
});
```
### Code editor or IDE name and version

WebStorm v11
### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Looks like `ava-spec` may need a special support from wallaby because from wallaby perspective it's essentially just a different testing framework.

**Comment by KeKs0r** [comment]
I also just tried running ava-spec, it kinda works but not really. When initially executing wallaby it runs the tests correctly, but after changes and rerunning the tests I am getting the following error:
```
​​[Error] Runtime error: Error: All tests and hooks must be declared synchronously in your test file, and cannot be nested within other tests or hooks.​​
```
Which also happens if I would use ava in my tests instead of ava-spec.

Since the tests are running the first time, I hope this would only be a tiny fix. I would highly appreciate the support for ava-spec, since I am using it in all my current projects and I just wanted to check out wallaby and can't really play around with it yet.

**Comment by ArtemGovorov** [comment]
@KeKs0r [Recycling node processes](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) should help:

```javascript
module.exports = function () {
  return {
    ...

    workers: {
      recycle: true
    }
  };
};
```
