### ISSUE TITLE
[Jest] Need to run setupFiles script prior to processing file. Wallaby ostensibly doesn't support this.

### ISSUE THREAD

**Issue by dsifford** [wallabyjs/public#745]
### Issue description or question
Hello,

I've been struggling to get jest and wallaby to cooperate with each other. I need to set a global (window) variable and have it available prior to running all tests.

I've accomplished that by setting up a script and pointing to that script using Jest's `setupFiles` param.

However, I can not seem to figure out how to get wallaby to follow these instructions.

I've tried pretty much everything, including reading into issues in [various other repos](https://github.com/airbnb/enzyme/issues/80#issuecomment-169860598). I've tried modifying setup and teardown to no avail. Just nothing works.

I am able to get both to cooperate, however, if i just set the window variable before running the tests in the same file, BUT, doing that causes all coverage information to get lost (all dots in the atom sidebar turn white and are marked "no coverage for this line").

**Before setting the window variable in the same file**
![image](https://cloud.githubusercontent.com/assets/5240018/17751699/3fcdccd4-6496-11e6-8b81-6616fc5601e7.png)

**After setting the window variable in the same file**
![image](https://cloud.githubusercontent.com/assets/5240018/17751691/32d15dc0-6496-11e6-861a-8a4efc87b936.png)

Any help is much appreciated.

**Side note:** The console logs in atom are not readable. Wallaby parses its logs using 1 letter per line in the console (I'm assuming this is due to the logs coming from a stream or something). Any chance on fixing that?

![image](https://cloud.githubusercontent.com/assets/5240018/17751552/9805ab02-6495-11e6-80d0-25e4aad4f5fd.png)

### Wallaby.js configuration file

```javascript
module.exports = {
    files: [
        'src/**/*.{tsx,ts}',
        'types/**/*.d.ts',
        './package.json',
        '!src/**/__tests__/*',
        '!src/**/index.{ts,tsx}',
        '!src/lib/js/Frontend.ts',
        '!src/lib/js/utils/TinymceFunctions.ts',
    ],
    tests: [
        'src/**/__tests__/*-test.{ts,tsx}',
    ],
    env: {
        type: 'node',
        runner: 'node',
    },
    testFramework: 'jest',
    setup(wallaby) {
        wallaby.testFramework.configure(require('./package.json').jest);
    },
};
```

**Jest Configs**
```json
  "jest": {
    "scriptPreprocessor": "scripts/jestPreprocessor.js",
    "testFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "moduleFileExtensions": [
      "js",
      "ts",
      "tsx",
      "json"
    ],
    "unmockedModulePathPatterns": [
      "react",
      "react-dom",
      "react-addons-test-utils",
      "fbjs",
      "enzyme",
      "sinon",
      "mobx",
      "mobx-react",
      "lib/js/utils/Constants",
      "scripts/Fixtures"
    ],
    "verbose": true,
    "collectCoverage": true,
    "collectCoverageFrom": [
      "src/**/*.{js,ts,tsx}",
      "!**/{vendor,__tests__}/**",
      "!src/lib/js/Frontend.ts",
      "!src/**/index.{ts,tsx}",
      "!src/lib/js/utils/TinymceFunctions.ts"
    ],
    "coverageDirectory": "tmp/coverage",
    "setupFiles": ["scripts/beforeTest.js"]
  },
```

### Code editor or IDE name and version

Atom - Latest

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment]
> Side note: The console logs in atom are not readable. Wallaby parses its logs using 1 letter per line in the console

It's something that `Jest` introduced recently, for whatever reason they're [writing to stderr and one by one character](https://github.com/facebook/jest/blob/ba3d6883eb5a46341fe6a7db713367dc10abdc4d/packages/jest-cli/src/reporters/BaseReporter.js#L42), and wallaby never buffered any output relying on the output source to do it. For now I have monkey patched their reporter in core v1.0.280, [force the update and give it a go](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

Regarding the `setupFiles` error, [wallaby needs all used files to be in the `files` list](https://wallabyjs.com/docs/config/files.html). The `scripts/beforeTest.js` file is not there and it's most likely the reason for the error. `Jest` should have reported the missing file, but perhaps it's the output issue was preventing you from seeing it.

Not sure if the issue with grey marks is related or not, if the issue is still there after you include the file, please share a repo where it doesn't work because it works on a simple repo (the `beforeTest` is executed).

**Comment by dsifford** [comment]
@ArtemGovorov Thanks for the clarification! I'll give it a whirl and chime back if it doesn't work.

Side note: I'm using jest nightly (`jest@test`) because their "latest" branch breaks coverage reporting for typescript. Probably has nothing to do with my issue, but just throwing it out there.

Thanks again.

**Comment by dsifford** [comment]
Worked like a charm. All issues I've mentioned were fixed. You...are...awesome!

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!

> I'm using jest nightly (`jest@test`)

Please note that I have seen some issues with the nightly version (when typing fast causes Jest to hit cache instead of running tests of the latest file version). I'll be looking into those issues soon.

**Comment by dsifford** [comment]
Noted, thanks again so much.
