### ISSUE TITLE
Using modules in setup function

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#746]
I'm runnning Wallaby and Karma together so I try to keep their configs about the same. Karma does not have something like a `setup` function so if you want to do some setup code, you have to load a file that runs the setup code for you in the global scope.

### Example 1
I have some setup code that `imports` (ES6) some other files so I need to make sure it is transpiled/bundled. In Karma this happens automatically because test files and src files are just together in the files list.

Wallaby however has a separate `tests` list which functions as entry point. This means that the file with setup code only is loaded when I import it from al my test files. Now I have a lot of boilerplate code :(.

### Example 2
I have another project that shows the same issue from another point of view.
There is a **main.js** file which is loaded in my app, but not during tests:

```js
import Vue from 'vue';
import VueResource from 'vue-resource';
Vue.use(VueResource);
// more stuff
```

When `VueResource` is not loaded a lot of tests are breaking. So I want to `use` the `VueResource` in the setup function.

I could add these 3 lines to every test file, but that's overhead again, even when I export these statements from a separate file. Alternative is to load Vue and VueResource lib files globally (ES5) and add `Vue.use(VueResource);` to the setup function, but that feels like the direction you don't want to go to...

Is there any way to `import` or `require` a file into the setup function?

**Comment by ArtemGovorov** [comment]
I think the [entry patterns setting](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns) addresses your question.

For example, with the `main.js`, it may look like:

```javascript
var wallabyPostprocessor = wallabyWebpack({
    entryPatterns: [
            'main.js',
            'src/**/*.spec.js'
            ]
});

return {
        files: [
            ...
            {pattern: 'src/**/*.js', load: false},
            {pattern: 'main.js', load: false},
            {pattern: 'src/**/*.spec.js', ignore: true}
        ],

        tests: [
            {pattern: 'src/**/*.spec.js', load: false}
        ],

        ...

        setup: function () {
            window.__moduleBundler.loadTests();
        }
    };
```

**Comment by fvanwijk** [comment]
Wow you are lightning fast. Thanks, that worked (`browserify` -> `wallabify` -> [`entryPatterns`](https://wallabyjs.com/docs/integration/browserify.html#entry-patterns) in my case)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! Sorry, I should have asked what module bundler you're using, for whatever reason assumed it was webpack.

**Comment by fvanwijk** [comment]
"Potato, potato"

Last week we were using Webpack, now it is Browserify. Next month it might be Webpack again ;)

**Comment by rvanzon** [comment]
Hi, don't know if it's the right place, but because Vue is mentioned: I am looking for an Vue.js (2.0) example. I can get things running only partly. Except: 
1) changes in a Vue-component are not detected (I have to restart Wallaby) 
2) "test colors" are not shown in the Vue-code (only in the unit test), not in VS Code and Atom. I think this is because JavaScript is inline.
My setup is the same as: https://github.com/vuejs-templates/webpack/tree/2.0

**Comment by ArtemGovorov** [comment]
@rvanzon None of us in the team have ever used Vue, neither I have heard anyone using/trying to use wallaby with Vue before (actually remember one question, but it was a long time ago and I couldn't find it), so thanks for sharing the project. Could you please also share your current wallaby config that partly works for the mentioned project?

**Comment by ArtemGovorov** [comment]
@rvanzon Just looking into Vue samples, looks like `.vue` files are a mixture of HTML/JavaScript. Wallaby.js only supports instrumenting pure code file (JS, JSX, TypeScript, CoffeeScript, etc.), but not HTML files with `<script>` tags. So both of the things you mentioned are happening because of it. I'm not yet sure, but perhaps [writing a custom compiler](https://wallabyjs.com/docs/config/compilers.html#writing-a-custom-compiler), that would grab everything inside `<script>` tags and run it through the built-in babel compiler could do the trick  may do the trick. Need to have a working project with wallaby config to see if it's going to work.

**Comment by rvanzon** [comment]
Hi Artem, thanks for responding so quickly! 

Vue.js is gaining popularity rather quickly because it's a pretty good framework. It's very fast and easy to learn. The upcoming version (2.0) is even faster (2-4 times) and adds, among many other things, server side rendering.

I created a new repository, which is based on the "official" webpack-template. I added Wallaby.js and chai in the test (as I don't get it to work when used in wallaby.js yet). The test is included with the template and passes. De code of the Vue-component is located in `src/components/Hello.vue`. If you have any questions I am happy to assist. Thanks!

**Comment by ArtemGovorov** [comment]
@rvanzon Thanks for the repo. I tried to write a custom compiler, but no luck yet. Something somewhere shifts the lines or generates an incorrect source map so that I can't get indicators in the .vue file to display correctly. 

My guess for now is that it happens because the `vue-loader` generates code that loads the script part of the through a babel loader (and this is hardcoded) in the auto-generated `require`.  Wallaby does babel compilation itself so needs to avoid the second one.

I'll investigate more a bit later and let you know if I manage to make it work with vue.

**Comment by rvanzon** [comment]
@ArtemGovorov thanks for your time! I hope you get it working, as Vue js is my (and others of course) tool of choice, and from what I have seen, Wallaby is great and would be a perfect combination!

**Comment by ArtemGovorov** [comment]
@rvanzon I'll try, but can't yet promise anything because there're a few moving parts that are out of wallaby control.
