### ISSUE TITLE
VSCode inline messages issues

### ISSUE THREAD

**Issue by asvetliakov** [wallabyjs/public#751]
### Issue description or question
Tried to evaluate wallaby:
1. Breakpoints are not visible in gutter
2. No inline messages from chai-enzyme
3. Duplicated inline messages
4. Cursor lives by own life due to inlining messages 
5. When typing console.log(large_object) sometimes cursor jumps to the beginning of the line

See screencast:
http://recordit.co/m7FTdhA0lA

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
    return {
        files: [
            "src/**/*.ts?(x)",
            "!src/**/*_Spec.ts?(x)"
        ],
        tests: [
            "src/**/*_Spec.ts?(x)"
        ],
        env: {
            type: "node"
        },
        compilers: {
            "**/*.ts?(x)": wallaby.compilers.typeScript({ module: "commonjs" })
        },
        setup: function () {
            var chai = require("chai");
            var sinonChai = require("sinon-chai");
            var chaiEnzyMe = require("chai-enzyme");
            var chaiImmutable = require("chai-immutable");
            var chaiSubset = require("chai-subset");
            var jsdom = require("jsdom").jsdom;


            //chai.should();
            chai.use(sinonChai);
            chai.use(chaiImmutable);
            chai.use(chaiEnzyMe());
            chai.use(chaiSubset);

            var doc = jsdom(`<html><body></body></html>`);
            global.window = doc.defaultView;
            global.document = doc;

            require("mutationobserver-shim");
            global.MutationObserver = window.MutationObserver;
            global.SVGElement = function () { };
            global.getComputedStyle = window.getComputedStyle;

            // Ignore any styles (react-datepicker loads css)
            require('ignore-styles');


            // For radium & jsdom
            global.navigator = { userAgent: 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2454.85 Safari/537.36' };
        }
    };
}
```

### Code editor or IDE name and version

Visual Studio Code 1.5.0-insider
Using VSCodeVim plugin for VS Code

### OS name and version

Windows 10 14393.82

**Comment by ArtemGovorov** [comment]
Thanks for the feedback!

> 1 Breakpoints are not visible in gutter

There's an opened for this one. Unfortunately there's only space in there for one glyph for now, feel free to vote for the issue in the VS Code repo: https://github.com/Microsoft/vscode/issues/5923

> 2 No inline messages from chai-enzyme

Wallaby.js [reuses node processes by default](https://wallabyjs.com/docs/integration/node.html#node-process-reuse) and it looks like calling `chai.use(chaiEnzyMe());` more than once in a single process breaks `chai` stack reporting. You can easily see it if you break a test, restart wallaby - you'll see the correct inline report. Then if you keep editing the file, it'll stop reporting inline messages.

An easy fix for the issue (apart from configuring wallaby to [recycle processes](https://wallabyjs.com/docs/integration/node.html#node-process-reuse)) is to just call `chai.use(chaiEnzyMe());` once per process. I have created this sample repo with your config. [here's an example of how you can do it](https://github.com/wallabyjs/wallaby-751/blob/master/wallaby.js#L18).

>3 Duplicated inline messages
4 Cursor lives by own life due to inlining messages 
5 When typing console.log(large_object) sometimes cursor jumps to the beginning of the line

These issues seem to be caused by a single reason, not yet sure though because I can't reproduce it in the same environment with the same config. I guess I'm missing some other project specific dependencies/setting.

![i](https://cloud.githubusercontent.com/assets/979966/17841926/fcbc865a-6860-11e6-99a9-8e3a6942add4.gif)


Could you please [clone the sample repo](https://github.com/wallabyjs/wallaby-751) (it contains your config), run `npm i` and try reproducing the issue? If the issue is not reproducible, could you try adding more tests from your project to see if you can break it?

**Comment by asvetliakov** [comment]
Thanks for such informative response!
2. Thanks for pointing to that

3 & 4 & 5
I'm getting same result:
![2016-08-22](https://cloud.githubusercontent.com/assets/8881674/17842060/3bcb6e2a-681f-11e6-9667-2ae14f411494.png)
Perhaps this is because i'm using VSCodeVim plugin (https://github.com/VSCodeVim/Vim) and it's somehow conflicting with wallaby. I'm not sure on which side it should be fixed (by you or by VSCodeVim side), but i'd be just happy if there will be a way to disable inline messages from wallaby (VIM is must for me sorry :smile: )

**Comment by ArtemGovorov** [comment]
Thanks for checking!
I can't reproduce it with the VSCodeVim plugin either. Could you please try disabling the `VSCodeVim` plugin to see if the issue is still there? Just so I know what to try next.

**Comment by ArtemGovorov** [comment]
> disabling VIM plugin doesn't resolve the issue, would try to disable others

Oh, thanks. Disregard my prev message then.

**Comment by ArtemGovorov** [comment]
Could you please try [this sample project](https://github.com/wallabyjs/calculator-sample)? Just clone it, run wallaby and try typing `console.log(abc` in any test, no `npm i` required.

**Comment by ArtemGovorov** [comment]
> would try to disable others

Do you have many other plugins installed? Could you please share the list, I could try install them to see if I can reproduce the issue?

**Comment by asvetliakov** [comment]
The https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets caused that. Disabling this plugin resolves the messages issue, thank you for help and for great product :+1: 

Offtop: is there a way to show only failed tests in wallaby app?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update! I'll look into the plugin to see if we can do anything to protect  from them breaking our inline messages.

> is there a way to show only failed tests in wallaby app?

Not yet, but we're planning to add some filters. For now [Wallaby Tests output channel in VS Code shows all failing tests](https://wallabyjs.com/docs/intro/get-started-vscode.html#failing-tests).

**Comment by ArtemGovorov** [comment]
After looking into the Rainbow Brackets extension, I haven't found anything unusual with the way they highlight brackets, so I have reproduced the issue on a simple case and reported it to the VS Code repo: https://github.com/Microsoft/vscode/issues/10774
