### ISSUE TITLE
Typescript, webpack and ng-metadata

### ISSUE THREAD

**Issue by LPCmedia** [wallabyjs/public#757]
### Issue description or question
I'm having some trouble setting up wallaby with webpack, ts and ng-metadata. 

Hi, thanks for your support on this. 

My project is a combination of ts and js. The legacy app ( js ) has its tests and they are shimmed with chai, sinon etc. I need to add some additional typescript modules. Please see the readme.md for the folder structure. The app also uses oc-lazyload and code splitting to build the modules. 

Karma runs fine ( even if it needs optimization. )

I'm assuming that the way to setup the tests is as follows: 

1 - TS compiler is run by wallaby so the webpack bundler runs on the generated js. 
2 - Most test libs should be handled by wallaby.js files so the shims / testlibs are in the files
3 - A spec-bundle file needs to load the app and modules while 

**Issues & questions :** 
1 - If I disable ts-loader in webpack I get issues regarding the @Inject annotations. 
2 - If I enable it 
    a - how do I approach the module resolution with code-splitting ? 
    b - ts-loader seems to generate a bunch of ts errors ? can't find interfaces, experimental decorators etc.
3 - what am I missing ? I'm going in circles here. 

I copied part of the repo and invited you to it. 
https://github.com/Acquisio/wallaby-test

### Wallaby.js configuration file

```javascript
// var babel = require('babel-core');
var wallabyWebpack = require('wallaby-webpack');
var webpackTestConfig = require('./config/webpack.test.js');
var path = require('path');

module.exports = function(wallaby) {
  delete webpackTestConfig.devtool;
  // removing instrumenters
  delete webpackTestConfig.module.preLoaders;
  delete webpackTestConfig.module.postLoaders;

  // remove ts-loader
  var tsLoaderIndex = webpackTestConfig.module.loaders.findIndex(function(element) {
    return element.loader === 'ts-loader';
  });

  // TURN ON OR OFF webpackTestConfig.module.loaders.splice(tsLoaderIndex, 1);
  webpackTestConfig.context = path.join(wallaby.projectCacheDir, 'src');

  webpackTestConfig.entryPatterns = [
    'test/spec-bundle-wallaby.js',
    'src/**/*.spec.js'
  ]

  return {
    files: [
      {pattern: 'node_modules/jquery/dist/jquery.min.js', instrument: false},
      {pattern: 'node_modules/angular/angular.min.js', instrument: false},
      {pattern: 'node_modules/angular-mocks/angular-mocks.js', instrument: false},
      {pattern: 'node_modules/chai/chai.js', instrument: false},
      {pattern: 'node_modules/chai-as-promised/lib/chai-as-promised.js', instrument: false},
      {pattern: 'node_modules/chai-jquery/chai-jquery.js', instrument: false},
      {pattern: 'node_modules/chai-things/lib/chai-things.js', instrument: false},
      {pattern: 'node_modules/sinon/pkg/sinon-1.17.5.js', instrument: false},
      {pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', instrument: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.spec.ts', ignore: true},
      {pattern: 'src/**/*.spec.js', ignore: true},
      {pattern: 'test/spec-bundle-wallaby.ts', instrument: false, load: false}
    ],

    tests: [
      {pattern: 'src/**/*.spec.*s', load: false},
    ],
    env: {
      type: 'browser'
    },
    testFramework: 'mocha',
    compilers: {
      '**/.ts': wallaby.compilers.typeScript({
        experimentalDecorators: true,
        sourceMap: true,
        emitDecoratorMetadata: true,
        inlineSourceMap: false,
        declaration: false,
        orderFilesByReferenceComments: true,
        pretty: true,
        preserveConstEnums: true

      })
    },
    debug: true,

    postprocessor: wallabyWebpack(webpackTestConfig),
    bootstrap: function() {
      window.angular = angular;
      window.chai = chai;
      window.expect = chai.expect;
      window.__moduleBundler.loadTests();
    }
  };
};

```

### Code editor or IDE name and version

Visual Studio Code v0.10.x

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Thanks for providing the access to the repo. I have pushed the working wallaby config to the repo, with some comments why I changed things. It's really just a couple of changes.

> I'm assuming that the way to setup the tests is as follows:
> 1 - TS compiler is run by wallaby so the webpack bundler runs on the generated js. 

Correct.

> 2 - Most test libs should be handled by wallaby.js files so the shims / testlibs are in the files

Yes, it's more efficient than to `require`/`import` those from `spec-bundle`, because webpack will not have to process those libs. However, wallaby will work either way - you have some libs imported in the `spec-bundle-wallaby` and they work ok.

> 3 - A spec-bundle file needs to load the app and modules

It depends on your app. Some apps require/import dependencies from each spec, this is the most efficient way because if only one spec has to run, no need to load all app modules. In wallaby context, `spec-bundle` is just a file that gets loaded as an entry point (before tests).

> If I disable ts-loader in webpack I get issues regarding the @Inject annotations. 

Your compiler pattern (`**/.ts`) wasn't correct, so wallaby just wasn't compiling anything (it tells how many files get compiled in the debug output for the TS compiler). I have just removed the whole `compilers` section from your config, wallaby is using your `tsconfig.json` by default, so it just works.

Other changes I have made to your wallaby config:
- Removed `.ts` from `webpackTestConfig.resolve.extensions`. Wallaby compiles `.ts` to `.js`, so don't need to allow Webpack load .ts files.
- Pointed webpack to wallaby cache instead of local project folder for moduleDirectories, as [described in the docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder). Otherwise webpack is trying to load modules from `src`, `shared`, etc. from your local project, instead of wallaby cache where everything is compiled/instrumented.
- Removed `chai-things` file loading (it breaks inline error reporting and is not used anyway).
- Fixed source files patter to include `.js` files, not only `.ts`, as you have a mixed source code base.
- Made wallaby use the same PhantomJs version as Karma does (just in case).
- Correctly initialised `chai` globals in the `bootstrap` function.

While I have fixed the above mentioned things pretty quickly and most of the tests are passing, I got stuck with **13 tests that are failing** (most of them in the `..../overlay/overlay.spec.js`). Surprisingly, those tests were failing in wallaby, but passing in karma. After some investigation, I have found out that tests are supposed to fail and **managed to make them fail in karma as well**.

Those tests are making assertions like:
```javascript
expect($document.find('acq-test')).to.exist;
```
and they are passing in karma because it was loading different jQuery versions, so this [check in `chai-jquery`](https://github.com/chaijs/chai-jquery/blob/e1c6697286274bc4c6170040c0f1a7742c8b5798/chai-jquery.js#L169) would execute the `else` branch and the test would pass because `$document.find('acq-test')` object exists, not because the selector returns anything.

You may easily verify that's the case by simply asserting or `console.log`-ing `$document.find('acq-test').length`, which will return you `0` in both wallaby and pseudo-working karma config. I'm guessing that for the same reason a few passing tests in that spec are actually asserting `assert.equal(test.length, 0);` and not `expect($document.find('acq-test')).not.to.exist`.

Hope it makes sense, let me know if it helps.

**Comment by LPCmedia** [comment]
Awesome. I will try it out and let you know.
