### ISSUE TITLE
Electron with node integration and jasmine Error

### ISSUE THREAD

**Issue by gmsconstantino** [wallabyjs/public#764]
### Issue description or question
Hello,

I have a very strange problem with running wallaby in VS Code. I already have runned test with jasmine and electron, but when I add the node integration to electron.

It looks like wallaby can't load jasmine and I can't figure why. What I'm doing wrong here.

<img width="693" alt="screen shot 2016-08-27 at 22 39 17" src="https://cloud.githubusercontent.com/assets/1086856/18030293/8182e294-6ca8-11e6-9830-c72635207244.png">

I have recreated a [repository](https://github.com/gmsconstantino/wallaby-electron-node-jasmine), based on wallaby-electron-node, where I hope my error can be reproduced.

###Code editor or IDE name and version

Visual Studio Code v1.4.0

###OS name and version

MacOS

**Comment by ArtemGovorov** [comment]
Hi,

`jasmine` has [the known issue in Electron environment](https://github.com/jasmine/jasmine/issues/964) (with `node` integration on). It's been [fixed in March 2016](https://github.com/jasmine/jasmine/pull/1079/commits/c302545ba4bfea2c3325dcac798d59cb6cb8f538), but the last published jasmine release [was in Dec 2015](https://github.com/jasmine/jasmine/releases). 

Wallaby has its own version of jasmine embedded, so I just ported the fix and released it in core v1.0.284. It'll be updated automatically or you can [force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).
