### ISSUE TITLE
Equivalent to webpack's `resolve.root`

### ISSUE THREAD

**Issue by brianmhunt** [wallabyjs/public#766]
### Issue description or question

Is there an equivalent to Webpack's [`resolve.root`](https://webpack.github.io/docs/configuration.html#resolve-root)?

### Wallaby.js configuration file

```javascript
  require('something-at-root/file')
```

### Code editor or IDE name and version
Atom v1.9.9

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
It depends on your current wallaby config. If you're configuring browser tests and are using wallaby plus webpack, the you may just use the `resolve.root` setting and pass it to [your wallaby-webpack options](https://wallabyjs.com/docs/integration/webpack.html). If you're using node environment, then you may use [`process.env.NODE_PATH`](https://wallabyjs.com/docs/integration/node.html#node-modules-in-subfolder) to set a root that will act like Webpack's resolve.root.
Could you please share your wallaby.js config?

**Comment by brianmhunt** [comment]
Thanks for the quick response.

I'm working through it, at https://github.com/brianmhunt/build-test

The problem right now is that no tests are run i.e. Wallaby shows 0 failing tests, 0 passing.

Will post if I figure it out!

**Comment by ArtemGovorov** [comment]
Your project doesn't seem to have `webpack` in package.json. [Wallaby console in Atom Dev Tools](https://wallabyjs.com/docs/intro/get-started-atom.html#troubleshooting) may be helpful.

**Comment by brianmhunt** [comment]
Thanks @ArtemGovorov - yes, I've added a few packages that were missing (opening Atom's dev console was illuminating :))

I've updated master - same problem (no tests running), but I've not yet rooted out what the issue is.

**Comment by ArtemGovorov** [comment]
I have sent you the pull request: https://github.com/brianmhunt/build-test/pull/1. 
- added `resolve.root` to map to the wallaby cache, as [described in the docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder),
- added webpack `json-loader` for `.yaml` files (because your preprocessor converts them to JSON), you'll also need to `npm install --save json-loader`,
- added missing file patterns, 
- [compiler for ES6 `.js`](https://wallabyjs.com/docs/integration/es-next.html) and for CoffeeScript (it wouldn't be required, but need to change its default behaviour of renaming all `.coffee` files to `.js` because you're importing with file extensions),
- fixed typo in `postprocessor` setting,
- merged `setup` and `bootstrap` function as pit's the same thing (just an alias)](https://wallabyjs.com/docs/config/bootstrap.html).

Few of the tests are failing, but looks like for some valid reasons. Other than that, it's working for me.

Please check to see if it works for you and let let me know if it does or doesn't.

**Comment by brianmhunt** [comment]
Thank you very much, @ArtemGovorov – That would've taken an inordinately long time for me to figure out.
