### ISSUE TITLE
Loading Wallaby theme

### ISSUE THREAD

**Issue by IPWright83** [wallabyjs/public#771]
### Issue description or question

Issues with the theme when loading other plugins. I've tried installing an eslint plugin:

`SublimeLinter`
`SublimeLinter-contrib-eslint`

When I have both this and wallaby running however I get issues:

![image](https://cloud.githubusercontent.com/assets/1374775/18171036/6f5680a4-7058-11e6-810c-598c2d444381.png)

### Code editor or IDE name and version

Sublime Text v3 - Dev Build 3119

### OS name and version

Windows 10 Pro x64

**Comment by ArtemGovorov** [comment]
We have seen the issue few times, wallaby has to copy your existing colour theme in order to overcome some Sublime Text styling limitations. Some of the packages may be using the same workaround, so it may conflict sometimes. Just re-select your color theme (Monokai) in Sublime Text menu and restart the editor, the issue should be fixed.
