### ISSUE TITLE
Require a startup file with webpack in typescript

### ISSUE THREAD

**Issue by tjoskar** [wallabyjs/public#782]
Hi,

I'm using typescript and webpack and are running the test in the browser. I need however to import a startup file to modify the global context (window) before the test runs. 

As I understand it, I should only need to add the file into the `files`-list? But when I do so I get the following error:

```
Uncaught SyntaxError: Unexpected token import
at http://localhost:62166/__modules/148.js?1473526904487:1
Uncaught Error: Cannot find module '148'
at http://localhost:62166/wallaby-webpack.js?1473526904588:1
```

Which I find hard to interpret ;)

There are only two test cases that require the startup file ([test/helpers/test-helper.ts](https://github.com/tjoskar/ng2-lazyload-image/blob/8d0287d258ca21ab573f30c0ee44533a97e15d18/test/helpers/test-helper.ts)) so the other test cases works fine.

Furthermore, if I use [karma](https://github.com/tjoskar/ng2-lazyload-image/blob/8d0287d258ca21ab573f30c0ee44533a97e15d18/karma.default.js) (without wallaby) the test cases works fine.

### Wallaby.js configuration file

```javascript
const path = require('path');
const wallabyWebpack = require('wallaby-webpack');

const webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'unit-test.bundle.js',
        'test/**/*.test.js'
    ]
});

module.exports = () => {

    return {

        files: [
            {pattern: 'test/helpers/test-helper.ts', load: false}, // the file I need to include before the test runs
            {pattern: 'unit-test.bundle.js', load: false},
            {pattern: 'src/**/*.ts', load: false},
            {pattern: 'test/**/*.ts', load: false},
            {pattern: 'test/**/*.test.ts', ignore: true}
        ],

        tests: [
            {pattern: 'test/**/*test.ts', load: false}
        ],

        env: {
            kind: 'electron'
        },

        testFramework: 'mocha',

        postprocessor: webpackPostprocessor,

        setup: function() {
            window.__moduleBundler.loadTests();
        },

        debug: true
    };
};

```

You can find the project here: https://github.com/tjoskar/ng2-lazyload-image/tree/feature/wallaby

My wallaby config file: https://github.com/tjoskar/ng2-lazyload-image/blob/8d0287d258ca21ab573f30c0ee44533a97e15d18/wallaby.js
The file I need to execute before the test case: https://github.com/tjoskar/ng2-lazyload-image/blob/8d0287d258ca21ab573f30c0ee44533a97e15d18/test/helpers/test-helper.ts

Karma config that works: https://github.com/tjoskar/ng2-lazyload-image/blob/8d0287d258ca21ab573f30c0ee44533a97e15d18/karma.default.js (you can test it by running `npm test`)

I guess my question boil down to how I can import a file that executes before the test case. Form what I understand, I can't use [setup](https://wallabyjs.com/docs/config/bootstrap.html) since I need to require a file which I can not do since the `setup` method runs in the browser context.

Sorry that I can't pointing out the error in more detail.

### Code editor or IDE name and version
Atom v1.10.2

### OS name and version
OSX v10.11.6

**Comment by ArtemGovorov** [comment]
> I guess my question boil down to how I can import a file that executes before the test case. Form what I understand, I can't use setup since I need to require a file which I can not do since the setup method runs in the browser context.

You may use [`entryPatterns` for this](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns). You are already using it for making `unit-test.bundle.js` an entry point, so may just add the `'test/helpers/test-helper.js',` file there:
```javascript
const webpackPostprocessor = wallabyWebpack({
    entryPatterns: [
        'unit-test.bundle.js',
        'test/helpers/test-helper.js',
        'test/**/*.test.js'
    ]
});
```
(note that I added it with the `.js` extension because wallaby TS compiler renames files from `.ts` to `.js` as mentioned in the docs)

There's one more issue with you config, causing the 
```
Uncaught SyntaxError: Unexpected token import
at http://localhost:62166/__modules/148.js?1473526904487:1
```
error. If you try opening the file `http://localhost:62166/__modules/148.js` in browser (note that the port is changing between wallaby restarts) while wallaby is running, you'll see the issue - the file is TS file not compiled to JS.

It happens because you do this: 
```javascript
var testContext = require.context('./test', true, /\.test\.ts/);
testContext.keys().forEach(testContext);
```
in the `unit-test.bundle.js` file.
This is basically a way karma needs to run tests, but wallaby doesn't need it and require-ing the `.ts` files breaks it. Wallaby runs your tests when your `setup` function calls `window.__moduleBundler.loadTests();`.

If you comment out these two lines, everything should works for you in wallaby. Now because karma needs those lines, you may create a `unit-test.karma.bundle.js`, move those 2 lines to that file,  so that your `unit-test.bundle.js` looks like:
```javascript
Error.stackTraceLimit = 5;
require('core-js/es7/reflect');
require('zone.js/dist/zone');
require('zone.js/dist/long-stack-trace-zone');
if (window.__karma) require('./unit-test.karma.bundle');
```
so it'll work both in wallaby and karma. Note that it will not work without a separate file (just by doing the `if` with those two lines in the same file) because of the way webpack works.

Hope it makes sense. Let me now if it helps.

**Comment by tjoskar** [comment]
Aaaa, alright! Thanks @ArtemGovorov! And thanks for your detailed answer!

If someone finding this issue and have the same problem:
```
if (window.__karma) require('./unit-test.karma.bundle');
// should be (for karma 1.3.0):
if (window.__karma__) require('./unit-test.karma.bundle');
```

And make sure to add:
```
module: {
  loaders: [
    {test: /unit-test\.karma\.bundle\.js/, loader: 'null'}
  ]
}
```
in your wallaby webpack config. 

You can find my wallaby config here: https://github.com/tjoskar/ng2-lazyload-image/blob/master/wallaby.js

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the corrections/notes @tjoskar!
