### ISSUE TITLE
is it possible to replace babel compiler with babel-register

### ISSUE THREAD

**Issue by yanivefraim** [wallabyjs/public#783]
we use babel register for our mocha tests, something similar to this:

`"test": "mocha --compilers js:babel/register --require ./test/test_helper.js  --recursive",`

can we use the same in our wallaby? something like requiring 'babel-register' somewhere? And if so, will it have same performance as using wallaby's babel compiler?

Thanks!

**Comment by ArtemGovorov** [comment]
You may use `babel-register`, but only for files that will not be instrumented (and will not have the coverage displayed). If you'd like to have wallaby coverage, then wallaby compiler has to be used because it's doing the code instrumentation that enables the code coverage, etc.

For example, have a look into [this sample config](https://github.com/wallabyjs/public/issues/602#issuecomment-220504165) where `babel-register` is used for compiling ES6 node modules, while wallaby compiler is used to the rest.

Performance wise, wallaby compiler is the fastest way because it's done upfront so no runtime compilation is required. However, I'd be surprised if `babel-register` doesn't use babel cache, so should also be pretty fast. If it uses the cache, then really the only difference will be that `babel-register` will have to do the cache checks/access, while wallaby doesn't have to.
