### ISSUE TITLE
typescript- target is es2015 is not working

### ISSUE THREAD

**Issue by rgoldman-qb** [wallabyjs/public#787]
Im getting a syntax error when trying to destructure off an object
for example `const { a } = obj;`
throws an error of
```
​​SyntaxError: Unexpected token {​​
```
I've created a repo demonstrating the issue.
Please let me know if you have any trouble reproducing
https://github.com/rgoldman-qb/wallaby-typescript-sample
 

### Wallaby.js configuration file
_Please see linked repo_

### Code editor or IDE name and version
Visual Studio Code v1.4.0

### OS name and version
OSX

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

It works for me with the latest version of node.js (6.x), but when I switch to node 4.x, it starts showing the error you're observing, and it's expected because older versions of node don't fully support ES6 syntax. 
You may upgrade your node.js version, or install a newer version side by side with the current one (with something like `nvm`) and [configure wallaby for VS Code to use the version](https://wallabyjs.com/docs/intro/install.html#nodejs-2).

**Comment by rgoldman-qb** [comment]
that worked thanks!
