### ISSUE TITLE
Limit re-running tests until file is explicitly saved in IDE

### ISSUE THREAD

**Issue by vjpr** [wallabyjs/public#789]
Test runs slow down my editor. It's not huge, but its enough to create a bit of typing lag.

It would be great to have an option that would only run tests on save.

I am using IntelliJ 2016.

**Comment by ArtemGovorov** [comment]
I understand that it's not quite the same as you're requesting, but before the feature is implemented, you may for now try using [the `delays` setting](https://wallabyjs.com/docs/config/overview.html#delays-setting) to throttle test runs a bit (so that the tests will only run after the configured delay in code editing).

**Comment by vjpr** [comment]
Thanks for the speedy response. For now I am using a 1s run delay and its an improvement.

**Comment by ArtemGovorov** [comment]
There was (is) an `edit` setting, but it's obsolete - not likely to ever be removed, but only implemented in some supported editors. You may still use it in IntelliJ based IDEs.

Regarding test runs slowing down your editor - do you have many tests re-running on normal editing? Or it's just that some tests are very CPU intensive or the machine is not very powerful?

You may also try limiting test run parallelization to one worker (one core on your machine) as [described here](https://wallabyjs.com/docs/config/workers.html).

**Comment by vjpr** [comment]
> do you have many tests re-running on normal editing? 

Just a single test really, but it did access the db.

I will try to see if I can isolate the behaviour. I'm not seeing such a lag with 1s delay.

**Comment by lgandecki** [comment]
@ArtemGovorov any update on this? 
To be honest, wallabyjs has not been stable for us in multiple big projects, when I start refactoring and for example cut/paste things around, breaking syntax meanwhile, wallabyjs tends to "die", very often without any indicator.. so it keeps showing green, until I realize that's something is wrong, manually restart wallabyjs, to see errors. By then I don't know at which point I broke the tests, which defeats the purpose of wallaby. Restarting wallabyjs (when we see green and don't expect it, and when we se red when we think it should be green) become our habit, and it very often fixes the problem. I've had the same experience with more than 5 codebases, react, react-native, blaze, meteor, express, pure nodejs.. 

Me and my coders have started running wallabyjs alongside with cli test runner, to have both great IDE indicator of coverage/which tests break (and where), results from console.log etc,, and reliability of tests at the same time.

We can increase delay but it's a presure on us to not have syntax errors before the delay passes. Which means, we either miss it often, or increase the delay to seconds, which makes it slower than running on save anyway.

Running on save would be great, because then we skip the moments when we know the code is broken. Realtime is nice, but it's mostly just a wow factor, it's not very useful, unless it's super stable, and doesn't break regularly :( Running on save would be as much useful, especially if you force yourself to save everytime your code "makes sense"/lacks syntax errors. 

btw, what is the "edit" option, that is supposed to work in IntelliJ?

**Comment by ArtemGovorov** [comment]
@lgandecki I'm going to address your points in the other issue where you've left your other comment. This feature (running on save) is orthogonal to the issues that you are observing, and, when implemented, will not be able to solve them anyway (you'd get the exact same issue but delayed).

**Comment by asvetliakov** [comment]
I think this ability (run tests only after save) is critical for few cases, one scenario which i'm currently facing now:
1) I have monorepo which consist of 6 packages and running wallaby for whole monorepo.
2) One of the packages is the UI library which exports all content via top-level index.ts
3) 5 other packages are consuming content of this lib though top-level export, i.e. dependent of lib's index.ts, have ~250-300 test suites and mapped to UI library sources through ```moduleNameMapper```
4) The attempt to edit some component in this UI library is resulting to almost full monorepo rerun on every keystroke since 5 other packages are heavily depending on the UI package. Running 200-300 suites with ~1500 tests inside is just very slow no matter what.

Other issue - i'm using vscode and VSCodeVim plugin for editing. Since both wallaby & vscodevim are sharing one single extension host of vscode, running big number of test suites while typing makes my editing experience very sluggish. It's not wallaby fault but another point to consider to implement this feature.

**Comment by unional** [comment]
Another critical use case for run-on-save: the test code is making live calls to a remote server (e.g. GitHub API).

Now, GitHub team may start banging on my door any moment.

**Comment by farzher** [comment]
I also need run onsave to stop making so many remote requests.
not to mention wallaby executing dangerous requests mid-typing `delete from users` ... ` where id=1` o: !

**Comment by smcenlly** [comment]
Our integrations for VS Code and JetBrains editors (e.g. IntelliJ, WebStorm, etc.) now support the ability to switch between triggering a test run when code is edited and when a file save occurs within your project. See instructions below. We'll be enhancing this feature further over the coming week to support providing the project default using your Wallaby configuration.

---

**For Wallaby for VS Code (v1.0.145+)**
Three new commands are available:
* Wallaby.js: Make current session Run on any change
* Wallaby.js: Make current session Run only on save
* Wallaby.js: Toggle current session Run mode (any change/on save)

---

**For Wallaby for IntelliJ Editors (v1.0.142+)**
Two new commands are available on the left hand side of your Wallaby run configuration window (underneath Re-run and Stop):
* Wallaby.js: Make current session Run on any change
* Wallaby.js: Make current session Run only on save

_Important Note:_ to use this feature with IntelliJ, you must first disable auto-save:

1. Go to File > Settings (Ctrl+Alt+S).
2. Go to Appearance & Behavior > System Settings.
3. Make sure the two are unchecked:
4. Save files on frame deactivation
5. Save files automatically if application is idle for x sec.
6. Go to Editor > General > Editor Tabs
7. Put a checkmark on "Mark modified files with asterisk"
8. (Optional but recommended) Under "Tab Closing Policy", select "Close non-modified files first". You may also want to increase the number of allowed tabs.
9. Click Apply > OK.

**Comment by selfrefactor** [comment]
My issue is that as I paid only one time, I wouldn't receive this feature - which is quite important. I guess I will keep not using Wallaby, even if I have paid it.

**Comment by smcenlly** [comment]
@selfrefactor - we understand if you do not wish to renew your license. Having said that, if you're not aware, the renewal price for personal licenses includes a 50% discount off the normal price. You may email us if you have any questions (hello@wallabyjs.com). In addition to this feature, we have also recently released [automatic configuration](https://wallabyjs.com/docs/intro/config.html#automatic-configuration) for Jest (v24+) and Angular CLI (v8.2+) that may be of interest. You may also request a [trial license](https://wallabyjs.com/download/#try-it-free) if you'd like to try the latest release.

**Comment by smcenlly** [comment]
This feature is now available in all editors. In addition to being able to change what triggers test runs after Wallaby has started, you can also set the default run mode to `onsave` in your Wallaby configuration file:

```javascript
module.exports = function (wallaby) {
  return {
    files: [
      ...
    ],

    tests: [
      ...
    ],

    runMode: 'onsave'
  };
};
```

Please refer to our docs for more information on the wallaby configuration file setting as well as editor-specific commands for changing the mode after starting Wallaby:

* [Configuration File Setting](https://wallabyjs.com/docs/config/overview.html#run-mode-automatic--on-save)
* [VS Code docs](https://wallabyjs.com/docs/intro/get-started-vscode.html#commands)
* [JetBrains IDEs docs](https://wallabyjs.com/docs/intro/get-started-jetbrains.html#run-only-on-save)
* [Visual Studio docs](https://wallabyjs.com/docs/intro/get-started-vs.html#other-actions)
* [Atom docs](https://wallabyjs.com/docs/intro/get-started-atom.html#commands)
* [Sublime docs](https://wallabyjs.com/docs/intro/get-started-sublime.html#commands)

**Comment by lgandecki** [comment]
Fantastic news! Thank you guys!
