### ISSUE TITLE
Errors when running with Jest

### ISSUE THREAD

**Issue by okonet** [wallabyjs/public#795]
### Issue description or question

When running wallaby with Jest I'm getting:

```
console.log:   ● Test suite failed to run

    TypeError: Cannot read property 'cache' of undefined
      
      at Object.<anonymous> (src/containers/Board/reducer.spec.js.wbp.js:1:112)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

Exact same config worked fine last week.

### Wallaby.js configuration file

```javascript
process.env.BABEL_ENV = 'test'

const wallabyWebpack = require('wallaby-webpack')
const webpackConfig = require('./webpack.config')

const wallabyPostprocessor = wallabyWebpack(webpackConfig)

module.exports = wallaby => ({
  files: [
    { pattern: 'src/**/*.js', load: false },
    { pattern: 'src/**/*.spec.js', ignore: true }
  ],

  tests: [
    { pattern: 'src/**/*.spec.js', load: false }
  ],

  compilers: {
    'src/**/*.js': wallaby.compilers.babel()
  },

  env: {
    type: 'node',
    runner: 'node'
  },

  testFramework: 'jest',

  postprocessor: wallabyPostprocessor,

})
```

### Code editor or IDE name and version

IntelliJ IDEA v2016.3 EAP

### OS name and version

OSX 10.11.5 (15F34)

**Comment by ArtemGovorov** [comment]
I'm not sure how it was working before, but wallaby never supported the scenario: node + environment + Webpack together. In wallaby it was always either a browser environment (with webpack) or not environment (with native CommonJs).

While we may add the support in future, we actually see most of our customers avoiding using webpack when running tests in node. Apart from the fact that it's way easier to set up, one major (and not only wallaby specific) reason is that using webpack to run tests in node is slowing the tests down. Mostly because it is an unnecessary compilation/bundling of CommonJs code that node supports natively anyway. If tests are already running in node (and in case of using Jest it is the only option), then why not skipping the webpack part for tests altogether.

So we see many users ending up having a webpack production build, but running tests in pure node with jsdom (it's how jest works anyway) +  setting a noop function as a loader for assets (for example using a `require.extensions[".css"] = noop;` call or node modules like https://www.npmjs.com/package/ignore-styles).

Here are a couple of examples:
https://github.com/wallabyjs/public/issues/719#issuecomment-237132412
https://github.com/wallabyjs/public/issues/684#issue-165139502
https://github.com/wallabyjs/public/issues/642#issuecomment-225146019

Please let me know if it addresses your question.

**Comment by ArtemGovorov** [comment]
Forgot to mention, perhaps it was working without this line:
```javascript
postprocessor: wallabyPostprocessor,
```
and other webpack related stuff. Try removing it to see how it goes.

**Comment by okonet** [comment]
It doesn't work without the webpack preprocessor. I've tried it already.

**Comment by okonet** [comment]
So, with the following config:

```js
process.env.BABEL_ENV = 'test'

module.exports = wallaby => ({
  files: [
    { pattern: 'src/**/*.js', load: false },
    { pattern: 'src/**/*.spec.js', ignore: true }
  ],

  tests: [
    { pattern: 'src/**/*.spec.js', load: false }
  ],

  compilers: {
    'src/**/*.js': wallaby.compilers.babel()
  },

  env: {
    type: 'node',
    runner: 'node'
  },

  testFramework: 'jest'
})
```

I see `No failing tests, 0 passing`

and it looks like this:

![2016-09-20 at 13 19](https://cloud.githubusercontent.com/assets/11071/18668306/f299a91a-7f34-11e6-9426-d9248b484bb8.png)

**Comment by ArtemGovorov** [comment]
Oh, sorry, forgot to mention, you'll need to remove `load: false` from `files` and `tests`, it's only required for webpack.

**Comment by okonet** [comment]
That worked! Thanks.

Still not sure how could it work last week with the previous config. I've been writing tests like this for a few days.

**Comment by ArtemGovorov** [comment]
Well, we never officially added the support for the scenario, but also never tested it, so perhaps it just works under some circumstances and in some scenarios.
