### ISSUE TITLE
Reify and async-to-gen

### ISSUE THREAD

**Issue by djhi** [wallabyjs/public#797]
### Issue description or question
Hello, 

I'm testing this tool and trying to make it work with [reify](https://github.com/benjamn/reify) and [async-to-gen](https://github.com/leebyron/async-to-gen).

Following the docs and issues, I tried to set `preprocessors` without luck and then `setup` (like in [this issue](https://github.com/wallabyjs/public/issues/759), but none of these two approaches worked.

Any help would be greatly appreciated :)

### Wallaby.js configuration file

```javascript
module.exports = () => ({
    files: [
        'src/api/**/*.js',
        { pattern: 'src/api/**/*.spec.js', ignore: true },
    ],

    tests: [
        'src/api/**/*.spec.js',
    ],

    testFramework: 'mocha',

    env: {
        type: 'node',
    },

    setup: wallaby => {
        require(require('path').join(wallaby.localProjectDir, 'node_modules/reify'));
        require(require('path').join(wallaby.localProjectDir, 'node_modules/async-to-gen/register'));
    },
});
```

### Code editor or IDE name and version
Atom v1.10.2

### OS name and version
Linux (Ubuntu 16.04)

**Comment by ArtemGovorov** [comment]
Hello,

Using hooks in the `setup` will not work (it may compile, but inline messages and line mapping may be broken because `async-to-gen` will not supply a source map).

After playing a bit I've managed to make it work with preprocessors:

```javascript
module.exports = () => ({
    
    ...

    preprocessors: {
      '**/*.js': [
        file => require('reify/lib/compiler').compile(file.content),
        file => {
          var result = require('async-to-gen')(file.content, {sourceMaps: true});
          if (!result.isEdited) return file.content;
          var sourceMap = result.generateMap();
          sourceMap.sources = sourceMap.sourcesContent = [''];
          return {
            map: sourceMap,
            code: result.toString()
          };
        }
      ]
    },

    setup: () => {
      require('reify/node/runtime');
    }
});
```
There're two preprocessors, one for `reify` (doesn't need a source map because `reify` doesn't generate one, instead it pads the code so the number of line doesn't change), and one for `async-to-gen` (is using a source map). The values that the `async-to-gen` generates for `sourceMap.sources/sourceMap.sourcesContent` are not valid for the source map consumer, so I'm just clearing them out.

There's also a `setup` function require-ing `reify` runtime, it's required because the code generated by `reify` invokes `module.import(...)` and `module.export(...)` functions defined in the required runtime module.

With this setup a sample project like this one works for me:

<img width="471" alt="screen shot 2016-09-21 at 3 49 42 pm" src="https://cloud.githubusercontent.com/assets/979966/18699211/2439ca5c-8013-11e6-9a4f-192c1876a628.png">

Let me know if this works for you.

**Comment by ArtemGovorov** [comment]
Forgot to mention, we have added `async/await` native instrumentation support for this scenario, so you'll need the latest core v1.0.291. The core will be updated automatically between wallaby restarts, or to get the change ASAP, you [may force the update](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update).

**Comment by djhi** [comment]
Thanks @ArtemGovorov ! It works fine with this setup and I learned something about reify :) Couldn't figure out how to make it "compile" some code.

What do you mean by native instrumentation ? I wouldn't even need async-to-gen ?

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update.

> What do you mean by native instrumentation ? I wouldn't even need async-to-gen ?

I mean wallaby is now able to instrument code that contains async/await. I called it "native" because the way it would normally work before, is with babel compiler compiling the ES7/TypeScript code to ES5 or ES6 and then wallaby doing the instrumentation. As most of our users are using babel with ES7, we didn't need to instrument ES7 code. So it was just a poorly selected terminology on my side, and you do need to `async-to-gen` (well, until node.js adds support for async/await).

**Comment by ArtemGovorov** [comment]
Unfortunately I had to roll back the change in the parser for now because of [this issue](https://github.com/MatAtBread/acorn-es7-plugin/issues/14). Will put it back once the issue is resolved.

**Comment by ArtemGovorov** [comment]
Actually, disregard my previous comment, it'a all working now (with the latest acorn version).
