### ISSUE TITLE
Angular 2 issue with Test-bed angular-class Webpack Starter

### ISSUE THREAD

**Issue by vespertilian** [wallabyjs/public#812]
### Issue description or question

Angular 2 Webpack Starter issue with test component builder and useValue: 

You may need an appropriate loader to handle this file type.

Here is a repository with the issue (Branch: wallaby_failure)
https://github.com/Benefex/angular2-webpack-starter/tree/wallaby_failure

In the about.spec

```js
  beforeEach(() => TestBed.configureTestingModule({
    providers: [
      // provide a better mock
      {
        provide: ActivatedRoute,
        useValue: {
          data: {
            subscribe: (fn: (value: Data) => void) => fn({
              yourData: 'yolo'
            })
          }
        }
      },
      About
    ]
  }));
```

yields error

```js 
Error: Module parse failed: .\src\app\about\about.spec.ts Unexpected token (17:26)
You may need an appropriate loader to handle this file type.
|         useValue: {
|           data: {
|             subscribe: (fn: (value: Data) => void) => fn({
|               yourData: 'yolo'
|             })
at http://localhost:60129/__modules/874.js?1475501739532:1

```
### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');

var webpackPostprocessor = wallabyWebpack({
  entryPatterns: [
    'config/spec-bundle.js',
    'src/**/*spec.js'
  ],

  module: {
    loaders: [
      {test: /\.css$/, loader: 'raw-loader'},
      {test: /\.html$/, loader: 'raw-loader'},
      {test: /karma-require/, loader: 'null'},
      { test: /\.jade$/, loader: 'pug-html-loader' },
      {test: /\.(scss|sass)$/, loader: 'null'},
    ],
    // plugins: [
    //   new webpack.NormalModuleReplacementPlugin(/\.(scss|sass)$/, path.resolve('./', './empty-module.js'))
    // ]
  }
});

module.exports = function () {

  return {
    files: [
      {pattern: 'config/spec-bundle.js', load: false},
      {pattern: 'config/karma-require.js', load: false},
      {pattern: 'src/**/*.ts', load: false},
      {pattern: 'src/**/*.css', load: false},
      {pattern: 'src/**/*.html', load: false},
      {pattern: 'src/**/*.jade', load: false},
      {pattern: 'src/**/*.sass', load: false},
      {pattern: 'src/**/*.scss', load: false},
      {pattern: 'src/**/*spec.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/**/*spec.ts', load: false},
      {pattern: 'test/**/*spec.ts', load: false}
    ],

    testFramework: 'jasmine',

    env: {
      runner: require('phantomjs-prebuilt').path,
      params: { runner: '--web-security=false' }
    },

    postprocessor: webpackPostprocessor,

    setup: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

### Code editor or IDE name and version

WebStorm v2016.2.3

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

As described [in this issue](https://github.com/wallabyjs/public/issues/782#issuecomment-246156290), [karma needs to run a hack](https://github.com/Benefex/angular2-webpack-starter/blob/wallaby_failure/config/spec-bundle.js#L42) that is not required when running tests in wallaby (and breaks the runner because plain TS files are required - hence the error you're getting). So you may just extract the [the hack for karma into a separate file](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/karma-require.js) and conditionally require the file like [it is done in this sample](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/spec-bundle.js#L39) (where you'be probably taken the wallaby config from). This way the setup will work in both wallaby and karma.

I have also sent [the PR with wallaby config updates](https://github.com/Benefex/angular2-webpack-starter/pull/1), you need to add `.json` files and loader, and exclude `.d.ts` files (otherwise they interfere with compilation). You also need to run `npm i null-loader --save-dev` to install the null loader.

Hope it makes sense. Let me know if this helps.

**Comment by ArtemGovorov** [comment]
Oh, forgot to mention one more thing - please update your `wallaby-webpack` package to latest (0.0.25), there's been a bug fix there that is required for the sample to work.

**Comment by ArtemGovorov** [comment]
Re: https://github.com/wallabyjs/public/issues/814#issuecomment-251691913

1) SASS related errors are caused by the difference in your test webpack config and wallaby webpack config:

```javascript
var webpackPostprocessor = wallabyWebpack({
  ...
  module: {
    loaders: [
      ...
      {test: /\.(scss|sass)$/, loaders: ['raw', 'sass']}, // <--like in webpack.test.js
      ...
    ]
  }
});
```

Also, SASS compiler node module is node version dependent, so you'll need to change your node.js version in wallaby.js Run Configuration in Webstorm to point to your system default (in `Program Files`):

<img width="848" alt="screen shot 2016-10-06 at 10 42 54 am" src="https://cloud.githubusercontent.com/assets/979966/19136671/c5ac62e2-8bb1-11e6-9cb5-dc04de30805d.png">

2) The `matchers.spec.ts` file doesn't contain any tests, but is named using the pattern that you're using to name your tests. Wallaby.js requires `tests` to [only contain files with tests](https://wallabyjs.com/docs/config/files.html#tests), test helpers must be in the `files` list. You may either rename the file to `matchers.ts` or exclude it from the `tests` list and include to the `files` list.

Once the file is renamed, you'll need to let wallaby know to load it globally via script tag (because if it is not imported from anywhere, it will not be loaded by webpack):

```javascript
module.exports = function () {

  return {
    files: [
      'src/matchers.ts', // is the same as {pattern: 'src/matchers.ts', load: true}
      ...
    ],
```
