### ISSUE TITLE
Cannot find module 'C:\Users\xps-15-landria\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.28\wallaby\server.js'

### ISSUE THREAD

**Issue by leon-andria** [wallabyjs/public#820]
### Issue description or question
Error: Cannot find module 'C:\Users\xps-15-landria\.vscode\extensions\WallabyJs.wallaby-vscode-1.0.28\wallaby\server.js'
### Code editor or IDE name and version
Visual Studio Code v1.5.3
### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
Try re-installing the extension.

**Comment by leon-andria** [comment]
I did it and it works.
But i'm not confident why happen like this, one day, it works perfectly and day after, having restarting my laptop, it happens like this. 
Hopefully that this happen once because I do'nt spend my time to re-enter my paid licence every time.

Thanks for you support.

**Comment by ArtemGovorov** [comment]
Thanks for the update. I can only see it happening when an automatic core
update failed for some reason. We don't have any other reports of issues
like this from other users, so hopefully it was just a one time glitch. Let
me know if it happens to you on a regular basis.

On 9 Oct 2016, at 8:39 PM, Andrianarivony Leon <notifications@github.com>
wrote:

I did it and it works.
But i'm not confident why happen like this, one day, it works perfectly and
day after, having restarting my laptop, it happens like this.
Hopefully that this happen once because I do'nt spend my time to re-enter
my paid licence every time.

Thanks for you support.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/wallabyjs/public/issues/820#issuecomment-252478891>,
or mute
the thread
