### ISSUE TITLE
electron require directory

### ISSUE THREAD

**Issue by tamascsaba** [wallabyjs/public#827]
I want to use electron nodeIntegration to require tests and test require your files, which speed up lot of my test running process (with wallaby-webpack or wallabify runs very slow).

### Wallaby.js configuration file

```javascript
module.exports = function (wallaby) {
  return {
    debug: true,
    files: [
      {pattern: 'src/client/testing/setup.ts'},
      {pattern: 'src/client/**/*.ts', load: false},
      {pattern: 'src/client/**/*.test.ts', ignore: true}
    ],

    tests: [
      {pattern: 'src/client/**/*.test.ts', load: false},
    ],

    testFramework: 'jasmine',

    env: {
      kind: 'electron',
      runner: require('electron'),
      options: {
        webPreferences: {
          nodeIntegration: true
        }
      }
    },

    bootstrap: function (w) {
      require('module').globalPaths.push(require('path').join(process.cwd(), 'node_modules'));
      requireGlob([w.baseDir + '/**/*test.js']).then(function (modules) {
        console.log(modules); // load nothing 
      });
    }
  };
};

```

### Example test
foo.test.ts

```typescript
import {foo} from './foo';

describe('foo', () => {
  it('to be defined', () => {
    expect(foo).toEqual({foo: true});
  });
});

```

### Code editor or IDE name and version
WebStorm 2016.02.3

### OS name and version
Linux

**Comment by ArtemGovorov** [comment]
The `bootstrap` (AKA `setup`) function is sync, so that's why the `then` callaback is not called You may try [using `delayStart` and then `start`](https://wallabyjs.com/docs/config/bootstrap.html):
```javascript
bootstrap: function (w) {
      w.delayStart();
      require('module').globalPaths.push(require('path').join(process.cwd(), 'node_modules'));
      requireGlob([w.baseDir + '/**/*test.js']).then(function (modules) {
        ...
        w.start();
      });
    }
```
but I haven't tried this specific setup (Electron+node require for tests/files). When uses want better performance they normally just switch their tests to use [plain node with wallaby](https://wallabyjs.com/docs/integration/node.html) plus [jsdom](https://github.com/tmpvar/jsdom) if DOM interaction is required.

**Comment by tamascsaba** [comment]
Thanks, for quick answer, unfortunately it does not work :( requireGlob load my modules but webstorm not show anything. 

I can't use node until https://github.com/angular/zone.js/pull/475 will be merged, but nice idea
