### ISSUE TITLE
Help with config file for Ionic2 RC1

### ISSUE THREAD

**Issue by superkew** [wallabyjs/public#834]
### Issue description or question
I've tried a few times to get my wallabyjs wired into my app and always fail. Please help by adding a config file for Webstorm use?

Here is a repo that has a great starter project and having the wallabyjs wired into it would be very nice.
https://github.com/marcoturi/ionic2-boilerplate 

### Wallaby.js configuration file

```javascript
// paste your config here
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
I have forked the repo and [added working wallaby config file there](https://github.com/wallabyjs/ionic2-boilerplate/commit/6ccdc7d386a4ea4a7fb45086955418f60a5f4418). 

Few notes:

- the starter project is using rollup, but I don't think there's a plugin for wallaby.js yet, so I have used [the wallaby-webpack plugin](https://github.com/jeffling/wallaby-webpack), and added the plugin and webpack to the devDependencies list;
- there's the `config/karma-shim.js` file in the project, wallaby.js needs a similar bootstrap code, but without karma specific functions, so I have added `config/wallaby-shim.ts` file. The file needs to be used as an [entry pattern](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns) because the code it contains has to be executed before tests;
- in karma config, `rollup-plugin-angular` plugin inlines angular 2 styles, I have added [wallaby.js preprocessor](https://wallabyjs.com/docs/config/preprocessors.html) for compiled `.js` files to do the same as the rollup plugin is doing. In the preprocessor I have used [the `angular2-inline-template-style` module](https://github.com/ghpabs/angular2-inline-template-style) and added it as a dev dependency to the `project.json`.

**Comment by superkew** [comment]
Thank you for the help! I'm looking forward to using this at work tomorrow. Finally getting to a tool we bought months ago :)
