### ISSUE TITLE
Wallaby with Aurelia ES6 Webpack

### ISSUE THREAD

**Issue by stevies** [wallabyjs/public#835]
### Wallaby.js configuration file
My basic attempt at a config file for aurelia with eS6 and webpack

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.config');
var wallabyPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'src/**/*.js', load: false},
    ],
    tests: [
      {pattern: 'test/unit/**/*.spec.js', load: false}
    ],
    compilers: {
      '**/*.js': wallaby.compilers.babel()
    },
    postprocessor: wallabyPostprocessor,

    bootstrap: function () {
      window.__moduleBundler.loadTests();
    }
  };
};
```

Also tried it with:
```
      {pattern: 'node_modules/babel-polyfill/browser.js', instrument: false},
      {pattern: 'src/**/*.js', load: false},
      {pattern: 'test/unit/setup.js', load: false}
```

### Code editor or IDE name and version

WebStorm v11

### OS name and version

Windows

I've had a try at getting wallaby working with the aurelia ES6 with webpack skeleton, 

https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-esnext-webpack

Get error message:

```
Failed to run compilers on src/users.js, SyntaxError: src/users.js: Decorators are not officially supported yet in 6.x pending a proposal update.
However, if you need to use them you can install the legacy decorators transform with:
npm install babel-plugin-transform-decorators-legacy --save-dev
and add the following line to your .babelrc file:
{
  "plugins": ["transform-decorators-legacy"]
}
The repo url is: https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy.
    
   6 | 
   7 | @inject(Lazy.of(HttpClient))
>  8 | export class Users {
```
 babel-plugin-transform-decorators-legacy  is installed by default in package.json.
There is no .babelrc file in the project.  Tried adding one anyway - no effect.

Is there a working wallaby config for this project setup?  Or anything else needed to get it working.

**Comment by ArtemGovorov** [comment]
Re: babel config: in the project `require('@easy-webpack/config-babel')` call in the `webpack.config.js`dynamically creates the config for babel loader. I have just taken the same settings and put them into the wallaby [babel compiler settings](https://wallabyjs.com/docs/integration/es-next.html#babel-compiler-options) in the config below. To avoid double babel run, I have removed the babel loader from the list of webpack loaders.

Re: `babel-polyfill`, you shouldn't need it, as all the required polyfills should be supplied by aurelia. If you do need it, you'll need to install it because the skeleton project doesn't have it in its `devDependencies`.

Re: `test/unit/setup.js` file, you also need to [specify the file in the `entryPatterns` list](https://wallabyjs.com/docs/integration/webpack.html#entry-patterns).

Please find the working config below.

```javascript

// Loading existing webpack config
process.env.NODE_ENV = 'test';
var webpackConfig = require('./webpack.config');

// Cleaning it
delete webpackConfig.entry;
delete webpackConfig.devServer;
delete webpackConfig.resolve.root;
delete webpackConfig.module.postLoaders;
webpackConfig.module.loaders.shift();
webpackConfig.plugins = webpackConfig.plugins.filter(p => !p.getPath);

webpackConfig.entryPatterns = ['test/unit/setup.js', 'test/**/*.spec.js'];

var wallabyWebpack = require('wallaby-webpack');
var wallabyPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function (wallaby) {
  return {
    files: [
      {pattern: 'test/unit/setup.js', load: false},
      {pattern: 'src/**/*.js', load: false}
    ],

    tests: [
      '!test/e2e/**',
      {pattern: 'test/**/*.spec.js', load: false}
    ],

    postprocessor: wallabyPostprocessor,

    compilers: {
      '**/*.js': wallaby.compilers.babel({
        presets: ['es2015', 'stage-1'],
        plugins: ['transform-decorators-legacy']
      })
    },

    setup: function () {
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

Note that when I had to remove `AureliaWebpackPlugin` from the webpack plugins list (line: `webpackConfig.plugins = webpackConfig.plugins.filter(p => !p.getPath);`) for wallaby.js because a couple of things it's doing are breaking `wallaby-webpack`. Specifically it's adding the `run` plugin for webpack, but `wallaby-webpack` doesn't do full compilation run, it uses fast incremental webpack compilation provided by the direct `compile` call. I'm not sure what exactly the plugin is doing, tests do work without it, so just note it may (or may not) cause issues when/if it is required.

**Comment by stevies** [comment]
Thanks for the super fast response.  It's working nicely.
