### ISSUE TITLE
Default argument values are always "uncovered"

### ISSUE THREAD

**Issue by smeijer** [wallabyjs/public#840]
### Issue description or question
When using es6 default argument values, wallaby always treats this line as being partially covered:

A method like:
```js
const intToHsl = (number, saturation = 100, lightness = 50) =>
  `hsl(${(number % 360)}, ${saturation}%, ${lightness}%)`;
```

Should be covered with a test like:
```js
test('it can adjust saturation and lightness', (t) => {
  t.is(intToHsl(269, 75), 'hsl(269, 75%, 50%)');
  t.is(intToHsl(151, 50, 25), 'hsl(151, 50%, 25%)');
  t.is(intToHsl(33, 25, 75), 'hsl(33, 25%, 75%)');
});
```

Instead it is showing me that `100` and `50` are uncovered.

![image](https://cloud.githubusercontent.com/assets/1196524/19529092/d47388be-962e-11e6-88e7-990a35c399b8.png)

Using: WebStorm v11 on Windows 10 x64, screenshot from wallabyjs.com/app/

**Comment by ArtemGovorov** [comment]
This test:

```javascript
test('it can adjust saturation and lightness', (t) => {
  t.is(intToHsl(269, 75), 'hsl(269, 75%, 50%)');
  t.is(intToHsl(151, 50, 25), 'hsl(151, 50%, 25%)');
  t.is(intToHsl(33, 25, 75), 'hsl(33, 25%, 75%)');
});
```

is displaying the partial coverage for me in both, WS and Wallaby App:

![ws](https://cloud.githubusercontent.com/assets/979966/19543402/7f52ea6e-96ba-11e6-9d25-8babe20d95e2.gif)

![screen shot 2016-10-20 at 11 43 23 am](https://cloud.githubusercontent.com/assets/979966/19543411/8dd129c0-96ba-11e6-8cdb-d9b05122930c.png)

And this is expected, because the code branch with the `saturation` set to its default value `100` is never exercised from the test.

This line causes the default `lightness` parameter value to be used:
```javascript
t.is(intToHsl(269, 75), 'hsl(269, 75%, 50%)');
```
and that's why it's covered.
These 2 lines are not executing any default parameter value resolution paths, because they're supplying all function values.
```javascript
t.is(intToHsl(151, 50, 25), 'hsl(151, 50%, 25%)');
t.is(intToHsl(33, 25, 75), 'hsl(33, 25%, 75%)');
```
To execute the uncovered branch, you need to add a test that would not supply a value for the parameter, thus causing the default value branch to be executed:
![ws](https://cloud.githubusercontent.com/assets/979966/19543505/46cf580c-96bb-11e6-8cc9-6cb188dd2f82.gif)

Hope it makes sense. Please let me know if it doesn't work for you as expected or if I'm missing something.
