### ISSUE TITLE
Wallaby has problems with processing src files in commonjs style wrapped in webpack

### ISSUE THREAD

**Issue by DmitryMakhnev** [wallabyjs/public#85]
I try use wallaby for my lib https://github.com/DmitryMakhnev/defaultLib.js
Wallaby processing tests files http://take.ms/5eBVm, but has problems with processing src http://take.ms/3c4HB
Maybe I made a mistake in the configuration or for correct work I must rewrite to ES7 and use the babel?
Thank you.

**Comment by ArtemGovorov** [comment]
Have sent you the [pull request](https://github.com/DmitryMakhnev/defaultLib.js/pull/1) to fix wallaby config. 

The issue was pointing modules folder to local project `src` folder. Wallaby uses its own file cache, where it stores instrumented files and runs tests using them. In your initial version, you were pointing webpack to get modules code from `bower_components` and `src` folder. While it's ok to use local `bower_components` folder, because you don't need coverage for those files, for `src` wallaby needs instrumented versions of your source code files to provide the coverage. Original files in your local `src` are not instrumented, so that's why the source files had grey indicators.

Another option is to reference `default-lib` by its relative path from your tests, like: `var defaultLib = require('../src/default-lib');`. In this case you don't even need to specify the `src` as a module directory and everything will just work. However, I guess you have not chosen this option in a first place, because it's less convenient, especially with nested test folders where you'd have to keep maintaining growing relative paths `var defaultLib = require('../../src/default-lib');`.

Please let me know if this fixes the issue.

**Comment by DmitryMakhnev** [comment]
Your pull request fixes this! Thank you so mach!
