### ISSUE TITLE
Test failures only in untouched spec.ts files using fetchmock

### ISSUE THREAD

**Issue by grantbowering** [wallabyjs/public#868]
### Issue description or question

I've whittled this down to a [sample project](https://github.com/wallabyjs/public/files/592935/untouched.fetchmock.failures.zip) on which the following behavior occurs:

1. When you first open this up in VSCode and start wallaby, the tests in regionApi.spec.ts and userApi.spec.ts will both fail as unmatched calls to fetchmock.
2. As soon as you make any change whatsoever to either of those files, the test in it will suddenly **_pass_**, even if you immediately undo any change you made (i.e., spacebar Ctrl+Z is good enough to cause the tests to pass)... but the next time you restart wallaby, they will go back to failing until you meaninglessly touch the spec file in the IDE again.
3. If you put a second copy of the projectApi.spec.ts file next to the original (i.e. projectApi2.spec.ts or something), two of the tests in it will start failing with "SyntaxError: JSON Parse error: Unexpected EOF". Again, if you touch the spec file at all in the IDE, it causes its tests to pass.
4. If you delete the projectApi.spec.ts file (and its duplicate from the previous bullet), the regionApi and userApi failures are no longer reproducible when restarting wallaby.

Since some of the test expectations appear in promise callbacks, after I zipped this up I did try changing the tests to take the done() callback and call it after their expectations in the promise callbacks (and that's probably the way the tests should be written), but this did not have any effect on the odd wallaby behavior so I didn't change it in the zip.

Tests work as expected in karma, and they do in wallaby as well but only after touching the files after wallaby has started.

### Wallaby.js configuration file

```javascript
// see attached project
```

### Code editor or IDE name and version

Both Visual Studio Code v1.7.1 and Visual Studio 2015 Update 3
Wallaby.js v1.0.321 and v1.0.323

### OS name and version

Windows 8.1 and 10

**Comment by ArtemGovorov** [comment]
Thanks for sharing the project and the detailed issue description, it's very helpful.

The issue here, like in 100% of cases where we see tests fail and then pass on a file change, is the shared state.

The `App/api/common.ts` exports an object that is used to call project/region/user APIs. The object is modified in the `App/api/projectApi.ts`:

```javascript
Object.assign(apiRequestInit,
			{
				method: 'POST',
				body: JSON.stringify({
					Outcome: outcome
				})
			}));
```

CommonJs caches once imported modules, so when you do it, the object is actually changed for the whole app/chunk. So if anything else in the app `imports` the object after the changed, the result will have the `method: 'POST', body...` properties. You may test it in your real app.

This is what happens: 
- `App/api/projectApi.spec.ts` runs and the `App/api/projectApi.ts` modifies the object,
- when `App/api/regionApi.spec.ts` and `App/api/userApi.spec.ts` run, the object contains those properties (`POST`) that are not expected by tests setup (`fetchMock.get(...)`).

This can actually be a real issue in your real app. The best way to fix it is to change the `accept` and the `rerun` methods in the `App/api/projectApi.ts` file to clone the object as opposed to be modifying it:

```javascript
Object.assign({}, apiRequestInit, // <--- using an empty object as a first arg (target)
			{
				method: 'POST',
				body: JSON.stringify({
					Outcome: outcome
				})
			}));
```

This way your tests will pass everywhere  and the state will not be corrupted in your real app.

Now a bit of a explanation of why it works in wallaby after modifying the test file and in karma:

- Wallaby only runs affected tests on code changes, so if you change a spec file, it'll only run tests from the spec file, so the `App/api/projectApi.ts` file required by the unchanged spec will not run and will not corrupt the shared object state.
- Your karma webpack configuration creates a bundle for each of your specs, where it duplicates all modules and source files, so every spec runs its own copy of the whole project. You may easily see it yourself by checking out the debug page in karma:

![k](https://cloud.githubusercontent.com/assets/979966/20332053/2da03adc-abf5-11e6-952b-82074429c1bf.gif)

Hope it makes sense.
