### ISSUE TITLE
Typescript with noEmitOnError as true

### ISSUE THREAD

**Issue by thomastnguyen91** [wallabyjs/public#871]
### Issue description or question
I am trying to have my tests error due to compilation errors so that it forces me to fix it. I used `wallaby-typescript-sample` to test it out. However, it's complaining about global functions that should had been available. Is there a way to fix this?

Examples: 
Cannot find name 'describe'.
Cannot find name 'it'.
Left-hand side of assignment expression cannot be a constant or a read-only property.
Cannot find name 'console'.
Type 'number' is not assignable to type 'string'.
Cannot find name 'expect'.

### Wallaby.js configuration file

```javascript
// test file
/// <reference path="../typings/jasmine/jasmine.d.ts" />

describe('Sayings Greeter', () => {
    it('should greet', () => {
        const a = 1;
        a = 2;

        console.log(a);

        var s:string = 1;

        var greeter = new Sayings.Greeter('John');
        expect(greeter.greet()).toBe('Hello, John');
    });
});
```

```javascript
// configuration
module.exports = function (wallaby) {
  return {
    files: [
      'src/*Browser.ts'
    ],

    tests: [
      'test/*BrowserSpec.ts'
    ],
    compilers: {
      "*.ts": wallaby.compilers.typeScript({
        noEmitOnError: true
      })
    }
  };
};
```

### Code editor or IDE name and version
WebStorm v2016.3

### OS name and version
Windows

**Comment by ArtemGovorov** [comment]
I wouldn't recommend setting `noEmitOnError: true` for wallaby.js, because WebStorm have its own  built-in TypeScript compiler that can display compilation errors for you nicely by highlighting errors right in the source code. 

If you set it to `noEmitOnError: true`, wallaby.js will also report compilation errors. but there's no need to do the job twice and its best to let each tool do its job: wallaby to run your tests and your IDE to display type errors:

<img width="827" alt="screen shot 2016-11-17 at 12 03 41 pm" src="https://cloud.githubusercontent.com/assets/979966/20373485/ee81854e-acbd-11e6-962d-13d5a301ec3b.png">


Having said that, if you'd like wallaby to stop running tests on type errors, you may do it. You'll need to let it know about definitions files `*.d.ts`. For [this sample](https://github.com/wallabyjs/wallaby-typescript-sample) you've mentioned, you'll need to get the latest version of the sample and run `npm install` (I added this to the sample, but before wallaby was using its embedded TS version)
and add definition files to the `files` list:
```javascript
module.exports = function (wallaby) {

  return {
    files: [
      'src/*Browser.ts',
      'typings/**/*.d.ts', // <--
      'node_modules/typescript/lib/lib.es5.d.ts' // <--
    ],

    tests: [
      'test/*BrowserSpec.ts'
    ],

    compilers: {
      "*.ts": wallaby.compilers.typeScript({
        noEmitOnError: true
      })
    }
  };
};
```
