### ISSUE TITLE
Wallaby config for ionic2 projects

### ISSUE THREAD

**Issue by zpydee** [wallabyjs/public#878]
Do you have any example wallaby setups for ionic 2 projects?

**Comment by ArtemGovorov** [comment]
Yes, I have created one few weeks ago, you may try it: https://github.com/wallabyjs/public/issues/834#issuecomment-254398261

**Comment by zpydee** [comment]
thanks as always. will give that a try... :-)

**Comment by wilgert** [comment]
The app that gets generated by Ionic CLI is a lot different from the example provided. I was not able to get it to work. @ArtemGovorov Can you provide a step by step guide to get it working with Ionic 2?

**Comment by ArtemGovorov** [comment]
@wilgert I have managed to make the example config work with a few changes. I have forked the testing repo mentioned in the Ionic forum thread that you've linked, and [here's the commit with the working wallaby config](https://github.com/ArtemGovorov/ionic-unit-testing-example/commit/2eba776374578ba3973b4817f5f62172a758ba70):

- there's the [`test-config/karma-test-shim.js`](https://github.com/ArtemGovorov/ionic-unit-testing-example/blob/master/test-config/karma-test-shim.js) file in the project, wallaby.js needs a similar bootstrap code, but without karma specific hacks, so I have added the [`test-config/wallaby-test.js` file](https://github.com/ArtemGovorov/ionic-unit-testing-example/blob/master/test-config/wallaby-test.js). The file needs to be used as an entry pattern because the code it contains has to be executed before tests;
- [webpack loaders](https://github.com/ArtemGovorov/ionic-unit-testing-example/blob/master/wallaby.js#L9) are mostly taken from the webpack.test file, except `ts-loader`, [wallaby doesn't need it](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript).
- karma config in this project is using Chrome to run tests, so I [configured wallaby](https://github.com/ArtemGovorov/ionic-unit-testing-example/blob/master/wallaby.js#L35) to use [Chrome/Electron runner](https://wallabyjs.com/docs/integration/electron.html) as well.
- For some reason, the sample project tests throw a global uncaught error. It's not reported by karma, but was reported by wallaby. It is actually displayed in karma debug mode (but is not reported to the karma console):

![screen shot 2017-03-29 at 12 51 43 am](https://cloud.githubusercontent.com/assets/979966/24412506/fcf5084c-141b-11e7-9a00-10a1b2f92536.png)

It looks like some Ionic component specific error. Anyway, to suppress reporting it in wallaby, I have added this [few lines to the setup function](https://github.com/ArtemGovorov/ionic-unit-testing-example/blob/master/wallaby.js#L44). You may want to check it and perhaps report to the Ionic project, I just suppressed it to make the tests pass like they appear to be passing in karma (but the error is still there in both runners).
