### ISSUE TITLE
Errors subclasses instances are replaced by base Error

### ISSUE THREAD

**Issue by ntrrgc** [wallabyjs/public#889]
### Issue description or question
I run a series of test I wrote a long time ago and suddenly two of them were failing... After running several experiments I found Wallaby is changing the semantics of this:

```
class MyError extends Error {
    myMethod() {
        return "meow";
    }
}

console.log(new MyError() instanceof MyError);
console.log(new MyError().myMethod);
```

Running the previous code in a browser returns this, as expected:

```
true
function myMethod() {
        return "meow";
    }
```

But running it in Wallaby returns something not expected at all:

```
false
undefined
```

### Wallaby.js configuration file

```javascript
module.exports = (w) => {
    return {
        files: [
            "src/**/*.ts"
        ],
        tests: [
            "spec/**.spec.ts"
        ],
        compilers: {
            "**/*.ts": w.compilers.typeScript({module: "commonjs"}),
        },
        debug: true,
        env: {
            type: "node"
        },
        testFramework: "mocha",
        setup: function (wallaby) {
            require("bluebird").config({
                longStackTraces: true
            })
        }
    }
}
```

### Code editor or IDE name and version

PHPStorm 2016.3

### OS name and version

Arch Linux

**Comment by ArtemGovorov** [comment]
Interesting one.

This issue is not wallaby.js specific, but TypeScript compiler version specific (same happens with Babel BTW). You may try compiling the code with `./node_modules/.bin/tsc`, running it in node and you'll get the same result. 

Have a look into:
https://github.com/Microsoft/TypeScript/issues/12123
https://github.com/Microsoft/TypeScript/issues/12058
https://github.com/Microsoft/TypeScript/issues/12145
https://github.com/Microsoft/TypeScript/issues/12581
https://github.com/Microsoft/TypeScript/issues/10166
https://github.com/Microsoft/TypeScript/issues/12279
