### ISSUE TITLE
Wallaby, webpack, typescript issue with multiple entry points

### ISSUE THREAD

**Issue by risonipli** [wallabyjs/public#890]
### Issue description or question
Hi guys, could you please help with wallaby configuration. Currently, our project integrating webpack as a bundler tool. 

We have a repository with a bunch of npm packages which we publish to our internal npm registry. 
### Repository structure
```
├── Gruntfile.js
├── karma.conf.js
├── package.json
├── packages
│   ├── another_package
│   ├── group_of_packages
│   │   ├── package1
│   │   └── package2
│   └── utils
│       ├── package.json
│       ├── src
│       │   ├── subdirs
│       │   ├── index.ts
│       │   └── test.ts
│       └── tests
│           └── unit
│               └── subdirs
├── packages.karma.conf.js
├── packages.test.ts
├── tsconfig.json
├── wallaby.js
└── webpack.conf.js
```
### Main entry point
Each package which lives in 'packages' has two webpack entry points: main entry point 'src/index.ts' e.g.:
```typescript
import * as angular from 'angular';
import 'angular-translate';

import { EarlyExitDecoratorConfig } from './decorators/EarlyExitDecoratorConfig.ts';
let uuid = require('./factories/UUID.js');

angular.module('u-workflow.utils', ['pascalprecht.translate'])
    .config(EarlyExitDecoratorConfig)
    .factory('UUID', uuid.UUIDService);
```

### Test entry point
And test entry point 'src/test.ts':
```typescript
import 'string.prototype.startswith';
import './index.ts';
import 'angular-mocks';

requireAll((<any>require).context('../tests/', true, /spec.js$/));
requireAll((<any>require).context('../tests/', true, /spec.ts$/));
function requireAll(r: any): any {
    r.keys().forEach(r);
}
```

We need this structure in order to be able to test each package individually by running 'npm test' at the root of the package & test all packages from the root of the repository.

### Global test entry point
For testing all packages we also have third entry point 'packages.test.ts' which simply require all 'test.ts' files:
```typescript
requireAll((<any>require).context('./packages', true, /test.ts$/));
function requireAll(r: any): any {
    r.keys().forEach(r);
}
```
node_modules live at the root of repository.

### Karma configuration file
```javascript
var webpackConf = require('./webpack.conf.js');

module.exports = function karmaConfig(config) {
    var conf = {
        frameworks: [
            'jasmine'
        ],

        reporters: [
            'progress'
        ],

        files: [
            'packages.test.ts'
        ],

        preprocessors: {
            'packages.test.ts': ['webpack']
        },

        browsers: [
            'Chrome'
        ],

        singleRun: true,
        webpack: webpackConf,

        webpackMiddleware: {
            noInfo: 'errors-only'
        }
    };

    config.set(conf);
};
```

### Webpack configuration file
```javascript
module.exports = {
    module: {
        resolve: {
            root: __dirname,
            extensions: ['', '.js', '.ts']
        },
        resolveLoader: {
            modulesDirectories: ['node_modules']
        },
        loaders: [
            { test: /\.ts$/, loader: 'ts' },
            { test: /\.html$/, loader: 'raw' },
            { test: /\.css$/, loader: 'ignore' }
        ]
    }
};
```

Running karma with karma-webpack works just fine. But I kind of stuck trying to write proper wallaby config

### Wallaby.js configuration file

```javascript
var wallabyWebpack = require('wallaby-webpack');
var webpackConfig = require('./webpack.conf.js');
webpackConfig.entryPatterns = ['packages.test.js'];

var webpackPostprocessor = wallabyWebpack(webpackConfig);

module.exports = function () {
    return {
        files: [
            {pattern: 'packages/**/src/**/*.html', load: false},
            {pattern: 'packages/**/src/**/*.css', load: false},
            {pattern: 'packages/**/src/**/*.js', load: false},
            {pattern: 'packages/**/src/**/*.ts', load: false},
            {pattern: 'packages.test.ts', load: false}
        ],

        tests: [
            {pattern: 'packages/**/tests/unit/**/*.spec.ts', load: false},
            {pattern: 'packages/**/tests/unit/**/*.spec.js', load: false}
        ],

        testFramework: 'jasmine',
        postprocessor: webpackPostprocessor,
        bootstrap: function () {
            window.__moduleBundler.loadTests();
        }
    };
};
```

Here is wallaby output:
```
​​​​​[Info]​​​​​ Started Wallaby.js Core v1.0.328
​​​​​[Info]​​​​​ Wallaby App available at: http://wallabyjs.com/app/#/files
​​​​​[Info]​​​​​ ts-loader: Using typescript@2.0.10
​​[Error] Runtime error: Error: Cannot find module '12'​​
​​[Error] Runtime error: Error: Cannot find module '12'​​
​​[Error] Runtime error: Error: Cannot find module '12'​​
​​[Error] at http://localhost:51791/wallaby-webpack.js?1480680703041:1​​
​​[Error] Runtime error: Error: Cannot find module '12'​​
​​[Error] at http://localhost:51791/wallaby-webpack.js?1480680703041:1​​
​​​​​[Info]​​​​​ Finished executing 4 affected test(s) 
```
If I disable 'ts-loader' I get:
```
​​​​​0 failing tests, 0 passing​​​​​
```

Here is example git repository: https://github.com/risonipli/wallaby-webpack-typescript-issue

### Code editor or IDE name and version

Visual Studio Code v1.7.2
Sublime Text v3 build 3126

### OS name and version

OSX 10.12.1

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo!

It's a tricky setup that is very karma-webpack oriented, because it's trying to load all tests in test entry points `src/test.ts`. ie. this is a karma-webpack specific code:
```javascript
requireAll((<any>require).context('../tests/', true, /spec.js$/));
requireAll((<any>require).context('../tests/', true, /spec.ts$/));
function requireAll(r: any): any {
    r.keys().forEach(r);
}
```
that wallaby doesn't really need. 

We normally recommend some refactoring so that the code doesn't get loaded by wallaby, like [separating the code](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/karma-require.js), [only referencing it is karma is running](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/config/spec-bundle.js#L41), and [ignoring it for wallaby](https://github.com/wallabyjs/angular2-webpack-starter/blob/master/wallaby.js#L14).

In your case however it *may* work as is, as wallaby seems to ignore the `requireAll` calls.

All you need to do is to make your `packages/**/test.js` to be entry points in addition to the rest of your tests, and it should hopefully work. There're few other minor changes required: 
- importing files without `.ts` extensions (that is a recommended way and should not break anything anyway),
- removing `.ts` extension from the webpack extensions list [as described in the docs](https://wallabyjs.com/docs/integration/webpack.html#typescript-and-coffeescript),
- mapping the webpack resolve root to the wallaby cache, [as described in the docs](https://wallabyjs.com/docs/integration/webpack.html#absolute-paths-for-wallaby-cache-folder).

I have created the [PR with the above mentioned changes](https://github.com/risonipli/wallaby-webpack-typescript-issue/pull/1) to make your sample work.

**Comment by risonipli** [comment]
Thanks a lot for super fast response. Works great!
