### ISSUE TITLE
VS Code output, can it be as nice as Atoms?

### ISSUE THREAD

**Issue by tomitrescak** [wallabyjs/public#898]
Hi, I really like the output of tests in Atom (the only reason why I switch back to it at times).
The VS Code's output seems to be much more limited. Would it be possible to bring these nice colours  to VS Code?

Compare these two outputs (In Atom I immediately see my error, while in Code the missing line is not even displayed):

<img width="992" alt="screen shot 2016-12-09 at 11 37 34 am" src="https://cloud.githubusercontent.com/assets/2682705/21033431/3d6daa00-be04-11e6-88b7-0d95340c59eb.png">

<img width="692" alt="screen shot 2016-12-09 at 11 37 18 am" src="https://cloud.githubusercontent.com/assets/2682705/21033434/41a65d4c-be04-11e6-85ec-9c7bdd9806e9.png">

Is this maybe problem of my theming somehow?

**Comment by ArtemGovorov** [comment]
Hi, looks like a bug. Are you comparing strings in the expect assertion?

**Comment by ArtemGovorov** [comment]
The issue (with not displaying the last line as deleted) is fixed in the wallaby for VS Code 1.0.33. Colours however may depend on your theme, here's how it looks like in the default dark theme:

<img width="969" alt="screen shot 2016-12-09 at 1 30 51 pm" src="https://cloud.githubusercontent.com/assets/979966/21036728/cdf50528-be13-11e6-93b9-6e5a843c4401.png">

Wallaby is using `token.error-token` for deletions and `constant.numeric.js` for insertions (can't use custom colours like in Atom), and these may be overridden in your theme.
