### ISSUE TITLE
Typescript compiler option outDir is not respected

### ISSUE THREAD

**Issue by KnisterPeter** [wallabyjs/public#911]
### Support tsc outDir flag

Currently wallaby does not respect the outDir set in tsconfig.
This is problematic if files need to find each other from process.cwd (in case of ava as test runner this is the project root).

For example if the outDir is set to 'dist' then every js file would be stored by tsc into the dist folder.
To locate that file by an absolute path would be possible outside of wallaby since it is kind of static, but within wallaby currently the js files are compiled right next to the ts files.
An encoded 'dist' in a path would then failed to be found.

**Comment by ArtemGovorov** [comment]
The `outDir` is not supported by design.

> This is problematic if files need to find each other from process.cwd (in case of ava as test runner this is the project root).

I don't think I understand the scenario. The `outDir` shouldn't affect the way files are imported/required/found by TypeScript compiler.

Could you please share an example repo to demonstrate the issue?

**Comment by KnisterPeter** [comment]
The problem you can see here in the [these cases](https://github.com/paeckchen/paeckchen-cli/blob/master/test/index-test.ts).
The tests are trying to figure out which is the cli entry point and run that to verify output expectations.
But if the compiled files are not in the dist folder (as configured and anticipated) the test will all fail.

**Comment by ArtemGovorov** [comment]
Thanks for sharing the repo. I had a look and scenario like this wouldn't work with the current wallaby config even if the `outDir` was respected, because wallaby doesn't support cross-process instrumentation reporting (and your [`index-test.ts`](https://github.com/paeckchen/paeckchen-cli/blob/master/test/index-test.ts) spawns processes that execute instrumented files).

The easiest way for you to make it work is to point `process.cwd` to your local project folder (where you have the `dist` folder):

```javascript
module.exports = function (w) {
  return {
    ...
    setup: (w) => {
      process.cwd = function () {
        return require('path').resolve(w.localProjectDir);
      }
    }
  };
};
```

**Comment by KnisterPeter** [comment]
Thanks
