### ISSUE TITLE
Problem with async tests?

### ISSUE THREAD

**Issue by mvestergaard** [wallabyjs/public#92]
Sync:
![](http://i.imgur.com/WnO8DoX.png)

Async (test is still failing):
![](http://i.imgur.com/RS2BuW6.png)

**Comment by ArtemGovorov** [comment]
Can't reproduce it, here is what I do:

![async](https://cloud.githubusercontent.com/assets/979966/7382926/c0186ff2-ee59-11e4-9c67-75d0c5241d80.gif)

Is there a small sample (perhaps a repo) that you could share where the issue is reproducible?

Another thing, in your sync test, what error does it report in the "Failing Tests" tab? It normally highlights the error line with red indicator, in your case they are all pink. Is the error line number it reports in the "Failing Tests" tab correct?

**Comment by mvestergaard** [comment]
I'll try to repro in a more isolated scenario tonight. I'll get back to you.
It seems I started having issues after i upgraded my dependencies, so it may be dependency version related.

**Comment by mvestergaard** [comment]
Sorry I didn't have time to look into this before now.

First to answer your question about the error indicator, this is the output from failing tests tab:

Sync:
![](http://i.imgur.com/logWONU.png)

Async:
![](http://i.imgur.com/P6k2AJS.png)

I'll spend some time now trying to replicate in an isolated test.

**Comment by mvestergaard** [comment]
Hi Artem,

It seems reproducable, see this repo: https://github.com/mvestergaard/wallaby_example

**Comment by mvestergaard** [comment]
The really odd thing is, removing the call to done() in the test does not make the test time out... ?

**Comment by mvestergaard** [comment]
I think I sort of figured out what's causing it.

The problem seems to be that the AssertionError is uncaught, so changing the process.nextTick block to:
```javascript
process.nextTick(function() {
      try{
        expect(errHandler).to.have.been.calledOnce;
      } catch(e) {
        done(e);
      }
    });
```

Seems to make it behave nicer. It's still a bit iffy though. I hope you'll take a look.

**Comment by ArtemGovorov** [comment]
Hi Mathias, 

Thanks a lot for your help and provided repository, it was very helpful to reproduce and fix the issue. So I have fixed the issue, it should now work fine and also report the error correctly (on the line where it happens).

Please let me know if it now works for you.
