### ISSUE TITLE
Wallaby reports a long running test possibly incorrectly?

### ISSUE THREAD

**Issue by IPWright** [wallabyjs/public#929]
### Issue description or question

Wallaby reports a long running test possibly incorrectly?

```
[Error]: Some long running code has been detected: test "undefined" is taking more than 5000ms to execute.​​
​​[Error]: Try commenting out the test or excluding the test file from the `tests` list in your wallaby config,​​
​​[Error]: and restarting wallaby to make sure that it is this test/file causing the issue and not something else.​​
​​[Error]: Also review your recent changes to the code that the test covers, as well as its `before` and `after` hooks.​​
​​[Error]: Pinging test runner sandbox...​​
​​[Error]: The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​
```

My specific test is this:

```
it("should return current locating for floating legend", () => {
                expect(LegendPositioner.getLocationFromDocking(LEGEND_DOCKING.FLOATING, LEGEND_LOCATION.TOPLEFT)).toBe(LEGEND_LOCATION.TOPLEFT);
});
```

This was exercising some code, which I think we can boil down to the following, the key thing to note is that `location` is undefined as I'd missed refactoring the name of it.

```
static getLocationFromDocking(docking, currentLocation) {

     // If floating just use the existing position
    if (docking === LEGEND_DOCKING.FLOATING) return location;
}
```

### Wallaby.js configuration file

```
module.exports = function (wallaby) {
    process.env.NODE_ENV = 'wallaby'; 
    return {
        files: [
            { pattern: "./tests/**/*.snap", load: false, instrument: false },
            { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
            { pattern: 'src/**/*.css', load: false },
            { pattern: 'src/**/*.js', load: false },
            { pattern: 'tests/utils/*.js', load: false }
        ],
        tests: [
            // Exclude specific tests, that won't run in Jest (since they require a browserr object)
            { pattern: './tests/d3/utils/spark-points.test.js', ignore: true },
            { pattern: './tests/d3/utils/tooltips.test.js', ignore: true },
            // Load all other tests
            { pattern: './tests/**/*.test.js' }
        ],
        filesWithNoCoverageCalculated: ['src/**/index.js', 'tests/**/*.js'],
        hints: {
            ignoreCoverage: /ignore coverage/
        },
        env: {
            type: "node",
            runner: "node",
        },
        testFramework: 'jest',
        compilers: {
            '**/*.js': wallaby.compilers.babel({ babel: require('babel-core') })
        },
    };
};
```

### Code editor or IDE name and version

Sublime Text v3

### OS name and version

Windows

**Comment by ArtemGovorov** [comment]
> The sandbox is not responsive. Check for possibly recently introduced infinite loops.​​

This usually happens when some code change (not necessarily the final state of the code) had cause the test worker to hang. Further changes to the code (unless they're breaking as well) should restart the worker and get rid of the issue. Perhaps the refactoring you've mentioned had created such code state?

> This was exercising some code, which I think we can boil down to the following, the key thing to note is that location is undefined as I'd missed refactoring the name of it.

If you restart wallaby, does the error persist? I mean the 'location is undefined' should still be reported, but definitely not as the `Some long running code has been detected` error. 

I've tried creating a simple project, but all I'm getting if the location is not defined is the `ReferenceError: location is not defined`. So I'm suspecting the might have been something else in the mentioned refactoring that caused the error message.

**Comment by IPWright** [comment]
@ArtemGovorov I've managed to get a reproduction with a reasonably small set of files. I'll email over a zip of these to your email address.

**Comment by ArtemGovorov** [comment]
Thanks for the repo.

It looks like the issue is not wallaby.js specific, because running `jest` from CLI also hangs, that you can easily test by running `jest` directly without wallaby. Seems like `jest` is hanging when doing the diff of objects. I managed to reproduce it on this one line test without any dependencies:
```javascript
it('fails', () => {
  expect(location).toBe(1);
});
```

I've also found the existing bug in jest repo and [reported the test case](https://github.com/facebook/jest/issues/1772#issuecomment-270903970) (a bit different test case for jest 18).

**Comment by IPWright** [comment]
@ArtemGovorov thanks - I've got a subscription onto the Jest issue so I'll keep an eye over there. Explains the message in Wallaby at least :)
