### ISSUE TITLE
Imports from node_modules not processed by babelify (Wallabify + Vueify + Babelify)

### ISSUE THREAD

**Issue by fvanwijk** [wallabyjs/public#930]
### Issue description or question
> Postprocessor run failure: 'import' and 'export' may appear only with 'sourceType: module'

We get this error because there is an `import` in `vue-multiselect/lib/multiselectMixin.js`. The files in node_modules are somehow not transpiled by babelify.

Setting `global: true` to apply transforms to the non-local files plus an `ignore: "/node_modules/(?!vue-multiselect).*/"` gives aditional weird errors. This might not be the way to go, since it is working in Karma without these settings. We do not even define any additional transforms in the local Karma config.

We need the browserify config in package.json to overrule the package.json config in `vue-multiselect`.

Everything was ok before we started using Vueify. `multiselectMixin.js` is now imported from a `.vue` file. Previously it was imported from a `.js` file. Since vueify automatically passes its JS stuff to browserify, it may be something with the vueify transform...
Still I don't understand why it is working in Karma in the new situation.

### Configuration files

```javascript
// wallaby.conf.js
const chai = require('chai');
const vueify = require('vueify');
const wallabify = require('wallabify');
const babelify = require('babelify');

module.exports = function (wallaby) {
  return {
    debug: true, // Gives no debug information for wallabify
    files: [
      { pattern: 'node_modules/babel-polyfill/dist/polyfill.js', instrument: false },
      { pattern: 'node_modules/chai/chai.js', instrument: false },
      { pattern: 'node_modules/chai-dom/chai-dom.js', instrument: false },
      { pattern: 'node_modules/chai-as-promised/lib/chai-as-promised.js', instrument: false },
      { pattern: 'node_modules/sinon-chai/lib/sinon-chai.js', instrument: false },
      { pattern: 'node_modules/vue-multiselect/lib/*.js', instrument: false, load: false },
      { pattern: 'src/*.js', load: false },
      { pattern: 'src/!(docs|semantic-ui)/**/!(*.spec).+(js|vue)', load: false },
      { pattern: 'mock/**/*.json', load: false }
    ],
    tests: [
      { pattern: 'src/**/*.spec.js', load: false }
    ],
    compilers: {
      'src/**/*.js': wallaby.compilers.babel()
    },
    postprocessor: wallabify({
      entryPatterns: [
        'src/test/bootstrap.js',
        'src/**/*.spec.js'
      ],
      debug: true,
      extensions: ['.js', '.vue']
    }),
    testFramework: 'mocha',
    setup() {
      chai.should();
      /* eslint no-underscore-dangle:0 */
      window.__moduleBundler.loadTests();
    }
  };
};

// package.json
  "browserify": {
    "transform": ["babelify", "vueify"]
  },
```

### Code editor or IDE name and version
IntelliJ IDEA v16

**Comment by ArtemGovorov** [comment]
It should work for you if you remove this line from your `files`:
```javascript
{ pattern: 'node_modules/vue-multiselect/lib/*.js', instrument: false, load: false },
```
With this line, wallaby.js copies the files to its local cache, and because the `instrument` is set to `false`, wallaby doesn't instrument/compile them. Later on, browserify finds the files and because there's no package.json copied over to the cache (the pattern only included `*.js` files from the `lib` folder: `node_modules/vue-multiselect/lib/*.js`), browserify doesn't transform the package source code.

> We need the browserify config in `package.json` to overrule the `package.json` config in vue-multiselect.

I'm even not sure browserify actually supports it. It sounds like you're not doing anything special in karma config, which means that the `package.json` config in vue-multiselect is used for the package by browserify when you run it from karma.

If it doesn't help (I tried on simple local project and it did help), please create and share a sample project that includes working karma setup as well.

**Comment by fvanwijk** [comment]
Hi Artem, thanks for the reply.

Removing that line, gives the error:
> Postprocessor run failure: Cannot find module '../../../../node_modules/vue-multiselect/lib/multiselectMixin' from './src/common/components/forms'

I recreated the issue in a [sample repo](https://github.com/fvanwijk/vue-multiselect-browserify-example/tree/wallaby).

Note that the master/js-only branches refer to a related issue: monterail/vue-multiselect#140

---
Here are some docs about browserify config in package.json, which will override local config:
- https://github.com/substack/browserify-handbook#configuring-transforms
- https://github.com/substack/node-browserify#browserifytransform
- https://github.com/substack/node-browserify#btransformtr-opts - About global transforms. I used them in the `master`/`js-only` but they seem not to be required in my project, since everything is working well in Karma, which doesn't use global transforms
-

**Comment by ArtemGovorov** [comment]
> Postprocessor run failure: Cannot find module '../../../../node_modules/vue-multiselect/lib/multiselectMixin' from './src/common/components/forms'

It is because the `src/Multiselect.vue` file is referencing the `vue-multiselect` module files via a relative path, not like a module files. If you change it to 
```javascript
  import multiselectMixin from 'vue-multiselect/lib/multiselectMixin.js'
  import pointerMixin from 'vue-multiselect/lib/pointerMixin.js'
```
then it'll work without this line: `{ pattern: 'node_modules/vue-multiselect/lib/*.js', instrument: false, load: false },`.

Alternatively, if you do need to reference those files like you're referencing them now with the relative paths, you may leave the line and add a preprocessor that will compile the node module files:
```javascript
module.exports = function (wallaby) {
  return {
    ...
    preprocessors: {
      'node_modules/vue-multiselect/**/!(*.min)*.js': file => require('babel-core')
        .transform(file.content, {presets: ['es2015']})
    },
    ...
  };
};
```
It'll be doing the same job as the compiler, except the compiler is not configured only for `src/*` files and wouldn't apply because of the `instrument: false` flag. Preprocessor on the other had doesn't care about the `instrument` flag.

**Comment by fvanwijk** [comment]
I just got it to work in 3 ways. Third alternative is to add the pattern to the `compilers` object instead of a preprocessor.

Many thanks. Couldn't come up with this myself :)

**Comment by ArtemGovorov** [comment]
Awesome, thanks for the update!
