### ISSUE TITLE
JEST and typescript

### ISSUE THREAD

**Issue by asvetliakov** [wallabyjs/public#938]
### Issue description or question
I'm having hard time of trying to configure wallaby with jest and typescript. I'm using jest with ts-jest preprocessor without ts pre-compilation step and do a lot of snapshot testing

Problems:
1) I'm getting empty coverage for source files
2) Since wallaby does preprocessing source files by self and feeds jest with them, the resulting snapshot files names are incorrect, i.e. runner creates ```snapshot.js.snap``` instead of taking ```snapshot.tsx.snap```

I'd be very happy if there is a way to feed jest with original ts files instead of wallaby preprocessed ones, but keep wallaby instrumentation for auto-testing and coverage in editor.

### Wallaby.js configuration file

```javascript
// paste your config here
module.exports = function (wallaby) {
    return {
        files: [
            "src/**/*.ts?(x)",
            "!src/**/*_Spec.ts?(x)",
            "src/**/*.snap",
            "package.json",
            "test-tsconfig.json",
            "helpers/**.js",
            { pattern: 'src/**/*.css', load: false, instrument: false },
            { pattern: 'src/**/*.png', load: false, instrument: false },
            { pattern: 'src/**/*.jpg', load: false, instrument: false },
            { pattern: 'src/**/*.mp3', load: false, instrument: false },
            { pattern: 'src/**/*.ogg', load: false, instrument: false }
        ],
        tests: [
            "src/**/*_Spec.ts?(x)"
        ],
        env: {
            type: "node",
            runner: "node"
        },
        compilers: {
            "**/*.ts?(x)": wallaby.compilers.typeScript({ module: 'commonjs' })
        },
        testFramework: "jest",
        setup: function () {
            const jestConfig = require("./package.json").jest;
            wallaby.testFramework.configure(jestConfig);
        }
    };
};
```

jest config
```js
    "globals": {
      "__TS_CONFIG__": "test-tsconfig.json",
      "window": true,
      "document": true
    },
    "resetMocks": true,
    "transform": {
      "\\.(ts|tsx)": "<rootDir>/node_modules/ts-jest/preprocessor.js",
      "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga|ogg)$": "<rootDir>/helpers/assetsfileTransformer.js"
    },
    "moduleNameMapper": {
      "\\.(css|less)$": "<rootDir>/helpers/styleMock.js"
    },
    "testRegex": "(/__tests__/.*|.*_[Ss]pec)\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx"
    ],
    "snapshotSerializers": [
      "<rootDir>/node_modules/jest-serializer-enzyme"
    ],
    "setupTestFrameworkScriptFile": "<rootDir>/helpers/setup.js",
    "testResultsProcessor": "<rootDir>/node_modules/jest-junit",
    "collectCoverageFrom": [
      "src/**/*.{ts,tsx}",
      "!src/**/*.d.ts",
      "!src/main.tsx",
      "!**/DevTools.tsx",
      "!**/configureStore.ts"
    ],
    "coverageReporters": [
      "json",
      "lcov",
      "text",
      "cobertura"
    ]
  
```

### Code editor or IDE name and version

Visual Studio Code v1.8.1

### OS name and version

Windows 10

**Comment by ArtemGovorov** [comment]
Could you please create small repo with your config files and a couple of dummy test/source files to demonstrate both issues?

**Comment by asvetliakov** [comment]
Here:
https://github.com/asvetliakov/wallaby-938

Steps:
1) Run wallaby and see if you can get coverage indicators in file.ts and component.tsx
2) Change any param for TestComponent in component_Spec.tsx. The test fails and it's ok. Then try to execute ```jest -u``` in terminal. The test still fails.

**Comment by asvetliakov** [comment]
Here is what i mean with two snapshot files:
![capture](https://cloud.githubusercontent.com/assets/8881674/21755909/7cd603f8-d61a-11e6-9895-54a13c4dd037.PNG)

**Comment by ArtemGovorov** [comment]
Thanks for the repo. I have sent you [the PR](https://github.com/asvetliakov/wallaby-938/pull/1). Both of the issues are related to the fact that wallaby renames compiled `.ts` files to `.js`. 

The issue with no coverage was happening because of the `.ts`/`.tsx` presence in the `moduleFileExtensions` (wallaby picks up raw non-instrumented .ts files from its cache - hence the issue). Deleting the `moduleFileExtensions` in wallaby config, OR moving `"js","jsx"` up in the array in your `package.json` should does the trick.

The issue with the snapshot name originates from the same fact of renaming files. `Jest` in its turn creates the `snapshot.js.snap` because of the spec name. The solution is pretty simple - a renamer ([wallaby preprocessor](https://wallabyjs.com/docs/config/preprocessors.html)) for `.snap` files to make them what jest produces from the start.

I tried the solution and both issues seem to go away. Please try it to see how it goes for you. Pretty sure you already know that, but don't forget to save a spec before running `jest -u` to update snapshots (I was caught thinking it's not working, but forgot that need to save the spec file as jest unlike wallaby doesn't work on unsaved files).

**Comment by asvetliakov** [comment]
Oh yes, i forgot that i can use preprocessors to rename snapshots (latest 20 minutes i have been trying to monkey patching writeFileSync 🐒 ) . Both issues was resolved for me, thank you, you rock 🚀 

>but don't forget to save a spec before running jest -u to update snapshots (I was caught thinking it's not working, but forgot that need to save the spec file as jest unlike wallaby doesn't work on unsaved files).
I have extension which does auto-saving and spins jest command (with snapshot update) for current test

**Comment by bsommardahl** [comment]
Too bad the PR and repo listed above were deleted. It would have helped me with my current issue with jest and ts.

**Comment by bsommardahl** [comment]
@ArtemGovorov If there's any way you can take a look at my wallaby config, I would really appreciate it. https://github.com/AcklenAvenue/mototaxi

I am also using Jest and Typescript, but my set up is MUCH simpler with less twists and turns. Here's the error I'm getting:

```
TypeError: Cannot convert undefined or null to object​​
​​    at setFromArgv (/home/byron/Projects/mototaxi/node_modules/jest-config/build/setFromArgv.js:18:32)​​
​​    at Object.normalize [as normalizeConfig] (/home/byron/Projects/mototaxi/node_modules/jest-config/build/normalize.js:280:44)​​
​​    at emitTwo (events.js:106:13)​​
​​    at WebSocket.emit (events.js:191:7)​​
​​    at afterWrite (_stream_writable.js:388:3)​​
​​    at onwrite (_stream_writable.js:379:7)​​
​​    at WritableState.onwrite (_stream_writable.js:90:5)​​
​​    at afterTransform (_stream_transform.js:79:3)​​
​​    at TransformState.afterTransform (_stream_transform.js:54:12)​​
​​    at Zlib.callback (zlib.js:639:5)​​
```

**Comment by ArtemGovorov** [comment]
@bsommardahl What is your version of wallaby.js core (printed in the Wallaby Console)? I can't reproduce the issue with [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). From the stack trace I can see that most likely you are using not the latest core version, because the issue (Jest 20 support) was resolved a few days ago.
