### ISSUE TITLE
Angular 1.5 - typescript - webpack - wallaby

### ISSUE THREAD

**Issue by dnatag** [wallabyjs/public#952]
### Issue description or question
I cannot make wallaby work with this combination. The code skeleton was generated with FountainJs with Webpack and Typescript. 

The only modification I did was to add wallaby-webpack and wallaby-ng-html2js-preprocessor packgages. Unfortunately, the code was working fine with Karma, but I could not get it work with Wallaby. I think the issue is related to template html module, although the ng-html2js preprocessor appears to be working fine. 

### Github repo link
https://github.com/dnatag/wallaby-ng1-typescript-webpack.git
```javascript
const wallabyWebpack = require('wallaby-webpack');
const angularTemplatePreprocessor = require('wallaby-ng-html2js-preprocessor');
const wallabyPostprocessor = wallabyWebpack({});

module.exports = function (wallaby) {
  return {
    files: [
      {
        pattern: 'src/**/*.html',
        load: false
      },
      {
        pattern: 'src/**/*.css',
        load: false
      },
      {
        pattern: 'src/**/*.ts',
        load: false
      },
      {
        pattern: 'src/**/*.spec.ts',
        ignore: true
      }
    ],

    tests: [{
      pattern: 'src/**/*.spec.ts',
      load: false
    }],

    testFramework: 'jasmine',

    preprocessors: {
      'src/**/*.html': function (file) {
        return angularTemplatePreprocessor.transform(file, {stripPrefix:'src/'})
      }
    },

    postprocessor: wallabyPostprocessor,

    setup: function () {
      // required to trigger test loading
      window.__moduleBundler.loadTests();
    },

    debug: true
  };
};
```

### Code editor or IDE name and version

IntelliJ IDEA v15
Visual Studio Code v1.x

### OS name and version
OSX Serria

Thanks.

**Comment by ArtemGovorov** [comment]
Thanks for the repo!

I have sent you [the pull request](https://github.com/dnatag/wallaby-ng1-typescript-webpack/pull/1). It wasn't working because the project is using both angular template module compilation and template imports (like `template: require('./header.html')`). 

You were very close though. The `wallaby-ng-html2js-preprocessor` preprocessor [renames `.html` files to `.html.js`](https://github.com/sheltonial/wallaby-ng-html2js-preprocessor/blob/master/index.js#L36), so while template cache is populated correctly as you said, webpack later on can't find `.html` files (because the are renamed) and fails to process stuff like `template: require('./header.html')` (because `header.html.js` doesn't export anything). So the missing bit of the puzzle was just to export the HTML from the preprocessed `.html.js` files, and that's what I did in the pull request.
