### ISSUE TITLE
Show failing tests for collapsed code in Intellij

### ISSUE THREAD

**Issue by maxklenk** [wallabyjs/public#97]
When using code folding WallabyJS should update the line indicator to show if the code in all collapsed lines is valid. The following example shows that it is difficult to see which test to fix.

![image](https://cloud.githubusercontent.com/assets/3898310/7460687/3cbb35cc-f2a5-11e4-9917-b4a2d97a2a48.png)
(the tests are the same and for sure both fail)

**Comment by ArtemGovorov** [comment]
Line indicator reflects the state of a particular line. I'm a bit worried that making it reflect the state of a collapsed region may be confusing. Also, would you like the aggregated indicator to consider the coverage as well, like becoming grey if nothing inside the collapsed region is covered or yellow if only some of the lines in it are covered? 

Regarding the visibility of tests to fix, I think using the "Failing tests" tab works better for this scenarios as a universal way to find failing tests and jump there. Generally, collapsed or not, some tests may start failing anywhere in the opened file or other files.

**Comment by maxklenk** [comment]
Sure you are definitively right that searching for failing test in project will not be done using this method.

But still a green point shown next to a collapsed region with failing or uncovered code is misleading. Perhaps my problem with the current behavior is that other functions which lead to an error are marked in pink, but the `it()` row is not.

![image](https://cloud.githubusercontent.com/assets/3898310/7469468/29850a0e-f314-11e4-8a99-0db4337cf09f.png)

**Comment by ArtemGovorov** [comment]
It's because `it()` function for wallaby is not different from any other function. Green in this context means that the call itself is successful (basically means that your test is registered with your testing framework successfully). But the actual test scope is another function (passed to `it` as a second argument) and it's pink because the error occurred in its scope (not in the the scope of the `describe` function where `it` is invoked). Having said that, `it` can be also be red/yellow/grey:

![screen shot 2015-05-05 at 6 59 38 pm](https://cloud.githubusercontent.com/assets/979966/7469672/8e0e1412-f359-11e4-8ae6-25f51794cbd8.png)

It also may be helpful when understanding what code is executed in your test file.

**Comment by maxklenk** [comment]
Thank you for explaining, you are right the highlighting of the it function works and should not be changed. You said:
> I'm a bit worried that making it reflect the state of a collapsed region may be confusing. 

But actually the editor changes the visual content of a line when collapsing it, it shows the whole block "in one line"(see the image i posted first). This way the line indicator would be wrong in this case.

Btw, this is not a crucial feature for me, I can work without it very well, but I think it would improve wallabyjs.

**Comment by ArtemGovorov** [comment]
Thanks, I'll have a look into the ways of both preserving the original indicator and somehow reflecting the collapsed region state into account as well (perhaps by showing a second indicator?)

**Comment by fvanwijk** [comment]
I have another example which shows some inconsistent behaviour

![collapsed lines](https://cloud.githubusercontent.com/assets/963136/7470472/b2d9b792-f31d-11e4-8273-ab6c88cc554c.png)

* Test A: the `it` at line 1 is registering the test (green), the expectation at line 1 fails (red) -> red
* Test B: the `it` at line 2 is registering the test (green), the expectation at line 3 fails (red) -> green
* Test C: the `it` at line 4 is registering the test (green), the test function at line 4 has been called, but the `false` has not (yellow) -> yellow 
* Test D: the `it` at line 5 is registering the test (green), the test function at line 5/6 has been called (green), the `false` at line 6 has not (grey), the function at line 6/7 has not (grey) -> green/grey/grey

The current behaviour is that if something fails (exception or failing test) or when there is partial coverage, this is overriding al markers by making the line red resp. yellow, in this order. I think this is good behaviour in terms of UX.

However, this is not done for collapsed lines, which are visually interpreted by the user as something like 'all lines are converted to 1 line', which I find inconsistent. Also the collapsed lines which have partial coverage.
I like the idea of showing two colored squares for collapsed lines, so if you do this for test B as well, the inconsistency is solved.

**Comment by MicahZoltu** [comment]
To expound a bit on why this is problematic:  In general, I browse code with everything fully collapsed/folded and only expand functions/blocks if I need to drill into them.  If I have a failing test, I will often use the coverage indicators as a very quick mechanism for debugging the test by looking to see what code path the test took.  Very often by just looking at the code path taken by the failing test (by looking for pink coverage markers) I can identify the problem (e.g., "oh, it should not have branched here... looks like my if statement is inverted").

However, because I have all of my code collapsed by default, I have to manually navigate through the code because any function that has a line that isn't covered by the test won't show up as pink when collapsed.  This usually leads to me unfolding everything, memorizing the pink links, then folding everything and expanding the lines that I remember as being pink.  Obviously, this is prone to error.

My personal preference would be to have the "worst case" dot for the collapsed code be the dot for that code.  I believe this is what `nCrunch` does (similar product for C#/Visual Studio).  To me, the order of impact would be red > pink > yellow > grey > green.  However, for collapsed code, I think yellow would make more sense if there is a mix of grey & green in the collapsed region, as that is what this color already represents.  So the order would in reality be red > pink > yellow|grey|green where grey is chosen only if _all_ lines in the region are grey and green is chosen only if _all_ lines in the region are green.

**Comment by ArtemGovorov** [comment]
@MicahZoltu I definitely like the idea, thanks for sharing! We'll investigate it, but the last time we checked the issue was that almost all of the editors that we support (except Visual Studio) simply don't let plugins to query the collapse state and to subscribe to the collapsed/expanded events.

**Comment by NikGovorov** [comment]
Hi All,

We recently improved how wallaby handles test declaration lines coverage indicators: if a test fails then the test declaration line's indicator is red.

![ScreenClip](https://user-images.githubusercontent.com/129254/77501855-eaba6f00-6ea4-11ea-9d6f-bbe488b358e9.png)

Please let us know if it does not work for you and want to keep the issue opened or create a new one.
