### ISSUE TITLE
Coverage for generator functions seems to be missing

### ISSUE THREAD

**Issue by rmevans9** [wallabyjs/public#978]
I am setting up a React Native project and playing with Wallaby.js and seeing how it plays with Redux Saga. Everything is going very well except that it seems coverage is unavailable for generator functions. I can run tests and assert them just fine but VSCode and the Wallaby.js app does not show the function as covered lines. Is there any way to get coverage working for generator functions as a large amount of what I will be testing with Wallaby.js is going to be Redux Sagas

### Wallaby.js configuration file

```javascript
module.exports = (wallaby) => ({
    files: [
        'app/**/*.js',
        { pattern: 'package.json', instrument: false },
        '!app/**/*.test.js',
    ],
    tests: [
        'app/**/*.test.js',
    ],
    env: {
        type: 'node',
    },
    compilers: {
        'app/**/*.js': wallaby.compilers.babel(),
    },
    testFramework: 'jest',
    setup: () => {
        wallaby.testFramework.configure(require('./package.json').jest);
   },
});
```

### Code editor or IDE name and version
Visual Studio Code v1.8.1

### OS name and version
macOS 10.12.2

**Comment by ArtemGovorov** [comment]
Just took a sample code from the Redux Sagas readme and pasted it into a test file. All indicators are correctly displayed for me for for generator functions (grey because I'm not invoking them): 
<img width="579" alt="screen shot 2017-01-27 at 2 26 38 pm" src="https://cloud.githubusercontent.com/assets/979966/22360563/a8357b4c-e49c-11e6-86a8-ca9240d87460.png">
Could you please share a sample repo where it doesn't work for you?

**Comment by rmevans9** [comment]
Hey @ArtemGovorov! Thanks for the quick response.

https://github.com/rmevans9/wallabygentest/tree/master/app

I put a testing.js and a testing.test.js in the app folder with some really really basic stuff. In my VSCode the generator does not show any block at all as your screenshot does. Playing around with options if I setup wallaby to ignore the babelrc it does add the coverage block but fails to run the test since it isn't handling ES2015 imports. I feel like this issue might be with how Wallaby, Babel and React Native interact. I am going to try and manually specify the plugins to get the tests running without using the React Native preset in babel and see what happens then.

**Comment by rmevans9** [comment]
Even more odd is the fact that if you setup the test to step through the generator it seems to figure out the coverage for any non generator function called by the generator.

![screen shot 2017-01-27 at 7 06 09 am](https://cloud.githubusercontent.com/assets/14151327/22370366/1edb566a-e45f-11e6-89f7-94cc8f2f67f1.png)

**Comment by rmevans9** [comment]
It is something within the react-native babel preset. A simple test of just the plugin to make ES2015 imports work makes the coverage show:

![screen shot 2017-01-27 at 7 10 21 am](https://cloud.githubusercontent.com/assets/14151327/22370511/bff160ee-e45f-11e6-987b-eb0f14462adf.png)

I don't know that is a valid workaround though because if I am going to test some of the components I would suspect that I would need to bring in the full list of plugins included with the preset which would likely cause the same issue.

Last test will be to start working through the plugins to figure out when it breaks.

**Comment by rmevans9** [comment]
Found it - it seems if you remove the `retainLines: true` from the babel-preset-react-native/configs/main.js file coverage suddenly starts working in generator functions. Not sure if this is something you guys want to address but it seems just simply overriding this for running wallaby the issue is resolve. Note: I haven't run any large "real" tests with this so jury is out on if this will really work or not yet.

![screen shot 2017-01-27 at 7 28 04 am](https://cloud.githubusercontent.com/assets/14151327/22370947/2a9565e2-e462-11e6-9d43-075e61bd949c.png)

**Comment by ArtemGovorov** [comment]
@rmevans9 Wow, thanks a lot for the repo and the issue analysis! After some investigation, we decided to set the `retainLines` to `false` in wallaby (can be overridden in wallaby config, but not by individual presets). We are already doing it for the `sourceMaps` setting (if we weren't, the preset would break not just the generators, but everything because the reset [disables the source map generation for some reason](https://github.com/facebook/react-native/blob/master/babel-preset/configs/main.js#L49)). 

The fix is published in [the latest core](https://wallabyjs.com/docs/intro/troubleshooting.html#forcing-wallabyjs-core-update). After the update, everything should work for you now as expected (we do have a few happy users using wallaby with react native) with the compiler setting like this:
```javascript
    compilers: {
        'app/**/*.js': wallaby.compilers.babel(),
    },
```

Thanks for the report and the investigation, much appreciated.
