### ISSUE TITLE
Wallaby not started on Sublime Text 3

### ISSUE THREAD

**Issue by ipostol** [wallabyjs/public#979]
### Issue description or question

Hello, after i am try reinstall wallaby and sublime text3 have problem with non started wallaby.
I am use "calculator-sample" project for try wallaby.

1 day ago, before i am try reinstall wallaby, all works fine.

This is error in console
```js
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 452, in <lambda>
    run_callback('on_close', callback, lambda: callback.on_close(v))
  File "<string>", line 204, in on_close
  File "<string>", line 579, in stop
  File "<string>", line 919, in cleanAllMarks
AttributeError: 'Wallaby' object has no attribute 'marks'
[warning]: Wallaby.js is not started
```

I am 3 times reinstall sublime text 3, clear all subfolders, remove Application Support/Sublime Text 3, but this don`t helps for me.

### Wallaby.js configuration file

```javascript
module.exports = () => {
  return {
    files: [
      'style/calculator.css',
      {pattern: 'lib/jquery.js', instrument: false},
      'src/*.js',
      'test/helper/template.js'
    ],
    tests: [
      'test/*Spec.js'
    ],
    debug: true,
  };
};

```

### Code editor or IDE name and version

Sublime Text v3

### OS name and version

OSX

**Comment by ArtemGovorov** [comment]
Hello, we didn't change the wallaby Sublime package for a couple of weeks, so the issue is likely in your local environment.

Did you install any new Sublime packages recently? Perhaps there were some other configuration changes?

Try looking for other errors in the Sublime console, may be there're some more wallaby related errors.

Also try changing your `Wallaby.sublime-settings` (`Preferences - Package Settings - Wallaby - Settings User`) file like this:
```
{
	"debug": true
}
```
and restart it. It should add some additional debugging output to the Sublime console, please paste the full output here.

**Comment by ipostol** [comment]
Wow, 

Sorry i am set in node_modules/jsdom/ some file as wallaby.config,
after i am remove them from Settings User all works fine.

Thank you for help
