### ISSUE TITLE
How about typescript 1.5 support?

### ISSUE THREAD

**Issue by rossross** [wallabyjs/public#99]

**Comment by ArtemGovorov** [comment]
Wallaby supports TypeScript 1.5 (was using 1.5 alpha package, today is has been updated to 1.5 beta).

![screen shot 2015-05-07 at 2 36 58 pm](https://cloud.githubusercontent.com/assets/979966/7508614/8c62d418-f4c6-11e4-8ca4-072998ef61f8.png)

Are your experiencing any issues with the feature?

**Comment by rossross** [comment]
Yeah, it's not able to support es6 style module loading.

**Comment by ArtemGovorov** [comment]
In the repository wallaby is configured to run in browser (PhantomJs). [ES6 modules](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#es6-modules) are just syntactic sugar over [external modules](https://github.com/Microsoft/TypeScript/wiki/Modules#going-external) and TypeScript converts them to CommonJs require/exports, so when browser environment tries to run it, it can't find `exports`, `require`, etc. variables.

If you are using TypeScript ES6 modules in your node.js app, you may change your config:
``` JavaScript
module.exports = function (w) {

  return {
    files: [
      'src/*.ts'
    ],

    tests: [
      'test/*Spec.ts'
    ],

    env: {
      type: 'node'
    },

    compilers: {'**/*.ts': w.compilers.typeScript({module: 1})}

  };
};
```
to let wallaby know that you are using node.js and it will work (the test in the repo will still fail because it uses jasmine `expect` and in node.js wallaby uses mocha by default, so may need to [install and require](https://github.com/wallabyjs/wallaby-node-iojs-sample/blob/master/test/calculatorSpec.js) `expect` lib instance)

If you are using TypeScript ES6 modules in your browser app, you have to either tell TypeScript compiler to generate JavaScript code using an alternative module format, [for example AMD](https://github.com/Microsoft/TypeScript/wiki/Modules#going-external), if I'm not mistaken it is `module: 2`, so wallaby.js compiler config would look like: `compilers: `{'**/*.ts': w.compilers.typeScript({module: 2})}`. You'll then have to use require.js, that [is supported by wallaby](https://github.com/wallabyjs/wallaby-requirejs-sample).

Another option is to keep CommonJs format and use a module bundler, such as browserify or webpack, with corresponding transformer or loader for TypeScript. Wallaby.js supports both [browserify](https://github.com/wallabyjs/wallabify) and [webpack](https://github.com/jeffling/wallaby-webpack) if you select this option.

**Comment by rossross** [comment]
Thanks for the detailed response. I solved it.
