### ISSUE TITLE
Using rootrequire with wallabyjs

### ISSUE THREAD

**Issue by PaddyMann** [wallabyjs/public#994]
### Issue description or question

We use the `rootrequire` module to support us in importing files relative to the root directory.

All this module does is create an absolute path (which it works out based on its own location).

When using wallabyjs, I've found that the babel compiler doesn't seem to hit the files imported this way. Additionally, it looks like wallabyjs may import certain files twice - once using a relative path and once using an absolute path.

Is there an easy way to get this all set up and working?

**Comment by ArtemGovorov** [comment]
Wallaby.js is using [its own file cache](https://wallabyjs.com/docs/intro/how-it-works.html#wallabyjs-cache) to instrument files/run tests, so the `root-require` module breaks it because it's pointing back to the original project folder, that's why it loads files that were not compiled by babel compiler.

There's a very easy way to get it working. You may just one-line patch `root-require` module to point it to the wallaby cache in your config [setup function](https://wallabyjs.com/docs/config/bootstrap.html):

```javascript
    setup: function (w) {
      require('root-require');
      require.cache[require.resolve('root-require')].exports = function (modulePath) {
        return require(require('path').join(w.projectCacheDir, modulePath));
      };
    },
```

Let me know if this works for you.

**Comment by PaddyMann** [comment]
Thanks for the help @ArtemGovorov 

Unfortunately this doesn't work. After implementing, `rootrequire` returns a function rather than the project root path. I've tinkered around but haven't been able to come up with a working solution.

Note: In your example code, you've required `root-require` rather than `rootrequire` (2 different packages).

**Comment by ArtemGovorov** [comment]
@PaddyMann Sorry, I have mistakenly made it work for the [`root-require` module](https://www.npmjs.com/package/root-require), as opposed to the [`rootrequire`](https://www.npmjs.com/package/rootrequire). Anyway, just tried the same idea, and here's the working implementation for the latter:

```javascript
    setup: function (w) {
      require('rootrequire');
      require.cache[require.resolve('rootrequire')].exports = w.projectCacheDir + require('path').sep;
    }
```

**Comment by PaddyMann** [comment]
The above didn't seem to have any impact, but moving it into the `bootstrap` function fixed it.

Thanks for your speedy and v useful help @ArtemGovorov !

**Comment by ArtemGovorov** [comment]
Oh, that explains it. 'setup' and 'bootstrap' are alias of the same thing, so only one of them is used.

Thanks for the update!
